- src/vmm/src/resources.rs
- src/vmm/src/rpc_interface.rs
- tests/integration_tests/build/test_coverage.py
- tests/integration_tests/functional/test_snapshot_basic.py
Creating diff snapshot fails when the target microVM's config has `enable_diff_snapshots` off.  Even if the operation fails, snapshot files are still created.
Added a check at the beginning of the snapshotting operation. If `diff` snapshot is requested and `enable_diff_snapshots` is disabled in the machine configuration, a `NotSupported(Diff snapshots are not allowed on uVMs with dirty page tracking disabled.)` error is displayed.
> Fix snapshot files being created when snapshot operation failed

- Cargo.lock
- resources/seccomp/x86_64-unknown-linux-musl.json
- src/arch/Cargo.toml
- src/cpuid/Cargo.toml
- src/cpuid/src/common.rs
- src/vmm/Cargo.toml
- src/vmm/src/builder.rs
- src/vmm/src/persist.rs
- src/vmm/src/version_map.rs
- src/vmm/src/vstate/vcpu/x86_64.rs
- tests/integration_tests/build/test_coverage.py
- tests/integration_tests/functional/test_snapshot_advanced.py
VMs restored from a snapshot might have the TSC frequency misaligned with the original, which could lead to problems further down the line. We took this as an opportunity to add snapshot compatibility checks, which start with adding the original TSC in the state file and scaling it for resumed VMs.
Added compatibility checks for snapshot create/restore, starting with TSC scaling.
> Add snapshot compatibility checks for snapshot create/restore

- tests/framework/report.py
`description` item needs to enable `from_docstring` in order to be populated when parsing the test's docstring.
Enabled `from_docstring` in the "description" `ReportItem`.
> test report: fetch description from docstring

- CHANGELOG.md
- docs/snapshotting/snapshot-support.md
- src/devices/src/lib.rs
- src/devices/src/virtio/vsock/device.rs
- src/devices/src/virtio/vsock/mod.rs
- src/vmm/src/device_manager/persist.rs
- tests/integration_tests/build/test_coverage.py
- tests/integration_tests/functional/test_vsock.py
Fixes #2218 .
Signed-off-by: berciuliviu <lberciu@amazon.com>
With this PR, we want to send the VIRTIO_VSOCK_EVENT_TRANSPORT_RESET event to the
vsock driver when we create a snapshot. The event is sent only if the device is active.
Send VIRTIO_VSOCK_EVENT_TRANSPORT_RESET by filling a descriptor in the
event queue and signaling an interrupt event to the driver.
> Send transport_reset event on vsock snapshot create path

- CHANGELOG.md
- docs/seccomp.md
- docs/seccompiler.md
- src/seccompiler/Cargo.toml
- src/seccompiler/src/common.rs
- src/seccompiler/src/compiler.rs
- src/seccompiler/src/lib.rs
- src/seccompiler/src/seccompiler_bin.rs
- src/vmm/build.rs
- tests/conftest.py
- tests/host_tools/cargo_build.py
- tests/integration_tests/performance/test_process_startup_time.py
- tests/integration_tests/security/test_custom_seccomp.py
- tests/integration_tests/security/test_seccomp.py
- tools/devtool
1. Considering the proposal of upstreaming the seccompiler library to rust-vmm,
the seccompiler binary used by Firecracker will need a slightly different name, so that
it doesn't clash with the library name.
2. Also, since the only use of the `--basic` flag of seccompiler-bin is to support Firecracker's `--seccomp-level 1`, which is deprecated, we are also deprecating the `--basic` flag.
3. Duplicated thread names in the JSON filter were allowed, due to the fact that the JSON spec doesn't forbid this. For the seccomp use case, however, it can result in undefined behaviour.
- rename the seccompiler binary to seccompiler-bin
- deprecate the seccompiler-bin `--basic` flag. It now displays a runtime warning when used.
- add a custom deserializer for the Json file that errors if there are …
> Rename seccompiler binary, deprecate --basic parameter and add extra thread name validation

- src/devices/src/virtio/block/device.rs
- src/devices/src/virtio/block/event_handler.rs
- src/devices/src/virtio/block/mod.rs
- src/devices/src/virtio/block/request.rs
- tests/integration_tests/build/test_coverage.py
Block device fixes and simplifications
Block device fixes and simplifications:
- fix the write_bytes metric
- fix the size of the block request status
- simplify the request status logic
> Block device fixes and simplifications

- src/devices/Cargo.toml
- src/devices/src/virtio/block/request.rs
- tests/integration_tests/build/test_coverage.py
Improve the testing of the block device emulation (#2480). This PR adds a property based that that validates properties in the block request parser output based on randomized input descriptor chains.
> Add property based test for block device Request::parse()

- tests/integration_tests/functional/test_api.py
Enhance negative testing for machine config's `mem_size_mib` field.
Added test cases to cover:
- mem_size_mib > usize::MAX
- mem_size_mib too large
- mem_size_mib = 0
> add negative tests for mem_size in machine config

- src/devices/src/virtio/vsock/unix/muxer.rs
Aims to close #2539
Renamed name-clashing variables to fix the bug and avoid the confusion in the future.
> Use the evset passed as a parameter instead of the one from connection

- docs/snapshotting/snapshot-support.md
We have recently added support for diff snapshots
for microVMs with vsock devices but the doc still
mentions that this is an unsupported scenario.
Removed outdated info from docs.
> doc: remove outdated vsock snapshot info

- docs/seccompiler.md
- resources/seccomp/aarch64-unknown-linux-musl.json
- resources/seccomp/x86_64-unknown-linux-musl.json
- src/seccompiler/src/backend.rs
- src/seccompiler/src/seccompiler_bin.rs
- tests/integration_tests/security/test_custom_seccomp.py
- tests/integration_tests/security/test_seccomp.py
- `arg_index` and `arg_type` redundantly include the `arg_*` in the name.
- the `kill` seccomp action was renamed in the kernel to kill_thread and a separate kill_process action was added.
- the `madvise(DONT_NEED)` is also triggered by some customer workloads but we don't know on which thread.
More details in the commit messages.
- renamed `arg_index` and `arg_type` to `index` and `type`
- rename kill actions to match the kernel
- allow madvise(DONT_NEED) on all thread categories, for safety.
> seccompiler: rename arg_index&arg_type, add KillProcess action and allow madvise on all threads

- tests/framework/artifacts.py
- tests/framework/matrix.py
- tests/framework/microvm.py
- tests/framework/stats/function.py
- tests/framework/utils.py
- tests/integration_tests/performance/configs/snap_restore_test_config.json
- tests/integration_tests/performance/test_snapshot_restore_performance.py
- tools/parse_baselines/main.py
- tools/parse_baselines/providers/snapshot_restore.py
The current snapshot restore tests are not enough to understand the impact on the restore latency of various variables in the VM configuration.
Added snapshot restore tests which measure the restore latency of VMs with variable configurations. The tests are scaling VCPU count, memory size, net device count and block device count, each individually over a base configuration of 1 VCPU 128MiB. We also test a configuration with the vsock and balloon devices enabled.
The tests are built on top of the existing performance test framework and come with a set of baselines, detailed in a config JSON file.
`[Reviewer TODO: Verify that these criteria …
> Add snapshot restore performance tests for scalable configurations

- tests/integration_tests/functional/test_balloon.py
The `deflate_on_oom` balloon tests are creating a 256MiB VM, inflating the balloon to 172MiB and then trying to allocate 32MiB of memory using the `fillmem` helper program. Depending on the `deflate_on_oom` balloon setting, the allocation should either succeed thanks to the balloon deflation making room for it, or fail by getting the helper program killed through the OOM killer.
On Intel x86_64 with the old kernel, the 172MiB inflation leaves the VM with about 29MiB of available memory, which is less than the amount the helper program wants to allocate, thus triggering the desired behavior.
A later version of the 4.14 kernel makes the VM lighter by about 4MiB, which means that, after the 172MiB inflation, the VM will have about 33MiB of available memory, which is slightly more than the …
> Adjust balloon tests for newer x86 kernel image

- src/devices/src/virtio/net/device.rs
- src/devices/src/virtio/vsock/event_handler.rs
Make event handling functions from vsock and tap field from net
pub so we can use them from fuzzer.
> [CI] Make handling functions and tap field pub

- tools/devtool
When you don't have a proper permission to mount ramdisk, the test suite won't issue a fatal error as mentioned in #2612. 
This PR adds check the status code of creating and mounting ramdisk so that test will die if you fail to mount it.
Before this PR, I tried to use docker `--mount type=tmpfs` option instead of adding the status check, but it had some performance regression (See #2655 ).
Close #2612 
It checks the status code of this command
```bash
mkdir -p ${DEFAULT_RAMDISK_PATH} && \
mount -t tmpfs -o size=${ramdisk_size} tmpfs ${DEFAULT_RAMDISK_PATH}
```
In order to check the status code I used `ok_or_die` command.
`[Reviewer TODO: …
> Abort test when failing to mount ramdisk

- src/devices/src/legacy/serial.rs
- tests/integration_tests/build/test_coverage.py
Fixes #2651 
This PR adds an extra check for the serial_input_fd before passing it to the event_manager register function. In this way, an error that should arise from the event_manager that the FD is invalid can be avoided.
> Check for serial_input_fd validity

- resources/seccomp/aarch64-unknown-linux-musl.json
- resources/seccomp/x86_64-unknown-linux-musl.json
- tests/conftest.py
- tests/integration_tests/security/demo_seccomp/Cargo.toml
- tests/integration_tests/security/demo_seccomp/src/bin/demo_panic.rs
- tests/integration_tests/security/test_seccomp.py
Whenever a panic happens, libc::abort is called. This function uses syscalls that are not allowed by the current seccomp filters.
Allowed these syscalls in order to allow the panics to finish cleanly.
> Allow syscalls used by Rust panic

- CHANGELOG.md
- src/vmm/src/default_syscalls/filters.rs
- tests/conftest.py
- tests/integration_tests/build/test_coverage.py
- tests/integration_tests/security/demo_seccomp/src/bin/demo_panic.rs
- tests/integration_tests/security/demo_seccomp/src/bin/seccomp_rules/mod.rs
- tests/integration_tests/security/test_seccomp.py
Whenever a panic happens, libc::abort is called. This function uses syscalls that are not allowed by the current seccomp filters.
Allowed these syscalls in order to allow the panics to finish cleanly.
Tested manually that the new filters allow for clean panics. The panic uses the same syscalls as in v0.25, as they are `libc::abort` dependent and not Firecracker implementation dependent, so the test on `main` branch should be sufficient to prove the validity of the new list in v0.24. 
> [v0.24] Allow syscalls used by Rust panic

- CHANGELOG.md
- src/vmm/src/default_syscalls/filters.rs
- tests/conftest.py
- tests/framework/decorators.py
- tests/framework/http.py
- tests/framework/utils.py
- tests/host_tools/cpu_load.py
- tests/host_tools/memory.py
- tests/integration_tests/security/demo_seccomp/src/bin/demo_panic.rs
- tests/integration_tests/security/demo_seccomp/src/bin/seccomp_rules/mod.rs
- tests/integration_tests/security/test_seccomp.py
- tools/devtool
Whenever a panic happens, libc::abort is called. This function uses syscalls that are not allowed by the current seccomp filters.
Allowed these syscalls in order to allow the panics to finish cleanly.
> [v0.23] Allow syscalls used by Rust panic

- docs/snapshotting/network-for-clones.md
If there was a connection before snapshot, we will also save the address
resolution information. If we delete the tap device and recreate it the
information will not be valid anymore because the tap device will have a new
mac address. The interval of time when packets are lost is due to ARP broadcast
packet being sent to all the hosts on the network requesting the physical 
hardware address for the host.
-> Added documentation update to drop arp tables before initiating a new connection
after restore if the tap device has been deleted.
-> Add integration test to check that we do not lose any packets after restore.
`[Reviewer TODO: Verify …
> Tap snapshot/restore integration test

- src/devices/src/legacy/serial.rs
This PR comes as an extension to solving issue #2651 and fixing `firecracker-go-sdk` builds failing. While we added an extra condition in Firecracker that would prevent the error from appearing, it seems the fc-go-sdk builds still fail.
The changes this PR brings are simple: changing an `error` log to a `warn` log. 
As we can observe [here](https://buildkite.com/firecracker-microvm/firecracker-go-sdk/builds/1875#533262e1-59ec-4e14-8ca1-b192698bc77b), fc-go-sdk builds are failing due to 
>"Running Firecracker v0.26-wip-13-g9e3c10fc\n2021-07-26T00:06:50.836452579 [UserSuppliedVMID:main:ERROR] 
> Failed to register serial input fd: event_manager: failed to manage epoll file descriptor\n" does not contain ":WARN]"
which means that the error keeps appearing and causes builds failure.
I have …
> Change serial_fd log from error to warn

- tests/integration_tests/functional/test_balloon.py
Using the new rootfs, the `test_size_reduction` balloon integration test failed due to an insufficient amount of memory reclaimed by inflating the balloon by 40 MiB on a 256 MiB VM.
This commit adjusts the inflate amount in the `test_size_reduction` balloon test to 160MiB so that we make sure the RSS drops below 100 MiB, making the assertions succeed.
> Adjust balloon integration test for newer x86 rootfs

- src/devices/src/bus.rs
- src/devices/src/lib.rs
- src/devices/src/virtio/balloon/device.rs
- src/devices/src/virtio/balloon/mod.rs
- src/devices/src/virtio/balloon/persist.rs
- src/devices/src/virtio/balloon/test_utils.rs
- src/devices/src/virtio/block/device.rs
- src/devices/src/virtio/block/event_handler.rs
- src/devices/src/virtio/block/mod.rs
- src/devices/src/virtio/block/persist.rs
- src/devices/src/virtio/block/test_utils.rs
- src/devices/src/virtio/device.rs
- src/devices/src/virtio/mmio.rs
- src/devices/src/virtio/mod.rs
- src/devices/src/virtio/net/device.rs
- src/devices/src/virtio/net/mod.rs
- src/devices/src/virtio/net/persist.rs
- src/devices/src/virtio/net/test_utils.rs
- src/devices/src/virtio/vsock/device.rs
- src/devices/src/virtio/vsock/event_handler.rs
- src/devices/src/virtio/vsock/persist.rs
- src/vmm/src/lib.rs
- tests/integration_tests/build/test_coverage.py
[virtio] code deduplication and simplifications
We move some logic to `DeviceState` in order to decrease code duplication.
We introduce `IrqTrigger` as an incremental improvement over the old approach where each device  was implementing a `signal_used_queue(&mut self)` method. This has 2 advatages:
1. We define this logic in one place in order to avoid code duplication
2. We can trigger a guest irq without borrowing the entire device. This
can lead to some code simplifications in the devices.
> [virtio] code deduplication and simplifications

- CHANGELOG.md
- docs/jailer.md
- docs/prod-host-setup.md
- src/jailer/src/env.rs
- src/jailer/src/main.rs
- src/jailer/src/resource_limits.rs
- tests/framework/jailer.py
- tests/integration_tests/security/test_jail.py
Defense in depth
Focused on two approaches:
- Provide jailer with default limits on the active resources without compromising legit user scenarios by placing aggressive constraints. The `--resource-limits` argument was added to the command line arguments accepted by jailer. This accepts a format similar to `--cgroup`, so that limits on resources ca be provided in the following format: `<resource=value>`. For example:
`--resource-limits fsize=1048575`
This argument can be used  multiple times to add multiple resource limits. Current available resource values are:
- `fsize`: The maximum size in bytes for files created by the process.
- `no-file`: Specifies a value one greater than the maximum file descriptor number that can be opened by this process.
- Update the documentation with …
> Jailer limits

- docs/network-setup.md
Signed-off-by: Bartosz Zbytniewski <bartosz.zbytniewski.dev@gmail.com>
It addresses https://github.com/firecracker-microvm/firecracker/issues/2620
This PR adds small note about TAP device IP address during networking setup.
> docs: Add note about TAP IP in networking setup

- tests/framework/report.py
- tests/framework/scheduler.py
Since the scheduler launches multiple processes to run tests, the test
report functionality was always reporting the last batch of tests.
This commit adds IPC communication for the report class so that all tests
are properly reported.
Thanks to @alindima for signalling this :+1: 
> fix reports being generated over multiple PIDs

- src/vmm/src/vstate/vcpu/aarch64.rs
- src/vmm/src/vstate/vcpu/mod.rs
- src/vmm/src/vstate/vcpu/x86_64.rs
Making the docs up-to-date.
Updating & fixing the documentation of both `Vcpu::new()` and `KvmVcpu::new()` which seem to be outdated. Also, removed a legacy description of a `vm_fd` argument.
> Fix docs of vcpu constructors

- src/devices/src/virtio/vsock/csm/connection.rs
- src/devices/src/virtio/vsock/device.rs
- src/devices/src/virtio/vsock/packet.rs
Avoid overflow during computing vsock packet used length.
Check package length before commiting the header to guest memory. If len is too big, we return `InvalidPktLen` error. 
> Avoid overflow on computing vsock packet used length

- docs/rootfs-and-kernel-setup.md
Fixes #2648
Added necessary details about manual compilation of a kernel built for booting Firecracker.
> missing step for aarch64

- resources/seccomp/aarch64-unknown-linux-musl.json
- resources/seccomp/x86_64-unknown-linux-musl.json
- tests/integration_tests/functional/test_api.py
When there is a large enough buffer there will be an attempt to map it using MAP_PRIVATE|MAP_ANONYMOUS. As mmap was not allowed with this flags on api_server thread the vmm was killed by seccomp filter.
-> Added rule to allow mmap with MAP_PRIVATE|MAP_ANONYMOUS
-> Added integration test.
> Fix seccomp

- Cargo.lock
Removed yanked crate dependencies (crossbeam-epoch and crossbeam-deque where both were an external dependency of criterion crate).
Ran `cargo update -p` on aforementioned dependencies. 
> cargo: removed yanked crate dependencies

- tests/integration_tests/functional/test_drives.py
The test_patch_drive_limiter was previously failing
intermittently on 3% of the cases.
This commit increases the accepted range from 20%
to 25% and adds 100% reliability.
> fix intermittent block rate limiter test failure

- src/vmm/src/builder.rs
- tests/integration_tests/performance/test_boottime.py
The initial timestamp passed to the boot-timer to calculate uVM boot time was taken after creating guest memory, loading the kernel, and loading the initrd. These should be included in the overall boot time.
Signed-off-by: Ben Holmes <bencwholmes@gmail.com>
Issue #2692
Moved the initial timestamp passed to the boot-timer to the beginning of  `build_microvm_for_boot()` to account for all steps in the build process. 
> Fix Boot Timer

- Cargo.lock
Crossbeam-deque and crossbeam-epoch crates are yanked.
Updated yanked crates.
> Update crossbeam crates 

- src/devices/src/virtio/block/device.rs
- src/devices/src/virtio/block/request.rs
- tests/integration_tests/build/test_coverage.py
[block] simplify unsafe flush behavior
Leverage the VIRTIO_BLK_F_FLUSH flag in order to avoid receiving flush
requests when the block device uses CacheType::Unsafe. This has 2
advantages:
1. It simplifies the request execution logic a bit
2. It improves efficiency when the block device uses CacheType::Unsafe
> [block] simplify unsafe flush behavior

- src/devices/src/virtio/balloon/mod.rs
- src/devices/src/virtio/balloon/test_utils.rs
- src/devices/src/virtio/block/mod.rs
- src/devices/src/virtio/block/test_utils.rs
- src/devices/src/virtio/net/mod.rs
- src/devices/src/virtio/net/test_utils.rs
- src/devices/src/virtio/test_utils.rs
- src/devices/src/virtio/vsock/test_utils.rs
Compile test_utils components always
Components from test_utils files could be used in some external projects that run are running a release binary of Firecracker. 
Removed `#[cfg(test)]` before test_utils because it contains
utilities that could be needed by external applications that
integrates firecracker that is not built in test mode.(i.e fuzzer).
> [tooling]: Make test_utils to be always compiled

- src/devices/src/virtio/block/device.rs
- src/devices/src/virtio/block/request.rs
- tests/integration_tests/build/test_coverage.py
Block - perform some validations when parsing the request
Addresses a comment from an older PR: https://github.com/firecracker-microvm/firecracker/pull/2629#discussion_r656187051
This simplifies the request execution logic which will make it easier for us to add io_uring support.
> Block - perform some validations when parsing the request

- CHANGELOG.md
- Cargo.lock
- resources/seccomp/aarch64-unknown-linux-musl.json
- resources/seccomp/x86_64-unknown-linux-musl.json
- src/api_server/Cargo.toml
- src/api_server/src/lib.rs
- src/dumbo/Cargo.toml
- src/dumbo/src/tcp/endpoint.rs
- src/firecracker/src/api_server_adapter.rs
- src/firecracker/src/main.rs
- src/mmds/Cargo.toml
- src/mmds/src/lib.rs
- tests/integration_tests/build/test_coverage.py
- tests/integration_tests/functional/test_cmd_line_start.py
Updated micro-http dependency to latest version which limits the payload size for PUT and PATCH requests.
-> consumed latest version of micro-http and updated API calls.
-> Added recvmsg on seccomp allowlist becase on upstream micro-http `read` call was replaced with `recv_with_fd`
-> Added cmdline parameter to customize the request upper limit.
> Update micro http

- Cargo.lock
- src/devices/src/virtio/block/device.rs
- src/devices/src/virtio/block/request.rs
- src/devices/src/virtio/device.rs
- src/devices/src/virtio/persist.rs
- src/devices/src/virtio/queue.rs
- src/firecracker/Cargo.toml
- src/jailer/Cargo.toml
- src/vmm/Cargo.toml
- src/vmm/src/device_manager/mmio.rs
- src/vmm/src/persist.rs
- src/vmm/src/version_map.rs
- tests/framework/artifacts.py
- tests/framework/utils.py
- tests/integration_tests/build/test_binary_size.py
- tests/integration_tests/build/test_coverage.py
- tests/integration_tests/functional/test_cmd_line_parameters.py
- tests/integration_tests/functional/test_snapshot_advanced.py
- tests/integration_tests/functional/test_snapshot_version.py
- tests/integration_tests/performance/test_snapshot_perf.py
#2635 
**Test setup:** We run on a m5d.metal host with Ubuntu and kernel 5.8.18. We start a number of microVMs with 8vCPUs and 16GB of RAM running linux kernel v5.8.18 as a guest OS. Each microVMs is pinned to NUMA node 1. We mount a ramdisk and we pin it to NUMA node 1 as well. For each microVM we create an ext4 file on the ramdisk and we attach it to the microVM as /dev/vdb. We want to have the content of the drives in the page cache in order to asses the performance improvement brought by notification suppression. Otherwise we would be limited by the disk access speed. Inside the VM we run the following command:
```
fio --name=test --ioengine=libaio --rw=readwrite --randrepeat=1 --bs=4k --size=500m --numjobs=1 --iodepth=32 --runtime=30 --time_base=1 --end_fsync=1 --direct=1 …
```
> [block] add support for notification suppression

- CHANGELOG.md
- docs/jailer.md
- src/jailer/src/cgroup.rs
- src/jailer/src/env.rs
- src/jailer/src/main.rs
- tests/framework/jailer.py
- tests/integration_tests/build/test_coverage.py
- tests/integration_tests/security/test_jail.py
Addresses #841 
This patch set adds the ability to use the jailer on systems that use cgroup-v2.
A new parameter named `--cgroup-version` was introduced in the jailer that enables the user to swap between using Cgroup-v1 and Cgroup-v2.
Hybrid mode is not supported as it is impractical for production use because controllers cannot be added to both v1 and v2 hierarchies at the same time. Typically on systems that use hybrid cgroups, all controllers are mounted to v1 hierarchies by default preventing controllers to be added to v2.
The default behaviour of the jailer (if `--cgroup-version` is not specified) is to use Cgroup-v1.
Using the jailer with `--cgroup-version 1` on a system that does not have Cgroup-v1 hierarchies mounted will result in an error. The same happens if `--cgroup-version …
> Add support for cgroups v2

- tools/devtool
Devtool capabilities were previously enhanced to include creating a draft release on GitHub. This PR adds an automated way to upload release artifacts to a previously created draft release.
Steps:
- call `tools/devtool upload_assets -v version -t token -a path_to_asset1 -a path_to_asset2 `
NOTE: This pull request DOES NOT add functionality to publish the draft release.
Added `upload_assets` devtool cmd to fetch URL of draft release associated to the version provided and upload assets to the draft. 
> [devtool]: upload assets to draft release on GitHub

- tools/devtool
The release devtool command requires `--username` argument
to be passed to specify the GitHub owner of the repo we want
to push the tag to. However, the name of the argument is confusing.
For a developer creating a release, it might seem that they must
provide the individual's username on GitHub, instead of the owner 
of the repo to push the tag/draft release to.
Changed the cli argument from `--username` to `--owner` to better reflect argument helper message and make this more intuitive.
> [tools] rename `--username` argument to `--owner`

- CHANGELOG.md
- docs/mmds/mmds-design.md
- src/api_server/src/lib.rs
- src/firecracker/src/api_server_adapter.rs
- src/mmds/src/data_store.rs
- src/mmds/src/lib.rs
- tests/framework/http.py
- tests/integration_tests/build/test_coverage.py
- tests/integration_tests/functional/test_mmds.py
- Make sure that MMDS data store size is less than the payload limit of requests.
- Limit MMDS data store size.
> Limit data store

- CHANGELOG.md
- docs/vsock.md
- src/api_server/src/lib.rs
- src/api_server/src/parsed_request.rs
- src/api_server/src/request/instance_info.rs
- src/api_server/src/request/mmds.rs
- src/api_server/src/request/version.rs
- src/api_server/src/request/vsock.rs
- src/api_server/swagger/firecracker.yaml
- src/devices/src/virtio/vsock/mod.rs
- src/logger/src/metrics.rs
- src/vmm/src/builder.rs
- src/vmm/src/device_manager/persist.rs
- src/vmm/src/resources.rs
- src/vmm/src/rpc_interface.rs
- src/vmm/src/vmm_config/vsock.rs
- tests/framework/resources.py
- tests/integration_tests/functional/test_api.py
`vsock_id` serves no purpose in our API, as the vsock device always has the same internal ID when registering it.
Deprecated the `vsock_id` field in PUTs on /vsock.
> Deprecate `vsock_id`

- docs/jailer.md
Jailer documentation is unclear regarding jailer intended usage.
Added disclaimer in jailer documentation stating that the jailer binary is intended to be used with Firecracker only.
> Clarify jailer usage in documentation

- src/devices/src/virtio/block/device.rs
- src/devices/src/virtio/block/io/async_io.rs
- src/devices/src/virtio/block/io/mod.rs
- src/io_uring/src/operation/cqe.rs
- src/vm-memory/src/lib.rs
- tests/integration_tests/build/test_coverage.py
[block] mark dirtied mem when executing io_uring ops
[block] mark dirtied mem when executing io_uring ops
> [block] mark dirtied mem when executing io_uring ops

- CHANGELOG.md
- Cargo.lock
- docs/jailer.md
- docs/mmds/mmds-design.md
- resources/seccomp/aarch64-unknown-linux-musl.json
- resources/seccomp/x86_64-unknown-linux-musl.json
- src/api_server/Cargo.toml
- src/api_server/src/lib.rs
- src/dumbo/Cargo.toml
- src/dumbo/src/tcp/endpoint.rs
- src/firecracker/src/api_server_adapter.rs
- src/firecracker/src/main.rs
- src/jailer/src/main.rs
- src/mmds/Cargo.toml
- src/mmds/src/data_store.rs
- src/mmds/src/lib.rs
- src/seccompiler/Cargo.toml
- src/seccompiler/src/seccompiler_bin.rs
- tests/framework/http.py
- tests/integration_tests/build/test_coverage.py
- tests/integration_tests/functional/test_cmd_line_start.py
- tests/integration_tests/functional/test_mmds.py
Backport significant commits from main to firecracker-v0.25.
Cherry-picked commits from main addressing the following:
- cargo update
- add MMDS data store size limit
- add cmd-line parameter to configure maximum payload size for MMDS patch requests
- clean-up environment variables in Jailer
- fix seccomp-bin being able to correctly report version by making use of `FIRECRACKER_VERSION` env variable
> [v0.25] Backport commits from main

- tools/devtool
Coverage tests overwrite binaries inside `release/` dir. Binary artifacts need to be copied before running the tests.
Copy release binaries and files before test run.
> [backport v0.25] 

- CHANGELOG.md
- docs/mmds/mmds-design.md
- src/firecracker/src/main.rs
- tests/integration_tests/functional/test_cmd_line_start.py
Max payload size parameter is not aligned with cmdline arguments' naming convention.
Renamed `--http_api_max_payload_size` parameter to `--http-api-max-payload-size`.
> rename max payload size cmdline argument

- src/devices/src/virtio/block/device.rs
- src/devices/src/virtio/block/event_handler.rs
- src/devices/src/virtio/block/io/async_io.rs
- src/devices/src/virtio/block/io/mod.rs
- src/devices/src/virtio/block/test_utils.rs
- src/io_uring/src/lib.rs
- src/io_uring/src/queue/submission.rs
- src/io_uring/tests/integration_tests.rs
- src/io_uring/tests/test_utils/mod.rs
- tests/integration_tests/build/test_coverage.py
[block] Use the async file engine in unit tests on kernel >= 5.10
[block] Use the async file engine in unit tests on kernel >= 5.10
> [block] Use the async file engine in unit tests on kernel >= 5.10

- CHANGELOG.md
- src/devices/src/virtio/block/device.rs
- src/devices/src/virtio/block/io/async_io.rs
- src/devices/src/virtio/block/io/mod.rs
- src/devices/src/virtio/block/mod.rs
- src/devices/src/virtio/block/request.rs
- src/devices/src/virtio/device.rs
- src/io_uring/src/lib.rs
- src/logger/src/metrics.rs
- tests/integration_tests/build/test_coverage.py
At the moment, if the io_uring submission queue is full we simply reject the block request, which is not correct. With the current queue size, this should not happen, but it's safer to handle this corner case.
When the io_uring submission queue is full we have to:
- undo the pop() operation from the block device virtio queue
- call process_queue() at the end of process_async_completion_evt()
Marking this PR as a draft until #2772 is merged since it's based on it.
> [block] Handle io_uring FullSq Error

- src/devices/src/virtio/block/io/async_io.rs
- src/io_uring/src/lib.rs
- src/io_uring/src/restriction.rs
- src/io_uring/tests/integration_tests.rs
- tests/integration_tests/build/test_coverage.py
io_uring exposes an alternative to syscalls, but without the ability of restricting the allowed list of syscalls via seccomp.
Starting with kernel 5.10, there is support for restrictions, an interface that enables a user to configure per-ring rules that are validated for each operation.
Installing restrictions require that we setup the ring in a disabled state and enable it after setting the restrictions.
For more context view the latest liburing man pages: https://github.com/axboe/liburing/blob/master/man/io_uring_register.2
and https://lwn.net/Articles/826053/
- add restrictions support in the io_uring crate
- add block async restrictions: only allow read,write and fsync on the pre-registered fds.
the terms of …
> [io_uring] add support for restrictions

- tests/framework/stats/core.py
- tests/integration_tests/performance/test_snapshot_restore_performance.py
We are using a global list to store the scratch drives info.
In function that makes the setup for block scaling test we
were changing the type of that global variable from list to
zip, thus in test function the list was seen as empty. Saved
the constructor result in an aux variable and unziped it in
the global variable to solve this issue. Also added catch
for AssertionError in run_exercise.
Fixes #
Changed the way we initialize the scratch drives list in performance test pipeline.
By submitting this pull request, I …
> [CI]: Fix snapshot perf test

- CHANGELOG.md
- docs/jailer.md
- src/jailer/src/cgroup.rs
- src/jailer/src/env.rs
- src/jailer/src/main.rs
- tests/framework/jailer.py
- tests/integration_tests/build/test_coverage.py
- tests/integration_tests/security/test_jail.py
Fixes #2788
Add ability to specify a custom parent cgroup where the microvm cgroup will be created.
This allows users to start microvms in cgroups that already have resource management configured.
In order to achieve this, a new parameter has been added to the jailer. `--parent-cgroup` allows for customisation of the path within the cgroup hierarchy where the microVM cgroup will be created.
- [N/A] Any API changes follow the [Runbook for Firecracker API changes][2].
> jailer: add parameter to specify custom parent cgroup

- CHANGELOG.md
- src/dumbo/src/tcp/endpoint.rs
- src/dumbo/src/tcp/handler.rs
- src/mmds/src/data_store.rs
- src/mmds/src/lib.rs
- src/mmds/src/token_headers.rs
- tests/integration_tests/build/test_binary_size.py
- tests/integration_tests/build/test_coverage.py
In order to be able to add IMDSv2 capabilities to Firecracker's MMDS, the backend needs to be able to process custom mmds-related headers. 
IMDSv2 uses session-oriented requests. With session-oriented requests, the guest creates a session token that defines the session duration and then uses that token for subsequent requests.
- Make use of micro-http's custom headers hash-map to fetch custom headers when processing the header of a request
- Add MMDS v2 headers:
`X-metadata-ttl-seconds` - used when fetching the session token to provide token lifetime in seconds
`X-metadata-token` - used to provide session token
`[Reviewer TODO: Verify …
> Add custom headers for MMDS requests

- CHANGELOG.md
- src/cpuid/src/cpu_leaf.rs
- src/cpuid/src/template/intel/c3.rs
- src/cpuid/src/template/intel/t2.rs
- tests/integration_tests/functional/test_cpu_features.py
There are a couple of new features that appear in the guests created with T2 and C3 cpu templates, on newer kernels (5.10).
**`umip`**
Newer KVM versions perform some CPU feature emulation in kernel space. These features are returned by `KVM_GET_SUPPORTED_CPUID` and `KVM_GET_EMULATED_CPUID`. Firecracker issues the `KVM_GET_SUPPORTED_CPUID` ioctl to get the set of features supported by the host plus the ones emulated by KVM. Firecracker then performs transformations on it, by masking specific features (like the ones for CPU templates), but it does not perform masking of features emulated by KVM.
This is the case for the `umip` feature.
**`avx512_vnni`**
In recent kernels, the code responsible for setting the cpuid features in kvm has had a redesign: https://lwn.net/Articles/811336/ …
> [main] cpuid: adapt templates for kernel 5.10

- CHANGELOG.md
- src/cpuid/src/cpu_leaf.rs
- src/cpuid/src/template/intel/c3.rs
- src/cpuid/src/template/intel/t2.rs
- tests/integration_tests/functional/test_cpu_features.py
Backport of https://github.com/firecracker-microvm/firecracker/pull/2795
Explicitly mask the aforementioned features
> [v0.25][backport] cpuid: adapt templates for kernel 5.10

- CHANGELOG.md
- src/vmm/src/builder.rs
- tests/integration_tests/build/test_coverage.py
- tests/integration_tests/functional/test_kernel_cmdline.py
Backports https://github.com/firecracker-microvm/firecracker/pull/2716 in v0.25
> [v0.25] Backport: kernel: fix bug in cmdline setup

- src/io_uring/src/lib.rs
The kernel memory associated to the rings was not getting freed upon freeing the io_uring resources.
The correct order is: `munmap` -> `close`
- enforce the correct order of destructor calls for the io_uring resources (by leveraging the rust order of `Drop` calls, which is well defined: https://doc.rust-lang.org/reference/destructors.html)
- misc change: fix the cqe `user_data` type on the io_uring proptest
> [feature/io_uring] Fix destructor call order

- tools/devtool
This is needed because the `io_uring_setup` system call
memlocks the rings and on some distros (e.g. ubuntu),
the default allowed limit is 65536, which only allows
creating up to 4 microVMs (based on the static size
of the rings).
We have tests which spawn more than 4 VMs, which would
otherwise fail with ENOMEM.
Set memlock unlimited on devtool `shell` and `test` commands
> devtool: set memlock:unlimited on container

- resources/seccomp/aarch64-unknown-linux-musl.json
- resources/seccomp/x86_64-unknown-linux-musl.json
- tests/framework/report.py
- tests/integration_tests/functional/test_api.py
- tests/integration_tests/functional/test_snapshot_basic.py
https://github.com/firecracker-microvm/firecracker/discussions/2811
- seccomp: allow mmap(MAP_PRIVATE|MAP_ANONYMOUS) on the vmm thread.
- add regression test for it
- fix error from commit https://github.com/firecracker-microvm/firecracker/pull/2701/commits/a3f5d47b063599e2eb73a116e537988de53b2929. The mmap call on aarch64 should have been allowed on the api thread, but was instead added to the vmm
> seccomp: fix large diff snapshot failure

- CHANGELOG.md
- src/jailer/src/cgroup.rs
- src/jailer/src/env.rs
- tests/integration_tests/security/test_jail.py
Fixes #2800:
Jailer's cgroup implementation considers that cgroup controllers and their associated properties follow the syntax of controller-name.property, both being separated by a dot.
However some cgroup controllers expose read/write properties that themselves contain dots that can be used to constrain the resource of a specific controller.
- Change jailer behavior to accept properties that contain multiple '.'
- ~[ ] The issue which led to this PR has a clear …
> cgroup: allow files containing multiple '.'

- docs/design.md
- docs/prod-host-setup.md
Fixes  #2785
Clearly mention that secure isolation and defense in depth can be
guaranteed only if prod-host-setup recommendations are implemented.
Remove the mention that Firecracker won't start without
the jailer in the future.
> Document Firecracker's defense in depth approach

- src/firecracker/src/main.rs
- src/vmm/src/resources.rs
- src/vmm/src/vmm_config/drive.rs
- tests/integration_tests/build/test_coverage.py
Fixes #2765
Adds an `std::fmt::Display` implementation for `vmm::resources::Error`
and uses it instead of the debug implementation when printing the error
in the CLI.
Here are is the error message before and after.
**Before:**
```bash
2021-10-29T15:14:13.216004769 [anonymous-instance:main:ERROR:src/firecracker/src/main.rs:321] Configuration for VMM from one single json failed: InvalidJson
```
**After:**
```bash
2021-10-29T15:37:12.523929871 [anonymous-instance:main:ERROR:src/firecracker/src/main.rs:444] Configuration for VMM from one single json failed: Invalid JSON: missing field `drives` at line 3 column 1
```
`[Reviewer TODO: Verify that these criteria are met. Request …
> Improve Display of VM Resource Errors

- tests/integration_tests/build/test_unittests.py
Superfluous musl unit testing on ARM.
We do not run musl unittests for x86 since
coverage will run them anyways with musl.
In the meantime, we also enabled coverage on
ARM so do the same for it too.
> [CI][build] do not run musl unittests for ARM

- src/devices/src/virtio/block/io/async_io.rs
- src/io_uring/src/lib.rs
- src/io_uring/src/operation/cqe.rs
- src/io_uring/src/operation/mod.rs
- src/io_uring/src/operation/sqe.rs
- src/io_uring/src/probe.rs
- src/io_uring/src/queue/completion.rs
- src/io_uring/src/queue/submission.rs
- src/io_uring/src/restriction.rs
- src/io_uring/tests/integration_tests.rs
- src/io_uring/tests/test_utils/mod.rs
- tests/integration_tests/build/test_coverage.py
Fixes https://github.com/firecracker-microvm/firecracker/issues/2759
Also adds some other minor refactoring: see the commits
See the commits
> io_uring: document public interface, limit visibility and rework unsafe usage

- src/devices/src/virtio/block/device.rs
- src/io_uring/src/lib.rs
- tests/integration_tests/build/test_coverage.py
- add negative block device unit test for invalid guest address.
> block: negative test for invalid guest address

- tests/integration_tests/functional/test_snapshot_advanced.py
Enable 2 tests from test_snapshot_advanced
that also make sense for aarch64. These tests
ensure snapshot compatibility across different
Firecracker versions.
Fixes #2784 
> CI: enable snapshot tests on ARM

- README.md
Currently this is not mentioned explicitly. Documentation states, that Firecracker may not run correctly on big endian, but doesn't have any reference to the guest.
With this PR, we are making clear that big endian guests are not supported.
Fixes #2826 
Mention in the README that Firecracker won't compile on big endian architectures, and it won't run correctly big endian guests. 
> Docs: mention that Firecracker doesn't support big-endian guests

- CHANGELOG.md
- src/api_server/src/lib.rs
- src/api_server/src/parsed_request.rs
- src/api_server/src/request/mmds.rs
- src/api_server/swagger/firecracker.yaml
- src/mmds/src/data_store.rs
- tests/framework/resources.py
- tests/integration_tests/functional/test_api.py
We need a way to configure MMDS version either to version 1 or to version 2.
Add a `/mmds/version` endpoint for configuring MMDS  version. The accepted values are `V1` or `V2` and it defaults on `V1`.
We also add a GET API request for `/mmds/version` endpoint to have a facile way of fetching current MMDS configuration used.
- ~[ ] The issue which led to this PR has a clear conclusion.~
- ~[ ] This PR follows the solution outlined in the related issue.~
- ~[ ] Any newly added `unsafe` code is properly documented.~
[2]: …
> [MMDS] add API to set MMDS version

- tests/framework/artifacts.py
- tests/integration_tests/functional/test_cmd_line_parameters.py
- tests/integration_tests/functional/test_snapshot_advanced.py
- tests/integration_tests/performance/test_snapshot_perf.py
Since io_uring snapshot support is now finalised, we no longer need to skip some tests that were being skipped due to
outdated artifacts in S3.
I've uploaded new binaries in S3 and now the tests pass.
However, the tests on the main branch would not pass with these artifacts so I created a separate temporary S3 folder for
the artifacts used on this branch.
We can remove the temporary folder in the PR that merges this feature branch into main.
View commit messages
> [feature/io_uring] Undo skipping some snapshot integration tests

- CHANGELOG.md
- tools/devtool
Fixes #601.
From now on, a checksum of the release artefacts will also get uploaded together with the corresponding release archive.
For a model of what the assets of each release will look like, checkout: https://github.com/dianpopa/firecracker/releases/tag/v0.26.0.
> Add checksum of release archive

- CHANGELOG.md
- src/firecracker/src/main.rs
- src/utils/src/arg_parser.rs
- src/vmm/build.rs
- src/vmm/src/seccomp_filters/mod.rs
- tests/integration_tests/security/test_custom_seccomp.py
- tests/integration_tests/security/test_seccomp.py
`--seccomp-level` was deprecated in Firecracker v0.25.0.
Given that we are preparing the v1.0.0 release, remove the deprecated parameter.
This also paves the way for consuming seccompiler from rust-vmm, as it removes the option for the `basic` option needed by `seccomp-level 1`.
The equivalent of seccomp-level 2 is the default for musl.
The equivalent of seccomp-level 0 is achievable by `--no-seccomp`.
The equivalent of seccomp-level 1 is achievable by using a custom filter.
- removes `--seccomp-level` parameter
[2]: …
> remove deprecated --seccomp-level param

- tests/framework/artifacts.py
Since the feature branch has been merged, I regenerated artifacts and uploaded them to the default S3 folder.
We can now roll back to using it instead the io_uring-specific one
> tests: remove tmp io_uring artifacts folder

- src/dumbo/src/pdu/ipv4.rs
- src/firecracker/src/api_server_adapter.rs
- src/mmds/src/data_store.rs
- src/mmds/src/token.rs
- tests/integration_tests/build/test_coverage.py
Small mmds fixes:
- include microVM instance ID into the AAD (Additional Authentication Data) used by the AES-GCM cipher when encrypting session tokens, which allows cryptographic code to add context information to the ciphering/deciphering processing.
- set TTL for MMDS response packets to 1
- AAD used by the AES-GCM cipher during encryption/decryption consists of a bytes sequence in the following format "microvmid=<microvm-id>"
- `DEFAULT_TTL = 1`
- ~[] The issue which led to this PR has a clear conclusion.~
- ~[] This PR follows the solution outlined in the …
> Small fixes for MMDS

- tests/integration_tests/performance/test_process_startup_time.py
Lately, intermittent perf fails were observed
on aarch64 on 5.10 for process start up time.
> CI: increase threshold for startup on ARM

- src/logger/src/lib.rs
- src/logger/src/logger.rs
- src/logger/src/metrics.rs
Due to previous refactorization, deny_docs
was left behind in what used to be the lib.rs
of the crate: logger/src/logger.rs.
Fixes #
> logger: move deny_docs to lib.rs

- src/devices/src/virtio/block/request.rs
Fixes a corner case for the block device.
Discard the virtio descriptor if we can't write the status byte.
> [block] fix corner case

- tests/framework/microvm.py
- tests/integration_tests/functional/test_api.py
- tests/integration_tests/functional/test_drives.py
- tests/integration_tests/functional/test_error_code.py
- tests/integration_tests/functional/test_shut_down.py
- tests/integration_tests/functional/test_snapshot_advanced.py
- tests/integration_tests/performance/test_boottime.py
- tests/integration_tests/security/test_custom_seccomp.py
* enforce sync mechanism on read/write of the log_data
* use `check_log_message` instead of directly accessing the log_data
Try to avoid situations like these: https://buildkite.com/firecracker/firecracker-x86-64-intel-kernel-4-dot-14-ci/builds/409#6bad3298-4bfe-4a54-8d59-c86e37830d8f
> Enforce sync mechanisms for accessing log data in CI

- src/mmds/src/token.rs
The unit test attempts to change just one byte from the payload or
tag sequences obtained after AES-GCM encryption, in order to
validate that such a change makes the ciphertext invalid.
Adding 1 to the first byte in the sequence might cause an
overflow. In order to fix this, we now replace the first byte
with its complementary value, which guarantees:
- sequence is changed (replacement value will never be equal to
the value replaced)
- will never overflow
Provided in the commit message output above.
Provided in the commit message output above.
`[Reviewer TODO: Verify that these criteria …
> mmds: fix faulty unit test

- src/cpuid/src/cpu_leaf.rs
- src/cpuid/src/template/intel/c3.rs
- src/cpuid/src/template/intel/t2.rs
IceLake introduced 5-level addressing, which appears as `la57` in the CPUID feature list if enabled. The templates should not present this feature.
Fixes #
Masked the feature in our CPUID templates.
> Mask IceLake `la57` feature in CPUID for templates

- docs/snapshotting/snapshot-support.md
[snap] update versioning documentation
Mention the fact that a new Firecracker release `v` might drop the
possibility to save snapshots at any versions older than `v`.
> [snap] update versioning documentation

- docs/rootfs-and-kernel-setup.md
- tools/devtool
Fixes #2831.
Use truncate instead of dd for allocating the rootfs
image. Also, make it clear in the doc that the format
of the size parameter is the same as that of truncates.
> devtool: fixes to build_rootfs

- README.md
- src/arch/src/aarch64/fdt.rs
The interrupt is not implemented by the pl031 device, but it is present in the device tree.
Removed the interrupt from the device tree, as it is not required (see [driver requirements](https://elixir.bootlin.com/linux/latest/source/Documentation/devicetree/bindings/rtc/arm,pl031.yaml)).
> Remove `pl031` interrupt from FDT

- CHANGELOG.md
- docs/jailer.md
- src/jailer/src/cgroup.rs
- src/jailer/src/env.rs
- src/jailer/src/main.rs
- tests/framework/jailer.py
- tests/integration_tests/security/test_jail.py
Fixes #2613
Remove the jailer --node parameter since it's duplicate functionality.
A user can set the numa node where Firecracker can run using the cpuset
cgroup controller.
- [] The issue which led to this PR has a clear conclusion.
- [] This PR follows the solution outlined in the related issue.
- [] Any API changes follow the [Runbook for Firecracker API changes][2].
> jailer: remove --node parameter

- src/vmm/src/device_manager/mmio.rs
We've removed the RTC device interrupt from the FDT
and we also no longer allocate an irqfd for it, so
we may safely remove the leftover allocated irq number.
View commit message
Remove the irq number allocation for the RTC device.
> IrqManager: don't allocate RTC interrupt number

- src/api_server/src/lib.rs
- src/cpuid/src/bit_helper.rs
- src/logger/src/logger.rs
- src/mmds/src/data_store.rs
- src/net_gen/src/iff.rs
- src/snapshot/src/lib.rs
- src/utils/src/net/ipv4addr.rs
- src/utils/src/sm.rs
- tests/integration_tests/style/test_rust.py
> rustfmt: format doc comments

- CHANGELOG.md
- docs/api_requests/block-io-engine.md
- Marks the `Async` block device io_engine as developer preview
- Adds docs about io_uring performance considerations in Firecracker
> io_uring: mark as dev preview and add perf documentation

- CHANGELOG.md
- src/api_server/src/lib.rs
- src/api_server/src/parsed_request.rs
- src/api_server/src/request/mmds.rs
- src/api_server/swagger/firecracker.yaml
- src/firecracker/src/api_server_adapter.rs
- src/firecracker/src/main.rs
- src/mmds/src/data_store.rs
- src/mmds/src/lib.rs
- src/vmm/src/resources.rs
- src/vmm/src/rpc_interface.rs
- src/vmm/src/vmm_config/mmds.rs
- tests/framework/resources.py
- tests/framework/vm_config.json
- tests/integration_tests/build/test_coverage.py
- tests/integration_tests/functional/test_api.py
- tests/integration_tests/functional/test_mmds.py
- Make MMDS V1 as default
- Configure MMDS version through `/mmds/config` instead of `/mmds/version`
- Remove `/mmds/version` endpoint
> Configure MMDS version through `/mmds/config` instead of `/mmds/version`

- src/mmds/src/token.rs
- src/utils/src/time.rs
This commit changes expiration time's unit of measure from seconds
to milliseconds. When computing expiry in seconds, if the request
to create a new token arrives at time X,999 seconds with a ttl=1s,
the token's expiry is computed to be X + 1 and the token ends up
having a lifetime of 0,0001 seconds instead of 1 second.
Computing expiry based on current time in milliseconds instead of
seconds provides greater precision.
Compute token's expiration time based on current time in ms instead of seconds and validate token's expiry based on its value in ms. …
> mmds: compute token's expiry in ms instead of seconds

- CHANGELOG.md
- src/api_server/src/parsed_request.rs
- src/api_server/src/request/mmds.rs
- src/api_server/src/request/net.rs
- src/api_server/swagger/firecracker.yaml
- src/devices/src/virtio/net/device.rs
- src/vmm/src/builder.rs
- src/vmm/src/device_manager/persist.rs
- src/vmm/src/persist.rs
- src/vmm/src/resources.rs
- src/vmm/src/rpc_interface.rs
- src/vmm/src/vmm_config/mmds.rs
- src/vmm/src/vmm_config/net.rs
- tests/framework/builder.py
- tests/framework/microvm.py
- tests/framework/resources.py
- tests/framework/vm_config.json
- tests/integration_tests/build/test_coverage.py
- tests/integration_tests/functional/test_api.py
- tests/integration_tests/functional/test_mmds.py
Provide a cleaner API for allowing MMDS requests on network interfaces. 
Also fixes #2174
- Add a `network_interfaces` field that takes a list of the network interface IDs capable of forwarding packets to the MMDS. Network interface IDs mentioned must be valid at the time of this request. The net device model will reply to HTTP GET requests sent to the MMDS address via the interfaces mentioned. In this case, both ARP requests and TCP segments heading to `ipv4_address` are intercepted by the device model, and do not reach the associated TAP device.
- Remove `allow_mmds_requests` from the body of the request that creates network interfaces. …
> Specify network interfaces that accept MMDS requests through `/mmds/config` API

- CHANGELOG.md
- docs/device-api.md
- docs/mmds/mmds-design.md
- docs/mmds/mmds-user-guide.md
Include documentation describing MMDS v2 behavior.
This PR is work in progress because it lacks specification regarding MMDS default behavior and version configuration.
> docs: update to include MMDS V2 behavior

- tools/devtool
Release artifacts must be copied before test run. These changes have been merged in v0.25 but missed on main.
> [backport][devtool] copy relase artifacts before test run

- CHANGELOG.md
- docs/device-api.md
- docs/getting-started.md
- docs/snapshotting/snapshot-support.md
- src/api_server/src/parsed_request.rs
- src/api_server/src/request/machine_configuration.rs
- src/api_server/swagger/firecracker.yaml
- src/cpuid/src/transformer/amd.rs
- src/cpuid/src/transformer/common.rs
- src/cpuid/src/transformer/intel.rs
- src/cpuid/src/transformer/mod.rs
- src/vmm/src/resources.rs
- src/vmm/src/vmm_config/machine_config.rs
- src/vmm/src/vstate/vcpu/mod.rs
- src/vmm/src/vstate/vcpu/x86_64.rs
- tests/framework/builder.py
- tests/framework/microvm.py
- tests/framework/resources.py
- tests/framework/vm_config.json
- tests/integration_tests/functional/test_api.py
- tests/integration_tests/functional/test_cpu_features.py
- tests/integration_tests/functional/test_logging.py
- tests/integration_tests/functional/test_topology.py
- tests/integration_tests/performance/test_snapshot_restore_performance.py
We plan on renaming/removing ht_enabled in a future release and this is a first step towards this without introducing a breaking change in this release.
Also, making it required did not make sense for ARM, where it actually does nothing if configured. Added an error for when it's configured as True on ARM.
View commits
> api: rename `ht_enabled` to `smt`, make it optional and forbid setting it to True on ARM

- tests/framework/jailer.py
- tests/framework/utils.py
- tests/framework/vm_config_with_mmdsv1.json
- tests/framework/vm_config_with_mmdsv2.json
- tests/integration_tests/functional/test_cmd_line_start.py
- tests/integration_tests/functional/test_mmds.py
Ensure MMDS works as expected (both default and V2) when spawning
microVM from a configuration file.
Enhance MMDS tests.
Add tests to ensure that MMDS works as expected when configuring microVM from file.
> tests: ensure MMDS works as expected when configuring microVM from file

- src/devices/src/legacy/serial.rs
- src/vmm/src/builder.rs
- src/vmm/src/lib.rs
- tests/framework/builder.py
- tests/integration_tests/build/test_coverage.py
- tests/integration_tests/functional/test_serial_io.py
After resuming from snapshot, the console is unresponsive.
* Set the RDA bit on serial after restore to kick the dive
* Added integration test for console functionality after restore
> Set RDA bit in serial after restore

- src/firecracker/src/main.rs
- src/firecracker/src/metrics.rs
- src/logger/src/metrics.rs
- src/vmm/src/signal_handler.rs
- tests/integration_tests/build/test_coverage.py
- tests/integration_tests/security/test_custom_seccomp.py
FIxes the root cause of intermittent failure of `test_custom_seccomp.py::test_failing_fiter`
View commit messages.
View commit messages.
> Fix signal handler race condition on metrics.write()

- src/vmm/src/vstate/system.rs
We are using KVM_CREATE_DEVICE to setup the
irqchip on ARM guests and not KVM_CREATE_IRQCHIP. Since
KVM_CAP_IRQCHIP is only mandated by the use of KVM_CREATE_IRQCHIP,
this means that on ARM we do not actually need to check for that
kvm capability.
For a detailed explanation check out kvm doc: https://elixir.bootlin.com/linux/v4.14.266/source/Documentation/virtual/kvm/api.txt#L659.
> kvm: KVM_CAP_IRQCHIP not needed on ARM

- CHANGELOG.md
- src/api_server/src/parsed_request.rs
- src/api_server/src/request/machine_configuration.rs
- src/api_server/swagger/firecracker.yaml
- src/vmm/src/builder.rs
- src/vmm/src/resources.rs
- src/vmm/src/rpc_interface.rs
- src/vmm/src/utilities/mock_resources/mod.rs
- src/vmm/src/vmm_config/machine_config.rs
- src/vmm/src/vstate/vcpu/mod.rs
- src/vmm/src/vstate/vcpu/x86_64.rs
- tests/framework/microvm.py
- tests/framework/vm_config_cpu_template_C3.json
- tests/framework/vm_config_missing_mem_size_mib.json
- tests/framework/vm_config_missing_vcpu_count.json
- tests/framework/vm_config_smt_true.json
- tests/integration_tests/build/test_coverage.py
- tests/integration_tests/functional/test_api.py
- tests/integration_tests/functional/test_cmd_line_start.py
Fixes several issues with machine_config:
- The following fields on machine-config: `vcpu_count` and `mem_size_mib` are mandatory when configuring via the API but optional when configuring from a JSON file.
- The CPU template and `smt` can be configured on ARM as well when starting from a JSON config. It only returns an error when using the API for config.
- If a machine_config PUT request is issued without the `track_dirty_pages` and the `cpu_template` parameters set, track_dirty_pages would be set to false but the cpu_template would remain unchanged.
- There is no way to reset the cpu_template through PUT or PATCH once it has been set with either of these methods.
- Patching track_dirty_pages was not allowed on aarch64 even though it is a pre-boot request.
This patch splits the actual …
> Machine config changes

- tools/create_snapshot_artifact/complex_vm_config.json
- tools/create_snapshot_artifact/main.py
- tools/devtool
Add `create_snapshot_artifacts` devtool command that creates snapshot artifacts for microVMs built from config file.
- ~[ ] The issue which led to this PR has a clear conclusion.~
- ~[ ] This PR follows the solution outlined in the related issue.~
- ~[ ] Any newly added `unsafe` code is properly documented.~
- ~[ ] Any API changes follow the [Runbook for Firecracker API changes][2].~
> Add tool to create snapshot artifacts for VMs built from config file

- src/vmm/src/device_manager/mmio.rs
- src/vmm/src/rpc_interface.rs
- tests/integration_tests/build/test_coverage.py
There were some leftover cfgs in tests that made them not run on arm.
Removed the cfgs to increase code coverage
> tests: remove cfg's that forbid runs on aarch64

- src/mmds/src/ns.rs
- tests/integration_tests/build/test_coverage.py
With a special crafted packet the speculative check from the `detour_frame` method could have been bypassed.
Fixes #
* Removes the speculative check of address from `detour_frame` method. 
* The address is now checked after the ethertype is verified.
* 
> Mmds remove speculative address check.

- CHANGELOG.md
- src/api_server/swagger/firecracker.yaml
- src/devices/src/virtio/net/device.rs
- src/devices/src/virtio/vsock/unix/muxer.rs
- src/mmds/src/ns.rs
- src/vmm/src/builder.rs
- src/vmm/src/device_manager/persist.rs
- src/vmm/src/persist.rs
- src/vmm/src/resources.rs
- src/vmm/src/rpc_interface.rs
- src/vmm/src/vmm_config/balloon.rs
- src/vmm/src/vmm_config/drive.rs
- src/vmm/src/vmm_config/net.rs
- src/vmm/src/vmm_config/vsock.rs
- src/vmm/tests/integration_tests.rs
- tests/framework/builder.py
- tests/framework/utils_cpuid.py
- tests/integration_tests/build/test_coverage.py
- tests/integration_tests/functional/test_api.py
Fixed the issue where GET /vm/config would return the default config for a VM restored from a snapshot. The config now updates after restoring from a snapshot.
This PR exists to fix the bug described in issue #2783. 
Changed restoring a snapshot to include updating the `VmResources` so that the correct config would be returned for the GET /vm/config endpoint. The only parts of the config that are still using default values after restoring a snapshot are the following:  boot-source (which is reasonable since there is no boot-source in the case of a restore), machine-config.smt and machine-config.cpu_template. 
`[Reviewer TODO: Verify that …
> Partial fix for restore snapshot GET /vm/config bug

- Cargo.lock
- src/rate_limiter/Cargo.toml
The rate_limiter has no dependencies on the libc.
Signed-off-by: wllenyj <wllenyj@linux.alibaba.com>
Remove the libc dependence.
> rate_limiter: remove unused dependencies

- Cargo.lock
- tests/integration_tests/build/test_coverage.py
`cargo audit` fails because `crossbeam-channel` v0.5.2 was yanked
recently. This commit updates Cargo.lock to fix the issue with this
dev-dependency.
Signed-off-by: Alexandru-Cezar Sardan <alsardan@amazon.com>
Fixes #
> Cargo.lock: update `crossbeam-channel`

- src/devices/src/virtio/net/persist.rs
- src/devices/src/virtio/net/test_utils.rs
- src/vmm/src/builder.rs
- src/vmm/src/device_manager/persist.rs
- src/vmm/src/resources.rs
- src/vmm/src/rpc_interface.rs
The mmds data store is initialised to a default even if
it is never used.
With this PR, the mmds data store is created on demand. View commit message for more info.
Also adapts unit tests.
> mmds: don't initialise data store unless used

- tests/integration_tests/functional/test_cmd_line_start.py
- tests/integration_tests/functional/test_snapshot_restore_cross_kernel.py
- tools/create_snapshot_artifact/main.py
These changes allow for better coverage for snap-restore testing and
can be reused to test cross-CPU snap restore compatibility.
Extend the functionality of the snapshot artifact creator tool in order
to create snapshots based on CPU templates.
Change the snapshot_restore_cross_kernel test to check restore
capability based on CPU template.
- [N/A] The issue which led to this PR has a clear conclusion.
- [N/A] This PR follows the solution outlined in the related issue.
- [N/A] Any newly added `unsafe` code is properly documented.
- [N/A] Any API changes follow …
> tests/snapshots: cross kernel test with cpu templates

- src/vmm/src/persist.rs
- tests/integration_tests/build/test_coverage.py
The page fault handler process requires FC's PID in order
to be able to notify FC of any crashes/exists. The way
we initially intended to make the handler process aware
of FC's PID was to have FC sent its PID explicitly through
the UDS. But there is a problem with this approach:
Firecracker's PID depends on the way the process was started.
When normally started through the jailer, Firecracker will
see its global PID. However, if using `--new-pid-ns` flag
when running the jailer, the jailer will spawn FC in a new
PID namespace, which would cause Firecracker to not be
aware of its PID and see it as being 1.
Moreover, when not using `--new-pid-ns` flag, we recommend
to the users to spawn the jailer process into a new PID
namespace when …
> Don't explicitly send FC's PID to the page fault handler

- CHANGELOG.md
- Cargo.lock
- docs/mmds/mmds-user-guide.md
- src/api_server/swagger/firecracker.yaml
- src/devices/src/virtio/net/persist.rs
- src/firecracker/Cargo.toml
- src/jailer/Cargo.toml
- src/mmds/src/ns.rs
- src/rebase-snap/Cargo.toml
- src/seccompiler/Cargo.toml
- src/vmm/src/builder.rs
- src/vmm/src/device_manager/persist.rs
- src/vmm/src/resources.rs
- src/vmm/src/version_map.rs
- tests/framework/artifacts.py
- tests/framework/resources.py
- tests/framework/utils.py
- tests/integration_tests/build/test_coverage.py
- tests/integration_tests/functional/test_cmd_line_start.py
- tests/integration_tests/functional/test_mmds.py
- tests/integration_tests/security/demo_seccomp/Cargo.lock
- tools/create_snapshot_artifact/main.py
- tools/devtool
Previously, there was no way of using MmdsV2 after a snapshot restore.
The mmds version is now persisted in the snapshot.
Make Mmds V2 Generally available.
Adds extensive integration tests.
> Persist mmds version in snapshot and make MmdsV2 GA

- src/devices/src/virtio/block/device.rs
issue https://github.com/firecracker-microvm/firecracker/issues/2951
Fixes:
```
warning: trailing semicolon in macro used in expression position
--> src/devices/src/virtio/block/device.rs:228:10
|
228 |         };
|          ^
...
394 |         let engine = unwrap_async_file_engine_or_return!(&mut self.disk.file_engine);
|                      --------------------------------------------------------------- in this macro invocation
|
= note: `#[warn(semicolon_in_expressions_from_macros)]` on by default
= warning: this was previously accepted by the compiler but is being phased out; it will become a hard error in a future release!
= note: for more information, see issue #79813 <https://github.com/rust-lang/rust/issues/79813>
= note: this warning originates in the macro …
```
> Removed the trailing semi-colon in `unwrap_async_file_engine_or_return`

- tests/integration_tests/functional/test_snapshot_restore_cross_kernel.py
- tools/create_snapshot_artifact/main.py
Cpu templates can only be used on Intel. Fix this logic so that we may run the test on other cpus as well
> test_snap_restore_cross_kern: use cpu_template only on intel

- CHANGELOG.md
- docs/mmds/mmds-user-guide.md
- src/api_server/src/request/mmds.rs
- tests/framework/utils.py
- tests/integration_tests/functional/test_mmds.py
> mmds: deprecate V1

- CHANGELOG.md
- src/api_server/swagger/firecracker.yaml
Signed-off-by: Lorenzo Fontana <fontanalorenz@gmail.com>
Fixes #2963
- Change the swagger definition to reflect the current state of the API
> api_server: VmmConfig swagger definition to reflect the actual state of the API

- src/api_server/src/lib.rs
- src/firecracker/src/api_server_adapter.rs
- tests/integration_tests/build/test_coverage.py
We have been observing intermittent failures for
test_start_with_metadata_default_limit. This comes
from a race possibility when the microVM is not
succesfuly built and thus there is no previous
blocking communication between the API thread and
Firecracker.
If that happens, we may run the risk of Firecracker trying
to connect to the socket path to trigger a graceful shutdown
of the API thread before the socket was actually created.
This test fixes a possible race condition and thus there is not
a short integration test that could exercise this path (we could add a patch over
the Firecracker binary but this is not quite feasible for the current framework).
The regression can be tested by running:
```
for i in {0..30}; do pytest -s …
```
> api: fix race in api connecting logic

- tests/framework/artifacts.py
- tools/devtool
Fix container image tag and ci-artifacts bucket
> Uffd: fix container image tag and ci-artifacts bucket

- src/api_server/src/lib.rs
- src/firecracker/src/api_server_adapter.rs
- src/firecracker/src/main.rs
- src/vmm/benches/main.rs
- src/vmm/src/lib.rs
- src/vmm/src/rpc_interface.rs
- src/vmm/src/signal_handler.rs
- src/vmm/src/vstate/vcpu/mod.rs
- src/vmm/tests/integration_tests.rs
See issue https://github.com/firecracker-microvm/firecracker/issues/2954
Using an enum with tagged variants instead of multiple constants to define exit codes.
```rust
/// Vmm exit-code type.
#[derive(PartialEq,Clone,Copy,Debug)]
enum FcExitCode {
/// Success exit code.
Ok = 0,
/// Generic error exit code.
CodeGenericError = 1,
/// Generic exit code for an error considered not possible to occur if the program logic is sound.
UnexpectedError = 2,
/// Firecracker was shut down after intercepting a restricted system call.
BadSyscall = 148,
/// Firecracker was shut down after intercepting `SIGBUS`.
SIGBUS = 149,
/// Firecracker was shut down after intercepting `SIGSEGV`.
SIGSEGV = 150,
/// Firecracker was shut down after intercepting `SIGXFSZ`.
SIGXFSZ = 151,
/// Firecracker was shut down …
```
> Using tagged enum variants for exit codes

- tests/integration_tests/functional/test_snapshot_advanced.py
This test does 2 things:
* Create a snapshot using Firecracker v0.24
* Restore that snapshot using the current build
Firecracker v0.24 is used here because the snapshot file does not
contain the TSC frequency. We do want to allow resume on the same
processor type without any TSC adjustment but since Firecracker
v0.24 is not supported anymore we need a different type of test to
do this validation.
Removed this test and added an issue to track the addition of a new type of test here: https://github.com/firecracker-microvm/firecracker/issues/2985
[1]: …
> tests/snapshots: remove test_restore_no_tsc

- tests/integration_tests/functional/test_snapshot_restore_cross_kernel.py
Tentative fix for the intermittent failure of tests/integration_tests/functional/test_snapshot_restore_cross_kernel.py in the CI.
When checking the functionality of the balloon device, we use an application to fault in some memory inside the guest, then try to reclaim some memory back using the balloon.
Make the balloon check function fault in and reclaim a more significant amount of memory such that the test does not get affected by other processes in the guest that are maybe using memory temporarily.
[2]: …
> tests/snap: make balloon checks more reliable

- tests/integration_tests/functional/test_uffd.py
`test_custom_seccomp.py` and `test_seccomp.py` are failing when preparing the release archive.
`spawn_pf_handler` changes the current working directory to `/`
which causes some tests that are run after this call to fail.
Revert to the correct working directory before exiting from
spawn_pf_handler.
> tests/test_uffd: revert to correct working dir

- src/api_server/src/request/net.rs
- src/vmm/src/vstate/system.rs
- tests/integration_tests/build/test_coverage.py
[Issue #2908](https://github.com/firecracker-microvm/firecracker/issues/2908) shows an example where configuring a network tap for a microVM run by a user without access to KVM will cause the firecracker process to close and returns an error that is quite vague.
Some potential options: 
1) Validate the user's access to the `/dev/kvm` device prior to attempting to fulfill the `InstanceStart` request. This would leave the firecracker process running and the API call could be re-attempted after configuring the file's ACL.
1) Add some detail to the error logged in response to the failed initialization of the `/dev/kvm` device.
Unfortunately the first option would likely require a system call which be executed for every `InstanceStart` API call (or possibly on the firecracker process' launch). …
> Clarify FC panic error message when missing user ACL for KVM device

- src/devices/src/virtio/block/io/async_io.rs
- src/logger/src/lib.rs
- src/vmm/src/rpc_interface.rs
A point raised in [PR/2976](https://github.com/firecracker-microvm/firecracker/pull/2976) is that it would be better to standardize the log level and message format for dev-preview lines,
This PR defines a dev-preview specific macro in the logger crate to standardize the logging and streamline the usage as well.
> Simplify dev-preview logging

- docs/snapshotting/snapshot-support.md
- src/devices/src/virtio/net/device.rs
- src/devices/src/virtio/net/mod.rs
- src/vmm/src/persist.rs
- tests/integration_tests/build/test_coverage.py
- tests/integration_tests/functional/test_mmds.py
- tests/integration_tests/functional/test_snapshot_advanced.py
- tests/integration_tests/functional/test_snapshot_version.py
Integrate notification suppression for the VirtIO net device (see issues: #2478, #2636) using functionality added for the 
equivalent block device feature (#2658).
Here I mainly used the machinery introduced by @serban300 for the corresponding block device feature. I ran a number of tests to evaluate performance impact.
My experimental setup is the following:
* I 'm using an `c5d.metal` instance
* I am using 48 cores to avoid using hyper-threading
* Each microVM has 5 vcpus and 4GB of memory (so that each microVM has 7 threads in total)
* I launch from 1-12 microVMs pinning them in cores and forcing them to allocate memory from the corresponding NUMA node, i.e. 6 microVMs fill up the available cores. Data points with more than 6 microVMs represent overcommit scenarios.
* Each microVM is …
> virtio-net: add support for notification suppression

- tests/framework/stats/function.py
Fixes these warnings when running the tests:
```
framework/stats/function.py:139
/firecracker/tests/framework/stats/function.py:139: SyntaxWarning: "is" with a literal. Did you mean "=="?
if len(result) is 1:
framework/stats/function.py:160
/firecracker/tests/framework/stats/function.py:160: SyntaxWarning: "is" with a literal. Did you mean "=="?
if len(result) is 1:
```
Fixes #
`[Reviewer TODO: Verify that these criteria are …
> Use == when comparing with an int literal

- Cargo.lock
- src/vm-memory/Cargo.toml
- tests/framework/utils.py
- tests/integration_tests/functional/test_api.py
- tests/integration_tests/style/test_gitlint.py
- tools/devctr/Dockerfile.aarch64
- tools/devctr/Dockerfile.x86_64
- tools/devctr/poetry.lock
- tools/devctr/pyproject.toml
- tools/devtool
Python 3.6 is reaching end of life and needs to be upgraded to version 3.7+.
Upgrading to 3.10.4 was started in [PR/3003](https://github.com/firecracker-microvm/firecracker/pull/3003) which upgraded the Ubuntu version of the container from 18.04 to 22.04. This resulted in a change to the Firecracker binary size that needs to be better understood before that upgrade can proceed. This change targets upgrading Python only and builds the runtime from source which is not ideal. This can ultimately be removed once the upgrade to 22.04 can be completed safely.
* Build and install Python 3.10.4 runtime
* Configure safe.directory to satiate git (via gitlint) file-system ownership checks
* Bump the vm-memory crate's version. vm-memory is now flagged as a side-effect of the update due to …
> Upgrade devtool container to use Python 3.10

- tests/integration_tests/build/test_coverage.py
Current code coverage error message is slightly inaccurate e.g.
```
E   AssertionError: Current code coverage (83.77%) is below the target (84.06%).
E   assert 83.76920450665756 >= 84.01
```
We are asserting we are not below `84.01` (`>= 84.01`) while the error message tells us we are asserting we are not below `84.06` (`>= 84.06`).
(same applies with above the target)
Enhanced error message to give:
```
E   AssertionError: Current code coverage (83.77%) is >0.05% below the target (84.06%).
E   assert 83.76920450665756 >= 84.01
```
(applied same change with above the target)
> Enhanced code coverage error message

- Cargo.lock
- src/vm-memory/Cargo.toml
- tests/framework/artifacts.py
- tests/framework/utils.py
- tests/integration_tests/build/test_coverage.py
- tests/integration_tests/functional/test_api.py
- tests/integration_tests/performance/test_versioned_serialization_benchmark.py
Maintenance changes to keep the v1.0 release branch stable and testable. Changes include:
* Bump internal crate vm-memory version to 0.3.0 - [Security advisory](https://rustsec.org/advisories/RUSTSEC-2020-0157) is being flagged for Firecracker due to a conflict between the internal crate and the external crate with the same name,  `vm-memory`. The internal crate's version for the firecracker main branch was bumped in [pr/3011](https://github.com/firecracker-microvm/firecracker/pull/3011). There isn't a security risk any more, but this is being done to resolve the call-out.
* Update test coverage targets.
* Fix test_api integ test that did not sanitize the FC version retrieved by the API.
* Fix FC artifact filter bug, that resulted in trying to restore snapshots with versions later than …
> Update v1.0 release branch with stability and security compliance changes

- CONTRIBUTING.md
- tests/framework/gitlint_rules.py
Add checks for commit body ending format, closes #3026 
Adds test for commit body ending format
that makes sure body ends with 'Signed-off-by' or 'Co-authored-by'
and no other trailing line
``` sh
1   │ A commit message
2   │
3   │ some message
4   │ some other message
5   │ Signed-off-by: someone@somewhere.com
```
``` sh
❯ cat gitlint_example_1 | gitlint -C .gitlint --extra-path tests/framework/gitlint_rules.py
```
-----------
``` sh
1   │ A commit message
```
``` sh
❯ cat gitlint_example_2 | gitlint -C .gitlint --extra-path tests/framework/gitlint_rules.py
1: UC2 Body does not contain a 'Signed-off-by' line
3: B6 Body message is missing
```
-----------
``` sh
1   │ A commit message
2   │
3   │ some other message
4   │ Signed-off-by: someone@somewhere.com
5   │ Co-authored-by: …
```
> CI: Add checks for commit body ending format

- Cargo.lock
- src/vmm/src/signal_handler.rs
- tests/integration_tests/build/test_coverage.py
We have been dealing with intermittent fails for `vmm::signal_handler::test_signal_handler` on AMD.
This happens in the cpu_count() function due. We are computing the number of cpus by getting the affinity mask of current process and then going through CPU_SETSIZE to count the number of cpus that hit the mask. 
Problem is that `libc:musl` has a maximum of CPU_SETSIZE equal 128 and  on AMD the maximum number of CPUS with SMT enabled is 192.
Fixes #2216 
The cpu_count was used as an trick for detecting whether or not the unit tests are run under `cargo test` or `cargo kcov` since cargo kcov would make it seem that there is only one CPU online.
We remove this workaround and introduce a environment variable CARGO_WRAPPER that can tell us what is the wrapper currently run by cargo.
While …
> Fix intermittent fail on AMD when getting cpu count

- Cargo.lock
- src/vm-memory/Cargo.toml
- tests/framework/artifacts.py
- tests/framework/utils.py
- tests/integration_tests/build/test_coverage.py
- tests/integration_tests/functional/test_api.py
- tests/integration_tests/style/test_gitlint.py
- tools/devctr/Dockerfile.aarch64
- tools/devctr/Dockerfile.x86_64
- tools/devctr/poetry.lock
- tools/devctr/pyproject.toml
- tools/devtool
[Security advisory](https://rustsec.org/advisories/RUSTSEC-2020-0157) is being flagged for Firecracker due to a conflict between the internal crate and the external crate with the same name,  `vm-memory`. The internal crate's version for the firecracker main branch was bumped in [pr/3011](https://github.com/firecracker-microvm/firecracker/pull/3011). There isn't a security risk any more, but this is being done to resolve the call-out.
(Change [made for Firecracker 1.0 branch](https://github.com/firecracker-microvm/firecracker/pull/3028))
> Update v1.1 release branch with stability and security compliance changes

- tests/integration_tests/functional/test_mmds.py
- tests/integration_tests/functional/test_snapshot_advanced.py
Due to notification suppression having been added
after v1.1.0, there is no past release that is snapshot
compatible with current one. 
This is tackling the scenario where past firecracker versions are not able to resume a microVM obtained with the current build.
Since the past firecracker versions cannot be aware of the features subsequent versions will implement, we do not have many options of offering a better compatibility check experience. It would be nice to brainstorm some ideas in that respect.
Fixes #
By submitting this pull request, I confirm that my contribution is …
> CI: fix snap incompatibility

- tests/conftest.py
- tools/devtool
We are now following the spectre-meltdown-checker
instruction for detecting full retpoline support.
We are checking the "retpoline" or "retpolines" are reported by
sysfs and that "minimal" is not.
> CI: intermittent spectre mitigation fail

- CONTRIBUTING.md
And Co-authored-by casing too since `gitline_rules.py` performs a case-sensitive check
Signed-off-by: Aaron O'Mullan <aaron.omullan@gmail.com>
> fix(CONTRIBUTING.md): Signed-off-by instructions

- src/arch/src/x86_64/msr.rs
Some Guest writtable MSRs are not saved in the snapshot which means that when the snapshot is resumed, software that was using those MSRs may not work properly.
Allow saving these additional guest writable MSRs to preserve
functionality after snapshot and resume:
* `MSR_MISC_FEATURE_ENABLES` to preserve CPUID fault
* `MSR_K7_HWCR` to preserve value written
* `MSR_KVM_POLL_CONTROL` to preserve HLT polling request
* `MSR_KVM_ASYNC_PF_INT` to preserve ASYNC PF interrupt vector
> arch/x86_64: save additional MSRs

- CHANGELOG.md
- Cargo.lock
- README.md
- src/api_server/swagger/firecracker.yaml
- src/arch/Cargo.toml
- src/arch/src/x86_64/msr.rs
- src/cpuid/Cargo.toml
- src/cpuid/src/cpu_leaf.rs
- src/cpuid/src/lib.rs
- src/cpuid/src/template/intel/mod.rs
- src/cpuid/src/template/intel/t2.rs
- src/cpuid/src/template/intel/t2s.rs
- src/vmm/src/vmm_config/machine_config.rs
- src/vmm/src/vstate/vcpu/x86_64.rs
- tests/integration_tests/build/test_coverage.py
Fix Guest CPU consistency issues when snapshotting and resuming uVMs across hosts with different CPUs.
The T2 template lets KVM populate the ARCH_CAPABILITIES MSR by using a
copy of the Host information. We sometimes want to force the information
contained in that MSR in order to make it look like a less capable
processor WRT speculative execution vulnerabilities and mitigations.
This is helpful when we want to snapshot a uVM on a newer processor and
resume on an older processor.
In this case, the software should use only the capabilities that are
available in both the newer and older host.
Create a new CPU template called T2S which is similar to the T2 template
but also sets additional information in the ARCH_CAPABILITIES MSR.
We basically set the MSR to expose to the guest a CPU that …
> cpu templates: add T2S templates

- CHANGELOG.md
- Cargo.lock
- README.md
- src/api_server/swagger/firecracker.yaml
- src/arch/Cargo.toml
- src/arch/src/x86_64/msr.rs
- src/cpuid/Cargo.toml
- src/cpuid/src/cpu_leaf.rs
- src/cpuid/src/lib.rs
- src/cpuid/src/template/intel/mod.rs
- src/cpuid/src/template/intel/t2.rs
- src/cpuid/src/template/intel/t2s.rs
- src/vmm/src/vmm_config/machine_config.rs
- src/vmm/src/vstate/vcpu/x86_64.rs
- tests/integration_tests/build/test_coverage.py
Backport 889b06807ca07425078e5aaf1fda9b9a84355bc5 and 839fe8e71acc5665b3905ae564cd18496791ab02 to Firecracker v1.1.
Backporting patches from the main branch.
> Backport CPUID and MSR patches from main

- tools/devtool
Running with EPT disabled can affect performance. 
Add a warning to `devtool checkenv` when EPT is disabled.
> Add EPT check to devtool checkenv

- tests/framework/utils.py
- tests/integration_tests/functional/test_api.py
- tests/integration_tests/style/test_gitlint.py
- tools/devctr/Dockerfile.aarch64
- tools/devctr/Dockerfile.x86_64
- tools/devctr/ctr_gitconfig
- tools/devctr/poetry.lock
- tools/devtool
This PR fixes the `test_api_version` which was broken due to this advisory:
https://github.blog/2022-04-12-git-security-vulnerability-announced/
- This PR adds a `gitconfig` file to the container that marks the `/firecracker` directory as safe. This way, both the tests and the `build.rs` build script can run `git describe --dirty` without failure when the dev container is run as privileged.
- Since this fix was added, remove the `configure_git_safe_directory` helper form the test framework since it's not needed and was a partial fix anyway.
- Also revert the `test_api_version` test behaviour to verify `git describe --dirty` output exactly vs the API output (which in turn should come by running `git describe --dirty` in `build.rs`).
- Since the dev container was re-generated and the …
> Fix API version tests and update development container

- docs/prod-host-setup.md
Signed-off-by: Ryan Russell <git@ryanrussell.org>
Correct `tc` usage example in production setup guide
Fix `tc qdisk` -> `tc qdisc` in `docs/prod-host-setup.md`
> docs(prod-host-setup): Fix `tc qdisc` reference

- tests/integration_tests/performance/test_network_latency.py
- tools/parse_baselines/main.py
- tools/parse_baselines/providers/latency.py
Enable baselines parsing for network latency
> enable baselines parsing for network latency

- tests/integration_tests/performance/configs/test_vsock_throughput_config_5.10.json
PR #3080 deleted 8175M Intel processor from vsock's
5.10 config file. This commit puts it back.
https://github.com/firecracker-microvm/firecracker/pull/3080/files#diff-d485d47397b9b4efd79ad0882361c81a815d93228d9245a441b7703597a04d99L516
Fixes #
> [perf] re-enable Skylake baselines in config

- tests/framework/stats/criteria.py
- tests/integration_tests/performance/configs/test_network_latency_config_4.14.json
- tests/integration_tests/performance/configs/test_network_latency_config_5.10.json
- tests/integration_tests/performance/test_network_latency.py
The network latency test was taking baseline values from a hardcoded dict inside the test file.
We need to be able to generate baseline values in config files so the test should use those instead.
Refactor the `test_network_latency` test in order to consume baseline
values from the config file and not from the hardcoded baselines.
Also add the packet loss measurement to the config files.
> tests/perf/net_latency: use values from config

- tests/integration_tests/performance/configs/test_network_latency_config_4.14.json
- tests/integration_tests/performance/configs/test_network_latency_config_5.10.json
- tools/parse_baselines/providers/latency.py
Latency performance baselines are currently incorrect.
Updates network latency performance baselines by adding baselines for all processors we test and adding the `pkt_loss` metric.
Also fix the `LatencyDataParser` in the `parse_baselines` script to correctly calculate the delta percentage.
> Update network latency performance baselines

- docs/snapshotting/snapshot-support.md
Extra comma causes JSON de-serialization to fail.
> Fix JSON syntax error in snapshotting docs

- .gitlint
- CHANGELOG.md
- docs/metrics.md
- src/api_server/swagger/firecracker.yaml
- src/firecracker/src/main.rs
- src/logger/src/metrics.rs
- tests/conftest.py
- tests/framework/microvm.py
- tests/integration_tests/build/test_coverage.py
- tests/integration_tests/functional/test_cmd_line_parameters.py
- tests/integration_tests/style/test_python.py
Metrics configuration are not saved in the snapshot since these are host related deployments settings. This means that after resuming, the only way to re-configure the metrics through an API call.
This can be costly for some customers since it will add up to the resume latency.
Add a CLI option to configure metrics
> Add --metrics-path option

- tests/framework/microvm.py
- tests/framework/resources.py
We are right now defaulting to use Async (io_uring)
for any test that does not explicitly sets a device engine.
That can lead to regressions (performance or otherwise) getting
obfuscated for the Sync engine (which is actually the only drive
engine that is currently GA).
I will post an ulterior PR with the peformance numbers updated for the snapshot and boottime tests since I think it is important to also have those numbers when testing with both Async and Sync.
[2]: …
> CI: remove Async default device configuration

- tests/README.md
Signed-off-by: Rares <raresgmihalcea@gmail.com>
Currently, the link to native Rust integration tests is broken
The link will now point to `../src/vmm/tests/` instead of `../vmm/tests/`
> Fix link to native Rust integration tests

- docs/prod-host-setup.md
Update the [prod-host-setup.md](https://github.com/firecracker-microvm/firecracker/blob/main/docs/prod-host-setup.md) document with some detail regarding [CVE-2022-26373](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2022-26373)
> Add details to docs on CVE-2022-26373

- tests/integration_tests/performance/test_snapshot_perf.py
- tools/devtool
We recently went back to using Sync engine by default and that required us to re-gather baselines for the snapshot resume test on all platforms.
This should also solve the intermittent failures that we sometimes get on x86 for this test (i.e test_snapshot_resume_latency).
> Add and update baselines inside snapshot resume latency CI test

- README.md
Signed-off-by: Takahiro Itazuri <itazur@amazon.com>
The existing slack invitation link has expired.
Renew the slack invitation link.
> README.md: renew slack invitation link

- docs/devctr-image.md
The currently suggested approach for logging into AWS for docker does not work with non-TTY devices.
Added approach which working alternative.
> Updated devctr-image.md

- tests/integration_tests/performance/configs/test_network_tcp_throughput_config_5.10.json
- tools/parse_baselines/main.py
* changed logic of CPU model update in parse_baselines tool
* updated baselines for Intel 5.10 net
* performance baselines failling nightly runs
---
> Update network TCP throughput baselines on Intel 5.10

- tests/integration_tests/performance/configs/test_network_latency_config_5.10.json
* updated net latency on Intel 5.10
* baselines on 8175M processor (Skylake) have suffered some changes most probably after the RetBleed update
---
> [perf] baselines update for net latency Intel 5.10

- tests/integration_tests/performance/configs/test_block_performance_config_4.14.json
* update block perf baselines for ARM
* failures in nightly long run
---
> [perf] new baselines for block on 4.14 ARM

- tests/integration_tests/performance/configs/test_vsock_throughput_config_4.14.json
- tests/integration_tests/performance/configs/test_vsock_throughput_config_5.10.json
Updating performance baselines for vsock
Multiple failures in vsock performance tests with varying performance
---
> [CI][perf] update vsock baselines

- tests/integration_tests/performance/configs/test_network_tcp_throughput_config_4.14.json
Signed-off-by: Babis Chalios <bchalios@amazon.es>
Updating NET throughput baselines for 4.14 on Intel
Performance tests were failing regularly
---
> [CI][perf] update net throughput baselines 4.14

- tools/devtool
This PR makes a few fixes to make it easier to use `devtool` with a ramdisk in order to run integration tests:
1. It prefixes with `sudo` commands used in `devtool` to create the ramdisk. Until now we need to run `devtool` with sudo which messes up with the build directory of the repo (makes it root-owned).
2. It makes TMPDIR point to the ramdisk
3. It uses `mktemp` for the directory of the ramdisk to avoid collisions when more than one test campaigns are running
Make it easier to run tests using a ramdisk. This can be potentially faster and also reduce interference (for example disk I/O) when running multiple tests.
---
[2]: …
> Fixes to allow using ramdisk to run tests

- CHANGELOG.md
- docs/network-setup.md
- src/devices/src/virtio/net/device.rs
- src/devices/src/virtio/net/persist.rs
- src/devices/src/virtio/net/test_utils.rs
- src/utils/src/lib.rs
- src/vmm/src/device_manager/persist.rs
- src/vmm/src/resources.rs
- src/vmm/src/vmm_config/net.rs
Signed-off-by: Vibha Acharya <vibharya@amazon.co.uk>
Code to generate and assign a MAC address when it is not explicitly specified when a network interface is added.
When MAC address is unspecified vm config reports it as null. Post restore it is reported as 00:00:00:00:00:00.
In reality the MAC address is assigned by the driver.
Related to: #2943 
---
> Snapshot-ga: Generate a MAC address if unspecified

- pre-commit
Add an excludsionary [filter to the `git diff` command](https://git-scm.com/docs/git-diff#Documentation/git-diff.txt---diff-filterACDMRTUXB82308203) in the `pre-commit` script to filter out files deleted from code revision.
Files that are attempted to be formatted (by rustfmt or black for example) when they no longer exist will cause the script to fail incorrectly.
> Ignore git-deleted files in pre-commit script

- src/arch/src/x86_64/layout.rs
According to the [spec](https://www.kernel.org/doc/html/latest/admin-guide/kernel-parameters.html),
the kernel command line should have a maximum size of COMMAND_LINE_SIZE bytes, where
COMMAND_LINE_SIZE is defined as a constant in Linux kernel. For x86, this constant has a value of 2048
according to the [kernel's source](https://elixir.bootlin.com/linux/v5.10.139/source/arch/x86/include/asm/setup.h#L7).
This PR is intended to correct the value of the constant that has a similar meaning on Firecracker side.
Correcting the value of the CMDLINE_MAX_SIZE const. Updating the comment of the const.
> Wrong Cmdline max size constant value

- src/vmm/src/builder.rs
- src/vmm/src/resources.rs
- src/vmm/src/rpc_interface.rs
- src/vmm/src/utilities/mock_resources/mod.rs
- src/vmm/src/vmm_config/boot_source.rs
Separate boot source configuration from boot source builder in vmm resources.
Depending on whether or not we are dealing with a resumed microVM or freshly booted up microVM, the vmm resources will contain a BootConfig (i.e a BootSourceConfig which has gone through the cmdline validation process and also opening of the kernel image) or not.
We want to decouple the BootSourceConfig (the description of the BootSource details like path to the kernel image) from the BootConfig which holds the fd to the kernel etc.
...
---
> separate boot source config from the associated runtime details

- CHANGELOG.md
- docs/jailer.md
- src/jailer/src/env.rs
- src/jailer/src/main.rs
- tests/integration_tests/security/test_jail.py
- check that the given `--exec-file` parameter contains `firecracker`.
- create `/tmp/pseudo_firecracker_exec_file` before tests with arguments.
Issue: #1082
As the doc states, the `--exec-file` parameter is intended to be specified a firecracker binary. 
> `exec_file` is the path to the Firecracker binary that will be exec-ed by the jailer. The user can provide a path to any binary, but the interaction with the jailer is mostly Firecracker specific.
But jailer didn't check if the given executable file as `--exec-file` is firecracker.
If jailer run it without this check, it might output nothing or uninterpretable messages.
This situation made it difficult for users to identify the root cause.
the terms of the …
> [jailer] add check of --exec-file parameter

- tools/devtool
Signed-off-by: Takahiro Itazuri <itazur@amazon.com>
- Changes the default size of rootfs used in `tools/devtool build_rootfs`
Closes #3147
---
> [devtool] change the default size of rootfs

- tests/framework/microvm.py
- tests/integration_tests/functional/test_serial_io.py
The test started failling after latest AMI
update on 4.14. Seems that reading from the
screen log file the output of the microVM
became slower.
---
> fix intermittent failure in serial_after_snapshot

- .github/pull_request_template.md
Changes the link of "Runbook for Firecracker API changes" from relative link to absolute link.
Fixes #2782 
---
> PR template: change relative link to absolute link

- src/devices/src/virtio/block/device.rs
- src/devices/src/virtio/queue.rs
- tests/framework/gitlint_rules.py
The number of descriptor chain heads to process should always be smaller or equal to the queue size, as the driver should never ask the VMM to process a available ring entry more than once. Checking and reporting such incorrect driver behavior can prevent potential hanging and Denial-of-Service from happening on the VMM side.
Issue reported in rust-vmm/vm-virtio and fixed in
https://github.com/rust-vmm/vm-virtio/pull/196.
Co-authored-by: Bo Chen <chen.bo@intel.com>
Fixes  #3149.
---
> virtio-queue: Error out on invalid available ring index

- src/vmm/benches/main.rs
- src/vmm/src/builder.rs
- src/vmm/src/lib.rs
- src/vmm/src/persist.rs
- src/vmm/src/rpc_interface.rs
- src/vmm/src/version_map.rs
- src/vmm/src/vmm_config/boot_source.rs
- src/vmm/src/vmm_config/machine_config.rs
- src/vmm/tests/integration_tests.rs
- tests/integration_tests/functional/test_api.py
Added `boot_source`, `smt`, `cpu_template` information to the snap state file in order to maintain consistency post restore.
This information was not being persisted into the snapshot and was missing from the VM config result as well.
Related to: #2943 
---
> [snapshot-ga] Additional info added to snap state.

- src/devices/src/virtio/block/device.rs
- src/devices/src/virtio/queue.rs
Backports https://github.com/firecracker-microvm/firecracker/pull/3156 in supported release version 1.0.
---
> Backport fix for virtio queue in 1.0

- src/devices/src/virtio/block/device.rs
- src/devices/src/virtio/queue.rs
Backports https://github.com/firecracker-microvm/firecracker/pull/3156 in supported release version 1.1.
---
> Backport fix for virtio queue in 1.1

- tools/bindgen.sh
- tools/test_bindings.py
Add a small python script that uses pahole (man 1 pahole) to test if the bindings created between two firecracker binaries match. Currently, this compares for the size of all structs created through bindgen.
When creating new bindings through bindgen we want to have visibility into possible changes in the binary layout of the new structs.
---
> Add tool to check bindgen structs

- tests/integration_tests/performance/configs/test_snap_restore_performance_config_5.10.json
- tools/parse_baselines/providers/snapshot_restore.py
* changed the way we compute baselines for snap resume latency
* gathered 5.10 baselines on cgroup v2 AL2 5.10
Make snapshot GA.
---
> [Snapshot] Performance baselines on 5.10 on AL2

- tests/integration_tests/performance/configs/test_snap_restore_performance_config_4.14.json
- tools/parse_baselines/main.py
* support for parsing baselines on AMD
* gathered 4.14 baselines on AMD
Snapshot GA
---
> [Snapshot] Performance baselines for AMD 4.14

- tests/integration_tests/performance/configs/test_snap_restore_performance_config_5.10.json
* gathered baselines for AMD 5.10 on cgroups v2 AL2
---
> [Snapshot] Performance baselines for AMD 5.10

- src/arch/src/x86_64/msr.rs
This excludes MSR_IA32_FEATURE_CONTROL from the deny list while saving MSRs to snapshot.
The MSR was previously masked from saving, but this is no longer relevant.
Testing showed that MSR_IA32_FEATURE_CONTROL did not preserve its value after being written to before taking snapshot and then restored. This is because it was in the deny list.
---
> arch/x86_64: save MSR_IA32_FEATURE_CONTROL

- src/vmm/src/device_manager/mmio.rs
- src/vmm/src/device_manager/persist.rs
Signed-off-by: Takahiro Itazuri <itazur@amazon.com>
- Renames `allocate_new_slot()` to `allocate_mmio_resources()`.
- Renames variables of `MMIODeviceInfo` related to this function.
Fixes #2014
`allocate_new_slot()` function allocates not only memory slots but also IRQs.
---
> vmm: correct function name and variable names

- tools/devtool
* Added kernel version log line in devtool
* Add CPU information with `lscpu`
```
[Firecracker devtool] 2022-10-12 16:38:51 UTC
[Firecracker devtool] Kernel version: 4.14.291-218.527.amzn2.aarch64
[Firecracker devtool] Starting test run ...
============================= test session starts ==============================
platform linux -- Python 3.10.4, pytest-7.1.2, pluggy-1.0.0
...
======================== 7 passed in 496.44s (0:08:16) =========================
[Firecracker devtool] Architecture:        aarch64
Byte Order:          Little Endian
CPU(s):              64
On-line CPU(s) list: 0-63
Thread(s) per core:  1
Core(s) per socket:  64
Socket(s):           1
NUMA node(s):        1
Model:               1
BogoMIPS:            243.75
L1d cache:           64K
L1i cache:           64K
L2 …
```
> Log kernel version and CPU in tests

- README.md
Document MSR_IA32_TSX_CTRL limitation when taking snapshot.
Inform users of a known limitation.
---
> doc: add MSR_IA32_TSX_CTRL snapshot limitation

- src/cpuid/src/cpu_leaf.rs
- src/cpuid/src/template/intel/c3.rs
- src/cpuid/src/template/intel/mod.rs
- src/cpuid/src/template/intel/t2.rs
This adds a new set of MSRs to be saved in x86_64: MTRR and MCE.
Both MTRR and MCE MSRs are not advertised by KVM via KVM_GET_MSR_INDEX_LIST, however are emulated by it. This means that they have to be saved/restored when taking a snapshot.
---
> x86_64: save extra msrs (mtrr and mce)

- tools/devctr/Dockerfile.x86_64
Specifies `mdl` version of `0.11.0` to resolve error with building `Dockerfile.x86_64`.
When attempting to build the container with `devtool build_devctr` an error is produced like:
```
...
Setting up curl (7.58.0-2ubuntu3.20) ...
Setting up ruby2.5 (2.5.1-1ubuntu1.12) ...
Setting up ruby (1:2.5.1) ...
Setting up ruby-test-unit (3.2.5-1) ...
Setting up rake (12.3.1-1ubuntu0.1) ...
Setting up libruby2.5:amd64 (2.5.1-1ubuntu1.12) ...
Setting up ruby2.5-dev:amd64 (2.5.1-1ubuntu1.12) ...
Setting up ruby-dev:amd64 (1:2.5.1) ...
Processing triggers for libc-bin (2.27-3ubuntu1.6) ...
Processing triggers for ca-certificates (20211016~18.04.1) ...
Updating certificates in /etc/ssl/certs...
0 added, 0 removed; done.
Running hooks in /etc/ca-certificates/update.d...
done.
Collecting setuptools …
```
> Fix gem dependencies in docker file

- .gitignore
- tests/integration_tests/build/test_coverage.py
- tests/integration_tests/build/test_unittests.py
- tools/devctr/Dockerfile.aarch64
- tools/devctr/Dockerfile.x86_64
- tools/devtool
Changed code coverage to use [grcov](https://github.com/mozilla/grcov).
grcov includes the test code as covered lines (where as kcov does not appear to do so). This moderately increases our line coverage.
Previously we ran tests with the `aarch64-unknown-linux-musl` and `x86_64-unkown-linux-musl` tool chains to generate code coverage data then ran the unit tests under the `x86_64-unknown-linux-gnu` and `aarch64-unknown-linux-gnu` tool chains. This accomplished testing both both combinations of tool chains covering both our primary `musl` targets and the commonly used `gnu` target.
At present `aarch64-unknown-linux-musl` is not supported with profiling by Rust lang, I opened an issue regarding this https://github.com/rust-lang/rustup/issues/3095 (interestingly `x86_64-unknown-linux-musl` …
> Update code coverage

- tests/integration_tests/performance/test_versioned_serialization_benchmark.py
Increase baseline values in the VMM serialisation test.
Serialisation takes longer due to addition of MTRR and MCE MSRs to the snapshot.
---
> test/versioned_serialization: update vmm baselines

- CHANGELOG.md
- Cargo.lock
- src/arch/src/aarch64/fdt.rs
- src/arch/src/aarch64/mod.rs
- src/vm-memory/Cargo.toml
- src/vmm/src/builder.rs
- src/vmm/src/device_manager/mmio.rs
- src/vmm/src/lib.rs
- src/vmm/src/resources.rs
- src/vmm/src/vmm_config/boot_source.rs
Signed-off-by: Traistaru Andrei Cristian <atc@amazon.com>
This PR contains code changes done for the integration of the new Cmdline parser implemented
in rust-vmm/linux-loader v0.7.0. The new version of the Cmdline struct allows better kernel
parameters handling (supporting both boot args and init args), catching some corner cases that
we currently do not handle properly. 
The PR should fix [this bug](https://github.com/firecracker-microvm/firecracker/issues/3023).
---
> Consuming linux-loader v0.7.0 for bugfix of the Cmdline

- docs/kernel-policy.md
Update snapshot compatibility matrix in docs.
We found out that a snapshot taken on AMD with 5.10 kernel is not compatible with 4.15 kernel
---
> docs: cross kernel snapshot incompatibility on AMD

- tests/integration_tests/performance/test_versioned_serialization_benchmark.py
Increase the Intel benchmark target in `test_versioned_serialization_benchmark.py` to unblock development.
Following changes to the Linux Kernel to handle
RETBLEED mitigations Skylake CPUs perform signicantly worse.
This affects the Firecracker baseline for all Intel testing. Until Firecracker's CI and performance pipelines can move off of Skylake, we will need drop our baseline to prevent unrelated disruptions to our pipeline.
> Increase serialize(no-crc) target benchmark

- .mailmap
- CHANGELOG.md
- src/api_server/swagger/firecracker.yaml
- tests/integration_tests/style/test_licenses.py
- tools/devtool
- tools/functions
- tools/release-notes.sh
- tools/release-prepare.sh
- tools/release-tag.sh
- tools/release.sh
- tools/update-credits.sh
Move the release functions of devtool into its own script. That way it can be built from within the Docker container too.
- Make it simple to change the release workflow
- Simplify `devtool`
- Allow builds from within the devctr (just call `./tools/release.sh`)
---
> Move `devtool release` functionality to a separate script

- tests/integration_tests/functional/test_snapshot_basic.py
Reduce the uVM memory in `test_5_inc_snapshots` test from 4GB to 512MB.
The memory size of the VM was causing the test to take a long time to complete and some times it would hit the CI timeout, causing intermittent failures. Moreover, the size of the memory does not add any value to the test itself.
---
> test: reduce snapshot size in test

- .cargo/config
- src/vmm/build.rs
This commit restored the old behavior while still fixing cross-compilation. For this, instead of relying on the default target matching the compilation host, we instead explicitly read the host target from the HOST variable that cargo sets for build scripts.
My PR #3213 carelessly changed the default behavior of cargo build.
---
> Revert default behavior of cargo build

- CHANGELOG.md
- tests/integration_tests/performance/configs/test_block_performance_config_4.14.json
- tests/integration_tests/performance/configs/test_block_performance_config_5.10.json
- tests/integration_tests/performance/configs/test_network_latency_config_4.14.json
- tests/integration_tests/performance/configs/test_network_latency_config_5.10.json
- tests/integration_tests/performance/configs/test_network_tcp_throughput_config_4.14.json
- tests/integration_tests/performance/configs/test_network_tcp_throughput_config_5.10.json
- tests/integration_tests/performance/configs/test_snap_restore_performance_config_4.14.json
- tests/integration_tests/performance/configs/test_snap_restore_performance_config_5.10.json
- tests/integration_tests/performance/configs/test_vsock_throughput_config_4.14.json
- tests/integration_tests/performance/configs/test_vsock_throughput_config_5.10.json
- tools/parse_baselines/main.py
Add performance baseline for m6i.metal.
Currently, performance baseline on m6i.metal (newer Intel instance type) are not included.
---
> add performance baseline for m6i.metal

- tests/framework/utils.py
- tests/integration_tests/functional/test_snapshot_basic.py
- tests/integration_tests/functional/test_snapshot_restore_cross_kernel.py
- tests/integration_tests/performance/test_snapshot_perf.py
We have stumbled upon an OOM scenario in one of our integration tests (5_inc and 5_full snapshots) due to the fact that we spawn FIO in the guest in every create/resume snapshot sequence. Doing it upon each invocation of snap/resume might possibly lead to multiple FIO instances on the guest (the FIO processes from the previous guest might get snapshotted). This can result in an OOM and thus lead to an intermittent failure in the CI.
---
> CI: fix 5_inc_snapshots intermittent failure

- docs/kernel-policy.md
Replace AMD kernel version 4.14 with 4.15 in the snapshot compatibility matrix.
Snapshot compatibility matrix gives wrong impression about supported kernel versions on AMD.
---
> doc: fix typo in AMD kernel version: 4.15 -> 4.14

- docs/jailer.md
Tweak markdown formatting by adding ` around code.
Tweak markdown formatting by adding ` around code.
---
> doc: Tweak markdown formatting

- docs/getting-started.md
Updates the documentation to include information about us setting a default target in .cargo/config which is incompatible with ARM, which causes issues if trying to build Firecracker on ARM without devtool.
The behavior here is unintuitive and has already tripped up multiple team members trying to build firecracker outside of docker on ARM.
---
> Clarify documentation on building Firecracker without devtool

- tests/integration_tests/performance/configs/test_block_performance_config_4.14.json
- tests/integration_tests/performance/configs/test_network_latency_config_4.14.json
- tests/integration_tests/performance/configs/test_network_tcp_throughput_config_4.14.json
- tests/integration_tests/performance/configs/test_snap_restore_performance_config_4.14.json
- tests/integration_tests/performance/configs/test_vsock_throughput_config_4.14.json
New baselines for Intel 4.14 trying to capture the regressions we have seen on Skylake.
We have observed performance regressions on Intel 4.14 for Intel Skylake.
---
> Performance baselines for Intel 4.14

- src/api_server/Cargo.toml
- src/arch/Cargo.toml
- src/arch_gen/Cargo.toml
- src/cpuid/Cargo.toml
- src/devices/Cargo.toml
- src/dumbo/Cargo.toml
- src/firecracker/Cargo.toml
- src/io_uring/Cargo.toml
- src/jailer/Cargo.toml
- src/logger/Cargo.toml
- src/mmds/Cargo.toml
- src/net_gen/Cargo.toml
- src/rate_limiter/Cargo.toml
- src/rebase-snap/Cargo.toml
- src/seccompiler/Cargo.toml
- src/snapshot/Cargo.toml
- src/utils/Cargo.toml
- src/virtio_gen/Cargo.toml
- src/vm-memory/Cargo.toml
- src/vmm/Cargo.toml
- tests/integration_tests/build/test_coverage.py
Update rust edition to 2021
Since we updated to cargo 1.64.0 we don't need to require edition 2018 any more
---
> rust: update to edition2021

- .mailmap
- tools/release-prepare.sh
- tools/release.sh
- Fix a version bump we didn't do before.
- During release, print some more info in case of a dirty version.
- Fix one entry in `CREDITS.md`.
- Fix a bug when comparing the swagger version to the release version.
To make releases work for all supported branches.
---
> Fix release

- tests/framework/stats/consumer.py
This reverts commit 082e58fbd931040a777da06f963eab71b6e8b8ff ([PR/3245](https://github.com/firecracker-microvm/firecracker/pull/3245)).
A change was introduced in [PR/3245](https://github.com/firecracker-microvm/firecracker/pull/3245) to force performance tests to fail if a given baseline configuration was missing for a given CPU. While this seems to have had the desired affect, the commit did not include baseline configurations for actual missing configurations:
* Intel m6i (4.14) - Vsock Throughput
* Intel m6i (5.10) - Vsock Throughput
* Intel m6i (4.14) - Network TCP Throughput
* Intel m6i (5.10) - Network TCP Throughput
* Arm (4.14) - Vsock Throughput
While the change is good and should be introduced, results in failures of performance pipelines for missing performance baseline …
> Revert "make tests fail when criteria not found"

- .buildkite/pipeline_pr.py
- tests/integration_tests/style/test_licenses.py
- Made a script that can generate the build script we run for every PR
- Made the license check a bit more robust by finding the copyright line instead of expecting it to be at an exact location.
We have more control to decide what steps run and on what agents. Also there is less clicking when trying to find a failed job. 
---
> CI: generate PR pipeline dynamically

- Cargo.lock
- src/arch/src/x86_64/interrupts.rs
- src/arch/src/x86_64/regs.rs
- src/devices/src/virtio/net/test_utils.rs
- src/dumbo/src/tcp/connection.rs
- src/utils/src/lib.rs
- src/vmm/src/vstate/vcpu/x86_64.rs
- src/vmm/src/vstate/vm.rs
- tests/host_tools/uffd/Cargo.lock
- tests/integration_tests/security/demo_seccomp/Cargo.lock
See https://github.com/firecracker-microvm/firecracker/pull/3249 and https://github.com/firecracker-microvm/firecracker/pull/3248.
rust-vmm/event-manager still uses comparision requirements, so we have to play catch up with any new rust-vmm version for now
...
...
---
> Update rust-vmm/vmm-sys-util to 0.11.0

- tests/framework/stats/criteria.py
When baseline is not available, performance tests pass without any errors.
By making tests fail in such situations, we can be aware of missing performance baselines.
Raise exception when baseline is not available.
A commit which has the same purpose was merged in PR #3245 .
But since it lead many false alarms, it was reverted in PR #3253 .
Before submitting this PR, I confirmed that it doesn't generate those false alarms and make tests fail correctly when baseline is not available.
---
> tests: make tests fail when baseline not found

- docs/design.md
- docs/prod-host-setup.md
Signed-off-by: Marco Cali <xmarcalx@amazon.co.uk>
Modify the documentation to include explicitly the max number of vCPU supported and other minor grammatical changes.
Fixes #3059
Updated the "Features" section of the design.md file to state the max vCPU number. 
> Update docs to provide better clarity of supported features

- src/vmm/src/builder.rs
Signed-off-by: Traistaru Andrei Cristian <atc@amazon.com>
Adding a comment according to https://github.com/firecracker-microvm/firecracker/pull/3264#discussion_r1023828793
---
> Adding comment for cmdline_contains()

- .buildkite/pipeline_pr.py
- tests/integration_tests/build/test_pylint.py
- tests/integration_tests/functional/test_balloon.py
- tests/integration_tests/functional/test_snapshot_advanced.py
- tests/integration_tests/functional/test_snapshot_basic.py
- tests/integration_tests/style/test_licenses.py
- tests/pytest.ini
~It would be helpful to have more context on what commands were run and what they returned in the captured logs. This is helpful for troubleshooting.~
Turns out the logging can be megabytes in size, and can hide things like the traceback. So I am pulling that commit but including all the other little quality-of-life improvements I did to support it. 
Increase the verbosity of the logger so that more messages appear in the logs.
To help troubleshooting intermittent issues. 
---
> chore(tests): add more logs to some intermittently failing tests

- tools/devtool
- tools/functions
- tools/release-notes.sh
- tools/release-prepare.sh
- tools/release-tag.sh
- tools/release.sh
Backport release automation changes to v1.1 branch
To make further patch releases 
---
> Backport Release Automation to Firecracker v1.1

- tools/devtool
* error management in  devtool's build_kernel command
* fixes #2932 
---
> build_kernel: check for errors

- src/cpuid/src/common.rs
Links the todo to a newly created issue.
A tracking issue prevents the todo being forgotten.
---
> Linking `has_cpuid` todo

- .buildkite/pipeline_pr.py
- tests/integration_tests/style/test_licenses.py
- tests/integration_tests/style/test_python.py
Backporting pipeline-pr.py script to FC 1.1. 
---
> Backport pipeline pr script to  FC 1.1

- tests/integration_tests/performance/configs/test_snap_restore_performance_config_4.14.json
- tests/integration_tests/performance/configs/test_snap_restore_performance_config_5.10.json
- tests/integration_tests/performance/test_snapshot_restore_performance.py
- tools/parse_baselines/main.py
- tools/parse_baselines/providers/latency.py
This brings changes in test framework and baseline collection script from main in order to be able to collect performance baselines for snapshot restore.
The change includes update in the baseline config schema and baseline config files themselves.
It was impossible to collect snapshot restore performance baselines for v1.1 in order to compare them with the main within the same environment (e.g., same testing instances). 
---
> v1.1: tests: backport changes to collect snapshot restore perf baselines 

- tools/devtool
- tools/functions
- tools/release-notes.sh
- tools/release-prepare.sh
- tools/release-tag.sh
- tools/release.sh
Backport release automation changes to v1.0 branch
Original PR: https://github.com/firecracker-microvm/firecracker/pull/3139
To simplify future patch releases
---
> Backport Release Automation to Firecracker v1.0

- tests/integration_tests/security/test_sec_audit.py
Suppress the warning `cargo audit` throws about `atty`
This warning is currently blocking our PR CI, and there is no remedy available, as there is no patched version of the atty crate available, and we do not know how long it will take for criterion to remove the dependency.
---
> Supress atty cargo audit warning

- src/api_server/src/lib.rs
- src/api_server/src/parsed_request.rs
- src/arch/src/x86_64/interrupts.rs
- src/firecracker/src/api_server_adapter.rs
- tests/integration_tests/build/test_coverage.py
- tests/integration_tests/functional/test_api_server.py
The old IOError and EventFdError in the api_server's enum Error are not actually used.
They have been at some point used but we later introduced the logci where bind_and_run would call std::proces::exit on errors on HttpServer creation so in reality the IOError and EventFD error would not be thrown ever.
There are still some things to figure out: bind_and_run will not return any type of error except for the one we add in this commit. All the error processing happens inside bind and run in reality.
...
...
--- …
> api_server: fix error propagating

- tests/integration_tests/functional/test_snapshot_restore_cross_kernel.py
- tools/create_snapshot_artifact/main.py
Add T2S template to cross-kernel/CPU snapshot tests.
Currently we are testing against C3 and T2 templates.
---
> test: add T2S to cross-kernel/CPU snapshot tests

- tests/framework/microvm.py
- tests/integration_tests/functional/test_serial_io.py
- tests/integration_tests/security/test_sec_audit.py
The test started failling after latest AMI
update on 4.14. Seems that reading from the
screen log file the output of the microVM
became slower.
(cherry picked from commit e779c545025e40d6c56371b0f97cbc2f30c1c518)
---
> Backport fix intermittent serial_after_snapshot

- src/devices/src/legacy/i8042.rs
- src/devices/src/legacy/mod.rs
- src/devices/src/legacy/rtc_pl031.rs
- src/devices/src/legacy/serial.rs
- src/devices/tests/serial_utils/mod.rs
- src/vmm/src/builder.rs
- src/vmm/src/lib.rs
- src/vmm/src/utilities/mock_devices/mod.rs
* add doc (i.e /// comments) for public facing struct for legacy devices
* nit improvements
---
> devices: add documentation for legacy devices

- Cargo.lock
- Cargo.toml
- src/api_server/Cargo.toml
- src/arch/Cargo.toml
- src/arch/src/aarch64/regs.rs
- src/cpuid/Cargo.toml
- src/devices/Cargo.toml
- src/dumbo/Cargo.toml
- src/firecracker/Cargo.toml
- src/logger/Cargo.toml
- src/mmds/Cargo.toml
- src/vm-memory/Cargo.toml
- src/vmm/Cargo.toml
- src/vmm/src/vstate/vcpu/aarch64.rs
- src/vmm/src/vstate/vcpu/mod.rs
- src/vmm/tests/integration_tests.rs
- tests/integration_tests/build/test_coverage.py
- tests/integration_tests/functional/test_mmds.py
- tests/integration_tests/functional/test_snapshot_advanced.py
- tests/integration_tests/performance/test_snapshot_perf.py
Bump all rust-vmm dependencies to the newest release and specify their versions using caret requirements (we update all our other dependencies in #3248). The only crate where the version bump also introduces API changes is kvm-ioctl,  but these are minimal and this PR adjusts for them. 
Recently, all rust-vmm crates received major version bumps to fix the way intra-rust-vmm dependencies are specified. See https://github.com/rust-vmm/community/issues/136#issuecomment-1314184934 for details
---
> Update rust vmm dependencies

- tools/compare_baselines/interactive.py
- tools/compare_baselines/main.py
- tools/compare_baselines/utils/__init__.py
- tools/compare_baselines/utils/comparator.py
- tools/compare_baselines/utils/defs.py
- tools/compare_baselines/utils/fetcher.py
Adds scripts to compare performance baselines
There are several situations to compare gathered performance baselines:
- when we encounter some performance regressions
- when we support new instance types / CPUs
Currently, we don't have any tools to evaluate gathered baselines and we have no choices but to compare them one by one.
---
> perf: add scripts to compare performance baselines

- tests/integration_tests/performance/test_snapshot_perf.py
Increases the target values of snapshot/resume latency for m6g.metal & m6i.metal.
Regarding m6g.metal, along with kernel updates including io_uring change, snapshot/resume latency values on kernel v5.10 increased. In order to not block merging PRs with the updated images, these values need to be updated. We'll keep diving deep into the root cause of this increase even after merging this commit.
Regarding m6i.metal, PR #3235 just copied the target values from m5d.metal and these target values are still TODO. And we have observed several errors for m6i.metal due to this. Replacing them with gathered values will mitigate the CI block.
---
[2]: …
> Increase snapshot/resume latency target values

- src/mmds/src/token.rs
In case the assertions fail, print out the values
We have observed spurious failures in this test, and this hopefully helps debugging them
---
> Improve assert messages in mmds::token::test_compute_expiry

- docs/snapshotting/snapshot-support.md
- src/vmm/src/rpc_interface.rs
- tests/integration_tests/security/test_sec_audit.py
Print a warning messages about 822009ce3ef521f5c91bcb7c6a36406ed5bdefba whenever a snapshot is created/loaded on arm64 in firecracker 1.0, and update the "Known issues and limitations" section
We decided against backporting the fix due to the significant work and the fact that 1.0 goes out of support in a handful of days. 
---
> [1.0.2] Warn on arm64 snapshots

- CHANGELOG.md
- Cargo.lock
- docs/network-setup.md
- src/devices/src/virtio/net/device.rs
- src/devices/src/virtio/net/persist.rs
- src/devices/src/virtio/net/test_utils.rs
- src/mmds/src/token.rs
- src/utils/Cargo.toml
- src/utils/src/lib.rs
- src/utils/src/net/mac.rs
- src/vmm/src/device_manager/persist.rs
- src/vmm/src/persist.rs
- src/vmm/src/resources.rs
- src/vmm/src/version_map.rs
- src/vmm/src/vmm_config/net.rs
- tests/integration_tests/build/test_coverage.py
Signed-off-by: Egor Lazarchuk <yegorlz@amazon.co.uk>
This PR:
- Removes random MAC address generation introduced by [this](https://github.com/firecracker-microvm/firecracker/pull/3121) commit
- fixes an issue in `GET /vm/config` which returned invalid `00:00:00:00:00:00` MAC address if it was not previously specified by the user.
Additionally fixes snapshot files not being truncated when saved.
Fixes #2943 second time
---
> Removing MAC address random generation

- tests/host_tools/uffd/Cargo.lock
- tests/host_tools/uffd/Cargo.toml
- tests/host_tools/uffd/src/bin/malicious_handler.rs
- tests/host_tools/uffd/src/bin/valid_handler.rs
- tests/host_tools/uffd/src/uffd_utils.rs
- tests/integration_tests/security/demo_seccomp/Cargo.toml
* push dirty uffd/Cargo.lock
* Some other small fixes were made that bring the
dependencies in sync with the versions used in
production.
The Cargo.lock from the uffd tests appears
as dirty since the "utils" crate depends on Versionize. This happened with the merging of PR #3287.
---
> [tests][uffd]: uffd/Cargo.lock is dirty

- build.rs
- src/devices/src/virtio/balloon/device.rs
- src/devices/src/virtio/block/device.rs
- src/jailer/src/cgroup.rs
- src/jailer/src/env.rs
- src/jailer/src/main.rs
- src/vmm/src/seccomp_filters/mod.rs
- src/vmm/src/vmm_config/mod.rs
- tests/integration_tests/build/test_coverage.py
- tools/devctr/Dockerfile.aarch64
- tools/devctr/Dockerfile.x86_64
- tools/devctr/poetry.lock
- tools/devtool
Updated Rust version to latest stable 1.65.0.
Fixed a variety of minor clippy warnings that where newly detected with the update. Some of these overlap with #3215.
With the Rust update a [`debug_assert!`](https://github.com/rust-lang/rust/blob/1.64.0/library/std/src/sys/unix/fs.rs#L690) is changed to an [`assert!`](https://github.com/rust-lang/rust/blob/1.65.0/library/std/src/sys/unix/fs.rs#L690:L694). Since we run with a pre-compiled standard library this meant previously this assert was not being checking (as the standard library is compiled in release), now with the update it is being checked.
This now results in an error. 
```
thread 'main' panicked at 'unexpected error during closedir: Os { code: 9, kind: Uncategorized, …
```
> Update Rust 1.65.0

- tools/devtool
v45 was already in use on the v1.1 branch
...
...
---
> Update devtool fcuvm tag to v46

- docs/devctr-image.md
Add instructions to make sure that we do not accidentally overwrite existing images when publishing new versions of the devctr
We accidentally overwrote some images the other day
---
> Update build_devctr with hint about version choice

- src/devices/src/virtio/balloon/device.rs
- src/devices/src/virtio/block/device.rs
- src/devices/src/virtio/mmio.rs
- src/devices/src/virtio/net/device.rs
* virtio trait functions are ordered in implementation functions
* This is to avoid a linting warning in my
IDE space.
* It is also good practice.
---
> virtio: use same impl member order from the trait

- CHANGELOG.md
- Cargo.lock
- docs/network-setup.md
- src/devices/Cargo.toml
- src/devices/src/virtio/net/mod.rs
- src/devices/src/virtio/net/tap.rs
- src/vmm/src/vmm_config/net.rs
- tests/integration_tests/build/test_coverage.py
- tests/integration_tests/functional/test_api.py
- tests/integration_tests/functional/test_net.py
So the task is to introduce a proper error message when passing a tap device with multi-queue feature enabled to firecracker. The error itself appears when we try to `TUNSETIFF` on the tap device [here](https://github.com/firecracker-microvm/firecracker/blob/1644b3cb4947b927f29da795492284b4b10f2405/src/devices/src/virtio/net/tap.rs#L126).
- One way to check if a tap device is configured with multi-queue flag is to read `/sys/class/net/{}/tun_flags` file and check it for the flag. The problem is that it does not work when firecracker is run inside the `jailer`, because it can not access that file. 
- So there is another way to check for the flag. We can just try to create tap device twice: one time with usual flags and second time with multi-queue flag set. If the second call successes …
> Better error message when multi queue net device is in use

- tests/integration_tests/performance/configs/test_snap_restore_performance_config_4.14.json
Updates baselines for snapshot/restore tests on kernel 4.14 + m6a.metal (AMD).
The snapshot/restore performance test continued to fail since 2022-10-30. 
As a result of investigation, `ioctl()` for `KVM_CREATE_VM` and the first `KVM_CREATE_VCPU` takes much time and most of the elapsed time for `ioctl()` was spent on sending IPIs to all-but-self.
The reasons why we see this issue only on the combination of kernel 4.14 and m6a.metal (AMD) are:
- m6a.metal (AMD) uses xAPIC and needs to send 1 IPI for each CPU thread, while m5d.metal (Intel) uses 2xAPIC support cluster configuration and just need to send 1 IPI for each cluster.
- [This patch](https://lwn.net/Articles/793065/) is available on kernel 5.10 and it reduces the time to send IPIs to all-buf-self by using the destination shorthand …
> chore: Update snap/restore baseline

- tests/integration_tests/performance/configs/test_snap_restore_performance_config_4.14.json
Re-gathered baselines for `snap_restore_performance` for m6i kernel 4.14.
Updates `snap_restore_performance` baselines for the 4.14 kernel on the m6i instance.
The P90 values with m6i kernel 4.14 for the intermittently failing tests are as follows:
`(x)` represents `x` samples.
case|32c7f1e220bf46f988301b915bb5f995772a31aa (original 40)|32c7f1e220bf46f988301b915bb5f995772a31aa (80) (https://pastebin.com/uLUVtM7r)|866ad25014ad55a82c113cf0c7ab8ed0f2d1f675 (80) (https://pastebin.com/WqBZZtK1)|01ecbccdc5140014e62f6fb600ff647f087d2af5 (80) (https://pastebin.com/q9XnPvGy)
---|---|---|---|---
1vcpu 8192mb|14.216±56%|14.471±149%|14.491±148%|15.374±134%
1vcpu 1024mb|4.902±17%|4.955±15%|4.966±22%|5.057±19%
1vcpu 3278mb|39.88±12%|42.044±87%|41.513±80%|42.679±75%
1vcpu …
> chore: snap_restore_performance 4.14. m6i baselines

- Cargo.lock
- src/arch/Cargo.toml
- src/vmm/Cargo.toml
- tests/integration_tests/build/test_coverage.py
* upgrade to linux loader 0.8.1
* consume latest fix: https://github.com/rust-vmm/linux-loader/pull/125/files#diff-c7c03aafbb71ffde8c782644097d85eba96f762dfb2e2fc870613f4071f57c35L220
---
> fix: upgrade to latest linux loader

- tools/bindgen.sh
Adds comma in `bindgen.sh`.
Fixes missing comma in lint settings in `bindgen.sh`.
---
> Fix `bindgen.sh`

- src/cpuid/src/common.rs
Replaced a transmutation with safe Rust
Less unsafe blocks to worry about
---
> cpuid: replace transmute with safe version

- tests/integration_tests/performance/test_snapshot_perf.py
- tests/integration_tests/performance/test_versioned_serialization_benchmark.py
* Increase the snapshot load test performance target on aarch64 hosts for Kernel 5.10 using the async file engine.
* Increase the snapshot load test performance target on amd hosts for Kernel 4.14 using the sync file engine.
* Adding rounding of some floating point values in the serialization benchmark test
Test failure for continuous integration seen in Buildkite ([ARM test](https://buildkite.com/firecracker/firecracker-pr/builds/242#01853975-5022-42eb-8f76-cb78fff3fb7d), [AMD test](https://buildkite.com/firecracker/firecracker-pr/builds/257#01853ec2-3e6a-496f-be2a-bd04ccc47e88)). This follows recent tweaks to that target in [PR/3291](https://github.com/firecracker-microvm/firecracker/pull/3291). A slightly increased time between the 256MB guest and the 512MB guest was not maintained …
> Increase snapshot target for 512mb VM on aarch64/amd64

- .gitlint
- docs/snapshotting/snapshot-support.md
- src/vmm/src/version_map.rs
- tests/conftest.py
- tests/framework/artifacts.py
- tests/integration_tests/functional/test_cmd_line_parameters.py
- tests/integration_tests/functional/test_snapshot_advanced.py
Fix missing versions in the version to snapshot version map.
...
---
> chore(snapshot): clarify snapshot version map

- tools/create_snapshot_artifact/main.py
The test infra assumes CWD is 'ROOT/tests'. create_snapshot_artifact runs from the root '.', so some functions can fail.
Workaround by changing to tests while doing the imports.
Original error:
```
[12] Command:
cd ../src/firecracker && cargo pkgid | cut -d# -f2 | cut -d: -f2
[12] stdout:
[12] stderr:
/bin/sh: 1: cd: can't cd to ../src/firecracker
Returned error code: 2
stderr:
/bin/sh: 1: cd: can't cd to ../src/firecracker
```
...
...
---
> fix(create-snapshot): workaround tests directory

- resources/seccomp/aarch64-unknown-linux-musl.json
- resources/seccomp/x86_64-unknown-linux-musl.json
- src/devices/src/virtio/net/device.rs
- src/devices/src/virtio/net/iovec.rs
- src/devices/src/virtio/net/mod.rs
- src/devices/src/virtio/net/tap.rs
- src/devices/src/virtio/net/test_utils.rs
- src/mmds/src/ns.rs
- tests/integration_tests/build/test_coverage.py
- tests/integration_tests/performance/configs/test_network_latency_config_4.14.json
- tests/integration_tests/performance/configs/test_network_latency_config_5.10.json
- tests/integration_tests/performance/configs/test_network_tcp_throughput_config_4.14.json
- tests/integration_tests/performance/configs/test_network_tcp_throughput_config_5.10.json
Currently, when performing TX, a network frame might be exist in various scattered in various memory regions described by a `DescriptorChain` that we receive from the guest. In order to write the frame to the tap device we first perform a number of copies from said memory buffers to a single buffer which we then write to the `Tap` file descriptor.
This PR reverts that, to use scatter-gather IO using the `writev` system call which avoids the intermediate memory copies.
Fixes #420
The main blocker for using the `writev` system call in our device is that we need to be able to inspect the outgoing frame to check if it is destined towards `mmds`. This requires us to read at least the frame headers which makes the code quite convoluted.
In order to do this in a clean way, I introduce an `IoVec` …
> Use `writev` for writing guest outgoing packets to the tap device

- src/devices/src/virtio/net/device.rs
- src/devices/src/virtio/net/persist.rs
- src/devices/src/virtio/net/tap.rs
- src/devices/src/virtio/net/test_utils.rs
- src/vmm/src/vmm_config/net.rs
- tests/integration_tests/build/test_coverage.py
Specify the tap name in unittests via `%d` to make the kernel pick a name for us that is ensured to not be in used by a separate process already.
spurious failures with "device busy" because of name clashes with tap devices. 
---
> Have kernel pick tap device name for us in unittests

- Cargo.lock
- src/api_server/src/parsed_request.rs
- src/devices/src/bus.rs
- src/devices/src/legacy/i8042.rs
- src/devices/src/virtio/vsock/csm/mod.rs
- src/jailer/Cargo.toml
- src/jailer/src/main.rs
- src/mmds/Cargo.toml
- src/mmds/src/data_store.rs
- src/mmds/src/lib.rs
- src/mmds/src/token.rs
- src/seccompiler/Cargo.toml
- src/seccompiler/src/backend.rs
- src/seccompiler/src/compiler.rs
- src/seccompiler/src/seccompiler_bin.rs
- tests/integration_tests/build/test_coverage.py
changed these packages implementation to use thiserror::Error instead implements fmt::Display.
- api_server
- mmds
- devices
- seccompiler
- jailer
This PR will fix partof https://github.com/firecracker-microvm/firecracker/issues/3278
---
> use thiserror::Error for more packages

- tests/integration_tests/performance/configs/test_vsock_throughput_config_5.10.json
Update performance baselines for vsock throughput.
AMI update.
- ~[ ] New `unsafe` code is documented.~
- ~[ ] All added/changed functionality is tested.~
---
- ~[ ] This functionality can be added in [`rust-vmm`][1].~
[2]: …
> perf: vsock: update baselines

- tests/framework/microvm.py
- tests/host_tools/memory.py
- tests/integration_tests/performance/test_network_latency.py
Due to some recent change, pytest can hang waiting for monitoring threads to run.
We fix it by:
1. Marking those threads as daemonic, which will help pytest finish [1]
2. Explicitly kill the VM of the affected test
With those fixes (only 1. may be required), pytest finishes as expected.
[1]: https://stackoverflow.com/questions/19219596/py-test-hangs-after-showing-test-results
...
...
---
> fix(tests): mark monitoring threads as daemonic

- tests/integration_tests/functional/test_logging.py
Now, it doesn't tear apart the tag anymore if there's a space in it, meaning we no longer get spurious failures in the above case.
Occasionally, the first logging message from a VM would be from a vcpu thread, which is named `fc_vpu 0` or similar. The previous logic would then split on spaces, assuming that the "tag" part of the message doesnt contain a space. This could lead to spurious failures, such as https://buildkite.com/firecracker/firecracker-pr/builds/326#01855e8c-a886-471b-8b1d-b9f7db3f9595
---
> Make test_logging correctly handle case where threadname has space

- .gitignore
- src/firecracker/tests/verify_dependencies.rs
- tests/integration_tests/build/test_coverage.py
- tests/integration_tests/build/test_unittests.py
- tools/devctr/Dockerfile.aarch64
- tools/devctr/Dockerfile.x86_64
- tools/devctr/poetry.lock
- tools/devtool
Changes code coverage to [grcov](https://github.com/mozilla/grcov).
kcov outputs inaccurate coverage.
---
> Update code coverage to grcov

- tools/devctr/Dockerfile.aarch64
- tools/devctr/Dockerfile.x86_64
- tools/devtool
Updates Rust to 1.66.1.
Addresses https://blog.rust-lang.org/2023/01/10/cve-2022-46176.html.
---
> build: Rust 1.66.1

- .gitignore
- CHANGELOG.md
- src/firecracker/tests/verify_dependencies.rs
- tests/integration_tests/build/test_coverage.py
- tests/integration_tests/build/test_unittests.py
- tools/devctr/Dockerfile.aarch64
- tools/devctr/Dockerfile.x86_64
- tools/devctr/poetry.lock
- tools/devtool
Back ports https://github.com/firecracker-microvm/firecracker/pull/3362.
See https://github.com/firecracker-microvm/firecracker/pull/3362.
---
> Firecracker v1.2 backport 1.66.1

- .gitignore
- .gitlint
- CHANGELOG.md
- tests/integration_tests/build/test_coverage.py
- tests/integration_tests/build/test_pylint.py
- tests/integration_tests/build/test_unittests.py
- tools/devctr/Dockerfile.aarch64
- tools/devctr/Dockerfile.x86_64
- tools/devctr/poetry.lock
- tools/devtool
Back ports https://github.com/firecracker-microvm/firecracker/pull/3362.
See https://github.com/firecracker-microvm/firecracker/pull/3362.
---
> Firecracker v1.1 backport 1.66.1

- tools/devctr/Dockerfile.aarch64
- tools/devctr/Dockerfile.x86_64
- tools/devtool
Reverts removed of:
```
&& rm -rf "$CARGO_HOME/registry" \
&& ln -s "$CARGO_REGISTRY_DIR" "$CARGO_HOME/registry" \
&& rm -rf "$CARGO_HOME/git" \
&& ln -s "$CARGO_GIT_REGISTRY_DIR" "$CARGO_HOME/git"
```
made in cbc073800c701294025372ea10ba6dfce6731e3d
`cargo audit` was timing.
---
> fix: cargo audit timeout

- src/dumbo/src/pdu/bytes.rs
Previously indexing only checked that `offset` was within the range of `self` but not that the given `value` could fit within the range of `self` starting from `offset`. This could previously lead to bytes not being written and the function not panicking,
Restricts assertions on `htons_unchecked` and `htonl_unchecked`.
Previously indexing only checked that `offset` was within the range of `self` but not that the given `value` could fit within the range of `self` starting from `offset`. This could previously lead to bytes not being written and the function not panicking.
---
[2]: https://github.com/firecracker-microvm/firecracker/blob/main/docs/ …
> fix: `htons_unchecked` and `htonl_unchecked`

- tests/framework/artifacts.py
Updates kernel selection mechanism in `artifacts.py`
Currently guest kernels are selected by searching a sub-string in kernel name.
This can lead to incorrect selection. If we have kernels: [5.10, 5.10-a, 5.10-b] and supported kernel is 5.10 then all 3 kernels will be selected. With this PR only 5.10 kernel will be selected.
---
> Better guest kernel selection

- .buildkite/pipeline_pr.py
- docs/RELEASE_POLICY.md
- src/vmm/src/version_map.rs
Add a supported releases table and also skip running integration tests if we only have doc changes. This would only work for future PRs, since changing that logic itself is a code change.  
...
---
> Doc fixes and skip builds if doc changes only

- src/dumbo/src/lib.rs
- src/dumbo/src/pdu/tcp.rs
Fix the documentation with comment with correct description of functionality and panic condition.
Also, add a comment on to why we cannot cause a panic when reading a TCP payload in a slice.
dumbo crate's `ByteBuffer` `read_to_slice` documentation was describing wrong the functionality of the function and the condition under which it may panic.
---
> Fix the documentation in function of dumbo crate

- tests/integration_tests/performance/configs/test_snap_restore_performance_config_5.10.json
Update the baselines.
There is an improvement in snapshot/restore performance of about 7% on ARM, 5.10 kernel:
```
{
"source": "dcf56c3a59168b47a435089d47b27a7945cc86db/tests/integration_tests/performance/configs/",
"test_snap_restore_performance_config_5.10.json": {
"test": "snap_restore_performance",
"kernel": "5.10",
"cpus": [
{
"stats": {
"latency": {
"mean": -7.308976464469347,
"stdev": 1.8383303612453021
},
"mean": 4.62,
"stdev": 22.954403639925967
}
}
}
}
]
}
}
```
---
[2]: …
> perf: update snapshot baselines for ARM 5.10

- tests/integration_tests/performance/configs/test_block_performance_config_4.14.json
- tests/integration_tests/performance/configs/test_block_performance_config_5.10.json
- tests/integration_tests/performance/configs/test_network_latency_config_4.14.json
- tests/integration_tests/performance/configs/test_network_latency_config_5.10.json
- tests/integration_tests/performance/configs/test_network_tcp_throughput_config_4.14.json
- tests/integration_tests/performance/configs/test_network_tcp_throughput_config_5.10.json
- tests/integration_tests/performance/configs/test_snap_restore_performance_config_4.14.json
- tests/integration_tests/performance/configs/test_snap_restore_performance_config_5.10.json
- tests/integration_tests/performance/configs/test_vsock_throughput_config_4.14.json
- tests/integration_tests/performance/configs/test_vsock_throughput_config_5.10.json
- tests/integration_tests/performance/test_boottime.py
- Updates performance baselines for snapshot/restore test on all supported x86-64 CPUs.
- Updates performance baselines for other tests on m5d.metal (Skylake + Cascade Lake)
- Updates target value of boot time with initrd on Skylake
To improve security and make our test environment similar with the recommended production environment, we disabled SMT on all supported x86-64 CPUs and enabled L1TF mitigation (unconditional L1D flush).
SMT disabling reduced the number of CPUs on x86-64. Since some KVM calls (like `KVM_CREATE_VM` and `KVM_CREATE_VCPU`) include per-cpu operations, snapshot restore performance was improved.
L1TF mitigation enables [unconditional L1D cache flush on VMENTER][3] and results in some performance decreases on Skylake.
By submitting this pull request, I confirm that my …
> perf: Update performance baselines

- Cargo.lock
- tests/integration_tests/performance/test_boottime.py
We do not use bumpalo in production code, as its only a transitive dependency of criterion (and there, only for web assembly targets). Nevertheless, cargo audit reports a vulnerability in it, and since we block our CI on cargo audit reports, this needs to be fixed as 1.1 is still support (so we need to be able to merge PRs)
...
...
---
> Update bumpalo 3.9.1 -> 3.12.0

- tests/conftest.py
When cleaning up microvm_factory fixture, remove resource directory that contains data related to all microvms created via the factory.
If the fixture is called many times within a pytest session, it accumulates artifacts from all microvms it creates, which may lead to running out of space.
- ~~[ ] New `unsafe` code is documented.~~
---
[1]: …
> test: remove resource dir when cleaning up microvm_factory

- src/devices/src/virtio/balloon/utils.rs
- src/devices/src/virtio/block/device.rs
- src/devices/src/virtio/block/event_handler.rs
- src/devices/src/virtio/block/request.rs
- src/devices/src/virtio/block/test_utils.rs
- src/devices/src/virtio/net/device.rs
- src/devices/src/virtio/net/mod.rs
- src/devices/src/virtio/net/persist.rs
- src/devices/src/virtio/net/test_utils.rs
- src/devices/src/virtio/queue.rs
- src/devices/src/virtio/test_utils.rs
- src/devices/src/virtio/vsock/test_utils.rs
- src/vmm/src/vmm_config/net.rs
- tests/integration_tests/build/test_coverage.py
Refractors some of the virtio test_utils code to deduplicate it. 
Improving maintainability of our test code
---
> Test utils cleanup

- resources/tests/setup_rootfs.sh
Removes `strings` package from rootfs.
`strings` package was added in the part of spectre/meltdown checker test on guests in this commit 42b78fda2a87ebbcdde06f9984d26366d0aea3ce. But actually the installation fails with "E: Unable to locate package strings." error, although it logs "Successfully built rootfs!". Since this package is not the strict requirement for the test, this commit removes the package to prevent rootfs build failures.
- ~~[ ] New `unsafe` code is documented.~~
- ~~[ ] API changes follow the [Runbook …
> fix: Remove strings from rootfs

- .github/pull_request_template.md
- CONTRIBUTING.md
Removed the ``New `unsafe` code is documented.`` checkpoint from the PR template
This is covered by the `clippy::undocumented_unsafe_blocks` lint.
---
> chore: Remove `unsafe` checkpoint from PR template

- tests/integration_tests/functional/test_balloon.py
A 1 second delay is added after the inflation request to give the stats time to update.
Since the configured stats polling interval is 1 second, it may take up to 1 second for the `available_memory` stat to get updated.
In some cases, the VM is snapshotted, restored and the `available_memory` stat is queried before the 1 second has passed after an inflation had been requested.
- ~~[ ] New `unsafe` code is documented.~~
- ~~[ ] User-facing changes …
> fix(tests): test_balloon_snapshot: add delay after inflate

- tests/integration_tests/performance/test_process_startup_time.py
Updates Arm start-up time.
There appears to have been a regression in Arm start-up.
---
> test: Update Arm start-up time

- src/devices/src/virtio/net/device.rs
- src/devices/src/virtio/net/iovec.rs
- src/devices/src/virtio/net/tap.rs
- tests/integration_tests/build/test_coverage.py
Avoid making a slice out of raw guest physical memory for `IoVecBuffer`s. Instead use directly `libc::iovec` to describe the buffers and, in order to have vectored writes for tap devices, call directly `libc::writev`.
The way we implemented `IoVecBuffer` was leading to potentially undefined behaviour. We were creating a normal slice from guest physical memory. Although, with well-behaved drivers this should be fine, a driver that touches that memory after adding the buffer in the queue and before the device adds it in the used queue, would cause undefined behaviour due to the aliasing requirements of Rust for slices.
---
[2]: …
> fix(virtio): undefined behaviour in net `writev` implementation

- src/devices/src/virtio/net/iovec.rs
We adjust the `len` parameter passed to `std::ptr::copy_nonoverlapping` to `end - start`, and add a tests that verifies that no bytes are written beyond the end of the slice passed to `read_at`.
The std::ptr::copy_nonoverlapping call used to copy into buf[buf_start..buf_end] was instructed to copy `end - start + 1` bytes, however `buf_end - buf_start` is exactly `end - start` (without the +1) long, since the upper bound of the slice is not inclusive. This would lead to either 1 byte being written past the end of `buf`, or 1 byte being read past the end of the last iovec.
---
[2]: …
> Fix off-by-one in iovec.rs

- src/cpuid-templates/Cargo.toml
- src/vmm/Cargo.toml
- src/vmm/src/vstate/vcpu/x86_64/cpuid_templates.rs
- src/vmm/src/vstate/vcpu/x86_64/mod.rs
- tests/integration_tests/build/test_coverage.py
Apply `#[cfg(target_arch = "x86_64")]` to CPUID template to avoid compiling them on Arm.
Minimizes negative impact on Arm coverage.
---
> fix: Exclude CPUID templates on Arm

- src/devices/src/virtio/net/iovec.rs
- src/dumbo/src/tcp/connection.rs
See #3402 for reference.
Link to MMDS documentation in dumbo and fix a safety comment in iovec.rs
The only reason we are able to simplify our TCP/IP stack in the way we do it because the traffic handled by it never leaves the microVM. However, the current comments in the code do not provide this justification. 
---
> Small documentation/code comment clarifications

- .gitignore
- Cargo.lock
- src/api_server/Cargo.toml
- src/api_server/src/parsed_request.rs
- src/arch/Cargo.toml
- src/arch/src/aarch64/cache_info.rs
- src/cpuid/Cargo.toml
- src/devices/Cargo.toml
- src/devices/src/virtio/net/tap.rs
- src/devices/src/virtio/queue.rs
- src/io_uring/Cargo.toml
- src/mmds/Cargo.toml
- src/mmds/src/data_store.rs
- src/mmds/src/token.rs
- src/seccompiler/Cargo.toml
- src/seccompiler/src/backend.rs
- src/seccompiler/src/compiler.rs
- src/seccompiler/src/lib.rs
- src/seccompiler/src/seccompiler_bin.rs
- src/vmm/Cargo.toml
- src/vmm/src/device_manager/mmio.rs
- src/vmm/src/device_manager/persist.rs
- src/vmm/src/rpc_interface.rs
- src/vmm/src/vmm_config/drive.rs
- src/vmm/src/vmm_config/net.rs
- tests/integration_tests/build/test_coverage.py
- tests/integration_tests/functional/test_api.py
- tests/integration_tests/functional/test_max_devices.py
- tests/integration_tests/functional/test_net.py
* be consistent when referring to the block device (sometimes it would be block device, sometimes drive)
* remove unused error entry
...
---
> rename error on block device update

- tests/host_tools/memory.py
- tests/integration_tests/functional/test_snapshot_basic.py
This change adds support for multiple regions in the memory monitor and enables memory monitor for test_create_large_diff_snapshot test.
Before the change, the memory monitor could not work with guests with large memory (>3328M) on x86_64.
Resolves: https://github.com/firecracker-microvm/firecracker/issues/3349
---
[2]: https://github.com/firecracker-microvm/firecracker/blob/main/docs/ …
> Support multiple regions in memory monitor

- docs/api_requests/patch-block.md
- docs/getting-started.md
- docs/prod-host-setup.md
* Add description of block device resource management with an updated API call sample of how to configure the rate limiter on a block device.
* Add some pointers for troubleshooting API usage with `curl`
> Doc updates for block device rate limiting and API usage

- .cargo/config
- src/api_server/src/lib.rs
- src/arch/src/lib.rs
- src/cpuid/src/lib.rs
- src/devices/src/lib.rs
- src/dumbo/src/lib.rs
- src/firecracker/src/main.rs
- src/io_uring/src/lib.rs
- src/jailer/src/main.rs
- src/logger/src/lib.rs
- src/mmds/src/lib.rs
- src/rate_limiter/src/lib.rs
- src/rebase-snap/src/main.rs
- src/seccompiler/src/lib.rs
- src/snapshot/src/lib.rs
- src/utils/src/lib.rs
- src/vm-memory/src/lib.rs
- src/vmm/src/lib.rs
- src/vmm/src/persist.rs
Collected clippy warnings in the `.cargo/config`.
Keeps clippy lints consistent across crates
---
> fix: Move clippy warnings into `.cargo/config`

- tests/framework/artifacts.py
- tests/framework/builder.py
This commit puts guest MAC address into `NetIfaceConfig` and generates it in its `__init__()`.
Guest MAC address was generated in `MicrovmBuilder` and this makes code difficult to read. 
---
[2]: …
> refactor: put guest MAC addr into NetIfaceConfig

- src/vmm/src/cpuid/amd/mod.rs
- src/vmm/src/cpuid/cpuid_ffi.rs
- src/vmm/src/cpuid/intel/mod.rs
- src/vmm/src/cpuid/mod.rs
- src/vmm/src/vstate/vcpu/x86_64/mod.rs
- tests/integration_tests/build/test_coverage.py
Passes portions of the host CPUID through to the guest depending on the CPUID template.
In setting CPUID a user will typically want to pass-through most values and only specify a few. These values can relate to cache topology and be very tricky to specify in a template. In this case we need CPUID to support setting specific leaves and passing-through others.
---
> fix: CPUID pass-through

- README.md
- docs/snapshotting/snapshot-support.md
- Adds m6i.metal (Intel Ice Lake) and c7g.metal (ARM64 Neoverse V1). 
- Fixes AMD Zen 2 to AMD Zen 3 since m6a.metal is EPYC 7003 family.
---
> docs: update supported platforms

- tests/framework/utils.py
The Ubuntu 22.04 upgrade brings some different behavior for the `top` command, where it truncates long lines with '+'.
...
---
> Fix perf tests

- tests/integration_tests/performance/test_snapshot_perf.py
- Update baselines for the snapshot performance test for x86
- Update doc to point to the use of cgroups V1 with x86 platforms (which result in high latencies)
Intermittent failures were noticed on kernel 5.10 & x86 platforms
---
[2]: …
> perf: update snaphot perf baselines for x86/5.10

- src/vmm/src/cpuid/normalize.rs
- tests/integration_tests/build/test_coverage.py
Adds unit test to `get_max_cpus_per_package_test()` within `src/vmm/src/cpuid/normalize.rs`.
Improves testing coverage.
---
> refactor: cpuid `get_max_cpus_per_package_test()`

- src/cpuid/src/transformer/intel.rs
- tests/integration_tests/build/test_coverage.py
To keep backward compatibility for guest VM CPU topology, the sub-leaf is added as needed.
The following commit changed the bahavior of KVM_GET_SUPPORTED_CPUID to no longer include leaf 0xb / sub-leaf 1.
https://lore.kernel.org/all/20221027092036.2698180-1-pbonzini@redhat.com/ 
--- …
> fix(cpuid): add leaf 0xb / subleaf 1 as needed

- CONTRIBUTING.md
This corrects this.
The commit title limit was updated to 72 characters in 3cc09c2 but this was not updated to match.
---
> docs: Fix commit title to 72 character limit

- tests/integration_tests/performance/test_block_performance.py
- tests/integration_tests/performance/test_network_tcp_throughput.py
- tests/integration_tests/performance/test_vsock_throughput.py
Since the Ubuntu 22 update we find there may be more than a thread with the firecracker name. We don't know exactly this can happen, but it doesn't change the result of the test.
...
...
~- [ ] All added/changed functionality is tested.~
---
[2]: …
> fix(tests): accept multiple firecracker threads with the same name

- tests/integration_tests/build/test_binary_size.py
Update the size of the firecracker binary in test.
Binary size has increased
---
> virtio-rng: update Firecracker binary size in test

- .github/pull_request_template.md
- CONTRIBUTING.md
Added in our documentation explicit reference to the Developer Certificate of Origin (DCO) mechanism used by this project.
We have been following DCO guidelines since the beginning of Firecracker and recently we even added a DCO app to validate automatically that contributions conform to such process. We are aligning our documentations to explicitly call out DCO policy and help a member of the community to be informed when contributing into the project.
~~- [ ] All …
> Update contributing guidelines with DCO references

- src/vmm/src/cpuid/amd/indexing.rs
- src/vmm/src/cpuid/amd/normalize.rs
- src/vmm/src/cpuid/common.rs
- src/vmm/src/cpuid/cpuid_ffi.rs
- src/vmm/src/cpuid/indexing.rs
- src/vmm/src/cpuid/intel/indexing.rs
- src/vmm/src/cpuid/intel/normalize.rs
- src/vmm/src/cpuid/mod.rs
- tests/integration_tests/build/test_coverage.py
Reduce occurrences of the `unsafe` keyword and adds additional documentation where present.
Improves documentation on possibly unsafe areas of code.
---
> fix: Documenting `unsafe` in CPUID

- tests/conftest.py
- tests/integration_tests/performance/configs/test_block_performance_config_4.14.json
- tests/integration_tests/performance/configs/test_block_performance_config_5.10.json
- tests/integration_tests/performance/configs/test_network_latency_config_4.14.json
- tests/integration_tests/performance/configs/test_network_latency_config_5.10.json
- tests/integration_tests/performance/configs/test_network_tcp_throughput_config_4.14.json
- tests/integration_tests/performance/configs/test_network_tcp_throughput_config_5.10.json
- tests/integration_tests/performance/configs/test_snap_restore_performance_config_4.14.json
- tests/integration_tests/performance/configs/test_snap_restore_performance_config_5.10.json
- tests/integration_tests/performance/configs/test_vsock_throughput_config_4.14.json
- tests/integration_tests/performance/configs/test_vsock_throughput_config_5.10.json
- tools/parse_baselines/main.py
- tools/parse_baselines/providers/types.py
Update perf baselines for block 5.10 async
Latest 5.10 kernel got a backport of 5.15 io_uring, with some performance changes. Overall it looks like a (small) net improvement.
```
{
"source": "3c2ba1048853afaac5a994f0cf90f02d5ff812bf/tests/integration_tests/performance/configs/",
"test_block_performance_config_5.10.json": {
"test": "block_performance",
"kernel": "5.10",
"cpus": [
{
"instance": "m5d.metal",
"model": "Intel(R) Xeon(R) Platinum 8175M CPU @ 2.50GHz",
"stats": {
"iops_read": {
"mean": 2.0112673185925574,
"stdev": 11.81608701300763
},
"mean": 0.5,
"stdev": 3.8015277064919317
}
},
"mean": 0.21311119987145952, …
```
> Update perf baselines for block 5.10 async

- tests/host_tools/memory.py
Reduce memory monitor sample timeout from 1 second to 50 milliseconds to decrease probability of false negatives.
Since most of the tests run microVMs for a very short period of time, memory monitor often does not have a chance to execute and inspect Firecracker's address space.
A simple example: test_api_happy_start().
The change below makes the VM run for 200 milliseconds longer and counts the guest memory in as Firecracker's own memory to trigger a problem that the memory monitor should spot. The memory monitor should have noticed the excessive memory usage, but it did not, because it never saw the address space with the guest in it.
```
diff --git a/tests/host_tools/memory.py b/tests/host_tools/memory.py
index 0d160aa4..032984cc 100644
--- a/tests/host_tools/memory.py
+++ …
```
> fix(tests): reduce memory monitor sample timeout

- src/vmm/src/cpuid/intel/indexing.rs
Correct leaf 0x12 indexing
The previous implementation could return multiple mutable references to the same value, this fix corrects this.
---
> Cpuid leaf12

- src/devices/tests/integration_tests.rs
- src/devices/tests/serial_utils/mod.rs
- src/io_uring/tests/integration_tests.rs
- src/io_uring/tests/test_utils/mod.rs
- src/vmm/tests/integration_tests.rs
Fix/Suppress clippy lints in-line with test modules
For some reason, these are not picked up by `cargo clippy --all`, only if the `--fix` flag is also passed. This is messing up my pre-commit hook.
---
> Fix clippy lints in rust integration tests

- src/vmm/src/cpuid/amd/normalize.rs
- src/vmm/src/cpuid/cpuid_ffi.rs
- src/vmm/src/cpuid/mod.rs
Reduced std `unchecked` calls.
Avoids `unsafe`.
---
> fix: Reduce std `unchecked` calls

- tests/framework/utils.py
- tests/host_tools/cpu_load.py
- tests/integration_tests/functional/test_rate_limiter.py
- tools/devtool
We used to get CI failures resulting from
```
File "/firecracker/tests/host_tools/cpu_load.py", line 70, in run
cpu_load = utils.ProcessManager.get_cpu_percent(self._process_pid)["real"]
KeyError: 'real'
```
At some point, pytest started to only issue warnings on exception in non-main threads, instead of failing the test. This means that it looked like these spurious failures went away, even though they really did not.
The CPU load monitor in its current form was broken, as the `get_cpu_percent` function returns a dictionary mapping process names to CPU utilization of each individual thread (despite it being annotated to return a single float). However, CpuLoadMonitor expected that dictionary to contain the cpu utilization under a key named 'real'. I'm assuming at some point in the past, …
> Fix CPU Load Monitor silently crashing

- tests/framework/builder.py
- tests/framework/microvm.py
- tests/integration_tests/performance/test_block_performance.py
- tests/integration_tests/performance/test_network_latency.py
- tests/integration_tests/performance/test_network_tcp_throughput.py
- tests/integration_tests/performance/test_snapshot_restore_performance.py
- tests/integration_tests/performance/test_vsock_throughput.py
Disable the memory monitor for nightly performance tests
Since the monitor's sampling rate was increased to 20 times per second, it seemingly started to interfere with the results of the performance tests.
---
> Disable memory monitor for nightly performance tests

- tests/integration_tests/performance/test_snapshot_restore_performance.py
Remove completely the usage of memory monitor in the snapshot restore latency test.
This is related to: https://github.com/firecracker-microvm/firecracker/pull/3454
---
> fix: memory monitor usage removed from snap restore test

- src/seccompiler/src/compiler.rs
- src/seccompiler/src/seccompiler_bin.rs
Replace HashMap usage in `seccomp` with BTreeMap to preserve order of items.
This enable reproducible builds (see issue #3439) 
fixes #3439 
---
> Use a deterministic hashmap for reproducible builds

- tests/integration_tests/performance/configs/test_vsock_throughput_config_4.14.json
- tests/integration_tests/performance/configs/test_vsock_throughput_config_5.10.json
Update vsock throughput baselines for `m5d` with kernels `4.14` and `5.10` and `m6i` with kernel `5.10`.
We have seen that in these two instance types and related kernel versions vsock throughput tests have been flaky. The only change that has been committed to the repo around the time the tests started failing was the upgrade to Ubuntu 22.04 of our dev container.
---
[3]: …
> Update vsock baselines

- .buildkite/common.py
- .buildkite/pipeline_perf.py
- .buildkite/pipeline_pr.py
Clearly specify the OS of the agents on which PR pipeline should run. 
---
> chore: add os tag to agent config of pipelines

- src/arch/src/x86_64/cpu_model.rs
- src/arch/src/x86_64/mod.rs
- src/cpuid/src/template/intel/t2cl.rs
- src/cpuid/src/transformer/mod.rs
- src/vmm/src/vstate/vcpu/x86_64.rs
- tests/framework/utils_cpu_templates.py
- tests/integration_tests/build/test_coverage.py
- tests/integration_tests/functional/test_cpu_features.py
Add a runtime check that T2CL CPU template can only be used on Cascade Lake or newer Intel CPUs.
The T2CL CPU template is only applicable to Cascade Lake and newer Intel CPUs. We need to guarantee it cannot be used on older versions.
- ~~[ ] New `TODO`s …
> Do not allow using T2CL on Intel Skylake

- src/arch/src/x86_64/cpu_model.rs
- src/cpuid/src/template/intel/t2cl.rs
- tests/integration_tests/build/test_coverage.py
Add fine-grained unittests for the T2CL CPU template. This is to avoid separate coverage targets for Skylake and non-Skylake CPUs.
The T2CL CPU template code needs explicit coverage as the coarse-grained test in vmm is not executed for the T2CL on a Skylake.
- ~~[ ] User-facing changes are mentioned in …
> Add unittests for T2CL CPU template

- tests/integration_tests/performance/configs/test_network_latency_config_4.14.json
- tests/integration_tests/performance/configs/test_network_tcp_throughput_config_4.14.json
- tests/integration_tests/performance/configs/test_vsock_throughput_config_4.14.json
Fixes: 0f224d0f8a80c13f06121f14f92b8509e0f22f86
Complete the performance baselines for c7g on linux 4.14
Last PR was missing the 4.14
---
~- [ ] This functionality can be added in [`rust-vmm`][1].~
[1]: …
> chore: new c7g.metal performance baselines

- .buildkite/common.py
- .buildkite/pipeline_perf.py
- src/devices/src/virtio/block/device.rs
- src/devices/src/virtio/block/mod.rs
- tests/conftest.py
- tests/framework/builder.py
- tests/framework/microvm.py
- tests/integration_tests/functional/test_api.py
- tests/integration_tests/functional/test_feat_parity.py
- tests/integration_tests/performance/test_snapshot_perf.py
- tests/integration_tests/security/test_jail.py
- tools/create_snapshot_artifact/main.py
More integration tests cleanups
- Removing more uses of TestMatrix
- Clearing the way for further cleanups
- 
---
~- [ ] This functionality can be added in [`rust-vmm`][1].~
[2]: …
> Integration tests cleanups

- MAINTAINERS.md
- docs/RELEASE_POLICY.md
- Update a list of maintainers.
- Update release status table along with firecracker v1.3.0 release.
...
---
- ~~[ ] This functionality can be added in …
> chore: update maintainers and release status table

- src/uffd_handler/src/handler.rs
- src/uffd_handler/src/main.rs
- src/uffd_handler/src/memory_region.rs
Add sanity checks for information received from Firecracker through UDS.
Ensure the mappings received through UDS are not corrupted.
---
[3]: …
> UFFD: Add sanity checks for information received through UDS

- tests/integration_tests/functional/test_cpu_features.py
This change includes T2CL CPU template that was previously removed into rdmsr/wrmsr tests.
The T2CL CPU template had been removed by mistake during refactoring.
---
[2]: …
> fix(tests): include t2cl back in rdmsr/wrmsr tests

- src/vmm/src/version_map.rs
- tests/integration_tests/functional/test_snapshot_version.py
Cherry-picks the snapshot version bump from the 1.3 release branch, as well as introduces a regression test (thanks to pablob@ for the code!) that ensure we do not forget to bump snapshot version prior to a release again.
We forgot to bump snapshot version prior to releasing 1.3.0
---
> Snapshot bump

- docs/getting-started.md
Updates `getting-started.md`.
The example now involves setting up a microVM you can SSH into.
See https://github.com/JonathanWoollett-Light/firecracker/blob/getting-started/docs/getting-started.md.
Some of the instructions are out-dated and it is missing a simple guide to ssh into a microVM.
---
> docs: Update `getting-started.md`

- tests/integration_tests/functional/test_cpu_features.py
Bit 0-7 of ICR 0x830 and SelfIPI 0x83F MSR represent interrupt vector numbers which could vary so add the 2 MSRs to the exception list.
Ignore MSR 0x830 and 0x83F when comparing MSR states before and after the snapshot-restore.
Bit 0-7 of ICR 0x830 and SelfIPI 0x83F MSR represent interrupt vector numbers which could vary so MSR values before and after snapshot-restore could be different.
~~- [ ] New `TODO`s …
> fix: ignore Inter processor interrupt MSRs

- tests/integration_tests/functional/test_cpu_features.py
While running snapshot test multiple times on the same instance, the snapshot test fails while trying to create artifacts directory if the old artifact directories are not deleted manually so, delete old artifacts directories and create clean directory before taking a new snasphot to avoid such failures.
To reproduce the issue run below command, twice back to back, manually (not through buildkite) on an instance :
> tools/devtool -y test -- -s --nonci integration_tests/functional/test_cpu_features.py -k 'test_cpu_cpuid_snapshot or test_cpu_wrmsr_snapshot'
Use a new function to delete existing old artifacts directory and create clean directory before taking a snapshot.
Snapshot test fails while creating an artifact directory if old artifact directory is not removed manually.
By submitting …
> fix: create clean artifact dir for taking snapshot

- .cargo/config
- src/arch/src/aarch64/gic/gicv2/regs/mod.rs
- src/arch/src/aarch64/gic/gicv3/regs/icc_regs.rs
- src/arch/src/aarch64/gic/gicv3/regs/mod.rs
- src/arch/src/aarch64/gic/gicv3/regs/redist_regs.rs
- src/arch/src/x86_64/interrupts.rs
- src/devices/src/virtio/net/tap.rs
- src/devices/src/virtio/net/test_utils.rs
- src/devices/src/virtio/vsock/test_utils.rs
- src/devices/src/virtio/vsock/unix/muxer.rs
- src/io_uring/src/lib.rs
- src/io_uring/src/operation/cqe.rs
- src/io_uring/src/queue/submission.rs
- src/io_uring/tests/test_utils/mod.rs
- src/rate_limiter/src/lib.rs
- src/seccompiler/src/backend.rs
- src/utils/src/byte_order.rs
- src/utils/src/kernel_version.rs
- src/utils/src/lib.rs
- src/utils/src/time.rs
- src/vmm/src/signal_handler.rs
- src/vmm/src/vstate/vcpu/x86_64.rs
Sets clippy to warn on the lint `clippy::cast_sign_loss` as mentioned in #3200
Sets the `-Dclippy::cast_sign_loss` flag and fixes existing issues. I could not identify any real cast issues, so this PR adds a few documented `#[allow(clippy::cast_sign_loss)]`. Many casts are caused by signed integer return values from libc.
Closes #3200
---
> Warn on `clippy::cast_sign_loss`

- src/vmm/src/builder.rs
- src/vmm/src/guest_config/aarch64/mod.rs
- src/vmm/src/guest_config/mod.rs
- src/vmm/src/guest_config/x86_64/mod.rs
- src/vmm/src/vstate/vcpu/aarch64.rs
- src/vmm/src/vstate/vcpu/mod.rs
- src/vmm/src/vstate/vcpu/x86_64/mod.rs
* Common types to be used by Firecracker for configuring guest vCPUs.
Common types for CPU templates to be applied by `vmm` crate to configure guest vCPUs.
> Define base CPU config types

- .github/workflows/send_pr_notification.yml
> feat: send notification when  pr opened

- .github/workflows/send_pr_notification.yml
This is a fix of 0d68b15d8fcfd15da70adf405d1a536c89ca3e06. Unfortunately, the `if:` tag from GitHub action definition doesn't work as expected when comparing with a label that contains special characters such as `:`. I tried a couple of suggestions to escape that but none of then worked. However, filtering out the labels directly in the `run` tag works.
Fix tested successfully in a couple of situations such as:
- adding a different tag
- adding `Status: Reviewer`
- adding a different tag (after already tagged as `Status: Reviewer`)
---
[1]: …
> fix: fix Slack notification on pr

- .buildkite/common.py
- tests/integration_tests/style/test_python.py
- tools/devctr/poetry.lock
- tools/devtool
Updates poetry and suppresses black / pylint errors and warnings.
...
---
[3]: …
> tools: bump devctr version to v53

- tests/framework/utils.py
* Check to make sure the screen process in integration tests is started successfully.
* Check the parent process' status with a retry added to confirm the screen process is up and running.
* Try-and-except blocks added at multiple stages of the screen sessions startup for clearer error handling.
Motivated by a [build error in Buildkite for Firecracker's CI pipeline](https://buildkite.com/firecracker/firecracker-pr/builds/1013#01865063-028d-473b-8ffa-346e1388e5c1).
The `screen` application is used to boot up Firecracker in a detached mode, and is used to launch the Firecracker process (or Jailer as a wrapper) for integration tests to be run against. This results in two processes being launched, the screen process, and the binary application's process (that is a child process of the screen …
> Add error handling when screen/firecracker processes have not launched successfully

- resources/tests/build_kernel.sh
- tools/devctr/Dockerfile
- tools/devtool
Moves package installation to Dockerfile and packs required packages into devctr.
When building kernel, installing packages require the root permission. To make `tools/devtool build_kernel` pass without `sudo`, this commit packs required packages into devctr.
---
[1]: …
> tools: move package installation to Dockerfile

- src/vmm/src/builder.rs
- src/vmm/src/guest_config/aarch64/mod.rs
- src/vmm/src/guest_config/cpuid/mod.rs
- src/vmm/src/guest_config/mod.rs
- src/vmm/src/guest_config/templates/mod.rs
- src/vmm/src/guest_config/x86_64/mod.rs
- src/vmm/src/resources.rs
- src/vmm/src/vstate/vcpu/aarch64.rs
- src/vmm/src/vstate/vcpu/mod.rs
- src/vmm/src/vstate/vcpu/x86_64/mod.rs
- src/vmm/src/vstate/vm.rs
- tests/integration_tests/build/test_coverage.py
Changes extend [PR/3483](https://github.com/firecracker-microvm/firecracker/pull/3483/) that have the `*CpuConfiguration` types defined.
* CPU template types for x86_64 and aarch64.
* `apply_template()` function for x86_64 to use the template to create `X86_64CpuConfiguration`.
* CPU template types to be used to store the payload for `/cpu-config` API.
> CPU Template Wrapping and Deserialization

- tests/integration_tests/performance/configs/test_block_performance_config_4.14.json
- tests/integration_tests/performance/configs/test_network_latency_config_4.14.json
- tests/integration_tests/performance/configs/test_network_tcp_throughput_config_4.14.json
- tests/integration_tests/performance/configs/test_vsock_throughput_config_4.14.json
- Removes unnecessary baselines.
- Renames vmlinux-5.10.bin to vmlinux-5.10-no-sve.bin on host kernel v4.14.
- Regather baselines for network latency, network TCP throughput, and vsock thoughput for c7g.metal.
Thanks to PR #3539, some incorrect baseline definitions are detected.
Along with it, some performance improvements are found. Please see below for summary of performance changes.
```
{
"source": "b32b1ed8f91954ced122d36259bf598ad66db929/tests/integration_tests/performance/configs/",
"target": "f22cc5f29e37299dd2cd32d8bf7c904abbf5c25d/tests/integration_tests/performance/configs/",
"test_network_latency_config_4.14.json": {
"test": "network_latency",
"kernel": "4.14",
"cpus": [
{
"instance": "c7g.metal",
"model": "ARM_NEOVERSE_V1",
"stats": {
"pkt_loss": { …
```
> test: fix performance baseline definitions for c7g.metal

- resources/guest_configs/DISCLAIMER.md
Add a quick doc adding a disclaimer regarding the guest kernel config files regarding their use.
A query raised in [#3514](https://github.com/firecracker-microvm/firecracker/issues/3514) highlighted a behaviour attributed to a nuance of the kernel configurations.
> Add guest kernel configs disclaimer

- Cargo.lock
Update versionize to 0.1.10 due to [1].
[1]: https://github.com/firecracker-microvm/versionize/security/advisories/GHSA-8vxc-r5wp-vgvc
...
...
---
> Update versionize dependency

- .gitlint
Dependabot commit messages are constructed by including the changelog of the package for which dependabot PRs in an update. We have no control over how these packages write their commits messages, so just disable gitlint for them.
Dependabot does not seem to have an option for configuring the commit messages beyond the title line. However, even if there was such an option, the next problem would be that GitHub's security update PRs (which are separate from normal dependabot) ignore the `.github/dependabot.yml` configuration file.
See: https://jorisroovers.com/gitlint/configuration/
Dependabot PRs fail the gitlint style test
Developer …
> gitlint: Ignore dependabot commits

- .gitlint
Comments need to be their own lines in the .gitlint file format.
Dependabot PRs were still not passing CI
---
> Fix .gitlint comment

- Cargo.lock
- tests/integration_tests/functional/test_mmds.py
- tests/integration_tests/performance/test_snapshot_perf.py
Update versionize for 1.3  branch. Subsumes https://github.com/firecracker-microvm/firecracker/pull/3562
backport
---
> Update versionize on 1.3 release branch

- Cargo.lock
- tests/framework/artifacts.py
Update dependency and fix snapshot tests trying to load a 1.3.0 snapshot in 1.2.0
...
---
> Update versionize dependency for 1.2 release branch

- src/vmm/src/device_manager/legacy.rs
- src/vmm/src/vstate/system.rs
- src/vmm/src/vstate/vcpu/x86_64.rs
- tests/integration_tests/build/test_coverage.py
implement 
I changed vmm packages implementation to use thiserror::Error instead implements fmt::Display.
This PR will fix partof #3278 
---
> fix: use `thiserror::Error` in vmm

- tests/integration_tests/style/test_rust.py
Updates `test_ensure_mod_tests` to allow easier filtering.
It allows for easier filtering.
This was spawned from attempting to change the filter in https://github.com/firecracker-microvm/firecracker/pull/3528 and finding it awkward.
This change should also help support further checking:
1. Checking `mod tests` is at the end of the file.
2. Checking files with `mod tests` don't have `#[test]`s outside of this.
---
[3]: …
> test: Update `test_ensure_mod_tests`

- src/firecracker/src/api_server_adapter.rs
A race condition has been identified between the API thread and the VMM thread due to a misconfiguration of the `api_event_fd`. What happens actually behind is like this:
The API thread receives API requests that needs to be handled one by one. Handling a request by the API thread means the following actions:
1. Write the request on the channel to the VMM thread
2. Notify the VMM thread that it has a new request to handle
3. Call a blocking read on the channel from the VMM in order to get the results
On the VMM thread side, handling such a request represents the opposite actions:
1. Wait until getting notified that a new request needs its attention
2. Handle the request
3. Write the result on the channel to the API thread
4. Clear out the notification done by the API thread about the …
> Possible race condition between VMM thread and API thread

- src/firecracker/src/api_server_adapter.rs
A race condition has been identified between the API thread and the VMM thread due to a misconfiguration of the `api_event_fd`.
What happens behind the scene:
The API thread receives API requests that need to be handled one by one. Handling a request by the API thread means the following actions:
1. Write the request on the channel to the VMM thread
2. Notify the VMM thread that it has a new request to handle
3. Call a blocking read on the channel from the VMM in order to get the results
On the VMM thread side, handling such a request represents the opposite actions:
1. Wait until getting notified that a new request needs its attention
2. Handle the request
3. Write the result on the channel to the API thread
4. Clear out the notification done by the API thread about the request …
> Possible race condition between VMM thread and API thread (FC 1.2)

- src/firecracker/src/api_server_adapter.rs
A race condition has been identified between the API thread and the VMM thread due to a misconfiguration of the `api_event_fd`.
What happens behind the scene:
The API thread receives API requests that need to be handled one by one. Handling a request by the API thread means the following actions:
1. Write the request on the channel to the VMM thread
2. Notify the VMM thread that it has a new request to handle
3. Call a blocking read on the channel from the VMM in order to get the results
On the VMM thread side, handling such a request represents the opposite actions:
1. Wait until getting notified that a new request needs its attention
2. Handle the request
3. Write the result on the channel to the API thread
4. Clear out the notification done by the API thread about the request …
> Possible race condition between VMM thread and API thread (FC 1.3)

- src/api_server/src/parsed_request.rs
- src/api_server/src/request/cpu_configuration.rs
- src/api_server/src/request/mod.rs
- src/api_server/swagger/firecracker.yaml
- src/logger/src/metrics.rs
- src/vmm/src/builder.rs
- src/vmm/src/guest_config/aarch64/mod.rs
- src/vmm/src/guest_config/templates/mod.rs
- src/vmm/src/guest_config/x86_64/mod.rs
- src/vmm/src/resources.rs
- src/vmm/src/rpc_interface.rs
- src/vmm/src/utilities/mock_resources/mod.rs
- src/vmm/src/vmm_config/machine_config.rs
- src/vmm/src/vstate/vcpu/aarch64.rs
- src/vmm/src/vstate/vcpu/mod.rs
- src/vmm/src/vstate/vcpu/x86_64.rs
- src/vmm/src/vstate/vm.rs
- tests/framework/microvm.py
- tests/integration_tests/build/test_coverage.py
Makes use of the `guest_config` module to provide an endpoint to configure vCPUs via an HTTP request using a JSON formatted payload. The means to change the configuration for the guest is a user-defined template that contains modifiers that will be applied to the default register values as they exist when KVM initializes them.
Currently, all configuration of guest vCPU resources is derived from defaults of the environment (centered around KVM and microcode defaults),  and pre-defined templates that users can choose from. This API will provide an endpoint to configure user-defined templates in the form of modifiers.
Developer Certificate of …
> Add PUT /cpu-config API

- Cargo.lock
- src/snapshot/Cargo.toml
- src/vmm/Cargo.toml
* exclude criterion's default features
Criterion offers opportunity to choose between
features and it does declare some dependencies
as being optional (like the rayon one) which we currently include even though we do not need to.
We actually do not need to include what criterion defines as default features.
---
> criterion: trim down dependencies

- Cargo.lock
- src/snapshot/Cargo.toml
- src/vmm/Cargo.toml
Criterion offers opportunity to choose between
features and it does declare some dependencies
as being optional (like the rayon one) which we currently include even though we do not need to.
We actually do not need to include what criterion defines as default features.
Fix vulnerability in crossbeam-channel.
---
> [1.3] criterion: trim down dependencies

- Cargo.lock
- Cargo.toml
- src/static_templates/Cargo.toml
- src/static_templates/src/c3.rs
- src/static_templates/src/lib.rs
- src/static_templates/src/t2.rs
- src/static_templates/src/t2a.rs
- src/static_templates/src/t2cl.rs
- src/static_templates/src/t2s.rs
- src/static_templates/tests/integration_tests.rs
- src/static_templates/tests/json/c3.json
- src/static_templates/tests/json/t2.json
- src/static_templates/tests/json/t2a.json
- src/static_templates/tests/json/t2cl.json
- src/static_templates/tests/json/t2s.json
- src/static_templates/tests/main_branch/amd/mod.rs
- src/static_templates/tests/main_branch/amd/t2a.rs
- src/static_templates/tests/main_branch/bit_helper.rs
- src/static_templates/tests/main_branch/cpu_leaf.rs
- src/static_templates/tests/main_branch/intel/c3.rs
- src/static_templates/tests/main_branch/intel/mod.rs
- src/static_templates/tests/main_branch/intel/t2.rs
- src/static_templates/tests/main_branch/intel/t2cl.rs
- src/static_templates/tests/main_branch/intel/t2s.rs
- src/static_templates/tests/main_branch/mod.rs
- tests/framework/dependencies.txt
- tests/integration_tests/build/test_coverage.py
Add static CPU templates defined in JSON format and new `CpuTemplate` type.
To test custom CPU template logic, we need some sample CPU templates in the JSON format. And, static CPU templates defined with the new `CpuTemplate` type is required to integrate static and custom CPU template handling into one logic.
The crate is added separately from vmm crate temporarily, because much changes are required to integrate static and custom CPU template on vmm crate as of now. The actual integration will be done in follow-up commits. To test that CPU templates defined in the JSON format and `CpuTemplate` type are consistent with the static CPU templates defined in main branch, some logics are put back here. But those should be removed when deleting this crate.
By submitting this pull request, I …
> feat: Static CPU templates in JSON format and `CpuTemplate` type

- CHANGELOG.md
- Cargo.lock
- src/jailer/Cargo.toml
- src/jailer/src/main.rs
- tests/framework/dependencies.txt
- tests/integration_tests/build/test_binary_size.py
Fixes the mechanism for closing open FDs in jailer which was
based on the SC_OPEN_MAX system constant. Such an approach can lead
to bad performance when this value is very high.
The method for closing file descriptors is now chosen based on the environment:
1. we try to call into the close_range syscall (available on kernels >=5.9)
2. we fallback to reading from /proc/self/fd (for kernels <5.9)
Fixes #3542 - a bug where firecracker would end up spending minutes starting which arises when running on systems with OPEN_MAX set to a very high number.
Thanks @gorbak25 for reporting the issue and proposing the fix!
Developer Certificate of Origin …
> jailer: fix perf regression when closing open FDs

- tests/framework/microvm.py
- tests/framework/resources.py
- tests/framework/utils.py
- tests/integration_tests/functional/test_api.py
- tests/integration_tests/functional/test_rng.py
Add integration tests for `virtio-rng` device.
Test end-to-end that virtio-rng is working. Also test rate limiting and functionality after resuming from a snapshot
---
> virtio-rng integration tests

- tests/integration_tests/security/test_spectre_meltdown.py
- tests/integration_tests/security/test_vulnerabilities.py
- Add tests to check for reported vulnerabilities in `/sys/devices/system/cpu/vulnerabilities/*` files
- Add tests to run the `spectre_meltdown_checker.sh` script on restored guests
- Add tests to check the vulnerabilities files on restored guests.
At the moment the `spectre_meltdown_checker.sh` script is only run on the launched guests. Guests restored from a snapshot are not exercised in a similar way.
Kernel's sysfs interfaces exposes vulnerabilities files that may report something other than Meltdown and Spectre.
- ~~[ ] If a specific issue …
> Add spectre_meltdown_checker and vulnerabilities tests for restored guests

- README.md
- docs/device-api.md
- docs/entropy.md
- docs/snapshotting/random-for-clones.md
Add documentation about `virtio-rng`
Let the users know how they can use `virtio-rng` and add implementation details.
---
> `virtio-rng` documentation

- tests/integration_tests/performance/configs/test_network_tcp_throughput_config_4.14.json
- tests/integration_tests/performance/configs/test_network_tcp_throughput_config_5.10.json
Re-gathered c7g.metal and m6g.metal network throughput performance test baselines to incorporate a performance improvement.
Failing CI due to out of date performance numbers.
---
> test: c7g & m6g network throughput baselines

- tests/integration_tests/performance/configs/test_vsock_throughput_config_4.14.json
- tests/integration_tests/performance/configs/test_vsock_throughput_config_5.10.json
Re-gathered m6a.metal vsock throughput performance test baselines to incorporate a performance improvement.
Failing CI due to out of date performance numbers.
---
> test: m6a vsock throughput baselines

- src/api_server/swagger/firecracker.yaml
Added `V1N1` aarch64 static cpu template to `firecracker.yaml`
---
> fix: added `V1N1` template to `firecracker.yaml`

- src/api_server/src/parsed_request.rs
- src/api_server/src/request/cpu_configuration.rs
- src/vmm/Cargo.toml
- src/vmm/benches/cpu_templates.rs
- src/vmm/benches/snapshots.rs
- src/vmm/src/guest_config/templates/aarch64.rs
- src/vmm/src/guest_config/templates/mod.rs
- src/vmm/src/guest_config/templates/test_utils/aarch64.rs
- src/vmm/src/guest_config/templates/test_utils/mod.rs
- src/vmm/src/guest_config/templates/test_utils/x86_64.rs
- src/vmm/src/guest_config/templates/x86_64.rs
- src/vmm/src/rpc_interface.rs
- tests/integration_tests/build/test_coverage.py
- tests/integration_tests/performance/test_cpu_template_benchmark.py
- tests/integration_tests/performance/test_versioned_serialization_benchmark.py
Add criterion benchmarks for the to/from string JSON operations for the `CustomCpuTemplate` type.
To keep a handle on the performance of serializing and deserializing CPU templates in JSON format.
> Add CPU template benchmarking for JSON ops

- .gitlint
- tests/framework/gitlint_rules.py
- tests/framework/microvm.py
- tests/host_tools/cpu_load.py
- tests/integration_tests/functional/test_rate_limiter.py
Also remove the CPU load monitoring from Microvm, since this is the only user and it fits better as a Context Manager.
...
The assert/error belongs during the test call phase, and not teardown.
---
> test: stop CPU load monitoring at the end of a test

- tests/conftest.py
- tests/framework/microvm.py
- tests/framework/resources.py
- tests/framework/utils_cpu_templates.py
- tests/integration_tests/security/test_vulnerabilities.py
Add custom CPU template tests to test_vulnerabilities.py. Dummy custom CPU templates are used for testing that are replicas of existing static templates.
Similar to static CPU templates, custom CPU templates need to be tested via `spectre_meltdown_checker.sh` and inspecting vulnerabilities files.
--- …
> Add custom CPU template tests to test_vulnerabilities.py

- src/vmm/src/vmm_config/machine_config.rs
- tests/integration_tests/build/test_coverage.py
- tests/integration_tests/functional/test_api.py
Removed check for cpu templates for aarch64.
This is done, because now we have static templates for aarch64 and we forgot to remove this restriction earlier.
---
> fix: removed check for cpu templates for aarch64

- src/api_server/src/lib.rs
Backport to FC 1.3 for commit d6f55d6ccdd9eb351400d4a7d523fa5ce46489a0
---
> Backport Fix spurious failure in api_server::tests::test_serve_vmm_action_request  to FC 1.3

- tests/framework/utils_cpuid.py
- tests/integration_tests/build/test_coverage.py
* Removes asserts from `get_cpu_codename` utility function that checks that the host environment is a known CPU model.
The asserts enforce that only known CPU models may run tests written in Pytest. This unfortunately prevents the Firecracker pytests from running on anything but specific CPU models currently defined by:
```
CPU_DICT = {
CpuVendor.INTEL: {
"Intel(R) Xeon(R) Platinum 8175M CPU": "INTEL_SKYLAKE",
"Intel(R) Xeon(R) Platinum 8259CL CPU": "INTEL_CASCADELAKE",
"Intel(R) Xeon(R) Platinum 8375C CPU": "INTEL_ICELAKE",
},
CpuVendor.AMD: {
"AMD EPYC 7R13": "AMD_MILAN",
},
CpuVendor.ARM: {"0xd0c": "ARM_NEOVERSE_N1", "0xd40": "ARM_NEOVERSE_V1"},
}
```
> Remove CPU model validation from python tests

- src/vmm/src/device_manager/persist.rs
- src/vmm/src/resources.rs
- tests/framework/vm_config.json
- tests/integration_tests/functional/test_api.py
- Add a new "cpu-config" field into the existing fireracker config file.
"cpu-config" PUT API was added in PR #3547 to set custom CPU template via API socket. Need to add the field to accept custom CPU template without API
- ~~[ ] New `TODO`s link to an …
> feat: Add "cpu-config" field to config file

- src/cpu-template-helper/src/dump/aarch64.rs
- src/cpu-template-helper/src/dump/mod.rs
- src/cpu-template-helper/src/dump/x86_64.rs
- src/cpu-template-helper/src/main.rs
- src/cpu-template-helper/src/strip/aarch64.rs
- src/cpu-template-helper/src/strip/mod.rs
- src/cpu-template-helper/src/strip/x86_64.rs
- src/cpu-template-helper/src/utils.rs
- src/vmm/src/guest_config/cpuid/mod.rs
- src/vmm/src/guest_config/templates/aarch64.rs
- src/vmm/src/guest_config/templates/x86_64.rs
- tests/integration_tests/build/test_coverage.py
- Add a strip feature of CPU template helper tool.
PR #3586 introduced the dump feature to dump CPU configuration in the custom CPU template JSON format. The dumped CPU configurations allow users to check what CPU configurations (CPUID and MSR for x86_64 and registers supported by `KVM_{GET/SET}_ONE_REG` for aarch64) are exposed to guests and use it as a draft custom CPU template.
As you can see in commit ee9d27fb981eb075caaf52113ad95157ad40e9a8, the dumped CPU configurations are ~1,000 lines of JSON files and it is quite difficult for humans to comprehend all the dumped information. Considering the main use case of CPU templates is to provide the feature parity between guests running on different CPU models, items that are shared between those CPU configurations and have same values can …
> feat(tool): Add strip feature

- src/vmm/Cargo.toml
- src/vmm/src/guest_config/cpuid/common.rs
- src/vmm/src/guest_config/cpuid/intel/mod.rs
- src/vmm/src/guest_config/cpuid/mod.rs
- src/vmm/src/guest_config/templates/mod.rs
- src/vmm/src/guest_config/templates/x86_64.rs
- src/vmm/src/guest_config/x86_64/static_cpu_templates/mod.rs
- tests/integration_tests/build/test_coverage.py
* Use derive_more::Display for a CPUID related error handling.
* Ignore AMD specific code when running checking test coverage on an Intel host.
* Ignore Intel specific code when running checking test coverage on an AMD host.
Improves accuracy of the Firecracker coverage report and improves the coverage target.
> Tweaks to improve overall test coverage

- CHANGELOG.md
Briefly mention what design choices and information about the API endpoint and the parameters users can pass.
Prepare for merging to `main`.
---
> Add CHANGELOG entry for `virtio-rng`

- tests/conftest.py
- tests/framework/artifacts.py
- tests/integration_tests/functional/test_cmd_line_parameters.py
- tests/integration_tests/functional/test_mmds.py
- tests/integration_tests/functional/test_snapshot_advanced.py
- tests/integration_tests/performance/test_snapshot_perf.py
- tools/release-prepare.sh
- split the tests so we can see which ones pass
- only test firecracker supported versions (drop 0.24, 0.25)
- make a new firecracker fixture so it is simple to use in tests
- give tests more descriptive names
...
...
---
> Fixing target version for snapshot tests

- docs/prod-host-setup.md
Add instructions to disable unprivileged BPF.
BPF is a useful tool in various transient execution attacks. While disabling is now a common default, it is worth ensuring unprivileged BPF is disabled.
---
> doc: Add guidance on disabling unprivileged BPF

- src/cpu-template-helper/src/dump/mod.rs
- src/cpu-template-helper/src/main.rs
- src/cpu-template-helper/src/strip/aarch64.rs
- src/cpu-template-helper/src/strip/mod.rs
- src/cpu-template-helper/src/strip/x86_64.rs
- src/cpu-template-helper/src/utils.rs
- src/cpu-template-helper/src/utils/aarch64.rs
- src/cpu-template-helper/src/utils/mod.rs
- src/cpu-template-helper/src/utils/x86_64.rs
- src/cpu-template-helper/src/verify/aarch64.rs
- src/cpu-template-helper/src/verify/mod.rs
- src/cpu-template-helper/src/verify/x86_64.rs
- tests/integration_tests/build/test_coverage.py
- tests/integration_tests/functional/test_cpu_template_helper.py
- Add a new command to verify CPU template to the helper tool.
- Refactor the helper tool.
As firecracker applies some modifications on the guest config after applying CPU template for some reasons (e.g. to boot linux kernel) and KVM ignores given values via SET APIs due to capabilities of KVM and host CPUs, a command to verify that the given custom CPU template is applied as intended is important for users in the loop of new custom CPU template creation and after KVM/firecracker/BIOS updates.
- ~~[ ] If a specific issue led to this PR, this PR …
> feat(tool): Add verify command

- src/cpu-template-helper/Cargo.toml
- src/cpu-template-helper/src/main.rs
- src/cpu-template-helper/src/utils/mod.rs
- tools/devtool
- tools/release-prepare.sh
- tools/release.sh
- Add cpu-template-helper to release artifacts
- Fix `tools/devtool install` and add cpu-template-helper to it.
The CPU template helper tool is delivered as a new separate binary from firecracker.
---
[1]: …
> chore: Add cpu-template-helper to release artifacts

- tests/integration_tests/functional/test_api.py
Rework of #3623 in python
added /cpu-config api tests
---
> added /cpu-config api tests

- src/devices/src/virtio/iovec.rs
This is needed for diff snapshots to work correctly.
Mark the memory that will be written to via IoVecBufferMut as dirty.
The memory needs to be marked as dirty for diff snapshots to work correctly.
---
> fix: Make sure memory written to by virtio-rng is marked as dirty

- CHANGELOG.md
- README.md
- docs/cpu_templates/boot-protocol.md
- docs/cpu_templates/cpu-templates.md
- docs/cpu_templates/cpuid-normalization.md
- docs/cpu_templates/schema.json
- docs/design.md
- docs/device-api.md
- docs/snapshotting/versioning.md
- tests/host_tools/mdl_style.rb
Add doc pages for static and custom CPU templates.
Static CPU templates are not sufficiently covered in the documentation. Custom CPU templates are not covered in the documentation.
The change contains a TODO without creating a Github issue. The TODO will be addressed by the Amazon team shortly.
---
[2]: …
> doc: add documentation for CPU templates

- .github/workflows/deny_dirty_cargo_locks.yml
- .github/workflows/dependency_modification_check.yml
It was causing them to trigger twice on every pull request, and also does not work since the checkout command in the action in specific to pull_request.
...
...
---
> remove "push" target from GitHub actions

- .gitlint
Reenable check for presence of message body.
The check was disabled temporarily to allow to merge the CPU templates feature branch.
---
[1]: …
> chore(gitlint): reenable check for presence of message body

- .github/workflows/deny_dirty_cargo_locks.yml
- .mailmap
- Cargo.lock
- build.rs
- src/api_server/swagger/firecracker.yaml
- src/cpu-template-helper/Cargo.toml
- src/firecracker/Cargo.toml
- src/jailer/Cargo.toml
- src/rebase-snap/Cargo.toml
- src/seccompiler/Cargo.toml
- src/vmm/src/version_map.rs
- tests/conftest.py
- tests/framework/utils.py
- tests/host_tools/uffd/Cargo.lock
- tests/integration_tests/build/test_binary_size.py
- tests/integration_tests/functional/test_api.py
- tests/integration_tests/functional/test_snapshot_version.py
- tests/integration_tests/security/demo_seccomp/Cargo.lock
- tests/integration_tests/style/test_repo.py
- tests/integration_tests/style/test_swagger.py
- tools/bump-version.sh
- tools/release-notes.sh
- tools/release-prepare.sh
- tools/release-tag.sh
- tools/release.sh
Change the release process so we use `Cargo.toml` as the authoritative version source, rather than git tags.
The current approach has a number of downsides, like requiring a git workspace to compile.
This should solve #3057 
---
> New release process and some 1.4.0 preparation

- tests/integration_tests/functional/test_cpu_template_helper.py
Skip the `integration_tests/functional/test_cpu_template_helper.py::test_cpu_config_change` test if the host kernel is not supported.
We only keep guest CPU config baselines for the kernels that we support.
---
[1]: …
> chore(tests): run test_cpu_config_change only for supported kernels

- Cargo.lock
- src/api_server/swagger/firecracker.yaml
- src/cpu-template-helper/Cargo.toml
- src/firecracker/Cargo.toml
- src/jailer/Cargo.toml
- src/rebase-snap/Cargo.toml
- src/seccompiler/Cargo.toml
- src/vmm/src/version_map.rs
- tests/host_tools/uffd/Cargo.lock
- tests/integration_tests/security/demo_seccomp/Cargo.lock
Bumping version to 1.5.0-dev
We already created the release branch for 1.4.0, so from now on we should be in 1.5.0-dev.
---
> Bump version to 1.5.0-dev

- README.md
- docs/snapshotting/snapshot-support.md
Warn about arm register width problem
---
> Warn about arm register width problem

- CHANGELOG.md
- Cargo.lock
- docs/entropy.md
- docs/snapshotting/random-for-clones.md
- resources/seccomp/aarch64-unknown-linux-musl.json
- resources/seccomp/x86_64-unknown-linux-musl.json
- src/devices/Cargo.toml
- src/devices/src/virtio/rng/device.rs
- src/vmm/Cargo.toml
- tests/host_tools/uffd/Cargo.toml
- tests/integration_tests/build/test_binary_size.py
- tools/devctr/Dockerfile
- tools/devtool
Switch to using `aws-lc-rs` for getting random bytes for `virtio-rng`.
Currently, we are using the `OsRng` type from the `rand` crate. `aws-lc-rs` is in the process of getting FIPS certification, so switching to this implementation might benefit us in the future for use-cases that require FIPS compliance.
---
> Backport `aws-lc-rs` switch to v1.4

- src/vmm/src/devices/virtio/rng/device.rs
In theory guests should not pass us 0 size buffers, but if they do right now we crash. Instead handle the case by adding back the buffer as used, having touched 0 bytes. Also add a unit-test for this case.
---
> handle 0 size buffers from guest

- README.md
* Use different logo when switch light/dark theme, see [specifying-the-theme-an-image-is-shown-to](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#specifying-the-theme-an-image-is-shown-to)
* Logos for dark/light theme already available in `docs/images` so why not use them
* Improve README style
---
[3]: …
> README.md: dark/light mode logo

- CHANGELOG.md
- src/cpuid/src/cpu_leaf.rs
- src/cpuid/src/transformer/amd.rs
- src/cpuid/src/transformer/common.rs
- src/cpuid/src/transformer/intel.rs
- tests/integration_tests/build/test_coverage.py
- tests/integration_tests/functional/test_cpu_features.py
Pass through the leaf 0x80000006 from the host to the guest.
Backport from https://github.com/firecracker-microvm/firecracker/pull/3721
---
> [1.3] Pass through cache information to the guest (leaf 0x80000006)

- CHANGELOG.md
- src/cpuid/src/cpu_leaf.rs
- src/cpuid/src/transformer/amd.rs
- src/cpuid/src/transformer/common.rs
- src/cpuid/src/transformer/intel.rs
- tests/framework/utils_cpuid.py
- tests/integration_tests/functional/test_cpu_features.py
Pass through the leaf 0x80000006 from the host to the guest.
Backport from https://github.com/firecracker-microvm/firecracker/pull/3721
---
> [1.2] Pass through cache information to the guest (leaf 0x80000006)

- CHANGELOG.md
- Cargo.lock
- src/api_server/swagger/firecracker.yaml
- src/firecracker/Cargo.toml
- src/jailer/Cargo.toml
- src/rebase-snap/Cargo.toml
- src/seccompiler/Cargo.toml
- tests/integration_tests/security/demo_seccomp/Cargo.lock
Create v1.3.3 release.
Release the following:
- Fixed passing through cache information from host in CPUID leaf 0x80000006.
---
> Release Firecracker v1.3.3

- CHANGELOG.md
Fix the upgraded Rust version to 1.68.2.
1.2.1 mentions upgrade to Rust 1.66.1, while the actual version is 1.68.2.
---
[3]: https://github.com/firecracker-microvm/firecracker/blob/main/ …
> [1.2] chore(changelog): fix version of the upgraded rust in 1.2.1

- tools/devtool
Example:
./tools/devtool sh "cd src/firecracker; cargo pkgid"
file:///firecracker/src/firecracker#1.5.0-dev
...
...
---
> ci: teach devtool to run shell commands inside devctr

- src/vmm/src/cpu_config/aarch64/custom_cpu_template.rs
- src/vmm/src/cpu_config/templates.rs
- src/vmm/src/cpu_config/x86_64/custom_cpu_template.rs
- tests/integration_tests/performance/test_cpu_template_benchmark.py
- Rewrote deserialization method for `RegisterValueFilter`.
- Improved performance by ~75%.
- Added ability to use `_` in string representation.
running: `cargo bench --bench cpu_templates`
```bash
deserialize_cpu_template
time:   [5.5389 µs 5.5402 µs 5.5419 µs]
change: [-77.543% -77.536% -77.530%] (p = 0.00 < 0.05)
Performance has improved.
Found 11 outliers among 200 measurements (5.50%)
2 (1.00%) low mild
4 (2.00%) high mild
5 (2.50%) high severe
```
---
[2]: …
> feat: upgrade of deserialization of RVF.

- tools/devtool
Example:
./tools/devtool sh "cd src/firecracker; cargo pkgid"
file:///firecracker/src/firecracker#1.5.0-dev
(cherry picked from commit 270819e697c058ae48a56a4d62df799e1bb7c178)
...
...
---
> [v1.2] ci: teach devtool to run shell commands inside devctr

- tools/devtool
Example:
./tools/devtool sh "cd src/firecracker; cargo pkgid"
file:///firecracker/src/firecracker#1.5.0-dev
(cherry picked from commit 270819e697c058ae48a56a4d62df799e1bb7c178)
...
...
---
> [v1.3] ci: teach devtool to run shell commands inside devctr

- tests/framework/utils.py
Backport PR #3523 to firecracker-v1.3
To suppress nightly CI failures.
---
> Backport PR #3523 to firecracker-v1.3

- CHANGELOG.md
- docs/cpu_templates/cpu-templates.md
- docs/cpu_templates/schema.json
- Updated doc with info about `_` in bitmaps.
---
> update of cpu_template doc

- src/vmm/src/vstate/vcpu/x86_64.rs
- Make all fields of VcpuState public
- To make them accessible by callers of `KvmVcpu::save_state()`.
---
[2]: https://github.com/firecracker-microvm/firecracker/blob/main/docs/api-c …
> refactor(vmm): Make fields of VcpuState public

- Cargo.lock
- src/utils/Cargo.toml
- src/utils/src/vm_memory.rs
- src/vmm/Cargo.toml
- src/vmm/src/builder.rs
- src/vmm/src/devices/virtio/block/device.rs
- src/vmm/src/devices/virtio/block/io/mod.rs
- src/vmm/src/devices/virtio/block/io/sync_io.rs
- src/vmm/src/devices/virtio/vsock/csm/connection.rs
- src/vmm/src/devices/virtio/vsock/csm/mod.rs
- src/vmm/src/devices/virtio/vsock/csm/txbuf.rs
- src/vmm/src/devices/virtio/vsock/packet.rs
- src/vmm/src/devices/virtio/vsock/test_utils.rs
- src/vmm/src/devices/virtio/vsock/unix/mod.rs
- src/vmm/src/devices/virtio/vsock/unix/muxer.rs
- src/vmm/src/memory_snapshot.rs
- tests/host_tools/uffd/Cargo.lock
- tests/integration_tests/build/test_coverage.py
- tests/integration_tests/security/demo_seccomp/Cargo.lock
Update vm-memory 0.10.0 -> 0.11.0
Update linux-loader 0.8.1 -> 0.9.0
The update to vm-memory 0.11.0 brought with it a performance degradation in the `read_from` and `write_to` methods used for transferring data between guest memory and some `Read`/ `Write` implementation. This is due to an added copy-to-vmm-memory of all transferred data to avoid unsoundness concerns with taking rust-style slices to guest memory. This PR alleviates that performance impact by implementing `ReadVolatile` and `WriteVolatile` traits that work exactly like `Read`/`Write`, but operate on `VolatileSlice` instead of `&mut [u8]`. This means there is no unsoundness when transferring directly between guest memory and a file descriptor. 
These traits are used in three places where `read_from`/`write_to` were …
> Update vm-memory to 0.11.0

- tests/framework/properties.py
- tests/integration_tests/functional/test_rng.py
The function get_kernel_version used to get the host operating system  kernel version was duplicated.
I removed the duplication.
this PR will close #3751
---
> refactor(test): Delete duplicate function definition

- tests/integration_tests/functional/test_balloon.py
Backports commit 4613131c53d4ee618419478d444ea4648d734af3.
Since the configured stats polling interval is 1 second, it may take up to 1 second for the `available_memory` stat to get updated.
In some cases, the VM is snapshotted, restored and the `available_memory` stat is queried before the 1 second has passed after an inflation had been requested.
To avoid this situation, a 1 second delay is added between sending an inflation request and reading stats.
- To suppress nightly CI test failures on v1.2
- ~~[ ] If a specific issue led to this PR, …
> Backport "fix(tests): test_balloon_snapshot: add delay after inflate" to v1.2

- tests/integration_tests/performance/configs/test_network_tcp_throughput_config_5.10.json
- Updates the performance baseline for network TCP throughput on kernel 5.10 + m6g.metal.
- This regression was caused by virtio-rng feature introduced in PR #3691.
```
{
"source": "9c7c47afc4fed69653b969549df6196db68436d3/tests/integration_tests/performance/configs/",
"test_network_tcp_throughput_config_5.10.json": {
"test": "network_tcp_throughput",
"kernel": "5.10",
"cpus": [
{
"stats": {
"mean": 0.38191623019355775,
"stdev": 0.8578222435586919
},
"mean": 0.11666666666666667,
"stdev": 0.8653727846986955
}
},
"cpu_utilization_vcpus_total": {
"mean": -0.05920123897172521, …
```
> chore(test): Update performance baseline

- src/vmm/src/arch/aarch64/regs.rs
- src/vmm/src/builder.rs
- src/vmm/src/vstate/vcpu/aarch64.rs
- tests/integration_tests/build/test_coverage.py
General improvements of vcpu code for aarch64
Before integrating updates from the `kvm-ioctls` crate which include update to how `get/set_one_reg` work, I thought to do some clean up to make integration easier.
---
> refactor: simplified aarch64 vcpu code 

- .buildkite/pipeline_pr.py
slightly increase timeout for pr pipelines
m6a.metal tests have been timing out due to too many different combinations of firecracker versions being tested in the snapshot tests.
---
> chore: adjust buildkite timeout

- tests/integration_tests/performance/test_process_startup_time.py
Adjust ARM startup threshold to prevent intermittent CI failures (note that the value is in microseconds) - put to 45 because the pytest teardown can take ages sometimes
With the merging of the CPU templates feature branch, we started seeing some intermittent failures of the test_process_startup_time.py tests.
---
> test: adjust ARM process startup time threshold

- src/vmm/src/vmm_config/boot_source.rs
- src/vmm/src/vmm_config/logger.rs
- src/vmm/src/vmm_config/metrics.rs
- src/vmm/src/vmm_config/mmds.rs
- tests/integration_tests/build/test_coverage.py
changed `src/vmm/src/vmm_config/` packages implementation to use thiserror::Error instead implements fmt::Display.
This PR will fix part of https://github.com/firecracker-microvm/firecracker/issues/3278
- [] All added/changed functionality is tested.
---
> fix: use thiserror::Error in vmm_config

- docs/cpu_templates/cpu-templates.md
- docs/cpu_templates/schema.json
The link to KVM API is provided to help users
find information on how to build register addresses in a custom CPU template for ARM.
It may be difficult for users to know how to choose ARM register addresses.
--- …
> doc: cpu templates: add info about arm register ids

- src/rate_limiter/src/lib.rs
Backporting https://github.com/firecracker-microvm/firecracker/pull/3706 from the main.
Fixes are missing in 1.4.
---
[2]: …
> 1.4: Correctly handle some extreme edge cases in the ratelimiter implementation #3706

- tools/gh_release.py
The version parameter is vulnerable to command injection. I.e.
gh_release.py --version '**v1.2.4;id #**'
Validate the version parameter so it's not accepted.
error: argument --version: invalid version value: '**v1.2.4;id #**'
...
...
---
> ci(gh_release.py): validate version parameter

- tests/framework/stats/baseline.py
734696ffd93d2cce2201aacf45e67551f1f548e2 slightly changed the structure of the dictionary containing the baselines against which performance test results are compared, causing failures of the tests. I verified this commit by comparing the return value to the what was returned before the above commit.
---
> test: fix baseline provider dict structure

- tools/gh_release.py
Backport of [#3784](https://github.com/firecracker-microvm/firecracker/pull/3784).
```
The version parameter is vulnerable to command injection. I.e.
gh_release.py --version '**v1.2.4;id #**'
Validate the version parameter so it's not accepted.
error: argument --version: invalid version value: '**v1.2.4;id #**'
```
[`CONTRIBUTING.md`][1].
[1]: https://github.com/firecracker-microvm/firecracker/blob/main/CONTRIBUTING.md
> backport: ci(gh_release.py): validate version parameter

- docs/cpu_templates/cpuid-normalization.md
- src/vmm/src/cpu_config/x86_64/cpuid/normalize.rs
- Add vendor ID normalization
The custom CPU template feature allows users to modify vendor ID. This
results in a situation where the vendor ID mismatch the brand string,
because the normalization is enforced on the brand string based on the
host value.
**Note that this PR should be backported to v1.4 release branch in PR #3791.**
- ~~[ ] …
> fix(vmm): Add vendor ID normalization

- docs/cpu_templates/cpuid-normalization.md
- src/vmm/src/cpu_config/x86_64/cpuid/normalize.rs
Backport PR #3789 to v1.4.
...
---
> Backport "fix(vmm): Add vendor ID normalization" to v1.4

- .github/dependabot.yml
They create a lot of noise due to the webhook. Since we now have a recurring task to only batch/merge them once a week, we do not need the notification from the webhook anymore, so remove the label.
---
> Remove labels from dependabot PR

- tests/integration_tests/performance/test_cpu_template_benchmark.py
Remove the lower threshold for the /cpu-config deserialization benchmarking.
The benchmark is useful in checking that  no regressions have been introduced into deserialization code for /cpu-config.
The benchmark can cause CI pipelines to fail because the benchmark exceeds expectations, the benchmark running faster than expected is not a problem
[`CONTRIBUTING.md`][1].
---
[1]: https://github.com/firecracker-microvm/firecracker/blob/main/CONTRIBUTING.md
> fix: Remove cpu-config benchmark lower threshold

- .cargo/audit.toml
Removes the ignorance of RUSTSEC-2021-0145 from cargo audit test.
Now we're consuming criterion 0.5.1 that no longer depends on atty.
Closes #3284
---
[3]: …
> chore(test): Remove ignorance of RUSTSEC-2021-0145

- src/vmm/src/cpu_config/aarch64/custom_cpu_template.rs
- src/vmm/src/cpu_config/templates_serde.rs
- src/vmm/src/cpu_config/x86_64/custom_cpu_template.rs
- src/vmm/src/cpu_config/x86_64/test_utils.rs
Removed JSON deserialization support for decimal numbers in CPU templates.
Unnecessary feature that isn't useful or has a known benefit.
[`CONTRIBUTING.md`][1].
[1]: https://github.com/firecracker-microvm/firecracker/blob/main/CONTRIBUTING.md
> fix: Remove decimal support for CPU templates

- resources/tests/build_kernel.sh
Fix the path in the info message.
Was:
`Kernel binary placed in build/kernel/vmlinux-4.14-x86_64.bin`
Now:
`Kernel binary placed in build/kernel/linux-4.14/vmlinux-4.14-x86_64.bin`
The info message says:
```Kernel binary placed in build/kernel/vmlinux-4.14-x86_64.bin```
However the binary is actually located at:
```build/kernel/linux-4.14/vmlinux-4.14-x86_64.bin```
~~- [ ] API changes …
> chore(devtool): build_kernel: fix info message

- src/vmm/src/cpu_config/aarch64/custom_cpu_template.rs
- src/vmm/src/cpu_config/templates_serde.rs
- src/vmm/src/cpu_config/x86_64/custom_cpu_template.rs
- src/vmm/src/cpu_config/x86_64/test_utils.rs
- tests/integration_tests/performance/test_cpu_template_benchmark.py
Backport of [PR 3695](https://github.com/firecracker-microvm/firecracker/pull/3695/) (removing decimal number support for CPU templates and [PR 3798](https://github.com/firecracker-microvm/firecracker/pull/3798) (cpu-config benchmark tweak to improve pass reliability).
[`CONTRIBUTING.md`][1].
[1]: https://github.com/firecracker-microvm/firecracker/blob/main/CONTRIBUTING.md
> Backport for CPU templates - Decimal number support and benchmark update (#3695, #3798)

- resources/tests/cpu_template_helper/fingerprint_AMD_MILAN_4.14host.json
- resources/tests/cpu_template_helper/fingerprint_AMD_MILAN_5.10host.json
- resources/tests/cpu_template_helper/fingerprint_AMD_MILAN_6.1host.json
- resources/tests/cpu_template_helper/fingerprint_ARM_NEOVERSE_N1_4.14host.json
- resources/tests/cpu_template_helper/fingerprint_ARM_NEOVERSE_N1_5.10host.json
- resources/tests/cpu_template_helper/fingerprint_ARM_NEOVERSE_N1_6.1host.json
- resources/tests/cpu_template_helper/fingerprint_ARM_NEOVERSE_V1_4.14host.json
- resources/tests/cpu_template_helper/fingerprint_ARM_NEOVERSE_V1_5.10host.json
- resources/tests/cpu_template_helper/fingerprint_ARM_NEOVERSE_V1_6.1host.json
- resources/tests/cpu_template_helper/fingerprint_INTEL_CASCADELAKE_4.14host.json
- resources/tests/cpu_template_helper/fingerprint_INTEL_CASCADELAKE_5.10host.json
- resources/tests/cpu_template_helper/fingerprint_INTEL_CASCADELAKE_6.1host.json
- resources/tests/cpu_template_helper/fingerprint_INTEL_ICELAKE_4.14host.json
- resources/tests/cpu_template_helper/fingerprint_INTEL_ICELAKE_5.10host.json
- resources/tests/cpu_template_helper/fingerprint_INTEL_ICELAKE_6.1host.json
- resources/tests/cpu_template_helper/fingerprint_INTEL_SKYLAKE_4.14host.json
- resources/tests/cpu_template_helper/fingerprint_INTEL_SKYLAKE_5.10host.json
- resources/tests/cpu_template_helper/fingerprint_INTEL_SKYLAKE_6.1host.json
- tests/integration_tests/functional/test_cpu_template_helper.py
- tools/devtool
**Note that the root cause analysis for guest CPU config change on Cascade Lake is being done in parallel. This PR goes first to unblock CI failures on the other PRs.**
Regathers the fingerprint baseline files.
Some kernel versions, microcode versions and guest CPU configs are updated.
- ~~[ ] User-facing changes are …
> chore(test): Update fingerprint baselines

- src/cpu-template-helper/src/fingerprint/dump.rs
Removes a message used for debug in the fingerprint dump command of the CPU template helper tool.
```
$ sudo cpu-template-helper fingerprint dump --config config.json
Some(0)
```
**Note: This command will be backported into 1.4 release branch.**
...
- ~~[ …
> chore(tool): Remove message for debug

- Cargo.lock
- src/cpu-template-helper/src/template/dump/aarch64.rs
- src/vmm/Cargo.toml
- src/vmm/src/arch/aarch64/mod.rs
- src/vmm/src/arch/aarch64/regs.rs
- src/vmm/src/arch/aarch64/vcpu.rs
- src/vmm/src/arch/mod.rs
- src/vmm/src/builder.rs
- src/vmm/src/cpu_config/aarch64/mod.rs
- src/vmm/src/persist.rs
- src/vmm/src/version_map.rs
- src/vmm/src/vstate/vcpu/aarch64.rs
- src/vmm/tests/integration_tests.rs
- tests/integration_tests/build/test_coverage.py
- Updated `kvm-bindings` to 1.4 which changes `get/set_one_reg` methods.
- Updated internal representation of aarch64 registers:
Now we are able to work with register wider then 128 bits. All registers are stored in the `Aarch64RegisterVec` in one byte array. This way registers of different sizes can be efficiently stored and iterated on.
Supported sizes are: 8, 16, 32, 64, 128, 256, 512, 1024, 2048 bits (all sizes supported by KVM).
Register size is determined by the ID of the register.
Interactions with registers are happening using `Aarch64RegisterRef` or `Aarch64RegisterRefMut`.
Developer Certificate of Origin and signing off your …
> feat(aarch64): ability to work with wide registers

- tests/integration_tests/performance/configs/test_vsock_throughput_config_4.14.json
Updated vsock throughput beselines for m6g and m6a
```bash
{
"source": "6da185481fc5cf00dfa796f828c3958709c9a8ee/tests/integration_tests/performance/configs/",
"target": "1fd4b15562fa86af90e1229636dc5af128d4bab1/tests/integration_tests/performance/configs/",
"test_vsock_throughput_config_4.14.json": {
"test": "vsock_throughput",
"kernel": "4.14",
"cpus": [
{
"stats": {
"cpu_utilization_vcpus_total": {
"mean": 0.0,
"stdev": 0.0
},
"mean": 0.0,
"stdev": 0.0
}
},
"throughput": {
"mean": -1.5073027234002798,
"stdev": 3.3625373822826403
},
"mean": -0.3,
"stdev": 0.8645047258706174
}
}, …
```
> chore(baselines): updated vsock throughput beselines for m6g and m6a

- .github/dependabot.yml
This caused dependabot to ignore the current config, and continue sending us alerts based on its old configuration.
...
...
---
> fix: typo in dependabot config

- tests/framework/microvm.py
- tests/integration_tests/functional/test_snapshot_basic.py
- tests/integration_tests/performance/test_block_performance.py
- tests/integration_tests/performance/test_network_latency.py
- tests/integration_tests/performance/test_network_tcp_throughput.py
- tests/integration_tests/performance/test_snapshot_restore_performance.py
- tests/integration_tests/performance/test_vsock_throughput.py
In 9d7080a39f31cd9ecff8d658edb4bd3930a54470 we changed the default log level to Debug, which unintentionally affected performance tests with lots of log output (like vsock).
---
> perf: Set log level to Debug

- Cargo.lock
- src/cpu-template-helper/Cargo.toml
- src/firecracker/Cargo.toml
- src/seccompiler/Cargo.toml
- tests/integration_tests/security/demo_seccomp/Cargo.lock
- Cherry-picks dependabot PRs created util 2023-06-22.
...
---
[3]: …
> accumulated dependabot PRs until 2023-06-22

- .github/dependabot.yml
- .github/workflows/deny_dirty_cargo_locks.yml
- Fixes non-dirty files being reported as dirty.
- Adds directories to dependabot.yaml.
Derived from discussions on PR #3850.
Please see commit messages.
**Note that adding directories to dependabot.yaml could be noisy if it created a PR per directory. But let's go forward for now and see how it goes!**
- ~~[ ] …
> test: Improve Cargo.lock dirty check

- src/vmm/src/devices/virtio/balloon/device.rs
- src/vmm/src/devices/virtio/block/device.rs
- src/vmm/src/devices/virtio/net/device.rs
In `Block::write_config()`, when computing the end of the destination slice for a configuration write, an addition might overflow (`offset + data_len`). This will immediately cause a panic in debug builds, and panic on slice indexing a few lines below for release builds.
https://github.com/firecracker-microvm/firecracker/blob/06256c309069e2db535bd0cdf55422e48eeb61c9/src/vmm/src/devices/virtio/block/device.rs#L583-L589
Fix this by using `usize::checked_add()` and `slice::get_mut()`.
There are similar issues in other devices.
The hypervisor should not panic when given an invalid device configuration offset.
Developer Certificate of Origin and …
> virtio: fix integer overflows

- src/vmm/src/devices/virtio/balloon/device.rs
- src/vmm/src/devices/virtio/block/device.rs
- src/vmm/src/devices/virtio/net/device.rs
The test makes sure that a large offset value does not cause an overflow inside VirtioDevice::write_config().
Regression test for https://github.com/firecracker-microvm/firecracker/pull/3869 .
---
[1]: …
> test(vmm): add regression test for virtio device write_config()

- CHANGELOG.md
- src/cpu-template-helper/src/template/strip/aarch64.rs
- src/cpu-template-helper/src/template/strip/mod.rs
- src/cpu-template-helper/src/template/strip/x86_64.rs
- src/cpu-template-helper/src/template/verify/mod.rs
- src/cpu-template-helper/src/template/verify/x86_64.rs
- src/cpu-template-helper/src/utils/aarch64.rs
- src/cpu-template-helper/src/utils/mod.rs
- src/cpu-template-helper/src/utils/x86_64.rs
- src/vmm/src/cpu_config/templates.rs
- tests/integration_tests/build/test_coverage.py
- Change the strip feature of the CPU template helper tool to operate bitwise.
In a case where only 1 bit of a CPUID register value is different across inputs, all the other 31 bits are also preserved in the stripped outputs.
Ignoring all the other bits by eyes is quite troublesome from user perspective.
example of value-wise output
```
{
"leaf": "0x0",
"subleaf": "0x0",
"flags": 0,
"modifiers": [
{
"register": "eax",
"bitmap": "0b00000000000000000000000000001001"
}
]
},
```
example of bit-wise output
```
{
"leaf": "0x0",
"subleaf": "0x0",
"flags": 0,
"modifiers": [
{
"register": "eax",
"bitmap": "0bxxxxxxxxxxxxxxxxxxxxxxxxxxx01x01"
}
]
},
```
the terms of the Apache 2.0 license. For more information on …
> Change the strip feature of the CPU template helper tool to operate bitwise

- .buildkite/pipeline_perf.py
- tools/devtool
Fix bug introduced in 30b7b20a14995e159f56d4ac4af2526b9fb7c0bf
Also an unrelated commit about retrying if the agent goes away.
---
> Fix create snapshots

- tests/framework/utils_iperf.py
Prior to 1e0fa78dc3bfba31e787425c8f907e7176956f22, the final two CPU load data points were ignored in the tcp and vsock throughput tests as they were seemingly impacted by test tear down. I accidentally removed that logic in my refractor, which caused the perf tests to fail. This commit reintroduces that logic.
---
> test(tcp/vsock throughput): Ignore final two cpu load datapoints

- tools/devtool
Turbo boost allows the CPU of the .metal instance running our test suite to temporarily operate at a higher frequency. Since some of our tests are performance tests, this add non-deterministic variability into the processor frequency. Therefore, disable it.
Also explicitly set the scaling governor to "performance" to prevent the kernel from adjusting CPU frequency for us.
---
[3]: …
> test: Disable Turbo Boost

- Cargo.lock
- tests/framework/stats/core.py
Changes the dimensions of the raw metrics output by the performance tests to match their aggregates. Prior to this change, all parameterizations of a single tests were only tagged with the test function name. This change instead includes the "tag" as well as full parameterized pytest test name, just like the aggregates.
---
> test: Name performance test data consistently

- .buildkite/pipeline_pr.py
- docs/formal-verification.md
- src/dumbo/src/pdu/ethernet.rs
- src/rate_limiter/src/lib.rs
- tests/conftest.py
- tests/integration_tests/performance/conftest.py
- tests/integration_tests/test_kani.py
- tools/devctr/Dockerfile
- tools/devtool
Introduces formal verification harnesses verifying the safety and correctness of the ethernet module of dumbo, and the rate limiter implementation. Additionally, add CI integration to run the verification on every PR.
Formal verification will significantly raise our safety and correctness bar. Please see the documentation included in this PR for details. 
---
[3]: …
> [Kani] Introduce formal verification harnesses for ratelimiter and dumbo

- Cargo.lock
Cherry-pick from https://github.com/firecracker-microvm/firecracker/pull/3927 .
To fix cargo audit warning due to 0.3.1 being yanked.
---
[1]: …
> chore: update hermit-abi

- tests/integration_tests/performance/configs/test_network_latency_config_4.14.json
- tests/integration_tests/performance/configs/test_network_latency_config_5.10.json
- tests/integration_tests/performance/configs/test_network_latency_config_6.1.json
A recent change in our CI infrastructure disabled deep C-states, which improves performance on x86 for tests that are no very cpu-bound (since cores no longer need to "wake" from idle states).
---
> chore: collect network latency baselines

- tests/integration_tests/performance/configs/test_block_performance_config_4.14.json
- tests/integration_tests/performance/configs/test_block_performance_config_5.10.json
- tests/integration_tests/performance/configs/test_block_performance_config_6.1.json
- tests/integration_tests/performance/test_block_performance.py
This PR accumulates some fixes to the block performance test that all each require new baselines. These include:
- Pinning the fio workers to vcpus inside of the guest to prevent guest-scheduling to impact test results
- Change parameterization from baseline level to pytest level to improve readability of test progress and do not reuse microvms across multiple tests
- Introduce a write test, as the randrw fio mode tries to balance reads and writes, leading to its results being highly correlated with the read tests. 
---
[1]: …
> test(perf): Accumulated Block Test fixes + baselines

- tests/integration_tests/performance/configs/test_vsock_throughput_config_4.14.json
Updates the performance baselines of vsock throughput tests for m6a.metal + kernel 4.14
Performance changes were introduced on 5 Jul 2023 due to AMI update (not due to firecracker changes).
I've confirmed that the test passes on the old AMI not on the new AMI.
- ~~[ ] User-facing changes are mentioned in …
> chore: Update vsock throughput baseline for m6a.metal + kernel 4.14

- tools/devctr/Dockerfile
- tools/devtool
When building the docker image, newlines were removed meaning the commands after the comment about why we do not install kani for aarch64 became part of the comment itself. This resulted in a broken docker image.
Fixes #3960
...
...
---
> fix: Comment in dockerfile breaking cargo build

- tests/framework/microvm.py
- tests/integration_tests/security/test_jail.py
- Adds reties to `pid_in_new_ns`.
When `pid_in_new_ns` is referenced before the pid file is created by jailer with `--new-pid-ns` flag, it returns `None` and some jailer integration tests fail.
```
___________________ test_new_pid_ns_resource_limits[ubuntu] ____________________
--
  | integration_tests/security/test_jail.py:629: in test_new_pid_ns_resource_limits
  | check_limits(fc_pid, NOFILE, FSIZE)
  | fc_pid     = None
  | test_microvm = <framework.microvm.Microvm object at 0x7fd92e890d30>
  | test_microvm_with_api = <framework.microvm.Microvm object at 0x7fd92e890d30>
  | integration_tests/security/test_jail.py:348: in check_limits
  | (soft, hard) = resource.prlimit(pid, resource.RLIMIT_NOFILE)
  | E   TypeError: 'NoneType' object cannot be interpreted as an integer
  | fsize …
```
> test: Add retries to get firecracker PID in new ns

- tests/integration_tests/functional/test_rate_limiter.py
- Fail early when iperf3 client exits with non-0 code.
- Fixes wrong or vague comments and clarify function names (mode (server/client) and env (guest/host))
Spurious failure occurred in `_check_tx_rate_limiting`.
```
integration_tests/functional/test_rate_limiter.py:218: in _check_tx_rate_limiting
--
  | _, burst_kbps = _process_iperf_output(iperf_out)
  | expected_kbps = 102400
  | guest_ips  = ['192.168.0.2', '192.168.0.6', '192.168.0.10']
  | host_ips   = ['192.168.0.1', '192.168.0.5', '192.168.0.9']
  | iperf_cmd  = 'iperf3 -c 192.168.0.9 -n 104857600 -f KBytes -w 256K -N'
  | iperf_out  = 'iperf3: error - unable to connect to server: Connection refused\n'
  | rate_no_limit_kbps = 3295251.5
  | test_microvm = <framework.microvm.Microvm object at 0x7fbd4f8671f0>
  | …
```
> test: refactor test_rate_limiter.py

- tests/framework/microvm.py
To suppress spurious failures, increases the duration between retries.
check_log_message() and check_any_log_message() are used to check if a given message is included in firecracker's log. At the moment, host kernel 6.1 has larger boot time than other kernel versions, resulting in delay of printing the message. 
- …
> test: Increases duration of delay for log message checker

- CHANGELOG.md
- resources/tests/static_cpu_templates/t2a.json
- src/vmm/src/cpu_config/x86_64/static_cpu_templates/t2a.rs
- Changes T2A template to set CPUID.0x80000008:EBX[20] to 1 which indicates that EFER[LMSLE] is not supported.
As described in AMD64 APM Vol.2, EFER[LMSLE] has already been deprecated and is not supported by all processor implementations (including m6a.metal).
KVM allows nested virtualized guests to write to EFER[LMSLE] only for very specific software (SLES11 version of Xen 4.0 to boot nested SVM).
https://lore.kernel.org/all/1273068285-3105-5-git-send-email-joerg.roedel@amd.com/
On non-nested virtualized guests, writing to EFER[LMSLE] generates #GP which is identical to behavior on CPUs where EferLmsleUnsupported is set to 1.  As T2A template disables SVM, it is safer and better to let guests know that writing to EFER[LMSLE] is not supported.
As a side note, to revert the above commit on …
> fix(vmm): Changes T2A to set EferLmsleUnsupported to 1

- src/api_server/src/lib.rs
- src/firecracker/src/api_server_adapter.rs
- src/vmm/src/rpc_interface.rs
- tests/integration_tests/build/test_coverage.py
Simplifies `build_microvm_from_requests` by  removing generic `Fn` arguments which where not needed.
Generic function arguments are unweidly and add uneeded complexity.
---
> refactor: Simplify `build_microvm_from_requests`

- tools/release.sh
Previously version of FC obtained from binary in `release.sh` contained `v` (so it was `v.1.4.0`). But in `Cargo.toml` of FC version was `1.4.0`. Because of this difference release process was failing. This change fixes this issue.
---
> fix: minor fix of `release.sh`

- CHANGELOG.md
- resources/tests/static_cpu_templates/t2a.json
- src/vmm/src/cpu_config/x86_64/static_cpu_templates/t2a.rs
- tests/integration_tests/functional/test_feat_parity.py
- Changes T2A not to unset MMX and FXSR bits
The MMX bit (CPUID.80000001h:EDX[23]) and the FXSR bit (CPUID.80000001h:EDX[24]) are unset on Intel CPUs as they are reserved in Intel specification. However, as described in AMD APM, these bits are same as CPUID.01h:EDX[23] and CPUID.01h:EDX[24] respectively. These bits are set to 1 on T2 instance,  Intel Cascade Lake, Intel Ice Lake and AMD Milan. Thus, T2A template does not need to unset CPUID.80000001h:EDX[23,24].
- ~~[ ] Any …
> fix(vmm): Changes T2A not to unset MMX and FXSR bits

- .buildkite/pipeline_pr.py
Thisshould solve issue #3966 It would prevent us from breaking devtool build cmd when updating the devctr
Adding check which tries to execute `tools/devtool -y test`
We want to avoid introducing breakings change like #3960 
Close #3966.
---
> test: Run devtool build in CI

- CHANGELOG.md
- resources/tests/static_cpu_templates/t2a.json
- src/vmm/src/cpu_config/x86_64/static_cpu_templates/t2a.rs
- tests/integration_tests/functional/test_feat_parity.py
- Changes the T2A template to set the RstrFpErrPtrs bit ( CPUID.0x80000008:EBX[bit 2] ).
According to AMD APM, the RstrFpErrPtrs bit ( CPUID.0x80000008:EBX[bit 2] ) indicates that FXSAVE, XSAVE, FXSAVEOPT, XSAVEC, XSAVES always save error pointers and FXRSTOR, XRSTOR, XRSTORS always restore error pointers.
Historically, the error pointers have been saved on Intel CPUs but were not on old AMD CPUs (called "FXSAVE leak"). To handle this difference, the linux kernel enables a workaround. See the following commit for more details.
https://github.com/torvalds/linux/commit/18bd057b1408
Given this sitaution, AMD decided to make their CPUs behave same as Intel CPUs and also added the CPUID bit to let softwares know this behavior.
https://github.com/torvalds/linux/commit/f2dbad36c55e
In terms of …
> fix(vmm): Changes T2A to set RstrFpErrPtrs bit

- tests/integration_tests/performance/configs/test_network_latency_config_6.1.json
Updated baselines for network latency for aarch64
Diff: 
```json
{
"source": "50b9fce7a2f9ea016423288524c11f94afab2b34/tests/integration_tests/performance/configs/",
"target": "bbe7fc957ef0ab4b5530432beaff57565be4115e/tests/integration_tests/performance/configs/",
"test_network_latency_config_6.1.json": {
"test": "network_latency",
"kernel": "6.1",
"cpus": [
{
"instance": "c7g.metal",
"model": "ARM_NEOVERSE_V1",
"stats": {
"latency": {
"mean": 6.166666666666609,
"stdev": 3.0641293851416824
},
"mean": 6.000000000000001,
"stdev": 4.2426406871192865
}
}
}
},
{
"stats": {
"latency": {
"mean": 6.9047619047618465,
"stdev": 0.33671751485072005
}, …
```
> chore: updated baselines for network latency for aarch64

- README.md
Updated the expired Firecracker slack workspace link in the README with a new valid one.
This change fix the issue #3976. It updates the README file with a new valid Firecracker slack workspace link.
Allows our community members to easily join our Slack workspace clicking the link. Currently any user who try to access the workspace via the link will face an error. 
---
[1]: …
> chore: Update Slack invitation link

- tests/integration_tests/build/test_unittests.py
Running unittests in debug mode gives us greater correctness guarantees, since `debug_assert!`s will be triggered. These are often used to perform "sanity checks" that are supposed to get compiled out in release mode for performance reasons. Additionally, our coverage test runs in debug bug, so this will make the behavior between the two tests consistent (whereas otherwise a failure of one but not the other due to a debug assertion will be confusing).
---
[2]: …
> test: Run unittests in debug mode

- Cargo.toml
- src/firecracker/Cargo.toml
With one of the recent rust toolchain upgrades, we started getting a warning about different defaults for the results (workspaces default to resolver = "1", yet individual crates default to resolver = "2" since edition 2021). To fix this warning, explicitly set the resolver to version 2 in our top level Cargo.toml
---
> fix: specify resolver in Cargo.toml

- tests/integration_tests/performance/configs/test_vsock_throughput_config_6.1.json
Update performance baseline for vsock throughput tests to reflect the change introduced by an AMI update on 27 Jul 2023 on m6g.metal + 6.1 kernel.
Diff:
```json
{
"source": "a99527728df177b90e1a951afa1244e453600ef2/tests/integration_tests/performance/configs/",
"test_vsock_throughput_config_6.1.json": {
"test": "vsock_throughput",
"kernel": "6.1",
"cpus": [
{
"stats": {
"mean": 0.6245428543966136,
"stdev": 0.9056726720121695
},
"mean": 0.1,
"stdev": 0.7880689256524125
}
},
"throughput": {
"mean": -2.7702661453821653,
"stdev": 1.8057381374168133
}, …
```
> chore: update baseline for vsock throughput for m6g.metal+6.1 kv

- tests/integration_tests/performance/configs/test_vsock_throughput_config_6.1.json
Update performance baseline for vsock throughput tests to fix intermittent performance issue introduced because of an AMI update on 27 Jul 2023 on c7g.metal and m6a.metal + 6.1 kernel.
diff 
```json
"test_vsock_throughput_config_6.1.json": {
"test": "vsock_throughput",
"kernel": "6.1",
"cpus": [
{
"instance": "m6a.metal",
"model": "AMD EPYC 7R13 48-Core Processor",
"stats": {
"mean": -0.26509885846733805,
"stdev": 1.3639893084026427
},
"mean": -0.05,
"stdev": 1.5035046776746235
}
},
"throughput": {
"mean": -3.9195584017998852,
"stdev": 2.175046913062185
},
"mean": -0.4,
"stdev": 0.9403246919632544
}
},
"cpu_utilization_vcpus_total": { …
```
> chore: update vsock perf baseline for m6a and c7g for 6.1

- tests/integration_tests/functional/test_cpu_template_helper.py
This test compares the baseline guest_cpu_config gathered in the past with the current one and fails potentially due to firecracker's code changes or kernel/microcode updates. To be aware correctly that CPU config has been changed by firecracker, the test was set as a mandatory requirement to merge PRs.
However, since the introduction of the test (commit 8161c0bca20d ("test(tool): verify CPU config has not changed") on 2023 Apr 5, the following CPU config changes have been caused by non-firecracker changes:
- The RRSBA bit of IA32_ARCH_CAPABILITIES MSR flipped from 0 to 1 on Intel Cascade Lake.
- The GDS_CTRL bit of IA32_ARCH_CAPABILITIES MSR flipped from 0 to 1 on combinations of (Intel Skylake, Intel Cascade Lake, Intel Ice Lake) x (host kernel 4.14).
Although this kind of CPU config …
> test: Make test_guest_cpu_config_change optional 

- .cargo/config
- Cargo.lock
- resources/seccomp/aarch64-unknown-linux-musl.json
- resources/seccomp/x86_64-unknown-linux-musl.json
- src/api_server/src/lib.rs
- src/cpu-template-helper/src/fingerprint/compare.rs
- src/cpu-template-helper/src/fingerprint/dump.rs
- src/cpu-template-helper/src/main.rs
- src/cpu-template-helper/src/template/dump/mod.rs
- src/cpu-template-helper/src/template/strip/aarch64.rs
- src/cpu-template-helper/src/template/strip/mod.rs
- src/cpu-template-helper/src/template/strip/x86_64.rs
- src/cpu-template-helper/src/template/verify/aarch64.rs
- src/cpu-template-helper/src/template/verify/mod.rs
- src/cpu-template-helper/src/template/verify/x86_64.rs
- src/cpu-template-helper/src/utils/mod.rs
- src/firecracker/src/api_server_adapter.rs
- src/firecracker/src/main.rs
- src/jailer/src/cgroup.rs
- src/jailer/src/chroot.rs
- src/jailer/src/env.rs
- src/jailer/src/main.rs
- src/jailer/src/resource_limits.rs
- src/rebase-snap/Cargo.toml
- src/rebase-snap/src/main.rs
- src/seccompiler/src/backend.rs
- src/seccompiler/src/compiler.rs
- src/seccompiler/src/seccompiler_bin.rs
- tests/integration_tests/build/test_coverage.py
- tests/integration_tests/functional/test_cmd_line_start.py
This PR is build on top of another PR: #3575
Adds new lint: `clippy::exit` and makes necessary changes for it.
Updates `Error` and `Result` types for several crates.
Enables the use of `clippy::exit`. Fixes #3233
---
> Adding `clippy::exit` lint

- CHANGELOG.md
- Cargo.lock
- resources/tests/static_cpu_templates/t2a.json
- src/api_server/swagger/firecracker.yaml
- src/cpu-template-helper/Cargo.toml
- src/firecracker/Cargo.toml
- src/jailer/Cargo.toml
- src/rebase-snap/Cargo.toml
- src/seccompiler/Cargo.toml
- src/vmm/src/cpu_config/x86_64/static_cpu_templates/t2a.rs
- tests/host_tools/uffd/Cargo.lock
- tests/integration_tests/functional/test_cpu_template_helper.py
- tests/integration_tests/functional/test_feat_parity.py
- tests/integration_tests/performance/test_process_startup_time.py
- tests/integration_tests/security/demo_seccomp/Cargo.lock
- Revert the v1.4.1 release commit
- Backport the following PRs
- #3979
- #3982
- #4011
- Backport commits to avoid failures in comparing cpu_startup_time_us with a threshold.
- Since the new v1.4.1 release commit will be included in a commit Sudan will create, this commit just reverts the release commit.
- comparing cpu_startup_time to a threshold leads to failures which are not relevant to the release so backporting commits from main which removes the comparison.
- ~~[ ] …
> Backport PRs #3979 and #3982 into v1.4

- tests/conftest.py
- tests/integration_tests/functional/test_mmds.py
- tests/integration_tests/functional/test_snapshot_advanced.py
- tests/pytest.ini
Deprecate v1.2 by raising the minimum supported version to 1.3
Per release policy after v1.4 was released
---
> Deprecate Firecracker v1.2

- tests/framework/utils_cpu_templates.py
- tests/integration_tests/functional/test_api.py
- tests/integration_tests/functional/test_cpu_features_aarch64.py
- tests/integration_tests/functional/test_cpu_template_helper.py
- tests/integration_tests/security/test_vulnerabilities.py
As we did in PR #4011, hardware vulnerability tests may also fail due to changes outside the Firecracker code (such as kernel/microcode updates), and this could block PRs. To unblock them, this commit makes these tests optional. Even if made optional, these tests will be run for each PR, allowing us to notice any failures. Also, we will run these tests every night, and continue to monitor failures and take appropriate actions in a timely manner.
- ~~[ ] Any required …
> test: Make hardware vulnerability tests optional

- .github/codecov.yml
- tests/integration_tests/build/test_coverage.py
- tools/devctr/Dockerfile
- tools/devtool
Changes the code coverage test to no longer compare to a fixed threshold and instead upload a report to codecov.io
Less PR churn due to adjusting coverage values in a dictionary and better insights into coverage
---
> Utilize codecov.io for coverage test

- src/logger/src/lib.rs
- Adds  a doc comment to the `FcLineWriter` type alias.
- Uses inline format arguments within `log_dev_preview_warning`.
Small fixes pulled out from a larger PR (https://github.com/firecracker-microvm/firecracker/pull/3971).
---
> Small fixes

- tests/integration_tests/build/test_coverage.py
For pull requests, the variable is set to the number of the pull request. For builds triggers not on pull requests its... the string literal "false". That broke submitting coverage data from non-pr branches because it tried to submit coverage data for a pull request with number "false", instead of submitting for the branch on which the test was run.
---
[3]: https://github.com/firecracker-microvm/firecracker/blob/main/CONT …
> fix: handle BUILDKITE_PULL_REQUEST correctly for non PRs

- src/cpu-template-helper/src/main.rs
- src/vmm/src/resources.rs
Replaces instances of `serde_json::from_slice(x.as_bytes())` with the equivalent but simpler `serde_json::from_str(&x)`.
Unnecessary complexity is bad.
---
> refactor: Replace redundant `serde_json::from_slice(x.as_bytes())`

- docs/snapshotting/handling-page-faults-on-snapshot-resume.md
Update the broken link of page faults handler process example.
...
...
---
> docs: Update broken link in snapshotting documentation

- docs/getting-started.md
Previously we had a separate set of artifacts for the quickstart guide. This increases maintenance burden. Instead, let's use our normal CI artifacts in the quickstart guide.
...
This way we don't need to maintain a separate set of artifacts for the quickstart
---
> doc: update quickstart artifacts

- tests/integration_tests/build/test_binary_size.py
- tests/integration_tests/performance/test_memory_overhead.py
Our current binary size test measures space in disk, as a proxy for used memory. This is not accurate, as parts of the binary are not loaded into memory.
This commits adds a new test that measures memory overhead directly and published metrics for different guest configurations.
Also remove thresholds from test_binary_size.py test, as we measure memory overhead directly now.
...
...
---
[3]: …
> test: add a test to measure Firecracker memory overhead

- .buildkite/pipeline_pr_no_block.py
- tests/framework/utils_cpu_templates.py
- tests/integration_tests/functional/test_api.py
- tests/integration_tests/functional/test_cpu_features_aarch64.py
- tests/integration_tests/functional/test_cpu_template_helper.py
- tests/integration_tests/security/test_vulnerabilities.py
We have recently introduced tests that are marked with the combination
of nonci and optional. This is because the tests are parameterized
to use different templates on x86 and ARM, but the ARM template tests
cannot be run in our PR CI due to requiring a specially compiled host
kernel. Therefore, whatever can run in our CI should run in optional,
and ARM should only run nightly.
This commit allows for what is described above.
---
[2]: https://github.com/firecracker-microvm/firecracker/blob/main/docs/api-change-runb …
> Allow for combination of no_block_pr and nonci pytest markers

- tests/integration_tests/functional/test_cpu_features_aarch64.py
With the new CI artifacts, the default G3 features changed (due to artifacts being more general purpose now). The DEFAULT_G3_FEATURES constant was updated in d1015be484d573f9f7ae92483f21a100da8aac4b, but DEFAULT_G3_FEATURES_NO_SSBS slipped through the cracks somehow.
This commit fixes a nightly test failures by updating the cpu features expected on G3 instances without SSBS.
---
[3]: …
> test: Update DEFAULT_G3_FEATURES_NO_SSBS to match new ci artifacts

- Cargo.lock
- deny.toml
- src/vmm/Cargo.toml
- tests/integration_tests/build/test_dependencies.py
These versions of serde_derive used a precompiled binary to generate the
proc-macro output on x86_64-unknown-linux-gnu. We do not want to
accidentally reintroduce these versions through a transitive dependency,
so explicitly forbid this.
https://github.com/serde-rs/serde/issues/2538
---
> Add serde_derive>1.0.171,<1.0.184 to deny.toml

- src/vmm/src/arch/aarch64/gic/mod.rs
- src/vmm/src/builder.rs
- src/vmm/src/vstate/vm.rs
Fixes kvm capability checks during snapshot restore.
Previously kvm capabilities were checked twice on snapshot
restore:
- when `Vm` was created with `create_vmm_and_vcpus`
- when `vm.restore_state` was called.
During first check `Vm` would not know about any modifications
to the list of kvm capabilities, so it would check
`DEFAULT_CAPABILITIES`. The problem is that if some
capabilities were removed from the check list
(for example if "!123" was specified in `kvm_capabilities`
field in the cpu-template for VM before snapshot)
they would still be checked during `Vm::new` call.
The fix is trivial, just pass the `kvm_capabilities` from `vm_state`
to `create_vmm_and_vcpus` call. Also removed kvm capabilities checks
from `restore_state` calls as they are not needed anymore.
By submitting this …
> Fix of kvm caps checks during restore

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- docs/snapshotting/snapshot-editor.md
- src/snapshot-editor/Cargo.toml
- src/snapshot-editor/src/edit_vmstate.rs
- src/snapshot-editor/src/info.rs
- src/snapshot-editor/src/main.rs
- src/snapshot-editor/src/utils.rs
- src/snapshot/src/lib.rs
- src/snapshot/tests/test.rs
- src/vmm/src/device_manager/persist.rs
- src/vmm/src/lib.rs
- src/vmm/src/persist.rs
- src/vmm/src/vstate/mod.rs
- src/vmm/src/vstate/vcpu/aarch64.rs
- src/vmm/src/vstate/vcpu/mod.rs
- src/vmm/src/vstate/vcpu/x86_64.rs
- src/vmm/src/vstate/vm.rs
- src/vmm/tests/integration_tests.rs
- tests/integration_tests/functional/test_snapshot_editor.py
Added initial version of `snapshot-editor` tool.
Initial functionality is:
- (aarch64 only) remove registers from vcpu states
- (aarch64 only)  print all vcpu states from vmstate file
---
> Snapshot editor

- .buildkite/pipeline_security.py
- tests/integration_tests/functional/test_cpu_template_helper.py
PR https://github.com/firecracker-microvm/firecracker/pull/4021 made some hardware vulnerability tests optional for PR merge, since those tests can fail due to changes outside the Firecracker code (such as kernel/microcode updates) and the failures would prevents PRs merged. The disadvantage of this approach is that an author and reviewers might miss failures caused by the PR.
To keep our eyes on those failures and address them correctly, we'd like to run it nightly and get noticed. This commit adds a script that generate buildkite steps to run those vulnerability tests as well as fingerprint checks.
Developer Certificate of Origin and …
> Nightly security buildkite pipeline

- tests/integration_tests/performance/test_boottime.py
See title.
There is a performance regression on 5.10 sky lake hosts that
cannot be easily resolved. To allow the CI to function well while
investigating this, this test will be skipped on this host.
---
> ci: Skip 5.10 sky lake bootime test

- CHANGELOG.md
- Cargo.lock
- docs/snapshotting/snapshot-editor.md
- docs/snapshotting/snapshot-support.md
- src/snapshot-editor/Cargo.toml
- src/snapshot-editor/src/edit_memory.rs
- src/snapshot-editor/src/main.rs
- tests/framework/microvm.py
- tests/host_tools/cargo_build.py
- tests/integration_tests/functional/test_snapshot_basic.py
Added `rebase-snap` function to the `snapshot-editor` tool.
---
> Adding `rebase-snap` to `snapshot-editor`

- tools/test-popular-containers/build_rootfs.sh
- tools/test-popular-containers/fcnet.start
- tools/test-popular-containers/test-docker-rootfs.py
The test is separated from the main integration tests as it reuires to build rootfs before running.
Add a new test for popular Docker containers.
Ensure Firecracker can run the latest popular container images.
---
> test: add a new test to run Firecracker in popular Docker containers

- Cargo.lock
- src/utils/Cargo.toml
- src/utils/src/vm_memory.rs
- src/vmm/src/devices/virtio/block/io/async_io.rs
- src/vmm/src/devices/virtio/iovec.rs
- src/vmm/src/devices/virtio/queue.rs
- src/vmm/tests/io_uring.rs
With 0.12.1, .as_ptr() got deprecated because on Xen, some additional guards need to be around before VolatileSlices can be accessed (as memory is mapped in on-demand, and those guards call mmap and mmunmap). On KVM, these are no-ops, so just inserting .ptr_guard() at the correct spaces is okay.
---
> chore: Update vm-memory to 0.12.2

- tests/framework/ab_test.py
- tests/framework/jailer.py
- tests/framework/microvm.py
- tests/framework/utils.py
- tests/host_tools/network.py
- tests/integration_tests/functional/test_balloon.py
- tests/integration_tests/functional/test_cmd_line_start.py
- tests/integration_tests/performance/test_benchmarks.py
Generalizes the A/B-testing approach used by the optional benchmark test (which does a dynamic comparison of PR HEAD vs main HEAD and determines pass state based on that). 
We want to apply this approach to performance testing and some auditing test that can block PRs across the board due to hardware changes (for example the cpu-template-helper tool tests that ensure cpu fingerprint reported inside guests stay the same, but which can fail due to microcode updates)
---
[2]: …
> A/B-Testing utilities for specifically testing changes introduced by a PR

- CHANGELOG.md
- FAQ.md
- src/vmm/src/resources.rs
- src/vmm/src/vmm_config/boot_source.rs
- tests/framework/microvm.py
- tests/integration_tests/performance/test_boottime.py
Changes "nomodules" in the default kernel cmdline to "nomodule", the correct spelling. The old argument was not recognized by the kernel and incorrectly forwarded to init binaries.
Reference: https://www.kernel.org/doc/html/v4.10/admin-guide/kernel-parameters.html
Note, **this is a breaking change** for anyone who is relying on the default kernel command line, and happens to be loading kernel modules at runtime - or if their init binary was inadvertently relying on `nomodules` to be present in argv.
Fixes https://github.com/firecracker-microvm/firecracker/issues/4090
> Fix spelling of 'nomodule' kernel param

- .buildkite/pipeline_perf.py
- tests/integration_tests/performance/configs/test_block_performance_config_4.14.json
- tests/integration_tests/performance/configs/test_block_performance_config_5.10.json
- tests/integration_tests/performance/configs/test_block_performance_config_6.1.json
- tests/integration_tests/performance/configs/test_network_latency_config_4.14.json
- tests/integration_tests/performance/configs/test_network_latency_config_5.10.json
- tests/integration_tests/performance/configs/test_network_latency_config_6.1.json
- tests/integration_tests/performance/configs/test_network_tcp_throughput_config_4.14.json
- tests/integration_tests/performance/configs/test_network_tcp_throughput_config_5.10.json
- tests/integration_tests/performance/configs/test_network_tcp_throughput_config_6.1.json
- tests/integration_tests/performance/configs/test_snapshot_restore_performance_config_4.14.json
- tests/integration_tests/performance/configs/test_snapshot_restore_performance_config_5.10.json
- tests/integration_tests/performance/configs/test_snapshot_restore_performance_config_6.1.json
- tests/integration_tests/performance/configs/test_vsock_throughput_config_4.14.json
- tests/integration_tests/performance/configs/test_vsock_throughput_config_5.10.json
- tests/integration_tests/performance/configs/test_vsock_throughput_config_6.1.json
Update performance baselines and re-enable them.
To continue monitoring performance until we implement a better way.
---
> Re-enable performance baselines

- tests/framework/artifacts.py
- tests/framework/stats/core.py
- tests/framework/utils.py
- tests/integration_tests/functional/test_mmds.py
- tools/devctr/pyproject.toml
With our current firecracker_release fixture, some tests are only run
against released firecracker versions that we keep in an S3 bucket. This
means the binary in the working copy does not execute those tests, and
we may only realize until we make a release, at which point is too late
and we have to make a patch release.
Fix it by extending the firecracker_release fixture to also test the
current binary as a regular release, so it goes through the same tests.
---
[2]: …
> Test the current binary as a regular release

- .cargo/audit.toml
To solve a cargo audit on vm-memory<=0.12.1
...
...
---
> [1.3][Backport] Add RUSTSEC-2023-0056 to audit.toml

- tests/integration_tests/performance/test_boottime.py
Test with all supported guest kernels, and a few different guest configurations.
In addition, boot 10 times instead of a single datapoint.
Add a boottime test
We currently only check the guest 4.14 kernel, with a small microvm size. This test generates more metrics so we have a better understanding of how VM size affects boot time.
---
> test: add a new, more complete boottime test

- .cargo/audit.toml
- tests/integration_tests/security/test_vulnerabilities.py
To solve a cargo audit on vm-memory<=0.12.1
...
...
---
> [1.4][Backport] Add RUSTSEC-2023-0056 to audit.toml

- .cargo/config
- tests/host_tools/cargo_build.py
Currently, every cargo invocation in the integration tests runs with -Dwarnings. This is fairly annoying, because it causes all tests to fail if there is a single compilation warning emitted somewhere. When locally testing some changes, this means that code needs to be cleaned up to fix all warnings before any test can be run, which makes rapid prototyping very slow.
This commit changes our testing to only pass -Dwarnings to our clippy lint test. This way we still block CI on compiler warnings, but no longer prevent literally every test from running if a single warning is emitted anywhere.
Developer Certificate of Origin and signing off your …
> test: Only run clippy lint test with -Dwarnings

- tools/devtool
Currently, devtool test silently fails if aws cli is not installed, which results in CI artifacts not getting downloaded, which results in all tests being skipped. Since the error message from downloading artifacts is burried in other output, explicitly abort.
We have received multiple reports of all integration tests being skipped due to "empty fixtures", which happens if artifacts fail to download. They can usually be traced back to aws cli not being installed, so make this case a bit more obvious.
---
[2]: …
> test: Print error message if aws cli not available

- tools/devtool
They were syntactically incorrect
...
...
---
> fix: Remove test brackets from awscli check

- MAINTAINERS.md
Few members are not part of the team anymore so updating the list.
---
> chore: update maintainers

- src/vmm/src/arch/aarch64/regs.rs
- src/vmm/src/arch/x86_64/mptable.rs
This PR removes some `unsafe` code by replacing it with safe alternatives, and removes some wrapper types that are not needed anymore since we started merging the workspace crates.
Less unsafe code
---
> Cleanup some `unsafe` code

- tests/integration_tests/security/test_vulnerabilities.py
- tools/devtool
- Show microcode version with `tools/devtool test`.
- Run the sysfs vulnerabilties test on host.
See the commit messages.
---
[2]: …
> Tiny enhancements for CI tests

- .buildkite/pipeline_pr.py
- tests/README.md
- tests/framework/microvm.py
- tests/framework/microvm_helpers.py
- tests/host_tools/memory.py
- tools/devtool
Some unrelated changes included:
- a fix for the devctr sanity build
- remove some dead code
This enables interactive use of Microvms, will follow up with a sandbox helper script.
---
> Microvm helpers for interactive usage

- tests/integration_tests/performance/configs/test_vsock_throughput_config_5.10.json
- tests/integration_tests/performance/configs/test_vsock_throughput_config_6.1.json
Updated m6a vsock_throughput perf
```
{
"source": "e2aabc2a76fd72b85dde734f2ae34ebe1ac5a16c/tests/integration_tests/performance/configs/",
"test_vsock_throughput_config_5.10.json": {
"test": "vsock_throughput",
"kernel": "5.10",
"cpus": [
{
"instance": "m6a.metal",
"model": "AMD EPYC 7R13 48-Core Processor",
"stats": {
"cpu_utilization_vcpus_total": {
"mean": -0.6593137024964435,
"stdev": 1.1152718594162747
},
"mean": 0.0,
"stdev": 1.1239029738980326
}
},
"mean": 0.5365316881725035,
"stdev": 1.2375661219742082
},
"mean": -0.95,
"stdev": 1.6050905860647506
}
},
"throughput": { …
```
> chore(perf): updated m6a vsock_throughput perf

- Cargo.lock
- src/api_server/Cargo.toml
- src/api_server/src/lib.rs
- src/api_server/src/parsed_request.rs
- src/dumbo/Cargo.toml
- src/firecracker/src/api_server_adapter.rs
- src/mmds/Cargo.toml
Use dedicated kill switch mechanism to break out of micro-http loop and gracefully shutdown the API server thread.
Remove hacky "/shutdown-internal" HTTP request which was externally exposing a way to bring down parts of firecracker components.
Ideally needs https://github.com/firecracker-microvm/micro-http/pull/33 merged first, then point the dependency there.
---
> Api server thread clean shutdown

- tests/integration_tests/test_kani.py
Prior to #4120, our unique way of runnign seccompiler inside of build.rs made it impossible to run kani or miri on the workspace (requiring it to be run on some crate which did not use the build script). With that all gone, we can finally run kani properly.
---
> test: Simplify test_kani.py

- .buildkite/pipeline_pr.py
- .cargo/config
- tests/integration_tests/build/test_binary_static_linking.py
- tools/devtool
- tools/release.sh
- Remove default target from .cargo/config
- check if Firecracker release binary is actually compiled using musl (static link) or gnu (dynamic link)
- test static linking of release binary
- create a dummy tests/test-report that release.sh can copy to avoid copy error
- The global `target` directive in .cargo/build forced the x86_64-unknown-linux-musl target whenever `--target` flag was not provided and because of this `cargo build` produced x86_64 binaries even if we tried to build on ARM. Though `devtool build` is the documented way to build Firecracker and does not have this issue since it always specifies the right arch `--target`, we would like to fix issues like #3221 and be able to just run `cargo run` without specifying the target.
- We want to make sure Firecracker release binary …
> fix: remove default target for cargo + check static linking of firecracker release binary

- .buildkite/pipeline_ab.py
- .github/workflows/trigger_ab_tests.yml
Adds a GitHub action that triggers the A/B-testing buildkite pipeline
To do an A/B-test on PR merge, the buildkite pipeline needs to know both the revision that main had before a PR was merged, and the revision after the merge. However, buildkite only provides the latter (e.g. it does not forward all information from the github push webhook payload to the actual pipeline). Therefore, we use a shim GitHub action that forwards both revisions to the build in environment variables.
---
[2]: …
> GitHub Action to orchestrate performance A/B-Tests

- tools/create_snapshot_artifact/main.py
- tools/test-popular-containers/test-docker-rootfs.py
Make testing framework available so that the few tools scripts using them work as expected.
changes added in #4089 breaks cross snapshot restore tests.
---
> fix:import testing framework for few tools scripts

- CHANGELOG.md
- docs/api-change-runbook.md
- docs/cpu_templates/cpu-templates.md
- src/api_server/src/lib.rs
- src/api_server/src/request/balloon.rs
- src/api_server/src/request/boot_source.rs
- src/api_server/src/request/cpu_configuration.rs
- src/api_server/src/request/drive.rs
- src/api_server/src/request/logger.rs
- src/api_server/src/request/machine_configuration.rs
- src/api_server/src/request/metrics.rs
- src/api_server/src/request/mmds.rs
- src/api_server/src/request/net.rs
- src/api_server/src/request/snapshot.rs
- src/api_server/src/request/vsock.rs
- src/api_server/swagger/firecracker.yaml
- src/vmm/src/cpu_config/templates.rs
- src/vmm/src/vmm_config/machine_config.rs
- tests/integration_tests/functional/test_api.py
Deprecate the `cpu_template` field in the `/machine-config` API, which is used to set static CPU templates.
Since v1.4.0, Firecracker has supported custom CPU templates that allows users to define their own CPU templates and can be used as an alternative of static CPU templates.
---
[3]: …
> vmm: Deprecate static CPU templates

- .buildkite/pipeline_ab.py
- tests/framework/utils_iperf.py
- tests/host_tools/metrics.py
- tests/integration_tests/performance/test_network_ab.py
- tests/integration_tests/performance/test_snapshot_ab.py
- tests/integration_tests/performance/test_vsock_ab.py
- tools/ab_test.py
Adds A/B compatible versions of the vsock and tcp throughput tests. Also includes the following small refractorings/improvements:
- Declare specific tests are particularly unstable. These are the tests that already have significant delta values associated with them in the current testing setup.
- Correctly associate p-values with metrics when submitting to Cloudwatch
- Correctly propagate CW metadata when reemitting captured logs (namespace and log stream name)
- Only run A/B tests if rust/python code was modified.
- Merge the two network tests into one file, because they are significantly simpler now
Developer Certificate of Origin and …
> Final A/B-Tests

- .buildkite/pipeline_pr.py
- docs/formal-verification.md
- tests/integration_tests/test_kani.py
- tools/devtool
Trying to run the kani integration test outside of the CI will almost certainly result in out of memory conditions in the best case, and in system hangs in the worst case. Therefore, do not attempt to run kani if running tests locally.
Also removes an unneeded assertion, as `run_cmd` already checks the exit code by default.
---
> test: Skip kani if not enough RAM

- CHANGELOG.md
- README.md
- docs/prod-host-setup.md
- tests/framework/properties.py
- tests/integration_tests/performance/test_boottime.py
- tools/devtool
- Note in the changelog that we officially support Linux 6.1 kernel.
- Document how to deal with performance regressions in Linux 6.1.
- Enforce the boot time SLA of 150ms in 6.1 back (reverts 1c0b992cafa0fa6712b7db9f370539da06fe50aa)
Closes #3837 
To keep up to date with stable Linux kernel releases.
---
> Support AL2023 officially

- src/firecracker/src/main.rs
- tests/integration_tests/functional/test_cmd_line_parameters.py
Restore the default value of the `--id` parameter, since it can cause a panic. And move the "running" message after the option is processed.
Without the change:
```
% sudo ./firecracker
2023-10-09T09:49:41.031007002 [anonymous-instance:main] Running Firecracker v1.5.0-dev
2023-10-09T09:49:41.031082658 [anonymous-instance:main] Firecracker panicked at 'called `Option::unwrap()` on a `None` value', src/firecracker/src/main.rs:291:52
[1]    980007 IOT instruction  ./build/cargo_target/x86_64-unknown-linux-musl/debug/firecracker
```
```
% sudo ./firecracker --id myname
2023-10-09T09:50:40.670878137 [anonymous-instance:main] Running Firecracker v1.5.0-dev
```
With the change:
```
% sudo ./firecracker
2023-10-09T10:01:11.604960827 [anonymous-instance:main] Running Firecracker v1.5.0-dev
```
``` …
```
> fix: restore the id parameter default

- .github/workflows/trigger_ab_tests.yml
- tests/framework/ab_test.py
- tests/framework/utils_iperf.py
- tests/host_tools/metrics.py
- tests/integration_tests/performance/test_block_ab.py
- tests/integration_tests/performance/test_network_ab.py
- tests/integration_tests/performance/test_vsock_ab.py
- tools/ab_test.py
This PR contains a variety of QoL refractors/small bug fixes for the performance A/B-testing setup. The most important change is in c3e27035c5c6e9e4132917c8ae6a64224ab079e9, which introduces a mechanism for using correlations between results for a metric across multiple tests to identify (and ignore) outliers and thus reduce false positives.
(a previous version of this PR contained an increased threshold for snapshot restore tests, due to their high instability, but this instability has since been fixed in #4151)
---
[1]: …
> Tweaks to reduce false positive rate of A/B-Tests
