firecracker-microvm/firecracker

Cargo.lock
docs/getting-started.md
src/api_server/swagger/firecracker.yaml
src/cpu-template-helper/Cargo.toml
src/firecracker/Cargo.toml
src/jailer/Cargo.toml
src/rebase-snap/Cargo.toml
src/seccompiler/Cargo.toml
src/vmm/src/version_map.rs
tests/framework/artifacts.py
tools/devtool

Things that need to happen after the release branch was taken
---

Release 1.5 postperations

---

CHANGELOG.md
CREDITS.md
Cargo.lock
src/api_server/swagger/firecracker.yaml
src/cpu-template-helper/Cargo.toml
src/firecracker/Cargo.toml
src/jailer/Cargo.toml
src/rebase-snap/Cargo.toml
src/seccompiler/Cargo.toml
tools/release.sh

Commit generated by `./tools/release-prepare.sh 1.5.0`. Only manual change was removing dependabot from `CREDITS.md`
---

chore: release v1.5.0

---

.buildkite/pipeline_pr.py
tests/framework/microvm.py
tests/integration_tests/functional/test_concurrency.py
tools/devtool
tools/release.sh
tools/update-credits.sh

Speeding up the running of tests, and automation of dependabot removal
less friction. also the other PR doesnt let itself get reopened
---

Improve QoL for release process

---

docs/cpu_templates/boot-protocol.md
docs/network-performance.md
docs/snapshotting/versioning.md
tools/devctr/Dockerfile
tools/devctr/poetry.lock
tools/devtool

Builds the backend from source at the devctr build time and installs the binary at `/usr/local/bin/vhost-user-blk` .
This also installs a runtime dependency: libglib2.0-dev .
Increases the image size by about 80M.
Required for vhost-user-blk device testing.
- ~[ …

chore(devctr): add qemu vhost-user-blk backend

---

CHANGELOG.md

We want to separate these from the "changes" section.
...
...
---

docs: Add "deprecated" section to changelog

---

docs/getting-started.md

When generating the 1.6 artifacts, it got updated, but I forgot to update the link.
Closes #4173
---

docs: Update vmlinux patch version in getting-started.md

---

CHANGELOG.md
docs/RELEASE_POLICY.md
docs/api-change-runbook.md

- Points semver links to the v2.0.0-specific one.
- Simplifies and clarifies the removal policy of deprecated API elements
Closes #4157 .
---

Update removal policy of deprecated API elements

---

CHANGELOG.md
src/firecracker/src/main.rs
src/vmm/src/logger/logging.rs
tests/framework/microvm.py
tests/integration_tests/functional/test_logging.py

Move the message after the logger has been configured, so it actually gets printed.
Eliminate redundant message that outputs internal vmm crate version 0.1.0.
Fixes: 96ed4576, 332f218
It can happen that the version printed is v0.1.0, instead of the expected version.
```
2023-10-12T15:15:39.609772934 [4a97aac2-88bc-4f59-8fe1-167bc078ac7e:main] Running Firecracker v0.1.0
```
This behavior may confuse users of the logs.
--- …

fix: move the logging message where it's effective

---

tests/integration_tests/performance/configs/test_network_latency_config_4.14.json
tests/integration_tests/performance/configs/test_network_latency_config_5.10.json
tests/integration_tests/performance/configs/test_network_latency_config_6.1.json

Jonathan Woollett-Light <jcawl@amazon.co.uk>
Disables 5.10 network latency baseline by removing the statistic.
To mitigate intermittent failures due to non-Firecracker changes.
---

ci: Disable network latency baseline

---

CHANGELOG.md
src/vmm/src/devices/mod.rs
src/vmm/src/devices/virtio/net/device.rs
src/vmm/src/devices/virtio/net/event_handler.rs
src/vmm/src/devices/virtio/net/metrics.rs
src/vmm/src/devices/virtio/net/mod.rs
src/vmm/src/devices/virtio/net/test_utils.rs
src/vmm/src/devices/virtio/test_utils.rs
src/vmm/src/logger/metrics.rs
tests/integration_tests/functional/test_metrics.py

- Move NetDeviceMetrics from logger to Net module.
- Use NET_DEV_METRICS_PVT instead of adding an entry of NetDeviceMetrics in Net so that metrics can be flushed even from signal handlers.
- use individual metrics instead of METRICS.net.
- Use "net_$iface_id" for the metrics name instead of "net_$tap_name" to be consistent with the net endpoint "/network-interfaces/{iface_id}".
- To add more granularity in analysing network device metrics.
- ~[ ] API changes follow the …

feat: Add per net device metrics

---

CHANGELOG.md
src/firecracker/src/main.rs
tests/framework/vm_config_network.json
tests/integration_tests/functional/test_cmd_line_start.py

Pass through no-API shutdown exit code
https://github.com/firecracker-microvm/firecracker/issues/4176
Without passing through the exit code a non-zero exit code was returned on a successful no-API shutdown.
---

fix: Pass through no-API shutdown exit code (main)

---

CHANGELOG.md
src/firecracker/src/main.rs
tests/framework/vm_config_network.json
tests/integration_tests/functional/test_cmd_line_start.py

Pass through no-API shutdown exit code
https://github.com/firecracker-microvm/firecracker/issues/4176
Without passing through the exit code a non-zero exit code was returned on a successful no-API shutdown.
---

fix: Pass through no-API shutdown exit code (1.5)

---

tests/integration_tests/performance/test_block_ab.py
tests/integration_tests/performance/test_snapshot_ab.py

Some functions get renamed but the tests didn't get updated.
---

fix block_ab and snapshot_ab after 4160

---

CHANGELOG.md
src/firecracker/src/api_server_adapter.rs
src/firecracker/src/main.rs
tests/integration_tests/functional/test_cmd_line_start.py

Refactors error propagation to avoid logging and printing misleading error messages.
#4176 
---

fix: Refactor error propagation

---

CHANGELOG.md
src/firecracker/src/api_server_adapter.rs
src/firecracker/src/main.rs
tests/integration_tests/functional/test_cmd_line_start.py

Refactors error propagation to avoid logging and printing misleading error messages.
See above.
---

fix: Refactor error propagation (1.5)

---

src/vmm/src/arch/x86_64/mptable.rs
src/vmm/src/arch/x86_64/regs.rs
src/vmm/src/builder.rs
src/vmm/src/devices/virtio/balloon/device.rs
src/vmm/src/devices/virtio/net/test_utils.rs
src/vmm/src/devices/virtio/test_utils.rs
src/vmm/src/devices/virtio/vsock/packet.rs
src/vmm/src/vstate/memory.rs
src/vmm/src/vstate/vm.rs
tests/integration_tests/build/test_unittests.py

Removed guard pages
Initially guard pages were added as a defence mechanism to prevent guest or firecracker from accessing guest memory outside of allocated memory. Main concern was the possibility of a bug in the device emulation, that can lead to the security issue. As of right now firecracker creates guest memory backed by memfd and utilizes different forms of verification and other defence in depth mechanisms such as jailing. Additionally guard pages do not provide a generic defence mechanism.
---
[2]: …

Remove guard pages

---

docs/getting-started.md

- Firecracker CI artifacts were updated but the links were not so update the link.
- Unify the way firecracker binary is made available in a directory so that it is easier for the users to copy pase the commands with less modifications.
A broken link to CI artifact was reported.
- ~~[ ] …

Update Getting started docs

---

CHANGELOG.md
docs/snapshotting/snapshot-editor.md
docs/snapshotting/snapshot-support.md
src/rebase-snap/src/main.rs

Marked `rebase-snap` as deprecated in favour of `snapshot-editor`
We have `snapshot-editor` which is a newer tool with more options.
---

Marked `rebase-snap` as deprecated

---

CHANGELOG.md
docs/snapshotting/snapshot-editor.md
src/snapshot-editor/src/info.rs
src/vmm/src/vstate/vcpu/aarch64.rs
src/vmm/src/vstate/vcpu/x86_64.rs

Add subcommand in InfoVmStateSubCommand to print the VmState.
Printing MicrovmState from vmstate file of snapshot makes snapshot comparison easier to read.
The command can be used as below on 2 different snapshot files and the output when compared using any diff tool (e.g. vimdiff) is lot easier to read.
<details>
<summary>An example run on aarch64</summary>
```
snapshot-editor info-vmstate vm-state --vmstate-path vmstate.snap1 > readable_vmstate.snap1
```
```
[~]$ cat readable_vmstate.snap1 
MicrovmState {
vm_info: VmInfo {
mem_size_mib: 128,
smt: false,
cpu_template: None,
boot_source: BootSourceConfig {
kernel_image_path: "./vmlinux",
initrd_path: Some(
"./initrd.cpio",
),
boot_args: Some(
"ro console=ttyS0 noapic reboot=k panic=1 pci=off nomodule random.trust_cpu=on i8042.noaux …
```

Print MicrovmState from vmstate file of snapshot

---

.buildkite/pipeline_ab.py
tests/framework/utils_vhost_user_backend.py
tests/host_tools/drive.py
tests/integration_tests/functional/test_drive_vhost_user.py
tests/integration_tests/performance/test_block_ab.py

This adds a performance test for the vhost-user-blk device.
vhost-user-blk device is added in https://github.com/firecracker-microvm/firecracker/pull/4170 .
We need to include performance tests for the new device.
---
[1]: …

Performance test for vhost-user-blk

---

src/vmm/src/builder.rs
tests/integration_tests/performance/test_boottime.py

Add a couple of events to the debug logs. With this information we can extract information of how long did those events take.
Added as debug messages to make it clear to customers that these are unstable and may change format or disappear at any moment, at should not be depended upon.
...
To have better visibility on where time goes during boottime.
---
[3]: https://github.com/firecracker-microvm/firecracker/blob/main/CONT …

feat: add a debug log for vm build time

---

src/rebase-snap/src/main.rs

- Moves the deprecation message not to come before the version info.
Commit ded9038aca16 ("deprecation(rebase-snap): marked rebase-snap as deprecated") breaks our release process, because it shows the deprecation message before the version info and the release script gets the version from the first line.
- ~~[ ] …

fix(rebase-snap): Move deprecation message after version info

---

README.md
docs/snapshotting/snapshot-support.md

Re(move) topic-specific issues and limitations from the main README page.
Only one limitation remains there that does not have a better location as of now.
We have a number of topic-specific limitations listed on the main README page that cause confusion about where a new limitation needs to be added, to the main README or elsewhere.
- ~[ ] All …

doc: clean up limitation section on the main readme page

---

src/vmm/src/devices/virtio/balloon/event_handler.rs
src/vmm/src/devices/virtio/net/event_handler.rs
src/vmm/src/devices/virtio/rng/device.rs
src/vmm/src/devices/virtio/virtio_block/event_handler.rs
src/vmm/src/devices/virtio/vsock/device.rs
src/vmm/src/devices/virtio/vsock/event_handler.rs
src/vmm/src/devices/virtio/vsock/unix/muxer.rs

Removed redundant `debug!` logs. These logs were used to trace execution of the FC, but it is better to use tracing tools for this.
---

chore(logs): removed redundant `debug!` logs

---

.buildkite/pipeline_perf.py
tests/framework/utils_drive.py
tests/integration_tests/performance/test_block_ab.py
tests/integration_tests/performance/test_block_performance.py

- Use correct name `add_vhost_user_drive()` in the test instead of the old name `add_vhost_user_block()`.
- Fix socket path
- Use different names for pipeline groups
- The method name has changed in https://github.com/firecracker-microvm/firecracker/commit/1c3c411133375fd3a69cbaf42cca09fdc44090ec, but was not updated in a parallel PR during a rebase.
- Incorrect socket path
- Same name for 2 BK pipeline groups
- ~[ ] Any required documentation changes (code and docs) are …

fix(test/perf/block): several minor fixes

---

src/vmm/src/devices/virtio/vsock/csm/connection.rs
src/vmm/src/devices/virtio/vsock/device.rs
src/vmm/src/devices/virtio/vsock/event_handler.rs
src/vmm/src/devices/virtio/vsock/metrics.rs
src/vmm/src/devices/virtio/vsock/mod.rs
src/vmm/src/devices/virtio/vsock/unix/muxer.rs
src/vmm/src/logger/metrics.rs
tests/integration_tests/functional/test_vsock.py

- Move vsock metrics out of logger to Vsock.
- Add check to test breaking change in vsock metrics.
- Net and Block metrics are moved out of logger so to be consistent in having device metrics in their own modules and decouple Vsock metrics from logger.
---
[2]: …

Vsock metrics

---

tests/integration_tests/performance/test_block_ab.py
tests/integration_tests/performance/test_block_performance.py

Omit randwrite test for vhost-user-blk and leave only randread.
Qemu vhost-user-blk backend uses O_DIRECT when accessing the block file.
Retrieving randwrite metric for this test does not represent significant value, because it is unlikely to be used in production setups due to low performance.
- ~[ ] User-facing changes …

test(perf): omit randwrite test for vhost-user-blk

---

CHANGELOG.md
src/vmm/src/devices/virtio/mod.rs
src/vmm/src/devices/virtio/vhost_user_block/device.rs
src/vmm/src/devices/virtio/vhost_user_metrics.rs
src/vmm/src/logger/metrics.rs
tests/host_tools/metrics.py
tests/integration_tests/functional/test_drive_vhost_user.py

- Add below metrics for vhost user device: 
1. to report activate failures.
2. to report failure to read config space.
3. to report time taken to init the device in micro seconds.
4. to report time taken to activate the device in micro seconds.
- Add test to validate breaking change in vhost device metrics.
Vhost user block is a new device which doesn't have any metrics.
- ~~[ ] New `TODO`s link to an …

Vhost user blk metrics

---

tests/framework/artifacts.py
tests/framework/utils_cpu_templates.py
tests/framework/utils_cpuid.py

Changes to depend less on exact instances and more on the CPU model.
This is useful to make the tests work in other instances that have the same CPUs.
---

Fixes to handle more instances with existing CPUs

---

src/vmm/src/builder.rs
src/vmm/src/device_manager/persist.rs
src/vmm/src/devices/legacy/i8042.rs
src/vmm/src/devices/legacy/mod.rs
src/vmm/src/devices/legacy/rtc_pl031.rs
src/vmm/src/devices/legacy/serial.rs
src/vmm/src/devices/mod.rs
src/vmm/src/devices/virtio/balloon/device.rs
src/vmm/src/devices/virtio/balloon/event_handler.rs
src/vmm/src/devices/virtio/balloon/metrics.rs
src/vmm/src/devices/virtio/balloon/mod.rs
src/vmm/src/devices/virtio/rng/device.rs
src/vmm/src/devices/virtio/rng/metrics.rs
src/vmm/src/devices/virtio/rng/mod.rs
src/vmm/src/logger/metrics.rs
src/vmm/src/logger/mod.rs

Move Virtio and legacy device metrics out of logger to their respective modules.
To be consistent in approach to move device metrics to their own modules.
---
[3]: …

Refactor devmetrics

---

src/api_server/src/lib.rs
src/seccompiler/src/lib.rs
src/snapshot/src/lib.rs
src/utils/src/net/mod.rs
src/vmm/src/dumbo/mod.rs
src/vmm/src/io_uring/mod.rs
src/vmm/src/lib.rs
src/vmm/src/logger/mod.rs
src/vmm/src/rate_limiter/mod.rs

In our CI, we explicitly check that no warnings are present (by meanings of -Dwarnings during build tests). This means that there is no need to have #![deny(...)] instead of #![warn(...)] directives in the source code. On the other hand, having deny directives makes prototyping more annoying, as scrappy code will not compile until all compiler warnings are fixed (which might not neccessarily make sense when prototyping).
See also https://github.com/firecracker-microvm/firecracker/pull/4106
---
[2]: …

fix: Downgrade #![deny(...)] to #![warn(...)]

---

.buildkite/pipeline_ab.py
.buildkite/pipeline_perf.py
.buildkite/pipeline_pr.py
.buildkite/pipeline_pr_no_block.py
tests/framework/microvm.py
tests/integration_tests/performance/test_block_ab.py
tests/integration_tests/performance/test_boottime.py
tests/integration_tests/performance/test_network_ab.py
tests/integration_tests/performance/test_vsock_ab.py
tools/devtool

- Disable idle states when running performance tests in CI
- Limit P-states to the highest p-state at which the processor can continuously operate safely.
- Disable turbo boost also on non-intel instances (if they support turbo boost in the first place)
Consolidate performance tweaks in one location
---

Disable CPU idle states when running performance tests in CI

---

tests/framework/utils_drive.py
tests/integration_tests/performance/test_block_performance.py
tools/devctr/Dockerfile
tools/devctr/poetry.lock
tools/devtool

This includes a `crosvm` vhost-user-blk backend in the devctr and adds a test helper to trigger vhost-user-blk device resizes.
We would like to test that Firecracker handles config changes in vhost-user-blk drives properly. …

test(vhost-user-blk): add a helper for drive resizing

---

CHANGELOG.md
docs/api_requests/block-io-engine.md
docs/api_requests/block-vhost-user.md
docs/api_requests/patch-block.md
docs/design.md
docs/device-api.md
src/api_server/swagger/firecracker.yaml

Add documentation for the vhost-user-blk device.
vhost-user-blk device is added in https://github.com/firecracker-microvm/firecracker/pull/4170 .
- ~[ ] All added/changed functionality is tested.~
---
[3]: …

doc: add vhost-user-blk documentation

---

docs/vsock.md

Related to issues/#3872.
Add some more details to make debugging vsock issues easier for users.
We have `CONFIG_VIRTIO_VSOCKETS=y` in our guest configurations however, if customers want to keep it `CONFIG_VIRTIO_VSOCKETS=m` then they would have to load `vmw_vsock_virtio_transport` manually.
Not adding the description or steps to load `vmw_vsock_virtio_transport` to keep the steps are short and simple and also because we don't do that in our CI.
One step forward in helping customers with debugging vsock related issues.
- ~~[ ] API changes follow …

doc: Add kernel pre-requisites for vsock

---

src/vmm/src/devices/virtio/vhost_user_block/event_handler.rs

Updated log message for init event because previous version could be confusing for users.
---

chore(vhost-user-block): updated log message for init event

---

.buildkite/pipeline_perf.py

argparse's `action="append"` interacts unexpectedly with default arguments, in the sense that it will _always_ include the default arguments in the resulting list, and then appends any actually specified argument to the default list. This meant that doing something like `.buildkite/pipeline_perf.py --test memory-overhead` will first cause steps for _every_ performance test be added, and then another copy of the memory overhead step.
Relevant python docs: https://docs.python.org/3/library/argparse.html#action
> 'append' - This stores a list, and appends each argument value to the list. It is useful to allow an option to be specified multiple times. **If the default value is non-empty, the default elements will be present in the parsed value for the option, with any values from the command …

test: Fix default handling of pipeline_perf --test argument

---

tests/integration_tests/performance/test_boottime.py

revert commit e8b5a6ff46646a9e772ed3853f70bd63c37bcf2f and re-enables checking against the 150ms SLA.
The boot time regression was resolved by another host kernel update and no changes in Firecracker.
Regression fixed in Kernel version: 6.1.61-85.141.amzn2023.x86_64
- ~~[ ] User-facing changes are mentioned in …

Revert "ci: skip boottime SLA in m6i Linux 6.1"

---

CHANGELOG.md

- Merge the item about metrics with the main one
- Mention snapshotting limitaion
- Add PR 4247 that removes device config offset
Changelog contains 2 entries related to a newly added device (vhost-user-blk). Having a separate entry for metrics does not make sense, because users didn't have a chance to experience the device without metrics.
- ~[ ] All added/changed functionality is tested.~
- ~[ ] New …

doc(changelog): deduplicate vhost-user-blk entries

---

tests/conftest.py
tests/framework/artifacts.py
tests/framework/jailer.py
tests/framework/microvm.py
tests/framework/microvm_helpers.py
tests/framework/utils.py
tests/framework/utils_iperf.py
tests/host_tools/network.py
tests/integration_tests/functional/test_api.py
tests/integration_tests/functional/test_cmd_line_start.py
tests/integration_tests/functional/test_net.py
tests/integration_tests/functional/test_net_config_space.py
tests/integration_tests/functional/test_serial_io.py
tests/integration_tests/functional/test_shut_down.py
tests/integration_tests/performance/test_rate_limiter.py
tests/integration_tests/security/test_jail.py
tools/create_snapshot_artifact/main.py
tools/devctr/Dockerfile
tools/sandbox.py
tools/test-popular-containers/test-docker-rootfs.py

Some changes in the tests framework. 
- Allow setting the NUMA node in integration tests.
- Extract the Network namespace logic out of the Jailer class, for more flexibility.
- Drop the resource path concept since it is not needed.
This is not needed for any of the current tests, but it can be useful when building new performance tests.
---

[test] Allow setting the NUMA node

---

resources/seccomp/aarch64-unknown-linux-musl.json
resources/seccomp/x86_64-unknown-linux-musl.json
src/api_server/src/request/drive.rs
src/vmm/src/devices/virtio/mmio.rs
src/vmm/src/devices/virtio/vhost_user_block/device.rs
src/vmm/src/devices/virtio/vhost_user_metrics.rs
src/vmm/src/lib.rs
src/vmm/src/rpc_interface.rs
src/vmm/src/vmm_config/drive.rs
tests/framework/microvm.py
tests/host_tools/metrics.py
tests/integration_tests/functional/test_api.py
tests/integration_tests/functional/test_drive_vhost_user.py

Updated `PATCH /drive` command to trigger config update for vhost-user-block devices if no parameters set.
The config update includes reading new config from the backend and notifying the guest about the changes.
Also added new metric for vhos-user devices that measures time it took to read new config from the backend and 
notify guest about it.
---
[3]: https://github.com/firecracker-microvm/firecracker/blob/main/CONTRIBU …

Vhost user blk basic config change

---

.github/workflows/trigger_ab_tests.yml

Currently, our runs get triggered on `/ref/heads/main`. For consistency with other pipelines, normalize that to just `main`.
---

fix: Trigger A/B-Test runs by $GITHUB_REF_NAME

---

.github/workflows/trigger_ab_tests.yml

This caused the triggered buildkite run to be on the literal string `"$GITHUB_REF_NAME"` instead of the value of the environment variable.
Fixes: cfc80403badbdfd71e10e668ac2c586c2a47b712
...
...
---

fix: environment variables dont interpolate with single quotes

---

docs/jailer.md
src/jailer/src/env.rs
src/jailer/src/main.rs

- Use the double fork method to daemonize jailer as suggested in https://0xjet.github.io/3OHA/2022/04/11/post.html
1st fork to make sure setsid doesn't fail and 2nd fork is to
make sure the daemon code cannot reacquire a controlling terminal.
In addition to the CI tried running --daemonize manually as per steps mentioned in https://github.com/firecracker-microvm/firecracker/issues/4140 and didn't see the setsid error.
- When running jailer with --daemonize, the jailer used to fail
to start if it was started a process group leader, because setsid()
returns an error if the calling process is already a process group
leader.
This was a common reported issue by users running jailer manually.
Compared to maintaining a document which was rather difficult to
understand and explain, it is easier …

Use the double fork method to daemonize jailer

---

Cargo.lock
src/vmm/Cargo.toml
src/vmm/src/logger/logging.rs

This commit re-introduces this support such that all variants should again be supported.
https://github.com/firecracker-microvm/firecracker/pull/4047 updated
parsing the logger level filter. It removed all case variants outside
fully uppercase (e.g. `INFO`) and the 1st character being upper case
(e.g. `Info`) this removed support for other previously supported
variants e.g. `info`. 
- …

fix: Support all logger level case variants

---

src/firecracker/src/api_server_adapter.rs
src/firecracker/src/main.rs
src/vmm/src/lib.rs
src/vmm/src/rpc_interface.rs

An exit code is a kind of `Result`: Either everything is `Ok()` if the exit code = 0, or some `Err()` happened if exit code != 0. Therefore, nesting `FcExitCode` inside the `Err` variant of a Rust `Result` yields a construct of `Result<_, Result<_, _>>`. This is no well-defined (as it is unclear what `Err(Ok(...))` is supposed to mean). This was made worse by the existence of `ApiServerError::MicroVMStoppedWithoutError`, which turned `ApiServerError` into a kind of `Result` itself. Since `MicroVmStoppedWithoutError` has a field of type `FcExitCode`, we ended up with a construct of `Result<_, Result<Result<_, _>, _>`, or, in terms of user visible error messages: "RunWithApiError error: MicroVMStopped without an error: GenericError". The confusion around this lead to bugs such as #4176. …

Cleanup confusion arising from mixing of unix exit codes and Rust `Result` types

---

tools/ab_test.py

In addition to the absolute change, also make it print the relative change compared to the old value
---

Make ab_test.py print relative delta of changes

---

src/vmm/src/builder.rs
src/vmm/src/devices/virtio/vhost_user_block/device.rs
src/vmm/src/devices/virtio/virtio_block/device.rs
src/vmm/src/resources.rs
src/vmm/src/rpc_interface.rs
src/vmm/src/vmm_config/drive.rs
tests/integration_tests/functional/test_api.py

Updated `BlockDeviceConfig` to have `file_engine_type` as an optional filed, instead of a filed with default value. This is done, because for vhost-user-block this field is not used, but it would still be have some value when user would request the block config.
With this change config for vhost-user-block will return `None` for `file_engine_type`.
---
[3]: https://github.com/firecracker-microvm/firecracker/blob/main/CONTR …

fix(drive): made FileEngineType optional

---

CHANGELOG.md
Cargo.lock
src/vmm/Cargo.toml
src/vmm/src/logger/logging.rs

Backport PR #4242 
This commit re-introduces this support such that all variants should again be supported.
https://github.com/firecracker-microvm/firecracker/pull/4047 updated
parsing the logger level filter. It removed all case variants outside
fully uppercase (e.g. `INFO`) and the 1st character being upper case
(e.g. `Info`) this removed support for other previously supported
variants e.g. `info`. 
- ~~[ ] API changes follow the [Runbook for Firecracker API …

Backport PR #4242 to support all logger level case variants

---

CHANGELOG.md

Changelog for 4261 and 4242

---

CHANGELOG.md
docs/api_requests/block-io-engine.md
docs/api_requests/block-vhost-user.md
docs/snapshotting/snapshot-support.md
src/vmm/src/devices/virtio/vhost_user_block/device.rs

Add notes in changelog, doc and a log message.
vhost-user-blk feature is in developer preview
---

doc(vhost-user-blk): add notes about developer preview

---

CHANGELOG.md
src/firecracker/src/api_server_adapter.rs
src/firecracker/src/main.rs
src/vmm/src/lib.rs
src/vmm/src/rpc_interface.rs

[1.5] Cleanup confusion arising from mixing of unix exit codes and Rust Result types

---

tests/integration_tests/performance/test_snapshot_ab.py
tools/ab_test.py

Relax snapshot restore test timeout because it was too tight, and add missing parenthesis to output.
---

Fix A/B-Test timeout and output formatting

---

tests/integration_tests/performance/test_vhost_user_metrics.py

Add a test to collect vhost-user metrics from Firecracker.
To monitor any regressions in vhost-user metrics over time.
- ~~[ ] User-facing changes are mentioned in `CHANGELOG.md`.
---
[2]: …

test(metrics): collect Firecracker vhost-user metrics

---

tests/framework/microvm.py
tests/framework/utils_drive.py
tests/integration_tests/functional/test_api.py
tests/integration_tests/functional/test_drive_vhost_user.py
tests/integration_tests/performance/test_block_ab.py
tests/integration_tests/performance/test_vhost_user_metrics.py

This change creates separate classes for Qemu and crosvm backends and moves management of backend processes to the Microvm class.
The following problems are being solved by this change:
- proper cleanup of sockets related to vhost-user-blk
- fixing name conflict for crosvm backend socket
---
[2]: …

test(vhost-user-blk): move backend management to microvm class

---

tests/integration_tests/functional/test_cpu_template_helper.py

Change integration test to pass a microVM configuration without a network interface to the CPU templates helper tool.
CPU template helper tool uses a microVM configuration we pass to it to launch a VM and get it's CPU config. Our integration test that drives that needs to configure the microVM with a network interface so that it can SSH into it and run commands. However, when we pass to helper tool a configuration that includes networking, we run into a race-condition with creating/configuring a TAP device.
--- …

fix(test): do not pass network config to CPU template helper

---

src/vmm/src/devices/virtio/virtio_block/device.rs
src/vmm/src/devices/virtio/virtio_block/io/async_io.rs
src/vmm/src/devices/virtio/virtio_block/io/mod.rs
src/vmm/src/devices/virtio/virtio_block/io/sync_io.rs
tests/integration_tests/functional/test_api.py
tests/integration_tests/functional/test_drive_virtio.py

Changes the implementation along the PATCH code path for `virtio-block` devices so that, for the case of asynchronous engines (IO uring), it reuses the existing `EventFd` for getting completion callback notifications, rather than creating a knew one.
It also modifies the `virtio-block` tests to also test the asynchronous engine. It extends a test that verifies the PATCH operation works to also check that `mount`-ing an asynchronous device works.
The asynchronous engine maintains an event file descriptor which passes to the IO uring interface when creating a new ring. IO uring uses this EventFd to notify us about completion of IO requests.
When we PATCH an async block device, we create a new asynchronous engine, including a new EventFd. However, we still monitor the old EventFd. This …

Fix PATCH operation in virtio-block devices backed by asynchronous engine

---

CHANGELOG.md

Add the fix for the async engine in the "Fixed" section of the CHANGELOG.
Forgot to update the CHANGELOG in the initial PR.
---

doc: add fix for async engine in CHANGELOG

---

src/utils/Cargo.toml

This reverts commit 5d7e75c59436b303994853da1ed57446d98f1865.
5d7e75c59436b303994853da1ed57446d98f1865 introduces a memory usage increase.
---

Revert "fix: Fix tracing optional dependency issue"

---

src/log-instrument/Cargo.toml

Moves `env_logger` from `dependencies` to `dev-dependencies` of `log-instrument`.
Reduces dependencies in release build.
---

build: Move `env_logger` to `dev-dependencies` of `log-instrument`

---

CHANGELOG.md
tests/integration_tests/style/test_repo.py

It is easy to forget to add the brackets when adding a new "Unreleased" version. Add a simple test to validate this.
Also fix a small issue the test caught.
- Add a test to check CHANGELOG.md is valid
- Fix CHANGELOG.md
To ensure CHANGELOG.md is always in a releasable state.
---

test(repo): ensure CHANGELOG.md is valid

---

tools/ab_test.py

This commit disables failing on this configuration to avoid spurious failures until the AMI is updated and the volatility has subsided.
An AMI update in CI introduced high volatility on m6i.metal 5.10 affecting a large number of performance.
---

ci: Disable A/B tests failing on m6i.metal 5.10

---

.buildkite/pipeline_perf.py
tests/integration_tests/performance/test_boottime.py

Run the boottime test as an A/B-test post-PR so that we note changes to this key metrics other than "are we below 150ms?".
...
...
---

test: A/B-ify boottime test

---

Cargo.lock
src/clippy-tracing/tests/integration_tests.rs
src/vmm/Cargo.toml
src/vmm/src/devices/virtio/iovec.rs
src/vmm/src/devices/virtio/net/device.rs
src/vmm/src/devices/virtio/rng/device.rs
src/vmm/src/devices/virtio/vsock/csm/connection.rs
src/vmm/src/devices/virtio/vsock/device.rs
src/vmm/src/devices/virtio/vsock/event_handler.rs
src/vmm/src/devices/virtio/vsock/mod.rs
src/vmm/src/devices/virtio/vsock/packet.rs
src/vmm/src/devices/virtio/vsock/test_utils.rs
src/vmm/src/devices/virtio/vsock/unix/muxer.rs
src/vmm/src/rpc_interface.rs
tests/integration_tests/functional/test_vsock.py

Allow the vsock device to process arbitrarily shaped descriptor chains.
As reported in #4284, with Linux 6.1 a linux guest will start using one virtio descriptor per vsock packet. Up until 6.0, it uses a two-descriptor descriptor chain, with the first descriptor containing the vsock packet header, and the second descriptor the payload (if it exists). 
---
[3]: https://github.com/firecracker-microvm/firecracker/blob/main/CO …

Allow vsock device to process arbitrarily shaped descriptor chains, in anticipation of guest-side Linux 6.1 changes

---

CHANGELOG.md
docs/jailer.md
src/jailer/src/cgroup.rs
src/jailer/src/env.rs
src/jailer/src/main.rs
tests/framework/jailer.py
tests/integration_tests/security/test_jail.py

If we specify `--parent-cgroup` without any `--cgroup` option, the jailer doesn't do anything, though a user specifying it could reasonably expect it to move the process under that cgroup.
We could just error in that situation, and expect something else to launch the jailer process in a cgroup, but we risk breaking anybody that is already using it that way.
Instead, we move the process to the `--parent-cgroup` since it's the most intuitive, although the specified `--parent-cgroup` is not a parent in that case.
Closes: #4287 
...
---
[1]: …

Fix jailer `--parent-cgroup` parameter when no cgroups specified

---

Cargo.lock
docs/getting-started.md
src/api_server/swagger/firecracker.yaml
src/cpu-template-helper/Cargo.toml
src/firecracker/Cargo.toml
src/jailer/Cargo.toml
src/rebase-snap/Cargo.toml
src/seccompiler/Cargo.toml
src/snapshot-editor/Cargo.toml
src/vmm/src/version_map.rs
tools/devtool

We are starting 1.6.0 development.
Bump versions of all crates and make all needed changes
Original PR #4322
Start firecracker-v1.7 development.
---

chore: bump version to 1.7.0-dev

---

docs/getting-started.md

Commit 5adfb16 did not update the kernel version.
Fixes: 5adfb16
Update the guest kernel version used in the getting-started guide
So that the getting-started guide works.
---

doc: fix getting-started guide

---

resources/seccomp/aarch64-unknown-linux-musl.json
resources/seccomp/x86_64-unknown-linux-musl.json

Add new entries for `mmap` and `madvise` in seccomp filters. The actual upgrade of the toolchain will
come in a follow up PR here: #4258. The reason for the separate PRs, is that if we bundle them together
A/B tests will run some tests on `main` with the new toolchain but using the old seccomp filters and cause
tests to fail due to seccomp violations. 
Rust toolchain upgrade to 1.73.0 introduces new `mmap` and `madvise` calls.
---
[2]: https://github.com/firecracker-microvm/firecracker/blob/main/docs/api-change-ru …

Update seccomp filters for rust toolchain upgrade

---

src/vmm/src/vstate/vcpu/aarch64.rs
tools/devctr/Dockerfile
tools/devtool
tools/release.sh

Upgrade Rust toolchain to 1.73.0
Use latest toolchain
---

Upgrade Rust toolchain to 1.73.0

---

src/cpu-template-helper/src/template/verify/mod.rs
src/vmm/src/cpu_config/x86_64/cpuid/mod.rs
src/vmm/src/cpu_config/x86_64/cpuid/normalize.rs
src/vmm/src/devices/virtio/net/tap.rs
src/vmm/src/mmds/mod.rs
src/vmm/src/mmds/token.rs
src/vmm/src/persist.rs
src/vmm/src/vmm_config/machine_config.rs
src/vmm/src/vmm_config/mmds.rs

Fixed issue #4313, 12 comments changed
This commit updates error doc comments with /** */.
It also moves or removes extraneous skip attributes.
modified:   src/cpu-template-helper/src/template/verify/mod.rs
modified:   src/vmm/src/cpu_config/x86_64/cpuid/mod.rs        
modified:   src/vmm/src/cpu_config/x86_64/cpuid/normalize.rs  
modified:   src/vmm/src/devices/virtio/net/tap.rs
modified:   src/vmm/src/mmds/mod.rs
modified:   src/vmm/src/mmds/token.rs
modified:   src/vmm/src/persist.rs
modified:   src/vmm/src/vmm_config/machine_config.rs
modified:   src/vmm/src/vmm_config/mmds.rs
Issue #4313 requested changes to error comment types across the codebase.
---
[1]: …

Replace #[doc] error comments with /// type

---

rust-toolchain.toml

This is needed to prevent A/B-tests across commit ranges that include a toolchain update (and associated code changes to keep Firecracker compiling) from breaking.
A downside of this approach is that it will always install both the x86_64 and aarch64 versions of the musl target (only takes a few seconds) on the fly. This could be fixed by always adding both of them to the docker container
---
[3]: …

chore: Add rust-toolchain.toml file to repository

---

.github/workflows/send_release_notification.yml

Use `html_url` instead of `url` so that the release slack notification contains the url that can be used to navigate to the release page.
The release Slack notification points to an url like https://api.github.com/repos/firecracker-microvm/firecracker/releases/134631702 instead of the release page.
~- [ ] User-facing …

fix: Use the right url to view the release

---

docs/metrics.md
tests/host_tools/fcmetrics.py

Present a list of metrics emitted by Firecracker and to make it easier to understand the metrics, provide links to the definition of each metrics.
Added a misc commit not related to the documentation to fix the validation of metrics.
~- [ ] All added/changed functionality is tested.~
---
[2]: …

doc(metrics): Make metrics related info easily accessible

---

src/vmm/src/builder.rs
src/vmm/src/lib.rs
src/vmm/src/vstate/vcpu/mod.rs

**Remove `RestoreVcpusError`**
Commit 8eb46c9a59e6 ("refactor(vmm): vcpu.init and vcpu.restore updates") removed `VcpuEvent::RestoreState`, `VcpuResponse::RestoreState` and `restore_vcpu_states()`. As `RestoreVcpusError` is an error type for `restore_vcpu_states()`, it is no longer needed. 
**Unify panic messages on failure to send a response from vcpu thread**
All the other `Vcpu`'s methods than `running()` uses "vcpu channel unexpectedly closed" message when it fails to send a response from the vcpu thread.
**Fix a broken table in comment**
The table in `exit()` comment explaining the interaction between vmm and vcpu threads was broken. …

Tiny refactors for vcpu-related code

---

src/vmm/src/persist.rs
src/vmm/src/vstate/vcpu/x86_64.rs
tests/integration_tests/functional/test_snapshot_basic.py

Used `Display` for internal data in errors.
The errors are more descriptive.
---

Display for errors

---

CHANGELOG.md
docs/metrics.md
src/vmm/src/logger/metrics.rs
src/vmm/src/vstate/vcpu/mod.rs
src/vmm/src/vstate/vcpu/x86_64.rs
tests/host_tools/fcmetrics.py
tests/integration_tests/performance/test_network_ab.py
tests/integration_tests/performance/test_vsock_ab.py

- Add a new struct to record aggregate (min/max/sum) of time
difference as a metric.
Use the Aggregate metrics structure to record aggregate of
IO and MMIO vm exits.
- Firecracker till now had a "group_metrics:key_metrics:value" pair and
with new metrics for kvm exits this relation changes to "group_metrics:
key_metrics:sub_key_metrics:value".
Update the flush_fc_metrics_to_cw() to be able to parse this and make
it future proof to support further sub_key_metrics levels.
- latency of kvm exits will improve observability.
~- [ ] If a specific …

Aggregate latency metrics for vm exits handling IO

---

docs/getting-started.md

- fix network setup for guest in getting started guide
- make host interface configurable in doc
- While following the getting started guide, new users might get confused with the host interface to use and might default to `eth0` as mentioned. Giving this as an env, makes users aware that we have to use the host interface that is connected to internet for getting internet access inside the VM.
- Refer to the network-setup guide from getting started, so that the next step to configure network in the guests are available.
---
[1]: …

doc: fix network setup in getting started guide

---

.buildkite/pipeline_perf.py
tools/ab_test.py

This allows comparisons of two test runs that were not orchestrated by the A/B-testing framework, for example if the two runs were done on different instances. Use this if the data you want to compare is from anything other than "two firecracker revisions tested on the same machine inside the same docker image".
...
...
---

Add option to run A/B-test on two arbitrary test-report.json files

---

Cargo.lock
Cargo.toml
src/firecracker/Cargo.toml
src/snapshot/Cargo.toml
src/utils/Cargo.toml
src/vmm/Cargo.toml
src/vmm/src/vstate/vcpu/mod.rs
tests/integration_tests/functional/test_shut_down.py

Update dependencies for various rust-vmm crates which made new releases to adapt to changes in vmm-sys-util crate. 
The vmm-sys-util changes were triggered due to a security vulnerability discovered: https://github.com/rust-vmm/vmm-sys-util/security/advisories/GHSA-875g-mfp6-g7f9, affecting the serde implementation for the FamStructWrapper types.
Firecracker itself is not affected by this vulnerability since we do not consume the serde feature of the FamStructWrapper type, but we will in the future. So, update the dependencies now to prepare for this and also avoid having `cargo audit` complaining to us.
Developer Certificate of Origin and …

Bump rust-vmm dependencies

---

tests/integration_tests/functional/test_shut_down.py

PR #4353 upgraded versions of various rust-vmm crates that got patched for a security vulnerability found in vmm-sys-util (not affecting Firecracker). This included a new version of kvm-bindings which includes bindings from a newer kernel. In this, `struct system_event`, which is the type that KVM passes over to us during a KVM_EXIT_SYSTEM_EVENT exit, changed from being a `u64` to being a `&[u64]`. The change itself, landed in kernel 5.18.
This changed, altered Firecracker logging during shutdown (in some cases), so #4353 PR made the necessary changes to fix the tests that relied on the log entry. The fix boils down to "if we are on 6.1 check for the new type of message". That caused our testing on latest Ubuntu to fail, because now it uses a 6.2 kernel.
Fix the test by correctly checking …

Fix test `test_shut_down::test_reboot` failure in Ubuntu tests with 6.2 kernel

---

src/jailer/src/main.rs
src/vmm/src/cpu_config/templates.rs
src/vmm/src/cpu_config/x86_64/cpuid/amd/normalize.rs
src/vmm/src/cpu_config/x86_64/cpuid/intel/normalize.rs
src/vmm/src/cpu_config/x86_64/cpuid/mod.rs
src/vmm/src/cpu_config/x86_64/cpuid/normalize.rs
src/vmm/src/cpu_config/x86_64/static_cpu_templates/c3.rs
src/vmm/src/cpu_config/x86_64/static_cpu_templates/t2.rs
src/vmm/src/cpu_config/x86_64/static_cpu_templates/t2a.rs
src/vmm/src/cpu_config/x86_64/static_cpu_templates/t2cl.rs
src/vmm/src/cpu_config/x86_64/static_cpu_templates/t2s.rs
src/vmm/src/device_manager/persist.rs
src/vmm/src/devices/virtio/vsock/csm/connection.rs
src/vmm/src/devices/virtio/vsock/unix/muxer.rs
src/vmm/src/dumbo/pdu/bytes.rs
src/vmm/src/dumbo/tcp/connection.rs
src/vmm/src/io_uring/operation/cqe.rs
src/vmm/src/io_uring/operation/sqe.rs
src/vmm/src/logger/logging.rs
src/vmm/src/mmds/data_store.rs
src/vmm/src/vmm_config/mod.rs
src/vmm/src/vstate/vcpu/x86_64.rs
tools/devtool

Change some Rustdoc comments so that they render correctly 
Just to make them more usable when looking at the documentation locally.
---

Rustdoc fixes

---

.buildkite/pipeline_cpu_template.py

The AL2023 Linux 6.1 kernel now has the CPU masking patches we need for snapshot / restore to work.
Move the tests to a platform where they are supported.
So we can run the tests.
---

chore: move aarch64 CPU template tests to al2023

---

Cargo.lock
Cargo.toml
src/firecracker/Cargo.toml
src/snapshot/Cargo.toml
src/utils/Cargo.toml
src/vmm/Cargo.toml
src/vmm/src/vstate/vcpu/mod.rs
tests/integration_tests/functional/test_shut_down.py

fix: bump rust-vmm dependencies
Update dependencies for various rust-vmm crates which made new releases to adapt to changes in vmm-sys-util crate. The vmm-sys-util changes were triggered due to a security vulnerability discovered in vmm-sys-util (Github Security Advisory id: GHSA-875g-mfp6-g7f9), affecting the serde implementation for the FamStructWrapper types.
Firecracker itself is not affected by this vulnerability since we do not consume the serde feature of the FamStructWrapper type, but we will in the future. So, update the dependencies now to prepare for this and also avoid having `cargo audit` complaining to us.
The most notable change here, is that we need to update our fork of kvm-bindings to bring it in-par with the upstream version.
By submitting this pull request, I confirm …

[1.6] backport #4353 to fix cargo audit

---

Cargo.lock
Cargo.toml
src/firecracker/Cargo.toml
src/snapshot/Cargo.toml
src/utils/Cargo.toml
src/vmm/Cargo.toml
src/vmm/src/vstate/vcpu/mod.rs
tests/data/static_cpu_templates/aarch64_remove_ssbs.json
tests/framework/utils_cpu_templates.py
tests/integration_tests/functional/test_cpu_features_aarch64.py
tests/integration_tests/functional/test_shut_down.py

bump rust dependencies by backporting
https://github.com/firecracker-microvm/firecracker/pull/4353 to fix cargo audit warnings.
---

[1.5] Backport firecracker#4353 to fix cargo audit

---

tools/ab_test.py

Reverts the commit that disabled failing for A/B tests on m6i.metal 5.10.
When we can, it is better to alarm on what we can.
---

Revert "ci: Disable A/B tests failing on m6i.metal 5.10"

---

src/jailer/src/resource_limits.rs

This change adds unit test for verifying that the resource limits for file size and the number of file descriptors has been set properly.
Minor change to add a unit test for installing the ResourceLimits for file size and the number of file descriptors.
...
- [N/A] If a specific issue led to this PR, this PR closes the issue.
- [N/A] Any required documentation changes (code and docs) are included in this PR.
- [N/A] API changes follow the [Runbook for Firecracker API changes][2].
- [N/A] User-facing changes are mentioned in `CHANGELOG.md`.
- …

test: Add unit test for installing resource limits

---

src/firecracker/Cargo.toml
src/firecracker/src/api_server/mod.rs
src/firecracker/src/lib.rs

Since #4377, the firecracker crate contains library code that specific tests expect to be able to `use`, however it was only a binary target so far. Add a library target that exposes the library components of the crate that now exists.
---

Fix: Add library target to src/firecracker crate

---

Cargo.lock

Update dependencies to mitigate
https://rustsec.org/advisories/RUSTSEC-2024-0006
No actual impact to Firecracker, as shlex is used during build-time only and this is not exploitable at that point.
Update dependencies
Upgrade the dependency so that the alarm clears.
---

chore(deps): run cargo update to update shlex

---

Cargo.lock

Same as #4394 
Update dependencies to mitigate
https://rustsec.org/advisories/RUSTSEC-2024-0006
No actual impact to Firecracker, as shlex is used during build-time only and this is not exploitable at that point.
Upgrade the dependency so that the alarm clears.
---

[bp v1.6] chore(deps): run cargo update to update shlex

---

Cargo.lock

Same as #4394 
Update dependencies to mitigate
https://rustsec.org/advisories/RUSTSEC-2024-0006
No actual impact to Firecracker, as shlex is used during build-time only and this is not exploitable at that point.
Upgrade the dependency so that the alarm clears.
---

[bp v1.5] chore(deps): run cargo update to update shlex

---

README.md
docs/prod-host-setup.md

Some small markdown formatting fixes and typos
...
---

Fix markdown formatting and typos

---

.buildkite/pipeline_perf.py
tools/ab_test.py

In some instances we see AB tests failing with very small deltas:
A/B-testing shows a change of 1.75μs, or 5.46%, (from 32.08μs to 33.83μs) for metric ping_latency
In Graviton instances the 5% default threshold is too narrow since, and we get false positives like the one above, that are mostly due to noise.
Set the absolute delta threshold for network latency test to 10us, which is chosen arbitrarily but should reduce the number of false positives.
...
...
---
[2]: …

ci(perf/net_latency): increase absolute delta threshold to 10us

---

tools/ab_test.py

Use the right argument `absolute-strength` to run AB tests.
The argument was added in d073c2bb89585df6d9aba1a58e9d20674a7eda77 replacing `relative-strength`.
---

Fix AB tests

---

src/firecracker/examples/uffd/malicious_handler.rs
src/firecracker/examples/uffd/uffd_utils.rs
src/firecracker/examples/uffd/valid_handler.rs
tests/integration_tests/build/test_unittests.py

Update to uffd handler used in tests to handle multiple uffd objects send through the UDS. This upgrade is needed for supporting snapshot restore with vhost-used devices. During restoration process FC will ask vhost-user devices to give it their uffds and then send them to global uffd handler.
---

Uffd protocol update

---

.buildkite/pipeline_cpu_template.py
tests/conftest.py
tests/framework/properties.py
tests/framework/utils_cpu_templates.py
tests/integration_tests/functional/test_api.py
tests/integration_tests/functional/test_cpu_features_aarch64.py
tests/integration_tests/functional/test_cpu_template_helper.py
tests/integration_tests/security/test_nv.py
tests/integration_tests/security/test_sec_audit.py
tests/integration_tests/security/test_vulnerabilities.py

Check that nested virtualization is disabled in all our CPU templates.
Other tests already check for CPU features explicitly, but this test just checks that virtualization is not available to the guest, however the means.
[rev3] 
- Added `fix: test_sec_audit`. The test has failed 3 times in this PR, so I am including it even though it is unrelated.
- Disabled some tests that don't pass. This is OK because the tests are completely disabled at the moment, so at least we enable the ones that pass. We will follow up on the 3 failing ones.
https://buildkite.com/firecracker/firecracker-pr/builds/8665#018d3caa-7488-44ee-a123-ea76ca15f318/55-278
... …

test: add a test to check for nested virtualization

---

.buildkite/pipeline_perf.py

We're observing spurious failures in the perf A/B pipeline. Some of them are gone in retries. To reduce unnecessary manual effort, enables automatic retries and disables manual retries on the pipeline.
---
[1]: …

test: Enable auto retries and disable manual retries on perf A/B test

---

tests/host_tools/fcmetrics.py
tests/integration_tests/performance/test_block_ab.py
tests/integration_tests/performance/test_memory_overhead.py
tests/integration_tests/performance/test_network_ab.py
tests/integration_tests/performance/test_snapshot_ab.py
tests/integration_tests/performance/test_vsock_ab.py

FC metrics were uploaded to CW with the same dimensions as the test to make it easy to map the metrics with the test in CW. However, each test has a huge number of dimensions which when multiplied with the number of FC metrics we upload add upto too many datapoints stored in CW.
This makes CW slow hard to monitor the dashboard and also has a significant increase in billing.
So limit the dimensions to (cpu-host_version-guest_version) so that we can monitor the dashboard properly and reduce the billing. To map the datapoints with the test that emitted them we'll have to use the datapoint timestamp with some CW query.
Developer Certificate of …

chore: Upload FCMetrics with reduced dimensions

---

CHANGELOG.md
src/cpu-template-helper/src/template/dump/aarch64.rs
tests/integration_tests/functional/test_cpu_template_helper.py

When SVE extension is enabled on aarch64 cpus, KVM will return wide registers when queried. Because cpu templates do not support registers wider than 128 bits we need to ignore wide registers when converting cpu configuration into a cpu template.
---

fix(cpu-template-helper): ignore wide registers

---

.buildkite/common.py
.buildkite/pipeline_cpu_template.py
.buildkite/pipeline_cross.py
.buildkite/pipeline_pr.py
.buildkite/pipeline_pr_no_block.py
README.md
docs/snapshotting/snapshot-support.md
tests/data/cpu_template_helper/fingerprint_INTEL_SKYLAKE_4.14host.json
tests/data/cpu_template_helper/fingerprint_INTEL_SKYLAKE_5.10host.json
tests/data/cpu_template_helper/fingerprint_INTEL_SKYLAKE_6.1host.json
tests/integration_tests/functional/test_rng.py
tests/integration_tests/security/test_vulnerabilities.py

- use c5n/m5n to consistently get a Skylake/Cascade Lake
- Use m7g instead of c7g since we use m in other instance types
To consistently test a homogeneous set of instance types
---

Use new instances (c5n/m5n/m7g)

---

Cargo.lock
src/vmm/Cargo.toml
src/vmm/src/devices/virtio/virtio_block/io/async_io.rs
src/vmm/src/io_uring/mod.rs
src/vmm/src/io_uring/operation/cqe.rs
src/vmm/src/io_uring/operation/mod.rs
src/vmm/src/io_uring/operation/sqe.rs
src/vmm/src/io_uring/queue/completion.rs
src/vmm/src/io_uring/queue/submission.rs
src/vmm/tests/io_uring.rs

1. use slab for user_data instead of boxto avoid unsafe code.
2. move generic type from push/pop to IoUring struct
Put generic type on push and pop may cause developers misuse it since current user_data is a pointer, and the type should be the same. Since we always use the same user_data type for an IoUring instance, I move the generic to the IoUring struct.
Signed-off-by: ihciah <ihciah@gmail.com>
---
[3]: …

refactor: use slab for user_data instead of box

---

CHANGELOG.md
src/vmm/src/arch/aarch64/regs.rs
src/vmm/src/arch/aarch64/vcpu.rs
src/vmm/src/vstate/vcpu/aarch64.rs
tests/integration_tests/functional/test_cpu_features.py
tests/integration_tests/functional/test_cpu_features_aarch64.py

Firecracker is incorrectly handling KVM_REG_ARM64_SVE_VLS register during snapshot restoration. KVM_REG_ARM64_SVE_VLS must be set after vcpu is initialized, but before it is finalized.
This PR fixes this issue.
Additionally cpu-feature related tests were updated to test cpu features after snapshot of a vm with cpu template was restored.
---

fix aarch64 not able to restore snaps when SVE enabled

---

docs/getting-started.md
docs/kernel-policy.md
docs/tracing.md

As part of this pull request i updated three files (getting-started.md, kernel-policy.md, and tracing.md) to restore important information about our kernel policy, and fix information or links in the remaining files. 
#3903 regressed the content of getting-started.md and kernel-policy.md, removing information which were useful to explain to Firecracker's customers our kernel policy, and introducing grammar mistakes. This PR aim to restore that content to enable Firecracker customers to be able to clearly identify host and guest kernel supported as well as fix grammar or other minor mistakes
Certificate of Origin and signing off your …

Restore public documentation with key information for Firecracker users

---

tests/host_tools/fcmetrics.py

To reduce the dimensions used to upload FC metrics, we used a new metrics logger as part of this commit 6f16d705e9a849add15ed8125bc913ffc715da46 however,
what was missed was actually flushing the metrics to CW.
Earlier to the said commit, since fc_metrics.py used the same metrics_logger as the performance tests, there was no need to flush because all metrics were flushed together as part of the performance test.
However, since we have a separate metrics_logger now, we need to add this missing step to actually have the metrics uploaded to CloudWatch …

fix: Flush metrics to cloudwatch

---

docs/RELEASE_POLICY.md

Fixes the link in the README.md.
It was previously updated with https://github.com/firecracker-microvm/firecracker/commit/96e7f16f8ee30c240902b3a0a116c4d4cd9728be but this was not the correct link.
PR.
[3]: …

docs: Fix roadmap link in README.md

---

deny.toml
tests/integration_tests/build/test_dependencies.py

`test_licenses` does not warn or fail if we
accidentally add a dependency having GPL2.0 license. `cargo deny` with current deny.toml prints a warning if we a dependency has GPL2.0 license but the test doesn't consider the cargo output.
We update the deny.toml to deny copyleft (includes GPL) and unlicensed crates but there could be other licenses which we don't want to add accidentally so, along with it assert that `cargo deny` output does not have any warning at all.
PR. …

fix: broken license check for dependencies

---

tools/ab_test.py

ci: Disable A/B tests failing on m6i.metal 6.1.
An AMI update in CI introduced high volatility on m6i.metal 6.1 in the
performance tests. This commit disables failing on this configuration
to avoid spurious failures until the AMI is updated and the volatility
has subsided.
PR.
[2]: …

ci: Disable A/B tests failing on m6i.metal 6.1

---

tools/ab_test.py

Previously 5af8df1b8152845c44fb6c53b70ea3f74a40334c only disabled alarming for `test_restore_latency` where the intention was to disable alarming for all m6i 6.1 A/B tests, this fixes this.
Fixes https://github.com/firecracker-microvm/firecracker/pull/4430
PR.
[2]: …

fix: Disable A/B tests alarming on m6.metal 6.1

---

docs/getting-started.md

Adds a disclaimer to highlight resources used in getting-started.md are not production ready.
Discussion highlighted this should be clarified.
PR.
[3]: …

docs: Highlight getting-started.md resources are not production ready

---

docs/jailer.md
tests/framework/microvm.py

Add a test to make sure there is no change in behaviour in killing firecracker_pid.
In our CI we pass `--new-pid-ns` along with `--daemonize` and so firecracker pid can be read from the file `firecracker.pid` present in the jailers root directory.
However, if there is a change in behaviour that leads to this file not having the actual firecracker pid then it could cause a regression.
PR. …

chore: test to check if killing microvm works as expected

---

tests/integration_tests/functional/test_cpu_features.py

Excludes X2APIC MSRs from checking in `test_cpu_wrmsr_restore` 
They cannot be reliabilty controlled and thus cause intermittent test failures.
> The X2APIC MSRs cannot to be loaded and stored on VMX transitions.
> A VMX transition fails if the VMM has specified that the transition
> should access any MSRs in the address range from 0000_0800H to
> 0000_08FFH
From the `Intel® 64 Architecture x2APIC Specification` at https://courses.cs.washington.edu/courses/cse451/24wi/documentation/x2apic.pdf.
PR. …

tests: Exclude  X2APIC MSRs from `test_cpu_wrmsr_restore`

---

tests/README.md

Correct description for pytest capturing.
Description for pytest capturing added in commit ea4a7cca5ac8 ("doc: Include information on how to capture stdout") was not quite accurate.
```
$ tools/devtool -y test -- test_sample.py
...
test_sample.py::test_success PASSED                                                       [ 50%]
test_sample.py::test_fail FAILED                                                          [100%]
=========================================== FAILURES ============================================
___________________________________________ test_fail ___________________________________________
test_sample.py:17: in test_fail
assert False
E   assert False
------------------------------------- Captured stdout call --------------------------------------
hello stdout …
```

doc: Correct description for pytest capturing

---

tests/framework/utils_drive.py

Internally, `sfdisk` calls `sync()` by default that is the main suspect as it may take very long depending on the filesystem activity (see https://www.linuxquestions.org/questions/slackware-14/sync-hangs-in-kernel-but-i-o-is-working-4175468599/#post4996115).
This change adds sfdisk option `--no-tell-kernel` that makes `sfdisk` omit the `sync()` call.
Before:
```
49269 write(1, "The partition table has been alt"..., 38) = 38
49269 fstat(3, {st_mode=S_IFREG|0644, st_size=524288, ...}) = 0
49269 fsync(3)                          = 0
49269 close(3)                          = 0
49269 write(1, "Syncing disks.\n", 15)  = 15
49269 sync()                            = 0
49269 close(1)                          = 0
49269 close(2)                          = 0
49269 exit_group(0)                     = …
```

test(drive): avoid calling sync inside sfdisk

---

CHANGELOG.md
docs/jailer.md
src/jailer/src/env.rs
tests/framework/microvm.py
tests/framework/microvm_helpers.py
tests/framework/utils.py
tests/integration_tests/functional/test_initrd.py
tests/integration_tests/functional/test_kernel_cmdline.py
tests/integration_tests/functional/test_serial_io.py
tests/integration_tests/security/test_jail.py

- Always save Firecracker PID in Jailer root directory regardless of whether `new_pid-ns` flag was set.
- Modify the CI to kill Firecracker using the PID saved in the file in Jailer's root directory.
- Add new tests to try all verify the Microvm.kill behaviour is same for all combinations of daemonize/new_pid_ns flags.
- There was a change in behaviour introduced in Jailer because of which Firecracker pid will always be different from the Jailer PID. So we need to suggested a reliable workaround to fetch Firecracker PID.
PR.
[contribution …

Save Firecracker PID in Jailer's root directory

---

tools/ab_test.py

Reenable A/B test alarming on m6i/6.1.
This reverts commit 5af8df1b8152845c44fb6c53b70ea3f74a40334c
Cherry-picked from https://github.com/firecracker-microvm/firecracker/pull/4431 .
m6i/6.1 test volatility has been mitigated.
PR.
[contribution …

test: reenable A/B test alarming on m6i/6.1

---

docs/getting-started.md

When regenerating artifacts for #4360, the guest kernels got updated to a new patch version.
Fixes #4454
PR.

fix(doc): Update vmlinux artifact link

---

rust-toolchain.toml
tools/devtool

Adds a rust-toolchain.toml file to the 1.6 release branch
Without this, doing A/B-tests across releases is impossible due to older release branches not working when compiled with a newer docker container (and thus a newer rust toolchain). 
---

Backport addition of `rust-toolchain.toml` to 1.6 release branch

---

.buildkite/pipeline_perf.py

Use correct kernel version for m6i/6.1.
We use `linux_6.1-pinned` instead of `linux_6.1+pinned` in our infra.
PR.~~ …

chore(buildkite): use correct kernel version for m6i/6.1

---

tools/devctr/Dockerfile

Install cargo tools with `--locked` option.
Without `--locked` option, installation cargo tools may fail for some reasons. `--locked` option is useful for reproducible installation since it ensures to use the exact same set of dependencies.
https://doc.rust-lang.org/cargo/commands/cargo-install.html#dealing-with-the-lockfile
For example, on v1.5 and v1.6, the installation failed due to an older rustc version.
```
error: failed to compile `cargo-audit v0.20.0`, intermediate artifacts can be found at `/tmp/cargo-installORO8R6`
--
  |  
  | Caused by:
  | package `clap_derive v4.5.0` cannot be built because it requires rustc 1.74 or newer, while the currently active rustc version is 1.70.0
  | Try re-running cargo install with `--locked`
  | error: failed to compile `cargo-deny v0.14.11`, …
```

tests: Install tools with `--locked` option

---

tools/devctr/Dockerfile

Backport 8bb883111ff608dc2ca1a08d5e4eb2ddbd5c1c8b to v1.5.
To make nightly PR test pass on v1.5
PR.~~
[contribution quality standards](https://github.com/firecracker-microvm/firecracker/blob/main/CONTRIBUTING.md#contributi …

Backport fix to v1.5

---

tests/integration_tests/security/test_vulnerabilities.py
tools/devctr/Dockerfile

Backport the following commits to v1.6:
- a8239112d9de0cbc4291833c8f83792084de1747
- 8bb883111ff608dc2ca1a08d5e4eb2ddbd5c1c8b
To make the nightly PR test pass on v1.6 branch.
PR.~~ …

Backport fixes to v1.6

---

rust-toolchain.toml
src/firecracker/src/api_server/mod.rs
src/firecracker/src/api_server/request/mod.rs
src/jailer/src/cgroup.rs
src/vmm/src/devices/virtio/block/virtio/mod.rs
src/vmm/src/devices/virtio/net/gen/mod.rs
src/vmm/src/devices/virtio/net/mod.rs
src/vmm/src/vmm_config/drive.rs
src/vmm/tests/io_uring.rs
tools/devctr/Dockerfile
tools/devtool

Some dependencies have recently adopted a MSRV of 1.74.0, which is higher than our current toolchain version (1.73.0). Update to the newest toolchain currently available, to unblock https://github.com/firecracker-microvm/firecracker/pull/4445
PR.
[2]: …

Update Rust Toolchain to 1.76.0

---

.cargo/config
Cargo.toml
src/clippy-tracing/Cargo.toml
src/cpu-template-helper/Cargo.toml
src/firecracker/Cargo.toml
src/jailer/Cargo.toml
src/log-instrument-macros/Cargo.toml
src/log-instrument/Cargo.toml
src/rebase-snap/Cargo.toml
src/seccompiler/Cargo.toml
src/snapshot-editor/Cargo.toml
src/utils/Cargo.toml
src/vmm/Cargo.toml

Moves lint configuration from `.cargo/config` to `Cargo.toml`.
...
---

build: Lints in `.toml` files

---

CHANGELOG.md
docs/jailer.md
src/firecracker/src/main.rs
src/jailer/src/env.rs
src/jailer/src/main.rs
src/vmm/src/logger/metrics.rs

Deprecate the `--start-time-cpu-us` parameter.
It is always 0 so it does not provide any useful information.
---

chore(docs): deprecate --start-time-cpu-us parameter

---

tests/framework/microvm.py
tests/framework/utils.py
tests/framework/utils_drive.py
tests/framework/utils_iperf.py
tests/host_tools/cpu_load.py
tests/integration_tests/build/test_dependencies.py
tests/integration_tests/performance/test_block_ab.py
tests/integration_tests/performance/test_network_ab.py
tests/integration_tests/performance/test_vsock_ab.py
tools/ab_test.py

Minor clean up of network and cpu utilization testing code.
Now cpu utilization is tracked for all threads.
PR.

[tests] Network and cpu utilization improvements

---

.buildkite/pipeline_perf.py

When running A/B-Tests, the pipeline generated by pipeline_perf.py does not care about pytest markers, it will run all tests specified and do the A/B-comparision. However, when running the pipeline in metrics collection mode, it passes `-m nonci` to pytest, which causes it to filter out tests that do not have the `nonci` marker. Some of our A/B-Tests (such as memory overhead) indeed do not have this marker, leading to confusing errors (where everything works in A/B-mode, but if just collecting metrics pytest fails with "no tests collected"). This commit makes the behavior consistent, but also triggering non-nonci tests in metrics collection mode.
...
...
the terms of the Apache 2.0 license. For more information …

fix: do not limit pipeline_perf.py to nonci tests in metrics mode

---

CHANGELOG.md
Cargo.lock
tests/framework/utils.py
tests/integration_tests/functional/test_mmds.py

- Check the return code of command run on guests.
- Update Cargo.lock to use the latest micro-http.
- Add an integration test for an empty MMDS path.
When querying a MMDS path that has an empty content, the response didn't
contain 'Content-Length' field, resulting in the client waiting for the
connection closed by the server or timeout. To fix this issue,
micro-http made a change to have the field when the response status code
is not 1XX or 204.
- ~~[ ] Any required …

Update micro-http for empty MMDS path handling

---

Cargo.lock
docs/getting-started.md
src/cpu-template-helper/Cargo.toml
src/firecracker/Cargo.toml
src/firecracker/swagger/firecracker.yaml
src/jailer/Cargo.toml
src/rebase-snap/Cargo.toml
src/seccompiler/Cargo.toml
src/snapshot-editor/Cargo.toml
tools/devtool

bump version to 1.8.0-dev
...
...
PR.

chore: bump version to 1.8.0-dev

---

src/jailer/src/env.rs

Deprecating --startup-time-cpu-us accidentally involved us to double count some time spent in the jailer. This commit reverts that behavior.
A/B-Test to compare to commit before --startup-time-cpu-us deprecation:
```bash
./tools/devtool test --ab -- run b546bc566244695d0c709a318c30d483fb86ed2c HEAD --test integration_tests/performance/test_process_startup_time.py
...
Doing A/B-test for dimensions frozenset({('rootfs', 'ubuntu-22.04.squashfs'), ('performance_test', 'test_startup_time_new_pid_ns'), ('host_kernel', 'linux-6.5'), ('cpu_model', '11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz'), ('guest_kernel', 'linux-5.10'), ('vcpus', '2'), ('instance', 'NA'), ('guest_memory', '1024.0MB')}) and property startup_time
Doing A/B-test for dimensions frozenset({('rootfs', 'ubuntu-22.04.squashfs'), …
```

fix: subtract pre-`run()` execution time from startup time again

---

CHANGELOG.md
docs/jailer.md
src/firecracker/src/main.rs
src/jailer/src/env.rs
src/jailer/src/main.rs
src/vmm/src/logger/metrics.rs

This reverts commit 21f0dea22aa1bb38daf32520b1196a9ff72b5815.
We decided not to include this in 1.7, as we would like some more time to (a) ensure the changes in this PR do not have unintended side effects, and (b) if we can come up with a coherent long-term plan for the various startup-time parameters.l
PR.
[1]: …

Revert "chore(docs): deprecate --start-time-cpu-us parameter"

---

tests/framework/microvm.py

Add a property in microvm class for printing console data. If console is disabled this will print an empty string.
I found it useful, when debugging some guest kernel changes. Essentially, if we call that method before launching a microVM we can later print it's console output in the same way we can print Firecracker logs.
PR.
[1]: …

Add microvm helper for enabling console data

---

docs/snapshotting/network-for-clones.md

docs network for clones iptables DNAT command
There is a problem with the command
PR.

doc: network for clones iptables dnat command error

---

.buildkite/pipeline_cross.py
docs/snapshotting/snapshot-support.md

Also test 6.1 -> 5.10
Add more tests since they work and we want to validate this functionality forwards and backwards.
Gain more confidence on the cross-kernel snapshot-restore.
PR.
[3]: …

ci: add aarch64 to cross-kernel tests

---

docs/prod-host-setup.md

This recommends disabling SMT and breaks out KSM into its own subsection.
We had previously removed this as part of focusing on Linux & vendor documentation that would be more holistic and up to date. However it is clear that disabling SMT is a good practice in general we should continue to emphasize that.
PR.
- ~~[ ] All added/changed …

docs: Add back guidance to disable SMT

---

CHANGELOG.md
src/vmm/src/devices/virtio/block/virtio/device.rs
src/vmm/src/devices/virtio/block/virtio/metrics.rs
src/vmm/src/devices/virtio/block/virtio/request.rs
src/vmm/src/devices/virtio/net/device.rs
src/vmm/src/devices/virtio/net/metrics.rs
src/vmm/src/devices/virtio/queue.rs
src/vmm/src/logger/mod.rs
tests/host_tools/fcmetrics.py

This adds the following accumulated metrics:
- block IO: read and write backend latencies (`read_agg`, `write_agg`)
- block IO: length of the queue backlog (`remaining_reqs_count`)
- net: tap write backend latencies (`tap_agg`)
- net: length of the Tx queue backlog (`tx_remaining_reqs_count`)
The latency metrics show how long the VMM thread spends waiting for the requests being processed by the block/net backend. The queue backlog metrics show how many requests are still waiting to be processed by the VMM thread. They are updated during processing of every request, so dividing it by the total number of requests would show the average queue length per request processing.
We would like to have more visibility on how block and network backends are saturated.
By submitting this pull request, …

feat(metrics): add IO queue len and backend latency metrics

---

Cargo.lock
src/utils/Cargo.toml
src/vmm/Cargo.toml

Update linux-loader to 0.11.0 to de-duplicate our vm-memory dependency.
...
...
PR.

chore: update linux-loader to 0.11.0

---

CHANGELOG.md
src/vmm/src/devices/virtio/block/virtio/device.rs
src/vmm/src/devices/virtio/block/virtio/metrics.rs
src/vmm/src/devices/virtio/block/virtio/request.rs
src/vmm/src/devices/virtio/net/device.rs
src/vmm/src/devices/virtio/net/metrics.rs
src/vmm/src/devices/virtio/queue.rs
src/vmm/src/logger/mod.rs
tests/host_tools/fcmetrics.py

Backporting extra IO metrics (https://github.com/firecracker-microvm/firecracker/pull/4486) from main.
We would like for them to appear in prod as soon as possible.
PR. …

[1.7] backport IO metrics from main

---

CHANGELOG.md
docs/api_requests/block-vhost-user.md
src/vmm/src/builder.rs
tests/integration_tests/functional/test_api.py
tests/integration_tests/performance/test_huge_pages.py
tests/integration_tests/security/test_jail.py

Only back guest memory with a memfd if a vhost-user-blk device is configured in the VM, otherwise fall back to anonymous private memory.
This is recovering performance demonstrated before commit 027a9929d62c77fa580eaac4792a9acc1bd3ae1c had been merged.
Page faults are more expensive for shared memory mapping (like memfd).
PR.~~
- ~~[ ] API changes follow the [Runbook for Firecracker API …

fix(vmm): only use memfd if no vhost-user-blk devices configured

---

CHANGELOG.md
DEPRECATED.md
docs/jailer.md
src/firecracker/src/main.rs
src/jailer/src/env.rs
src/jailer/src/main.rs
src/vmm/src/logger/metrics.rs

Deprecates the `--start-time-cpu-us` and `--start-time-us` CLI arguments and adds a `DEPRECATIONS.md` file.
printing the deprecation message caused an observable change in behavior, so the best we can do is "deprecation via changelog".
PR.
[2]: …

Re-deprecate `--start-time-[cpu-]us` flags 

---

CHANGELOG.md
docs/api_requests/block-vhost-user.md
src/vmm/src/builder.rs
tests/integration_tests/functional/test_api.py
tests/integration_tests/performance/test_huge_pages.py
tests/integration_tests/security/test_jail.py

Backport https://github.com/firecracker-microvm/firecracker/pull/4498/
To avoid page fault latency regression.
- ~~[ ] The description of changes is clear and encompassing.~~
PR.~~ …

[1.7] fix(vmm): only use memfd if no vhost-user-blk devices configured

---

.buildkite/pipeline_pr.py
tests/conftest.py
tests/integration_tests/functional/conftest.py

Make the style step faster to complete.
Before: 1m48s
After: 1m22s
Low priority. This test is not in the long pole of the build. 
While it is 25% faster test, it is only interesting if/when we we make the style step run before the full build.
PR.
[2]: …

[CI] Make the style checks step quicker to run

---

.buildkite/common.py
.buildkite/pipeline_pr.py
.buildkite/pipeline_pr_no_block.py

Use either $BUILDKITE_PULL_REQUEST_BASE_BRANCH if available
instead of main to get list of changed files.
Comparing changed files with main leads to running unnecessary tests like buid_devctr even when there is no Dockerfile change in the release branch.
PR.
[2]: …

fix: use the right base branch to detect changed files

---

.buildkite/common.py
.buildkite/pipeline_pr.py
.buildkite/pipeline_pr_no_block.py

- In non PR context, return empty list for changed files.
- In PR context, use $BUILDKITE_PULL_REQUEST_BASE_BRANCH if available
or else "main" as the base branch to check for list of files
changed.
- For custom buildkite jobs or nightly tests the concept of changed
files is not valid.
- When PR's are raised on release branches, comparing changed files
against main leads to running unnecessary tests like buid_devctr
even when there is no Dockerfile change in the release branch.
PR. …

fix: logic to detect changed files 

---

.buildkite/common.py

- In non PR context, return empty list for changed files.
- For custom buildkite jobs or nightly tests the concept of changed
files is not valid.
PR.
[3]: …

fix: logic to detect changed files

---

.buildkite/common.py
.buildkite/pipeline_pr.py
.buildkite/pipeline_pr_no_block.py

- In non PR context, return empty list for changed files.
- In PR context, use $BUILDKITE_PULL_REQUEST_BASE_BRANCH if available or else "main" as the base branch to check for list of files changed.
- For custom buildkite jobs or nightly tests the concept of changed files is not valid.
- When PR's are raised on release branches, comparing changed files against main leads to running unnecessary tests like buid_devctr even when there is no Dockerfile change in the release branch.
PR. …

Backport #4507

---

.buildkite/pipeline_perf.py
.buildkite/pipeline_pr.py
src/vmm/src/devices/virtio/balloon/device.rs
tests/framework/ab_test.py
tests/framework/defs.py
tests/host_tools/cargo_build.py
tests/integration_tests/functional/test_api.py
tools/ab_test.py
tools/devtool
tools/release.sh

Move the build step out of the test
The Firecracker build is done as part of test setup in one of the fixtures.
- The build log is hidden. It may be interesting to have it inlined in the build logs to see how long it takes and in case it fails.
- The Firecracker build is growing over time, and seems it is starting to fail in some CI builds.
- the first tests that compile Firecracker are penalized, as the Firecracker compilation is taken agains their 300s timeout quota
PR. …

CI: move Firecracker build out of test

---

tools/devctr/Dockerfile

Remove the pin of kani to 0.45.0.
We introduced this pin in 2f01981e6bd2cd1de15d81223b99deb3dc4c2dd6 due to https://github.com/model-checking/kani/issues/3035. Kani fixed the issue in 0.48.0 (verifier by installing kani 0.48.0 locally and executing the gcd proof), so we can remove the pin and pick up a new kani version the next time we rebuild the docker container.
cc @feliperodri 
PR. …

fix: unpin kani-verifier version in Dockerfile

---

.buildkite/pipeline_cross.py
tools/devtool

The commit df112e3 missed a few places where we depend on firecracker build.
Fixes: df112e39ccd558c51494b0d0e4ac8b288f6d140d
PR.

fix(ci): build Firecracker when we need to

---

docs/RELEASE_POLICY.md

Add 1.7 to release status table in RELEASE_POLICY.md
I forgot about it last week. Note that 1.5.0 is _not_ pushed out of support by 1.7 since it has not been 6 months since its initial release.
PR.
[3]: …

chore: Add 1.7 to release status table in RELEASE_POLICY.md

---

tests/framework/artifacts.py
tools/release.sh

Two issues:
1. There are some new errors:
FileExistsError: [Errno 17] File exists:
(from /firecracker/tests/integration_tests/functional/conftest.py)
https://buildkite.com/firecracker/firecracker-pr/builds/9536#018e65dd-d001-4c41-afc0-6a4ef97d2790/58-586
We removed some locks when simplifying the build. This function was depending on get_binary to serialize accesses, but it was always vulnerable to race conditions to begin with.
2. The binaries used for the testrun are not stripped.
Fixes: df112e39ccd558c51494b0d0e4ac8b288f6d140d
...
...
PR. …

Fixes related to moving the build out of the testrun

---

tests/framework/ab_test.py

During PR functional tests, we also run a build for the "B" branch. If the tests are running in parallel with xdist, there is a chance we try to build in parallel.
Add a lock to prevent that race condition.
Fixes: df112e39ccd558c51494b0d0e4ac8b288f6d140d
...
To fix https://buildkite.com/firecracker/firecracker-pr/builds/9578#018e8029-0278-4f09-9acc-c2283d8afd18/57-1236
PR. …

fix(tests): lock while building in AB mode

---

CHANGELOG.md
src/vmm/src/devices/virtio/net/device.rs
src/vmm/src/devices/virtio/net/test_utils.rs

Introduce a check that the size of a frame in the TX queue is not bigger than the one the device can handle.
We do not handle malformed packets that the driver might send to us. Also, we avoid big allocations when copying from guest memory to Firecracker memory when handling MMDS frames.
PR.
[2]: …

Fail early in case of too big a frame in the TX path

---

src/vmm/src/vstate/vcpu/mod.rs

Skipped context switches in the presence of run_emulation and VcpuEvent::Resume if kvm_immediate_exit is set
- Forced  kvm_immediate_exit to 0 in the presence of VcpuEvent::Resume, we are resuming the VM, we don't want to kick the vm out of the cpu during this process
- Skipped the context switches in the case of `run_emulation` if `kvm_immediate_exit is set
...
---
[3]: …

skipped unnecessary kvm_immediate_exits

---

tests/host_tools/fcmetrics.py

Update the Firecracker metrics schema to cover breaking change in
LatencyAggregateMetrics.
Use the 'additionalProperties' flag to catch new metrics which are not
covered by jsonschema validate and add required missing metrics to the schema.
LatencyAggregateMetrics added nested dictionaries in Firecracker's
json-formatted-metrics-object and validate_fc_metrics() failed to cover
breaking change in these metrics.
validate_fc_metrics() reported block_rootfs and vcpu metrics missing
from jsonschema validation after the additionalProperties flag was added. …

Update schema to validate breaking change in metrics

---

src/vmm/src/lib.rs
src/vmm/src/persist.rs
src/vmm/src/vstate/memory.rs
tests/integration_tests/functional/test_dirty_pages_in_full_snapshot.py
tests/integration_tests/functional/test_snapshot_basic.py

A continuation of the pr here https://github.com/firecracker-microvm/firecracker/pull/4385
The changes are:
- making sure we reset the firecracker internal bitmap when taking a full snapshot
- handling the error which could occur when trying to reset KVM's dirty log
- The full snapshot path doesn’t call `Vmm:get_dirty_bitmap` thus doesn’t call
`KVM_GET_DIRTY_LOG` which doesn’t reset dirty pages.
Closes #4543.
PR.
[contribution quality standards](https://github.com/firecracker-microvm/firecracker/blob/main/CONTRIBUTING.md#contribution-quality-stan …

Reset dirty bitmap on Full Snapshot

---

tests/framework/artifacts.py

Snapshot versioning changes only made it into 1.7.0, so the TODO should say "remove check once all versions _including_ 1.6.0" go out of support
Update the comment to reflect this.
PR.
[3]: …

chore: Update TODO in artifacts.py

---

tests/integration_tests/performance/test_snapshot_ab.py

Add an SSH command after starting the microVM and before taking a snapshot in snapshot latency A/B test. This fixes the errors we saw in A/B tests after we merged VMGenID support.
Since we added VMGenID support we need to wait that the guest kernel boots before taking a snapshot. That is because, if we send the VMGenID notification (upon snapshot resume) very early in the boot process, before the kernel had time to 
setup the interrupt handler for the device, the guest might crash.
PR. …

Wait for VM to boot in A/B snapshot test

---

tests/framework/microvm.py

Add a delay before opening the VM serial output file to avoid a race condition.
It is possible that by the time we open the screen output file, guest Linux has not yet started booting, so we may fail to open the file.
- ~~[ ] Any required documentation changes (code and docs) are included in this~~
PR.
- ~~[ ] New `TODO`s link to an …

test(cmdline): add delay for serial output file to appear

---

tests/integration_tests/functional/test_balloon.py

Insert a 1 second delay after the inflation request to increase the chance of memory allocation completion by the time of the stats check.
It looks like there is a race condition leading to intermittent failures. The test does the following:
- request pages from the driver
- change the polling interval to trigger stats update
- read stats and check that available memory has updated
Processing of the inflation request may take time due to memory allocation happening in the guest.
- ~~[ ] If a specific issue led to this PR, this PR closes the …

test(balloon): add delay in stats update test

---

.buildkite/common.py

We are running into io_uring test failures after 5.10 kernel update on 2024-04-19. The issue is under investigation, but it prevents us from merging PRs and it makes multiple pipelines fail. Until solving the issue, pin 5.10 kernel AMIs to older ones and set them default.
PR.~~
- ~~[ ] User-facing changes are mentioned in …

chore: Pin 5.10 kernel AMIs

---

tests/framework/microvm.py
tests/framework/utils.py
tests/host_tools/network.py
tests/integration_tests/functional/test_api.py
tests/integration_tests/functional/test_balloon.py
tests/integration_tests/functional/test_concurrency.py
tests/integration_tests/functional/test_dirty_pages_in_full_snapshot.py
tests/integration_tests/functional/test_drive_vhost_user.py
tests/integration_tests/functional/test_drive_virtio.py
tests/integration_tests/functional/test_pause_resume.py
tests/integration_tests/functional/test_serial_io.py
tests/integration_tests/functional/test_snapshot_basic.py
tests/integration_tests/functional/test_snapshot_editor.py
tests/integration_tests/functional/test_uffd.py
tests/integration_tests/functional/test_vsock.py
tests/integration_tests/performance/test_boottime.py
tests/integration_tests/performance/test_huge_pages.py
tests/integration_tests/performance/test_memory_overhead.py
tests/integration_tests/performance/test_snapshot_ab.py
tests/integration_tests/security/test_jail.py
tests/integration_tests/security/test_vulnerabilities.py

- Enable debug print of `find` and `lsblk` command.
- Change the log level of `ssh` command from quiet to error.
- Print debug information when guest is not up.
- Increase the waiting time for microVM to boot up.
We run into multiple intermittent issues where commands exit with status code 255 without any useful info in stderr on microVMs restored from snapshots. As per man page, the failing commands don't list 255 in the possible status codes while `ssh` does, so `ssh` is mostly likely to be the culprit. However, currently we're not sure whether the commands themselves failed or something happened before entering the commands. To make it debuggable in the next occurrence, enable debug print for some commands and change the log level of `ssh` command from quiet and error. 
`find` command …

test: Print debug information on test failure

---

tests/data/cpu_template_helper/fingerprint_AMD_MILAN_4.14host.json
tests/data/cpu_template_helper/fingerprint_AMD_MILAN_5.10host.json
tests/data/cpu_template_helper/fingerprint_AMD_MILAN_6.1host.json
tests/data/cpu_template_helper/fingerprint_ARM_NEOVERSE_N1_4.14host.json
tests/data/cpu_template_helper/fingerprint_ARM_NEOVERSE_N1_5.10host.json
tests/data/cpu_template_helper/fingerprint_ARM_NEOVERSE_N1_6.1host.json
tests/data/cpu_template_helper/fingerprint_ARM_NEOVERSE_V1_4.14host.json
tests/data/cpu_template_helper/fingerprint_ARM_NEOVERSE_V1_5.10host.json
tests/data/cpu_template_helper/fingerprint_ARM_NEOVERSE_V1_6.1host.json
tests/data/cpu_template_helper/fingerprint_INTEL_CASCADELAKE_4.14host.json
tests/data/cpu_template_helper/fingerprint_INTEL_CASCADELAKE_5.10host.json
tests/data/cpu_template_helper/fingerprint_INTEL_CASCADELAKE_6.1host.json
tests/data/cpu_template_helper/fingerprint_INTEL_ICELAKE_4.14host.json
tests/data/cpu_template_helper/fingerprint_INTEL_ICELAKE_5.10host.json
tests/data/cpu_template_helper/fingerprint_INTEL_ICELAKE_6.1host.json
tests/data/cpu_template_helper/fingerprint_INTEL_SKYLAKE_4.14host.json
tests/data/cpu_template_helper/fingerprint_INTEL_SKYLAKE_5.10host.json
tests/data/cpu_template_helper/fingerprint_INTEL_SKYLAKE_6.1host.json

- Update fingerprints
On m6i.metal + kernel 6.1, the following changes were detected:
- CPUID.(EAX=7,ECX=0):EDX[bit 0]: the number of subleaves
- CPUID.(EAX=7,ECX=2):EDX[bit 0]: support of IA32_SPEC_CTRL[bit 0 (PSFD)]
No changes are detected on IA32_SPEC_CTRL MSR. It is up to guests to set the bit or not inside.
Kernel commit to advertize it to userspace: https://github.com/torvalds/linux/commit/eefe5e6682099445f77f2d97d4c525f9ac9d9b07
- ~~[ ] Any required documentation …

chore: Update fingerprints

---

.buildkite/pipeline_cross.py

- Use pinned AMIs for cross snapshot restore target.
We pinned 5.10 kernel AMIs to an old one to mitigate io_uring test failures temporarily. We just changed `DEFAULT_PLATFORMS` but ARM cross snapshot restore test uses a custom set of platforms. 
Fixes: 238f55c18adb ("chore: Pin 5.10 kernel AMIs")
PR.~~
- ~~[ ] User-facing …

chore: Use pinned AMIs for cross snapshot restore target

---

Cargo.toml
src/cpu-template-helper/Cargo.toml
src/firecracker/Cargo.toml
src/snapshot-editor/Cargo.toml
src/utils/Cargo.toml
src/vmm/Cargo.toml

Formally include all crates, both binary and library, in the cargo workspace, so that dependabot can discover the Cargo.toml files of the library crates as well.
Also document the reason why we have a default-members entry, and why it excludes the jailer.
PR.
[2]: …

Update `members` field in Cargo.toml

---

tests/integration_tests/functional/test_api.py
tests/integration_tests/functional/test_balloon.py
tests/integration_tests/functional/test_cpu_features.py
tests/integration_tests/functional/test_cpu_features_aarch64.py
tests/integration_tests/functional/test_mmds.py
tests/integration_tests/functional/test_rng.py
tests/integration_tests/functional/test_snapshot_basic.py
tests/integration_tests/functional/test_vsock.py
tests/integration_tests/performance/test_huge_pages.py
tests/integration_tests/security/test_vulnerabilities.py

- Insert `wait_for_up()` before running guest commands.
`wait_for_up()` shows debugging information if the guest is not up and running.
PR.~~ …

wait_for_up() in tests running guest commands

---

src/vmm/src/vstate/vcpu/aarch64.rs

Do not power off vcpus during snapshot restore.
Vcpus should be in power off state during kernel boot, but during snapshot restore we do not need to power them off even thought kvm does not complain.
PR.
[3]: …

fix: power off vcpus only during startup

---

tools/test-popular-containers/build_rootfs.sh

Add support for testing Ubuntu 23.10 and 24.04
Add Ubuntu 23.10 and 24.04 to the popular Docker integration tests
To make sure Firecracker runs on the latest Ubuntu LTS release.
PR.
[3]: …

test-popular-containers: add ubuntu 23.10 and 24.04

---

src/vmm/src/builder.rs
src/vmm/src/vstate/vcpu/aarch64.rs
src/vmm/src/vstate/vcpu/mod.rs

Change kvi to be stored all the time
Previously we were storing kvi for vcpus only when cpu template was used. This was done to save vcpu configuration for snapshot restoration step, because when vcpus are restored, we don't have access to the cpu template to apply changes again. But when cpu template was not used we did not store already created kvi and were getting new one from KVM. This is a redundant work which we can avoid if we store kvi all the time. Also storing kvi unconditionally simplifies the code significantly.
PR.
[contribution …

Store kvi all the time

---

.buildkite/common.py
.buildkite/pipeline_cross.py

Unpin kernel 5.10 AMI.
Fix #4586.
Now that a new Amazon Linux 2 kernel 5.10 AMI arrived and I confirmed it solves the io_uring test failures (issue #4586)
- [Y] If a specific issue led to this PR, this PR closes the issue.
- [Y] The description of changes is clear and encompassing.
- [N/A] Any required documentation changes (code and docs) are included in this
PR.
- [N/A] API changes follow the [Runbook for Firecracker API changes][2].
- [N/A] User-facing changes are mentioned in `CHANGELOG.md`.
- [Y] All added/changed functionality is tested.
- …

Unpin kernel 5.10 AMI

---

tests/README.md

Include which error one would see if one forgets to set the `AWS_EMF_NAMESPACE` and `AWS_EMF_ENVIRONMENT` variables to `local`. Note a common pitfall of trying to set environment variables through buildkite.
Happened a few times, and I'm not always here
PR.
[2]: …

doc: Troubleshooting for `ab_test.py analyze`

---

tests/framework/microvm.py
tests/host_tools/fcmetrics.py
tests/host_tools/memory.py

If a test fails, the FCmetricsMonitor keeps running in some tests. After we kill the microvm and remove the resources, the monitor complains it cannot find the metrics file.
This is tricky to fix simply since we don't have a handle to the monitor either at fixture teardown or in the Microvm class.
Add a hook in the Microvm class to register monitors, so we can stop all of them before killing the microvm.
Also adapt existing monitors to fix this pattern.
...
...
PR. …

test: stop all monitors before killing microvm

---

tests/conftest.py

The current test failure metrics have high cardinality because they include the test name. This makes it hard to visualize them in CloudWatch since we run into aggregation limits.
It would be nice to have one global failure rate, and some views per-kernel and per-CPU type.
This adds 10 new metrics = 6 per-CPU + 3 per-host kernel + 1 global metric so it is not too costly.
...
...
PR. …

test: add a global dimension to test failure metric

---

src/vmm/src/vstate/vcpu/x86_64.rs

Because we are using u32 integer math when checking the TSC, it could happen that the value can overflow if the TSC value is very high, around 18GHz. While there is no processor on the market near that frequency, it's worth fixing this in case the snapshot gets corrupted somehow.
...
To make the snapshot implementation more robust
PR. …

fix(snapshot): prevent an integer overflow when calculating TSC scaling

---

tests/integration_tests/functional/test_rng.py

For the RNG tests, set the log level to INFO instead of DEBUG. The virtio-rng device does output a lot of DEBUG information, and that can add overhead and make some of our perf tests fail.
...
PR.
[3]: …

Decrease logging in test_rng tests

---

tests/integration_tests/security/test_vulnerabilities.py

Tests succeed now.
...
...
PR.

fix(test): re-enable tests

---

tests/framework/microvm.py
tests/integration_tests/security/test_custom_seccomp.py

Ignore metric lines that cannot be parsed.
Improve the stability of tests.
PR.

fix(test): avoid parsing broken metrics lines

---

src/vmm/src/vstate/memory.rs
tests/framework/microvm.py
tests/integration_tests/functional/test_snapshot_not_losing_dirty_pages.py

Store kvm dirty bitmap inside firecrackers internal bitmap so no data is lost incase of an error
As we load the KVM bitmap store it inside the internal firecracker bitmap. This is done incase of a failure while creating the snapshot, as the data is stored until it's completed successfully.
Making snapshot transactional
Ticket here: https://github.com/firecracker-microvm/firecracker/issues/4545
PR. …

Make diff snapshots transactional

---

src/vmm/src/devices/virtio/queue.rs
src/vmm/src/dumbo/tcp/endpoint.rs
src/vmm/src/logger/metrics.rs

Resolve 3 TODOs in the codebase
Rollup seemingly abandoned PRs that we still think have value to be merged.
PR.

Rollup of stale PRs

---

tools/devtool

Use host network for docker. This prevents issues when network access inside the container is different from the host access.
Docker default network bridge might be restricted by networking rules, which can result in builds inside docker fail to retrieve dependencies from the internet.
PR.
[2]: …

feat: use host network for docker

---

tools/devtool

Reverts firecracker-microvm/firecracker#4614 because this configuration change appeared to be unnecessary.
Additionally it introduce unwanted changes to the way CI was working.

Revert "feat: use host network for docker"

---

src/cpu-template-helper/src/fingerprint/compare.rs
src/cpu-template-helper/src/main.rs

- Don't show diff twice.
- Handle a new line correctly in error message.
Before
```
$ build/cargo_target/x86_64-unknown-linux-musl/debug/cpu-template-helper fingerprint compare --prev tests/data/cpu_template_helpe
r/fingerprint_INTEL_SKYLAKE_5.10host.json --curr tests/data/cpu_template_helper/fingerprint_INTEL_SKYLAKE_6.1host.json 
Difference detected between source and target: \n{
"name": "kernel_version",
"prev": "5.10.215-203.850.amzn2.x86_64",
"curr": "6.1.84-99.169.amzn2023.x86_64"
}
Error: FingerprintCompare(DiffDetected("{\n  \"name\": \"kernel_version\",\n  \"prev\": \"5.10.215-203.850.amzn2.x86_64\",\n  \"curr\": \"6.1.84-99.169.amzn2023.x86_64\"\n}"))
```
After
```
$ build/cargo_target/x86_64-unknown-linux-musl/debug/cpu-template-helper fingerprint compare --prev …
```

fix(cpu-template-helper): Fix error message display

---

Cargo.lock
docs/getting-started.md
resources/rebuild.sh
src/cpu-template-helper/Cargo.toml
src/firecracker/Cargo.toml
src/firecracker/swagger/firecracker.yaml
src/jailer/Cargo.toml
src/rebase-snap/Cargo.toml
src/seccompiler/Cargo.toml
src/snapshot-editor/Cargo.toml
tools/devtool

Update versions in `Cargo.toml` files and `Cargo.lock`. Update links in `devtool` and `docs/getting-started.md` to S3 CI artifacts to point to v1.9 bucket and also unpin guest kernel 5.10 from `5.10.210` version. Latest version (`5.10.217`) seems to be working
We started the release process for v1.8. We will continue development under the 1.9-dev tag.
PR. …

Bump version to 1.9-dev

---

src/seccompiler/src/seccompiler_bin.rs
src/vmm/src/devices/virtio/block/virtio/metrics.rs
src/vmm/src/devices/virtio/net/metrics.rs
src/vmm/src/devices/virtio/vhost_user_metrics.rs
src/vmm/src/devices/virtio/vsock/unix/muxer_killq.rs
src/vmm/src/dumbo/tcp/connection.rs
src/vmm/src/vmm_config/net.rs
src/vmm/src/vstate/vm.rs

Eliminate some unneeded use of unwrap from Firecracker.
While looking into the feasibility of #593, I stumbled across a few unwraps that were very simple to fix. 
PR.
[3]: …

Eliminate a handful of unwraps from the codebase

---

.github/CODEOWNERS
CONTRIBUTING.md
MAINTAINERS.md

- Clarify guidance on using `.unwrap()`
- Correct statement about how many approvals are needed
- Remove former team members from CODEOWNERS/MAINTAINERS.md
#808 
PR.
[3]: …

Update contribution guidelines

---

src/vmm/src/devices/virtio/iovec.rs
src/vmm/src/devices/virtio/net/device.rs
src/vmm/src/devices/virtio/net/tap.rs
src/vmm/src/devices/virtio/rng/device.rs
src/vmm/src/devices/virtio/vsock/mod.rs
src/vmm/src/devices/virtio/vsock/packet.rs

- Change IoVecBuffer[Mut] len to u32 (was usize)
- Add u32 overflow check (errors out rather than panics)
Closes https://github.com/firecracker-microvm/firecracker/issues/4548
Protect against overflows and use a consistent data type for virtio files.
PR.
[2]: …

Change IoVecBuffer[Mut] len to u32

---

tools/test.sh

Sometimes test fail because of running out of space. In that case it would be helpful to dump some information on disk usage.
Add debug information when a test run fails
...
PR.
[3]: …

ci: output disk usage if tests fail

---

tools/test.sh

The rest of the script was not executed because we run the script under `-e`. Disable errors so we can capture the exit code and print the information.
Fixes: a46b60e9ba774e831484315f20b2e437cc6c150f
Bugfix
To make the change be effective.
PR.
[2]: …

fix(ci): ignore errors so we can capture the exit status

---

Cargo.lock

This version contains a performance improvement during deserialization that would negate the performance regression observed when updating to kvm-bindings 0.8.0 in f68a2ef306807fdd298d85133d19eb595731d152.
Fixes: f68a2ef306807fdd298d85133d19eb595731d152
...
...
PR.
[2]: …

[1.8] chore: update kvm-bindings to 0.8.2

---

tests/pytest.ini

Currently our A/B testing builds Firecracker for each test and each environment while running tests. As the Firecracker build time increases, some tests timeout the current duration (300s). 
To mitigate this issue temporarily, sets it to 600s. It should be set it back to the original value after fixing the issue in PR #4624.
PR.~~
- ~~[ ] API changes follow the [Runbook for Firecracker API …

chore(ci): double pytest timeout duration temporarily

---

tests/conftest.py
tests/framework/microvm.py
tests/integration_tests/functional/test_snapshot_basic.py
tests/integration_tests/performance/test_snapshot_ab.py

Delete intermediary snapshot while when tests create snapshots in loops.
Tests such as `test_snapshot_ab.py` or `test_5_snapshots` create snapshot files in a loop. This interacts badly with some debugging infrastructure added in #4590: If a test fails, then all files from all microVM chroots from that test are copied to `test_results`, and then uploaded as run artifacts. This means that if one of the 30 microVM restorations in `test_snapshot_ab.py` fails, we copy all, potentially 30, snapshot files to `test_results`. If these are large (which they can be: the test goes up to 12GB microVMs), this can cause the buildkite agent to run out of disk space.
the terms of the Apache 2.0 license. For more information on …

Delete intermediary snapshots created by tests, to avoid out-of-disk-space errors during artifact generation

---

src/firecracker/src/api_server/parsed_request.rs

Previously, the method argument was first being converted to raw bytes, and then into utf8. However, a to_str() method exists that converts directly to utf8.
Remove instances in `parsed_request.rs` where HTTP method was being converted into raw bytes first and then UTF-8 and replace with `to_str()` method which converts directly into UTF-8
Removes an unnecessary source of error that could occur when converting from raw to UTF-8.
PR.
[contribution quality standards](https://github.com/firecracker-microvm/firecracker/blob/main/CONTRIBUTING.md#contr …

Remove unncessary encoding conversion

---

tests/integration_tests/functional/test_rng.py

Modify `test_rng.py::test_rng_bw_rate_limiter` to not check if the device achieves the performance defined by the devices rate limiter limit.
Currently, our test for virtio-rng rate limiter tests if the performance obtained by the device is within 10% of the rate limiter limit. This does not only test whether the rate limiter works (achieved bandwidth > 10% of limit), but also if the device performs at that same limit.
This test is supposed to be a functional test, not a performance one. In fact, it does not run in isolation. Moreover, we have not thoroughly profiled the performance we can achieve from the device, so we cannot be sure that the limits in the functional test correspond to the capabilities of the device. If we want, we should do that as part of a performance test.
By …

fix(test_rng): do not test for virtio-rng performance

---

.buildkite/common.py
.buildkite/pipeline_cpu_template.py
.buildkite/pipeline_cross.py
.buildkite/pipeline_perf.py
.buildkite/pipeline_pr.py
.buildkite/pipeline_pr_no_block.py
tests/framework/ab_test.py
tests/host_tools/cargo_build.py
tests/integration_tests/functional/test_concurrency.py
tools/ab_test.py
tools/devtool

The main change is to share the build. To do that without complicating each pipeline script, we first encapsulate all the complexity of parsing options and all the logic that each script duplicates into a BKPipeline class, and then we can make the build sharing change in a single place without having to touch each script.
The rest of the changes are small issues found while working on this PR.
- We use less resources by doing it this way. For example for an A/B performance run we built Firecracker 252 times. After this change, we only build it 4 times. This may ease the contention at the beginning of a build, as agents are not trying to access the network at the same time.
- Test runs may use less instance time overall. For PR for example it would be 4min * 108 = 432 minutes. Wall time …

CI: build Firecracker once and share it with all the jobs

---

pre-commit

Use git-secrets to ensure that no secrets are commited to the repository. Fails if it detects a secret and logs a warning if git-secrets is not present. Closes #386 
Adds a couple lines to the `pre-commit` file that checks if git-secrets exists. If it exists,  use it to scan and if it doesn't, just logs that scanning could not be performed.
...
To provide an extra layer of protection from committing secrets to the repository.
...
PR.~~
- ~~[ ] API changes follow the …

Add git-secrets to pre-commit

---

.buildkite/common.py
.buildkite/pipeline_cross.py
.buildkite/pipeline_perf.py

The automatic retry when a BK agent disconnects we want in all pipelines.
Automatically retry when a BK agent is lost, in all pipelines.
Before this was only done in the perf pipeline, but we want this behavior in all pipelines, so adding it as a default.
PR.
[2]: …

ci: move automatic retry to BKPipeline class

---

.buildkite/common.py
.buildkite/pipeline_perf.py
tools/ab_test.py

Fix perf tests when running in AB mode 
After the build sharing changes, this mode was working because we were still building Firecracker (unintentionally). After we removed that capability in 467c90d5ab69e191262781a46987c961a0b80cc1 this mode started failing.
PR.
[2]: …

Fix Perf tests AB mode

---

src/firecracker/src/api_server/parsed_request.rs
src/firecracker/src/api_server/request/hotplug.rs
src/firecracker/src/api_server/request/mod.rs
src/firecracker/swagger/firecracker.yaml
src/vmm/src/builder.rs
src/vmm/src/lib.rs
src/vmm/src/logger/metrics.rs
src/vmm/src/rpc_interface.rs
src/vmm/src/vmm_config/hotplug.rs
src/vmm/src/vmm_config/mod.rs
tests/host_tools/fcmetrics.py

* Created new API endpoint `hotplug` used to request resources on demand (currently only vCPU implemented)
* Currently, when a valid request is made to `hotplug`, the specified number of vCPU threads are added directly to the guest VMM
* For now, in order to allow hotplugging Firecracker must be launched with `--no-seccomp` option
* Unit tests added to test functionality of both endpoint and adding of vCPUs
This is the first step in implementing resource hotplugging via ACPI.
PR. …

Add vCPUs to VMM via new endpoint 

---

src/vmm/src/builder.rs
src/vmm/src/cpu_config/x86_64/custom_cpu_template.rs
src/vmm/src/vstate/vcpu/x86_64.rs

Move logic to create single msr chunk into separate function. Also use iterators for msr indexes to remove some unneeded allocations.
Minor simplification and removal of unneeded allocations.
PR.
[3]: …

refactor: simplify get_msr_chunks

---

.buildkite/common.py
resources/overlay/usr/local/bin/init.c

In our boottime tests, we use a custom `init` script to signal to
Firecracker (via MMIO) that booting has finished. This script then
`execve`s into `/sbin/init` (e.g. systemd) to continue the normal boot
process. However, when execve-ing, we forgot to NULL-terminate the
`envp` array, resulting a buffer over-run that caused systemd to crash
on m6a.metal instances.
Thus, NULL-terminate the array to fix the buffer-overrun. For this
change to take effect, we need to rebuild CI artifacts.
PR. …

fix(test): Stop guest from panicking in boottime tests on AMD

---

tests/integration_tests/functional/test_snapshot_basic.py

The `wait_for_up()` sends a dummy SSH command with a timeout of 10s, with the intention of blocking the integration test until a VM is responsive after booting. However, post-snapshot restore it runs into issue https://github.com/firecracker-microvm/firecracker/issues/4099, where on AMD inside the guest, sshd gets stuck inside a nanosleep syscall for longer than intended (and thus longer than the 10s timeout).
Alternatively, we could pass `lapic=notscdeadline` in the kernel commandline arguments, but we do not have an easy way to _append_ to the default kernel command line from integration tests, and I'd like to avoid duplicating our default across a bunch of places.
...
... …

fix(test): remove `wait_for_up` from `test_vmgenid`

---

src/vmm/src/device_manager/mmio.rs
src/vmm/src/devices/virtio/balloon/device.rs
src/vmm/src/devices/virtio/block/device.rs
src/vmm/src/devices/virtio/block/vhost_user/device.rs
src/vmm/src/devices/virtio/block/virtio/device.rs
src/vmm/src/devices/virtio/device.rs
src/vmm/src/devices/virtio/mmio.rs
src/vmm/src/devices/virtio/mod.rs
src/vmm/src/devices/virtio/net/device.rs
src/vmm/src/devices/virtio/rng/device.rs
src/vmm/src/devices/virtio/vsock/device.rs

When the guest driver sets a virtio devices status to `DRIVER_OK`, we
proceed with calling `VirtioDevice::activate`. However, our MMIO
transport layer assumes that this activation cannot go wrong, and calls
`.expect(...)` on the result. For most devices, this is fine, as the
activate method doesn't do much besides writing to an event_fd (and I
can't think of a scenario in which this could go wrong). However, our
vhost-user-blk device has some non-trivial logic inside of its
`activate` method, which includes communication with the
vhost-user-backend via a unix socket. If this unix socket gets closed
early, this causes `activate` to return an error, and thus consequently
a panic in the MMIO code.
The virtio spec, in Section 2.2, has the following to say [[1]]:
> The device SHOULD set …

fix: do not panic if virtio device activation return Err(...)

---

Cargo.lock
resources/seccomp/aarch64-unknown-linux-musl.json
src/vmm/Cargo.toml

New version of aws-lc-sys needs faccessat
syscall on aarch64, so add it to the seccomp filter.
Doing this separately from usual dependabot PRs.
PR.
[3]: …

chore: update aws-lc-sys

---

CHANGELOG.md
src/cpu-template-helper/src/template/dump/x86_64.rs
src/vmm/src/cpu_config/x86_64/cpuid/common.rs
src/vmm/src/cpu_config/x86_64/mod.rs
src/vmm/src/vstate/vcpu/mod.rs
src/vmm/src/vstate/vcpu/x86_64.rs

[1.8] Backport #4666

---

.buildkite/pipeline_perf.py

Pin m6i/5.10 and m6i/6.1 to last known stable AMIs.
We are seeing performance volatility on newest AMIs.
-~~ [ ] If a specific issue led to this PR, this PR closes the issue.~~
- ~~[ ] Any required documentation changes (code and docs) are included in this~~
PR.
[contribution quality standards](https://github.com/firecracker-microvm/firecracker/blob/main/CONTRIBUTING.md#c …

chore: Pin m6i/5.10 and m6i/6.1 AMIs

---

docs/getting-started.md

Fix the whole "we forgot to update the getting started guide after regenerating CI artifacts" thing once and for all by using S3's list-objects API for dynamically looking up the name of the 5.10 guest kernel. We commit the cardinal sin of parsing XML using regex, but this should be fine here as we're only matching for a single, complete tag. This breaks if the list objects operation ever returns more than 1000 objects (as then it starts paginating), but that would meant over 1000 5.10 guest kernels in our CI artiafacts, and I doubt that will ever happen.
Closes #4675 …

doc: Update guest kernel patch version in getting-started.md

---

pre-commit

Replaced a `sed -z` command in the pre-commit hook that seemed to only work on linux with a `paste`
command that seems to work on macos and linux.
While running the previous version of the precommit I got the following error:
```
Found configured hook: pre-commit
Running command: sh pre-commit
Fetching advisory database from `https://github.com/RustSec/advisory-db.git`
Updating crates.io index
Scanning Cargo.lock for vulnerabilities (184 crate dependencies)
src/jailer/src/env.rs
sed: illegal option -- z
usage: sed script [-Ealnru] [-i extension] [file ...]
sed [-Ealnu] [-i extension] [-e script] ... [-f script_file] ... [file ...]
Configured hook command failed
pre-commit hook rejected
```
Tested a couple different things and the `paste` command seemed to work both on macos (M1) and on …

Made pre-commit work in sillicon macos and linux

---

resources/seccomp/aarch64-unknown-linux-musl.json
resources/seccomp/x86_64-unknown-linux-musl.json
src/vmm/src/devices/virtio/mod.rs
src/vmm/src/devices/virtio/net/device.rs
src/vmm/src/devices/virtio/net/mod.rs

Changes the Firecracker implementation of VirtIO device to only setup the TAP offload features that correspond to the ones that the guest driver acknowledged.
This is a clean-up and re-spin of #4386.
Closes: #4659 
Currently, we assume that the guest virtio-net driver acknowledges all the offload features we offer to it and then subsequently set the corresponding TAP features.
This might be the case for the Linux guest kernel drivers we are currently using, but it is not necessarily the case. FreeBSD for example, might try to NACK some of them in some cases: https://github.com/firecracker-microvm/firecracker/issues/3905.
Certificate …

fix(net): Apply only supported TAP offloading features

---

src/utils/src/lib.rs
src/vmm/src/devices/virtio/net/device.rs
src/vmm/src/devices/virtio/net/test_utils.rs
src/vmm/src/devices/virtio/queue.rs

Minor tweaks to the virtio queue methods:
- more explicit offset calculations
- more descriptive names and methods
These changes were part of #4658, but are quite independent of it, so moved to separate PR.
PR. …

Virtio tweaks

---

docs/network-setup.md

Use default MAC for our rootfs in the `network-setup.md`
Should fix: #4582, #4557
PR.

fix: use default MAC in the network-setup.md

---

src/cpu-template-helper/src/fingerprint/dump.rs

Follow up of PR #4689.
run_shell_command() is no longer used and related error variant and tests can be dropped.
```
$ tools/devtool build --release
[Firecracker release.sh 2024-07-18T15:27:38+00:00] Building version=v1.9.0-dev, profile=release, target=x86_64-unknown-linux-musl, Rust toolchain=1.76.0...
Compiling jailer v1.9.0-dev (/firecracker/src/jailer)
Compiling vmm v0.1.0 (/firecracker/src/vmm)
Compiling firecracker v1.9.0-dev (/firecracker/src/firecracker)
Compiling cpu-template-helper v1.9.0-dev (/firecracker/src/cpu-template-helper)
Compiling snapshot-editor v1.9.0-dev (/firecracker/src/snapshot-editor)
warning: variant `ShellCommand` is never constructed
--> src/cpu-template-helper/src/fingerprint/dump.rs:20:5
|
12 | pub enum FingerprintDumpError {
|          -------------------- …
```

refactor: Drop run_shell_command()

---

README.md

Update links to Kata Containers and Flintlock projects.
(Resubmitting Again to fix the Commit message cause amend wouldn't let me go far enough back again)
Swap the link from pointing at outdated v1 kata container docs that are achieved
Swap the name and the linker for weaver because it was archived and deprecated and the deprecated statement points to Flintlock
Updating the examples to active projects to make it easier for people looking for them. (reason im making this pr is i went and clicked on them and found both archived) so people don't have to dig into the readmes and the links to get to the active projects
Certificate of …

doc: update README.md with up-to-date links to projects

---

tools/devctr/ctr_gitconfig
tools/devtool

Add `/firecracker/.git` as a safe directory in dev containers git configuration
Otherwise "git clone /firecracker ..." fails in the container. This happens due to a patched version of git [1] addressing a CVE [2] that could lead to remote code execution when cloning specially crafted local repositories.
[1] https://ubuntu.com/security/notices/USN-6793-1
[2] https://msrc.microsoft.com/update-guide/vulnerability/CVE-2024-32004
PR.
[contribution quality standards](https://github.com/firecracker-microvm/firecracker/blob/main/CONTRIBUTING.md#contribut …

Fix A/B testing

---

.buildkite/common.py
.buildkite/pipeline_pr_no_block.py

Change no block pipelines to not use the build step
No block pipeline runs rust benchmarks (among other things) which need to run `cargo bench` to build those benchmarks. Problem is that when we use pre-build artifacts some build paths don't match leading to errors like this: https://buildkite.com/firecracker/firecracker-pr-optional/builds/8136#0190dfc2-bdd9-42fc-9471-91b816f43d3f
Since we anyway rebuild these artifacts just do it in the test step and drop the build step.
PR. …

Fix optional PR tests

---

.buildkite/pipeline_perf.py

Unpin m6i 6.1 ami
The volatility is gone
PR.

Unpin m6i 6 1

---

tools/devctr/Dockerfile
tools/devtool

Update the docker container to not hardcode `/firecracker` as the root of all paths. Instead, use the `--workdir` option. Also use `--volume` instead of symlinks inside of the dockerfile to point the cargo registry toward `firecracker/build/cargo_{git_registry,registry}`. This is needed because we want to use this docker container to run fuzzers which we keep in a different (private) repository. 
PR. …

Generify docker container to not hardcode `/firecracker` paths

---

docs/getting-started.md

Replaces hardcoded occurrences of `tap0` with `$TAP_DEV` variable introduced earlier in `getting-started.md`
Currently, instructions break if users change value of `TAP_DEV` e.g. to `tap1`
PR.
[3]: …

Fixes minor variable naming issue in getting-started.md

---

tests/framework/microvm.py
tests/host_tools/fcmetrics.py
tests/integration_tests/performance/test_block_ab.py
tests/integration_tests/performance/test_memory_overhead.py
tests/integration_tests/performance/test_network_ab.py
tests/integration_tests/performance/test_snapshot_ab.py
tests/integration_tests/performance/test_vsock_ab.py

When flushing firecracker metrics to cloudwatch, explicitly assert that metrics containing the keypharses "err", "fail" or "panic" are all 0. Also move `FcMetricsMonitor` initialization into `Microvm`
Detect potentially silent failure modes
PR.
[2]: …

test: cause failure if FC emits an error metric

---

src/vmm/src/devices/virtio/iovec.rs
src/vmm/src/devices/virtio/net/device.rs
src/vmm/src/devices/virtio/vsock/packet.rs

Removes the allocation of the `IoVecBuffer` in the virtio net device during tx by reusing the same instance for each message.
To do this we have to implement Send on the type for it to work, I have tried to cover the unsafe sections the best I can.
Reduce the number of allocation
Ticket here: https://github.com/firecracker-microvm/firecracker/issues/4549
PR. …

Reuse the IoVecBuffer on TX

---

tests/host_tools/fcmetrics.py

Fix the assertion to print a more useful message when an error metric is non-zero. Also, make sure that we upload metrics to CloudWatch even when there is a non-zero error metric.
Right now the assertion message is not very legible which makes it difficult to debug. Also, if an error happens we don't upload the metrics to cloudwatch.
PR.
_____________________________________________________________________ …

metrics: dump the error metrics during failure

---

src/vmm/src/devices/virtio/queue.rs

Remove redundant memory check for `DescriptorChain::new`.
Since we already validated the queue layout and desc index, there's no need to check it again.
PR.
[3]: …

virtio: skip redundant memory check

---

src/jailer/src/cgroup.rs
src/jailer/src/env.rs
tests/framework/microvm.py
tests/integration_tests/security/test_jail.py

The previous Cgroup implementation used a separate object per every cgroup property. This lead to additional calls to create_dir_all and writes to cgroup.procs, especially in cgroupsv2 where there is only one hierarchy.
This change prevents the duplication by refactoring the code into:
- CgroupConfiguration: this holds multiple cgroup properties in multiple cgroup controllers and hierarchies
- Cgroup: this holds the configuration for a hierarchy and holds multiple properties
- CgroupProperty: a file to value mapping of the cgroup properties to be written.
The CgroupBuilder is changed to a CgroupConfigurationBuilder so that the setup of the Cgroup is abstracted away from the environment.
Additionally, in the CgroupV2 the available controllers read from cgroup.controllers are cached to …

refactor cgroup to allow multiple properties per controller

---

tests/integration_tests/functional/test_balloon.py

Add a `wait_for_up()` call in test_deflate_on_oom.
`test_deflate_on_oom started` failing recently while calling `make_guest_dirty_memory()` and instantiating an SSH object. It is likely because the guest is not able to set up the SSH server by the time we try to connect for the first time.
PR.~~
- ~~[ ] User-facing changes …

test(ballon): add wait_for_up in test_deflate_on_oom

---

tests/conftest.py

In some situations it would be useful to have the dmesg output to troubleshoot.
- Add host dmesg output
- Add guest dmesg screen output if available
To help troubleshooting
PR.
[3]: …

tests: capture host dmesg on test failure

---

src/vmm/src/devices/virtio/iovec.rs
src/vmm/src/devices/virtio/queue.rs
src/vmm/src/devices/virtio/rng/device.rs
src/vmm/src/devices/virtio/vsock/packet.rs

- Update calculations in the queue to use `std::mem::size_of` instead of hard-coded values
- Add ability to reload `IoVecBuffMut` the same way as it can be done with non `Mut` variant
These were part of #4658, but because these changes seem generic, move into separate PR.
PR.
[2]: …

Queue tweaks

---

CHANGELOG.md
docs/kernel-policy.md

Add an entry in the CHANGELOG about deprecation of 4.14 guest kernel and officially supporting 6.1. Also, update the kernel policy documentation to mention the changes.
PR.
[3]: …

Declare support for 6.1 guest kernels and deprecation for 4.14.

---

src/snapshot-editor/src/edit_memory.rs

The `rebase` command had a copy pasted description from `remove-regs`.
Fix command description
Command description may be confusing otherwise
PR.
[3]: https://github.com/firecracker-microvm/firecracker/blob/main/ …

snapshot-editor: fix rebase command description

---

tests/framework/microvm.py

In commit 059aa62216f8f1e22b2b7d7cbc1f15931c2dfe23 we started gathering console_data if a test failed. However console_data errors if we were not using screen in the first place.
Fixes: 059aa62216f8f1e22b2b7d7cbc1f15931c2dfe23
...
To avoid an error during teardown if a test failed.
PR.
[2]: …

tests: fix console_data if not under screen

---

src/vmm/src/devices/virtio/block/vhost_user/mod.rs
src/vmm/src/devices/virtio/block/vhost_user/persist.rs
src/vmm/src/dumbo/tcp/handler.rs
src/vmm/src/mmds/persist.rs

Correctly handle various error conditions that can only occur if a malformed snapshot file is attempted to be loaded.
Graceful exits are nicer than panics
PR.
[3]: …

Improve error handling for malformed snapshot files

---

tests/integration_tests/test_kani.py

Increase the timeout for kani test from 30 to 40 minutes.
Some changes that we did in the VirtIO queue in this PR: https://github.com/firecracker-microvm/firecracker/pull/4726 pushed kani proofs close to the time limit we set in the CI.
PR.
[2]: …

Increase timeout of kani tests

---

tests/integration_tests/test_kani.py

Backport fix for kani test that increases the timeout from 30 to 40 minutes.
Some changes that we did in the VirtIO queue in this PR: https://github.com/firecracker-microvm/firecracker/pull/4726 pushed kani proofs close to the time limit we set in the CI.
PR.
[2]: …

Backport timeout fix for kani into firecracker-1.9

---

tests/conftest.py
tests/framework/artifacts.py
tests/integration_tests/performance/test_block_ab.py
tests/integration_tests/performance/test_boottime.py
tests/integration_tests/performance/test_memory_overhead.py
tests/integration_tests/performance/test_network_ab.py
tests/integration_tests/performance/test_snapshot_ab.py
tests/integration_tests/performance/test_vhost_user_metrics.py
tests/integration_tests/performance/test_vsock_ab.py

Using guests without ACPI support is deprecated, but we need to
functionally verify it until we can remove support in Firecracker 2.0.
However, we definitely do not need to performance test this
configuration. So don't, and speed up our perf tests by 25%.
PR.
[2]: …

test: do not perf test with no-acpi kernels

---

CHANGELOG.md

Adds an entry in CHANGELOG.md about the fix
https://github.com/firecracker-microvm/firecracker/pull/4680. The fix ensures that we set to the TAP device only features that were successfully negotiated with the guest driver.
PR.
[2]: https://github.com/firecracker-microvm/firecracker/blob/main/docs/api-cha …

fix(changelog): add entry about virtio-net feature negotiation fix

---

CHANGELOG.md

Adds an entry in CHANGELOG.md about the fix
https://github.com/firecracker-microvm/firecracker/pull/4680. The fix ensures that we set to the TAP device only features that were successfully negotiated with the guest driver.
(cherry picked from commit 730e6458d7dcc6a67ea262fd8fd4087f8c939270)
PR.
[2]: …

Backport CHANGELOG entry about virtio-net feature negotiation fix

---

CREDITS.md
README.md

Update CREDITS.md and update README.md to mention guest kernel 6.1 as tested.
PR.

Doc and CREDITS fixes ahead of 1.9 release

---

.mailmap
CREDITS.md

Add entries to `.mailmap` to make re-generating CREDITS.md easier.
- Deduplicate some entries.
- Correct some existing addresses of maintainers.
...
...
PR.
[3]: …

chore: deduplicate emails in CREDITS.md

---

tools/devtool

Make sure the `build` directory exists before building with proper permissions.
Unless we call `ensure_build_dir`, the build directory will be created inside the Docker container as root and subsequent builds will fail.
PR.
[2]: https://github.com/firecracker-microvm/firecracker/blob/main/docs/api-change …

fix(make_release): create the build directory as non-root

---

tools/devtool

Fix `./tools/devtool make_release`  by making sure exists before building with proper permissions.
(cherry picked from commit 63749ec1af6a7d18cb3256be1579c5acfb174ff8)
Unless we call `ensure_build_dir`, the build directory will be created inside the Docker container as root and subsequent builds will fail.
PR.
[1]: …

Backport make_release fix for creating the build directory as non-root to v1.9

---

docs/getting-started.md
tools/devtool

Switch devtool to fetch kernels from v1.10 CI bucket. Also update links in our Getting Started guides to point to the new bucket.
Use the new CI bucket
PR.
[3]: …

Update CI bucket to point to v1.10

---

src/vmm/src/devices/virtio/iovec.rs

The `verify_read_from_iovec` and especially `verify_write_from_iovec` harnesses started taking upwards of 30 minutes for verification. Optimize them down to take less than 1 minute without losing generality.
Achieve this by applying something akin to loop-unrolling: Instead of having a `let nr_desc: usize = kani::any_where(...)` that limits `nr_desc` to be at most a fixed constant, use a for loop to explicitly list all possibilities up to said constant.
PR.
[contribution quality standards](https://github.com/firecracker-microvm/firecracker/blob/m …

kani: improve performance

---

CHANGELOG.md
src/utils/src/arg_parser.rs

Jailer: added the `-h` flag as a shorthand for `--help`.
This is a common convention - thought it would be useful.
PR.
---
Tried …

Jailer: added the `-h` flag as a shorthand for `--help`

---

.buildkite/common.py
.buildkite/pipeline_pr.py

The kani test does not use the pre-built firecracker binaries, as kani does static analysis, and does not execute binaries. Thus, do not have the kani test block on compilation finishing.
PR.
[3]: …

ci: start kani test without waiting for build

---

.buildkite/pipeline_pr.py

Kani has no use for pre-built binaries, and I'm fairly certain it cannot
even reuse the build artifacts due to using a different toolchain. So
pass `--no-build` to `devtool test` when running the kani test to safe a
few more minutes there.
PR.
[2]: …

test: do not build firecracker before running kani

---

tests/integration_tests/performance/test_benchmarks.py

The optional criterion benchmark A/B-test had swapped the "A" and "B" data, causing regressions to show up as improvements and improvements to show up as regressions.
See also [[1]] for a documentation of the criterion commandline arguments.
[1]: https://bheisler.github.io/criterion.rs/book/user_guide/command_line_options.html#baselines
Fixes: b6c0d43949843369be8913b2de0817d631721e52
PR. …

fix: do criterion benchmark comparision the correct way around

---

tests/integration_tests/performance/test_boottime.py

The search-and-replace for excluding the no-acpi kernels from the performance tests was a bit overzealous and also renames the `guest_kernel` metric.
Fixes: 2360fcce44365d6bc01453acefc22dff3152b323
...
...
PR. …

fix(test): fix guest_kernel metric in boottime tests

---

CHANGELOG.md
src/vmm/src/device_manager/mmio.rs
tests/integration_tests/functional/test_vsock.py

Kick vsock when resuming VM. This ensures that if VM is restored from a snapshot, guest gets a notification to read a queue with `TRANSPORT_RESET_EVENT` inside. This will trigger guest to close all vsock connections. This is expected behavior as vsock devices does not support bringing connections over the snapshot boundary.
Fixes #4736
PR.
___________________________________________________________________ …

Kick vsock during VM resume

---

tests/integration_tests/functional/test_vsock.py
tests/integration_tests/performance/test_huge_pages.py
tools/devtool

Various small commits that I wrote as parts of various discarded branches, but which have merit on their own. Please see individual commit messages.
PR.
[3]: …

Small testing QoL improvements

---

resources/guest_configs/patches/0003-enable-ftrace.patch
resources/guest_configs/patches/0004-disable-CONFIG_ARM64_ERRATUM_3194386-for-aarch64.patch
tests/integration_tests/performance/test_boottime.py
tests/integration_tests/performance/test_vhost_user_metrics.py

Enabled `ftrace` feature in guest kernels. This will help us to debug problems in the future.
Additionally we need to disable `CONFIG_ARM64_ERRATUM_3194386` in aarch64 guest configs as this option hides `ssbs` feature from the guest user space and this breaks our integration test that verifies these features. The option itself was added in recent  kernel versions and is intended for `Cortex-X4` and `Neoverse-V3` cpus, and we are not using those. Link: https://lore.kernel.org/stable/20240809095745.3476191-6-mark.rutland@arm.com/
Improve future debug-ability. 
```bash
root@ubuntu-fc-uvm:~# trace-cmd record -p function_graph -l 'hrtimer_*' -l 'lapic_*' -l 'wrmsr*'
...
root@ubuntu-fc-uvm:~# trace-cmd report
cpus=2
<idle>-0     [001]   185.577231: funcgraph_entry:        1.040 us   | …
```

Enable ftrace in guest kernels

---

.buildkite/pipeline_pr.py
tests/framework/microvm.py
tests/integration_tests/functional/test_pause_resume.py
tests/integration_tests/functional/test_vsock.py

- drop unneeded explicit "depends_on: null" from buildkite steps
- fix a typo
- rename a method
accumulates various nits from PR reviews that I was gonna "do the next time I touch the code"
PR.
[3]: …

Tiny Fixups

---

.buildkite/common.py
.buildkite/pipeline_cpu_template.py

19e90517fa9f12b740ba41393dbd6a8352c270f7 assumed the `agents` is a dict, which was true in all cases except in one pipeline.
Fixes: 19e90517fa9f12b740ba41393dbd6a8352c270f7
...
...
PR.
[3]: …

buildkite: fix CPU template pipeline issues

---

src/vmm/src/device_manager/persist.rs
tests/integration_tests/functional/test_vsock.py

This is a fix for a fix introduced in #4796
The issue was in vsock device hanging after snapshot restoration due to the guest not being notified about the termination packet. But there was bug in the fix, maily we saved the vsock state before the notification was sent, thus discarding all modifications made to sent the notification.
The reason original fix worked, is because we were only testing with 1 iteration of snap/restore. This way even though we lost synchronization with the guest in the event queue state, it worked fine once. But doing more iterations causes vsock to hang as before.
This PR fixes the issue by storing vsock state after the notification is sent and modifies the vsock test to run multiple iterations of snap/restore.
Fixes: #4811
By submitting this pull request, I …

fix(vsock): save state after sending a notification

---

docs/getting-started.md

Add quotes to prevent escaping and makes the code `shellcheck`-compliant.
`wezterm` escapes unquoted strings on paste, so it becomes `wget https://s3.amazonaws.com/spec.ccfc.min/$\{latest\}`. Adding quotes fixes that.
PR.
[2]: https://github.com/firecracker-microvm/firecracker/blob/main/docs/api-change-r …

doc: quote wget URLs to avoid copy paste escapes

---

src/vmm/src/devices/virtio/vsock/csm/connection.rs
src/vmm/src/devices/virtio/vsock/packet.rs
src/vmm/src/devices/virtio/vsock/test_utils.rs
src/vmm/src/devices/virtio/vsock/unix/muxer.rs

Use u32 for all Vsock reletated buffers  instead of usize, since the Virtio specification states that lengths of virtio-buffers fit into u32
Close #4627 
PR.
[3]: …

Use u32 for Vsock related buffer sizes

---

src/vmm/Cargo.toml
src/vmm/benches/memory_access.rs
src/vmm/src/builder.rs
src/vmm/src/resources.rs
src/vmm/src/rpc_interface.rs

Add a benchmark that attempts to capture the latency of a single page
fault in a guest memory configuration that we also use in production.
This should catch regressions such as the 1.6 memfd/vhost post
snapshot-restore latency regression, and does indeed do so:
MAP_ANONYMOUS:
```
Running benches/memory_access.rs
page_fault    time:   [2.8611 µs 2.9327 µs 3.0170 µs]
Found 9 outliers among 100 measurements (9.00%)
4 (4.00%) high mild
5 (5.00%) high severe
```
memfd_create:
```
Running benches/memory_access.rs
page_fault    time:   [5.7449 µs 5.8779 µs 6.0450 µs]
change: [+85.649% +92.231% +98.074%] (p = 0.00 < 0.05)
Performance has regressed.
Found 8 outliers among 100 measurements (8.00%)
5 (5.00%) low mild
2 (2.00%) high mild
1 (1.00%) high severe
```
Add the same benchmark for huge …

bench: add benchmark for page fault latencies

---

.buildkite/pipeline_perf.py

We're observing performance instability on m6i/5.10 which is causing A/B performance test failures. To suppress false positives, pin AMI to the last known good one only for m6i/5.10.
PR.~~ …

chore: Pin m6i/5.10 AMI to last known good one

---

.github/CODEOWNERS
MAINTAINERS.md

Update maintainer and codeowner lists.
To keep it up to date.
PR.~~
[contribution quality standards](https://github.com/firecracker-microvm/firecracker/blob/main/CONTRIB …

doc: update maintainers and codeowners

---

src/vmm/benches/memory_access.rs

The benchmark tries to write to guest physical address 0, but on ARM guest memory doesn't start at 0, so when resolving the address we panicked.
Fix this by instead simply using whatever address guest memory starts with.
...
...
PR.
[2]: https://github.com/firecracker-microvm/firecracker/blob/main/docs/a …

fix memory access benchmark panicking on ARM

---

tests/integration_tests/performance/test_benchmarks.py

With having more benchmarks, we started hitting the 600s pytest timeout: https://buildkite.com/firecracker/firecracker-pr-optional/builds/9105. Increase it to 900s.
...
...
PR.
[3]: …

test: increase timeout on benchmarks

---

.mailmap
CHANGELOG.md
CREDITS.md
Cargo.lock
docs/RELEASE_POLICY.md
resources/guest_configs/patches/0004-disable-CONFIG_ARM64_ERRATUM_3194386-for-aarch64.patch
src/cpu-template-helper/Cargo.toml
src/firecracker/Cargo.toml
src/firecracker/swagger/firecracker.yaml
src/jailer/Cargo.toml
src/rebase-snap/Cargo.toml
src/seccompiler/Cargo.toml
src/snapshot-editor/Cargo.toml

Update version number / CHANGELOG / CREDITS
Release v1.9.1
PR. …

chore: release v1.9.1

---

tests/integration_tests/performance/test_boottime.py
tests/integration_tests/performance/test_memory_overhead.py

These tests do not assert anything, and are only used for us to collect metrics. As such, it suffices to run them once at night (especially because we do not ever actually look at the metrics emitted by the PR runs).
Save compute resources and reduce CI runtime.
PR.
[2]: …

test: mark boottime and memory overhead tests as nonci

---

resources/seccomp/aarch64-unknown-linux-musl.json
resources/seccomp/x86_64-unknown-linux-musl.json
src/vmm/src/devices/virtio/iov_deque.rs
src/vmm/src/devices/virtio/iovec.rs
src/vmm/src/devices/virtio/mod.rs
src/vmm/src/devices/virtio/net/device.rs
src/vmm/src/devices/virtio/net/mod.rs
src/vmm/src/devices/virtio/net/persist.rs
src/vmm/src/devices/virtio/net/tap.rs
src/vmm/src/devices/virtio/net/test_utils.rs
src/vmm/src/devices/virtio/rng/device.rs
src/vmm/src/devices/virtio/vsock/mod.rs
src/vmm/src/devices/virtio/vsock/packet.rs

Change the network device emulation to avoid the intermediate memory copy from the TAP device to Firecracker memory buffer. To achieve this, we use `readv` system call to read from the TAP device directly in guest memory.
Currently, on the RX path of our network device we perform two memory copies for receiving a network frame from the TAP device to the guest driver. We first read the frame from the TAP device inside a memory buffer maintained by Firecracker. Next, we copy the frame from the buffer inside guest memory. We need the intermediate buffer because, typically, the guest side buffer is scattered across the guest memory.
We had tried to implement this optimization [before](https://github.com/firecracker-microvm/firecracker/pull/2958) but we observed performance regression which …

Use `readv` for the RX path of the network device to avoid one memory copy per frame

---

tests/host_tools/udp_offload.py
tests/integration_tests/functional/test_net.py

This is a regression test for the following fix (https://github.com/firecracker-microvm/firecracker/pull/4826):
```
commit a9e5f1381bb30f9ad9fca11f2eade83a642711b5
Author: Nikita Kalyazin <kalyazin@amazon.co.uk>
Date:   Mon Sep 30 13:05:28 2024 +0000
fix(net): set tap offload features on restore
```
The test verifies that tap offload features are configured for both booted and restored VMs.
Regression testing.
- ~~[ ] Any required documentation changes (code and docs) are …

test(net): add test for tap offload features

---

src/firecracker/swagger/firecracker.yaml

This updates `firecracker.yaml` to reflect the implementation.
cpu-config field was added by (https://github.com/firecracker-microvm/firecracker/pull/3678):
```
commit 9da9619ea480342e3c4063ed55193342cd7923ae
Author: Takahiro Itazuri <itazur@amazon.com>
Date:   Wed Apr 26 13:55:21 2023 +0000
feat: Add "cpu-config" to config file
```
entropy field was added by (https://github.com/firecracker-microvm/firecracker/pull/3691):
```
commit 250036de87052e41e7ccea6d475cbace6d1ae8de
Author: Babis Chalios <bchalios@amazon.es>
Date:   Wed Nov 23 09:52:28 2022 +0000
feat(entropy): plug in with API
```
Certificate of Origin and signing off your …

doc(swagger): add cpu-config and entropy in vm config

---

CHANGELOG.md
src/vmm/src/device_manager/mmio.rs
src/vmm/src/device_manager/persist.rs
tests/framework/microvm.py
tests/host_tools/udp_offload.py
tests/integration_tests/functional/test_api.py
tests/integration_tests/functional/test_balloon.py
tests/integration_tests/functional/test_cmd_line_start.py
tests/integration_tests/functional/test_concurrency.py
tests/integration_tests/functional/test_cpu_features.py
tests/integration_tests/functional/test_cpu_features_aarch64.py
tests/integration_tests/functional/test_dirty_pages_in_full_snapshot.py
tests/integration_tests/functional/test_drive_vhost_user.py
tests/integration_tests/functional/test_mmds.py
tests/integration_tests/functional/test_net.py
tests/integration_tests/functional/test_pause_resume.py
tests/integration_tests/functional/test_rng.py
tests/integration_tests/functional/test_serial_io.py
tests/integration_tests/functional/test_snapshot_basic.py
tests/integration_tests/functional/test_snapshot_editor.py
tests/integration_tests/functional/test_snapshot_not_losing_dirty_pages.py
tests/integration_tests/functional/test_uffd.py
tests/integration_tests/functional/test_vsock.py
tests/integration_tests/performance/test_huge_pages.py
tests/integration_tests/performance/test_memory_overhead.py
tests/integration_tests/performance/test_snapshot_ab.py
tests/integration_tests/security/test_jail.py
tests/integration_tests/security/test_vulnerabilities.py
tools/create_snapshot_artifact/main.py

Backport https://github.com/firecracker-microvm/firecracker/pull/4835 and its dependencies: https://github.com/firecracker-microvm/firecracker/pull/4782 , https://github.com/firecracker-microvm/firecracker/pull/4796 , https://github.com/firecracker-microvm/firecracker/pull/4798 , https://github.com/firecracker-microvm/firecracker/pull/4812 .
Regression testing in the release branch.
PR.
- ~~[ ] …

[1.9] add vsock fix and test for tap offload features

---

Cargo.lock
src/vmm/Cargo.toml
src/vmm/src/devices/virtio/iovec.rs
src/vmm/src/devices/virtio/vsock/csm/connection.rs
src/vmm/src/devices/virtio/vsock/device.rs
src/vmm/src/devices/virtio/vsock/event_handler.rs
src/vmm/src/devices/virtio/vsock/mod.rs
src/vmm/src/devices/virtio/vsock/packet.rs
src/vmm/src/devices/virtio/vsock/test_utils.rs
src/vmm/src/devices/virtio/vsock/unix/muxer.rs

Make `vsock` reuse packets for RX and TX paths. This removes overhead of creating packets from the virt queues.
This also should prevent regressions from #4799.
Improved performance.
PR.
[3]: …

vsock: reuse IoVecBuffer(Mut) buffers for packets within a connection

---

src/vmm/src/arch/aarch64/fdt.rs
src/vmm/src/arch/aarch64/mod.rs

Adds fdt to guest memory at the location `create_fdt` is called not in `create_fdt`.
Removes unnecessary `std::hash::BuildHasher` parameterization.
...
@roypat we are not able to remove the `GuestMemoryMmap` parameter because we use it to create the memory node.
However, this updated code now writes the fdt to guest memory at the site of the caller utilizing the previously unused return value from `create_fdt`. 
- separation of concerns
- simplify unit testing
#4700 
...
PR. …

Cleaning up create_fdt 

---

Cargo.lock
docs/gdb-debugging.md
src/firecracker/Cargo.toml
src/vmm/Cargo.toml
src/vmm/src/builder.rs
src/vmm/src/gdb/arch/aarch64.rs
src/vmm/src/gdb/arch/mod.rs
src/vmm/src/gdb/arch/x86.rs
src/vmm/src/gdb/event_loop.rs
src/vmm/src/gdb/mod.rs
src/vmm/src/gdb/target.rs
src/vmm/src/lib.rs
src/vmm/src/resources.rs
src/vmm/src/vstate/vcpu/mod.rs
tests/integration_tests/build/test_gdb.py

This PR is adding GDB support into Firecracker. This is will allow us to connect GDB to the guest kernel and enable step through debugging.
This is achieved by leveraging https://github.com/daniel5151/gdbstub which allows us to debug the kernel over the GDB Remote Serial Protocol. The way this is managed is through a new GDB thread which is used to manage the interaction between the VCPUs and the GDB server.
A list of the current features supported in x86
- Multithreaded Debugging (multi core VM's)
- Register Read/Write
- Guest Memory Read/Write
- Software Breakpoints Add/Remove
- Hardware Breakpoints Add/Remove
- Single Step
- Continue
The implementation is feature gated behind the `debug` flag which aims to allow us to remove all the dependencies at compiletime
- Adding GDB support for …

feat: Enable gdb debugging on x86

---

src/vmm/src/devices/virtio/rng/device.rs

Add a buffer to the Entropy struct which will be reused for descriptor chain processing. This will remove runtime overhead of recreating this buffer for each request.
Less overhead in rng device.
PR.
[3]: …

Reuse buffer for processing descriptor chains in virtio-rng device

---

tests/framework/utils.py

Substitute this mechanism with calling epoll() on the pidfd of the process instead. This should deterministically block until the process exits. If there's something else wrong, we will hit the pytest timeout.
Currently, we use psutil.pid_exists in a loop with a timeout of 10 seconds. This is racy and indeed some times we hit it in our CI.
PR.
_______________________________________________________________ …

fix(ci): epoll on pidfd to wait for Firecracker exit

---

tools/ab_test.py

Move the print statement that states which A/B-Tests we're performing below the check that filters out ignored test cases. This way, we avoid claiming to do an A/B-Test for things that are later actually filtered out (meaning no A/B-Test actually happens).
PR.
[2]: …

test: move "doing A/B-Test" print statement below ignore-check

---

tests/framework/utils.py
tests/host_tools/network.py

When doing `_init_connection`, set SSHs debug level to most verbose, so
that in case a connection failure occurs, we can look at the SSH logs
(both local and remote, see man ssh(1)).
PR.
[3]: …

Dump SSH debug level logs if initial connection to guest fails

---

tools/bump-version.sh

We want to do that before creating the release branch so that we can fix issues with new dependencies ahead of the release.
PR.

chore: don't update dependencies when with new vX.Y.0-dev version

---

.gitignore
docs/rootfs-and-kernel-setup.md
resources/rebuild.sh
tools/devtool

Add a devtool command to build CI artifacts. The command calls `resources/rebuild.sh` within the dev container, since the script itself assumes an Ubuntu host environment.
Also, update the documentation about building guest kernels to point to this script
Add a command that allows us to build CI artifact kernels locally and also fix the broken documentation about building guest kernels.
Fixes #4757 
PR. …

Add a devtool command for build CI artifacts

---

tests/host_tools/network.py
tests/integration_tests/functional/test_binary.py

Ensure the gdb feature is not enabled in releases.
We want to prevent accidentally running a gdb/debug build in production.
PR.

Test gdb feature is not enabled in release

---

docs/gdb-debugging.md
src/vmm/src/arch/aarch64/regs.rs
src/vmm/src/builder.rs
src/vmm/src/gdb/arch/aarch64.rs
src/vmm/src/gdb/arch/x86.rs
src/vmm/src/gdb/target.rs
tests/integration_tests/build/test_gdb.py

Adding support for GDB debugging on arm machines.
Unfortunately KVM doesn't provide all the same API's we have to use on x86 so some parts have to be manually implemented. Some assumptions around Virtual Address configuration have been made to simplify the implementation.
PR.
[2]: …

ARM support for GDB

---

tests/framework/microvm.py
tests/framework/utils.py
tests/framework/utils_vsock.py
tests/host_tools/network.py
tests/host_tools/vsock_helper.c
tests/integration_tests/functional/test_snapshot_basic.py

- more debug output if running SSH commands in the guest fails
- relax timeouts
- minor code cleanup
- more debug information when SSH failures, and less spurious timeout failures
PR.
[3]: …

Minor test fixes to improve debuggability and readability

---

.buildkite/pipeline_perf.py

Unpin 5.10/m6i ami.
Performance is stable now on 5.10/m6i instances.
PR.

chore: unpin 5.10/m6i ami

---

src/vmm/src/arch/aarch64/cache_info.rs
src/vmm/src/arch/aarch64/fdt.rs
src/vmm/src/arch/aarch64/mod.rs

The first commit improves the logging/reporting of errors during FDT creation (e.g., failures while parsing CPU cache information from `sysfs`).
The second commit changes the type of field `number_of_sets` in struct `vmm::arch::aarch64::cache_info::CacheEntry` from `u16` to `u32`, thus allowing support for hosts with CPU caches with a number of sets higher than `u16::MAX` (e.g., [NVIDIA GH200 Grace Hopper][gh200]).
When we attempted to boot a microVM on a [GH200][gh200] host following the [Getting Started guide](https://github.com/firecracker-microvm/firecracker/blob/main/docs/getting-started.md) (with a minor modification, to download the `aarch64` kernel binary), building the microVM failed, and the following was logged:
```text
. . .
2024-10-22T16:11:02.966071476 …
```

Support FDT setup for CPU caches with high number of sets

---

CHANGELOG.md
resources/seccomp/x86_64-unknown-linux-musl.json
src/vmm/src/logger/metrics.rs
src/vmm/src/vstate/vcpu/mod.rs
tests/framework/utils.py
tests/host_tools/fcmetrics.py
tests/integration_tests/functional/test_pause_resume.py

Call `KVM_KVMCLOCK_CTRL` when pausing vCPUs. This allows guest kernel's soft lockup watchdog to know that it was the hypervisor that paused the vCPUs and don't trigger an exception.
Fixes: https://github.com/firecracker-microvm/firecracker/issues/1859
This is to avoid guest kernel panic on resume path due to soft lockup detection.
PR.
[contribution quality standards](https://github.com/firecracker-microvm/firecracker/blob/main/CONTRI …

fix(vmm): call KVMCLOCK_CTRL when pausing

---

CHANGELOG.md

Add a CHANGELOG entry for changes in #4869 
https://github.com/firecracker-microvm/firecracker/pull/4869 changed the type that holds the number of sets of a CPU cache from `u16` to `u32`. This allows us to support ARM systems with CPU caches with sets more than `u16::MAX`.
PR.
[2]: …

Add CHANGELOG entry on support of ARM systems with big caches

---

.buildkite/pipeline_perf.py

The instability is still there, so we revert firecracker-microvm/firecracker#4865

Revert "chore: unpin 5.10/m6i ami"

---

tests/integration_tests/functional/test_balloon.py

Updated the deflate on oom test to attempt to increase stability of the test. 
Making the a balloon less aggressive size, but allocating a larger chunk of memory, we are still able to test the functionality of the balloon device (it will deflate if the flag is enabled and not if disabled.) With this setup it means the guest is less likely to crash and cause the test to fail
I ran the flaky test look as seen here: https://github.com/firecracker-microvm/firecracker/tree/main/tests#how-to-reproduce-intermittent-aka-flaky-tests for over an hour on my machine with no failures
Altered configuration of the balloon deflate on oom tests
Attempt to fix deflate on oom flaky test
the terms of the Apache 2.0 license. For …

Update test_deflate_on_oom test

---

tests/framework/artifacts.py
tests/integration_tests/functional/test_cmd_line_parameters.py
tools/test-popular-containers/build_rootfs.sh

- Add Ubuntu 24.10 to the popular containers test, and remove 23.10
- Drop some dead code supporting old releases.
...
PR.

Add Ubuntu 24.10 to popular containers

---

src/vmm/src/devices/virtio/iov_deque.rs
src/vmm/src/devices/virtio/iovec.rs
src/vmm/src/devices/virtio/net/device.rs
src/vmm/src/devices/virtio/net/mod.rs
src/vmm/src/devices/virtio/net/persist.rs
src/vmm/src/devices/virtio/net/tap.rs
src/vmm/src/devices/virtio/rng/device.rs

Make `IovDeque` to have configurable size and increase `virtio-net` queue size to 512. This helps with keeping both
`vmm` thread and guest busy at high network load and improves performance.
The increased queue size also leads to increased memory usage by 4 pages which is negligible compared to the overall VM memory usage.
Improved performance.
PR. …

Increase virtio-net queue size to 512

---

CHANGELOG.md

Add `readv` and queue size increase changes in virtio-net device to the CHANGELOG.
We forgot to add them initially.
PR.

chore: update CHANGELOG with virtio-net changes

---

CHANGELOG.md
docs/gdb-debugging.md
src/firecracker/swagger/firecracker.yaml
src/vmm/src/builder.rs
src/vmm/src/persist.rs
src/vmm/src/resources.rs
src/vmm/src/vmm_config/machine_config.rs

Allow a GDB debugging session to be started over API
Moved the GDB address config inside the machine-config section.
This allows a user to start a GDB debugging session using the API and are not limited to just using the config file
Allow for GDB to be setup when using config file is not possible
PR. …

Start GDB session with API

---

.buildkite/common.py
.buildkite/pipeline_perf.py
tests/README.md
tests/conftest.py
tests/framework/ab_test.py
tests/framework/properties.py
tests/framework/utils.py
tests/integration_tests/performance/test_benchmarks.py
tests/integration_tests/security/test_jail.py
tests/integration_tests/security/test_vulnerabilities.py
tools/ab_test.py
tools/devtool

Make the A/B-Test script take two directories with firecracker/jailer binaries as arguments, instead of two git revisions
Since we extracted the build step in our buildkite infra, we refuse to compile firecracker inside of pytest. This means that running A/B-Tests outside the buildkite infra was essentially impossible, as the two revisions were resolved to a directory path as it would be created by the buildkite infra. If this directory did not exist, the script would fail. Additionally, the few git operations that the script did do on the revisions were very brittle and did not match what the extracted build step did for resolving git objects (so it could be that the build step passes, but then ab_test.py doesn't understand the git objects anymore). 
By submitting this pull request, I …

Simplify A/B-Test orchestration

---

CHANGELOG.md
Cargo.lock
docs/RELEASE_POLICY.md
src/acpi-tables/Cargo.toml
src/cpu-template-helper/Cargo.toml
src/firecracker/Cargo.toml
src/jailer/Cargo.toml
src/rebase-snap/Cargo.toml
src/seccompiler/Cargo.toml
src/snapshot-editor/Cargo.toml
src/utils/Cargo.toml
src/vmm/Cargo.toml
src/vmm/src/devices/virtio/net/mod.rs

Update the release branch with the queue size revert and release policy changes
...
PR.

Update v1.10 branch with revert

---

Cargo.lock
src/cpu-template-helper/Cargo.toml
src/firecracker/Cargo.toml
src/firecracker/swagger/firecracker.yaml
src/jailer/Cargo.toml
src/rebase-snap/Cargo.toml
src/seccompiler/Cargo.toml
src/snapshot-editor/Cargo.toml

bump version to 1.11.0-dev
...
...
PR.

chore: bump version to 1.11.0-dev

---

CHANGELOG.md
CREDITS.md
Cargo.lock
src/cpu-template-helper/Cargo.toml
src/firecracker/Cargo.toml
src/firecracker/swagger/firecracker.yaml
src/jailer/Cargo.toml
src/rebase-snap/Cargo.toml
src/seccompiler/Cargo.toml
src/snapshot-editor/Cargo.toml

Update version number / CHANGELOG / CREDITS
...
...
PR.

chore: release v1.10.0

---

tests/integration_tests/functional/test_net.py

Use iperf3-vsock on host for the `test_high_ingress_traffic` test instead of iperf3.
We see crashes inside `test_high_ingress_traffic` on aarch64 with both iperf3 3.16 (currently in devctr) and 3.17 (latest release).
PR.~~
- ~~[ ] New `TODO`s link to an …

test(net): use iperf3-vsock to avoid iperf crashes on aarch64

---

tests/integration_tests/functional/test_cpu_features_aarch64.py
tests/integration_tests/functional/test_cpu_features_x86_64.py

PR #4884 introduced a test that ensures CPU feature diff between host and guest hasn't been changed.
However, the expected diff can vary depending on a combination of host kernel version and guest kernel version.
The current our setting is as follows:
- Host
- Amazon Linux 2 (v5.10)
- Amazon Linux 2023 (v6.1)
- Ubuntu 24.04 (v6.8)
- Guest
- Amazon Linux microvm kernel (v5.10)
- Amazon Linux microvm kernel (v6.1)
- aarch64
- Add "ssbs" to the expected diff if needed.
- x86_64
- Remove "flush_l1d" from the expected diff if the host passes through it.
- Add "invpcd_single" to the expected diff if needed.
**Note that I implemented it in a general way as possible because we might want to support more host and guest kernels in the future.**
By submitting this pull request, I confirm that my …

fix(test): Handle CPU feature diff between host and guest correctly

---

src/vmm/src/devices/virtio/net/device.rs

Double the refill time for RX rate limiter.
Although we increased the refill time in the past in commit 347f877ec2a9 ("unittest: net: eliminate ReadTapMock::MockFrame") to avoid intermittent issues, it still fails rarely (maybe due to resource contention). We are not sure the enough refill time, but it's worth doubling it and may reduce the chance of kicking the retry of the whole unit tests manually.
- ~~[ ] Any required documentation changes (code and docs) are included in …

chore(test): Double refill time for RX rate limiter

---

src/vmm/src/devices/virtio/iovec.rs
src/vmm/src/devices/virtio/net/device.rs

Minor fixes for usage of constants in the virtio-net and iovec.
More maintainable code.
PR.

Minor queue size fixes

---

CHANGELOG.md
docs/pvh.md
docs/rootfs-and-kernel-setup.md
src/vmm/src/arch/x86_64/gdt.rs
src/vmm/src/arch/x86_64/mod.rs
src/vmm/src/arch/x86_64/regs.rs
src/vmm/src/builder.rs
src/vmm/src/vstate/vcpu/aarch64.rs
tests/framework/utils.py
tests/integration_tests/functional/test_api.py
tests/integration_tests/style/test_gitlint.py

Bring the feature branch up-to-date with all changes that happened in `main` since it was last updated, and which didn't show up as a merge conflict. Also do some minor doc fixes, and add integration testing.
Since these days all our CI kernels are compiled with `CONFIG_PVH=y`, integration testing is just a matter of adding an assert to verify that PVH boot mode is indeed being used. We are not adding FreeBSD tests to our CI, as we have no easy means for maintaining FreeBSD artifacts, and last time I checked (which admittedly was August 23), it also didn't boot on AMD instances. 
See also https://github.com/firecracker-microvm/firecracker/issues/3041 
the terms of the Apache 2.0 license. For more information on …

Final PVH fixups

---

.github/pull_request_template.md

Improve the PR checklist to make it more clear and explicitly ask contributors to run the automated checkstyles.
The current PR checklist doesn't tell to run the `checkstyle` explicitly and it's a common reason PRs from external contributors get delayed. I also took the opportunity to refresh it. 
[3]: …

chore: update PR checklist

---

tests/framework/utils_cpu_templates.py

Add the SVE CPU template as a valid template in 5.10 since it works.
Test ARM CPU templates in host Linux 5.10
While not all ARM CPU templates work in 5.10, some simple ones like enabling SVE work.
in the PR.
[2]: https://github.com/firecracker-microvm/firecracker/blob/main/docs/api-change-runboo …

test: test ARM CPU templates in Linux host 5.10

---

CHANGELOG.md
src/vmm/src/mmds/ns.rs
src/vmm/src/mmds/persist.rs
src/vmm/src/persist.rs

Remove `max_connections` and `max_pending_resets` fields from snapshot.
**Note that I only focused on removing them in this PR although I might open another PR to refactor more later.**
`TcpIPv4Handler` for MMDS network stack preallocates several buffers
whose sizes are saved into a snapshot as `max_connections` and
`max_pending_resets` in `MmdsNetworkStackState`. But they are always the
same constant hardcoded values (`DEFAULT_MAX_CONNECTIONS` and
`DEFAULT_MAX_PENDING_RESETS`) as of today, which means there is no need
to save them into a snapshot. Even if we change the hardcoded sizes
across Firecracker versions, that should not be a problem. This is
because the snapshot feature does not support migration of network
connections and those buffers are initialized with empty on snapshot …

snapshot: Remove max_connections and max_pending_resets fields

---

CHANGELOG.md

**follow-up for https://github.com/firecracker-microvm/firecracker/pull/4913#discussion_r1841969632**
We bumped the snapshot version up twice recently, requiring users to regenerate their snapshot, but the user action isn't clearly stated.
in the PR.~~ …

chore: Clarify user action

---

.buildkite/common.py
.buildkite/pipeline_cpu_template.py

This helps the script work for instances it doesn't know about, which is helpful while onboarding new instances.
Only Graviton metal instances are aarch64 at the moment.
Fixes: c33bc6c6f32a886cf186d4c4130cb0f6bd66bdca
There's a better solution using `StrEnum`, but the python that runs this script does not support that.
To be able to use the script with instances it does not know about. I.e. `--instance mX.metal`  
in the PR. …

ci: infer instance architecture from a heuristic

---

docs/network-setup.md

network-for-clones is not changed in this PR since it's a whole another can of worms I'd like to deal with later.
These changes are to network-setup:
- Migrate to nftables
- Improve the documentation itself to convert it from a rather basic getting started guide to something more usable in the real world:
Fulfills #4874 
PR.
[1]: …

Improve network-setup with nft support and further instructions.

---

CHANGELOG.md
src/firecracker/swagger/firecracker.yaml

- Add vcpu_features and kvm_capabilites to swagger `CpuConfig`
- Also, the field type is changed from "string" to "object", as it has properties and thus can't be a string.
These fields were added in #3967 but the Swagger API definition was not updated. This patch fixes the API definition.
Also, the field was incorrectly marked as string. I've verified that changing to object doesn't lead to any changes in the generated client code, as it was already considering it as an object.
how they are solving the problem in a clear …

fix: add vcpu_features and kvm_capabilites to swagger

---

src/vmm/src/devices/virtio/device.rs
src/vmm/src/devices/virtio/mmio.rs
src/vmm/src/devices/virtio/vsock/device.rs
src/vmm/src/gdb/target.rs
src/vmm/src/vstate/vcpu/x86_64.rs
src/vmm/src/vstate/vm.rs
tests/data/static_cpu_templates/aarch64_with_sve_and_pac.json
tests/framework/utils_cpu_templates.py

Setting the least significant 4 bits to zero overwrites some
configuration that Firecracker sets on secondary CPUs that is needed for
them to be able to be booted. With these 4 bits set to 0, the CPUs will
never show up as online inside the guest, and KVM will just infinitely
spin inside KVM_RUN for them. Fix by using 'x' in the template, which
preserves the defaults set by Firecracker.
in the PR.
[Runbook …

fix: make aarch64_with_sve_and_pac template example work with >=2 vcpus

---

docs/getting-started.md

During the last change we missed updating the Firecracker CI version.
Also keep the rootfs as ext4 for the rest of the guide.
Fixes: a69595f5f03757bd990318e7aa4f23409355ae13
...
...
in the PR.
[3]: …

docs: fix Firecracker version and rootfs

---

tools/devtool

Without ensure_ci_artifacts called inside cmd_sandbox, you will see an index out of bounds errors during set up of the argument parser, since build/img will be an empty directory (e.g. there are no kernels to select, and the -1 index will be out of bounds).
Reported-by: Jack Thomson <jackabt@amazon.co.uk>
...
...
in the PR. …

fix: ensure ci artifacts are present when using devtool sandbox

---

docs/getting-started.md

the getting started guide was hardcoding eth0 as the network interface on the host to route outbound microvm network traffic to. However, on EC2 instances (and my laptop), that's wrong, because its not called eth0. So instead dynamically determine the hopefully correct network interface on the host.
Suggested-by: Pablo Barbáchano <pablob@amazon.com>
...
...
in the PR. …

fix: properly setup outbound network connectivity in getting started

---

tools/devtool

Every now and then, I managed to end up with an empty CI artifacts
folder, for whatever reason (mostly me being silly). The solution is
generally to remove whatever messed up stuff I ended up with in
build/img, and run some arbitrary devtool command that I know will
redownload everything. Similar workflows must happen whenever we do an
in-place update of our CI artifacts.
Abstract this away into a command that deletes the build/img folder, and
then redownloads it.
...
... …

devtool: add download_ci_artifacts command

---

.buildkite/pipeline_perf.py

This is to keep monitoring functionality and performance on the latest known stable AMI.
...
...
in the PR.

test: use pinned ami for m6i/6.1

---

tools/devtool
tools/functions

Whenever devtool notices that its container is not cached locally, it requests user input to confirm the new devctr version should indeed be downloaded. In practice, I do not remember ever saying "no" here. On the other hand, forgetting to explicitly disable these confirmations in buildkite pipelines has lead to a myriad of "stuck pipeline" issues. Thus, remove this confirmation step altogether, as it does more harm than good.
To avoid having to fix all pipelines that do pass `-y` today, simply treat the `-y` parameter as a no-op (suggested by Pablo, thanks!).
...
... …

devtool: stop asking for user confirmation on container pull

---

tests/framework/utils_cpuid.py
tests/integration_tests/functional/test_cpu_features_x86_64.py

Add support for detection on m7a instance and prevent the test failure from missing cpu config test
Steps to allow us to run the M7a instance in our CI environment
in the PR.
[3]: …

[CI] Add support for M7a detection in tests

---

tests/framework/microvm.py

We missed saving metadata when saving to disk
Fixes: 426790e4001ac7315554f876637298fb37fb85a8
Save the metadata when storing snapshot on disk
Fix pipelines that started failing because of the previous change
in the PR.
[2]: https://github.com/firecracker-microvm/firecracker/blob/main/docs/api-cha …

fix(tests): save snapshot metadata when saving to disk

---

tests/integration_tests/functional/test_cpu_features_host_vs_guest.py

During previous refactoring, this switch was accidentally removed.
We need this for pipelines not to fail.
in the PR.

fix(tests): add switch case for AMD_GENOA to the cpu features test

---

tests/integration_tests/functional/test_cpu_features_host_vs_guest.py

Record the differences with AMD Milan CPU.
in the PR.

tests: flesh out the AMD Genoa host vs guest test

---

.gitlint
tests/integration_tests/functional/test_cpu_features_x86_64.py

These run in a nightly pipeline and apparently the read/write MSR scripts take longer than the 100s default timeout added in b99abe1.
Fixes: 36448e94ebf4 ("test: set default timeout of 100s for ssh commands")
...
...
in the PR.
[2]: https://github.com/firecracker-microvm/firecracker/blob/main/doc …

fix(test): remove timeouts from MSR integration tests

---

tests/host_tools/test_syscalls.c
tests/integration_tests/security/test_seccomp_validate.py

In addition do a few more cleanups to the test:
- Use `atol` to read longs
- musl makes an ioctl that is not permitted in seccomp. We didn't use the return code anyway, so remove it.
...
...
in the PR. …

tests: compile test_syscall with musl-gcc

---

tests/framework/utils_vsock.py

Use a try-finally block inside check_guest_connection to make sure that
socat gets killed even if something inside check_guest_connection fails
and raises an exception.
...
...
in the PR.
[2]: …

fix(test): ensure socat gets killed in test_5_snapshots

---

resources/seccomp/aarch64-unknown-linux-musl.json
resources/seccomp/x86_64-unknown-linux-musl.json
tests/framework/static_analysis.py
tests/integration_tests/build/test_seccomp_no_redundant_rules.py

Use static analysis to determine the set of syscalls (+ arguments) that are actually present in the Firecracker binary, and cross-reference this with the seccomp filters, to determine redundant seccomp rules. Additionally, remove redundant seccomp rules identified by this process. Please see the individual commit messages for details.
Sample output:
```
FAILED integration_tests/build/test_seccomp_no_redundant_rules.py::test_redundant_seccomp_rules - AssertionError: Found redundant seccomp rules! [('uname', {})]
```
how …

Add static analysis to CI to determine redundant seccomp rules

---

tests/integration_tests/performance/test_drive_rate_limiter.py

In test_drive_rate_limiter, use `fio` for measuring latencies of writing a fixed number of bytes to a block device, instead of `dd` (which the test itself notes is unreliable). Should fix intermitted failures we're been seeing in this test, hopefully.
...
...
in the PR.
[2]: …

test: use fio instead of dd for performance tests

---

tests/host_tools/network.py

This change fixes the `test-popular-containers` suite by using the binary name `true` when estabilishing the ssh connection instead of the absolute path, and cleaning up the ssh control socket on error before the next retry.
Fixes #4955 
In #4955 the executable to check the ssh connection liveliness was changed from `true` to `/usr/bin/true`, but that is not its path in all rootfs, causing failures in the `test-popular-containers` suite.
Also, since the error is retried but the control socket is not cleaned up, subsequent retries would fail for the assertion. …

fix(test): do not use absolute path to true when opening ssh connection

---

tests/conftest.py

tests: prevent double publishing of metrics

---

.buildkite/pipeline_perf.py

Unpin m6i/6.1 AMI.
The volatility is not visible on the latest AMI.
- ~~[ ] I have run `tools/devtool checkstyle` to verify that the PR passes the
automated style checks.~~
- ~~[ ] I have described what is done in these changes, why they are needed, and
how they are solving the problem in a clear and encompassing way.~~
in the PR.~~
- ~~[ ] If a specific issue led to this PR, this PR closes the …

chore: unpin m6i/6.1 ami

---

tests/conftest.py

Print the EC2 AMI in the pytest report header.
To easily tell which AMI is being used, for validation or troubleshooting
in the PR.
[3]: https://github.com/firecracker-microvm/firecracker/blob/main/CONTRI …

ci: print EC2 AMI in the pytest report header

---

CHANGELOG.md
src/firecracker/src/main.rs
src/vmm/src/arch/aarch64/mod.rs
src/vmm/src/arch/mod.rs
src/vmm/src/arch/x86_64/mod.rs
src/vmm/src/builder.rs
src/vmm/src/devices/virtio/iov_deque.rs
src/vmm/src/devices/virtio/iovec.rs
src/vmm/src/gdb/target.rs
src/vmm/src/vstate/vm.rs

Separate `PAGE_SIZE` constant into 2: `GUEST_PAGE_SIZE` and `HOST_PAGE_SIZE`.
`HOST_PAGE_SIZE` has a default of 4K, but is also queried at runtime to support other page sizes.
The only structure which did not work with non default 4K pages is `IovDeque`. This PR updates it
and removes restrictions on the queue size and on the host page size.
Tested16K pages support on rp5 with 16K page kernel.
Previously Firecracker was working on hosts with non 4K pages, but with 1.10 version we introduced `IovDeque` type
which assumed the host page size to be 4K. …

Fix 16K host page support

---

.buildkite/common.py

In c6add4fccf27cd0522a7e49a2c5dc67ab7067980 while adding support for more complex parameters we broke passing simple strings.
While it can be worked around by quoting the string with '', that makes the simple case more complex than it was before, and breaks previous pipeline definitions.
Fix it so if the first character does not look like a python expression, take the value verbatim.
Fixes: c6add4fccf27cd0522a7e49a2c5dc67ab7067980
Tested with:
```
.buildkite/pipeline_perf.py --step-param env/foo1=foo --step-param env/foo2=[1,2]
```
...
automated …

ci: fix passing simple values to step parameters

---

tools/devtool

When running performance tests, the devtool script was disabling lower C-states, leaving only C0 (e.g. "CPU actively polling for new instructions") enabled, with the goal to reduce latencies of switching between C-states, and therefore increase test stability. However, we found out that on m6i (Icelake) this was causing performance to become erratic, with most performance metrics taking on bi-modal characteristics (funnily enough, this seems to be tied to something in the host kernel, as this volatility appears and disappears with host kernel updates, but we weren't able to narrow it down to _what_).
Since back when we originally disabled sleep states, we did not see any impact on metrics, the theory that it helps with test stability doesn't have any experimental support, so removing the …

fix: stop messing with C-states in performance tests

---

tests/integration_tests/build/test_seccomp_no_redundant_rules.py
tools/devctr/Dockerfile
tools/devtool

Update kani tool-chain.
Unpin cargo-deny because rust tool-chain has been upgraded.
Specify tag for libseccomp to have a fixed version.
Allow seccomp rules integration test to run on aarch64.
in the PR. …

docker update

---

.buildkite/pipeline_cross.py
.buildkite/pipeline_pr.py
tests/conftest.py
tests/framework/microvm.py
tests/host_tools/network.py
tests/integration_tests/functional/test_api.py
tests/integration_tests/functional/test_net.py

Reuse network namespaces during integration tests. This avoids spending time creating network devices and namespaces, which is a slow operation because of networking lock contention.
After doing that, since we don't have lock contention anymore, we can double the number of test workers and see an ~25% improvement on top of that.
To make functional test runs faster. Though this is low priority and the functional tests are not the long pole, this change is relatively small and self-contained.
The 2 changes together almost half the execution time:
| instance | before (s) | after (s) | % |
|:-:|-:|-:|-:|
| m6a | 361 | 195 | -47% |
|m6g | 245 | 137 |-45% |
the terms of the Apache 2.0 license. For more information on …

Tests: reuse network namespaces

---

.buildkite/pipeline_perf.py
tests/integration_tests/performance/test_network_ab.py

With C-states renabled by f610cae59a5d ("fix: stop messing with C-states in performance tests"), the m6i volatility will be gone.
...
...
in the PR.
[3]: …

test: unpin m6i/5.10 AMI for perf tests

---

tools/test-popular-containers/build_rootfs.sh

Add Amazon Linux 2023 to the list of rootfs we try.
We have no RHEL-derivative examples, and it would be good to have some variety.
in the PR.
[3]: …

CI: also test amazonlinux:2023 in the popular containers test 

---

tests/README.md
tools/devtool

If `cmd_test` is instructed to build its own binaries (e.g. being ran
outside of CI), and the environment specifies that A/B-tests should
be ran, then we not only need to build the currently checked out commit
(the "B" revision), but also an "A" binary based on the value of the
`BUILDKITE_PULL_REQUEST_BASE_BRANCH` environment variable.
...
...
in the PR. …

devtool: Build A and B binaries if $do_build is true

---

CHANGELOG.md
src/cpu-template-helper/src/main.rs
src/firecracker/examples/uffd/fault_all_handler.rs
src/firecracker/examples/uffd/uffd_utils.rs
src/firecracker/examples/uffd/valid_handler.rs
src/firecracker/src/api_server/parsed_request.rs
src/firecracker/src/api_server/request/machine_configuration.rs
src/vmm/benches/memory_access.rs
src/vmm/src/builder.rs
src/vmm/src/persist.rs
src/vmm/src/resources.rs
src/vmm/src/rpc_interface.rs
src/vmm/src/test_utils/mock_resources/mod.rs
src/vmm/src/vmm_config/machine_config.rs
src/vmm/tests/integration_tests.rs
tests/framework/microvm.py

This PR is an assortment of 5 small changes that are only connected by the fact that I ran into 4 of them while playing around with guest_memfd in Firecracker (the odd one out is the UFFD one, which is related to #4601). Roughly, we can group these changes into 3 categories:
- Remove an unneeded .clone() operation
- Ensure that a panic in the example UFFD handlers does not cause pytest to hang for 5 minutes because suddenly it's waiting indefinitely for page faults to be served, by having it take down Firecracker with it (and improvement of error messages in this case)
- Refactor some handling behind the /machine-config endpoint because the duplication of the same data/fields across VmConfig/MachineConfig was already confusing me when working on huge pages, and now that I had to touch …

Simplify microvm builder code and make uffd test failures easier to debug

---

CHANGELOG.md
docs/prod-host-setup.md
src/vmm/src/arch/aarch64/regs.rs
src/vmm/src/arch/aarch64/vcpu.rs
src/vmm/src/builder.rs
src/vmm/src/device_manager/legacy.rs
src/vmm/src/device_manager/mmio.rs
src/vmm/src/lib.rs
src/vmm/src/persist.rs
src/vmm/src/vstate/kvm.rs
src/vmm/src/vstate/mod.rs
src/vmm/src/vstate/vcpu/aarch64.rs
src/vmm/src/vstate/vcpu/mod.rs
src/vmm/src/vstate/vcpu/x86_64.rs
src/vmm/src/vstate/vm.rs
tests/integration_tests/functional/test_snapshot_basic.py

Reset KVM_REG_ARM_PTIMER_CNT physical counter register on VM boot to avoid passing through host physical counter. Note that resetting the register on VM boot does not guarantee that VM will see the counter value 0 at startup because there is a delta in time between register reset and VM boot during which counter continues to advance.
Prevent guest from reading host performance counter.
in the PR. …

feat: reset KVM_REG_ARM_PTIMER_CNT on VM boot

---

src/firecracker/examples/uffd/uffd_utils.rs

Add additional info to the panic messages in uffd examples.
Will help to debug potential issue.
in the PR.

feat: more descriptive panic messages in uffd examples

---

docs/ballooning.md

Add notes around known limitations of the balloon device
Add clarification around issues customers may encounter when using the balloon device
in the PR.
[3]: …

docs: Update documentation on balloon device

---

tests/integration_tests/functional/test_kvm_ptp.py

We have sometimes seen that this test can fail. In theory it could
happen that udev has not created the /dev/ptp0 file before we run the
ssh command.
So let's wait in udev for the device to appear up to 5 seconds.
Prevents (rare) test failures.
in the PR.
[2]: …

Tests: test_kvm_ptp: wait up to 5s for the device to appear.

---

tests/framework/gitlint_rules.py
tests/framework/properties.py
tests/framework/utils.py
tests/framework/utils_imdsv2.py
tests/host_tools/udp_offload.py
tests/integration_tests/style/test_rust.py
tools/devtool

With these two changes `./tools/devtool -y test -- --doctest-modules framework` passes
Closes #3035
Make sure doctests stay up to date.
in the PR.
[3]: …

tests: fix doctests in the Python codebase

---

tools/devtool

Since `devtool` does not have `-e`, commands fail but don't fail the test run.
Fixes:
dfb45dc4213bcb1c9704435457e233d3a210dce2
...
...
in the PR.
[3]: …

fix: make style checks fail if either test fails

---

docs/hugepages.md
src/vmm/src/resources.rs
src/vmm/src/vmm_config/boot_source.rs
src/vmm/src/vmm_config/machine_config.rs
tests/conftest.py
tests/integration_tests/performance/test_huge_pages.py
tests/integration_tests/performance/test_initrd.py

We have decided to move hugepages support out of developer preview,
despite missing support for memory ballooning.
...
...
in the PR.
[3]: …

Move huge pages support out of developer preview.

---

tests/integration_tests/functional/test_net.py

It can happen that we check for the file before `socat` has written it in the filesystem.
Sync before checking.
...
...
in the PR.
[3]: https://github.com/firecracker-microvm/firecracker/blob/main/CONTRIB …

test: sync fs before checking for output file

---

tests/integration_tests/build/test_coverage.py

Pass the `-Z` flag (fail on error) to the codecov uploader. According to
the docs, without this flag upload failures will be silently ignored
(why isn't this the default??) [1]. We can also see this from the logs,
which contain:
```
[2025-01-28T12:10:57.973Z] ['info'] Codecov will exit with status code
0. If you are expecting a non-zero exit code, please pass in the `-Z`
flag
```
The docs say that a long form `--fail-on-error` is available, but actually
it doesnt seem to work, so we have to use `-Z`.
example of it failing: https://buildkite.com/firecracker/firecracker-pr/builds/12416#0194ad35-9532-409d-b90b-1a05c3f80cc1
[1]: https://docs.codecov.com/docs/cli-options
...
... …

Fix(test): have codecov uploader exit with non-zero code on error

---

CHANGELOG.md
src/firecracker/examples/uffd/fault_all_handler.rs
src/firecracker/examples/uffd/uffd_utils.rs
src/firecracker/examples/uffd/valid_handler.rs
src/vmm/src/builder.rs
src/vmm/src/device_manager/persist.rs
src/vmm/src/devices/virtio/balloon/device.rs
src/vmm/src/devices/virtio/balloon/persist.rs
src/vmm/src/devices/virtio/balloon/util.rs
src/vmm/src/lib.rs
tests/integration_tests/functional/test_uffd.py

When the balloon inflates, and the guest gives us back some pages of memory, we need to free those pages. In booted VMs, we do this with madvise(MADV_DONTNEED), and in restored VMs we do it by MAP_FIXED-ing a new VMA on top of the range-to-free. This is because if guest memory is a MAP_PRIVATE of a memory file, madvise has no effect.
However, we also do this MAP_FIXED trick if the snapshot is restored with UFFD. In this case, its not needed (madvise works perfectly fine), and in fact, its wrong: If we map over the memory range, UFFD will not receive Remove events for the specified range.
Fix this by only using the mmap trick for file-based restored.
After doing this, fix our test uffd handler to actually handle remove events correctly (since it never received any before, we never noticed …

Fix UFFD handler never receiving `remove` messages when balloon device inflates

---

CHANGELOG.md
src/vmm/src/builder.rs
src/vmm/src/device_manager/mmio.rs
src/vmm/src/devices/virtio/block/vhost_user/device.rs
src/vmm/src/devices/virtio/block/virtio/io/mod.rs
src/vmm/src/devices/virtio/vhost_user.rs
src/vmm/src/lib.rs
src/vmm/src/persist.rs
src/vmm/src/resources.rs
src/vmm/src/test_utils/mod.rs
src/vmm/src/vstate/memory.rs
src/vmm/src/vstate/vm.rs

In this day and age, Firecracker supports theoretically 4 different ways of backing guest memory:
1. Normal MAP_ANONYMOUS | MAP_PRIVATE memory
2. memfd backed memory, mapped as shared
3. direct mapping of a snapshot file
4. MAP_ANONYMOUS again, but this time regions are described by snapshot file.
We have 3 different functions for creating these different backing stores, which then call each other and vm_memory's APIs. 
In light of https://github.com/firecracker-microvm/firecracker/issues/4522, which will add yet another way of backing virtual machine guests, this was starting to make my head hurt a bit.
Clean this up by consolidating these into just one function (`GuestMemoryExtensions::create`) that can be called with a description of the memory regions, plus an enum argument stating …

refactor: Unify methods of guest memory creation

---

tests/conftest.py

Save ssh key on test failure.
Since ssh keys are now generated on the test machine, we need to preserve the key in test artifacts to be able to debug a test failure.
in the PR.~~ …

test(conftest): save ssh key on test failure

---

src/vmm/src/vstate/memory.rs

Currently, when backing guest memory by memfd or when mmaping a snapshot file, we duplicate the file descriptor once per memslot. This is not necessary: KVM will happily accept the same fd into multiple memslots, and even rust-vmm supports APIs for this (by storing `Arc<File>` instead of just `File` in `FileOffset`, we can actually share the same `File` reference between multiple memory regions). So let's make use of this capability.
...
...
in the PR. …

fix: stop `dup(2)`-ing fds when setting up guest memory

---

docs/snapshotting/snapshot-support.md

Update the explanation text to refer to the "working?" column instead of some mystical "**all**", which doesnt exist. Also expand a bit on the explanation to make it clearer what works and what doesnt.
Closes #4912
(Am admittedly not 100% happy with what I came up with - if someone has ideas how to make the "same hardware" thingy clearer, please let me know!)
in the PR. …

doc: clarify cross-kernel snapshot compatibility

---

tests/integration_tests/functional/test_pause_resume.py

Test with 1 vCPU when running the KVMCLOCK_CTRL tests so we don't fail on intermittent issue with clock.
Confirmed with the KVMCLOCK_CTR call removed the test still fails after the update.
...
in the PR. …

fix: Rare failure in pause resume test

---

.buildkite/common.py

Backport changes to buildkite scripts:
- https://github.com/firecracker-microvm/firecracker/pull/4979
- https://github.com/firecracker-microvm/firecracker/pull/4965
Allows to simplify buildkite pipeline configuration.
in the PR.~~
- ~~[ ] …

[1.9] buildkite: backport step list as list/dict

---

src/vmm/src/devices/virtio/block/virtio/device.rs
src/vmm/src/devices/virtio/block/virtio/mod.rs
src/vmm/src/devices/virtio/block/virtio/persist.rs

Instead of using a vector of bytes as a config space it is better to use a proper type. This was already done in the virtio-net device, so just repeat same in block device.
Less manual bytes manipulations.
in the PR.
[2]: https://github.com/firecracker-microvm/firecracker/blob/main/docs/api-chang …

refactor(virtio-block): use a type for config space

---

tools/ab_test.py

m6g/5.10 block throughput results are no longer volatile, so we can reinsert it to the A/B testing.
in the PR.~~
- ~~[ ] I …

test(ab): unignore m6g/5.10 block

---

CHANGELOG.md
src/jailer/src/env.rs

Oh, here we go again. 
The jailer wishes to compute the CPU time it spents before exec-ing into
Firecracker, so that it can be passed to Firecracker's `parent-cpu-us`
flag and emitted as a metric.
The CLOCK_PROCESS_CPUTIME_ID is reset on every fork() call, so we need
to stitch together the different values from before the first fork, and
then between each consecutive fork. However, we also need to account for
the scenarios that we do not fork() at all (no daemonization).
Now, this all goes slightly wrong because we want to exclude the time
spent the call to Env::run() from the reported time (note that inside
the jailer, this is only the time spent parsing arguments, but if a user
ended up exec()-ing into the jailer, it would also include the time from
prior to calling exec(), which makes …

fix: compute jailer cpu time without underflow 

---

tests/integration_tests/functional/test_snapshot_basic.py

Right now the test would pass on stock AL kernels, because without the commits from 6.4 backported the CNTPCT_EL0 register won't even be included in the snapshot, and thus the assert is never reached.
Fix this by failing the test if the register isnt found.
...
...
in the PR.
[2]: …

fix: fail physical counter test if phy counter reg isn't in snapshot

---

tests/conftest.py
tests/host_tools/memory.py
tools/devtool

The access to the `firecracker_pid` property causes a read to the vm's
pid file. This means that in the scenario where the VM is already dead
by the time the monitor starts running, we won't get a `NoSuchProcess`
error, we potentially get a `FileNotFoundError` (if the jail is already
cleaned up). Thus, to avoid spurious failures, also catch
`FileNotFoundError`.
We leave the catch for `NoSuchProcess` error in case a VM exits between
reading the pid file and the call to the`psutils.Process` constructor
(race condition).
...
...
Certificate of Origin and signing off your …

test: catch correct exception in memory.py

---

src/vmm/src/vstate/vm/aarch64.rs
src/vmm/src/vstate/vm/mod.rs
src/vmm/src/vstate/vm/x86_64.rs

It is known that KVM_CREATE_VM occasionally fails with EINTR on heavily loaded machines
with many VMs.
The behavior itself that KVM_CREATE_VM can return EINTR is intentional. This is because
the KVM_CREATE_VM path includes mm_take_all_locks() that is CPU intensive and all CPU
intensive syscalls should check for pending signals and return EINTR immediately to allow
userland to remain interactive.
https://lists.nongnu.org/archive/html/qemu-devel/2014-01/msg01740.html
However, it is empirically confirmed that, even though there is no pending signal,
KVM_CREATE_VM returns EINTR.
https://lore.kernel.org/qemu-devel/8735e0s1zw.wl-maz@kernel.org/
To mitigate it, QEMU does an inifinite retry on EINTR that greatly improves reliabiliy:
- https://github.com/qemu/qemu/commit/94ccff133820552a859c0fb95e3 …

fix: Retry KVM_CREATE_VM on EINTR

---

CHANGELOG.md

No reason not to have it in CHANGELOG.
in the PR.~~
- ~~[ ] I have linked an issue to every new `TODO`.~~
[1]: …

chore: Add CHANGELOG entry for retrying KVM_CREATE_VM on EINTR

---

tests/framework/utils_cpuid.py
tests/integration_tests/functional/test_cpu_features_aarch64.py
tests/integration_tests/functional/test_cpu_features_host_vs_guest.py

Add ability to detect Graviton 4 (neoverse v2) and adjust host and guest feature checks with new features.
Graviton 4 on-boarding.
in the PR.
[3]: …

add initial Graviton 4 support

---

resources/overlay/usr/local/bin/fast_page_fault_helper.c
tests/conftest.py
tests/framework/utils.py
tests/framework/utils_uffd.py
tests/integration_tests/functional/test_uffd.py
tests/integration_tests/performance/test_huge_pages.py

Make page fault helper used in test_ept_violation_count actually cause page faults post restore. Currently, it is just crashing because the signal that is supposed to wake it up is actually killing it, due to no signal mask being installed.
Surrounded by a few refactors/fixes that came from me working on a page fault latency test before realizing that my approach was fundamentally flawed and I had to throw most of it away.
in the PR.
[Runbook for …

Fix fast_page_fault_helper crashing instead of causing page faults

---

Cargo.lock
src/cpu-template-helper/Cargo.toml
src/firecracker/Cargo.toml
src/firecracker/swagger/firecracker.yaml
src/jailer/Cargo.toml
src/rebase-snap/Cargo.toml
src/seccompiler/Cargo.toml
src/snapshot-editor/Cargo.toml

Generated running `./tools/bump-version.sh 1.12.0-dev`
in the PR.

chore: bump version to 1.12.0-dev

---

docs/snapshotting/snapshot-support.md

This patch clarifies that vsock connections are explicitly closed by a transport reset, in order to avoid the aforementioned issue. This doesn't impact listening sockets as they are able to accept new connections after restore.
The current documentation is not clear, mentioning that the device could break if active at time of snapshot. It also mentions that 
this is fixed by resetting the device at snapshot time, closing all open connections.
in the PR. …

doc(vsock): clarify vsock support on snapshot/restore

---

src/jailer/src/chroot.rs
src/jailer/src/env.rs
src/jailer/src/main.rs

- Clarify the reason for main function wrapping. This is mainly because I have this question each time I look at this code and each time need to discover the reason again.
- Use Rust feature to create `CStr` constants for paths avoiding runtime conversion.
Since Rust 1.77 `CStr` can be created with `c` prefix to string. Use this to simplify the code and remove runtime conversions.
in the PR. …

Jailer tweaks

---

CHANGELOG.md
docs/pvh.md
docs/rootfs-and-kernel-setup.md
src/vmm/src/arch/mod.rs
src/vmm/src/arch/x86_64/gdt.rs
src/vmm/src/arch/x86_64/layout.rs
src/vmm/src/arch/x86_64/mod.rs
src/vmm/src/arch/x86_64/regs.rs
src/vmm/src/builder.rs
src/vmm/src/vstate/vcpu/aarch64.rs
src/vmm/src/vstate/vcpu/mod.rs
src/vmm/src/vstate/vcpu/x86_64.rs
tests/framework/utils.py
tests/integration_tests/functional/test_api.py
tests/integration_tests/style/test_gitlint.py
tests/integration_tests/style/test_licenses.py

This is a rebased version of the feature/pvh feature branch contributed by @cperciva a while ago. 
In Linux guests supporting the PVH protocol (which is all linux guests compiled with `CONFIG_PVH=y`, a default), Firecracker will now boot guests using the PVH boot protocol. Our performance testing has shown there to be no difference in performance to the old way of booting using the Linux boot protocol.
Functionally, this means Firecracker can now boot FreeBSD guests (which only support the PVH boot protocol).
how they are …

Support for PVH boot protocol in Firecracker

---

src/jailer/src/env.rs

Allows the `jailer` to continue when files in `/sys/devices/system/cpu/cpuX/cache/indexY/` are missing.
Nested virtualization support was added on macOS Sequoia for Apple M3/M4 chips. When using `vz` with [Lima](https://lima-vm.io) a few of the CPU cache information files are missing, namely `size`, `coherency_line_size`, and `number_of_sets`. `firecracker` itself [handles if these files are missing](https://github.com/firecracker-microvm/firecracker/blob/b4cb9d311d026c5e45f13bd56089d2db024ec983/src/vmm/src/arch/aarch64/cache_info.rs#L101-L124), while the `jailer` doesn't . This patch passes whatever is present to the copied cache information, and allows `firecracker` to determine if it is valid or not.
By making this change, we are able to simplify our development environments …

fix: Allow jailer to continue with partial CPU cache info

---

src/vmm/src/arch/aarch64/vcpu.rs

The counter value observed in tests sometimes is a bit larger than 1000 cycles. Adjust max_value to accommodate this.
Less intermediate failures.
in the PR.
[3]: …

chore(aarch64): increase the max_value for timer reset test

---

tests/conftest.py
tests/framework/defs.py
tests/framework/utils.py
tests/integration_tests/functional/test_api.py
tests/integration_tests/functional/test_balloon.py

Fixes a handful of small issues discovered in integration tests, such as
- specific tests that were supposed to cover all io engines only testing the async engine
- tests not asserting error messages even though that was clearly the intention
- test duplicating functionality for which we have helper functions
in the PR.
[1]: …

Tiny integration test fixes to fill accidental gaps in coverage

---

tests/integration_tests/security/test_sec_audit.py
tools/devctr/Dockerfile
tools/devtool

This reverts commit d761b013db1caeec046b187927133b7fdac1375d. The output to stdout was fixed in cargo audit 0.21.2, so if we rebuild the docker container (needed to pick up the new cargo audit version, as currently we're on 0.21.0) the grep is no longer necessary.
In fact, the grep has broken this test in our nightly pipeline because it overwrites the return code of cargo audit itself, meaning the non-PR version of this test (which is supposed to fail if there exist any cargo audit warnings) was never failing.
how they …

Revert "fix: test_sec_audit: ignore cargo audit output"

---

docs/cpu_templates/cpuid-normalization.md

- Avoid confusion of CPUID.(EAX=0xB,ECX=1) normalization
- Simplify explanation of extended topology leaf
See commit messages.
in the PR.
- ~~[ ] I have linked an issue to every new `TODO`.~~
___________________________________________________________________ …

fix(doc): Update normalization for extended topology leaf

---

.buildkite/pipeline_pr.py
src/vmm/src/arch/x86_64/interrupts.rs
src/vmm/src/dumbo/pdu/ethernet.rs
src/vmm/src/utils/byte_order.rs
tests/integration_tests/test_kani.py

Since 0.58.0 kani gets stuck unwinding loops in the dumbo proofs. The exact loops were the ones in the `byte_order` module. We've previously seen this with a subset of the `byte_order` functions, which is why some of them were already stubbed out in kani. However, instead of just doing more stubbing, let's just eliminate the loops. The were just a handrolled memcpy (the reason we need these convoluted byte_order functions in the first place is that the stdlib functions cannot deal with buffers that are "too small", while we for some reason want to support that).
...
... …

kani: fix infinite loop unwinding in dumbo harnesses

---

CHANGELOG.md
src/vmm/src/vmm_config/boot_source.rs
tests/integration_tests/functional/test_api.py

Instead of sleeping for 2 seconds to wait for booting, add a network device and wait for ssh availability (happens automatically in .start()). Use mark_killed() to assert that Firecracker exited instead of "waitpid". Using `waitpid(2)` here is wrong, because it only works on child processes, and Firecracker is no child of the pytest process (it is daemonized, for starters). The reason we never caught this being broken is because the test also simply ignores all exceptions raised.
But there's more issues here: The test never caused _killed to be set to `True`, so if Firecracker really did exit, then we would have been seeing intermittent failures during microvm teardown (as Microvm.kill() asserts that the process is still alive if _killed is False). In fact, our guest kernels do not have …

test: Modernize test_send_ctrl_alt_del

---

docs/cpu_templates/cpuid-normalization.md
src/vmm/src/cpu_config/x86_64/cpuid/amd/normalize.rs
src/vmm/src/cpu_config/x86_64/cpuid/intel/normalize.rs
src/vmm/src/cpu_config/x86_64/cpuid/normalize.rs
tests/integration_tests/functional/test_cpu_features_host_vs_guest.py
tests/integration_tests/functional/test_cpu_features_x86_64.py
tests/integration_tests/functional/test_cpu_template_helper.py
tests/integration_tests/security/test_vulnerabilities.py

- Do refactoring of the existing CPUID normalization in the first 11 commits (not related to Intel Sapphire Rapids support, so I can open another PR for this but this PR touches the same doc.)
- Add CPUID leaf 0x1F normalization
- Make functional integration tests support Intel Sapphire Rapids
Intel Sapphire Rapids reports more CPUID leaves (0x1C - 0x1F) than Intel Ice Lake:
- 0x1C: Last Branch Records Information Leaf (filled with 0 since not supported in guest)
- 0x1D: Tile Information Main Leaf (passed through since it's for Intel AMX)
- 0x1E: TMUL Information Main Leaf (passed through since it's for Intel AMX)
- 0x1F: V2 Extended Topology Enumeration Leaf (same contents with leaf 0xB since leaf 0x1F is a preferred superset to leaf 0xB)
By submitting this pull request, I confirm that …

Functional support of Intel Sapphire Rapids

---

tests/data/cpu_template_helper/fingerprint_AMD_MILAN_5.10host.json
tests/data/cpu_template_helper/fingerprint_AMD_MILAN_6.1host.json
tests/data/cpu_template_helper/fingerprint_INTEL_CASCADELAKE_5.10host.json
tests/data/cpu_template_helper/fingerprint_INTEL_CASCADELAKE_6.1host.json
tests/data/cpu_template_helper/fingerprint_INTEL_ICELAKE_5.10host.json
tests/data/cpu_template_helper/fingerprint_INTEL_ICELAKE_6.1host.json
tests/data/cpu_template_helper/fingerprint_INTEL_SKYLAKE_5.10host.json
tests/data/cpu_template_helper/fingerprint_INTEL_SKYLAKE_6.1host.json

We changed to calculate the right-shift bits to address socket ID based on max number of vCPUs, but I forgot to update fingerprints :(
Fixes: 62207118 ("fix(vmm): Calc right-shift bits to address socket ID")
...
...
in the PR.~~
- ~~[ ] …

chore: Regather fingerprints for x86-64 instance types

---

.cargo/audit.toml
Cargo.lock

Fixes for `cargo audit`. We backport e7f60511f761e4c622ee0609a71c7b76d3925b6c for ignoring `paste` issue and also run `cargo update` to update `hashbrown` dev dependency.
in the PR.
[3]: …

Fix audit v1.10

---

.cargo/audit.toml

Backport #5081 
Fix cargo audit
in the PR.

[v1.11] ignore paste in cargo audit

---

docs/snapshotting/snapshot-support.md

We fixed the arm register length limitation in #3787 but never removed this note from the doc.
It is time to update the doc.
in the PR.
[3]: https://github.com/firecracker-microvm/firecracker/blob/main/CO …

chore(doc): remove arm64 snapshot reg length limitation

---

CHANGELOG.md
CREDITS.md
docs/RELEASE_POLICY.md
docs/getting-started.md
docs/kernel-policy.md
tools/release-notes.py

1. Make quickstart guide detect the right CI artifacts depending on the latest release
- I've tested it locally to make sure it works
3. Update and improve kernel-policy.md
4. Fix release note script
5. Update release policy with 1.11
6. Move PVH changelog to right section
7. Update the credits file
1. I needed to update the quickstart guide and thought it'd be best to just have it detect the latest versions as we do for the bnaries
2. There were still references to 4.14
3. the script wasn't working
4. it's now being released, wohoo
5. it was marked as 1.11
6. for the glory
Certificate of Origin and signing off your commits, please …

Post-release doc updates and other miscellanea

---

CHANGELOG.md
src/firecracker/examples/uffd/uffd_utils.rs
src/vmm/src/persist.rs
src/vmm/src/vmm_config/machine_config.rs

* update `page_size_kib` name to the more accurate `page_size`, since it's actually in bytes, not KiB.
...
We leave the old page_size_kib field in there, but mark it as deprecated to avoid any Firecracker code from accidentally using it (and update everything on the Firecracker side to be called page_size instead of page_size_kib). This way we're backward compatible (and can remove the wrongly named field in 2.0), but have correctly named variables in the code base at least.
...
how they are solving the problem in a clear …

fix: rename page_size_kib to page_size

---

src/firecracker/examples/uffd/uffd_utils.rs

Add logic to our UFFD handlers to retry the negotiation with Firecracker up to 5 times before giving up. This helps making them (slightly) more robust. Also, we add some logging in the receive logic so that we can inspect failures post-mortem.
According to our UFFD protocol, UFFD handlers negotiate with Firecracker during initialization and wait for it to send over a UDS the UFFD file descriptor along with the memory mappings that are being handled over the UFFD.
During this handshake, our (testing only/not production grade) UFFD handlers issue what essentially is a `recvmsg` that should return with the UFFD fd and the mappings. Some times instead of the file descriptor, the `recvmsg` wrapper returns a `None` value for the file descriptor. When this happens, the UFFD handler crashes and …

Try to make UFFD handlers more robust

---

tests/framework/utils_cpu_templates.py
tests/integration_tests/functional/test_snapshot_basic.py

Update `test_5_snapshots` test to test with cpu_templates as well. Also enable sve + pac template for G4.
We did not have snapshot tests with cpu templates.
in the PR.
[3]: …

Snap restore test with templates

---

tests/integration_tests/functional/test_cpu_features_aarch64.py

Add a case for G4 with sve+pac template to the guest cpu feature check test.
Fixes test for G4 with sve+pac template.
in the PR.
[3]: https://github.com/firecracker-microvm/firecracker/blob/main/CONTRIBUT …

adjust G4 guest features with sve+pac cpu template

---

src/firecracker/examples/uffd/uffd_utils.rs

Add a small timeout between retries during UFFD negotiation between handler and Firecracker.
During fc8517044adc, we changed the UFFD handler logic to retry the negotiation with Firecracker up to 5 times in case of failures. Retries happen immediately.
in the PR.
[2]: …

Sleep between retries during UFFD handler negotiation

---

tests/integration_tests/security/test_sec_audit.py
tools/devtool

This reverts commit d761b013db1caeec046b187927133b7fdac1375d. The output to stdout was fixed in cargo audit 0.21.2, so if we rebuild the docker container the grep is no longer necessary.
In fact, the grep has broken this test in our nightly pipeline because it overwrites the return code of cargo audit itself, meaning the non-PR version of this test (which is supposed to fail if there exist any cargo audit warnings) was never failing.
(cherry picked from commit 1d98a21e087aa4f188f2d6e665b54c6962569199)
...
... …

[1.11 Backport] Revert "fix: test_sec_audit: ignore cargo audit output"

---

tests/integration_tests/security/test_sec_audit.py

This reverts commit https://github.com/firecracker-microvm/firecracker/commit/d761b013db1caeec046b187927133b7fdac1375d. The output
to stdout was fixed in cargo audit 0.21.2, so if we rebuild the docker
container the grep is no longer necessary.
In fact, the grep has broken this test in our nightly pipeline because
it overwrites the return code of cargo audit itself, meaning the non-PR
version of this test (which is supposed to fail if there exist any cargo
audit warnings) was never failing.
(cherry picked from commit https://github.com/firecracker-microvm/firecracker/commit/1d98a21e087aa4f188f2d6e665b54c6962569199)
the terms of the Apache 2.0 license. For more …

[1.10 Backport] Revert "fix: test_sec_audit: ignore cargo audit output"

---

docs/kernel-policy.md

Clarify in the documentation that the kernel configurations we keep in our repo are meant to be used with kernels provided by Amazon Linux and that we don't guarantee that they can be used to build kernels from upstream Linux.
We keep in the repo the kernel configurations from which we build the kernel images we use in our CI pipelines. However, we don't mention what kernel sources we use to build these kernel images.
Fixes #4881
in the PR.
[Runbook for …

doc: clarify kernel configuration usage in our repo

---

.buildkite/common.py
.buildkite/pipeline_pr.py
src/vmm/src/arch/x86_64/interrupts.rs
src/vmm/src/dumbo/pdu/ethernet.rs
src/vmm/src/utils/byte_order.rs
tests/integration_tests/test_kani.py

Backport https://github.com/firecracker-microvm/firecracker/pull/5069 and https://github.com/firecracker-microvm/firecracker/pull/5078 .
Bumping devctr version (https://github.com/firecracker-microvm/firecracker/pull/5100/commits/75b1a1d2cff469e4dab2a6734711f444df5ef914) brought Kani timeouts that we observed in main.
in the PR.~~
- ~~[ ] I have mentioned all user-facing …

[1.11] backport Kani fixes

---

src/firecracker/src/api_server/request/machine_configuration.rs
src/vmm/src/arch/aarch64/fdt.rs
src/vmm/src/arch/aarch64/mod.rs
src/vmm/src/arch/x86_64/mod.rs
src/vmm/src/builder.rs
src/vmm/src/device_manager/mmio.rs
src/vmm/src/devices/virtio/vsock/event_handler.rs
src/vmm/src/lib.rs
src/vmm/src/resources.rs
src/vmm/src/rpc_interface.rs
src/vmm/src/utils/mod.rs
src/vmm/src/vstate/memory.rs
src/vmm/src/vstate/vcpu.rs
src/vmm/src/vstate/vm.rs

A collection of cleanups I accumulated on a local branch while prototyping for #4522. Mainly
- Clean up error types in builder.rs slightly to avoid a lot of unsightly .map_err calls
- Clean up a lot of unnecessary generics in fdt.rs
- Add a constant to make our left shifts by 20 less mysterious.
in the PR.
[1]: …

Elimination of unneeded generics and lots of `.map_err()`

---

src/vmm/src/arch/aarch64/fdt.rs
src/vmm/src/arch/aarch64/mod.rs
src/vmm/src/arch/mod.rs
src/vmm/src/arch/x86_64/mod.rs
src/vmm/src/builder.rs
src/vmm/src/cpu_config/aarch64/mod.rs
src/vmm/src/cpu_config/x86_64/mod.rs
src/vmm/src/device_manager/persist.rs
src/vmm/src/devices/virtio/test_utils.rs
src/vmm/src/gdb/arch/aarch64.rs
src/vmm/src/gdb/target.rs
src/vmm/src/initrd.rs
src/vmm/src/lib.rs
src/vmm/src/persist.rs
src/vmm/src/resources.rs
src/vmm/src/utils/mod.rs
src/vmm/src/vstate/vcpu.rs

This is another attempt at fixing #4547. 
- Move architecture specific parts from `builder.rs` into `arch` modules. 
- Do slight refactoring on top in the `arch` modules.
Less arch specific mess in the codebase.
Fixes: #4411
Previous attempt was: #4910
in the PR.
[2]: …

Builder refactor

---

src/vmm/src/arch/aarch64/mod.rs
src/vmm/src/arch/aarch64/regs.rs
src/vmm/src/arch/aarch64/vcpu.rs
src/vmm/src/builder.rs
src/vmm/src/persist.rs

A follow up to #5098 I volunteered to do during review
in the PR.

Eliminate free functions in arch::aarch64::vcpu

---

tests/conftest.py
tests/framework/microvm.py
tests/framework/properties.py
tests/host_tools/fcmetrics.py
tests/integration_tests/performance/test_boottime.py

When emitting metrics for host kernels greater than 6.12 (latest LTS) we will report them as "next" kernels to make them easier to track in our dashboards
...
...
in the PR.
[3]: …

tests: Report kernels newer than 6.12 as next

---

tests/conftest.py

Move instead of copying VM artifacts (like mem snapshot files).
This is to keep free space in the /srv filesystem.
in the PR.~~
- ~~[ ] I …

test(conftest): move (not copy) vm artifacts

---

resources/hiding_ci/build_and_install_kernel.sh
tests/integration_tests/performance/test_snapshot_ab.py

Moved away from using dir stacks for navigation.
Skipped a performance test with large pages on ARM
...
in the PR.

Tidyup on Hiding CI

---

tests/integration_tests/functional/test_cpu_features_host_vs_guest.py

We disabled WAITPKG intentionally since it can put a physical processor into an implementation-depedent optimized state. So it should not exist in guest.
in the PR.~~
[Runbook for …

test: Add waitpkg to host-minus-guest features

---

.buildkite/pipeline_pr.py
tests/integration_tests/performance/test_snapshot_ab.py

Skip some more huge pages tests on ARM instances on our newer kernel.
Run our kernel build as part of our nightly pipeline to ensure that it's passing
...
...
in the PR.
[3]: …

Secret Hiding: Skip more huge page tests and run build nightly

---

CHANGELOG.md
src/vmm/src/persist.rs

Do not close the UFFD UDS socket.
We prevent Rust from closing the socket file descriptor to avoid a potential race condition between the mappings message and the connection shutdown.  If the latter arrives at the UFFD handler first, the handler never sees the mappings. No meaningful test is possible due to the rare nature of the issue.
in the PR.~~
- ~~[ ] If a specific issue …

fix(vmm/persist): do not close uffd socket

---

tests/framework/microvm.py
tests/framework/utils_uffd.py
tests/integration_tests/functional/test_uffd.py
tests/integration_tests/performance/test_huge_pages.py

It turns out that some of our snapshot tests are not exactly exemplary at cleaning up snapshot memory files after they're done. This is partly because Microvm.restore_from_snapshot was largely oblivious to the fact that if a snapshot is uffd-restored, it doesn't need to be copied into the jail _again_ for mmaping that will never happen, and also due to me messing up the build_n_from_snapshot function and not cleaning up snapshots in "incremental" mode.
in …

fix(test): cleanup snapshot files better

---

Cargo.lock
src/firecracker/examples/seccomp/jailer.rs
src/firecracker/examples/seccomp/panic.rs
src/firecracker/src/seccomp.rs
src/seccompiler/Cargo.toml
src/seccompiler/src/lib.rs
src/vmm/Cargo.toml
src/vmm/src/mmds/token.rs
src/vmm/src/seccomp.rs
src/vmm/src/snapshot/mod.rs

Follow the official migration guide for upgrading with serde support,
described in [1]
[1]: https://github.com/bincode-org/bincode/blob/trunk/docs/migration_guide.md#migrating-with-serde
in the PR.
[3]: …

chore: update bincode to 2.0

---

src/vmm/benches/memory_access.rs
src/vmm/src/acpi/mod.rs
src/vmm/src/arch/aarch64/kvm.rs
src/vmm/src/arch/aarch64/mod.rs
src/vmm/src/arch/aarch64/vcpu.rs
src/vmm/src/arch/aarch64/vm.rs
src/vmm/src/arch/x86_64/kvm.rs
src/vmm/src/arch/x86_64/mod.rs
src/vmm/src/arch/x86_64/vcpu.rs
src/vmm/src/arch/x86_64/vm.rs
src/vmm/src/builder.rs
src/vmm/src/device_manager/legacy.rs
src/vmm/src/device_manager/mmio.rs
src/vmm/src/device_manager/persist.rs
src/vmm/src/devices/virtio/block/vhost_user/device.rs
src/vmm/src/devices/virtio/block/virtio/io/mod.rs
src/vmm/src/devices/virtio/persist.rs
src/vmm/src/devices/virtio/vhost_user.rs
src/vmm/src/gdb/arch/aarch64.rs
src/vmm/src/gdb/target.rs
src/vmm/src/lib.rs
src/vmm/src/persist.rs
src/vmm/src/resources.rs
src/vmm/src/test_utils/mod.rs
src/vmm/src/vstate/kvm.rs
src/vmm/src/vstate/memory.rs
src/vmm/src/vstate/vcpu.rs
src/vmm/src/vstate/vm.rs
src/vmm/tests/integration_tests.rs

Move the `GuestMemoryMmap` that keeps track of a Firecracker VM's memory regions into `struct Vm`, from `struct Vmm`, and then update some related functionality (such as various snapshot helper functions) to operate on `struct Vm` instead of `struct Vmm`.
So far, Firecracker always dealt with a single collection of homogeneous guest memory regions. However, #5108 introduces a second type of memory regions, which makes the set of memory regions heterogeneous, and other features, such as virtio-pmem support, will come with similar "special" memory regions. By moving the guest memory management into `Vm`, we encapsule this heterogeneity and allow incremental building of guest memory configuration.
Admittedly, there's nothing _right now_ that would benefit from this refactor (it doesn't even …

Refactor: Move `GuestMemoryMmap` into `struct Vm`

---

.buildkite/pipeline_pr.py
resources/hiding_ci/patches/0002-mm-introduce-AS_NO_DIRECT_MAP.patch
resources/hiding_ci/patches/0003-KVM-guest_memfd-Add-flag-to-remove-from-direct-map.patch

Add an updated version of relevant patches from my v4 direct map removal
series [1]. Updated here means
- Drop all selftests patches, as they are irrelevant for our CI
- Address comments from David about squashing commits
- Rebase on top of Fuad's v7
[1]: https://lore.kernel.org/kvm/20250221160728.1584559-1-roypat@amazon.co.uk/
...
...
in the PR.
integration …

add direct map removal patches to secret hiding CI

---

.buildkite/pipeline_perf.py

Move the network latency test onto the same worker as the throughput test, and split the snapshot tests across two workers, to optimize pipeline runtime by loading all workers roughly equally.
in the PR. …

CI: Reshuffle perf steps a bit to better utilize workers

---

CHANGELOG.md
src/firecracker/src/api_server/mod.rs
src/firecracker/src/api_server_adapter.rs

- Log API socket creation and API server start.
- Emit startup metrics after server start.
We found such logs useful to debug Firecracker startup issues.
The startup time metrics were recorded before applying seccomp filter and starting the API server.
in the PR.~~
- ~~[ ] When making API changes, I have …

Log API socket creation and API server start + Correct startup time metrics timing

---

CHANGELOG.md
src/vmm/src/persist.rs

To support the snapshot feature for Intel AMX, we changed to use `Xsave` struct instead of `kvm_xsave` struct. We should have bumped the snapshot version.
Fixes: 803140d8249d ("feat(vmm): Use structs and methods for KVM_CAP_XSAVE2")
in the PR.~~
- …

fix(vmm): Bump snapshot version

---

.buildkite/common.py
README.md

Add m8g.metal-24/48xl instances to the instances list used by bk pipelines.
It is time to test Graviton4 in all pipelines.
in the PR.
[3]: https://github.com/firecracker-microvm/firecracker/blob/main/CONT …

chore: add Graviton4 instances to the bk pipelines

---

tools/devtool

If something goes wrong during aws s3 cp, exit early with an error message instead of quietly trying to soldier on. A common(-ish) cause of something going wrong here is having installed the aws cli for the wrong CPU architecture (e.g. x86 awscli on ARM64), as the awscli installer apparently doesnt not check the architecture, and its easy to copy the wrong command from the website.
...
...
in the PR.
integration …

fix: dont fail silently on awscli errors during artifact setup

---

resources/hiding_ci/build_and_install_kernel.sh

Previously this would fail on x86 as we set -e. By setting the || echo this means the script will continue. The grubby step next will fail if it failed to find the image.
...
...
in the PR.
[3]: …

Fix SH install script exiting too early

---

src/vmm/src/devices/virtio/block/virtio/device.rs
src/vmm/src/devices/virtio/block/virtio/io/async_io.rs
src/vmm/src/devices/virtio/block/virtio/io/mod.rs
src/vmm/src/devices/virtio/block/virtio/request.rs

These generic type parameters were leaking out from the io_uring module. Having a generic ring structure in the io_uring module: makes sense. Having a generic file engine: probably makes less sense (what are we ever gonna process in there except block io requests?). Just replace all instances of `T` in the virtio module with `PendingRequest` - that's what it all ended up getting monomorphized to anyway.
...
...
in the PR. …

refactor: de-generify async_io engine

---

src/vmm/src/rate_limiter/mod.rs
tests/integration_tests/functional/test_balloon.py

Add more print info to the rss check for balloon test and define slightly bigger rate limiter refill interval for unit tests.
Less intermediate failures and simpler debugging.
in the PR.
[3]: …

Minor test fixes

---

tests/framework/utils.py

`Python psutil.Process.cpu_affinity()` returns the current CPU affinity as a list of integers. So we don't need to have our own CPU affinity getter implementation.
```
$ docker run --cpuset-cpus 1,3,5-8 -it python:3 /bin/bash
root@435fd3d38bed:/# pip3 install psutil
Collecting psutil
...
Successfully installed psutil-7.0.0
...
root@435fd3d38bed:/# python3
Python 3.13.3 (main, Apr  9 2025, 00:27:54) [GCC 12.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import psutil
>>> psutil.Process().cpu_affinity()
[1, 3, 5, 6, 7, 8]
>>> 
```
Certificate of Origin and signing off your commits, please …

Eliminate homemade CPU affinity getter

---

tests/README.md
tools/devtool

- Do not silently soldier on when firecracker compilation fails as part of `devtool test`
- suggest passing --no-build together with --ab when doing manual A/B tests
in the PR.
[3]: …

Fix two annoyances with compiling Firecracker through devtool/test

---

CHANGELOG.md
docs/snapshotting/snapshot-support.md
src/vmm/src/rpc_interface.rs

Declare full snapshots as fully supported. Diff snapshots remain in development preview status, as we wait to see how these will play with secret hiding.
in the PR.
[3]: …

Move snapshot feature to GA

---

tests/integration_tests/functional/test_balloon.py

- Update the way we wait for the rss to stabilize in the balloon tests
Fix intermittent failures.
in the PR.

ci: intermittent failures fixes

---

CHANGELOG.md
src/vmm/src/arch/aarch64/vcpu.rs
src/vmm/src/builder.rs
src/vmm/src/persist.rs
tests/integration_tests/functional/test_steal_time.py

Opening this PR as a draft as we continue working on this issue to add steal time support for ARM. Please see below for the changes we have implemented so far.
- Added PVTime struct in `src/vmm/src/arch/aarch64/pvtime/mod.rs` that allocates and stores per-vCPU stolen_time regions
- It offers a `new` constructor to create the device (allocating system memory and storing regions per vcpu), and `register_vcpu` which attempts to use `kvm_set_device_attr` to register the corresponding IPA for a vcpu
- Created a function `setup_pv_time` in `src/vmm/src/builder.rs` which is invoked in `build_microvm_for_boot`
- Checks if PVTime is supported using `kvm_has_device_attr`
- Creates a PVTime device
- Iterates over vcpu fd's to register their IPAs for steal_time struct
- Started using debug/info logs …

Add Steal Time support in ARM

---

src/jailer/src/cgroup.rs
src/jailer/src/env.rs
src/vmm/src/signal_handler.rs
tests/integration_tests/functional/test_balloon.py
tests/integration_tests/functional/test_net.py
tests/integration_tests/functional/test_shut_down.py
tests/integration_tests/functional/test_steal_time.py

Fixes:
- signal unit test that was failing due to the async signal delivery (supposedly) by adding a sleep
- jailer unit test that was crashing because the node was already existing by using a tmp directory
- tap offload unit test that was failing because the file read was written async by adding a sleep
- balloon unit test that was failing because the stats weren't refreshed by adding a sleep to ensure they get refreshed
I've gone through the recent flaky test failures and this is a proposed fix. In most cases, the fix is to add a time interval to break an async race condition for which we have no better way to resolve.
Certificate …

Miscellaneous flaky test fixes

---

tests/integration_tests/performance/test_boottime.py
tools/ab_test.py

- Emit `systemd-analyze` output as metrics.
- Emit already collected, but not emitted metrics
Better boot time test visibility.
in the PR.
[3]: …

More boot time metrics

---

tests/README.md
tools/ab_test.py

Fix A/B-test ignore list not working due to recently introduced "dimension simplification", which results in a lot of noise due to the ignore of tcp throughput tests on amd not working. While we're here, do a tiny documentation fix, and extend the ignore list.
in the PR.
[2]: …

Small Fixes to A/B-Test scripts

---

CHANGELOG.md
src/vmm/src/resources.rs

When starting firecracker without the API server and configuring it through a config files, specifying a custom cpu template requires writing this cpu template into a separate json file, and then passing the path to this separate json file in the config json file. This is a bit silly, since everything is just json. So additionally allow just directly specifying the custom cpu template inside the config file.
...
...
in the PR. …

allow specifying custom cpu template inline in config json

---

resources/hiding_ci/build_and_install_kernel.sh

The install script on amazon linux isn't storing the .config in our boot directory by default. This is causing our spectre checker script which relies on the config. Updated our script to move this if it has't been done so already.
...
...
in the PR.
[2]: …

Hiding CI install script store kernel config in boot

---

CHANGELOG.md
docs/RELEASE_POLICY.md

- Update CHANGELOG with Intel Sapphire Rapids and ARM Graviton4 support declaration.
- Update the release status table
We'll make v1.12.0 release tomorrow since v1.10.0 is going to reach EOL tomorrow.
in the PR.~~ …

chore(release): Prepare for v1.12.0 release

---

.github/workflows/trigger_ab_tests.yml

We had only enabled the workflow for main and release branches.
in the PR.

test: run A/B tests for feature branches

---

tools/ab_test.py

`dimension_set` is a frozenset of tuples, not a dictionary, so no need
to call .items() (which in fact doesnt even exist), and converting a
dictionary comprehention expresson into a dictionary with an explicit
call to dict() is also unnecessary.
...
in the PR.
[2]: …

fix(ab): do not crash during printing of dimensions

---

tests/conftest.py

During pytest teardown, we explicitly kill all microvms that a test might have left behind. We do this by reading Firecracker's pid file and then SIGKILL-ing the process. However, if a test fails, we also try to upload its entire jail to S3 as buildkite artifacts, for post-mortem analysis. Here, we are moving instead of copying files, to save on disk space. This is a problem though, as the pid file is inside the jail, and this moving happens _before_ the call to .kill() (and has to happen before, as killing a VM cleans up its jail). This leads to duplicate pytest errors every time a test fails: One for the actual failure, and then a second failure from Microvm.kill() due to the pid file not being found.
Fix this by reverting the commit that changed the copy to a move - we copy outside of …

fix: do not error during pytest teardown after test failure

---

tools/release.sh

- Enable tracing mode (`set -x`) for the future debugability
- Fix release.sh by using upper case custom CPU template file names
The release script failed.
This will be forward-ported to the main branch after the release.
in the PR.~~
- …

Enable tracing mode for release.sh and fix release.sh

---

src/vmm/src/builder.rs

By using a MaybeBounce with N=0 we are allocating a bounce buffer that matches exactly the number of bytes that need to be copied into guest memory, e.g. the size of the kernel file. This is fairly expensive performance wise, and the spike in memory usage from the firecracker process is also unwanted. Thus, just use a 4096 byte fixed size buffer through which we repeatedly read+memcpy. This has slightly better performance (10ms faster for cold boots) and makes Firecracker's memory usage during InstanceStart go back into its O(1) bound.
...
... …

secret_freedom: Use fixed size bounce buffer for loading kernel

---

.buildkite/common.py

Add `--parallelism` option to specify how much instances of tests to run.
It is useful to run multiple test instances for testing purposes.
in the PR.
[3]: …

feat(ci): add paralellism option to bk pipelines

---

.buildkite/pipeline_cross.py
tests/conftest.py
tests/framework/ab_test.py
tests/framework/defs.py
tests/host_tools/fcmetrics.py
tests/host_tools/metrics.py
tests/integration_tests/build/test_seccomp_no_redundant_rules.py
tests/integration_tests/performance/test_block_ab.py
tests/integration_tests/performance/test_network_ab.py
tests/integration_tests/performance/test_vsock_ab.py
tools/ab_test.py
tools/devtool

Save metrics and performance artifacts(logs/json files) we get from test into `test_results` for further processing.
Allow to change the results directory for CI.
Previously the content of `test_results` looked like this:
```
test_results
- test-report.json 
```
Now it will be:
```
test_results
- test-report.json
- test_boottime
- 'test_boottime[vmlinux-5.10.233-1-128]'
- metrics.json
- other test related files
- ...
```
If the CI is run in BK the `test_results` directory will be archived into `test_results/data.tar.gz`
Currently the only output of tests we have are emitted metrics. This means we discard a lot of data we get during test runs (mainly perf tests). This is turn makes it more difficult to analyze performance of Firecracker to the point where we have to use custom scripts to …

Save tests metrics and performance artifacts

---

tests/conftest.py

Dump VM metrics on test failure.
This is to have latest VM metrics available when analysing failures.
in the PR.~~
- ~~[ ] I have tested all …

test(conftest): dump VM metrics on test failure

---

tests/integration_tests/performance/test_boottime.py

Make the boot time perf test use `guest_memory` as a dimension instead of `guest_mem_mib`.
Only boot time perf test uses `guest_mem_mib` as a dimension while all the others use `guest_memory` via `vm.dimensions`, which makes it a pain when treating metrics data with pandas DataFrame.
in the PR.~~
- ~~[ ] If a …

chore(test): Unify guest memory dimension

---

tests/integration_tests/performance/test_block_ab.py

Don't store latency info for `libaio` fio backend
Latency for block device only makes sence if we use `psync` fio backend.
in the PR.
[3]: https://github.com/firecracker-microvm/firecracker/blob/main/CONT …

chore(ci): don't store latency for libaio

---

tests/integration_tests/functional/test_steal_time.py

Split the double assertion in `test_pvtime_snapshot` in two separate ones.
`test_pvtime_snapshot` checks that steal time reporting mechanism works on snapshotted microVMs. This includes two checks; first that the old steal time values are saved and restored correctly through snapshots and second that steal time keeps increasing in microVMs resumed from a snapshot.
The test fails intermittently, but we are not sure which of the two invariants causes it to fail because we are checking both in the same assertion
how they are …

Split post-snapshot checks for steal time test

---

docs/network-setup.md

Remove instruction for nameserver setup via boot_args.
Related issue: https://github.com/firecracker-microvm/firecracker/issues/5172 .
It does not work with our current rootfs.
in the PR.
~~- [ ] I have mentioned all user-facing changes in `CHANGELOG.md`.~~
~~- [ ] When making API changes, I have followed the
~~- [ ] I have tested all new and …

doc(net): remove instruction for nameserver setup via boot_args

---

tests/conftest.py

This change adds a new set of dimensions with just the test name so that we reduce it to a few hundreds and are able to plot them (CW limit is 500).
The current metric dimensions are so that we have 13k+ different sets of dimensions for each metric, which makes it impossible to plot in CloudWatch.
in the PR.
[1]: …

chore(metric): add per-test metric dimension for coarse grained metrics

---

tests/framework/microvm.py
tests/framework/utils_uffd.py
tests/host_tools/fcmetrics.py
tests/integration_tests/functional/test_uffd.py
tests/integration_tests/performance/test_huge_pages.py

By not killing the uffd handler, we are leaking the resources associated
with the uffd handler, which can be undesirable and cose gradual
slowdown in in snapshot performance tests that restore snapshots using
uffd in a loop.
in the PR.
[2]: …

fix(test): kill uffd handler when microvm gets killed 

---

tests/host_tools/proc.py

This small PR resolves the regex library warnings showing in Python3.13:
```python
DeprecationWarning: 'count' is passed as positional argument
```
in the PR.
[3]: …

fix(test): resolve regex library warnings

---

tests/integration_tests/functional/test_cpu_features_x86_64.py

This small PR evaluates the displays the cpu template name in the test skip message.
in the PR.

test: display the cpu template name

---

tests/framework/microvm.py
tests/pyproject.toml

In Microvm.kill() we have a sanity check for ensuring the firecracker
process wrote the correct pid to its pidfile: We ps | grep for the
jailer id of the supposedly dead firecracker process and see if any
process that has "fircracker" somewhere in its argv is using it (with
the somewhat reasonable assumption that this would be exactly the
firecracker process we just tried to kill). Howver, if the firecracker
process isnt daemonized, then we spawn it under `screen`, and now we
have two processes that contain both the jailer id and the name
"firecracker" in its argv, because screen fork()s into firecracker in
this case. Now if we kill firecracker, screen might stick around a bit
longer (because we only explicitly wait for firecracker to terminate),
and the sanity check might incorrectly …

test: fix false positive in Microvm.kill check for correct pid 

---

tests/framework/http_api.py
tests/framework/microvm.py
tests/framework/utils.py
tests/integration_tests/functional/test_api_server.py
tests/integration_tests/functional/test_cmd_line_parameters.py
tests/integration_tests/functional/test_cmd_line_start.py

Sometimes, we intermittently see `ConnectionRefused` errors when doing
http requests to the firecracker API in integration tests. Have the test
framework dump relevant logs in these cases.
...
...
in the PR.
[2]: …

test: dump debug information if http request to firecracker fails

---

src/vmm/src/cpu_config/x86_64/cpuid/normalize.rs

Prints a warning message instead of erroring out on unexpected subleaf detected for CPUID leaf 0xB.
Fixes #5213
in the PR.~~
- ~~[ ] I have linked an issue to every new `TODO`.~~ …

vmm: warn instead of bailing out on unexpected subleaf for leaf 0xB.

---

resources/overlay/usr/local/bin/init.c
resources/rebuild.sh
tests/integration_tests/performance/test_boottime.py

Update the init.c and initramfs values for the MMIO region of the boot timer device. Also, add a functional test that runs during CI PR tests and makes sure the boot timer works.
When we re-arranged the MMIO address space in commit 9a165d17f1ba (arch: define 64-bit capable MMIO memory regions) we moved the MMIO region of the boot timer device for x86 systems, but we didn't update the init scripts that hardcode it and use it to report boot time timestamp back to Firecracker.
how they are solving the problem in a clear and …

fix: boottimer device MMIO address

---

src/vmm/benches/block_request.rs
src/vmm/benches/queue.rs
src/vmm/src/device_manager/mmio.rs
src/vmm/src/devices/mod.rs
src/vmm/src/devices/virtio/balloon/device.rs
src/vmm/src/devices/virtio/balloon/mod.rs
src/vmm/src/devices/virtio/block/device.rs
src/vmm/src/devices/virtio/block/virtio/device.rs
src/vmm/src/devices/virtio/block/virtio/request.rs
src/vmm/src/devices/virtio/iovec.rs
src/vmm/src/devices/virtio/net/device.rs
src/vmm/src/devices/virtio/net/mod.rs
src/vmm/src/devices/virtio/net/persist.rs
src/vmm/src/devices/virtio/net/test_utils.rs
src/vmm/src/devices/virtio/persist.rs
src/vmm/src/devices/virtio/queue.rs
src/vmm/src/devices/virtio/rng/device.rs
src/vmm/src/devices/virtio/vsock/csm/connection.rs
src/vmm/src/devices/virtio/vsock/device.rs
src/vmm/src/devices/virtio/vsock/event_handler.rs
src/vmm/src/devices/virtio/vsock/packet.rs
src/vmm/src/devices/virtio/vsock/unix/muxer.rs

virtio/queue.rs has a panic in pop()/try_enable_notification(), to
avoid DoS scenarios of the guest asking firecracker to process the same
virtio descriptor multiple times. However, this panic is not only
triggered at VM runtime, but also by various snapshot calls (parsing rx
buffers on net restore, vsock notifying used buffers), where ideally we
shouldn't panic on malformed snapshots, but instead report an error back
to the user. It also make fuzz-testing of firecracker more difficult,
because this panic represents a false-positive.
To avoid all of this, turn the panic into an error variant, and bubble
it out of the virtio stack. This way, the event loop and
unwrap()/panic!() when it encounters this error, while other usecases
and report the error properly (snapshot code) or ignore it …

refactor: Hoist panic out of virtio queue code 

---

tests/conftest.py

The current metric dimensions are so that we have 13k+ different sets of
dimensions for each metric, which makes it impossible to plot in
CloudWatch.
This change adds a new set of dimensions with just the test name so that
we reduce it to a few hundreds and are able to plot them (CW limit is
500).
in the PR.
[1]: …

[1.12] chore(metric): add per-test metric dimension for coarse grained metrics 

---

tests/conftest.py

The current metric dimensions are so that we have 13k+ different sets of dimensions for each metric, which makes it impossible to plot in CloudWatch.
This change adds a new set of dimensions with just the test name so that we reduce it to a few hundreds and are able to plot them (CW limit is 500).
in the PR.
[1]: …

[1.11] chore(metric): add per-test metric dimension for coarse grained metrics

---

docs/getting-started.md

Adding missing 'u' from the word squashfs in the script responsible for downloading the kernel and rootfs
This is clearly a typo and, although it doesn't break the script, leads to names like 'ubuntu-.ext4' instead of 'ubuntu-24.04.ext4' which are not very helpful.
in the PR.
[2]: …

chore: fix typo in script in the getting started guide

---

CHANGELOG.md
src/vmm/src/devices/virtio/balloon/device.rs
src/vmm/src/devices/virtio/block/virtio/device.rs
src/vmm/src/devices/virtio/mmio.rs
src/vmm/src/devices/virtio/net/device.rs
src/vmm/src/devices/virtio/queue.rs
src/vmm/src/devices/virtio/rng/device.rs
src/vmm/src/devices/virtio/vhost_user.rs
src/vmm/src/devices/virtio/vsock/device.rs

Backport of #5260 to 1.12 branch
in the PR.

[1.12 Backport] Fix greedy block device

---

CHANGELOG.md

Remove 1.10.1 CHANGELOG entry
We only track changes to major/minor releases in the CHANGELOG on main branch. Changes in patch versions are listed in the CHANGELOG of the corresponding branch. (firecracker-v1.10 in this case)
in the PR.
[2]: …

chore: remove 1.10.1 CHANGELOG entry

---

src/vmm/src/devices/virtio/balloon/device.rs
src/vmm/src/devices/virtio/balloon/event_handler.rs
src/vmm/src/devices/virtio/block/vhost_user/device.rs
src/vmm/src/devices/virtio/block/virtio/device.rs
src/vmm/src/devices/virtio/device.rs
src/vmm/src/devices/virtio/mmio.rs
src/vmm/src/devices/virtio/persist.rs
src/vmm/src/devices/virtio/queue.rs
src/vmm/src/devices/virtio/vhost_user.rs
src/vmm/src/devices/virtio/vsock/test_utils.rs
src/vmm/src/persist.rs

As part of #5260 we noticed that parts of our virtio queue validation logic was duplicated between `Queue::is_valid` and `Queue::initialize`, resulting in most queue invariants being checked twice needlessly. This PR fixed this by merging the two functions, and having all validation happen right before activation (refusing to activate the device if validation of any of its queues fails).
in the PR.
integration …

refactor: de-duplicate virtio queue validation logic

---

tests/framework/microvm.py
tests/integration_tests/performance/test_snapshot.py

Disable netns reuse for test_restore_latency test.
This is because with netns reuse, the first test variant spends time on initialising netns, while the subsequent test variants do not. Disable netns reuse to make the performance data consistent.
in the PR.~~
- ~~[ ] If a specific issue led to this PR, this …

test(restore_latency): do not reuse netns

---

tests/integration_tests/performance/test_jailer.py

Add host kernel number to the dimension set in the jailer performance test.
in the PR.

fix: add host kernel to the metric dimensions

---

src/vmm/src/devices/virtio/net/tap.rs

We are experiencing intermittent failures of test_write_iovec() due to the rx packet not matching the ones written. To ensure the write has been completed successfully, check the return value of writev() matches the number of bytes that were supposed to be written.
in the PR.~~
- ~~[ ] If a specific issue led …

test(tap): Check return value of writev()

---

Cargo.lock
src/pci/Cargo.toml
src/pci/src/lib.rs

Add some error handling in the PciBdf de-serialization logic.
Also add some unit tests to make Coverage happy.
Fuzzer reported panics on random snapshot file due to this validation logic.
in the PR.
[3]: …

Improve error handling in PciBdf de-serialization

---

tests/integration_tests/performance/test_rate_limiter.py

Print log of iperf server running in a guest if the iperf command fails.
We occasionally see failures of `test_rx_rate_limiting` with the following error:
```
iperf3: error - unable to connect to server - server may have stopped running or use a different port, firewall issue, etc.: Connection refused
```
However, we didn't have any diagnostic info about what happened inside a guest.
- ~~[ ] I have updated any relevant documentation (both in code and in the …

test: Print log of iperf server running in guest

---

tests/integration_tests/performance/test_block.py

Fix the block tests by using the correct fixture name.
PCI pipeline is failing :( 
in the PR.
[3]: …

[feature/pcie] fix(test_block): correct fixture name s/uvm_any_acpi/uvm_plain_acpi/

---

CHANGELOG.md
Cargo.lock
resources/overlay/usr/local/bin/fillmem.c
resources/overlay/usr/local/bin/go_sdk_cred_provider.go/main.go
resources/overlay/usr/local/bin/go_sdk_cred_provider_with_custom_endpoint.go/main.go
resources/rebuild.sh
src/vmm/src/mmds/mod.rs
tests/integration_tests/functional/test_mmds.py

- Set the token TTL header in the MMDS response to "PUT /latest/api/token".
- Add integration tests using AWS SDK for GO to ensure the token TTL header is set in the response and MMDS responds as EC2 IMDS does if `imds_compat` flag is true.
EC2 IMDS sets X-Aws-Ec2-Metadata-Token-Ttl-Seconds header in the
response to PUT /latest/api/token, while MMDS didn't. AWS SDK for Go
tries to parse it as integer (i.e. tries to parse an empty string "" as
integer) [4].
how they are solving …

fix(mmds): Set token TTL header in response to PUT /latest/api/token

---

tests/integration_tests/functional/test_serial_io.py

Add some tolerance (1%) to the memory size check of `test_serial_io.py::test_serial_dos` to avoid false positives.
`test_serial_dos` ensures that the internal FIFO buffer used for storing the bytes to be written does not grow indefinitely. Some times during the test we observe small allocations that make the assertion fail. 
in the PR. …

Add some tolerance in test_serial_dos

---

Cargo.lock
src/pci/src/bus.rs
src/pci/src/msix.rs
src/vmm/src/devices/virtio/transport/pci/common_config.rs
src/vmm/src/devices/virtio/transport/pci/device.rs
src/vmm/src/vstate/vm.rs

Various fixes in the PCI code:
* Relax a redundant assertion in MSI code. The condition of the assertion is anyways checked by the code. When the condition is true, we print an error message.
* Get rid of a `HashMap` that was tracking objects index by integers starting from 0. Use a `Vec` instead.
* Fix the size of the `HashMap` used to track interrupt routes to the maximum possible interrupt number (considering IRQs and MSIs) we can have.
* Validate the queue index selected by guest VirtIO code when using the PCI transport.
build checks on all …

Msix assertions

---

src/vmm/src/vmm_config/boot_source.rs
tests/framework/microvm.py
tests/framework/microvm_helpers.py
tests/framework/vm_config_missing_vcpu_count.json
tests/integration_tests/functional/test_error_code.py
tests/integration_tests/functional/test_kernel_cmdline.py
tests/integration_tests/functional/test_serial_io.py
tests/integration_tests/performance/test_boottime.py
tests/integration_tests/performance/test_initrd.py

Add `iommu=off` to the default command line to disable SWIOTLB.
The kernel enables SWIOTLB when the physical address range exceeds 32b, which ends up wasting 64MB of the VM memory, which translates to higher RSS.
in the PR.
[2]: …

[feature/pcie] feat: add swiotlb=noforce to default kernel command line

---

src/vmm/src/devices/virtio/transport/mmio.rs
src/vmm/src/devices/virtio/transport/pci/device.rs

According to the VirtIO spec section 2.1.2, when we enter a failed state we need to to set `DEVICE_NEEDS_RESET` status field and if `DRIVER_OK` is set we need to must send a device configuration change interrupt to the driver.
In MMIO code we were trying to follow this logic, but we were trying to get the interrupt object from the device, which fails (and panics) because interrupts are only set in the device upon successful activation. In the PCI transport, instead, we were not doing this at all.
For VirtIO devices, the transport layer always holds a reference to the interrupt object of the device. Use this reference in cases that we need to send an interrupt from the transport emulation logic. Moreover, add the missing logic in PCI transport to send a configuration update interrupt to …

Fix mmio interrupts

---

tests/integration_tests/security/test_vulnerabilities.py

Use alternative link to download the spectre/meltdown checker script.
(cherry picked from commit e5b4f26d624f4256147bd7013cfe3f3d2ef5d115)
The link we were using to download the Spectre/Meltdown checker script stopped working and caused our CI to fail consistently.
in the PR.
[1]: …

fix(test): use alternative URL for Spectre/Meltdown checker

---

src/vmm/src/devices/virtio/transport/pci/common_config.rs
src/vmm/src/devices/virtio/transport/pci/device.rs

Validate the interrupt vectors that guest selects for VirtIO queues and configuration interrupts. Also, make sure that the MSI implementation of `VirtioInterrupt` checks that the interrupt index corresponds to a valid interrupt vector.
If the guest sets an invalid vector for a VirtIO queue and/or configuration, we might end up doing an out-of-bounds access to the table that holds the MSI vectors and cause a panic at runtime.
how they are solving the problem in a clear and …

Fix MSIx interrupts

---

Cargo.toml
src/clippy-tracing/src/main.rs
src/cpu-template-helper/src/template/verify/mod.rs
src/vmm/src/vstate/vm.rs

Use `.ok_or_else` when the `Error` needs to be computed by a function call, which may be expensive.
I fixed it in these places:
- MSI interrupt trigger
- clippy tracing
- cpu template helper
And I've added a clippy rule for the future.
I was looking at perf traces for a different thing and noticed an unexpected String format in a good path during interrupt trigger:
```
-    1.16%     0.29%  firecracker  firecracker        [.] <vmm::devices::virtio::transport::pci::device::VirtioInterruptMsix as vmm::devices::virtio::transport::VirtioInterrupt>::trigger                                                     ▒
- 0.88% <vmm::devices::virtio::transport::pci::device::VirtioInterruptMsix as vmm::devices::virtio::transport::VirtioInterrupt>::trigger …
```

[feature/pcie] prevent unnecessary fmt

---

Cargo.lock
src/pci/Cargo.toml
src/pci/src/bus.rs
src/pci/src/configuration.rs
src/pci/src/device.rs
src/pci/src/lib.rs
src/pci/src/msix.rs
src/vmm/src/devices/virtio/transport/pci/device.rs

Add tests for PCI-related code within the `pci` crate
Unit tests for PCI configuration space handling, regarding guest accesses within the configuration space and configuration of MSIx interrupts
Increase testing coverage
in the PR.
[2]: …

Increase testing coverage for PCI code

---

.github/dependabot.yml

rust-vmm deps have to be updated in lockstep most of the time, due to
tight inter-dependencies. However, releasing new versions of all
rust-vmm crates often takes time, and having dependabot include partial
rust-vmm updates in its big PR of the week just results in broken
dependabot PRs. Thus, just sort out the rust-vmm dependencies into a
separate PR
I've tested this over in my fork, and it produced https://github.com/roypat/firecracker/pull/124
how they are solving the …

dependabot: move rust-vmm updates to their own PR

---

.github/dependabot.yml

Apparently, if a rust-vmm dep (currently vmm-sys-util) is included in a
PR for the firecracker group _once_, it will indefinitely be stuck in
there. So explicitly exclude these deps from that group, in hopes of
getting dependabot to understand that it should split the current PR
into two.
in the PR. …

dependabot: explicitly exclude rust-vmm deps from firecracker group

---

tests/framework/utils.py
tests/host_tools/cpu_load.py

Use a single psutil.Process to verify the process still exists, and extend it with better support for threads using psutil.Process to retrieve their information.
The previous fix didn't work because the read can also return `ProcessLookupError`. There is also the issue of pid recycling.
Example:
```
integration_tests/performance/test_block.py::test_block_performance[Sync-vmlinux-5.10.238-True-libaio-bs4096-randwrite-1vcpu] defaultdict(<class 'list'>, {'fc_vcpu 0': [99.95329178526431, 99.95998553854952, 100.91893865958598, 99.95372053973948, 99.95989024751518, 99.96019994404158, 99.96074787336654, 99.9602237669306, 99.96100992864535, 99.95634078590423, 99.96043817344481, 99.96077169651657, 99.95996171577396, 99.96024758983143, 99.9610575752075, 99.959890247515, 99.96036670450454, …
```

fix(tests/cpu-monitor): use psutil.Process for threads to fix errors

---

src/vmm/src/arch/aarch64/regs.rs
src/vmm/src/arch/x86_64/vm.rs
src/vmm/src/device_manager/pci_mngr.rs
src/vmm/src/device_manager/persist.rs
src/vmm/src/devices/virtio/balloon/persist.rs
src/vmm/src/devices/virtio/block/virtio/persist.rs
src/vmm/src/devices/virtio/net/persist.rs
src/vmm/src/devices/virtio/persist.rs
src/vmm/src/devices/virtio/rng/persist.rs
src/vmm/src/devices/virtio/vsock/persist.rs
src/vmm/src/mmds/persist.rs
src/vmm/src/persist.rs
src/vmm/src/rate_limiter/persist.rs
src/vmm/src/snapshot/mod.rs
src/vmm/src/vmm_config/boot_source.rs
src/vmm/src/vstate/memory.rs
src/vmm/src/vstate/resources.rs
src/vmm/src/vstate/vm.rs
tests/integration_tests/functional/test_snapshot_basic.py

In commit e7504ae ("refactor: cleanup vmm::snapshot module"),
firecracker started reading the snapshot vmstate file in a single pass
instead of first loading it into a Vec and then deserializing. This
seems to have caused some performance regression due to the deserializer
doing many successive reads, resulting in many read(2) syscalls.
Fix this by going back to first reading the snapshot file into a buffer,
and then deserializing from slice instead.
...
...
build checks on all supported …

fix: use temporary buffer for loading vmstate file

---

src/vmm/src/device_manager/mod.rs
src/vmm/src/device_manager/pci_mngr.rs
src/vmm/src/device_manager/persist.rs

Store the vm type as an Arc in the constructor args for the MMIO dev mgr restore, as it's done in the PCI one. Also use a reference to avoid extra clones.
I will need to pass the `Arc<Vm>` to the virtio-mem device. It's already done like so in the PCI device manager, but not in MMIO.
in the PR. …

refactor(dev-mngr): store vm as Arc in MMIODevManagerConstructorArgs

---

src/firecracker/swagger/firecracker.yaml

Fix a few typos in swagger
- `imds_compat` parameter of `mmds` endpoint
- `snapshot` spelled as `snaphot` in some descriptions
- `responds` spelled as `reponds` in a description
Fixes #5417.
in the PR.
[2]: …

Fix typo in swagger

---

.buildkite/pipeline_perf.py

Increase timeout for population latency tests.
We are seeing the execution time exceed the default 60 minutes Buidlkite timeout sometimes.
- ~~[ ] I have run `tools/devtool checkbuild --all` to verify that the PR passes
build checks on all supported architectures.~~
- ~~[ ] I have run `tools/devtool checkstyle` to verify that the PR passes the
automated style checks.~~
- ~~[ ] I have described what is done in these changes, why they are needed, and
how they are solving the problem in a clear and encompassing way.~~
- ~~[ ] I have updated any …

buildkite: increase timeout for population latency tests

---

tests/integration_tests/performance/test_vsock.py

Move the copy into the test construction to copy the binary only once.
Currently we copy the iperf3-vsock binary into the guest in spawn_iperf3_client that is called by every client (we have 2).  If by the time the second binary is being copied that first one is already executing, we get the "Text file busy" error.
- ~~[ ] I have run `tools/devtool checkbuild --all` to verify that the PR passes
build checks on all supported architectures.~~
- ~~[ ] I have …

test(perf/vsock): copy iperf binary only once

---

docs/jailer.md
src/jailer/src/env.rs
src/jailer/src/main.rs
tests/integration_tests/security/test_jail.py

- Tiny cleanups of jailer doc
- Clarify the jailer's behavior when --parent-cgroup provided but --cgroup not provided
- Add integration tests for all the cases when --parent-cgroup provided but --cgroup not provided.
The behavior of `--parent-cgroup` parameter on cgroup v2 is a bit complicated:
- If any --cgroup parameters passed, jailer creates a new cgroup under the specified cgroup
- If no --cgroup parameters not passed,
- If the specified cgroup exists, jailer moves the process to the cgroup instead of creating a new cgroup under it.
- If the specified cgroup does not exist, jailer doesn't do anything and proceeds without error. …

docs: Clarify jailer's behavior when --parent-cgroup provided but --cgroup not provided

---

src/vmm/src/builder.rs
src/vmm/src/gdb/event_loop.rs
src/vmm/src/gdb/mod.rs
src/vmm/src/gdb/target.rs
src/vmm/src/lib.rs
src/vmm/src/vstate/vcpu.rs

Instead of storing mmaped kvm_vcpu struct in the TLS, we can have it in the VcpuHandle. This way we don't need to deal with TLS and it's synchronization.
Dealing with TLS was difficult and bug prone
in the PR.
[2]: …

refactor: remove TLS from vcpus

---

Cargo.lock
src/pci/Cargo.toml
src/pci/src/bus.rs
src/pci/src/configuration.rs
src/pci/src/device.rs
src/vmm/src/device_manager/pci_mngr.rs
src/vmm/src/devices/virtio/transport/pci/device.rs
src/vmm/src/vstate/vm.rs

This is the first in a series of PRs that are meant to simplify our PCI codebase
Mainly two changes:
* Move (de)allocation of the BAR outside the `PciDevice` trait
* Encode in the PCI handling logic the fact that we only ever create 64-bit BAR regions with fixed size (for VirtIO) devices
A lot of the PCI code we pulled from Cloud Hypervisor is built in the form of a library trying to be generic and support various functionalities of the PCI specification.a
In our case, we only support certain functionality. For example, we only have two types of PCI devices, VirtIO devices and the Root Port. Only VirtIO devices use BAR regions (64 bits). We don't use 32-bit, I/O or ROM BARs.
We'd like to move towards a PCI implementation which is tailored to our use-case instead of a generic library …

Simplify PCI code

---

tests/framework/microvm.py
tests/host_tools/network.py
tests/integration_tests/functional/test_balloon.py

Teach MicroVM.kill() that there might be cases where the microVM process has already died and let it finish its cleanup gracefully.
We have some tests that stress the microVM in a way that _might_ cause it to die. We do check whether that's the case, however this is inherently racy, i.e. the microVM might die on us after the check but before the fixture logic tries to recycle it. Such a test is test_balloon.py::test_deflate_oom.
how they are solving the problem in a clear and …

Gracefully clean-up potentially dead microVMs

---

src/vmm/src/devices/virtio/transport/pci/device.rs

Even though currently, no device supports resetting, once the guest attempts to reset the device we must set the status to 0 as specified in the 2.4.1 Device Requirements: Device Reset.
This does not change the current status of us not supporting device resetting.
This is the issue we encountered during addition of virtio-pmem device where the guest kernel now resets devices on VM shutdown.
in the PR.
[Runbook …

fix: correctly set device status to 0 on reset

---

.github/dependabot.yml
Cargo.lock
src/vmm/Cargo.toml

This change pins aws-lc-rs back to 1.14.0 to fix the performance regression and tells dependabot to ignore it until further notice.
The recent aws-lc-rs update including the Ragdoll changes has caused a significant regression in multiple metrics, inclusing a 45ms (900%) regression in load_snapshot latency.
See also https://github.com/aws/aws-lc-rs/issues/899
in the PR. …

chore: pin aws-lc-rs version to 1.14.0

---

tests/integration_tests/security/test_vulnerabilities.py

Add an exception for TSA for host kernels before 6.1.153
Vulnerability checks are failing. 
TSA is marked as vulnerable as 6.1 kernels before 6.1.153 don't correctly pass through the CPUID bit to let the guest know that the microcode is applied (CLEAR_VERW).
We noticed only now as we just updated the guest kernels and they now contain the TSA mitigation.
in the PR. …

fix(test/vulnerabilities): add exception for TSA before 6.1.153

---

tests/host_tools/fcmetrics.py

In order to collect all error metrics we're checking for "err" in the key name, which causes performance tests to fail because we added metrics called "intERRupts".  Change the check to only look at the leafof the path, so that when we have a metric such as `fc_metrics.net_metrics.cfg_fails`, we'll only be looking into cfg_fails`.
in the PR. …

Do not look into full path for error metric

---

tests/integration_tests/functional/test_cpu_features_host_vs_guest.py

Backport commit 8221464e80782e999aa980f34ced324e22336b74 from main.
Add ibpb_exit_to_user as host only feature
New Amazon Linux host kernels enable mitigation against VMScape that is IBPB before exit to userspace. However, our guest kernels still haven't had the patches yet. Note that Intel Ice Lake is not affected by VMScape as long as BHB clearing sequence is used to mitigate BHI.
- ~~[ ] I have updated any …

[v1.13] chore: Add ibpb_exit_to_user as host only feature
