SPECIFICATION.md

Correct Open API spec link in SPECIFICATION.md

---

.gitignore
Cargo.lock

This PR addresses issue #617.
cc @andreeaflorescu

Add Cargo.lock to Git

---

docs/prod-host-setup.md

Covers side-channel considerations, which includes descriptions, mitigation detection and enablement.   Reworking of https://github.com/firecracker-microvm/firecracker/pull/635 .
Fixes  #659

Adding "Production Host Setup Recommendations" doc 

---

x86_64/src/regs.rs

Setting and getting the SREGS by calling the KVM-related ioctls trigger
the same error. Created two different errors for each of them in order
to be able to differentiate them in log messages.
Fixes #556

Differentiate between SRegs related errors

---

CHANGELOG.md
api_server/src/http_service.rs
mmds/src/data_store.rs
tests/integration_tests/functional/test_mmds.py

* Fix response code of mmds PUT request to 204(No Content)
* Fixes #528

fix(api-server):  fix mmds PUT response status code

---

CHANGELOG.md
api_server/src/http_service.rs
api_server/src/request/net.rs
api_server/swagger/firecracker.yaml
tests/framework/resources.py
vmm/src/lib.rs
vmm/src/vmm_config/mod.rs
vmm/src/vmm_config/net.rs

Remove DeviceState from NetworkInterfaceConfig

---

CREDITS.md

... and populate with crosvm authors. I tried to dig through history
to make sure that we give everyone credit based on what's been
included / ported over from the crosvm repository over time.
Signed-off-by: Matt Wilson <msw@amazon.com>

docs: add CREDITS.md

---

memory_model/src/mmap.rs

Use usize.overflowing_add() to validate requested address range and
avoid panicking at runtime.
Signed-off-by: Liu Jiang <gerry@linux.alibaba.com>
Issue #744 :

memory_model: improve access request address range validation

---

Cargo.lock
devices/Cargo.toml
devices/src/virtio/block.rs
devices/src/virtio/net.rs
vmm/Cargo.toml
vmm/src/lib.rs

Upgraded from 2.1.0 to 4.0.1. Implements updates from nathansizemore/epoll#8
#757 

Upgrades epoll crate. 

---

api_server/src/http_service.rs
tests/host_tools/logging.py
tests/integration_tests/functional/test_logging.py
tests/integration_tests/performance/test_boottime.py
tests/integration_tests/performance/test_process_startup_time.py

Issue #, if available: Partially addressing https://github.com/firecracker-microvm/firecracker/issues/478
Fixed a bug in sequential_fifo_reader.
Added logs for PUT PATCH & GET requests on /mmds.
Removed the body from log messages for GET requests. 
Re-phrased some of the existing log messages in the API server. 

API Server Logs - Adding MMDS & Refactoring

---

dumbo/src/ns.rs

Reiteration of #619, which apparently can no longer be updated after moving my fork.

Dumbo: added some new unit tests to ns.rs (2)

---

CHANGELOG.md
CREDITS.md
Cargo.lock
Cargo.toml
api_server/swagger/firecracker.yaml
jailer/Cargo.toml

* Added missing item to CHANGELOG.md relating removed action.
* Updated CREDITS.md.
* Updated firecracker, jailer & swagger versions.
* Updated cargo dependencies.

Changes for Firecracker-v0.13.0 Release

---

devices/src/virtio/vhost/handle.rs
devices/src/virtio/vhost/vsock.rs
vmm/src/lib.rs

Minor code improvements to vhost/vsock and get rid of some compilation warnings.

Minor code improvements to vhost/vsock

---

docs/network-setup.md

Issue #, if available: https://github.com/firecracker-microvm/firecracker/issues/711
Description of changes: Add very basic network setup instructions, re-using a lot of the code from folks responding to that issue.

Add getting started network setup

---

CHANGELOG.md
CREDITS.md
Cargo.lock
Cargo.toml
api_server/swagger/firecracker.yaml
jailer/Cargo.toml

Issue #, if available: N/A
Updated:
* version number
* changelog
* swagger spec
* cargo dependencies
* credits

Changes for v0.14.0 release

---

sys_util/src/eventfd.rs

Closes #129
* Make EventFd non-blocking by passing `EFD_NONBLOCK` on eventfd creation

Make EventFd non-blocking

---

logger/src/lib.rs

Issue #, if available: #906 
Description of changes: fix logger issue

fix logger issue

---

memory_model/src/mmap.rs

Function libc::mmap() returns libc::MAP_FAILED(-1) instead of null on
failure, so don't detect failure by checking that the returned pointer
is null.
Signed-off-by: Liu Jiang <gerry@linux.alibaba.com>

memory-model: correctly handle result of libc::mmap()

---

tests/framework/http.py
tests/framework/microvm.py
tests/integration_tests/functional/test_api.py
tests/integration_tests/functional/test_drives.py
tests/integration_tests/functional/test_logging.py
tests/integration_tests/functional/test_mmds.py
tests/integration_tests/performance/test_boottime.py
tests/integration_tests/performance/test_process_startup_time.py

Issue #524
Replace `is_good_response` with functions checking each status code.

Fix assert on the acutual http code

---

cpuid/src/bit_helper.rs
cpuid/src/cpu_leaf.rs
cpuid/src/lib.rs
tests/integration_tests/build/test_coverage.py

Issue #, if available: #851 
cpuid crate refactoring - part 1: use helper methods instead of bitwise operations when editing the cpuid

cpuid crate refactoring - part 1

---

FAQ.md

docs: add FAQ entry for rebooting and powering off

---

cpuid/src/bit_helper.rs
cpuid/src/lib.rs
dumbo/src/lib.rs
kvm/src/lib.rs
logger/src/lib.rs
memory_model/src/lib.rs
micro_http/src/lib.rs
rate_limiter/src/lib.rs
seccomp/src/lib.rs
vmm/src/lib.rs

Issue #, if available: #944 
Description of changes: add documentation for BitRangeExt

add documentation for BitRangeExt

---

FAQ.md

Explain that in the last release of Kata containers, support for Firecracker has been included.
Issue #941
Signed-off-by: Javier Romero <xavinux@gmail.com>

Update FAQ.md with support for Kata containers.

---

micro_http/src/request.rs

Description of changes: Corrected the comment on min_len() function of micro_http package

correct the comment of min_len() function

---

.cargo/config
Cargo.toml
kernel/src/loader/mod.rs
kvm/src/lib.rs
logger/src/lib.rs
src/main.rs
tests/integration_tests/build/test_build.py
tools/devtool
vmm/src/default_syscalls/aarch64.rs
vmm/src/lib.rs
vmm/src/vmm_config/logger.rs

Issue #, if available: Fixes #949 
Fixed build on arm.

kvm crate: fix arm build

---

devices/src/virtio/net.rs

Issue #, if available: #425 
Description of changes: early marking of descriptors as *used* by avoiding double borrowing

Net IO performance optimization

---

CHANGELOG.md
Cargo.toml
jailer/Cargo.toml
jailer/src/env.rs
jailer/src/lib.rs
tests/conftest.py
tests/framework/microvm.py
tests/framework/resources.py
tests/framework/s3fetcher.py
tests/host_tools/cargo_build.py
tests/host_tools/network.py
tests/host_tools/test_vsock.c
tests/integration_tests/build/test_build.py
tests/integration_tests/functional/test_api.py
tests/integration_tests/functional/test_vsock.py
tools/devctr/Dockerfile
vhost_gen/src/lib.rs
vmm/src/default_syscalls/x86_64.rs
vmm/src/lib.rs

Putting together the vsock fix and tests

---

CHANGELOG.md
CREDITS.md
Cargo.toml
api_server/swagger/firecracker.yaml
jailer/Cargo.toml

Firecracker release v0.15.0

---

Cargo.lock
api_server/swagger/firecracker.yaml
tests/host_tools/network.py
tests/integration_tests/functional/test_cpu_features.py
tests/integration_tests/functional/test_drives.py
tests/integration_tests/functional/test_rate_limiter.py
tools/devctr/Dockerfile
tools/devtool

- Removed paramiko as a dependency for our integration tests, since it was yielding a bunch of deprecation warnings.
- Rebuilt a new version of the dev container, with aarch64 support and more
- Fixed our API swagger definition YAML

Dev container upgrade (v5) + swagger fix

---

CHANGELOG.md
docs/jailer.md

update CHANGELOG.md with jailer changes

---

vmm/src/default_syscalls/x86_64.rs

Small whitelist fix

---

docs/network-setup.md

Signed-off-by: Mehrdad Arshad Rad <arshad.rad@gmail.com>

fixed --tap-device value

---

cpuid/src/cpu_leaf.rs
cpuid/src/transformer/amd.rs
cpuid/src/transformer/common.rs
cpuid/src/transformer/intel.rs

implement basic cpuid filtering for AMD

---

cpuid/src/cpu_leaf.rs
cpuid/src/transformer/amd.rs

fix AMD boot warning

---

cpuid/src/brand_string.rs
cpuid/src/lib.rs
cpuid/src/transformer/amd.rs
cpuid/src/transformer/common.rs
cpuid/src/transformer/intel.rs
cpuid/src/transformer/mod.rs
tests/integration_tests/functional/test_cpu_features.py

add support for AMD brand string

---

arch/src/aarch64/layout.rs
arch/src/aarch64/mod.rs
arch/src/aarch64/regs.rs
kernel/src/loader/mod.rs
vmm/src/lib.rs
vmm/src/vstate.rs

This sets up the aarch64 specific registers.

aarch64: add vcpu configuration

---

.mailmap
CHANGELOG.md
CREDITS.md
Cargo.lock
Cargo.toml
api_server/Cargo.toml
api_server/swagger/firecracker.yaml
arch_gen/Cargo.toml
cpuid/Cargo.toml
dumbo/Cargo.toml
fc_util/Cargo.toml
jailer/Cargo.toml
logger/Cargo.toml
micro_http/Cargo.toml
mmds/Cargo.toml
rate_limiter/Cargo.toml
seccomp/Cargo.toml
tests/integration_tests/security/demo_seccomp/Cargo.toml
vhost_gen/Cargo.toml
vmm/Cargo.toml

Updated the version number, changelog, cargo dependencies & credits.md.

release v0.16.0

---

CHANGELOG.md

release v0.16.0 - fixed CHANGELOG

---

devices/src/bus.rs
devices/src/lib.rs
devices/src/virtio/block.rs
devices/src/virtio/mmio.rs
devices/src/virtio/mod.rs
devices/src/virtio/net.rs
devices/src/virtio/queue.rs
devices/src/virtio/vhost/handle.rs
tests/integration_tests/build/test_coverage.py
vmm/src/lib.rs
vmm/src/vmm_config/drive.rs

VirtIO: Add support for downcasting EpollHandler

---

src/main.rs

Signed-off-by: Adrian Catangiu <acatan@amazon.com>

tiny fix: remove some dead code

---

SPECIFICATION.md

Description of changes: Fix typo, assuming that this is what was meant here.

fix typo in SPECIFICATION.md

---

cpuid/src/brand_string.rs

Issue #, if available: fixes #546 
Description of changes: Fixed an issue where the brand string from cpuid did not display the
correct clock frequency of the cpu when it was provided in THz.

Fixed brand string not supporting THz

---

fc_util/src/lib.rs

Fixed logged month being one less than actual

---

docs/prod-host-setup.md

Add recommendation to run each Firecracker instance under its own `uid` and `gid`.
Update system check commands to explicitly say if recommendations are met.
Fixes #1118 

docs: update prod-host-setup.md

---

logger/src/metrics.rs

Issue #, if available: n/a
Description of changes: Refactors metrics code ~~,adding a `BinarySharedMetric` type, and~~ removing the `SimpleMetric` type.
Fixes: #1204 
Signed-off-by: Tamio-Vesa Nakajima <tamiove@amazon.com>

Remove simple metrics

---

vmm/src/device_manager/legacy.rs
vmm/src/lib.rs
vmm/src/vstate.rs

Signed-off-by: Gábor Lipták <gliptak@gmail.com>

Cleanup unused imports

---

docs/rootfs-and-kernel-setup.md

add `sysfs` to automount upon boot

Updated doc for creating rootfs sample: automount sysfs

---

memory_model/src/guest_memory.rs
memory_model/src/lib.rs
vmm/src/lib.rs
vmm/src/vmm_config/drive.rs
vmm/src/vmm_config/instance_info.rs

Stylistic refactoring of the `vmm` module.
Signed-off-by: Tamio-Vesa Nakajima <tamiove@amazon.com>
Issue #, if available: N/a.
Description of changes: Code in `vmm/lib.rs`, `vmm/vmm_config/drive.rs` is refactored.

Vmm refactoring

---

docs/getting-started.md

Documentation fix for aarch64 kernel command line boot arguments . 

Update boot_args docs for aarch64.

---

tests/framework/microvm.py
tests/integration_tests/functional/test_serial_io.py
tools/devctr/Dockerfile.aarch64
tools/devctr/Dockerfile.x86_64
tools/devtool

Fixes: #1251.
New integration test for the serial console.
Provided in commit messages. 
**_Note: An update of the dev container image is required for this test to pass._**

Serial login test

---

api_server/src/request/mod.rs
arch/src/aarch64/fdt.rs
arch/src/aarch64/gic.rs
arch/src/aarch64/mod.rs
arch/src/aarch64/regs.rs
arch/src/lib.rs
arch/src/x86_64/interrupts.rs
arch/src/x86_64/layout.rs
arch/src/x86_64/mod.rs
arch/src/x86_64/regs.rs
vmm/src/lib.rs

#609 
The #![deny(missing_docs)] is now on
for this crate.

Doc for public facing content in arch crate

---

README.md

Small wording and formatting improvements to `README.md`.
* Replaced "Beta" with "Preview" for AMD and Arm CPU support.
* Mentioned Weaveworks Ignite as a container-world project that integrates with Firecracker.
* Formatted markdown to wrap at 80 lines across the doc.

docs: mention Ignite and swap "Beta" for "Preview"

---

Cargo.lock
devices/src/virtio/net.rs
net_util/Cargo.toml
net_util/src/lib.rs
net_util/src/mac.rs
net_util/src/tap.rs
vmm/src/lib.rs

`A better net_util crate.`
* removed lazy_static dependency and replaced with another mechanism
* added documentation for public functions
* relocate functions that were only used in unit tests

Miscellanous improvements to net_util

---

net_util/src/tap.rs

Small refactor to make the tap-name code more robust.

tap: fix error-prone hardcoding of tap names max length

---

CHANGELOG.md
api_server/src/http_service.rs
tests/integration_tests/functional/test_logging.py

Log the error returned by the vmm in the FIFOs

---

tools/devtool

#1317
Use container image v11, with the latest version of `cargo-audit` (0.9.2).

devtool: update devctr image

---

SPECIFICATION.md
tests/integration_tests/performance/test_boottime.py

Fix #1313 
- updated the specification with information about how we are measuring the boot time and the memory overhead.

Fix specification

---

arch/src/aarch64/fdt.rs

#1264
When we insert virtio mmio devices into fdt, we should add it in order, from low to high.
For now, they were iterated and inserted in agnostic order.
To avoid that, we re-store them in Vec for sorting out lately in right
order.
Signed-off-by: Penny Zheng <penny.zheng@arm.com>
Signed-off-by: Haibo Xu <haibo.xu@arm.com>
reflected in …

virtio-mmio: insert device nodes into fdt in order on AArch64

---

.mailmap
CHANGELOG.md
CREDITS.md
Cargo.lock
Cargo.toml
api_server/swagger/firecracker.yaml
jailer/Cargo.toml

Update Firecracker version
- added missing entries in the changelog
- run `tools/devtool prepare_release 0.19.0`

V0.19.0 release

---

vmm/src/lib.rs

#1354 
provided in the commit message

fix test_attach_legacy_devices

---

Cargo.lock
arch/Cargo.toml
arch/src/x86_64/regs.rs
cpuid/Cargo.toml
cpuid/src/lib.rs
cpuid/src/transformer/common.rs
cpuid/src/transformer/mod.rs
vmm/Cargo.toml
vmm/src/vstate.rs

#1358 - Update kvm-ioctls to v0.3.0
Update kvm-ioctls to v0.3.0.

Update kvm-ioctls to v0.3.0

---

Cargo.lock
cpuid/Cargo.toml
cpuid/src/lib.rs
cpuid/src/transformer/common.rs
cpuid/src/transformer/mod.rs

fixes #1019 
provided in commit message

simplify use_host_cpuid_function

---

.github/pull_request_template.md

Remind authors and reviewers to carefully audit unsafe code.
Added a new checkbox in the PR template.

PR template: add checkbox for new unsafe code

---

tests/integration_tests/build/test_coverage.py

We do not care about pnet anymore as per
latest commits.
#1238.

fix: little leftover from previous commit

---

arch/src/aarch64/fdt.rs
arch/src/aarch64/mod.rs
arch/src/x86_64/mod.rs
arch/src/x86_64/mptable.rs
arch/src/x86_64/regs.rs
devices/src/virtio/block.rs
devices/src/virtio/mmio.rs
devices/src/virtio/queue.rs
kernel/src/loader/mod.rs
memory_model/src/guest_address.rs
memory_model/src/guest_memory.rs
memory_model/src/lib.rs
vmm/src/vstate.rs

#1350 
provided in the commits

[GuestAddress] Use the vm-memory method names

---

devices/src/legacy/serial.rs

Fixed some inconsistencies in the serial console implementation.
We were doing some unnecessary casts. Also, the emulation was split between IoBus and Serial. Moved all emulation to Serial instead. 
Check reasons for this PR and the commit messages.
this PR have user impact and have been added to …

Serial Console Improvements

---

vmm/src/vstate.rs

This brings minor improvement, to leverage Iterator::find() instead `if...else`, and
deconstruct it.
Levergae iterator methods to find item instead `if...else` block.
This find the unavailable particular `Cap` via `iterator::find()` and deconstruct it for next handling.
reflected in …

Leverage Iterator::find() to get KVM extension capability

---

vmm/src/lib.rs

Fixes #1381 
This unit tests makes sure that calling
epoll_ctl_add on STDIN_FILENO succeeds.
However, if the unit tests are run through
ssh without a pseudo terminal, adding STDIN_FILENO
would return EPERM. Adjust unit test to not panic
in case of EPERM.

vmm: fix test_epoll_stdin_event

---

CONTRIBUTING.md
FAQ.md
MAINTAINERS.md
README.md
SECURITY-POLICY.md

Update project root documentation files to reflect current state.
- Remove firecracker-devel@lists.infradead.org as a contact.
- Mention that Firecracker runs workloads at scale in AWS.
- Mention that AMD and Arm are in developer preview.
- Mention container integrations (Kata, Weave).
- Add the "KVM userspace" article to QEMU mentions.
- Mention rust-vmm as part of the crosvm story.
- Add OSv as a supported guest operating system.
- Remove OpenStack/CNCF FAQ question.
- Replace "security problem/vulnerability" with "security issue".
- Update maintainers.

Docs Update 2019-11

---

polly/src/event_manager.rs
src/polly/Cargo.toml
src/polly/src/event_manager.rs
src/polly/src/lib.rs
src/polly/src/pollable.rs
src/vmm/Cargo.toml
tests/integration_tests/build/test_coverage.py

#1403 
- Implement Pollable, PollableOps
- Implement EventManager and EventHandler trait.
- Implement channel for sending PollableOps
- Unit tests

Implement an I/O EventManager ("polly" crate).

---

src/api_server/src/lib.rs
src/devices/src/virtio/mmio.rs
src/firecracker/src/main.rs
src/vmm/src/controller.rs
src/vmm/src/device_manager/mmio.rs
src/vmm/src/error.rs
src/vmm/src/lib.rs
src/vmm/src/vmm_config/instance_info.rs
src/vmm/src/vstate.rs
tests/integration_tests/build/test_coverage.py

Initial decoupling implementation. Still working on adapting tests.
Signed-off-by: Alexandru Agache <aagch@amazon.com>

Initial controller/vmm decoupling

---

docs/network-setup.md

Link has to be first activated
Change example code for setting network interface in container. In order to add gateway the interface has to be active.

Add command for setting guest network

---

src/logger/src/lib.rs

This improves a little creating prefix. Generate prefix items using `if in let` expression, and join all ones by separator `:`, as to make easy to add or delete item from/to prefix.
This improves a little on creating prefix in logger.
1. To use `if in let` expression as to simplify the condition block.
2. To organize ones to vector and join them by separator `:`, as to make easy to add or delete item from/to prefix.
doc changes are included in this PR. Docs …

logger: improve function create_prefix

---

FAQ.md

Issue #835
Added description and root cause for possible error when starting Firecracker

Updated FAQ with description for error when starting Firecracker

---

CHANGELOG.md
Cargo.lock
Cargo.toml
api_server/swagger/firecracker.yaml
devices/src/virtio/queue.rs
devices/src/virtio/vsock/epoll_handler.rs
devices/src/virtio/vsock/mod.rs
devices/src/virtio/vsock/packet.rs
jailer/Cargo.toml
memory_model/src/guest_memory.rs
vmm/src/lib.rs

Fixed a logical error in bounds checking performed on vsock virtio descriptors. (CVE-2019-18960)

Firecracker release v0.19.1

---

src/vmm/src/controller.rs

Re-added a fix for patching dev based block devices that got lost during the previous rebase, and was not caught by the CI because it skips the corresponding test for some reason. Opened #1454.

fixed patch dev for block devices

---

src/mmds/src/data_store.rs

Improve a little code progress, by converting object into iterator.
To improve a little the code progress in `fn check_data_valid()`.
This insteads `for..loop` block, by converting object into iterator. It breaks automatically when encountering error. …

mmds: try each value item in fn check_data_valid

---

Cargo.lock
src/rate_limiter/Cargo.toml
src/utils/Cargo.toml
src/utils/src/net/tap.rs

Some:
* alphabetical reorderings inside toml's
* some missed newlines inside toml's
* removal of unused imports

Little style adjustments

---

docs/api_requests/logger.md

From the documentation, one could thing that
the destination for the logger's outputs could
only be named pipes. Now, we are also mentioning
usual files.
Added info in logger doc.

docs: mention additional logger info

---

src/arch/src/aarch64/fdt.rs
src/arch/src/x86_64/mod.rs
src/arch/src/x86_64/mptable.rs
src/arch/src/x86_64/regs.rs
src/devices/src/virtio/block.rs
src/devices/src/virtio/net.rs
src/devices/src/virtio/queue.rs
src/devices/src/virtio/vsock/epoll_handler.rs
src/kernel/src/loader/mod.rs
src/memory_model/src/bytes.rs
src/memory_model/src/guest_memory.rs
src/memory_model/src/lib.rs
src/memory_model/src/mmap.rs
src/vmm/src/lib.rs
tests/integration_tests/build/test_coverage.py

implements #1470 
Provided in the commits description.

[memory_model] import Bytes trait from rust-vmm/vm-memory

---

tests/integration_tests/build/test_binary_size.py

Issue #1337
Added a test to check if the size of the release binary is within expected range

Added binary size test

---

tests/framework/scheduler.py

Fixed a regression introduced by #1478, whereby the pytest session would return an incorrect exit code.
See above.

tests: fixed exit code regression

---

src/devices/src/virtio/block.rs

Old code would just inhibit error triggered when file metadata could not be obtained.
Use `map_err`.

block: propagate GetFileMetadata error

---

Cargo.lock
src/api_server/Cargo.toml
src/api_server/src/lib.rs
src/api_server/src/request/actions.rs
src/api_server/src/request/drive.rs
src/api_server/src/request/instance_info.rs
src/api_server/src/request/logger.rs
src/api_server/src/request/net.rs
src/api_server/src/request/vsock.rs
tests/integration_tests/build/test_coverage.py

Fixed, completed and reorganized some things inside the api_server.
Please keep in mind while reviewing that this does not aim at making api_server perfect. These are just nice, good improvements.
Check out the commits.
* coverage increases with 0.2%

Fixes inside api_server

---

src/devices/src/virtio/queue.rs
src/devices/src/virtio/vsock/packet.rs
src/vm-memory/src/guest_memory.rs

It's been decided we're not going to upstream the `checked_range_offset`
and the modified version of `get_host_address` to `vm-memory`, and these
changes bring things in line with the future `vm-memory` integration.
`checked_range_offset` has been removed entirely, together with the
associated check in `DescriptorChain::is_valid`. The validity of memory
accesses is checked at the time of read/write when the device model
calls `GuestMemory` methods. Vsock devices are currently an exception,
but they do enforce their own validations via `get_host_address` (the
two parameter version, that won't get upstreamed). On that
front, we revert `GuestMemory::get_host_address` to the original, single
parameter version, and add a new one local to `vsock/packet.rs` that
implements the two-parameter …

Reworked checked_range_offset and get_host_address

---

src/micro_http/src/common/headers.rs
src/micro_http/src/common/mod.rs
src/micro_http/src/connection.rs
src/micro_http/src/request.rs
src/micro_http/src/response.rs
src/micro_http/src/server.rs

Signed-off-by: karthik nedunchezhiyan <karthik1705.n@gmail.com>
This PR includes some doc and code corrections.

micro_http: some doc and code corrections

---

src/logger/src/lib.rs

Signed-off-by: karthik nedunchezhiyan <karthik.n@zohocorp.com>
- Fixes #1566 
- `log_metrics` returned result of false even successfully written the metrics to a destination.
This PR includes
- `missed_log_count` incremented if the FIFO fd's destination lock got poisoned.
- returned result of true if `log_metrics` successfully written the metrics to a destination.
code …

logger: increase metrics count if lock poisoned.

---

src/micro_http/src/request.rs

This updates unit test:
1. Add test cases for sub-domain url and `ip:port`;
2. Re-organize test cases by vector of tuple to identify original input and exp value. I assume this make test code flexible. 
refactor `test_uri()`  in `request.rs`
this PR have user impact and have been added to the …

micro_http: update unit test

---

docs/prod-host-setup.md

Fixes #1583
Provided in the commit message.

provide guidelines for avoiding CVE-2019-3016

---

Cargo.lock
src/devices/Cargo.toml
src/devices/src/virtio/block/device.rs
src/devices/src/virtio/block/request.rs
src/devices/src/virtio/queue.rs
tests/integration_tests/build/test_coverage.py

After the block device was refactored, the tests have not been updated to work with the new API.
This PR remedies the situation (issue #1563).
The existing tests have been reorganized in the `device.rs` and `request.rs` files.
A few other tests have been added.

Update the block device tests

---

FAQ.md

Resolves https://github.com/firecracker-microvm/firecracker/issues/1554.
Initrd issue is resolved, so updating FAQ to match.

fix initrd FAQ section

---

src/devices/src/virtio/vsock/unix/muxer.rs
src/vmm/src/builder.rs
tests/integration_tests/build/test_coverage.py

#1578 
Raised the coverage for `builder.rs`.

Raise coverage for vmm builder

---

.mailmap
CHANGELOG.md
CREDITS.md
Cargo.lock
src/api_server/swagger/firecracker.yaml
src/firecracker/Cargo.toml
src/jailer/Cargo.toml

Self explanatory.
Self explanatory.

Release v0.21.0

---

CHANGELOG.md
docs/prod-host-setup.md

Updates the mitigation information for CVE-2019-3016.
Same as above.

Update mitigation for CVE-2019-3016.

---

tools/devtool

There are cases when CI fails with "Error accessing Docker".
Show in log docker command output in order to investigate the issue further.
Logs more info, required for issue #1615 
Log docker commands output in case of failures.

devtool: log the errors reported by docker checks

---

tests/integration_tests/functional/test_cmd_line_start.py

Run the 'ps' call in a retry loop to avoid situations where `ps` does not list the process threads.
Since the ps call does not guarantee that the firecracker process has been fully launched, the ps call should be retried.

tests: Retry 'ps' call if PID does not show up

---

src/devices/src/virtio/device.rs
src/devices/src/virtio/mmio.rs
tests/integration_tests/build/test_coverage.py

Fixes #1595 
Updated unit tests from `virtio/mmio.rs`.

virtio/mmio: updated unit tests

---

src/api_server/swagger/firecracker.yaml
src/firecracker/Cargo.toml
src/jailer/Cargo.toml

This patch release includes a backport for the issue:
https://github.com/firecracker-microvm/firecracker/issues/1632
Signed-off-by: Andreea Florescu <fandree@amazon.com>
this PR have user impact and have …

patch release for v0.21.1

---

src/firecracker/src/api_server_adapter.rs

This fixes a race during config/pre-boot phase where the VMM thread reads this event_fd before API thread gets the chance to increment it.
The API event_fd is used by the API thread to signal the VMM thread that it has pending messages.
During config/pre-boot phase, this event_fd is used in a simple blocking loop that waits for an API event, then processes the request.
To keep this scenario simple, make the event_fd a blocking event_fd.
During runtime/post-boot phase the event_fd is registered with polly alongside multiple other events (from multiple sources), and is only read when EPOLLIN is reported on it. Having it as a blocking event_fd is safe.
`[Author TODO: Meet these …

Fix API race during microVM configuration

---

README.md

Fixes #1217 
A Unix/Linux OS and `bash` are prerequisites to build Firecracker using the `tools/devtool` script.

readme: update the "Getting Started" section

---

src/logger/src/logger.rs
src/logger/src/metrics.rs
src/vmm/src/resources.rs
src/vmm/src/vmm_config/logger.rs
src/vmm/src/vmm_config/metrics.rs
src/vmm/src/vmm_config/mod.rs

Introduce some logger simplifications that will make it easier to work on #1675 
Introduce some logger simplifications that will make it easier to work on #1675 

Logger simplifications

---

MAINTAINERS.md

There was a typo in Serban Iorga's email.
I have fixed the typo in Serban Iorga's email.

Fix typo in Serban Iorga's email

---

src/snapshot/src/lib.rs
src/versionize/src/crc.rs
src/versionize/src/primitives.rs
tests/integration_tests/build/test_coverage.py

Fixes #1698 
Some more unit tests in snapshot crates.

Increase coverage for snapshot crates

---

tests/integration_tests/functional/test_logging.py

Improve the `test_logging.py` resilience to logging output delays.
Removed `log_file_contains_strings` from `test_logging.py` and used instead
`check_log_message`, which has retries, thus is more safe in checking content inside the logging output.
Signed-off-by: iulianbarbu <iul@amazon.com>

test_logging: removed log_file_contains_strings

---

src/snapshot/src/lib.rs
src/snapshot/src/persist.rs

Define trait Persist: interface for saving/restoring a component from state

---

CHANGELOG.md
docs/mmds.md
src/api_server/src/parsed_request.rs
src/api_server/src/request/mmds.rs
src/api_server/swagger/firecracker.yaml
src/devices/src/virtio/net/device.rs
src/dumbo/src/ns.rs
src/dumbo/src/tcp/handler.rs
src/micro_http/src/connection.rs
src/vmm/src/builder.rs
src/vmm/src/resources.rs
src/vmm/src/rpc_interface.rs
src/vmm/src/vmm_config/mmds.rs
src/vmm/src/vmm_config/mod.rs
src/vmm/src/vmm_config/net.rs
tests/framework/resources.py
tests/integration_tests/build/test_coverage.py
tests/integration_tests/functional/test_mmds.py

Fixes #1228 
This PR is a proposal for supporting custom IPv4 address configuration for our MicroVM Metadata Service. It comprises a new API for configuring the MMDS IPv4 address and some changes/refactoring in our current MMDS logic, for cleansing. 

Added MMDS custom IPv4 support

---

src/vmm/src/builder.rs
src/vmm/src/device_manager/mmio.rs
src/vmm/src/lib.rs
src/vmm/src/vstate.rs

Unblocks #1729 
Self explanatory.

aarch64: fix build warnings

---

src/devices/src/lib.rs
src/devices/src/virtio/queue.rs
src/devices/src/virtio/vsock/device.rs
src/devices/src/virtio/vsock/mod.rs
src/devices/src/virtio/vsock/persist.rs
src/devices/src/virtio/vsock/unix/muxer.rs
src/snapshot/src/lib.rs
src/snapshot/tests/test.rs
src/versionize/src/lib.rs
src/versionize/src/primitives.rs
src/versionize/tests/test.rs
src/versionize_derive/src/descriptors/enum_desc.rs

Implement Vsock Device serialization

---

src/snapshot/benches/basic.rs

Fixes build issue for the snapshot crate.
Fixes build issue for the snapshot crate.

[snapshot] fix build issue

---

src/snapshot/benches/README.md
src/snapshot/benches/basic.rs
src/snapshot/src/lib.rs
src/snapshot/tests/test.rs
tests/integration_tests/build/test_coverage.py

Snapshot crate code cleanup.

---

CHANGELOG.md
src/api_server/src/parsed_request.rs
src/api_server/src/request/machine_configuration.rs
src/api_server/src/request/mod.rs
src/api_server/src/request/snapshot.rs
src/api_server/swagger/firecracker.yaml
src/vmm/src/builder.rs
src/vmm/src/device_manager/mmio.rs
src/vmm/src/resources.rs
src/vmm/src/rpc_interface.rs
src/vmm/src/vmm_config/machine_config.rs
src/vmm/src/vmm_config/mod.rs
src/vmm/src/vmm_config/snapshot.rs
src/vmm/src/vstate.rs
tests/framework/resources.py
tests/integration_tests/build/test_coverage.py
tests/integration_tests/functional/test_api.py

Fixes: #1796, #1798.
This is a proposal for the Snapshot API calls through which I tried to keep the API as RESTful as it can be with the newly added actions. I will update the integration tests with the snapshotting resources once we're okay with certain paths / calls.

Snapshot API calls

---

src/dumbo/src/tcp/handler.rs
src/vmm/src/vmm_config/net.rs

Attempt to close #1868
Move test functions into test module
Hello, this is my first attempt to contribute and I'm entirely new to this area :) I haven't finished setting up a dev environment and running `cargo test` fails on linker but since this is a trivial change I thought it might be okay to just start a PR?

Move test functions into test module

---

docs/network-setup.md

Make the network setup example documentation a little bit more useful, by adding instructions for using a config file, and supporting DNS.

Add DNS and config file help to network-setup.md

---

src/firecracker/src/api_server_adapter.rs
src/firecracker/src/main.rs
src/logger/src/init.rs
src/logger/src/lib.rs
src/logger/src/logger.rs
src/logger/src/metrics.rs
src/vmm/src/resources.rs
src/vmm/src/rpc_interface.rs
src/vmm/src/vmm_config/instance_info.rs
src/vmm/src/vmm_config/logger.rs

partially addresses #1675 
- add more unit tests for the logger
- simplify some internal logger methods
- move logger init logic to separate component

logger improvements

---

tests/integration_tests/functional/test_rate_limiter.py

Fixes #1809 
This commit makes the test more reliable by using a fixed TCP window size and disabling TCP Nagle.
It is however still not ideal. The problem is that it relies on iperf3 which measures transport protocol bandwidth and compares that to raw wire bandwidth. To make matters worse, iperf3 and the guest kernel vary transmission parameters in their attempt to maximize TCP throughput. For short test durations like ours, resulting numbers show jitter.
Another thing we could try is to move to UDP iperf3 tests, but that's also not trivial because UDP packet size is not configurable in iperf3 and it uses small packets making the total difference between raw bytes and protocol bytes even larger.
An accurate test should use a low level tool to send an exact number of raw bytes and measure …

tests: fix net rate limiters test

---

src/mmds/src/lib.rs

Sanitize Mmds request URI

---

src/devices/src/virtio/block/request.rs

The `status` and `data` (if present) descriptors' addresses were not validated, relying on the assumption that the guest driver sends valid buffers in the virtq. An `unwrap` in the block device's `process_queue` function may have failed on invalid input.
Added an extra validation for the descriptors' addresses. The `data` descriptor must point to a valid address in the guest's physical memory space, with enough room to fit the data (specified by `data.len`). The `status` descriptor must also point at a valid address which fits the 4-byte status written there by the device after processing the request. …

virtio blk: check descriptor valid addresses when parsing an operation request

---

docs/design.md

Signed-off-by: not required <bertdeb@gmail.com>
`[This sentence is not grammatically correct.]`
`[Amend sentence to make it grammatically correct.]`
- [X ] All commits in this PR are signed (`git commit -s`).
- [X ] The reason for this PR is clearly provided (issue no. or explanation).
- [X ] The description of changes is clear and encompassing.
- [X ] Any required documentation changes (code and docs) are included in this PR.

docs: remove extra article 'the'

---

.github/pull_request_template.md

We lack a remainder for reviewers & PR authors, to ensure that all added/changed functionality is tested.
Added a checkbox inside the GitHub PR template which states that functionality is tested.
It must be checked by Pauthors and verified by the reviewer.
- ~~[] Any required documentation changes (code and docs) are included in this PR.~~
- ~~[] Any newly added `unsafe` code is properly documented.~~
- ~~[ ] Any API changes are reflected in `firecracker/swagger.yaml`.~~
- ~~[ ] Any user-facing changes are mentioned in `CHANGELOG.md`.~~

PR_template: ensure tests are added checkbox

---

Cargo.lock
src/arch/Cargo.toml
src/cpuid/Cargo.toml
src/devices/Cargo.toml
src/mmds/Cargo.toml
src/rate_limiter/Cargo.toml
src/snapshot/Cargo.toml
src/vmm/Cargo.toml

Upgrade to Versionize v0.1.1.

---

tests/framework/artifacts.py
tests/framework/builder.py
tests/framework/microvm.py
tests/framework/resources.py
tests/host_tools/network.py
tests/host_tools/snapshot_helper.py
tests/integration_tests/functional/test_pause_resume.py
tests/integration_tests/functional/test_snapshot_basic.py

Add snapshot integration tests.

---

tests/host_tools/memory.py

This PR fixes a bug in the memory monitor's message. The memory usage is determined by adding kilobytes, but the message was mentioning megabytes.

tests: fix memory usage exceeded message

---

tests/framework/builder.py
tests/framework/microvm.py
tests/integration_tests/functional/test_snapshot_basic.py
tests/integration_tests/performance/test_snapshot_perf.py

Fixes #2028
-  Add metrics setup in build_from_snapshot()
-  Add test to sample 3 load and 3 create latencies
-  Add some temporary baseline latencies

Add snapshot performance integration test.

---

Cargo.lock

Upgrade to Versionize v0.1.2

---

src/vmm/src/lib.rs
src/vmm/src/vstate/vcpu.rs
src/vmm/tests/integration_tests.rs

Improves error handling in VMM.

VMM: Improve vCPU error handling when restoring snapshots.

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md

#2004 
Add bug and feature request Github templates.  Examples can be viewed/tested [here](https://github.com/tnotw/firecracker/issues)

issue_templates: Add bug and feature request templates.

---

tests/integration_tests/functional/test_mmds.py

#2017 
Added an integration test which checks whether the guest mmds can hang after receiving a malformed request with a content length header value larger than the actual size of the payload.

mmds: add integration test for mmds guest hang

---

tests/framework/microvm.py
tests/integration_tests/functional/test_signals.py

We need to also check that metrics are updated
upon receiving the aforementioned signals.
- Configure metrics through a path to a file
- Assert that metrics appear after InstanceStart
- Assert that metrics ["signals"][sigbus/sigsegcv] is 1 after intercepting the signal

CI: improve test_sigbus_sigsegv test

---

CHANGELOG.md
docs/snapshotting/snapshot-support.md
src/api_server/src/lib.rs
src/api_server/src/request/snapshot.rs
src/api_server/swagger/firecracker.yaml
src/vmm/src/persist.rs
src/vmm/src/rpc_interface.rs
src/vmm/src/vmm_config/snapshot.rs
src/vmm/tests/integration_tests.rs
tests/integration_tests/build/test_coverage.py

Incremental/diff snapshot support is currently broken, fixing it is tracked in #1997.
Because the fix is going to take a while, this PR disables diff snapshots support.
The commit in this PR will be reverted once we can correctly support incremental snapshots.

snapshot: disable diff snapshots support

---

src/logger/src/metrics.rs
src/vmm/src/lib.rs
src/vmm/src/signal_handler.rs
tests/integration_tests/build/test_coverage.py
tests/integration_tests/functional/test_signals.py

Signed-off-by: cihodar <cihodar@amazon.com>
Fixes #2093 
Added signal handlers for SIGXFSZ, SIGXCPU and SIGPIPE

Added more signal handlers

---

src/devices/src/virtio/block/persist.rs
src/devices/src/virtio/net/persist.rs
src/devices/src/virtio/persist.rs
src/devices/src/virtio/vsock/persist.rs

When resuming from snapshot do full queue validation on activated devices.
For devices not yet activated, we stick to the minimal queue sanity checks. Full queue validation will happen later during device activation anyway.

snapshot: improve queue restore sanity checks

---

Cargo.lock

#1991  Reason for This PR
Update versionize crate.
Update cargo.lock.

Update versionize to v0.1.3.

---

docs/snapshotting/snapshot-support.md

Improve documentation.
Update the snapshot documentation.

Update snapshot documentation.

---

docs/mmds/mmds-user-guide.md

The commands for updating MMDS were incorrect. Fixing them.
Fixing documentation. 
The commands for MMDS updates were incorrect. There were " around the data field on the MMDS update commands. That is a syntax error. It should be '. Fixing that. 

Fix documentation for MMDS.

---

src/api_server/src/parsed_request.rs

When an HTTP request path does not contain a leading '/' character, the
API server will crash, also killing the Firecracker process.
Reported-by: Davide Berardi <berardi.dav@gmail.com>
Fixes #2123 
Avoid indexing starting from `[1..]` when the string is empty.

micro_http: fix crash when calling 'GET none ...'

---

tests/integration_tests/performance/test_snapshot_perf.py

#2159 
enables snapshot perf tests on AMD

enables snapshot perf tests on AMD

---

src/snapshot/Cargo.toml

remove accidental comments
remove accidental comments

remove accidental comments

---

src/cpuid/src/transformer/amd.rs

Fixes #222 
Some versions of kernel may return the 0xB leaf for AMD even if this is an Intel-specific leaf. So we have to remove it.

remove 0xB leaf on AMD

---

CHANGELOG.md
Cargo.lock
src/api_server/swagger/firecracker.yaml
src/firecracker/Cargo.toml
src/jailer/Cargo.toml

New release.
Provided in  commit messages.

Release v0.22.1.

---

CHANGELOG.md
Cargo.lock
src/api_server/swagger/firecracker.yaml
src/firecracker/Cargo.toml
src/jailer/Cargo.toml

Release v0.21.3.

---

docs/prod-host-setup.md

update prod-host-setup.md for AMD
update prod-host-setup.md for AMD

update prod-host-setup.md for AMD

---

SPECIFICATION.md

The documentation was out of date.

Update Specification for v0.23.0

---

FAQ.md

FAQ.md needed updates with the latest supported CPUs

v0.23.0 docs: update FAQ with supported CPUs.

---

src/api_server/src/lib.rs

Signed-off-by: Alexandru Cihodaru <cihodar@amazon.com>
Made handle_request public. The changes are necessary so Firecracker could be integrated easier with other projects.

Made handle request public

---

Cargo.lock
src/snapshot/Cargo.toml

[snapshot] fix bench build
fix `cargo build --all --all-targets ` issues the following error because of the missing criterion dependency.
```
error[E0432]: unresolved import `criterion`
--> src/snapshot/benches/main.rs:3:5
|
3 | use criterion::{black_box, criterion_group, criterion_main, Criterion};
|     ^^^^^^^^^ use of undeclared type or module `criterion`
error[E0432]: unresolved import `criterion`
--> src/snapshot/benches/version_map.rs:3:5
|
3 | use criterion::{black_box, criterion_group, Criterion};
|     ^^^^^^^^^ use of undeclared type or module `criterion`
error: cannot determine resolution for the macro `criterion_group`
--> src/snapshot/benches/version_map.rs:140:1
|
140 | criterion_group! {
| ^^^^^^^^^^^^^^^
|
= note: import resolution is stuck, try simplifying macro imports …
```

[snapshot] fix bench build

---

README.md
docs/design.md
docs/prod-host-setup.md
docs/snapshotting/snapshot-support.md

Cherry-picked relevant documentation updates for the v0.23.0 release.
- various doc updates, including: release pace, prod-host-setup, snapshot security & uniqueness

v0.23.0: cherry-pick docs updates from master

---

.mailmap
CHANGELOG.md
CREDITS.md
src/api_server/swagger/firecracker.yaml
src/firecracker/Cargo.toml
src/jailer/Cargo.toml

Changes automatically generated with `devtool prepare-release`.

Release v0.23.0

---

Cargo.lock

Lockfile was not updated in previous PR

[v0.23.0] Update Cargo.lock for v0.23.0

---

tests/integration_tests/build/test_coverage.py
tests/integration_tests/functional/test_balloon.py

There is an intermittent faliure in the feature branch balloon tests and coverage is not up to date.
Updated coverage and fixed intermittent failure in balloon tests.

Fix intermittent failure in balloon test and update coverage on feature branch

---

tests/integration_tests/functional/test_logging.py
tests/integration_tests/functional/test_pause_resume.py
tests/integration_tests/functional/test_snapshot_basic.py
tests/integration_tests/performance/test_snapshot_perf.py

CI: enable snapshot tests on aarch64

---

tests/framework/builder.py
tests/framework/microvm.py
tests/framework/utils.py
tests/integration_tests/performance/test_network_latency.py

The test is failing intermittently.
* Pinned uVM threads to physical cores.
* Adjusted latency baseline and delta to cover lows and highs which were observed outside the current interval.
* Fixed a mapping issue: AVG latency was MAX latency.
- ~~[] Any required documentation changes (code and docs) are included in this PR.~~
- ~~[] Any newly added `unsafe` code is properly documented.~~
- ~~[] Any API changes are reflected in `firecracker/swagger.yaml`.~~
- ~~[] Any user-facing changes are mentioned in `CHANGELOG.md`.~~
- ~~[] All added/changed functionality is …

Improvements around network latency performance test

---

CHANGELOG.md
docs/ballooning.md
src/vmm/src/rpc_interface.rs

The balloon device needs public documentation.
Added public documentation for the balloon device.

[Balloon] Added public documentation

---

CHARTER.md

Adjusted the Firecracker tenets based on what we have learned over the past two years.
- The **Built-In Security** tenet now expresses the team's focus on security investment and security best practices.
- The The **Light-Weight Virtualization** tenet has been reworded to emphasize on accurate overhead measurement and a strive to minimize overhead. A single fixed overhead is not really applicable, since it's based on microVM configuration).
- The **Minimalist in Features** tenet gained a clarification that will deprecate features that become unneeded or duplicated.

charter: updated tenets

---

tests/integration_tests/functional/test_balloon.py

The intermittent fail in `test_reinflate_balloon` has resurfaced and
this commit introduces the (hopefully) final fix for this test.
Fixes #2257 

Fix reinflate test intermittent fail

---

CHANGELOG.md
Cargo.lock
docs/snapshotting/snapshot-support.md
src/api_server/src/lib.rs
src/api_server/src/request/snapshot.rs
src/api_server/swagger/firecracker.yaml
src/arch/Cargo.toml
src/devices/Cargo.toml
src/kernel/Cargo.toml
src/vm-memory/Cargo.toml
src/vm-memory/src/bitmap.rs
src/vm-memory/src/lib.rs
src/vm-memory/src/mmap.rs
src/vmm/Cargo.toml
src/vmm/src/builder.rs
src/vmm/src/memory_snapshot.rs
src/vmm/src/persist.rs
src/vmm/src/rpc_interface.rs
src/vmm/src/vmm_config/snapshot.rs
src/vmm/tests/integration_tests.rs
src/vmm/tests/mock_resources/mod.rs
tests/framework/builder.py
tests/integration_tests/build/test_coverage.py
tests/integration_tests/functional/test_snapshot_basic.py

We need to bring the new diff snapshots functionality from the feature branch into master.
Added logic to track dirty pages for diff snapshots.

[Snapshot] Merge feature/diff snapshot and master

---

tests/integration_tests/functional/test_balloon.py

This commit enables the tests that ensured
snapshotting works as expected on the balloon device.

CI: enable snapshot related tests

---

src/snapshot/src/lib.rs

When trying to load a snapshot shorter than `size_of::<u64>()`, the snapshot load function would subtract with overflow and cause Firecracker to panic.
Added a `checked_sub` to handle the overflow and catch the panic.

Check snapshot file size to avoid overflowing on calculating snapshot length

---

tests/integration_tests/performance/test_network_latency.py

Performance pipeline runs now on 5.4 AL2 hosts.
Updated the test network latency baselines.
~~- [] Any required documentation changes (code and docs) are included in this PR.~~
~~- [] Any newly added `unsafe` code is properly documented.~~
~~- [] Any API changes are reflected in `firecracker/swagger.yaml`.~~
~~- [] Any user-facing changes are mentioned in `CHANGELOG.md`.~~
~~- [] All added/changed functionality is tested.~~

[performance] tests: updated net latency baseline

---

CHANGELOG.md
src/api_server/swagger/firecracker.yaml
tests/framework/microvm.py
tests/framework/resources.py

tests: check InstanceInfo field on start()

---

src/api_server/swagger/firecracker.yaml
tests/integration_tests/style/test_swagger.py
tools/devctr/Dockerfile.x86_64
tools/devtool

Fixes #2294 
Added [swagger-cli](https://apitools.dev/swagger-cli/) to our dev container and used it in CI to validate our API swagger spec file.
Fixed invalid `instanceInfo` definition in our swagger spec file.

Fix swagger definition and add automated validation

---

CHANGELOG.md
src/api_server/src/request/drive.rs
src/api_server/swagger/firecracker.yaml
src/devices/src/virtio/block/device.rs
src/vmm/src/lib.rs
src/vmm/src/rpc_interface.rs
src/vmm/src/vmm_config/drive.rs
src/vmm/src/vmm_config/mod.rs
src/vmm/src/vmm_config/net.rs
tests/integration_tests/build/test_coverage.py
tests/integration_tests/functional/test_api.py
tests/integration_tests/functional/test_drives.py

Partially fixes #1338 
Provided in commits.

Add support for patching the block ratelimiter

---

tests/integration_tests/performance/test_snapshot_perf.py

#2324 
Cherry pick snapshot perf tests fixes from master. Otherwise all PRs will fail on this branch.

Cherry pick snapshot perf tests fixes from master

---

tests/framework/artifacts.py
tests/framework/builder.py
tests/framework/microvms.py
tests/integration_tests/functional/test_balloon.py
tests/integration_tests/functional/test_snapshot_advanced.py
tests/integration_tests/functional/test_snapshot_version.py
tests/integration_tests/performance/test_network_latency.py

Add snapshot restore integration tests across all supported versions and devices.

---

src/arch/src/aarch64/gic/dist_regs.rs
src/arch/src/aarch64/gic/icc_regs.rs
src/arch/src/aarch64/gic/redist_regs.rs

#2239 
- GIC registers fixes
- simplify gic registers logic
- Improve readability for VGIC' distributor register handling

Improve readability for VGIC distributor register handling

---

src/devices/src/virtio/balloon/device.rs
src/devices/src/virtio/balloon/mod.rs
src/devices/src/virtio/balloon/utils.rs
tests/integration_tests/build/test_coverage.py

Improve security posture and stability of the virtio-balloon emulation.
Provided in commits.

Add virtio-balloon sanity checks.

---

NOTICE

We need to give credit in our release artefacts to the CrosVM BSD-3-Clause license we are carrying it over.
Update NOTICE file to include credit for BSD-3-Clause license.

Updating NOTICE to give credit to the CrosVM BSD-3-Clause License.

---

src/vmm/src/persist.rs
src/vmm/tests/integration_tests.rs

Add sanity checks before the load path attempts to start building the microvm.

LoadSnapshot: Implement microvm state sanity checks.

---

tests/integration_tests/performance/test_snapshot_perf.py

Enable snapshot performance integration tests for aarch64.
**Obs**: this is created against this [PR](https://github.com/firecracker-microvm/firecracker/pull/2351) so you may be seeing more commits than expected. You can only take into account the last 4 commits.

[ARM] enable snapshot performance tests

---

.gitignore
tests/integration_tests/performance/test_vsock_throughput.py
tests/integration_tests/performance/vsock_throughput_test_config.py
tools/devctr/Dockerfile.x86_64
tools/devtool

Lack of Vsock performance test
Add performance test for vsock throughput.

Vsock performance test

---

src/arch/src/aarch64/gic/mod.rs
src/arch/src/aarch64/gic/regs/dist_regs.rs
src/arch/src/aarch64/gic/regs/icc_regs.rs
src/arch/src/aarch64/gic/regs/mod.rs
src/arch/src/aarch64/gic/regs/redist_regs.rs
src/vmm/src/lib.rs
src/vmm/src/vstate/vm.rs
tests/integration_tests/performance/test_snapshot_perf.py

Fixes #2234 
Fixes #2239 
- Refactor the logic for saving/restoring GIC regs in order to make it more generic and reusable.
- Reorganizing the GIC registers state. 
Each GIC register has different values for each CPU and can be represented as a `Vec<REG_CHUNK_SIZE>`. So we serialize a list of Registers as `Vec<Vec<Vec<REG_CHUNK_SIZE>>>`. The levels of imbrication signify:
- the list of CPUs
- the list of registers for each CPU
- the data for each register
Before, all this data was compressed in a `Vec<REG_CHUNK_SIZE>` , leading to information loss. For example creating a snapshot on a Firecracker version with 100 IRQs and trying to restore it on a system with 1000 IRQs would have been impossible.
**This is designed as an incremental PR in order to make it easier to be reviewed.** 
Next …

[aarch64][snap] Reorganizing the GIC registers state

---

tests/conftest.py

Temporarily disable these tests since we have
seen multiple intermittent failures.
Frequent intermittent failures.
Temporarily ignore snapshot performance tests on AMD.

CI: ignore snapshot related tests on AMD

---

src/arch/src/aarch64/gic/mod.rs
src/arch/src/aarch64/gic/regs/icc_regs.rs
tests/integration_tests/build/test_coverage.py

Improvements for #2234
[aarch64][snap] update ICC regs state

[aarch64][snap] update ICC regs state

---

docs/snapshotting/snapshot-support.md

There was no example in the documentation for merging `diff` snapshot layers.
Added an example in the documentation for merging `diff` snapshot layers.

Added example usage for merging diff snaps in docs

---

src/vmm/src/vstate/vcpu/mod.rs
tests/integration_tests/build/test_coverage.py
tests/integration_tests/functional/test_error_code.py

ENOSYS was not handled and they caused `unexpected` errors.
Added handler for ENOSYS on aarch64.

Catch enosys

---

docs/api_requests/patch-block.md

Update PATCH block device documentation.

---

docs/prod-host-setup.md

Talk about the architectural decision of allowing guest
access to the host physical counter.

docs: mention virtualization design decision for ARM

---

CHANGELOG.md
docs/snapshotting/snapshot-support.md
docs/snapshotting/versioning.md

Documentation update.
Please see commit messages.

Documentation updates.

---

CHANGELOG.md
CREDITS.md
Cargo.lock
src/api_server/swagger/firecracker.yaml
src/firecracker/Cargo.toml
src/jailer/Cargo.toml

Prepare v0.24.0 release.

---

CHANGELOG.md
CREDITS.md
Cargo.lock
src/api_server/swagger/firecracker.yaml
src/firecracker/Cargo.toml
src/jailer/Cargo.toml

Merge v0.24.0 release branch.

---

Cargo.lock

Cargo update.

---

.gitlint
tests/framework/gitlint_rules.py
tests/integration_tests/style/test_gitlint.py
tools/devctr/Dockerfile.x86_64
tools/devtool

CI: add git commit message linter

---

docs/getting-started.md

Closes #2394 
* Adjusted firecracker binary download flow to latest release model.

doc: adjusted download flow to new release model

---

MAINTAINERS.md

The maintainers list was outdated.
Updating the Firecracker maintainers list

docs: updating Firecracker maintainer list

---

src/vmm/src/vstate/vcpu/mod.rs
tests/integration_tests/build/test_coverage.py

Created unit tests for run_emulation function.
Added test cases for run_emulation function.

Added test cases for run_emulation function

---

tests/integration_tests/functional/test_pause_resume.py

This patch adds a PyTest for checking DescribeInstance
different states.
Signed-off-by: berciuliviu <lberciu@amazon.com>
Fixes issue [#2355](https://github.com/firecracker-microvm/firecracker/issues/2355)
Add a PyTest that verifies the DescribeInstance "Running", "Not started" and "Paused" states.

Add DescribeInstance integration test

---

src/api_server/src/lib.rs
src/firecracker/src/api_server_adapter.rs

Cross checking an item off [this list](https://github.com/firecracker-microvm/firecracker/issues/609).

api_server: add documentation for public items

---

docs/snapshotting/snapshot-support.md

Signed-off-by: berciuliviu <lberciu@amazon.com>
Fixes [2068](https://github.com/firecracker-microvm/firecracker/issues/2068)
Add details regarding snapshot CRC verification.

Add snapshot doc CRC detail

---

CHANGELOG.md
Cargo.lock
src/api_server/swagger/firecracker.yaml
src/devices/src/virtio/block/device.rs
src/devices/src/virtio/block/event_handler.rs
src/devices/src/virtio/block/request.rs
src/firecracker/Cargo.toml
src/jailer/Cargo.toml
tests/framework/artifacts.py
tests/framework/utils.py
tests/integration_tests/build/test_coverage.py
tests/integration_tests/functional/test_drives.py
tests/integration_tests/functional/test_snapshot_version.py
tests/integration_tests/performance/test_snapshot_perf.py

v0.23.2 patch release
Adapt patch for block off-by-one error from mainline.
Update changelog and coverage.
Fix snapshot tests
Release commit

Release v0.23.2

---

tests/framework/microvm.py
tests/framework/state_machine.py

Serial I/O test fixes.

---

src/arch/src/aarch64/gic/regs/mod.rs
src/cpuid/src/template/intel/mod.rs
src/utils/src/signal.rs
src/vmm/src/utilities/mod.rs
tests/integration_tests/style/test_licenses.py
tests/integration_tests/style/test_rust.py
tools/update-credits.sh

Fix tests checking for existence of copyright messages

---

src/vmm/src/vstate/system.rs

Signed-off-by: binoychitale <binoychitale@gmail.com>
Fixes #2418

#2418 Update KVM compatibility checks

---

src/api_server/src/parsed_request.rs

Deduplicate hard coded HTTP responses and requests in tests as per #2293.
- In `src/api_server/src/parsed_request.rs` testing:
- Remove hard-coded literal HTTP responses and requests in tests.
- `fn http_response(body: &str, status_code: i32) -> String` is introduced
- Given the body and string, format to fit HTTP response string
- `fn http_request(request_type: &str, end_point: &str, body: &str) -> String` is introduced
- Given the request type, end point, and content fit to HTTP request string.
- Every instance of this uses `.as_bytes()` in the testing, but I left it to return a String for consistency sake.

dedupe literal HTTP response and request strings

---

src/arch/src/aarch64/fdt.rs
src/arch/src/aarch64/regs.rs
src/vmm/src/vstate/vcpu/aarch64.rs
src/vmm/src/vstate/vcpu/mod.rs
tests/integration_tests/build/test_coverage.py

Unit tests for aarch64 logic
Refined some logic and added unit tests
for those part that can benefit from them.

aarch64: unit tests for aarch64 logic

---

src/firecracker/src/api_server_adapter.rs
src/firecracker/src/main.rs
src/vmm/src/signal_handler.rs
src/vmm/src/vstate/vcpu/mod.rs
tests/integration_tests/build/test_coverage.py
tests/integration_tests/functional/test_signals.py

https://github.com/firecracker-microvm/firecracker/issues/2452 
Resources:
https://man7.org/linux/man-pages/man2/signalfd.2.html
https://man7.org/linux/man-pages/man7/signal.7.html
View commit messages

Replace unsafe signal handlers with signalfd mechanism.

---

CHANGELOG.md
Cargo.lock
src/api_server/swagger/firecracker.yaml
src/firecracker/Cargo.toml
src/jailer/Cargo.toml
src/vmm/src/signal_handler.rs
tests/framework/utils_vsock.py
tests/integration_tests/functional/test_signals.py
tests/integration_tests/functional/test_vsock.py

Apply patch for gracefully handling SIGPIPE and release v0.23.3

Release v0.23.3

---

tests/integration_tests/performance/test_process_startup_time.py

Increase ARM process startup time baseline

---

Cargo.lock
src/arch/Cargo.toml
src/arch/src/aarch64/cache_info.rs
src/arch/src/aarch64/fdt.rs

Fixes #2407 
* the commits contain the info needed

aarch64: relax cache topology restrictions

---

CHANGELOG.md
CHARTER.md
CONTRIBUTING.md
SPECIFICATION.md
docs/design.md
docs/getting-started.md
docs/jailer.md
src/arch/src/x86_64/msr.rs
src/net_gen/src/iff.rs
src/vmm/src/default_syscalls/filters.rs
src/vmm/src/utilities/mock_seccomp/mod.rs
src/vmm/src/vstate/vm.rs
src/vmm/tests/integration_tests.rs
tests/conftest.py
tests/integration_tests/security/test_seccomp.py
tests/integration_tests/style/test_gitlint.py

Firecracker needs to use inclusive language.
Changed code and documentation to use inclusive language as follows:
- replace _master_ with _main_
- replace _whitelist_ (as a noun) with _allow list_
- replace _whitelist_ (as a verb) with _allow_
- replace _blacklist_ (as a verb) with _deny_

Used inclusive language

---

src/logger/src/metrics.rs

Fixes #2486 
Added comments for `Metrics::init` and `Metrics::write` to state that these functions should only be used in a single threaded scenario.

[Metrics] Add warning comment for race condition in metrics initialization

---

docs/dev-machine-setup.md

Signed-off-by: Tobias Pfandzelter <pfandzelter@campus.tu-berlin.de>
The setup documentation for development on Google Cloud was complete but had some subtle bugs and missing information that made it hard for newbies (like myself) to get started. Namely, information about availability of nested virtualization was missing, and some whitespace characters in code/shell listings made it difficult to copy/paste commands.
I have added the missing information and fixed formatting and whitespace to make everything a bit easier.
Alongside changes to the documentation I set up my own GCP development instance so I could verify everything.
~~- [ ] Any newly added `unsafe` code is properly …

Update GCP Development Machine Setup Documentation

---

tests/integration_tests/performance/test_block_performance.py

Before running block IO performance test we drop caches using
`/proc/sys/vm/drop_caches` but that only drops clean caches, dirty
ones are kept around, more details can be found at
https://www.kernel.org/doc/Documentation/sysctl/vm.txt
Before dropping caches, run a `sync` command which will flush
all dirty FS cache entries.

tests: sync FS before block IO performance test

---

src/vmm/src/persist.rs
src/vmm/src/version_map.rs
tests/integration_tests/functional/test_snapshot_version.py

Fixes https://github.com/firecracker-microvm/firecracker/issues/2467
Conditionally excludes v0.23 from version mapping for aarch64.  

Add conditional target architecture when getting supported versions

---

docs/getting-started.md

#2513 
docs: update kernel links in quickstart script

docs: update kernel links in quickstart script

---

src/vmm/src/persist.rs
tests/framework/builder.py
tests/framework/microvm.py
tests/framework/utils_vsock.py
tests/integration_tests/functional/test_api.py
tests/integration_tests/functional/test_snapshot_basic.py
tests/integration_tests/functional/test_snapshot_version.py

Fix #2005 and #2232.
Described in commit messages.

Add snapshot negative tests and fix vsock snapshot intermittent failure

---

CHANGELOG.md

changelog: remove duplicate `Fixed` section

---

CHANGELOG.md
CREDITS.md
Cargo.lock
src/api_server/swagger/firecracker.yaml
src/firecracker/Cargo.toml
src/jailer/Cargo.toml

v0.24.3 patch release
Release commit.

Release v0.24.3

---

tests/framework/defs.py
tests/framework/report.py
tests/framework/scheduler.py
tests/integration_tests/build/test_binary_size.py

Add functionality for test reports. 
Implement basic test report functionality and add an example for one of the tests.

Add functionality for generating test reports

---

CHANGELOG.md
Cargo.lock
docs/prod-host-setup.md
src/api_server/swagger/firecracker.yaml
src/firecracker/Cargo.toml
src/firecracker/src/main.rs
src/jailer/Cargo.toml
tests/integration_tests/build/test_coverage.py
tests/integration_tests/security/test_ssbd_mitigation.py
tests/integration_tests/style/test_rust.py

Backport SSBD mitigation fix and release firecracker v0.24.4
Backport SSBD mitigation fix and release firecracker v0.24.4

[v0.24.4] Backport SSBD mitigation fix and release firecracker v0.24.4

---

tools/devtool

[v0.24.4] devtool: add check_ssbd() to checkenv()

---

src/vmm/src/persist.rs
src/vmm/tests/integration_tests.rs
tests/integration_tests/functional/test_snapshot_basic.py
tests/integration_tests/functional/test_snapshot_version.py

Fixes #2520
Went through all the snapshot related errors and made more specific and accurate.

Make snapshot related errors more specific and user friendly 

---

tests/integration_tests/security/test_custom_seccomp.py

#2607 
fix test_failing_filter intermitent failures

[seccomp] fix test_failing_filter

---

src/devices/src/virtio/vsock/packet.rs

add unit tests for VsockPacket
add unit tests for VsockPacket

[vsock] add unit tests for VsockPacket

---

docs/prod-host-setup.md

https://github.com/firecracker-microvm/firecracker/issues/2452
- add a note and recommendation in the prod-host-setup.

prod-host-setup: recommendation on async-unsafe signal handlers

---

tests/integration_tests/functional/test_snapshot_basic.py

Comment is outdated.
Removed comment

CI: remove outdated comment

---

src/vmm/src/resources.rs

When providing an invalid JSON through the `--config-file` command line parameter, the error would be uninformative, for example:
```
2021-07-09T15:15:59.565949813 [anonymous-instance:main:ERROR:src/firecracker/src/main.rs:431] Configuration for VMM from one single json failed: InvalidJson
```
Make the error more explicit by encapsulating the error message from `serde_json` in the error returned.
For the above scenario, the error should be something like:
```
2021-07-09T15:29:41.086912506 [anonymous-instance:main:ERROR:src/firecracker/src/main.rs:431] Configuration for VMM from one single json failed: InvalidJson(Error("expected value", line: 1, column: 1))
```
`[Author TODO: …

Make config file JSON error more explicit

---

tests/framework/defs.py
tests/framework/jailer.py
tests/framework/microvm.py
tests/integration_tests/security/test_jail.py

Fixes #2602
See commit messages.

Fix test cleanup

---

tests/integration_tests/functional/test_cpu_features.py

Added integration tests for exposed CPUID feature. https://github.com/firecracker-microvm/firecracker/issues/342
Added check for exposed cpuid features

Add tests for CPUID exposed features

---

CHANGELOG.md
Cargo.lock
src/api_server/swagger/firecracker.yaml
src/firecracker/Cargo.toml
src/jailer/Cargo.toml

Release v0.23.5

---

CHANGELOG.md
Cargo.lock
src/api_server/swagger/firecracker.yaml
src/firecracker/Cargo.toml
src/jailer/Cargo.toml

Release v0.24.5

---

CHANGELOG.md
CREDITS.md
Cargo.lock
src/api_server/swagger/firecracker.yaml
src/firecracker/Cargo.toml
src/jailer/Cargo.toml
src/seccompiler/Cargo.toml
tests/integration_tests/build/test_binary_size.py

release v0.25.0

---

CHANGELOG.md
CREDITS.md
Cargo.lock
docs/jailer.md
docs/prod-host-setup.md
resources/seccomp/aarch64-unknown-linux-musl.json
resources/seccomp/x86_64-unknown-linux-musl.json
src/api_server/swagger/firecracker.yaml
src/devices/src/virtio/vsock/csm/connection.rs
src/devices/src/virtio/vsock/device.rs
src/devices/src/virtio/vsock/packet.rs
src/firecracker/Cargo.toml
src/jailer/Cargo.toml
src/jailer/src/env.rs
src/jailer/src/main.rs
src/jailer/src/resource_limits.rs
src/seccompiler/Cargo.toml
tests/framework/jailer.py
tests/integration_tests/build/test_binary_size.py
tests/integration_tests/build/test_coverage.py
tests/integration_tests/functional/test_api.py
tests/integration_tests/security/test_jail.py

Merge v0.25.0 commits to main 
Cherry-pick v0.25.0 commits to main.
There were no conflicts during cherry-pick. However, the integration tests docs needed to be expended to contain `@type`, for test reports generation (this feature was added as part of v0.26-wip).

Merge v0.25.0 commits to main 

---

Cargo.lock
tests/integration_tests/build/test_coverage.py

cargo update

---

CHANGELOG.md
Cargo.lock
src/api_server/swagger/firecracker.yaml
src/firecracker/Cargo.toml
src/jailer/Cargo.toml
tests/integration_tests/build/test_coverage.py

release v0.24.6

---

docs/network-setup.md

Signed-off-by: Colton J. McCurdy <replace>
https://github.com/firecracker-microvm/firecracker/issues/2618
Adds simple bridge networking documentation.

[docs] adds simple bridge networking documentation.

---

docs/jailer.md
src/jailer/src/env.rs
src/jailer/src/main.rs

The exec_into_new_pid_ns() function of the jailer should dispatch a new
process inside a new PID namespace.
It was done using unshare to a new PID namespace, then calling fork to
dispatch a process inside that namespace.
Changed it According to the TODO message - replaced this combo
with a single call to clone with the CLONE_NEWPID flag.
Besides the actual change inside the function, changed the jailer.md
documentation and the errors in main in order to fit the change.
A TODO comment inside the code. Also it is a preferred linux way to use clone
in order to create a new child process when possible. 
1. Changed the implementation of exec_into_new_pid_ns to use the clone function.
Before the call I created a wrapper to give clone and a capture that will be the 
Actual callback. The callback …

Change jailer's 'unshare' + 'exec' to 'clone'

---

CHANGELOG.md
Cargo.lock
docs/mmds/mmds-design.md
src/api_server/swagger/firecracker.yaml
src/firecracker/Cargo.toml
src/firecracker/src/main.rs
src/jailer/Cargo.toml
src/seccompiler/Cargo.toml
tests/integration_tests/functional/test_cmd_line_start.py

Release v0.25.1

---

CHANGELOG.md
Cargo.lock
src/api_server/swagger/firecracker.yaml
src/firecracker/Cargo.toml
src/jailer/Cargo.toml
src/seccompiler/Cargo.toml
tests/integration_tests/build/test_coverage.py

Release v0.25.2
Release v0.25.2

Release v0.25.2

---

docs/prod-host-setup.md

prod-host-setup: add kvm-pit recommendations

---

src/devices/src/virtio/block/device.rs
src/devices/src/virtio/block/io/async_io.rs
src/devices/src/virtio/block/io/mod.rs
src/devices/src/virtio/block/io/sync_io.rs
src/devices/src/virtio/block/persist.rs
src/devices/src/virtio/block/test_utils.rs
src/vmm/src/device_manager/persist.rs
tests/framework/utils_vsock.py
tests/integration_tests/build/test_coverage.py
tests/integration_tests/functional/test_snapshot_basic.py
tests/integration_tests/performance/test_snapshot_perf.py

[block][io_uring] Complete pending requests on snapshotting 
[block][io_uring] Complete pending requests on snapshotting 

[block][io_uring] Complete pending requests on snapshotting 

---

src/devices/src/virtio/block/device.rs
src/devices/src/virtio/block/io/mod.rs
src/devices/src/virtio/block/request.rs
src/io_uring/src/lib.rs
src/io_uring/src/queue/completion.rs
src/io_uring/src/queue/submission.rs
src/io_uring/tests/integration_tests.rs
tests/integration_tests/build/test_coverage.py

[io_uring] add FullRing error
[io_uring] add FullRing error

[io_uring] add FullCQueue error

---

.cargo/audit.toml
tests/framework/utils.py
tests/integration_tests/security/test_sec_audit.py

It's best to also deny warnings since they may hide Unsound or Unmaintained dependencies
View commit messages

cargo audit: deny warnings

---

.cargo/audit.toml
tests/framework/utils.py
tests/integration_tests/security/test_sec_audit.py

[v0.24] cargo audit: deny warnings

---

.cargo/audit.toml
tests/framework/utils.py
tests/integration_tests/security/test_sec_audit.py

Backport of https://github.com/firecracker-microvm/firecracker/pull/2858

[v0.25] cargo audit: deny warnings

---

src/jailer/src/env.rs

Suggested-by: Alexandru-Cezar Sardan <alsardan@amazon.com>
Checks cgroup name to not contain path traversal tokens, return error if it does.

jailer:Check cgroup name for path traversal tokens

---

tests/integration_tests/functional/test_drives.py

Repost of https://github.com/firecracker-microvm/firecracker/pull/2842, which was closed by accident.
Addressed @dianpopa's comments from previous PR

tests: remove catch..skip statements

---

src/api_server/swagger/firecracker.yaml

swagger: fix swagger codegen warnings

---

CHANGELOG.md
CREDITS.md
src/api_server/swagger/firecracker.yaml

Firecracker v1.0 release

---

tests/framework/utils_vsock.py

Fix some intermittent CI failures
View commit message

tests: fix race in HostEchoServer.exit()

---

src/mmds/src/token.rs
tests/framework/defs.py

This is to limit intermittent test failures on
some hosts.

tests: relax some test latencies

---

src/vmm/src/lib.rs

Before this fix, if creating the Vmm object would fail after restoring the vcpus during a snapshot restore, Firecracker would panic at the assert line inside Vmm's drop(). This is because when trying to propagate the error, the Vmm object would be dropped, without clearing out the contents of `vcpu_handles` (without joining the vcpu threads).
By explicitly calling `stop()` insinde the dropping logic of the Vmm object, we ensure that the Vmm is always ready to be teared down when the dropping logic kicks in.
- Explicitly call `stop()` inside drop to allow Vmm destruction during Vmm initialization process. …

vmm: fix drop logic for Vmm

---

tests/framework/artifacts.py
tests/framework/scheduler.py
tests/framework/utils_vsock.py
tests/integration_tests/functional/test_snapshot_advanced.py
tests/integration_tests/functional/test_snapshot_basic.py
tests/integration_tests/functional/test_snapshot_restore_cross_kernel.py
tests/integration_tests/functional/test_vsock.py
tests/integration_tests/performance/test_snapshot_restore_performance.py
tests/integration_tests/performance/test_vsock_throughput.py
tools/create_snapshot_artifact/main.py

Test that builds snapshot from artifacts and ensures devices are functional.

Build snapshot from artifacts and ensure devices are functional

---

Cargo.lock
docs/prod-host-setup.md
src/jailer/Cargo.toml
tests/integration_tests/build/test_coverage.py

prod-host-setup: Spectre-BHB recommendations

---

Cargo.lock
src/jailer/Cargo.toml
tests/integration_tests/build/test_coverage.py

Make cargo audit test pass again.
Bump version of regex dependency.

[firecracker-v1.0] cargo: update regex dependency

---

Cargo.lock
src/jailer/Cargo.toml
tests/integration_tests/build/test_coverage.py

Make cargo audit test pass again.
Bump version of regex dependency.

[firecracker-v0.25] cargo: update regex dependency

---

src/cpuid/src/brand_string.rs

Fixes #2914
- Fix a length check that accesses `some_slice[unsigned 0 - 1]` on systems without a Brand String
- Refactor that length check so we can write a test around it that doesn't depend on the system it's run on
Yes

Fix a panic in cpuid/brand_string.rs

---

tests/framework/artifacts.py

revert temporary CI folder

---

tests/integration_tests/functional/test_snapshot_restore_cross_kernel.py

Mmds version is now persisted across snapshot-restore,
so use the v2 requests to query the data store post-load.

test_snap_restore_cross_kernel: use MMDSV2

---

src/vmm/src/persist.rs

The feature will get enabled only when the
microVM uses a balloon device.
Fixes #

uffd: enable EVENT_REMOVE for ballooning

---

tests/integration_tests/performance/test_versioned_serialization_benchmark.py
tests/integration_tests/security/test_sec_audit.py

run some tests only on Intel

---

tests/host_tools/memory.py

The logic used for monitoring Firecracker's overhead
when running the integration tests would not actually
add up all the relevant mappings since the algorithm may not
be able to parse all the hex addresses.
Fixes #

CI: bug in memory monitor

---

src/snapshot/src/lib.rs
tests/integration_tests/build/test_coverage.py

Fixes https://github.com/firecracker-microvm/firecracker/issues/2953

remove unused struct field `format_version` on Snapshot

---

tools/parse_baselines/main.py

Improvements for the parse_baselines script
- fix some runtime errors
- write the output directly to the perf baselines files instead of the terminal
- for the block performance tests parse both the sync and async results

Improvements for the parse_baselines script

---

tests/integration_tests/performance/configs/test_block_performance_config_4.14.json
tests/integration_tests/performance/configs/test_block_performance_config_5.10.json
tests/integration_tests/performance/configs/test_network_tcp_throughput_config_4.14.json
tests/integration_tests/performance/configs/test_network_tcp_throughput_config_5.10.json
tests/integration_tests/performance/configs/test_vsock_throughput_config_4.14.json
tests/integration_tests/performance/configs/test_vsock_throughput_config_5.10.json

- update performance tests baselines
- small changes to the tool that parses baselines
Just submitting the PR for the moment. Didn't check yet if the results are better or worse than before.
Update performance tests baselines

Update performance tests baselines

---

tests/framework/http.py

Fixes #
AMD intermittent failures of type "too many open connections" 
Update max saved connections limit. See comment in the code.

AMD intermittent failures

---

tools/parse_baselines/main.py

[parse_baselines] update ARM test instance type
[parse_baselines] update ARM test instance type

[parse_baselines] update ARM test instance type

---

tests/integration_tests/functional/test_uffd.py
tools/parse_baselines/main.py

Release 1.1

---

tests/integration_tests/performance/test_network_latency.py

Follow up to https://github.com/firecracker-microvm/firecracker/pull/3017

tests/perf/net: update network latency baselines

---

tools/devtool

Add SHA256SUMS checksums when making a release

---

docs/prod-host-setup.md
tests/conftest.py

For better security recommendations regarding Spectre-like attacks should be improved and there should be testing regarding the presence of these mitigations.
1. Added an integration test checking for the presence of necessary SPECTREv2 mitigations.
2. Updated recommendations to better cover Spectre-like attacks.

Updating recommendations and checking mitigations regarding Spectre-like attacks

---

CONTRIBUTING.md
rusty-hook.toml

Fixes https://github.com/firecracker-microvm/firecracker/pull/3037#discussion_r915627662 & https://github.com/firecracker-microvm/firecracker/pull/3037#discussion_r915628587
See above.

Fixing git hooks setup docs

---

docs/mmds/mmds-user-guide.md

MMDS is GA as of fc v1.1.0, JSON format no
longer experimental.

mmds: small doc fix

---

docs/prod-host-setup.md

Update documentation with details on CVE-022-1789.

docs: add details on CVE-2022-1789

---

Cargo.lock
src/api_server/swagger/firecracker.yaml
src/firecracker/Cargo.toml
src/jailer/Cargo.toml
src/rebase-snap/Cargo.toml
src/seccompiler/Cargo.toml
tests/framework/microvm.py
tests/framework/scheduler.py
tests/framework/utils.py
tests/integration_tests/functional/test_api.py
tests/integration_tests/style/test_gitlint.py
tests/integration_tests/style/test_python.py
tools/devctr/Dockerfile.aarch64
tools/devctr/Dockerfile.x86_64
tools/devctr/ctr_gitconfig
tools/devctr/poetry.lock
tools/devtool
tools/parse_baselines/providers/block.py
tools/parse_baselines/providers/iperf3.py
tools/parse_baselines/providers/snapshot_restore.py

Prepare Firecracker v1.1.1 release.

release: prepare v1.1.1

---

CHANGELOG.md

Update Changeling version for the release.

release v1.1.1: update Changelog

---

README.md

Slack invite has expired.
#3072
Renew slack invite

README.md: renew slack invite

---

tools/devctr/poetry.lock
tools/devctr/pyproject.toml
tools/devtool

Add pandas package that can be used to manipulate large datasets in

devctr: add pandas

---

tests/integration_tests/performance/configs/test_network_tcp_throughput_config_4.14.json
tests/integration_tests/performance/configs/test_network_tcp_throughput_config_5.10.json

Update network throughput performance baselines

tests: update net tput perf baselines

---

tests/integration_tests/performance/configs/test_snap_restore_performance_config_4.14.json
tests/integration_tests/performance/configs/test_snap_restore_performance_config_5.10.json
tests/integration_tests/performance/test_snapshot_restore_performance.py
tools/parse_baselines/main.py
tools/parse_baselines/providers/snapshot_restore.py

Gather performance baselines for snapshot resume long running perf test on ARM.

Performance baselines for ARM snapshot resume latency

---

tests/integration_tests/functional/test_cpu_features.py

CI: enhance allowed CPU features on ARM guests

CI: enhance allowed CPU features on ARM guests

---

tests/framework/utils_cpuid.py
tests/framework/utils_imdsv2.py

IMDSv1 has problems and nowadays IMDSv2 is preferred.
Fixes #

Use IMDSv2

---

docs/prod-host-setup.md
tests/conftest.py

Update expected SPECTRE mitigations after RETbleed

---

docs/mmds/mmds-user-guide.md
src/mmds/src/lib.rs
tests/integration_tests/functional/test_mmds.py

Fix typos in the MMDS token header in README and in error messages.

Fix MMDS header typos in README and error messages

---

CHANGELOG.md
Cargo.lock
src/api_server/swagger/firecracker.yaml
src/firecracker/Cargo.toml
src/jailer/Cargo.toml
src/rebase-snap/Cargo.toml
src/seccompiler/Cargo.toml
tools/update-credits.sh

Release v1.1.2 - update relevant files
---

release v1.1.2 - prepare files

---

CHANGELOG.md
CREDITS.md
Cargo.lock
src/api_server/swagger/firecracker.yaml
src/firecracker/Cargo.toml
src/jailer/Cargo.toml
src/seccompiler/Cargo.toml
tests/framework/microvm.py
tests/framework/scheduler.py
tests/framework/utils.py
tests/integration_tests/functional/test_api.py
tests/integration_tests/style/test_gitlint.py
tests/integration_tests/style/test_python.py
tools/devctr/Dockerfile.aarch64
tools/devctr/Dockerfile.x86_64
tools/devctr/ctr_gitconfig
tools/devctr/poetry.lock
tools/devtool
tools/parse_baselines/providers/block.py
tools/parse_baselines/providers/iperf3.py
tools/parse_baselines/providers/snapshot_restore.py
tools/update-credits.sh

Release v1.0.1 - update relevant files
---

release v1.0.1 - prepare files

---

tests/integration_tests/performance/configs/test_snap_restore_performance_config_4.14.json

* gathered 4.14 baselines on Intel
Snapshot GA
---

[Snapshot] Performance baselines for Intel 4.14

---

CHANGELOG.md

updated fixed section of latest Unreleased section
Forgot about this when merging correspondent PR.
---

update CHANGELOG with self-DoS fix

---

docs/snapshotting/random-for-clones.md

Following recent changes to the Linux Kernel, synchronous reseeding of entropy pools has been changed and does not necessarily guarantee secure random number generation depending on the timeframe (see [reseed interval for CRNG](https://elixir.bootlin.com/linux/v4.14.295/source/drivers/char/random.c#L217) after a restored snapshot has been resumed.

Update snapshot-for-clones doc to reseed RNG

---

tests/integration_tests/build/test_coverage.py

* remove comment
* no longer using the mentioned bucket.
---

nit: remove outdated comment

---

docs/snapshotting/snapshot-support.md
docs/vsock.md

Docs: fix "Vsock device limitation" links

---

docs/snapshotting/snapshot-support.md

Signed-off-by: Vibha Acharya <vibharya@amazon.co.uk>
- Add details to the snapshot characteristics
- Fix vsock limitation link within doc
- Remove one of two known issues link
...
- Add clarity regarding snapshotting feature
- Vsock device limitation link
- There was one 'known issues' and one 'known issues and limitations' header in the doc
...
---

Docs: Update snapshot support doc

---

docs/snapshotting/versioning.md

Introduce T2S template in the documentation and provide guidance on usage.
T2S is not covered in the documentation.
---

doc: add info about T2S template

---

src/jailer/src/env.rs

There were a couple of places where the manual calls to `libc::close`, which also required an unsafe block, could be omitted if the original RAII resources was retained until the end of its scope where its `Drop` implementation would clean it up automatically.
Less `unsafe` blocks and automatic resource management.
---

jailer: rely on RAII to close open file descriptors

---

docs/snapshotting/snapshot-support.md

* #snapsafe related updates
* peformance related updates
* accuracy
---

snaps: doc update for accuracy purposes

---

CHANGELOG.md

Signed-off-by: Trăistaru Andrei Cristian <atc@amazon.com>
Keep track of Rust toolchain upgrade in CHANGELOG.
---

Changelog updated.

---

src/arch/src/aarch64/regs.rs

Housekeeping for #3280, we only noticed the outdated comment when backporting
...
---

Updated outdated comment

---

.mailmap
CHANGELOG.md
CREDITS.md
Cargo.lock
src/api_server/swagger/firecracker.yaml
src/firecracker/Cargo.toml
src/jailer/Cargo.toml
src/rebase-snap/Cargo.toml
src/seccompiler/Cargo.toml
tests/integration_tests/security/demo_seccomp/Cargo.lock

Release v1.2.0
New release v1.2.0
---

Firecracker v1.2

---

tests/host_tools/memory.py
tests/integration_tests/performance/test_snapshot_restore_performance.py

* see commit msgs
* intermittent failures on snapshot latency performance test
---

Fix intermittent issue related to memory monitor

---

Cargo.lock

Pick up a fixing name collisions when generating temporary files
...
---

Update vmm-sys-util 0.11.0 -> 0.11.1

---

src/vmm/src/signal_handler.rs

A unittest in vmm::signal_handler needed kcov specific code due to kcov swallowing specific signals. This is no longer a problem with our new coverage tooling, so the special cases can be removed (they were already not triggered anymore, since we no longer set the CARGO_WRAPPER environment variable)
technical debt
---

Remove kcov-specific code from unittest

---

src/cpuid-templates/src/lib.rs
src/cpuid/src/amd/normalize.rs
src/cpuid/src/common.rs
src/cpuid/src/lib.rs
src/vmm/src/persist.rs
src/vmm/src/vstate/vcpu/x86_64.rs
tests/integration_tests/build/test_coverage.py

Updates templates on the `feature/cpu-templates` branch to match `main`.
Required to rebase the branch.
---

Fix CPUID rebase on main

---

src/cpuid/src/amd/mod.rs
src/cpuid/src/common.rs
src/cpuid/src/cpuid_ffi.rs
src/cpuid/src/intel/mod.rs
src/cpuid/src/intel/normalize.rs
src/cpuid/src/lib.rs
tests/integration_tests/build/test_coverage.py

Adds additional testing onto the `cpuid` crate in the `feature/cpu-templates` feature branch.
Increases safety.
---

Testing cpuid

---

CHANGELOG.md

Mention Graviton3 support in the changelog.
We already mentioned Graviton3 in the documentation and tests.
---

chore(changelog): mention graviton3 support

---

src/vmm/src/cpuid/cpuid_ffi.rs
src/vmm/src/cpuid/leaves.rs
tests/integration_tests/build/test_coverage.py

Removes some unused functionality and adds a simple test case.
Reduces lines of code and increases coverage.
---

Cpuid cropping

---

docs/snapshotting/snapshot-support.md
docs/snapshotting/versioning.md
src/vmm/src/lib.rs

Fixes some comments and docs.
...
---

fix: tiny fixes for comment and docs

---

CHANGELOG.md
tools/release.sh

Fix a small couple of bugs related to release automation

---

.buildkite/common.py
.buildkite/pipeline_pr.py
tests/integration_tests/performance/test_boottime.py
tests/integration_tests/performance/test_snapshot_perf.py
tests/integration_tests/performance/test_versioned_serialization_benchmark.py
tests/integration_tests/security/test_spectre_meltdown.py

...
...
---
~~- [ ] This functionality can be added in [`rust-vmm`][1].~~
[3]: …

Migrate PR CI to new infra and add c7g to testing matrix 

---

.buildkite/pipeline_perf.py
tests/conftest.py
tests/framework/__init__.py
tests/framework/builder.py
tests/framework/defs.py
tests/framework/microvm.py
tests/framework/stats/core.py
tests/host_tools/__init__.py
tests/integration_tests/functional/test_balloon.py
tests/integration_tests/functional/test_cpu_features.py
tests/integration_tests/functional/test_mmds.py
tests/integration_tests/functional/test_snapshot_basic.py
tests/integration_tests/performance/conftest.py
tests/integration_tests/performance/test_block_performance.py
tests/integration_tests/performance/test_network_latency.py
tests/integration_tests/performance/test_network_tcp_throughput.py
tests/integration_tests/performance/test_snapshot_perf.py
tests/integration_tests/performance/test_snapshot_restore_performance.py
tests/integration_tests/performance/test_vsock_throughput.py
tests/integration_tests/style/test_pylint.py
tools/create_snapshot_artifact/main.py
tools/devtool
tools/parse_baselines/providers/types.py

Convert performance tests using TestMatrix to new fixtures, so we can assign metric dimensions. They also result in simpler, shorter tests.
...
---
~- [ ] This functionality can be added in [`rust-vmm`][1].~
[1]: …

Add metrics to performance tests

---

tests/integration_tests/functional/test_cpu_features.py

It is possible that some X template is not supported on the instance where the snapshots were created and, snapshot is loaded on an instance where X is supported. This results in error since restore doesn't find the file to load. To avoid this we make an assumption that if template directory does not exist then snapshot was not created for that template and we skip the test.
Assume that if snapshot_artifacts/wrmsr/vmlinux-4.14/$TEMPLATE  does not exist then snapshot was not taken for this template and skip restore for the same ($TEMPLATE could be T2CL, T2S, etc.).
The skipped line will be shown as below (T2CL is taken as an example here):
> integration_tests/functional/test_cpu_features.py::test_cpu_cpuid_restore[T2CL] SKIPPED
Snapshot restore test could fail is snapshot was taken on …

fix: skip restore if template dir not found

---

.buildkite/common.py
.buildkite/pipeline_pr.py
.gitlint
CONTRIBUTING.md
src/cpuid/src/transformer/intel.rs
tests/integration_tests/build/test_binary_size.py
tests/integration_tests/performance/test_boottime.py
tests/integration_tests/performance/test_process_startup_time.py
tests/integration_tests/performance/test_versioned_serialization_benchmark.py
tests/integration_tests/style/test_swagger.py
tools/devctr/Dockerfile

Migrate the PR pipeline to the new infra.
---

Migrate PR pipeline to new CI infrastructure

---

tests/integration_tests/security/test_jail.py

On Ubuntu 22 we have cgroupv2 enabled by default. Thus, we no longer need to add the `cgroup_no_v1=all` flag in the cmdline to enforce cgroupv2. This resulted in a wrong detection of cgroup version by just looking into the cmdline. According to docs, existence of /sys/fs/cgroup/cgroup.controllers should be a marker of cgroupsv2 enabled.
---

chore: enhance cgroupv2 checking

---

.mailmap
CHANGELOG.md
CREDITS.md
Cargo.lock
src/api_server/swagger/firecracker.yaml
src/firecracker/Cargo.toml
src/jailer/Cargo.toml
src/rebase-snap/Cargo.toml
src/seccompiler/Cargo.toml
tests/integration_tests/security/demo_seccomp/Cargo.lock

Changes required for a new release.
To prepare for a new release.
---

Releasing v1.3.0

---

tools/release-prepare.sh

Refuse to release if the snapshot version is missing

---

.mailmap
CHANGELOG.md
MAINTAINERS.md
docs/RELEASE_POLICY.md
tests/integration_tests/functional/test_cpu_features.py
tests/integration_tests/functional/test_snapshot_version.py
tests/integration_tests/security/demo_seccomp/Cargo.lock
tools/release-prepare.sh

Cherry picking commits from main that need to go to 1.3.1 plus changes required for a new release.
To prepare for a new release.
- ~~[] User-facing changes are mentioned in `CHANGELOG.md`.~~
---
[1]: …

Releasing v1.3.1

---

docs/prod-host-setup.md

Include `spectre-meltdown-checker.sh` in `prod-host-setup.md`
It is the best way to check for spectre vulnerability.
---

Include `spectre-meltdown-checker.sh` in `prod-host-setup.md`

---

.buildkite/pipeline_cross.py
tests/integration_tests/functional/test_feat_parity.py

...
...
~- [ ] The description of changes is clear and encompassing.~
~- [ ] Any required documentation changes (code and docs) are included in this PR.
~- [ ] API changes follow the [Runbook for Firecracker API changes][2].
~- [ ] User-facing changes are mentioned in `CHANGELOG.md`.
---
~- [ ] This functionality can be added in [`rust-vmm`][1].~
[2]: …

Add script to generate Cross CPU pipeline

---

.buildkite/pipeline_perf.py

Allow specifing multiple instance types and platforms after `--instances` and `--platforms` flags.
---

chore: enhance pipeline_perf arguments

---

docs/jailer.md
tools/compare_baselines/utils/comparator.py

- Fix a typo on jailer doc.
- Fix an output of performance comparison script.
...
--- …

Tiny fixes

---

.buildkite/common.py
.buildkite/pipeline_cpu_template.py
.buildkite/pipeline_cross.py
.buildkite/pipeline_pr.py
tests/conftest.py
tests/framework/artifacts.py
tests/framework/defs.py
tests/framework/utils.py
tests/integration_tests/functional/test_cpu_features.py
tests/integration_tests/performance/test_boottime.py

Some preliminary support for kernel 6.1
...
~- [] New `TODO`s link to an issue.~
---
[3]: …

Preparation work for kernel 6.1

---

tests/host_tools/uffd/Cargo.lock
tests/integration_tests/security/demo_seccomp/Cargo.lock

test: bump versionize and versionize_derive

---

tools/devtool

It creates an env.list file that is left behind. Now that files gets deleted.
The file was bothering me
---

test: Cleanup file created by cmd_test

---

Cargo.lock
src/snapshot/Cargo.toml
src/vmm/Cargo.toml
tests/integration_tests/performance/test_boottime.py
tests/integration_tests/performance/test_snapshot_perf.py
tests/integration_tests/performance/test_versioned_serialization_benchmark.py

Criterion offers opportunity to choose between
features and it does declare some dependencies
as being optional (like the rayon one) which we currently include even though we do not need to.
We actually do not need to include what criterion defines as default features.
Fix vulnerability in crossbeam-channel.
---

[1.2] criterion: trim down dependencies

---

FAQ.md

The recommendation to patch and recompile a kernel is dubious. Instead, let's suggest some more mainstream approaches.
...
...
---

docs: update recommendation on ENOMEM

---

src/api_server/src/lib.rs

Backport to FC 1.2 for commit d6f55d6ccdd9eb351400d4a7d523fa5ce46489a0
---

Backport Fix spurious failure in api_server::tests::test_serve_vmm_action_request to FC 1.2

---

docs/RELEASE_POLICY.md

chore: prepare release FC 1.2.1

---

docs/RELEASE_POLICY.md

chore: prepare patch release FC 1.3.2

---

CHANGELOG.md
docs/RELEASE_POLICY.md

chore: update release policy for patch releases FC 1.2.1 and 1.3.2

---

CHANGELOG.md
Cargo.lock
src/api_server/swagger/firecracker.yaml
src/firecracker/Cargo.toml
src/jailer/Cargo.toml
src/rebase-snap/Cargo.toml
src/seccompiler/Cargo.toml
tests/integration_tests/security/demo_seccomp/Cargo.lock

chore: release v1.3.2

---

CHANGELOG.md
Cargo.lock
src/api_server/swagger/firecracker.yaml
src/firecracker/Cargo.toml
src/jailer/Cargo.toml
src/rebase-snap/Cargo.toml
src/seccompiler/Cargo.toml
tests/integration_tests/security/demo_seccomp/Cargo.lock
tools/release-prepare.sh

Releasing v1.2.1

---

tests/host_tools/uffd/Cargo.lock

chore: update Cargo.lock

---

.github/dependabot.yml

The 'r' in 'review' is not capitalized
...
...
---

dependabot: fix label name

---

src/vmm/src/cpu_config/aarch64/custom_cpu_template.rs
src/vmm/src/cpu_config/templates_serde.rs
src/vmm/src/cpu_config/x86_64/custom_cpu_template.rs

Fixed byte access with `strip_prefix` checks + added unit tests with unicode.
---

fix: fixed bug in deserialization method

---

CHANGELOG.md

Add an entry for virtio-rng to the new features section of the CHANGELOG.
---

Mention virtio-rng in CHANGELOG

---

tests/framework/utils.py

Backport PR #3523 to firecracker-v1.2
To suppress nightly CI failures.
---

Backport PR #3523 to firecracker-v1.2

---

Cargo.lock

Update dependencies by cherry-picking dependabot commits.
Close #3743 
Close #3744 
Close #3745 
Close #3746
Close #3747
---
[3]: …

Update dependencies by cherry-picking dependabot PRs

---

Cargo.lock

Collects all recent dependabot commits into one PR
Merging each one separately takes ages
---

Accumulated Dependabot Commits

---

docs/prod-host-setup.md

Direct host owners to their distribution security advisories
Listing out individual kernel vulnerabilities will tend to be out of date and gives a false sense of security. Move up the recommendation to keep host & guest kernels up to date and give ALAS as an example for following security advisories.
---

Direct host owners to their distribution security advisories

---

Cargo.lock
src/cpu-template-helper/Cargo.toml
src/firecracker/Cargo.toml
src/jailer/Cargo.toml
src/rebase-snap/Cargo.toml
src/seccompiler/Cargo.toml
tests/integration_tests/security/demo_seccomp/Cargo.lock

Combine several dependabot PRs into one
...
---

Dependabot PRs 20230613

---

src/vmm/src/cpu_config/x86_64/static_cpu_templates/c3.rs
src/vmm/src/cpu_config/x86_64/static_cpu_templates/t2.rs
src/vmm/src/cpu_config/x86_64/static_cpu_templates/t2a.rs
src/vmm/src/cpu_config/x86_64/static_cpu_templates/t2cl.rs
src/vmm/src/cpu_config/x86_64/static_cpu_templates/t2s.rs
tests/integration_tests/build/test_coverage.py
tests/integration_tests/functional/test_cpu_template_helper.py

- Refactors fingerprint-related tests
- Adds annotation to static CPU templates
**Note that this PR does not include any functional changes.**
To improve maintainability of CPU templates
---
[1]: …

Refactor fingerprint-related tests and add annotation to static CPU templates

---

Cargo.lock
src/cpu-template-helper/Cargo.toml
src/firecracker/Cargo.toml
src/jailer/Cargo.toml
src/rebase-snap/Cargo.toml
src/seccompiler/Cargo.toml
src/utils/Cargo.toml
tests/host_tools/uffd/Cargo.lock
tests/host_tools/uffd/Cargo.toml
tests/integration_tests/security/demo_seccomp/Cargo.lock
tests/integration_tests/security/demo_seccomp/Cargo.toml

Updates dependencies.
Closes #3888
Closes #3887
Closes #3886 
Closes #3885 
Closes #3884
Closes #3882
Closes #3882
Closes #3881 
Closes #3880 
Closes #3879 
Closes #3878
Closes #3877 
Closes #3876 
Closes #3877 
Closes #3876 
Closes #3875 
---

Dependabot

---

.buildkite/pipeline_cross.py
.gitlint
tests/framework/stats/consumer.py
tests/framework/stats/core.py
tests/framework/utils.py
tests/framework/utils_vsock.py
tests/host_tools/cargo_build.py
tests/integration_tests/functional/test_cpu_template_helper.py
tests/integration_tests/functional/test_vsock.py
tests/integration_tests/performance/configs/test_snapshot_restore_performance_config_4.14.json
tests/integration_tests/performance/configs/test_snapshot_restore_performance_config_5.10.json
tests/integration_tests/performance/configs/test_snapshot_restore_performance_config_6.1.json
tests/integration_tests/performance/conftest.py
tests/integration_tests/performance/test_network_latency.py
tests/integration_tests/performance/test_snapshot_restore_performance.py
tests/pytest.ini
tools/create_snapshot_artifact/main.py
tools/devtool

Some cleanups done during the new CI artifacts work, that can be merged independently.
...
---

New CI artifacts: first batch of changes 

---

.buildkite/common.py
.buildkite/pipeline_cross.py
.buildkite/pipeline_perf.py
.buildkite/pipeline_pr.py
.buildkite/pipeline_pr_no_block.py
tests/integration_tests/performance/test_boottime.py

Always publish metrics even if the test fails
So that metrics are properly tracked and we get no gaps.
---

Boottime test improvements

---

CHANGELOG.md
CREDITS.md
Cargo.lock
src/api_server/swagger/firecracker.yaml
src/cpu-template-helper/Cargo.toml
src/firecracker/Cargo.toml
src/jailer/Cargo.toml
src/rebase-snap/Cargo.toml
src/seccompiler/Cargo.toml
tests/host_tools/uffd/Cargo.lock
tests/integration_tests/build/test_binary_size.py
tests/integration_tests/security/demo_seccomp/Cargo.lock

Final touches for v1.4.0 release
It is time
---

chore: release v1.4.0

---

src/vmm/src/arch/aarch64/cache_info.rs

- Removed unnecessary warnings when failing to get a `level` or `type` of cache for some index.
These errors were logged, but then ignored.
- Replaced error string construction when optional attributes are not available with separate `info` logs.
With these changes we don't create warning level logs during normal operation.
Fixes warnings like this:
```
2023-06-26T10:38:56.776864578 [anonymous-instance:main:WARN:src/vmm/src/arch/aarch64/cache_info.rs:90] Could not read cache level for index 4: Failed to read cache information: No such file or directory (os error 2)
```
That appear during normal Firecracker startup and are causing confusion. …

fix(aarch64): removed warnings for missing cache info

---

CHANGELOG.md
docs/RELEASE_POLICY.md
tools/release.sh

Syncing CHANGELOG files and porting `release.sh` fix
---

Post 1.4.0 release updates

---

docs/RELEASE_POLICY.md

Added 1.4 release to the RELEASE_POLICY doc
---

chore: added 1.4 release to the RELEASE_POLICY doc

---

src/vmm/src/device_manager/mmio.rs
src/vmm/src/devices/bus.rs
src/vmm/src/devices/legacy/rtc_pl031.rs
src/vmm/src/devices/legacy/serial.rs
src/vmm/src/devices/mod.rs
src/vmm/src/devices/pseudo/boot_timer.rs
src/vmm/src/devices/pseudo/mod.rs
src/vmm/src/devices/virtio/balloon/device.rs
src/vmm/src/devices/virtio/balloon/mod.rs
src/vmm/src/devices/virtio/balloon/persist.rs
src/vmm/src/devices/virtio/block/device.rs
src/vmm/src/devices/virtio/block/mod.rs
src/vmm/src/devices/virtio/block/persist.rs
src/vmm/src/devices/virtio/device.rs
src/vmm/src/devices/virtio/mmio.rs
src/vmm/src/devices/virtio/mod.rs
src/vmm/src/devices/virtio/net/device.rs
src/vmm/src/devices/virtio/net/mod.rs
src/vmm/src/devices/virtio/net/persist.rs
src/vmm/src/devices/virtio/net/tap.rs
src/vmm/src/devices/virtio/persist.rs
src/vmm/src/devices/virtio/queue.rs
src/vmm/src/devices/virtio/vsock/device.rs
src/vmm/src/devices/virtio/vsock/event_handler.rs
src/vmm/src/devices/virtio/vsock/mod.rs
src/vmm/src/devices/virtio/vsock/persist.rs
src/vmm/src/devices/virtio/vsock/unix/mod.rs
src/vmm/src/devices/virtio/vsock/unix/muxer.rs

This is an updated #3410 PR.
Enables doc comments for all current `pub` constructs
---

Add doc to devices

---

src/vmm/src/cpu_config/x86_64/cpuid/intel/normalize.rs

As reported in issue https://github.com/firecracker-microvm/firecracker/issues/3995, some instances might not have
frequency mentioned in the host model name.
Though it is not essential for us to include host frequency in
the normalized brandstring we expected it to be present since
our internal instances had frequency present in the model name.
Given that checking frequency is not always valid for external
instances, ignore the frequency check and normalize the brand
string using the default brandstring.
fixes https://github.com/firecracker-microvm/firecracker/issues/3995
While normalising brand string, ignore absence of frequency in host brand string.
Some external instance do not have frequency in the model name.
By submitting this pull request, I confirm that my contribution is made …

Fix: Ignore frequency from host brand string in normalize

---

CHANGELOG.md
Cargo.lock
src/api_server/swagger/firecracker.yaml
src/cpu-template-helper/Cargo.toml
src/firecracker/Cargo.toml
src/jailer/Cargo.toml
src/rebase-snap/Cargo.toml
src/seccompiler/Cargo.toml
tests/host_tools/uffd/Cargo.lock
tests/integration_tests/security/demo_seccomp/Cargo.lock

chore: release v1.4.1

---

tests/integration_tests/performance/configs/test_network_tcp_throughput_config_4.14.json
tests/integration_tests/performance/configs/test_network_tcp_throughput_config_5.10.json
tests/integration_tests/performance/configs/test_network_tcp_throughput_config_6.1.json
tests/integration_tests/performance/configs/test_vsock_throughput_config_4.14.json
tests/integration_tests/performance/configs/test_vsock_throughput_config_5.10.json
tests/integration_tests/performance/configs/test_vsock_throughput_config_6.1.json
tests/integration_tests/performance/test_network_tcp_throughput.py
tests/integration_tests/performance/test_vsock_throughput.py
tools/parse_baselines/providers/latency.py

Some small miscellaneous changes to perf tests that have been in my backlog for a while  
---

Miscellaneous performance test changes

---

Cargo.lock
src/api_server/Cargo.toml
src/cpu-template-helper/Cargo.toml
src/logger/Cargo.toml
src/mmds/Cargo.toml
src/seccompiler/Cargo.toml
src/utils/Cargo.toml
src/vmm/Cargo.toml
tests/host_tools/uffd/Cargo.toml
tests/integration_tests/security/test_vulnerabilities.py

build: Update `serde` for v1.4

---

src/snapshot-editor/Cargo.toml

See b8d2909e1888ef147cf3ec32c1f92a9bbb48873c
---

Mark snapshot-editor as not containing benchmarks

---

MAINTAINERS.md

chore: update maintainers

---

src/vmm/src/arch/x86_64/mod.rs

Fixes #3044
As described in the issue FC was only announcing 639 KiB as the first memory region available to the guest.
But at the same time FC is placing MP tables in the 640th KiB of the memory.
This PR fixes it by adding an additional entry from `EBDA_START` to `EBDA_START` + 1 KiB to represent mp tables.
Old memory map:
```
[    0.000000] BIOS-e820: [mem 0x0000000000000000-0x000000000009fbff] usable
[    0.000000] BIOS-e820: [mem 0x0000000000100000-0x000000003fffffff] usable
```
New memory map:
```
[    0.000000] BIOS-e820: [mem 0x0000000000000000-0x000000000009fbff] usable
[    0.000000] BIOS-e820: [mem 0x000000000009fc00-0x000000000009ffff] reserved
[    0.000000] BIOS-e820: [mem 0x0000000000100000-0x0000000007ffffff] usable
```
By submitting this pull request, I confirm that my …

fix: add 640th KiB to the available memory

---

Cargo.lock
src/snapshot-editor/Cargo.toml
src/utils/Cargo.toml
src/vmm/Cargo.toml

Removes unused cargo dependencies.
We do not want to keep unused dependencies.
---

build: Removed unused dependencies

---

tests/integration_tests/functional/test_metrics.py

Add test to make sure all fields of FirecrackerMetrics are present in the flushed metrics and make sure that all are numbers.
To catch any breaking change in Firecracker metrics.
---
- ~~[ ] This functionality …

chore(metrics): Test for breaking change in Firecracker metrics

---

.cargo/config
src/cpu-template-helper/src/template/strip/x86_64.rs
src/rebase-snap/src/main.rs
src/seccompiler/src/backend.rs
src/seccompiler/src/compiler.rs
src/snapshot-editor/src/edit_memory.rs
src/vmm/src/arch_gen/x86/hyperv.rs
src/vmm/src/arch_gen/x86/hyperv_tlfs.rs
src/vmm/src/arch_gen/x86/mpspec.rs
src/vmm/src/arch_gen/x86/msr_index.rs
src/vmm/src/arch_gen/x86/perf_event.rs
src/vmm/src/cpu_config/x86_64/cpuid/intel/normalize.rs
src/vmm/src/cpu_config/x86_64/cpuid/mod.rs
src/vmm/src/cpu_config/x86_64/cpuid/normalize.rs
src/vmm/src/devices/bus.rs
src/vmm/src/devices/virtio/balloon/device.rs
src/vmm/src/devices/virtio/gen/virtio_blk.rs
src/vmm/src/devices/virtio/gen/virtio_net.rs
src/vmm/src/devices/virtio/gen/virtio_ring.rs
src/vmm/src/devices/virtio/gen/virtio_rng.rs
src/vmm/src/devices/virtio/mmio.rs
src/vmm/src/devices/virtio/net/gen/if_tun.rs
src/vmm/src/devices/virtio/net/gen/iff.rs
src/vmm/src/devices/virtio/net/gen/sockios.rs
src/vmm/src/devices/virtio/vsock/csm/txbuf.rs
src/vmm/src/devices/virtio/vsock/unix/muxer.rs
src/vmm/src/io_uring/bindings.rs
tests/integration_tests/style/test_rust.py
tools/bindgen.sh

Fixes newly breaking clippy lints.
Without the fix clippy fails.
---

Clippy fixes

---

tests/integration_tests/performance/test_network_ab.py

Splits the network latency test, which currently does 900 pings from guest to host into two tests each doing 450 pings. The rationale behind this is that we have very little network latency test cases (only 2, which is the number of guest kernels), which means that the A/B-testing framework does not have enough data to meaninfully correct for outliers (it has only 2 data points). This change increases the number of data points it can work with to 4, which should hopefully help with the high false-positive rate we have been seeing from this test. …

test(ab): artificially increase network latency test cases

---

tests/integration_tests/functional/test_snapshot_basic.py

Instead of creating a new socat process on every guest resume, create socat process in the 1st guest created so that the snapshotted guests just use the same process through.
Suspend and resume socat process before taking snapshot and after resuming from snapshot respectively to make sure the process is in the right state for the snapshot.
---
[3]: https://github.com/firecracker-microvm/firecracker/blob/main/CONTRIBUTING.m …

fix: intermittent vsock timeout in snapshot tests

---

.buildkite/pipeline_perf.py

This commit updates them to fix this.
The emojis where null characters due to not being supported in all fonts. 
---

test: Update perf pipeline emojis

---

CHANGELOG.md
CREDITS.md
Cargo.lock
docs/RELEASE_POLICY.md
src/api_server/swagger/firecracker.yaml
src/cpu-template-helper/Cargo.toml
src/firecracker/Cargo.toml
src/jailer/Cargo.toml
src/rebase-snap/Cargo.toml
src/seccompiler/Cargo.toml
src/snapshot-editor/Cargo.toml
tests/framework/ab_test.py

Bookkeeping changes to make a release.
See `CHANGELOG.md` for the actual list of changes included in the release..
Release latest features and bug fixes.
---

chore: release v1.6.0

---

CHANGELOG.md
CREDITS.md
docs/RELEASE_POLICY.md
tests/framework/ab_test.py

- Release doc updates from v1.6.0
- If the revision is a branch name instead of a commit, massage it so that git understands what we mean.
A forward port of the fix included in #4333, so that A/B tests work when running over branches other than main.
---

forward port release changes and fixes from v1.6.0

---

src/vmm/src/arch/x86_64/mptable.rs

Resolves #3045.
This PR counts the number of entries added to the MultiProcessor Configuration Table and passes it to the guest through the `oemcount` field on `mpspec::mpc_table`.
Guest operating systems that comply with the [Intel MP spec](https://pdos.csail.mit.edu/6.828/2018/readings/ia32/MPspec.pdf) (see Section 4), such as FreeBSD, fail to boot because the Entry Count field in the MP Configuration Table header is unset (defaults to 0). When Firecracker sets that field to a reasonable value, those guests are able to discover the MP configuration and continue booting.
I've tested this on a FreeBSD 14 guest with the patches from the `feature/pvh` branch and a few kernel `printf`s added to verify that the `MPTABLE_LINUX_BUG_COMPAT` option wasn't interfering (it was enabled but didn't …

Pass correct MP Table entry count to unblock spec-compliant guests

---

tests/integration_tests/functional/test_cpu_features.py

The error messages were swapped in the
msr tests.
---

fix(test): error messages in msr tests

---

tests/integration_tests/security/test_vulnerabilities.py

There is a REPTAR exception reported on m6i.metal for guest kernel versions 4.14/5.10/6.1 when spectre-meltdown-checker.sh script is run inside the guest from below the tests:
- test_spectre_meltdown_checker_on_guest and
- test_spectre_meltdown_checker_on_restored_guest
The same script when run on host doesn't report the exception which means the instances are actually not vulnerable to REPTAR.
The only reason why the script cannot determine if the guest is vulnerable or not is due to the unavailability of the microcode in Firecracker.
The check for REPTAR is in check_CVE_2023_23583_linux in spectre-meltdown-checker.sh
Since we have a test on host and the exception in guest is not valid, we add a check to ignore this exception because it is a false positive.
There could be more such …

fix: Add check for known vulnerabilities in guest

---

src/vmm/src/arch/aarch64/vcpu.rs

Resize the kvm_reg_list buffer and make the get_reg_list call again, if the reported buffer size is larger than 500.
get_reg_list returns E2BIG when the passed buffer is not large enough.
fixes https://github.com/firecracker-microvm/firecracker/issues/3768.
Unit tests are passing locally, with `500` and `10` as the buffer size. `10` is chosen to execute the new resize code path inside `get_all_registers_ids`.
---
[3]: …

fix: handle E2BIG error from get_reg_list

---

src/vmm/src/devices/virtio/balloon/event_handler.rs
src/vmm/src/devices/virtio/net/event_handler.rs
src/vmm/src/devices/virtio/rng/event_handler.rs
src/vmm/src/devices/virtio/vhost_user_block/event_handler.rs
src/vmm/src/devices/virtio/virtio_block/event_handler.rs
src/vmm/src/devices/virtio/vsock/event_handler.rs

perf: Change virtio event_handlers to use Events::with_data()
Using Events::with_data when registering events for block/network/vsock
devices and associating a u32 const data with each event. Then, in the
process function, instead of using if to see what process_* function to
call, we can do a match on consecutive u32 values which is going to be
optimized by the compiler into a jump table.
Fixes #1920 
---
[3]: …

perf: Change virtio event_handlers to use Events::with_data()

---

tests/framework/utils_drive.py

There is a difficult to reproduce issue we encounter in this test during fixture setup.
---- Captured stderr call ----
dd: writing to '/dev/loop1p1': No space left on device
8193+0 records in
8192+0 records out
It is difficult to root cause this, but it seems to be related to the loopback devices. Avoid them by creating the disk image without.
...
...
---
[3]: https://github.com/firecracker-microvm/firecracker/blob/main/CO …

test: fix test_partuuid_boot

---

tests/framework/utils_cpu_templates.py

Uses structured matching on cpu properties to clarify the different cases.
Split off from https://github.com/firecracker-microvm/firecracker/pull/4404#discussion_r1466145413.
---

test: Use structured matching on cpu properties

---

tools/ab_test.py

In the past, it was possible for a performance A/B-Test to fail with the message listing all the metrics that had a significant change (p<0.01) having only entries of changes where the magnitude is below the noise threshold.
This is because to determine whether we want to print the message, try to correct for false-positives by considering the average change reported across all data points for the metric, and if the average of their relative changes is below the noise threshold, we ignore it. However, this average includes the metrics not deemed statistically significant (p>=0.01), so if we have large variation that is not deemed significant, this can still skew this average, and thus fail the overall test. Since the failure message only contains significant results, it will seem like the …

ab: Do not fail with summary listing values below noise threshold

---

.buildkite/pipeline_perf.py

Use pinned AMI for m6i/6.1.
This is to keep monitoring functionality and performance on the latest known stable AMI.
- ~~[ ] Any required documentation changes (code and docs) are included in this~~
PR. …

test: use pinned ami for m6i/6.1

---

src/vmm/src/cpu_config/x86_64/cpuid/common.rs
src/vmm/src/devices/virtio/balloon/device.rs
src/vmm/src/devices/virtio/queue.rs
src/vmm/src/io_uring/mod.rs

chore: remove repetitive words

---

.mailmap
CHANGELOG.md
CREDITS.md
Cargo.lock
deny.toml
src/cpu-template-helper/Cargo.toml
src/firecracker/Cargo.toml
src/firecracker/swagger/firecracker.yaml
src/jailer/Cargo.toml
src/rebase-snap/Cargo.toml
src/seccompiler/Cargo.toml
src/snapshot-editor/Cargo.toml

Update version number / CHANGELOG / CREDITS + backport of 5b2ace936394160ab2e0b4238f010a52e36b89eb (needed because cargo update is run as part of the release process)
We have committed to release 1.7 this week
PR.
[2]: https://github.com/firecracker-microvm/firecracker/blob/main/docs/api-change-runbook.m …

chore: release v1.7.0

---

CHANGELOG.md

Move everything that we just released in 1.7 into the 1.7 section, and keep everything we didnt release in the "Unreleased" section.
...
...
PR.
[3]: https://github.com/firecracker-microvm/firecracker/blob/main/C …

chore: Updated CHANGELOG post 1.7 release

---

tests/integration_tests/functional/test_topology.py

Update aarch64 cache topology tests for newer kernels
Starting from 6.3 kernel, cache topology propagated to the guest has changed. This results in L1 cache information being less detailed in the guest compared to the host. This commit changes the cache topology test to skip L1 cache during checks for kernels start 6.3.
PR.
[1]: …

fix: update aarch64 cache topology tests for newer kernels

---

tests/conftest.py

If test uses snapshots and fails save most files in `root` to the `test_results`.
If CI test fails due to snapshot problems it will be easier to reproduce with original snapshot files.
PR.
[3]: …

feat: store snapshot files on test fail

---

tests/pytest.ini

Revert pytest timeout

---

.buildkite/common.py

The `git clone -b {rev_a} . build/{rev_a}` command does not work if `rev_a` is a commit hash. Thus, copy the logic from `tests/framework/ab_test.py` for checking out the `A` revision.
Additionally, stop unconditionally compiling `HEAD` as the `B` revision in A/B-tests, and instead correctly compile the revision that is specified by the `REVISION_B` environment variable.
PR. …

fix(test): make build step work for A/B-tests

---

.mailmap
CHANGELOG.md
CREDITS.md
Cargo.lock
resources/seccomp/aarch64-unknown-linux-musl.json
src/cpu-template-helper/Cargo.toml
src/firecracker/Cargo.toml
src/firecracker/swagger/firecracker.yaml
src/jailer/Cargo.toml
src/rebase-snap/Cargo.toml
src/seccompiler/Cargo.toml
src/snapshot-editor/Cargo.toml
src/vmm/Cargo.toml

Update version number / CHANGELOG / CREDITS
Also back port https://github.com/firecracker-microvm/firecracker/commit/b83640c0f7eb286103aa133175cd1d566d858a10 with `aws-lc-sys` fix. 
1.8 release
PR.
[3]: …

chore: release v1.8.0

---

docs/RELEASE_POLICY.md

Add a row with the v1.9 release and deprecation dates.
We are going to release v1.9
PR.

Update RELEASE_POLICY table with v1.9 release

---

docs/RELEASE_POLICY.md

Update release policy ready for release
...
...
PR.

chore: Update release policy

---

CHANGELOG.md

Update with v1.10.0 section
...
...
PR.

chore: Update changelog with v1.10.0 section

---

CHANGELOG.md
src/vmm/src/persist.rs

Bump the snapshot version
Bumping snapshot version  
...
PR.

chore: Bump snapshot version

---

docs/RELEASE_POLICY.md

Update release notes to v1.10.1 patch
...
...
in the PR.

chore: Update to v1.10.1 patch

---

tests/host_tools/fcmetrics.py

Ignore `tx_flush_fails` in tests

---

src/vmm/src/devices/virtio/queue.rs

Add pointer alignment check and exit with an error early instead of panic.
Raw pointers of `struct Queue` are assumed to be aligned properly;
otherwise some methods (e.g. `read_volatile()`) will panic. Such an
alignment is possible when restored from a broken/fuzzed snapshot.
in the PR.~~
- ~~[ ] If a …

chore(vmm): Add pointer alignment check for Queue

---

docs/snapshotting/snapshot-support.md
src/vmm/src/devices/virtio/vsock/packet.rs
src/vmm/src/dumbo/tcp/connection.rs

This is a combination of stale PRs (#4891 and #4873).
Will be easier to merge this way.
Original authors marked as `Co-Author`s.
Merge stale PRs.
in the PR.
[3]: …

Documentation minor fixes

---

src/vmm/src/resources.rs

VmmConfig is parsed from Firecracker config JSON file. I don't know why we used different field names than names in the JSON format, which just makes it difficult to read code and readers have to keep the field mapping in their mind.
Remove unnecessary field renaming of VmmConfig.
in the PR.~~
- ~~[ ] If a …

refactor(vmm): Remove unnecessary renames

---

tests/integration_tests/functional/test_balloon.py

If we set deflate_on_oom to False, and then induce an out of memory condition, then we're really only testing how well the guest can handle oom conditions. Do not fail the test if the guest responds to OOM by shutting down though.
...
...
in the PR.
[2]: …

do not fail balloon test if deflate_oom is false and guest crashes

---

src/vmm/src/vstate/memory.rs

Since we dropped the explicit offset field from the snapshot file, we are implicit computing it as "sum of sizes of all preceding regions". If the snapshot file is corrupted, it can describe regions whose sum exceeds u64::MAX. Fix this by adding overflow checks and returning an error in case of overflows
We also error out if it exceeds i64::MAX as the offset argument to mmap(2) is a signed 64 bit integer value.
Fixes: d8358055d4b2
...
...
in the PR. …

fix: handle overflow when computing mmap offset during restore

---

CHANGELOG.md

- bump changelog
- ~~add 1.11 to release_policy~~
- ~~mark 1.9 as EOL~~
We're about to branch for 1.11
- [NA] I have updated any relevant documentation (both in code and in the docs)
in the PR.
- [NA] I have mentioned all user-facing changes in `CHANGELOG.md`.
- [NA] If a specific issue led to this PR, this PR closes the issue.
- [NA] When making API changes, I have followed the
- [NA] I have tested all new and …

Doc updates in preparation for 1.11 release

---

tests/integration_tests/style/test_gitlint.py

This reverts commit 38a6faffa84cae7d033ee5d7b44d1ae78624693b.
...
...
in the PR.

Revert "test: skip test_gitlint on PR #5048"

---

tests/integration_tests/performance/test_snapshot_ab.py

Gathering more data should make the A/B test more stable and avoid intermittent failures.
in the PR.

test: increase cases for test_population_latency

---

tests/integration_tests/build/test_hiding_kernel.py

Add an `apt update` before `apt install`
Otherwise, we might hold an old view of the package versions and installation might fail.
in the PR.
[3]: …

Fix package installation for secret hiding test

---

tests/integration_tests/performance/test_block_ab.py

- Fix a typo of a parameter
- Reorder and group related parameters.
in the PR.~~
- ~~[ ] I have linked an issue to every …

chore: Refactor fio parameters

---

.mailmap
CREDITS.md
Cargo.lock
src/cpu-template-helper/Cargo.toml
src/firecracker/Cargo.toml
src/firecracker/swagger/firecracker.yaml
src/jailer/Cargo.toml
src/rebase-snap/Cargo.toml
src/seccompiler/Cargo.toml
src/snapshot-editor/Cargo.toml

- Update version number / CREDITS
We'll make a release today :tada:!!
in the PR.~~
- ~~[ ] I have linked an issue to every …

chore: release v1.12.0

---

tools/release.sh

This is a forward port of #5200
in the PR.~~
- ~~[ ] I have linked an issue to every new `TODO`.~~ …

[main] Enable tracing mode for release.sh and fix release.sh

---

src/firecracker/examples/uffd/uffd_utils.rs

If a remove event is pending to be read from the uffd, then all uffdio ioctls return EAGAIN. We correctly handle this for COPY, but did not for ZEROPAGE. Also handle this for zeropage to fix spurious test failures.
See commit e92a7ff01aa5 ("fix(example): correctly handle `remove` events in uffd exammple") for more details.
in the PR.
_________________________________________________________________ …

example(uffd): handle EAGAIN from UFFDIO_ZEROPAGE

---

rust-toolchain.toml
src/rebase-snap/src/main.rs
src/vmm/src/cpu_config/x86_64/cpuid/intel/normalize.rs
src/vmm/src/devices/virtio/vsock/csm/txbuf.rs
src/vmm/src/logger/logging.rs
src/vmm/src/vstate/kvm.rs
src/vmm/src/vstate/vcpu.rs
tools/devctr/Dockerfile
tools/devtool

Update to rust 1.87.0
in the PR.

chore: update rust toolchain

---

src/vmm/src/devices/virtio/vsock/event_handler.rs

turns out that when driving the vsock device from test code using fake descriptors placed in guest memory, calling this function is the only way to get it to process new connections, etc. So avoid it panicking.
This is a follow up/fix for https://github.com/firecracker-microvm/firecracker/pull/5248
in the PR.
[1]: …

fix: propagate Err(InvalidAvailIdx) out of Vsock::notify_backend

---

Cargo.lock
docs/RELEASE_POLICY.md
src/cpu-template-helper/Cargo.toml
src/firecracker/Cargo.toml
src/firecracker/swagger/firecracker.yaml
src/jailer/Cargo.toml
src/rebase-snap/Cargo.toml
src/seccompiler/Cargo.toml
src/snapshot-editor/Cargo.toml

Update version number / CHANGELOG / CREDITS
1.12.1 patch release
in the PR.

chore: release v1.12.1

---

tests/integration_tests/performance/test_network.py

test_network_latency uses ping to send 15 rounds of 30 pings from the guest to the host and collects the latencies printed. For this, instead of just parsing the ping output for however many lines of latency data there we, implicitly assert that we get exactly 30. However, sometimes this fails. Nikita and Egor investigated and found that no packages are lost, sometimes ping just seems to not print all 30 lines for some reason (presumably a bug in ping). So just drop this assertion to stop spurious test failures from happening. This is a performance test, not a functional test anyway.
...
...
Certificate of Origin and signing off …

test(network_latency): drop check on number of pings returned

---

tests/integration_tests/functional/test_cpu_features_host_vs_guest.py
tests/integration_tests/functional/test_cpu_template_helper.py

Backport of https://github.com/firecracker-microvm/firecracker/pull/5314
in the PR.
[3]: https://github.com/firecracker-microvm/firecracker/blob/main/CONTRIBUT …

[1.11] Update amd x86_64 cpu features

---

CHANGELOG.md
Cargo.lock
src/cpu-template-helper/Cargo.toml
src/firecracker/Cargo.toml
src/firecracker/swagger/firecracker.yaml
src/jailer/Cargo.toml
src/rebase-snap/Cargo.toml
src/seccompiler/Cargo.toml
src/snapshot-editor/Cargo.toml

Update changelog and run ./tools/bump-version.sh 1.14.0-dev
We are releasing 1.13
in the PR.
[3]: https://github.com/firecracker-microvm/firecracker/blob/main/ …

Start v1.14.0 development

---

src/vmm/src/devices/virtio/transport/pci/device.rs

Add a unit test that ensures the device initialization process works properly.
in the PR.
[3]: https://github.com/firecracker-microvm/firecracker/blob/main/CON …

pci: add test for device initialization
