firecracker-microvm/firecracker

- CONTRIBUTE.md
The current links takes you to 404'ing page. Much sadness!
https://github.com/firecracker-microvm/firecracker/blob/master/LICENSE.md
The correct link doesn't have `.md` on the end.
I've grepped the other Markdown files in the repo to look for similar links; I couldn't find any.
> Fix the link to the LICENSE file in CONTRIBUTE.md

- kernel/src/cmdline/mod.rs
Initializes the internal String buffer inside of Cmdline with the given capacity
> Preallocate Cmdline internal String

- logger/src/lib.rs
- src/main.rs
- vmm/src/lib.rs
* Log messages related to flushing metrics are now customized to reflect the scenario that triggered it.
* Removed "Failed to log metrics" so that it does not cause duplicate sentence inside log message.
* Also, two log messages would have a ":?" due to it being placed outside of curly braces.
> Unifying log messages triggered by flushing metrics

- vmm/src/lib.rs
This is meant to help diagnose spurious stops of the VMM control loop.
> vmm: log graceful / forceful termination

- micro_http/src/common/mod.rs
- micro_http/src/request.rs
- micro_http/src/response.rs
+ `Body::new()` works for generic `T: Into<Vec<u8>>`, this will convert `String`s without allocation like before, but also adds some convenience when you have a `Vec<u8>`, `&str`, or `&[u8]`.
+ Made some code in `request.rs` more declarative. It's shorter, intent I think is clearer to read, and it should be faster in at least one instance.
+ Side note: the `if index + 1 < bytes.len() {` branching in `fn split` was completely unnecessary. `index + 1` for the last byte is equal to length, thus `&bytes[index + 1..]` will produce an empty slice without panics.
+ `StatusCode::raw()` returns `&[u8; 3]` instead of `&[u8]`, since it's always 3 bytes we can save a word on stack here and there.
(Replacing #688)
> Some non-breaking tweaks to `micro_http`

- docs/getting-started.md
Added a BASH script snippet that can check if the host system meets the basic requirements to run Firecracker.
Also removed the kernel version check from the KVM access setup appendix, since it was both out of scope and wrong (yielding false positives).
Signed-off-by: Dan Horobeanu <dhr@amazon.com>
> getting-started: Host requirements check

- FAQ.md
- mmds/src/data_store.rs
The FAQ has a link a GitHub issue in what looks like a previous, private incarnation of this repo. Link to the [current URI](https://github.com/firecracker-microvm/firecracker/issues/208) of that issue instead.
> Fix hyperlink to public URI for a GitHub issue

- Cargo.lock
- dumbo/Cargo.toml
- dumbo/src/lib.rs
- dumbo/src/tcp/connection.rs
- tests/framework/jailer.py
Apply tight seccomp filters to Firecracker in the integration tests to prevent unauthorized syscalls from being introduced.
> Enforce seccomp filtering in integration tests

- tests/integration_tests/build/test_unittests.py
By default, `cargo test` runs the tests in parallel. Official
recommended solution is to use environment variable `RUN_TEST_THREADS`
to specify the number of threads used to run the tests. Since we are
opening `/dev/kvm` in multiple unit tests, we need this in order to
avoid race conditions.
> CI: run unit tests sequentially

- docs/getting-started.md
In the getting started guide, the BASH snippet recommended to check the basic host requirements was issuing an ERROR, if it detected a nested virtualization environment. Downgraded that to a warning, since reports came in that Firecracker was successfully run on GCE, with L2 KVM.
> getting-started: Only warn on nested virtualization

- docs/prod-host-setup.md
Changes `--guid` to `--gid`.
Signed-off-by: Nicolas Mesa <nicolasmesa@gmail.com>
The jailer expects a [`--gid` argument](https://github.com/firecracker-microvm/firecracker/blob/master/jailer/src/lib.rs#L139-L140) but the docs said `--guid`. This PR fixes that.
> Fix typo in prod-host-setup docs

- api_server/src/http_service.rs
- api_server/src/request/mod.rs
- cpuid/src/lib.rs
- devices/src/bus.rs
- jailer/src/env.rs
- jailer/src/lib.rs
- jailer/src/uuid.rs
- logger/src/lib.rs
- mmds/src/lib.rs
- rate_limiter/src/lib.rs
- seccomp/src/lib.rs
- src/bin/jailer.rs
- src/main.rs
- sys_util/src/errno.rs
- vmm/src/lib.rs
- vmm/src/vmm_config/instance_info.rs
- vmm/src/vstate.rs
- x86_64/src/interrupts.rs
* replaced several occurrences of `unwrap()` with `expect()`. This will produce an explanatory message on panics that will speed up panic diagnosis.
* replaced other occurrences of `unwrap()` with error propagation for better error handling.
* added appropriate messages for jailer errors, which are diverse and can be confusing, especially with the jailer not having a logger.
This PR only addresses a part of the `unwrap()`s in the code base. More TBD.
Partially addresses #593
> Improve error readability: part 1

- CHANGELOG.md
- jailer/src/lib.rs
Changes the default seccomp level when starting Firecracker via the jailer to 2.
> Jailer: set default seccomp level to 2

- docs/getting-started.md
The current firecracker binary defaults to creating
`/tmp/firecracker.socket`, the example commands in the documentation
specify `/tmp/firecracker.sock`, this brings them into agreement.
> Updated example Curl commands to match default socket name

- README.md
Added the [firecrackerdevel@lists.infradead.org](mailto:firecrackerdevel@lists.infradead.org) mailing list and its [sign-up link](https://lists.infradead.org/mailman/listinfo/firecracker-devel) to `README.md`.
> docs: add email list to README.md

- CHANGELOG.md
- api_server/src/request/logger.rs
- api_server/swagger/firecracker.yaml
- kvm/src/lib.rs
- kvm_gen/src/lib.rs
- logger/src/error.rs
- logger/src/lib.rs
- logger/src/metrics.rs
- memory_model/src/guest_memory.rs
- src/main.rs
- tests/framework/resources.py
- tests/integration_tests/functional/test_logging.py
- vmm/src/lib.rs
- vmm/src/vmm_config/logger.rs
- vmm/src/vstate.rs
Issue #, if available: N/A
Description of changes: This PR is a re-submission of #551.
* Added a new `options` parameter for logging configuration. This should be used as a list of logging options sent to Firecracker. Currently there's only 1 valid option: `LogDirtyPages`.
* Added logging flags in the logger implementation. They are the "inner" representation of the `options` from the API. `LogDirtyPages` translates into a logging flag that, in turn, sets the `KVM_MEM_LOG_DIRTY_PAGES` flag when initializing memory in kvm and gets the dirty page bitmap via `KVM_GET_DIRTY_LOG` into a new metric when flushing metrics.
* Added the functions written by @marcbrooker to retrieve the dirty page bitmap and hooked them up to the logging options.
* Completed documentation in `kvm/src/lib.rs`.
* …
> Add periodic logging of dirty pages

- kvm/src/lib.rs
Issue #, if available: N/A
Description of changes: I noticed a small typo in the kvm crate. This tiny patch fixes that!
> Fix typo in kvm docs

- CHANGELOG.md
- src/main.rs
Issue #, if available: #763 
Description of changes: This patch adds the DEFAULT_INSTANCE_ID to log messages when no
instance id is specified.
Previous behavior:
`[:ERROR:src/main.rs:49] `
After: 
`[anonymous-instance:ERROR:src/main.rs:49] `
> Log with DEFAULT_INSTANCE_ID in the absence of instance id

- mmds/src/data_store.rs
- tests/integration_tests/functional/test_mmds.py
Return dictionary keys when path doesn't end with '/'. This change is necessary for the MMDS to be backwards compatible with the IMDS implementation on C5.
Same commit as in PR #562.
> mmds: return dictionary keys

- README.md
Make it clear how to contact for security-related issues. Hopefully
prevents a naive public disclosure via a GitHub issue or other channel.
> readme: clarify how to contact for security

- tools/devtool
When using SELinux for controlling processes within a container,
you need to make sure any content that gets volume mounted into
the container is readable, and potentially writable.
Use 'z' on the --volumes parameter for docker to automatically
relabel the content and allow sharing between containers.
Fixes #682 
> devtool: fix building on SELinux

- api_server/swagger/firecracker.yaml
Signed-off-by: Noah Meyerhans <nmeyerha@amazon.com>
Addresses #774 
Description of changes: This change corrects the OpenAPI specification of the "options" array property of the Logger object.
> Correct specification of the "options" property of the Logger object

- vmm/src/default_syscalls.rs
Issue #, if available: #747
Description of changes: Blacklist several more syscalls that aren't called by customer code.
> Seccomp: tighten filters

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- api_server/swagger/firecracker.yaml
- docs/getting-started.md
- jailer/Cargo.toml
* updated version in TOML files and API spec
* ran `cargo update`
* adjusted CHANGELOG.MD
* hardcoded the **backtrace** crate's version to workaround bug induced by upstream update
> Firecracker release v0.12.0

- api_server/swagger/firecracker.yaml
Related to https://github.com/firecracker-microvm/firecracker/issues/673
Removed InstanceHalt action type from swagger as we don't support it yet.
> swagger: remove InstanceHalt from actions

- CHANGELOG.md
- README.md
- api_server/src/http_service.rs
- api_server/src/request/logger.rs
- api_server/swagger/firecracker.yaml
- docs/api_requests/logger.md
- vmm/src/lib.rs
- vmm/src/vmm_config/logger.rs
Related to https://github.com/firecracker-microvm/firecracker/issues/785.
Added a directory in docs called `api_requests`. This directory should contain examples and details about API requests that are too technical to be included in the swagger definition.
The first document added is detailing the Logger option 
Added default values for the optional fields in the Logger object and specified the required fields.
Refactored the LoggerConfig structure. Insteaad of using optional values in the strongly typed serde structure, use defaults.
> API Requests Usage Docs & LoggerConfig Refactoring

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- api_server/src/lib.rs
- src/main.rs
- sys_util/src/signal.rs
- tests/framework/microvm.py
- tests/integration_tests/functional/test_shut_down.py
- tests/integration_tests/security/test_seccomp.py
- vmm/src/default_syscalls.rs
- vmm/src/lib.rs
Apply seccomp filters to all firecracker threads
Refactor and apply the seccomp filters to all Firecracker threads.
New syscalls had to be whitelisted as they are necessary (previously API and vCPUs threads had no filters installed).
Firecracker default SECCOMP level is now 2 - SECCOMP_ADVANCED meaning filtering both on the syscall number and the syscall parameters.
Added integration test to validate all Firecracker threads have seccomp applied.
Fixes #800.
> Apply seccomp filters to all firecracker threads

- devices/src/virtio/vhost/vsock.rs
Commit d6861f91ac forgot to update the vhost vsock part and build fails when vsock is enabled.
> vhost-vsock: fix build after epoll crate update

- vmm/src/lib.rs
Vec::set_len is incredibly unsafe - all of the epoll::Event instances
are completely uninitialized. While this might happen to work for now,
the epoll crate could break it any time time. Specifically, if epoll
adds any code that relies on epoll::Event being initialized (e.g. a Drop
implementation), this code will exhibit undefined behavior.
This commit explicitly initializes the `events` vector using the
vec![] macro. This eliminates the potential for undefined behavior,
since epoll::Event instances are now created via explicit constructors
(epoll::Event::new() and an implicit Clone::clone())
> Replace Vec::set_len with explicit initialization

- tests/conftest.py
- tests/framework/decorators.py
- tests/framework/http.py
- tests/framework/s3fetcher.py
- tests/integration_tests/performance/test_boottime.py
This PR introduces following changes:
* a new fixture is available `test_vm_performance` that is able to spawn multiple vms by using a dynamically parametrized fixutre `context`. The parameters are sent to this fixture by using a decorator.
* It also removes the `microvm_s3_fetcher` (which was used as a fixture but also a function). It is transformed in this PR into a global variable returning a `MicrovmS3fetcher` object given that all fixtures are using it without modifying its state. No need for a borg pattern.
* Observation: All other `test_microvm_*` fixtures could now be transformed to use the `context` fixture and we would be getting rid of the necessity to autogenerate code by doing `exec`.
Duplicate of #588 .
> CI: Support for spawning multiple microvms

- CHANGELOG.md
- api_server/src/request/actions.rs
- api_server/swagger/firecracker.yaml
- docs/api_requests/actions.md
- docs/api_requests/logger.md
- tests/integration_tests/functional/test_logging.py
- vmm/src/lib.rs
- vmm/src/vmm_config/logger.rs
At any time, the user can call the `FlushMetrics` api command for
getting the values of the metrics at that moment. The action can only be
called after the logger has been initialized (i.e a FIFO has been
provided as the destination for the metrics).
```
curl --unix-socket /tmp/firecracker.socket -i      
-X PUT "http://localhost/actions"      
-H  "accept: application/json"      
-H  "Content-Type: application/json"      
-d "{  
\"action_type\": \"FlushMetrics\"
}"
```
You will get an error saying `  "fault_message": "Failed to log metrics. Logger was not initialized."
` if the logger has not been initialized beforehand. Othewise, you should see the json related metrics on the screen.
* Unified behavior when receiving error on logging the metrics
* Wrote unit tests
* Wrote integration …
> Add a vmm action for flushing the metrics

- CHANGELOG.md
- api_server/src/http_service.rs
Added URL decoding to `id` from HTTP request path.
Issue #, if available: #794 
Used `percent_decode` from the `url` crate to decode `id` extracted from HTTP request path.
> Added URL Decoding to API server (#794)

- Cargo.lock
- Cargo.toml
- src/main.rs
What really happened when the test_main seemed to fail with error "DEFAULT_API_SOCK_PATH already exists":
1. `cargo update` was run -> backtrace version was updated -> `backtrace-rs` changed the way the backtrace looked:
* Before:
0:           0xc30e46 - backtrace::backtrace::libunwind::trace::h317d1a757d5a039e
at /home/ANT.AMAZON.COM/dpopa/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.9/src/backtrace/libunwind.rs:53
- backtrace::backtrace::trace::hd728055c5e2a0dd3
at /home/ANT.AMAZON.COM/dpopa/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.9/src/backtrace/mod.rs:42
1:           0xc2b503 - backtrace::capture::Backtrace::new_unresolved::h41d1b0720bff36f8
at /home/ANT.AMAZON.COM/dpopa/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.9/src/capture.r …
> remove hardcoded backtrace-rs version

- devices/src/virtio/vhost/handle.rs
- tests/host_tools/cargo_build.py
- tests/integration_tests/build/test_build.py
Description of changes: Added two integration tests, one that checks that features vsock builds in both debug and release mode.
This will help us avoid situations like this one: #804.
> Test that vsock feature builds

- CHANGELOG.md
- docs/dev-machine-setup.md
> added instructions for AWS

- CHANGELOG.md
- src/main.rs
Issue #, if available: #837 
Instead of printing the PanicInfo using debug, we can use display
as this generates a human readable panic.
Before:
Panic occurred: PanicInfo { payload: Any, message: Some(Failed to
open the API socket: IO Error: Io(Os ...
After:
Firecracker panicked at 'Failed to open the API socket: IO Error:
...
This is the first step in having human readable panics. Next we
should implement Display for errors that can generate panics.
> pretty print panics

- jailer/src/cgroup.rs
Issue #, if available: #842 
Description of changes: According to the cgroups man page, the device used in the mount point
can be 'none'. Modify the regex used in the jailer to also match that.
> Jailer: Allow 'none' device for cgroups

- tests/integration_tests/functional/test_logging.py
- vmm/src/default_syscalls.rs
Issue #, if available: #845, #847
* whitelisted the `KVM_GET_DIRTY_LOG` ioctl in the seccomp filters. It was not getting through with the advanced filters, causing a SIGSYS and a failure to get the actual dirtied page count, which stayed 0.
* verified in the corresponding integration test that the metric is correctly emitted (i.e. after the microVM has been up for some time, it has dirtied a positive number of pages).
> Fix dirty page logging functionality and corresponding integration test

- Cargo.lock
- arch/Cargo.toml
- arch/src/lib.rs
- arch/src/x86_64/gdt.rs
- arch/src/x86_64/interrupts.rs
- arch/src/x86_64/regs.rs
- cpuid/Cargo.toml
- cpuid/src/c3_template.rs
- cpuid/src/lib.rs
- cpuid/src/t2_template.rs
- kvm/Cargo.toml
- kvm/src/cap.rs
- kvm/src/ioctl_defs.rs
- kvm/src/lib.rs
The kvm_wrapper crate was deprecated in favor of kvm-bindings.
> replace kvm_wrapper with kvm-bindings

- CHANGELOG.md
- api_server/src/http_service.rs
- api_server/swagger/firecracker.yaml
- arch/src/x86_64/mptable.rs
- vmm/src/vmm_config/machine_config.rs
Fix a panicking when creating a VM with 255 vCPUs.
> x86_64: limit maximum number of supported CPUs

- README.md
**Summary**
* There seems to be a common misconception in the Firecracker Slack
channel that you have to start off by building Firecracker when there
are binaries ready for download that don't require the whole docker
setup. Bit me and I've seen some other people in the Slack do the same
thing
* Hopefully this gives a useful pointer to where to look if you just
want to run Firecracker
> Clarify getting started section of README

- api_server/src/lib.rs
- devices/src/legacy/i8042.rs
- devices/src/legacy/serial.rs
- devices/src/lib.rs
- devices/src/virtio/block.rs
- devices/src/virtio/net.rs
- devices/src/virtio/vhost/mod.rs
- src/main.rs
- sys_util/src/eventfd.rs
- vmm/src/device_manager/legacy.rs
- vmm/src/device_manager/mmio.rs
- vmm/src/lib.rs
- Removes the usage of `sys_util::Error` in `EventFd`, in the spirit of #858 . Originally part of #863, but split off to expedite merging and to keep work in scope, as recommended in https://github.com/firecracker-microvm/firecracker/pull/863#pullrequestreview-195704361
- Added Debug and Display implementations for api_server errors
- Fixed error output/panics in main as well
> Drop usage of `sys_util::Error` in `EventFd`

- CHANGELOG.md
- api_server/swagger/firecracker.yaml
Tighten the API definition to better match the implementation:
- explicitly specify required fields
- explicitly specify read-only fields
- add missing `vmm_version` field in the API definition
> api: tighten swagger definition

- .mailmap
- tools/devtool
Issue #, if available: #821 
Description of changes: added a `devtool` command that changes the version number, updates cargo dependencies,  the list of contributors and the changelog. Added 2 more name/email deduplications for the credits list.
Testing done:
```bash
tools/devtool release 0.14.1
[Firecracker devtool] Updating from 0.14.0 to 0.14.1 ...
[Firecracker devtool] Continue? (y/n) y
[Firecracker devtool] Updated version number in source files.
Updating crates.io index
...
```
```diff
diff --git a/CHANGELOG.md b/CHANGELOG.md
index 4e719bf..4f4de06 100644
--- a/CHANGELOG.md
+++ b/CHANGELOG.md
@@ -1,6 +1,6 @@
-## [Unreleased]
+## [0.14.1]
diff --git a/CREDITS.md b/CREDITS.md
index eadb113..e981e65 100644
--- a/CREDITS.md
+++ b/CREDITS.md
@@ -42,11 +42,14 @@ Contributors to the …
```
> Release automation with devtool

- CHANGELOG.md
- devices/src/lib.rs
- devices/src/virtio/block.rs
Issue #, if available: #857 and (partly) #865.
- Fixed virtio-blk flush request handling: now, our device advertises flush functionality and handles flush requests correctly (i.e. the requests may or may not contain a data buffer).
- Fixed a couple of possible bound check problems.
> virtio-blk flush and bound checks

- tests/integration_tests/build/test_coverage.py
This PR resolves #829 by more or less forcing future PR authors to both avoid decreasing overall code coverage, and to update `COVERAGE_TARGET_PCT` in `test_coverage.py` so the target percentage closely follows the currently achieved percentage.
Using this approach, we get the adaptive coverage threshold behavior with each PR by default, without having to build more tooling.
The downside is that submitting successful PRs becomes a bit more awkward, but hopefully this won't be such a big issue once people become accustomed to it (and the test failure message is pretty clear about what needs to be done) :D
Thoughts?
> [RFC] Adaptive coverage threshold based on assisted dilligence

- tools/devtool
- vmm/src/default_syscalls/x86_64.rs
- vmm/src/sigsys_handler.rs
- Updated dev container to Rust 1.32
- Added brk() to the seccomp whitelist (needed to support Rust 1.32)
Closes #870 
> Update to Rust 1.32

- CHANGELOG.md
- api_server/src/request/actions.rs
- api_server/swagger/firecracker.yaml
- devices/src/legacy/i8042.rs
- devices/src/legacy/mod.rs
- docs/api_requests/actions.md
- tests/integration_tests/functional/test_api.py
- vmm/src/device_manager/legacy.rs
- vmm/src/lib.rs
- vmm/src/vstate.rs
Issue #, if available: #673 
Added a new API action to send CTRL+ALT+DEL to the guest. This can be used to trigger a graceful shutdown of the microVM, if the guest has support for i8042 (CONFIG_SERIO_I8042) and AT Keyboard (CONFIG_KEYBOARD_ATKBD).
> [RFC] New API action: SendCtrlAltDel

- jailer/src/lib.rs
- tests/integration_tests/build/test_coverage.py
Issue #, if available: #873 
improve jailer startup time by changing the strategy used to sanitize
the process. Close all the file descriptors listed in /proc/self/fd
instead of trying to close all the file descriptors from 3 until
libc::_SC_OPEN_MAX
> improve jailer startup time

- CHANGELOG.md
- devices/src/virtio/net.rs
- logger/src/metrics.rs
Issue #, if available: #762
Added a new metric (`net.tx_spoofed_mac_count`), to count the number of egress packets, having a spoofed MAC (i.e. different from the one set via `PUT /network-interfaces`, if one was provided).
Closes #762 
> Added guest MAC spoofing detection

- tools/devtool
- tools/update-credits.sh
Issue #, if available: #821 
Added a few minor adjustments to make `devtool prepare_release` work with the macOS/BSD tools and environment. Tested on macOS only, but it's nice to say "BSD". BSD.
> devtool prepare_release: fix for macOS/BSD

- Cargo.lock
- arch/src/x86_64/mod.rs
- arch/src/x86_64/mptable.rs
- arch_gen/Cargo.toml
- arch_gen/src/lib.rs
- arch_gen/src/x86/mod.rs
Issue #, if available: Fixes #871 
Since rust prohibits that a foreign trait is implemented by a foreign type, we defined a wrapper over the foreign type as a workaround.
> remove memory dependency for arch_gen

- api_server/swagger/firecracker.yaml
Swagger operationId is often used by code generators.
But the current `/machine-config get` does not have it.
> Add Swagger operationId of /machine-config get

- Cargo.lock
- Cargo.toml
- api_server/src/lib.rs
- jailer/Cargo.toml
- jailer/src/env.rs
- jailer/src/lib.rs
- src/main.rs
- tests/framework/jailer.py
- tests/framework/microvm.py
- tests/integration_tests/build/test_coverage.py
- vmm/src/lib.rs
- vmm/src/vmm_config/net.rs
- vmm/src/vstate.rs
This is leftover logic from when `seccomp()` was done in jailer and Firecracker was not allowed to `open()` anything.
Now, Firecracker does `seccomp()` itself just before booting the guest, which means it can also set up its own resources beforehand.
> Remove file descriptor inheritance from Jailer to Firecracker

- CHANGELOG.md
- logger/src/metrics.rs
- vmm/src/sigsys_handler.rs
Issue #, if available: #869
Description of changes: Removed the `bad_syscalls` array metric. In case of seccomp fault, the offending syscall is already logged and the exit code is already appropriately set.
> Metrics: remove `bad_syscalls`

- CHANGELOG.md
- vmm/src/default_syscalls/x86_64.rs
Issue #, if available: #982
Description of changes: Allow `madvise(MADV_DONTNEED)`, which [can be called by the musl allocator](https://elixir.bootlin.com/musl/v1.1.20/source/src/malloc/malloc.c#L501).
> seccomp: allow madvise(*, *, MADV_DONTNEED)

- tests/framework/defs.py
Issue #976 
Description of changes: Bumps the API Timeout from 100 to 200ms for all API calls during testing to avoid unnecessary vsock errors. This does increase the timeout for _all_ API calls, not just vsock, which should be noted.
> tests: increase api timeouts from 100 to 200ms

- Cargo.lock
- kvm/Cargo.toml
- kvm/src/lib.rs
- memory_model/src/mmap.rs
- vmm/src/lib.rs
- vmm/src/vstate.rs
Issue #, if available: #932 
Remove dependency on memory-model crate.
Refactored some functions to receive the kvm bindings structure instead of individual parameters.
Refactored kvm get dirty log to not assume that the memory size is a multiple of 256KB.
> Remove kvm dependency on memory_model

- api_server/src/request/mod.rs
- arch/src/lib.rs
- arch/src/x86_64/mod.rs
- vmm/src/vstate.rs
Since there is no Zero Page concept under aarch64,
move the related errors under specific x86_64 code.
> ARM: corectly place x86_64 specific error

- CHANGELOG.md
- tools/devtool
Issue #, if available: #901 
Description of changes: Added a `devtool tag $release` command that takes the text from `CHANGELOG.md` between the specified version and the previous one, removes header markers (`#`) and replaces `-` with `*` and uses it as the tag message for a new release tag.
Testing done:
```bash
tools/devtool tag asdf
[Firecracker devtool] Invalid version number: asdf (expected: $Major.$Minor.$Build).
tools/devtool tag 1.2.3
[Firecracker devtool] No changelog entry for release 1.2.3 can be found.
tools/devtool tag 0.14.0
[Firecracker devtool] Preparing to create tag...
[Firecracker devtool] Tag: v0.14.0
[Firecracker devtool] Tag text:
Added
* Documentation for development environment setup on AWS in
`dev-machine-setup.md`.
* Documentation for microVM networking setup in …
```
> devtool: add command to create release tag

- FAQ.md
- docs/rootfs-and-kernel-setup.md
Added a short guide on creating uncompressed kernel and rootfs images, that can be used with Firecracker.
> docs: rootfs and kernel image creation guide

- arch/src/aarch64/layout.rs
- arch/src/lib.rs
- arch/src/x86_64/layout.rs
- vmm/src/device_manager/mmio.rs
- vmm/src/lib.rs
Issue #, if available: #757 
Description of changes: The interrupts assignment (irq base, maximum irq) is platform dependent but up until now we would be hard coding those for x86_64 inside the mmio device manager. Refactored the code accordingly.
> Platform dependent irq assignment for the mmio device manager

- arch/src/aarch64/layout.rs
- arch/src/aarch64/mod.rs
The code follows the memory address mapping of a 64-bit guest.
Link to documentation can be found in the following diff.
Issue #, if available: #757 
> arm64: added memory layout representation

- kvm/src/lib.rs
- tests/integration_tests/build/test_coverage.py
We weren't checking the MMIO Read & MMIO Write because we were actually
performing read & write to an address that was part of the guest memory.
Issue #, if available: #999 
> fixed the test for the kvm_run loop

- api_server/src/request/mod.rs
- tests/integration_tests/build/test_coverage.py
- vmm/src/lib.rs
On aarch64 KVM_CREATE_VCPU needs to be called before setting up the
IRQCHIP, while on x86 it needs to be called after setting up the
IRQCHIP. Consequently the configuration of the vcpus was moved to a
different function.
Also, architecture specific labeling was added.
Issue #, if available: #757 
> vmm: move logic for creating vcpus

- vmm/src/lib.rs
Vcpus have an `id` which is a 0-based index, and this `id` matches the guest vCPU index. We also add this `id` in the name of each Firecracker vCPU thread so that guest vCPU index can be matched to a host thread.
This PR fixes this mapping since `.pop()` effectively reverses the order in which vcpus are consumed from a vec, by also reversing the order in which we iterate over the `id` numbers.
> vmm: fix vCPU-thread mapping

- api_server/src/request/mod.rs
- kernel/src/loader/mod.rs
- vmm/src/lib.rs
- vmm/src/vmm_config/instance_info.rs
Issue #855  
Transform the `map_err()` into an   ##`expect()`.
> fix error message when writing commandline to memory

- docs/getting-started.md
- tests/integration_tests/build/test_build.py
- vmm/src/default_syscalls/x86_64.rs
This pull request adds support for building Firecracker with the default Rust toolchain and without the docker container. This is nice, because building Firecracker on Ubuntu 18.04 is now as simple as:
```
sudo apt install rustc cargo
cargo build --target x86_64-unknown-linux-gnu
```
No Docker is required and building uses familiar Rust tools directly.
#647 tried to achieve the same. I'll let the Firecracker experts decide whether any of the changes in that PR are still necessary.
@andreeaflorescu was so nice to add integration testing (and went slightly overboard with refactoring :+1:  ).
> Add support for building with system Rust toolchain (glibc)

- cpuid/src/common.rs
- cpuid/src/cpu_leaf.rs
- cpuid/src/lib.rs
- cpuid/src/template/c3.rs
- cpuid/src/template/t2.rs
- cpuid/src/transformer/amd.rs
- cpuid/src/transformer/common.rs
- cpuid/src/transformer/intel.rs
- cpuid/src/transformer/mod.rs
- kvm/src/lib.rs
> Fix AMD boot freeze

- cpuid/src/common.rs
- tests/integration_tests/build/test_coverage.py
- tests/integration_tests/performance/test_boottime.py
- vmm/src/default_syscalls/x86_64.rs
- vmm/src/lib.rs
- vmm/src/vmm_config/instance_info.rs
- vmm/src/vstate.rs
Move the main loop being run by vCPU threads from the generic `vmm/src/lib.rs` inside the implementation of the existing `vcpu` struct defined in `vmm/src/vstate.rs`.
Fixes https://github.com/firecracker-microvm/firecracker/issues/1002.
> move 'floating' vCPU code to the `vcpu` struct

- CHANGELOG.md
We do not yet have a process for merging back the changelog changes
that are made by hot fixes releases. To keep the CHANGELOG.md up
to date, manually add the entries.
This manual update should be a one time thing (hopefully).
> manually update the CHANGELOG.md

- CHANGELOG.md
- api_server/src/http_service.rs
- fc_util/src/validators.rs
- micro_http/src/common/mod.rs
- mmds/src/data_store.rs
- mmds/src/lib.rs
- rate_limiter/src/lib.rs
Signed-off-by: ylyu <lyuyuan92@gmail.com>
#529
1. Add data validator method Mmds::is_data_valid().
2. Call is_data_valid in put and patch to valid the payload first.
3. Add BadRequest response in http_service if put/patch data is invalid.
> Let MMDS accept only String values on PUT and PATCH

- arch/src/aarch64/gic.rs
- arch/src/aarch64/layout.rs
- arch/src/aarch64/mod.rs
- vmm/src/lib.rs
- vmm/src/vstate.rs
Implements the GICv3 for handling interrupts on aarch64.
===CAUTION===
This PR will initially fail the CI cause it is based on #1039 getting fixed.
Edit1: Unit tests were added and cargo test inside vmm crate is succesful except for the test_run_vcpu which will be succesful after `configure` is implemented for the vcpu.
> aarch64: setup the interrupt controller (GIC)

- api_server/src/request/mod.rs
- tests/integration_tests/build/test_coverage.py
- vmm/src/lib.rs
- vmm/src/vmm_config/net.rs
- vmm/src/vstate.rs
Implement `std::convert::From<T> for VmmActionError` and mark each `VmmActionError` with the correct `ErrorKind`.
Fixes issue: https://github.com/firecracker-microvm/firecracker/issues/1062
>  Set each VmmActionError kind based on inner error

- cpuid/src/cpu_leaf.rs
- cpuid/src/transformer/amd.rs
- cpuid/src/transformer/common.rs
- tests/integration_tests/build/test_coverage.py
- tests/integration_tests/functional/test_cpu_features.py
> Add cpuid features integration tests

- CHANGELOG.md
- api_server/src/http_service.rs
- api_server/src/request/machine_configuration.rs
- api_server/swagger/firecracker.yaml
- logger/src/metrics.rs
- tests/integration_tests/functional/test_api.py
- tests/integration_tests/functional/test_logging.py
#557 
Let Vmm::set_vm_configuration() use default values if any optional parameter is missing.
> Add PATCH and change PUT MachineConfig API calls

- api_server/swagger/firecracker.yaml
Mark the mandatory fields in machine-config as required.
This will ensure that swagger code generators will not omit
boolean fields when set to false.
Signed-off-by: Manohar Castelino <manohar.r.castelino@intel.com>
> swagger: Fix swagger definition for machine-config

- CHANGELOG.md
- README.md
- api_server/swagger/firecracker-experimental.yaml
- tests/integration_tests/build/test_style.py
Fixes https://github.com/firecracker-microvm/firecracker/issues/1085
Added firecracker-experimental.yaml in api_server/swagger.
This file is a copy of firecracker.yaml with an additional definiton
for the vsock API request.
The point of this file is to be used by third-party projects (like
Kata Containers) to automatically generate an API client that knows
how to send requests to the Firecracker API. The definition currently
lies in a different file and not in firecracker.yaml because vsock
is consider an experimental feature. Once the production ready vsock
is merged we will get rid of this experimental yaml.
For tracking purposes, this is the issue regarding switching to
vsock with UDS:
https://github.com/firecracker-microvm/firecracker/issues/650
In the new …
> added vsock definition in experimental yaml

- api_server/src/request/mod.rs
- kernel/src/cmdline/mod.rs
- kernel/src/loader/mod.rs
- vmm/src/device_manager/mmio.rs
- vmm/src/lib.rs
- vmm/src/vmm_config/instance_info.rs
- vmm/src/vstate.rs
Register legacy devices IRQs as part of legacy device registration, do IRQCHIP and PIT creation independently as part of (kvm) VM init.
Also do a bit of refactoring around kernel cmdline to move some ugly logic out of vmm.
Setting up an interrupt controller should, well.. set up an interrupt controller (irqchip) without having a dependency on a particular list of devices that will eventually use it.
Move the registering of legacy devs irqs to `attach_legacy_devices()` which already does the registering of legacy devs bus addrs.
Before this patch the implementation was not just spaghetti but also incorrect because it would register irqs for devices not yet attached.
> vmm: decouple legacy dev init from IRQCHIP creation

- devices/src/virtio/mmio.rs
- vmm/src/lib.rs
The generic part of a virtio device only needs access to the guest memory to configure said device. Once configuration is complete and device is activated, move instead of cloning the memory object to the device implementation.
> virtio generic device moves out ownership of Memory

- tests/framework/http.py
- tests/framework/microvm.py
- tests/integration_tests/performance/test_boottime.py
Issue #, if available: N/A
Description of changes: Disabled timing in timed tests on vsock builds.
* Disabled boot time test on the single microVM fixture - it doesn't appear to run at all on the multiple microVM fixture.
* Disabled timing API requests because `InstanceStart` (maybe others?) sometimes takes more with vsock.
* The option to disable timing on API requests is separate and can be used on other potentially long running APIs (I'm thinking MMDS).
```bash
pytest integration_tests/performance/test_boottime.py::test_single_microvm_boottime_no_network -vv
Boot time with no network is: 108668 us
PASSED
integration_tests/performance/test_boottime.py::test_single_microvm_boottime_no_network[minimal-vsock] SKIPPED
0.71s call …
```
> Disable timing on vsock integration tests

- seccomp/src/lib.rs
- vmm/src/default_syscalls/aarch64.rs
- vmm/src/default_syscalls/macros.rs
- vmm/src/default_syscalls/mod.rs
- vmm/src/default_syscalls/x86_64.rs
- vmm/src/vstate.rs
Issue #, if available: Fixes #867 .
Description of changes: Whitelisted necessary syscalls for aarch64. Also, moved code common to x86_64 and aarch64 to mod.rs
> Aarch64 seccomp

- Cargo.lock
- arch/src/aarch64/fdt.rs
- arch/src/aarch64/mod.rs
- arch/src/lib.rs
- devices/Cargo.toml
- devices/src/legacy/mod.rs
- devices/src/legacy/rtc_pl031.rs
- devices/src/lib.rs
- logger/src/metrics.rs
- vmm/src/device_manager/mmio.rs
- vmm/src/lib.rs
Since on arm there is no kvmclock, we need to
implement an RTC device. Implements RTC PL031.
Follow specification:
https://static.docs.arm.com/ddi0224/c/real_time_clock_pl031_r1p3_technical_reference_manual_DDI0224C.pdf
Issue #, if available: Fixes #1066 
> aarch64: Implement RTC Pl031 

- arch/src/aarch64/fdt.rs
- arch/src/aarch64/mod.rs
- arch/src/lib.rs
- devices/src/lib.rs
- devices/src/virtio/block.rs
- devices/src/virtio/mod.rs
- devices/src/virtio/net.rs
- devices/src/virtio/vhost/handle.rs
- devices/src/virtio/vhost/mod.rs
- tests/integration_tests/build/test_coverage.py
- vmm/src/device_manager/mmio.rs
- vmm/src/lib.rs
- vmm/src/vmm_config/drive.rs
> VirtIO: Make it easy to access the BusDevice and EpollHandler starting from a device id

- CHANGELOG.md
- CREDITS.md
- Cargo.lock
- Cargo.toml
- api_server/swagger/firecracker-experimental.yaml
- api_server/swagger/firecracker.yaml
- docs/api_requests/actions.md
- docs/getting-started.md
- jailer/Cargo.toml
- tools/devtool
Issue #, if available: 
* Fixes #1101.
* Fixes #1135.
> Release v0.17.0

- cpuid/src/common.rs
- cpuid/src/cpu_leaf.rs
- cpuid/src/lib.rs
- cpuid/src/template/c3.rs
- cpuid/src/template/t2.rs
- cpuid/src/transformer/amd.rs
- cpuid/src/transformer/common.rs
- cpuid/src/transformer/intel.rs
- cpuid/src/transformer/mod.rs
- vmm/src/vstate.rs
Issue #, if available: #1025 
Description of changes: Use BitHelper and CpuidTransformer for the cpuid templates
> Refactor cpuid templates

- devices/src/lib.rs
- devices/src/virtio/block.rs
- devices/src/virtio/net.rs
- devices/src/virtio/vhost/handle.rs
- vmm/src/lib.rs
**Description of changes**
Fixed a recent code regression, that removed the epoll event set from the epoll handler parameters.
--
> vmm/epoll: pass event set to epoll handler

- devices/src/virtio/block.rs
- devices/src/virtio/net.rs
- devices/src/virtio/queue.rs
- tests/integration_tests/build/test_coverage.py
Added a new VirtIO queue manipulation pattern, without the use of the currently employed available chain iterator. Available descriptor chains can now be popped straight from the queue.
The offending iterator used to hold a mutable reference to the VirtIO queue, which hindered the get_avail/add_used/maybe_rewind_iterator cycle, since that implied performing mutable actions on both the iterator and the queue itself. Workarounds included creating and dropping the iterator with each iteration (the `while let Some(desc) = queue.iter().next()` pattern).
This PR changes that behavior by dropping the iterator altogether, and replacing it with queue-provided manipulation methods, such as:
- `pop()` - fetch the next avail chain; and
- `undo_pop()` - place the last …
> device/virtio: new queue processing pattern

- CHANGELOG.md
- api_server/swagger/firecracker-experimental.yaml
Description of changes: Due to indentation issues swagger was unable to generate code.
Fix the indentation issues with vsock fields.
The error was
```
swagger generate client -f ./firecracker-experimental.yaml --model-package=client/models --client-package=client
2019/06/18 17:20:06 validating spec ./firecracker-experimental.yaml
The swagger spec at "./firecracker-experimental.yaml" is invalid against swagger specification 2.0. see errors :
- definitions.TokenBucket.Vsock in body is a forbidden property
- paths./network-interfaces/{iface_id}./vsocks/{id} in body is a forbidden property
```
Signed-off-by: Manohar Castelino <manohar.r.castelino@intel.com>
> firecracker-experimental: Fix indentation issues

- devices/src/lib.rs
- devices/src/virtio/net.rs
- tests/integration_tests/build/test_coverage.py
Fixes #1049 
If the guest virtio-net driver didn't make any RX buffers available, the virtio-net device would busy-spin on tap RX events, unable to consume them, causing host CPU usage to spike needlessly.
This PR changes the virtio-net device behavior to listen to tap RX events, only when there are RX buffers available.
**Note**: this PR is rebased on #1156 , so only the last two commits in here are of interest.
------
> devices/net: fix busy spin when no RX buffers are available

- logger/src/metrics.rs
- vmm/src/vstate.rs
Issue #, if available: fixes #1121
Description of changes: Fixes a typo where filter_cpuid was called fitler_cpuid. Also fixed an issue where the filter_cpuid metric wasn't incremented anywhere; also, adds an error log in this case.
Signed-off-by: Tamio-Vesa Nakajima tnk@amazon.com
> logger/src, vmm: Fixed typo and added `filter_cpuid` metric

- tests/integration_tests/security/test_sec_audit.py
- tools/devctr/Dockerfile.x86_64
- tools/devtool
Description of changes: See [doc](https://github.com/RustSec/cargo-audit).
New docker image with tag **v9** was added to docker repo.
> CI: run cargo audit on Cargo.lock deps

- sys_util/src/struct_util.rs
This improves the equal assert, by presenting the accurate expected error type.
> add expected error type to equal assert

- docs/getting-started.md
Since v0.16.0 @YLyu add more limitations.
Sending machine-config as this doc will trigger this error:
`{"fault_message": "Missing mandatory fields."}`
Signed-off-by: Shen Jiale <shenjiale@baidu.com>
> Add mandatory "ht_enabled" field for doc example

- Cargo.lock
- Cargo.toml
- api_server/Cargo.toml
- api_server/src/lib.rs
- devices/Cargo.toml
- devices/src/legacy/rtc_pl031.rs
- devices/src/lib.rs
- devices/src/virtio/net.rs
- dumbo/src/ns.rs
- dumbo/src/tcp/connection.rs
- fc_util/src/lib.rs
- logger/Cargo.toml
- logger/src/lib.rs
- logger/src/metrics.rs
- memory_model/src/guest_memory.rs
- rate_limiter/Cargo.toml
- rate_limiter/src/lib.rs
- src/bin/jailer.rs
- vmm/Cargo.toml
- vmm/src/lib.rs
Instead of using the time and chrono crates, we implemented some functionality in the 'fc_util' crate. It uses the UNIX syscall 'clock_gettime', which is also what time and chrono used on Linux, so no precision is lost. Where possible, we used 'Instant' from 'std::time' to measure elapsed time, as the time crate was deprecated and it is at least as accurate. However, we could not use 'std::time' everywhere as it doesn't support getting CPU clocks and system wall time.
Issue #, if available: fixes #1123 
> Removed dependency on time and chrono crates

- CHANGELOG.md
- tests/README.md
Description of changes: The integration tests' README has fallen behind, made no mention of running the integration tests with the dev container, and wasn't very helpful with the howto for adding new image capabilities. Updated usage examples and features to reflect running tests in the container.
> README update in integration tests

- dumbo/src/tcp/endpoint.rs
- micro_http/src/common/headers.rs
- micro_http/src/common/mod.rs
- micro_http/src/lib.rs
- micro_http/src/request.rs
- micro_http/src/response.rs
- mmds/src/lib.rs
- tests/integration_tests/build/test_coverage.py
The current version of `micro_http` now supports the GET, PUT and
PATCH methods. Aside from this, we also added specific header
support and refactored the parsing.
Issue #, if available: fixes #1191
> Enhanced micro_http implementation

- tools/devtool
Issue #, if available: #951 
Description of changes: The build script pre-creates `cargo_git_registry`, a directory used by cargo to store crates downloaded directly from GitHub.
> devtool: create cargo git registry dir if missing

- tests/README.md
Issue #, if available: NA
The repos is now under `firecracker-microvm` org, but tests/README.md still mentions `aws` org.
> The repos is now under `firecracker-microvm` org

- Cargo.lock
- net_util/Cargo.toml
- Updated `Cargo.lock` (via `cargo update`) in order to get rid of the `spin` crate dependency. `cargo audit` was reporting an issue with the version we were pulling in, causing our CI to fail all PRs;
- Updated our `pnet` version dependency.
--------
> Hasty cargo update

- .github/PULL_REQUEST_TEMPLATE.md
- .github/pull_request_template.md
To ensure that the Firecracker docs and changelog are updated with each PR
where that's needed, the PR template Is extended with an appropriate checklist.
The PR template now includes a checklist that encourages both author and
reviewer to verify that:
- The PR's commits are signed.
- The PR is well reasoned.
- The PR has a clear description.
- The PR includes documentation updates (if needed).
- The PR includes swagger API definition updates (if needed).
- The PR includes changelog updates (if needed).
> repo: expand PR template with checklist

- logger/src/metrics.rs
- vmm/src/signal_handler.rs
Issue #, if available: fixes #1205
Description of changes: Added testing and metrics for the SIGSEGV/SIGBUS signal handler. Also, refactors some of the signal handler testing to avoid some race conditions.
Signed-off-by: Tamio-Vesa Nakajima <tnk@amazon.com>
> Add metric to test SIGBUS, SIGSEGV signal handler.

- jailer/src/cgroup.rs
the regex used to determine where certain mount points are for controllers only assumes that everything is either a "cgroup" or a "none", not any specific controller type...
> jailer: fix regex mountpoint detection

- micro_http/src/common/headers.rs
- micro_http/src/common/mod.rs
- micro_http/src/connection.rs
- micro_http/src/lib.rs
- micro_http/src/request.rs
- micro_http/src/response.rs
- tests/integration_tests/build/test_coverage.py
This is just the outline of a functional HTTP Connection structure, which should later be used in the implementation of the HTTP Server.
Fixes: #1192 
Description of changes: Implemented HTTP Connection.
> Implemented `HttpConnection`

- rate_limiter/src/lib.rs
Signed-off-by: Tamio-Vesa Nakajima <tamiove@amazon.com>
The `RateLimiter::make_bucket` function had a dummy comment, and a typographical error had slipped into the rate_limiter crate. These should be fixed.
This PR fixes a minor typographical error in the rate_limiter crate, and fills in a missing comment.
located either in the repository root, or in the `docs/` directory.~~
code is included in this PR.~~
reflected in …
> Typographical error fixes for rate_limiter

- .mailmap
- CHANGELOG.md
- CREDITS.md
- Cargo.lock
- Cargo.toml
- api_server/swagger/firecracker.yaml
- docs/vsock.md
- jailer/Cargo.toml
Release v0.18.0.
- Fixed some typos left behind in `docs/vsock.md`.
- Updated `CHANGELOG.md` with all user-facing changes since v0.17.0.
- Fixed `CHANGELOG.md` (line length) formatting.
- Updated Firecracker version via `devtool prepare_release`.
> Release v0.18.0

- api_server/swagger/firecracker.yaml
The parameter "id" changed into "vsock_id" with the recent virtio-vsock
changes. This needs to be applied to the yaml file describing the client
API, otherwise swagger tool complains when generating the code.
> api_server/swagger: Fix yaml file with correct parameter vsock_id

- README.md
- docs/api_requests/patch-network-interface.md
Update outdated information in the `README`.
README.md: vsock is no longer experimental
> docs: README.md: vsock is no longer experimental

- seccomp/src/lib.rs
> fix seccomp unit tests output

- vmm/src/device_manager/mmio.rs
- vmm/src/lib.rs
This PR introduces a couple of changes which make it easier to use the `Vmm` object by importing the appropriate crates at the code interface level. It simplifies decoupling the operation of the `Vmm` struct from the API server, enriching the interface to allow easier access to some inner objects, and adding the `pub` modifier to a number of methods, so it can be driven by outside modules as well.
Same as above. Descriptions also available as part of the individual commit messages.
> Make the Vmm struct a bit more modular

- Cargo.lock
- net_gen/Cargo.toml
- net_gen/src/lib.rs
- net_util/src/lib.rs
- net_util/src/tap.rs
#603
Code that was not generated with bindgen was moved away from `net_gen` to the associated crate.
> net_gen: move away code that is not bindgen'd

- README.md
- docs/getting-started.md
Updated README.md Firecracker documentation
Documentation should be updated to reflect current FC implementation.
README.md documentation was falling behind current Firecracker implementation. Now,
Firecracker supports AMD and ARM CPUs. Also, after building FC, the resulted binaries will
reside in a different directory than the one specified in the current documentation.
Changes: README.md, docs/getting-started.md
located either in …
> Updated Firecracker doc.

- api_server/src/http_service.rs
- devices/src/bus.rs
- devices/src/legacy/serial.rs
- devices/src/virtio/block.rs
- devices/src/virtio/mmio.rs
- devices/src/virtio/mod.rs
- devices/src/virtio/net.rs
- devices/src/virtio/vsock/mod.rs
- kernel/src/cmdline/mod.rs
- vmm/src/device_manager/mmio.rs
- vmm/src/lib.rs
Rust 1.37 warns about using `Trait` instead of `dyn Trait` (https://github.com/rust-lang/rust/pull/61203/) and inclusive ranges with `...` syntax ranges instead of `..=` syntax (https://github.com/rust-lang/rust/issues/28237). 
I've fixed the specific instances where these two warnings appear in the firecracker code.
reflected in …
> Fix warnings with rust 1.37

- api_server/src/http_service.rs
- api_server/src/request/net.rs
- vmm/src/lib.rs
- vmm/src/vmm_config/net.rs
#1167 
This PR removes the `Tap` device from `NetworkDeviceConfig`. Instead of explicitly holding the device file all the time, we now re-open it when we either explicitly need it, or want to check if it is openable. This makes it so that `NetworkDeviceConfig` holds no live data.
this PR have user …
> Remove `Tap` device from `NetworkDeviceConfig`.

- devices/src/virtio/block.rs
Fixes: https://github.com/firecracker-microvm/firecracker/issues/1285
In the execute function, the disk_id was passed as an immutable
reference to a Vec<u8>. Since the reference is immutable, a slice
can be passed as well and the clippy allow macro for ptr_arg can
be safely removed.
this PR have …
> [device] pass disk_id as a slice

- CHANGELOG.md
- api_server/src/http_service.rs
- api_server/src/lib.rs
- docs/mmds.md
- src/main.rs
- tests/framework/jailer.py
- tests/framework/microvm.py
- tests/framework/vm_log_config.json
- tests/integration_tests/build/test_coverage.py
- tests/integration_tests/functional/test_cmd_line_start.py
- vmm/src/lib.rs
Signed-off-by: Laura Loghin <lauralg@amazon.com>
We want to allow the user to not use the API socket at all, if he configures the microvm with a configuration file and doesn't need to make post-boot operations (PATCH, GET calls).
Fixes: #1165
Added new command line parameter for Firecracker, named `--no-api` which will disable API server thread. Also, to avoid ambiguity, now the main thread is the VMM thread and the API thread is the one that is spawned from `main()`.
doc changes are included in this …
> Allow API socket deactivation by passing no-api parameter

- tests/integration_tests/security/test_sec_audit.py
Signed-off-by: Laura Loghin <lauralg@amazon.com>
On some machines, `test_sec_audit.py` fails because the output of `cargo audit` command contains some random characters between "Success" and "No vulnerable packages found". We can avoid that by checking the exit code of the command instead.
Changed test to check exit code of `cargo audit`.
> Changed check for cargo audit command

- api_server/src/http_service.rs
- api_server/src/request/actions.rs
- api_server/src/request/boot_source.rs
- api_server/src/request/drive.rs
- api_server/src/request/logger.rs
- api_server/src/request/machine_configuration.rs
- api_server/src/request/mod.rs
- api_server/src/request/net.rs
- api_server/src/request/vsock.rs
- cpuid/src/brand_string.rs
- devices/src/legacy/i8042.rs
- devices/src/virtio/block.rs
- devices/src/virtio/mmio.rs
- devices/src/virtio/net.rs
- devices/src/virtio/vsock/csm/txbuf.rs
- devices/src/virtio/vsock/unix/muxer.rs
- dumbo/src/pdu/tcp.rs
- jailer/src/env.rs
- kernel/src/loader/elf.rs
- memory_model/src/guest_address.rs
- micro_http/src/request.rs
- net_util/src/tap.rs
- src/main.rs
- sys_util/src/ioctl.rs
- sys_util/src/signal.rs
- vmm/src/lib.rs
#1287 , #1142
This does not fully fix #1287, but approximately halves the number of ignored clippy lints.
This PR does mainly stylistic refactoring in order to remove many occurrences ```#[allow(clippy::...)]```. The only meaningful change is a change in the definition of ```ParsedRequest```, boxing the largest enum variant. This will make our code more efficient, as the enum will no longer be forced to have its largest possible size at all times.
doc changes are included in this PR. Docs in scope are …
> Stop ignoring many clippy lints.

- tests/integration_tests/build/test_coverage.py
Remove some of the frustration that comes with
a PR failing this test by actually showing what
numbers lead to the coverage value obtained.
Two more variables are now displayed in the CI output that explain
the number associated with the kcov percentage.
reflected in …
> CI: improve output of kcov test

- README.md
Fixes: https://github.com/firecracker-microvm/firecracker/issues/1298
Used a permanent invitation link in the README. This uglifies the
text version of the readme a bit, but the link never experies as
oppose to using tiny URLs.
this PR have user impact and have been added to the `CHANGELOG.md` …
> fixed slack invitation link in README.md

- CHANGELOG.md
- devices/src/virtio/vsock/mod.rs
- vmm/src/lib.rs
- vmm/src/vmm_config/instance_info.rs
The `CreateVsockDevice` error does not propagated
the error that triggers it.
Also this would be used for creation of the
backend and also for the device itself. These
changes also adds two different errors for those
different scenarios.
Fixes #1279.
* Split `CreateVsockDevice` into `CreateVsockBackend` and `CreateVsockDevice`
* Propagate error for the above mentioned errors
The Error message from #1279 now looks like this:
`  "fault_message": "Cannot create backend for vsock device: UnixBind(Os { code: 98, kind: AddrInUse, message: "Address in use" })"
`
`[Reviewer TODO: Verify that these criteria …
> Improve failure message for vsock device creation

- CHANGELOG.md
- FAQ.md
- resources/microvm-kernel-config
Added KVM_PTP support in the recommended guest kernel config.
Added FAQ entry describing how to use KVM_PTP for guest timekeeping.
> Documentation for guest timekeeping

- tests/host_tools/cargo_build.py
- tests/integration_tests/build/test_build.py
- tests/integration_tests/build/test_unittests.py
Remove test for building with `debug` profile, only test building `release`.
Skip running unit tests on X86_64 with `musl` target where the unit tests are also run as part of testing code coverage.
This shaves off around 4-5 minutes from a full test run on x86_64.
Fixes #1308 
this PR have user …
> tests: eliminate some redundant steps in our CI

- micro_http/src/common/headers.rs
- micro_http/src/lib.rs
- micro_http/src/response.rs
As we're starting to use the `micro_http` crate from the cloud-hypervisor project, we have a few very minor fixes/improvements. This is an upstream submission tentative.
* Export the `Method` enum
* Clippy fix
* Allow for setting the HTTP response header `Server` field as there might be other consumer of the micro_http crate than Firecracker.
code is included in …
> micro_http fixes and enhancements

- CHANGELOG.md
- api_server/swagger/firecracker.yaml
- vmm/src/lib.rs
- vmm/src/vmm_config/instance_info.rs
Instance states `Halting` and `Halted` were unused/unsupported. Removed them.
> vmm: remove unused Vmm InstanceStates

- api_server/src/http_service.rs
- api_server/src/lib.rs
- api_server/src/request/actions.rs
- api_server/src/request/boot_source.rs
- api_server/src/request/drive.rs
- api_server/src/request/logger.rs
- api_server/src/request/machine_configuration.rs
- api_server/src/request/mod.rs
- api_server/src/request/net.rs
- api_server/src/request/vsock.rs
- logger/src/metrics.rs
- src/main.rs
- vmm/src/device_manager/mmio.rs
- vmm/src/lib.rs
- moves the vmm driving logic outside the vmm for more maneuverability,
- completely decouples the vmm from the api_server, the vmm can now be controlled using whichever control method the external driver chooses.
> Completely decouple the vmm from the api_server

- jailer/src/cgroup.rs
Signed-off-by: chaos matrix <mythsphoenix@outlook.com>
```
It might be better replace 'keys().len()' with 'len()' to get the number of elements in HashMap,
even there's no clear performance impact.
```
```
replace 'keys().len()' with 'len()' to get the size of HashMap
```
this PR have user impact …
> jailer: replace 'keys().len()' with 'len()' to get the size of HashMap

- api_server/src/lib.rs
- api_server/src/request/actions.rs
- src/main.rs
- vmm/src/device_manager/legacy.rs
- vmm/src/device_manager/mmio.rs
- vmm/src/error.rs
- vmm/src/lib.rs
- vmm/src/vmm_config/instance_info.rs
- vmm/src/vstate.rs
Fixes #1340 
Firecracker doesn't currently have `i8042` support on `aarch64`. Because of this, disable and provide a clear error message for the `SendCtrlAltDel` API request.
Also mark all the port-io code as `x86_64` specific.
this PR have user impact and have been added to the `CHANGELOG.md` …
> Disable unsupported `SendCtrlAltDel` API action on aarch64

- vmm/src/error.rs
- vmm/src/lib.rs
- vmm/src/vstate.rs
KvmContext is actually coupled to the
functonality defined in vstate since it
all handles kvm interaction. Move it there and
make the appropriate changes.
The commit says it all.
> vmm: move `KvmContext` to vstate file

- micro_http/src/connection.rs
- micro_http/src/lib.rs
- add extra `micro_http` documentation
- fix a case where errors in `try_read` now lead to dropping all requests that we have not yet yielded to the user and marking the connection as being closed
> Extra `micro_http` documentation and connection error fix

- arch/src/aarch64/fdt.rs
- arch/src/aarch64/gic.rs
- arch/src/aarch64/gicv2.rs
- arch/src/aarch64/gicv3.rs
- arch/src/aarch64/mod.rs
- vmm/src/lib.rs
- vmm/src/vstate.rs
This PR is meant to address #1196 for supporting GICv2 devices on aarch64 architecture.
This makes the GIC-related code more flexible and implements a GICv2 device. It introduces a `GICDevice` Trait which needs to be implement by GIC device implementations. We implement the Trait for GICv3 and GICv2 devices. When creating the GIC device for the microVM we initially try to create a v3 device and if that fails, we fall back to creating a v2 device.
I have tried this on a Hikey970 board and it works, so far. I 'm trying this out on a RPi4 as well to double check everything is working. In any case, I'm not greatly familiar with the GIC architecture (I did some research for this PR), so any comments on what I 've done so far is more that welcome.
By submitting this pull request, I confirm that …
> gicv2 support

- CHANGELOG.md
- arch/src/aarch64/fdt.rs
- arch/src/aarch64/mod.rs
- arch/src/aarch64/regs.rs
- tests/framework/state_machine.py
- tests/integration_tests/functional/test_max_vcpus.py
- tests/integration_tests/functional/test_serial_io.py
- vmm/src/lib.rs
- vmm/src/vstate.rs
Fixes #1283 - Can't start a VM in AARCH64 with vcpus number more than 16. 
Changes:
- added integration test for booting with max vcpus
- moved common state machine code to tests/framework
Changes relevant to ARM platform:
- implement read_mpdir() function
- implement arm64_sys_reg macro
- add vcpu array parameter to vmm.configure_system()
- add vcpu mpidr array parameter to create_fdt()
- use mpidr in fdt.rs/create_cpu_nodes
> Properly set 'reg' field for fdt cpu nodes.

- Cargo.lock
- api_server/Cargo.toml
- api_server/src/lib.rs
- api_server/src/request/net.rs
- devices/src/virtio/net.rs
- dumbo/Cargo.toml
- dumbo/src/lib.rs
- dumbo/src/mac.rs
- dumbo/src/ns.rs
- dumbo/src/pdu/arp.rs
- dumbo/src/pdu/ethernet.rs
- dumbo/src/pdu/ipv4.rs
- dumbo/src/pdu/mod.rs
- dumbo/src/pdu/tcp.rs
- dumbo/src/pdu/udp.rs
- net_util/Cargo.toml
- net_util/src/lib.rs
- net_util/src/tap.rs
- tests/integration_tests/build/test_coverage.py
- vmm/Cargo.toml
- vmm/src/lib.rs
- vmm/src/vmm_config/net.rs
Fixes #612 
1. parse UDP datagrams
2. replace pnet::packet with dumbo's sutff
3. move MacAddr from `net_util` to dumbo
4. use UdpSocket in `test_write`, `test_read` in `tap.rs` ARP reply construction was needed to make this work
5. Use host-IPs instead of hardcoded ones since the packets will be routed
reflected in …
> Remove pnet dependency

- CHANGELOG.md
- vmm/src/default_syscalls/filters.rs
#1088 - `SYS_mremap` is called by `libbacktrace` when building the stack trace and was causing a seccomp fault, terminating Firecracker by `SIGSYS` before it got the chance to log the trace.
Note that Firecracker still dies by `SIGSYS` if a panic occurs because of its `panic=abort` configuration. `musl` aborts the process by literally raising `SIGABRT`, and blocks all signals while doing so. To block signals it uses `rt_sigprocmask`, which is blacklisted => seccomp fault. This is in the end okay as the process was going to die anyway and, with this fix, at least we have the stack trace.
Whitelisted `SYS_mremap`.
> Whitelist SYS_mremap to allow the backtrace to be built and printed.

- devices/src/virtio/block.rs
- devices/src/virtio/mmio.rs
- devices/src/virtio/mod.rs
This PR contains some small updates to the virtio implementation that should make it easier to map the Firecracker code to the virtio spec.
- Group Device Status in a module so that we can have an associated namespace. Renamed the Device Status fields so that they map to the virtio spec.
- Renamed variables and function names where "driver" was used instead of "device"
- Virtio Block Device: added a RequestHeader used for simplifying the parsing of the Request.   
doc changes are included in this PR. …
> Tiny Updates to Virtio Impl

- tests/framework/jailer.py
- tests/integration_tests/functional/test_drives.py
- vmm/src/lib.rs
#1316
When a virtio device is backed by a block device, the actual size of the block device file doesn't represent the size as a virtio device.
> Fix the size of a virtio device, backed by a block device

- tests/integration_tests/build/test_coverage.py
- vmm/src/lib.rs
- vmm/src/vstate.rs
The VMM has two fields (among others):
Vm and guest_mem. The Vm has another guest_mem
field which is a clone of the one found in the
VMM. Removed it from the VMM and used the one
inside the Vm.
Some error throwing scenarios denoting programming
errors were transformed into expects.
- removed `guest_mem` field from VMM since it was a duplicate of vmm.vm.guest_mem
- transformed some error throwing scenarios into expects
- adjusted unit tests
doc changes are included in this PR. Docs in scope are all …
> vmm: remove duplicated field from VMM

- vmm/src/lib.rs
Remove superfluous vcpu count variable.
We can use the length of the vcpus variable
to get the count of vcpus. This way we also
discarding unused variables for x86_64.
> vmm: remove superfluous vcpu count

- tests/README.md
- tests/conftest.py
Add the env variable KEEP_TEST_SESSION to keep the created test session
files tree at the end of a test. This allow re-launching tests on a
previous test session without rebuilding all binaries.
conftest.py and integration tests README.
this PR have user impact and have been added to the …
> tests: add env variable to keep test session

- api_server/src/lib.rs
- api_server/src/parsed_request.rs
- tests/integration_tests/functional/test_logging.py
Fixes #1383 
Failing API requests would report their error message in the HTTP response, but not also log it.
Add the mechanism to also log the detailed error.
> API: log failed api requests

- CHANGELOG.md
- api_server/src/parsed_request.rs
- api_server/src/request/logger.rs
- logger/src/lib.rs
- vmm/src/lib.rs
- vmm/src/vmm_config/logger.rs
Change logger options type from Value to Vec<LogOption> for
strictly type checking, which would prevent potential unwrap
on None panics.
Signed-off-by: lifupan <lifupan@gmail.com>
Fix: #1375 
code is unavoidable and properly …
> fix: change logger options from Value to Vec<LogOption>     

- arch/src/aarch64/layout.rs
- arch/src/aarch64/mod.rs
- arch/src/aarch64/regs.rs
- arch/src/lib.rs
- arch/src/x86_64/layout.rs
- arch/src/x86_64/mod.rs
- arch/src/x86_64/mptable.rs
- arch/src/x86_64/regs.rs
- devices/src/virtio/block.rs
- devices/src/virtio/mmio.rs
- devices/src/virtio/net.rs
- devices/src/virtio/queue.rs
- devices/src/virtio/vsock/packet.rs
- kernel/src/loader/mod.rs
- memory_model/src/guest_address.rs
- memory_model/src/guest_memory.rs
- vmm/src/lib.rs
- vmm/src/vstate.rs
addresses #1397 
Use u64 as GuestAddress inner type. This is needed in order to make the switch to `rust-vmm/vm-memory` crate.
> use u64 as GuestAddress inner type

- src/jailer/src/chroot.rs
- src/jailer/src/env.rs
- src/utils/src/lib.rs
- src/utils/src/syscall.rs
Signed-off-by: Iulian Barbu <iul@amazon.com>
Fixes #1422 
Moved `SyscallReturnCode` struct and logic pertaining to this
struct from utils/src/lib.rs to utils/src/syscall.rs.
> Move SyscallReturnCode to utils/syscall.rs

- Cargo.lock
- src/arch/Cargo.toml
- src/arch/src/aarch64/gic.rs
- src/arch/src/aarch64/gicv2.rs
- src/arch/src/aarch64/gicv3.rs
- src/arch/src/aarch64/regs.rs
- src/arch/src/x86_64/interrupts.rs
- src/arch/src/x86_64/regs.rs
- src/cpuid/Cargo.toml
- src/cpuid/src/lib.rs
- src/cpuid/src/template/c3.rs
- src/cpuid/src/template/t2.rs
- src/cpuid/src/transformer/amd.rs
- src/cpuid/src/transformer/common.rs
- src/cpuid/src/transformer/mod.rs
- src/devices/src/legacy/rtc_pl031.rs
- src/kernel/src/loader/mod.rs
- src/utils/Cargo.toml
- src/vmm/Cargo.toml
- src/vmm/src/device_manager/mmio.rs
- src/vmm/src/error.rs
- src/vmm/src/lib.rs
- src/vmm/src/vmm_config/logger.rs
- src/vmm/src/vstate.rs
Fixes #1385 
Fixes #1386 
No reason to pin certain versions of the rust-vmm crates in our TOMLs.
We control the exact versions we build from using the Cargo.lock.
Unpinned version numbers for `kvm-bindings`, `kvm-ioctls` and `vmm-sys-util`.
Also updated the minimum version of `vmm-sys-util` to v0.2.1 to include the FAM wrappers safe clone fix.
Updated `kvm-ioctl` errors to work with `kvm_ioctl::Error` instead of `io::Error` directly.
Changed to use `CpuId` from `kvm-bindings` instead of `kvm-ioctls`.
Updated the usages of the `kvm-ioctls` that changed their interface.
Replaced MSRs `unsafe` code with the safe FAM wrapper over `kvm_msrs`.
`[Author TODO: Meet these criteria. …
> Update to kvm-bindings v0.2 and kvm-ioctls v0.4

- CHANGELOG.md
- src/devices/src/virtio/net.rs
- tests/integration_tests/build/test_coverage.py
Fixes #1439, #1436 .
- Raise interrupt after TX queue is processed. 
- Use edged triggered epoll for the tap fd.
This change will degrade performance as it increases the interrupt rate. It will also improve emulation thread cpu usage.
I've run some benchmarks on a m5d.metal host running a microvm with 2vCPUs and 2GB of RAM.
Without this PR:
- Guest RX, throughput: 13194.73 Mbps, retransmits: 106
- Guest TX, throughput: 18468.89 Mbps, retransmits: 0
With this PR:
- Guest RX, throughput: 12484.86 Mbps, retransmits: 102 **-6%**
- Guest TX, throughput: 17103.22 Mbps, retransmits: 0 **-8%**
`[Reviewer …
> Raise interrupt for used descriptors on tx queue and use edged triggered epoll.

- src/vmm/src/lib.rs
- src/vmm/src/vstate.rs
Fixes #1392 
Kicking the `Vcpu` out of `KVM_RUN` is done by making use of the kvm `immediate_exit` flag.
The vcpu is signaled and the `immediate_exit` flag is set in the signal handler. This leads to race-free interruption of KVM_RUN.
In order to access the `immediate_exit` flag for a particular vcpu from a global context such as the signal handler, we use the TLS of that vcpu thread to gain access to the vcpu's data.
This commit tries to keep the flow as safe as possible, and in that spirit, the following vcpu methods are defined:
- `init_thread_local_data(&mut self)` - associates the `self` vcpu to the current thread.
- `reset_thread_local_data(&mut self)` - deassociates the `self` vcpu from the current thread.
- `Vcpu::run_on_thread_local_vcpu<F>(fn: F)` - runs `fn` passing it a …
> vcpu: add support for kicking out of KVM_RUN

- CHANGELOG.md
- src/api_server/src/request/net.rs
- src/vmm/src/vmm_config/mod.rs
Invalid fields in PATCH requests should be failing properly with an error message, not silently. See #1437 for more information.
Added serde macro to the RateLimiterConfig.
> Ratelimiter API: Correctly return error for invalid fields in PUT/PATCH requests 

- CHANGELOG.md
- src/devices/src/virtio/queue.rs
- src/devices/src/virtio/vsock/epoll_handler.rs
- src/devices/src/virtio/vsock/mod.rs
- src/devices/src/virtio/vsock/packet.rs
- src/memory_model/src/guest_memory.rs
- tests/integration_tests/build/test_coverage.py
Fixed a logical error in bounds checking performed on vsock virtio descriptors. (CVE-2019-18960)
> Fix CVE-2019-18960

- src/utils/src/lib.rs
- src/utils/src/sm.rs
- src/vmm/src/default_syscalls/filters.rs
- src/vmm/src/error.rs
- src/vmm/src/lib.rs
- src/vmm/src/vstate.rs
- tests/integration_tests/build/test_coverage.py
Fixes #1391
Fixes #1393
Implemented a control interface through which the Vmm (or another controller component) can communicate in a request/response model with each Vcpu.
`Vcpu` exposes a `start_threaded()` function which will run the vcpu emulation on its own thread. The function returns a `VcpuHandle` which exposes a control interface to be able to send requests/events and receive responses from the owned vcpu thread.
Using the above, the control thread can now send commands/events to the vcpu threads.
Implemented support for `Pause`, `Resume` and `Exit` events. These effectively pause, resume, or respectively stop the microVM by pausing, unpausing or stopping the vcpu threads.
The vcpus are kicked out of KVM_RUN when the VMM thread needs to send them events.
**Note:** this builds on …
> Add support to control Vcpu

- README.md
- SPECIFICATION.md
- docs/api_requests/actions.md
- docs/api_requests/logger.md
- docs/api_requests/patch-network-interface.md
Path to swagger definition is broken by commit b6f46364eacf ("build: workspace cleanup").
Update to new path since commit b6f46364eacf ("build: workspace cleanup").
git grep -l -e api_server/swagger --and --not -e src/api_server/swagger \
| xargs sed -i 's:api_server/swagger:src/api_server/swagger:'
code is included in this PR.~~
reflected in `firecracker/swagger.yaml`.~~
this PR have user impact and have been added to the `CHANGELOG.md` …
> docs: update swagger path

- Cargo.lock
- src/devices/Cargo.toml
- src/devices/src/virtio/block.rs
- src/firecracker/Cargo.toml
- src/jailer/Cargo.toml
- src/jailer/src/cgroup.rs
- src/logger/Cargo.toml
- src/logger/src/lib.rs
- src/memory_model/Cargo.toml
- src/memory_model/src/mmap.rs
- src/utils/src/lib.rs
- src/utils/src/rand.rs
- src/utils/src/signal.rs
- src/utils/src/structs.rs
- src/utils/src/time.rs
- src/utils/src/validators.rs
- src/vmm/Cargo.toml
- src/vmm/src/default_syscalls/filters.rs
- src/vmm/src/lib.rs
- src/vmm/src/signal_handler.rs
- src/vmm/src/vmm_config/drive.rs
- src/vmm/src/vmm_config/logger.rs
- src/vmm/src/vstate.rs
- tests/integration_tests/build/test_coverage.py
Signed-off-by: Iulian Barbu <iul@amazon.com>
Fixes #1125 
Some of Firecracker crates have dev-dependency on `tempfile` crate from crates.io. This crate has other dependencies on its own that are brought into Firecracker as well.
Removed `tempfile` crate dev-dependency and used instead `vmm-sys-util` `tempfile module`, which basically replaces `tempfile` crate with a simpler implementation for temporary files & temporary directories, without additional dependencies.
doc changes are included in this PR. …
> Removed tempfile dependency

- src/arch/src/x86_64/mod.rs
- src/arch/src/x86_64/mptable.rs
- src/devices/src/virtio/block.rs
- src/devices/src/virtio/queue.rs
- src/memory_model/src/bytes.rs
- src/memory_model/src/guest_memory.rs
- src/memory_model/src/lib.rs
- src/memory_model/src/mmap.rs
- tests/integration_tests/build/test_coverage.py
#1396 
Rename DataInit trait to ByteValued. We need this in order to align with `rust-vmm/vm-memory`
> [memory_model] rename DataInit to ByteValued

- CHANGELOG.md
- docs/vsock.md
- src/devices/src/virtio/vsock/csm/connection.rs
- src/devices/src/virtio/vsock/csm/mod.rs
- src/devices/src/virtio/vsock/unix/muxer.rs
- tests/integration_tests/functional/test_vsock.py
#1432 #1253 #1443 
Changed the host-initiated vsock connection protocol to include a trivial handshake.
The new protocol looks like this:
- [host] `CONNECT <port><LF>`
- [guest/success] `OK <assigned_host_port><LF>`
On connection failure, the host connection is reset without any accompanying message, as before.
This allows host software to more easily detect connection failures, for instance when attempting to connect to a guest server that may have not yet started listening for client connections.
doc …
> VSock Connection Handshake

- CHANGELOG.md
- CREDITS.md
- Cargo.lock
- src/api_server/swagger/firecracker.yaml
- src/firecracker/Cargo.toml
- src/jailer/Cargo.toml
Firecracker release v0.20.0
```
- Added support for GICv2.
- Fixed a logical error in bounds checking performed on vsock virtio
descriptors (CVE-2019-18960).
- Fixed #1283 - Can't start a VM in AARCH64 with vcpus number more than 16.
- The backtrace are printed on `panic`, no longer causing a seccomp fault.
- Fixed #1375 - Change logger options type from Value to Vec<LogOption> to
prevent potential unwrap on None panics.
- Raise interrupt for TX queue used descriptors - Github issue #1436
- Fixed a bug that causes 100% cpu load when the net device rx is throttled
by the ratelimiter - Github issue #1439
- Invalid fields in rate limiter related API requests are now failing with
a proper error message.
- Fixed #1316 - fix the size of a virtio device, backed by a block device.
- Log failed …
```
> Firecracker release v0.20.0

- CHANGELOG.md
- docs/getting-started.md
#1469 
- Fixes issue were downloading broken links would later throw `Command Not Found` exceptions while running firecracker binary
- Updated binary links in [Getting Started](https://github.com/firecracker-microvm/firecracker/blob/master/docs/getting-started.md#getting-the-firecracker-binary) documentation to include system architecture via `uname -m`
> Fixed #1469: Broken link to firecracker binaries in getting started

- Cargo.lock
- src/api_server/Cargo.toml
- src/api_server/src/lib.rs
- src/firecracker/src/main.rs
- src/seccomp/src/lib.rs
- src/vmm/src/default_syscalls/mod.rs
- src/vmm/src/device_manager/mmio.rs
- src/vmm/src/lib.rs
- src/vmm/src/vstate.rs
- tests/integration_tests/build/test_coverage.py
Vmm only has a few predefined seccomp filters, however, in practice it might be useful to allow filters to be defined more dynamically. This PR allows the filters to be fully customized when creating the Vmm structure.
https://github.com/firecracker-microvm/firecracker/issues/1366
This commit aims to move the creation of seccomp filters closer to the CLI/API server and allows them to be defined before instantiating the Vmm.
located …
> Allow installing custom Seccomp Filters

- FAQ.md
Fixes: #1109
Document 'Resource busy' error cause and possible remedial in
FAQ documentation.
Signed-off-by: Abhijeet Kasurde <akasurde@redhat.com>
> FAQ: Document 'Resource busy' error in FAQ

- src/api_server/src/lib.rs
Turn unwrap into expect for a more friendly and
very frequently encountered exit message.
Failing to create a new HTTP server object (most frequently due to the fact that the api socket is already in use), would throw a message error of the kind:
```
Firecracker panicked at 'called `Result::unwrap()` on an `Err` value: IOError(Os { code: 98, kind: AddrInUse, message: "Address in use" })', src/libcore/result.rs:1165:5
```
With this change the message looks like this:
```
Firecracker panicked at 'Error creating the HTTP Server: IOError(Os { code: 98, kind: AddrInUse, message: "Address in use" })', src/libcore/result.rs:1165:5
```
Furthermore, this is more in the direction of what #593 tries to accomplish.
Use `expect("pretty message")` instead of …
> api_server: improve termination message

- src/jailer/src/env.rs
- src/jailer/src/main.rs
Signed-off-by: karthik nedunchezhiyan <karthik1705.n@gmail.com>
directory check for the chroot_dir missed in the jailer.
added directory check for the chroot_dir in jailer.
> jailer: enforce directory check for the chroot

- CHANGELOG.md
- docs/jailer.md
- docs/prod-host-setup.md
- src/jailer/src/env.rs
- src/jailer/src/main.rs
- tests/framework/jailer.py
`--seccomp-level` command line argument, if passed to jailer process, was only sent further to Firecracker. This was a leftover from when the jailer was setting the seccomp filters.
Remove `--secomp-level` from jailer parameters; now this argument should be specified after `--` (end of command options) in order to be forwarded to Firecracker process.
> Remove `--seccomp-level` argument from jailer parameters

- src/vmm/src/lib.rs
- src/vmm/src/vmm_config/mod.rs
Minor cleanup that makes rate limiter-related struct conversion slightly more idiomatic, by use of `Into` and `TryInto` traits
The `into_rate_limiter` and `into_token_bucker` converter functions were replaced with implementations of the `Into` and `TryInto` traits.
> rate limiters: convert Configs with *Into traits

- CHANGELOG.md
- Cargo.lock
- src/firecracker/Cargo.toml
- src/firecracker/src/main.rs
- src/jailer/Cargo.toml
- src/jailer/src/env.rs
- src/jailer/src/main.rs
- src/seccomp/src/lib.rs
- src/utils/src/arg_parser.rs
- src/utils/src/lib.rs
- src/vmm/src/default_syscalls/filters.rs
- src/vmm/src/default_syscalls/mod.rs
- src/vmm/src/lib.rs
- tests/integration_tests/build/test_binary_size.py
Signed-off-by: Laura Loghin <lauralg@amazon.com>
Get rid of `clap` crate dependencies and reduce this way the binary size.
Implements command line arguments parsing and validating and replaces `clap` crate functionality.
> Replace clap with our own args parser

- CHANGELOG.md
When https://github.com/firecracker-microvm/firecracker/pull/1246 was merged,
the changelog entry was added under 0.19.0. This seems like a mistake as 0.19.0
was already released.
Moves the changelog entry about initrd support into the "Unreleased" section.
> docs: initrd support is not released yet

- docs/rootfs-and-kernel-setup.md
Steps 1 and 2 listed in the documentation should use the same path
The documentation that shows how a root filesystem is built references the root filesystem image once as "/rootfs.ext4" and another time as "rootfs.ext4". 
If one is to follow these steps, there would be a file not found error thrown.
Since it makes more sense to have the filesystem built in the current working directory, this PR removes the extra "/" which is prepended in the first step
> docs: fix inconsistent reference to rootfs.ext4

- tests/framework/scheduler.py
CI could fail erroneously due to running multiple unit tests in parallel.
Marked the coverage integration test as concurrency-unsafe, so that it
doesn't get scheduled to run at the same time as test_unittests.
Currently the unit tests cannot be run in parallel, and computing the
coverage involves running all the unit tests.
> tests: solved unit/coverage conflict

- Cargo.lock
- src/arch/Cargo.toml
- src/arch/src/lib.rs
- src/arch/src/x86_64/interrupts.rs
- src/devices/Cargo.toml
- src/devices/src/legacy/rtc_pl031.rs
- src/devices/src/lib.rs
- src/devices/src/virtio/mmio.rs
- src/devices/src/virtio/vsock/device.rs
- src/devices/src/virtio/vsock/packet.rs
- src/dumbo/Cargo.toml
- src/dumbo/src/lib.rs
- src/dumbo/src/pdu/bytes.rs
- src/utils/src/byte_order.rs
- src/utils/src/lib.rs
The `device` and `dumbo` crates only have a few uses of the `byteorder` crate and all of them can be trivially replaced with functions from the standard library.
Fixes #1365 
This PR removes the `byteorder` dependency of the `device` and `dumbo` crates and improves the code that was using it. This also involved updating the tests to ensure complete removal of dependency on the `byteorder` crate. 
located either in the repository …
> Byteorder remove from device and dumbo crates

- CHANGELOG.md
- docs/jailer.md
- src/firecracker/src/main.rs
- src/jailer/src/env.rs
- src/jailer/src/main.rs
- tests/framework/jailer.py
Signed-off-by: karthik nedunchezhiyan <karthik1705.n@gmail.com>
`--api-sock` value was constant in jailer and not allowed to modify by the user.
Removed constant `--api-sock` from the jailer. Now user can pass `--api-sock` value as an extra argument (after --) to the jailer.
this PR have user impact …
> jailer: remove hardcoded api socket location

- src/devices/Cargo.toml
- src/devices/src/bus.rs
- src/devices/src/lib.rs
- src/devices/src/virtio/block.rs
- src/devices/src/virtio/block/device.rs
- src/devices/src/virtio/block/event_handler.rs
- src/devices/src/virtio/block/mod.rs
- src/devices/src/virtio/block/request.rs
- src/devices/src/virtio/device.rs
- src/devices/src/virtio/mmio.rs
- src/devices/src/virtio/mod.rs
- src/devices/src/virtio/net.rs
- src/devices/src/virtio/queue.rs
- src/devices/src/virtio/vsock/device.rs
- src/devices/src/virtio/vsock/mod.rs
- src/firecracker/Cargo.toml
- src/firecracker/src/api_server_adapter.rs
- src/firecracker/src/main.rs
- src/vmm/src/builder.rs
- src/vmm/src/controller.rs
- src/vmm/src/device_manager/mmio.rs
- src/vmm/src/lib.rs
- src/vmm/src/rpc_interface.rs
- tests/integration_tests/build/test_coverage.py
Implements #1428
**Please review the commits one by one if it helps while also keeping in mind that there are some leftovers from first commits that get cleared out in the last one as "Cosmetic changes".** 
**While reviewing this you will also find that I temporarly broke the promise of keeping the devices generic (dyn VirtioDevice) in some places like builder and controller. I will address these after we finish refactoring all the devices.**
This PR focuses mostly on refactoring the Block device but also touches Net, Vsock, MmioDevice and MmioDeviceManager.
Summary of changes:
- Merge BlockEpollHandler with Block and implement EventHandler for Block. Add a dummy implementation of EventHandler for Net and Vsock.
- Adds EventManager in VmmController and uses it Builder to register the …
> Refactor the Block device.

- tests/integration_tests/security/demo_seccomp/Cargo.lock
- tests/integration_tests/security/demo_seccomp/Cargo.toml
- tests/integration_tests/security/demo_seccomp/src/bin/seccomp_rules/mod.rs
This is a leftover of PR #1333 which removed hardcoded
syscall numbers only in development code and forgot
to update demo_seccomp module inside the integration tests.
* ran cargo update on demo_seccomp
* removed hardcoded stuff
> tests: leftover aarch64 hardcoded syscall

- src/arch/src/x86_64/mod.rs
- src/arch/src/x86_64/msr.rs
- src/arch/src/x86_64/regs.rs
- src/vmm/src/vstate.rs
Fixes #1388 
Created a new module with X86_64 MSRs related functionality.
Current included functionality:
- setting up MSRs for booting Linux,
- definition of MSRs whitelist and blacklist when considering saving virtual CPU state.
this PR have user impact and have been added to the `CHANGELOG.md` …
> arch/x86_64: add separate MSRs related module

- src/seccomp/src/lib.rs
This PR includes:
- Changed level representation of seccomp from u32 to u8.
- Some code and docs adjustments.
> seccomp: code and docs adjustments

- tests/framework/jailer.py
- tests/framework/microvm.py
- tests/integration_tests/functional/test_cmd_line_start.py
The `--` (extra-args) feature for propagating
jailer parameters to firecracker gets appended
only when config-file is specified.
Fixed this by implementing a forward looking approach
that enables us to even exercise our new implementation
of the arg parser.
The approach implemented mirrors the codebase. Added the extra-args parameter to the jailer (just like in the [codebase](https://github.com/firecracker-microvm/firecracker/blob/master/src/jailer/src/main.rs#L272)) that can be tweaked from inside the integration tests in any means possible for the sake of exercising valid as well as non-valid scenarios.
`[Reviewer TODO: Verify that these criteria are met. Request changes if …
> tests: fix broken parameter propagation

- Cargo.lock
- src/devices/src/virtio/block/event_handler.rs
- src/polly/Cargo.toml
- src/polly/src/epoll.rs
- src/polly/src/event_manager.rs
- src/polly/src/lib.rs
- src/polly/src/pollable.rs
Remove epoll crate dependency in order to reduce number of external dependencies.
Fixes #1259 
Implement our own epoll wrapper.
Add some renames and comments in polly.
Remove API channel functionality from polly crate.
> Implement epoll wrapper

- CHANGELOG.md
- docs/api_requests/actions.md
- docs/api_requests/patch-block.md
- src/api_server/src/lib.rs
- src/api_server/src/parsed_request.rs
- src/api_server/src/request/actions.rs
- src/api_server/swagger/firecracker.yaml
- src/devices/src/virtio/block.rs
- src/firecracker/src/main.rs
- src/vmm/src/error.rs
- src/vmm/src/lib.rs
- tests/integration_tests/functional/test_api.py
- tests/integration_tests/functional/test_drives.py
The RescanBlockDevice /actions API call is redundant, the same
functionality can be achieved using a PATCH /drives API call.
This resolves issue #1511  because through the latter call,
the `ndisk_sectors` field that is used in the processing of the disk's
transport requests is updated correctly.
- Remove the RescanBlockDevice API call and related tests.
- Update the docs to include an example of using the PATCH /drives call 
to rescan a block device.
- Remove duplicated warning code about disk_size not being a multiple of SECTOR_SIZE.
`[Reviewer TODO: Verify that these criteria are met. Request …
> Remove RescanBlockDevice from the /actions API

- Cargo.lock
- src/devices/Cargo.toml
- src/devices/src/bus.rs
- src/devices/src/legacy/mod.rs
- src/devices/src/legacy/serial.rs
- src/devices/src/lib.rs
- src/firecracker/Cargo.toml
- src/firecracker/src/api_server_adapter.rs
- src/firecracker/src/main.rs
- src/firecracker/src/metrics.rs
- src/polly/src/event_manager.rs
- src/vmm/Cargo.toml
- src/vmm/src/builder.rs
- src/vmm/src/controller.rs
- src/vmm/src/device_manager/legacy.rs
- src/vmm/src/device_manager/mmio.rs
- src/vmm/src/lib.rs
- tests/integration_tests/build/test_coverage.py
Another step in migrating Firecracker to the new `polly` event manager.
Fixes #1522 
Fixes #1523 
Both `LOGGER` and `METRICS` are Firecracker specific, not `Vmm` specific, and thus should not be tied to the `Vmm`.
Logger has already been taken out of `Vmm`, now take the metrics periodic logging logic out of the `Vmm` as well.
A `PeriodicMetrics` object is defined in the firecracker crate, which uses `EventManager` to drive periodic reporting of `METRICS`.
The serial device no longer has to be injected with input from some external component. It can now be created with any input object that is `dyn std::io::Read + std::os::unix::io::AsRawFd`.
Because the serial now implements the `EventHandler` trait, it can internally handle all input.
Removed the `EpollDispatch::Stdin` previously handled …
> Migrate Metrics and the Serial device to EventManager (polly)

- src/micro_http/src/common/headers.rs
HTTP header matching should be case-insensitive. In particular the `hyper` http client appears to use lower case headers which causes an `Empty Put Request` (b/c `content-length` header not found) error.
Do a case insensitive comparison.
this PR have user impact and have been added to the …
> micro_http: use case-insensitive match for header names

- src/arch/src/aarch64/fdt.rs
- src/arch/src/aarch64/mod.rs
- src/arch/src/x86_64/mod.rs
- src/devices/src/virtio/block.rs
- src/kernel/src/loader/mod.rs
- src/vm-memory/src/guest_memory.rs
`region_end` from `guest_memory.rs` is an orphan function which returns the end of a memory region exclusive. This behavior might be misleading for usage, and it also presents a possibility to overflow:
**BEFORE:** region_end = region.guest_base + region.mapping.size().
**NOW:** region_end -> last_addr = region.guest_base + region.mapping.size() - 1. 
Signed-off-by: Iulian Barbu <iul@amazon.com>
Linked to #1527.
Disambiguate the `region_end` function, applied on `MemoryRegion` , changing it to a method,
bound to `MemoryRegion` struct.
* Renamed GuestMemory `region_end` to `last_addr`.
* Modified the behaviour of the function.
**BEFORE**: The function returned the last address of
a region exclusive.
**NOW**: The function returns the last address of a region
inclusive.
* Changed the …
> Renamed `region_end` to `last_addr` in guest memory

- src/api_server/src/parsed_request.rs
- tests/integration_tests/functional/test_logging.py
The response from this function has content-type:application/json and
Swagger specifies that the JSON object must have "fault_message".
However the implementation was returning a plan string such as
"vCPUs resume failed." which broke clients.
Signed-off-by: Kazuyoshi Kato <katokazu@amazon.com>
The response from this function has content-type:application/json and
Swagger specifies that the JSON object must have "fault_message".
However the implementation was returning a plan string such as
"vCPUs resume failed." which broke clients.
It adds ApiServer::json_fault_message() to convert a string to a valid JSON document.
`[Author TODO: Meet these criteria. Where there are two …
> api_server: convert the VmmActionError to a JSON object

- src/arch/src/aarch64/fdt.rs
- src/arch/src/aarch64/mod.rs
- src/arch/src/x86_64/mod.rs
- src/arch/src/x86_64/mptable.rs
- src/arch/src/x86_64/regs.rs
- src/devices/src/virtio/queue.rs
- src/kernel/src/loader/mod.rs
- src/vm-memory/src/guest_memory.rs
- src/vm-memory/src/lib.rs
- src/vmm/src/lib.rs
- src/vmm/src/vstate.rs
addresses #1543 
We need this in order to align our interface to the `rust-vmm/vm-memory` interface. 
> [GuestMemory] import GuestMemoryRegion and GuestMemory traits from rust-vmm/vm-memory

- src/jailer/src/chroot.rs
- src/jailer/src/env.rs
- src/jailer/src/main.rs
- tests/framework/decorators.py
- tests/framework/defs.py
- tests/framework/jailer.py
- tests/integration_tests/security/test_jail.py
Fix for [regression](https://github.com/firecracker-microvm/firecracker/pull/1500/commits/1e5e6ac45fb0b4cdbadbf11d9355876f5a09089e).
When run only with the required parameter the  jailer would crash.
Fixes #1551.
* Added a new function which constructs the required folder hierarchy for firecracker to be able to run. Momentarily these are `dev`, `dev/net` and `run.` 
* The function also gives the necessary permissions.
* First two commits are nit's. The third one is the one fixing the regression.
* The 4th, 5th, 6th and 7th are integration tests related commits. …
> Fix regression in jailer

- src/firecracker/src/api_server_adapter.rs
- src/firecracker/src/main.rs
- src/polly/src/event_manager.rs
- src/vmm/src/builder.rs
- src/vmm/src/controller.rs
- src/vmm/src/device_manager/legacy.rs
- src/vmm/src/lib.rs
- src/vmm/src/rpc_interface.rs
- tests/integration_tests/build/test_coverage.py
Fixes #1524 
Fixes #1546 
The `Vmm` object registers its exit event to `EventManager` and provides a `handle_read` routine for it.
On EPOLLIN/read events, the `Vmm` will call its `stop()` routine and exit the process.
`Vmm::run_event_loop` becomes a static function since it no longer needs a `self: &Vmm`, this brings us one step closer to removing it altogether.
Since `Vmm` implements `EventHandler`, it now has to be wrapped in an `Arc<Mutex>`.
The RPC `PrebootApiController` now also has a method to drive itself all the way to the `Vmm` being built.
The same logic was previously in the `firecracker` crate, but through some refactoring, it's now generic enough to live in `rpc_interface.rs`.
The `ApiServerAdapter` registers itself to `EventManager` and dispatches runtime api messages to the …
> Migrate the Vmm-exit and Api events to EventManager (polly)

- tests/framework/microvm.py
- tests/framework/utils.py
- tests/integration_tests/build/test_licenses.py
Occasionally tests would fail due to the fact that the output of 'screen -ls' did not contain the screen session name.
Due to this issue, re.search() would return 'None', which would throw a generic exception.
Run 'screen -ls' in a busy waiting loop to wait for the given regular expression object. 
If the object is not found within the default time frame, raise an exception.
> tests: Run 'screen -ls' in a busy-waiting loop

- src/vmm/src/lib.rs
Starting 100 VMs on a EC2 m5d.metal host sometimes didn't work due to
the timeout.
Fixes #1555.
Changing the timeout from 100ms to 1000ms, as we discussed in #1555.
> vmm: relax resume_vcpus's timeout

- src/firecracker/src/main.rs
- src/jailer/src/env.rs
- src/jailer/src/main.rs
- src/utils/src/arg_parser.rs
Some renames and small changes in order to have in `arg_parser` file only
the functionality of a command line argument parser.
App struct was renamed ArgParser and app specific fields
were removed in order to keep in `arg_parser.rs` only the
functionality that is related to a command line argument
parser.
ArgInfo struct was renamed Argument because it contains
the `user_value` field which is not actually an info about
the argument.
> Fixes for the arg parser

- src/arch/src/aarch64/fdt.rs
- src/arch/src/aarch64/mod.rs
- src/arch/src/aarch64/regs.rs
- src/arch/src/x86_64/mod.rs
- src/arch/src/x86_64/mptable.rs
- src/arch/src/x86_64/regs.rs
- src/devices/src/virtio/block.rs
- src/devices/src/virtio/mmio.rs
- src/devices/src/virtio/net.rs
- src/devices/src/virtio/queue.rs
- src/devices/src/virtio/vsock/epoll_handler.rs
- src/devices/src/virtio/vsock/mod.rs
- src/kernel/src/loader/mod.rs
- src/vm-memory/src/guest_memory.rs
- src/vmm/src/device_manager/mmio.rs
- src/vmm/src/lib.rs
- src/vmm/src/vstate.rs
Part of #1400 
The PR https://github.com/rust-vmm/vm-memory/pull/70 has introduced some
changes in the rust-vmm/vm-memory crate. We have to keep our interface
aligned.
> [GuestMemoryMmap] rename new() to from_ranges()

- src/vmm/src/error.rs
- src/vmm/src/lib.rs
- src/vmm/src/vstate.rs
Before changing the way to stop vCPU threads (see #1586), we need to have a cleaner way to tell the exit signal.
The first change is adding exit_evt on aarch64, as #1456 proposed. The second change is getting rid of Option on the event FD.
this PR have user impact and have been added to the …
> Use exit_evt on aarch64

- tests/framework/scheduler.py
When running pytest in test discovery mode `pytest --co`, tests were being executed when they should have not.
When adding a custom hook on test discovery through pytest_runtestloop(), we should check whether pytest is running in test discovery mode or not, as implemented in pytest  https://github.com/pytest-dev/pytest/blob/master/src/_pytest/main.py#L278
> tests: Return when pytest is in discovery mode

- src/arch/src/x86_64/msr.rs
- src/vmm/src/error.rs
- src/vmm/src/lib.rs
- src/vmm/src/vstate.rs
- tests/integration_tests/build/test_coverage.py
Fixes #1389 and fixes #1390 
x86_64 support for saving and restoring `kvm vm` and `kvm vcpu` states.
> Add support for saving and resuming x86_64 vm and vcpu states

- src/devices/src/legacy/serial.rs
- src/devices/src/virtio/block/device.rs
- src/devices/src/virtio/block/event_handler.rs
- src/devices/src/virtio/net/device.rs
- src/devices/src/virtio/net/event_handler.rs
- src/devices/src/virtio/vsock/event_handler.rs
- src/devices/src/virtio/vsock/mod.rs
- src/devices/src/virtio/vsock/unix/muxer.rs
- src/firecracker/src/api_server_adapter.rs
- src/firecracker/src/metrics.rs
- src/polly/src/epoll.rs
- src/polly/src/event_manager.rs
- src/vmm/src/lib.rs
Fixes: #1536
Implemented Drop for Epoll and remove copy & clone from Epoll and copy from epoll_event.
Also use reference instead of copying the epoll & epoll_event.
> Event Manager Cleanup

- CHANGELOG.md
- src/vmm/src/lib.rs
- src/vmm/src/vstate.rs
- tests/integration_tests/build/test_coverage.py
fixes #1456 
Don't allow vCPU threads to exit. If they finished execution, they will signal the VMM to exit and then wait forever.
> Change vCPU threads exit behavior in order to avoid sigprocmask

- src/utils/src/sm.rs
- src/vmm/src/vstate.rs
Simplify the state machine by removing the `end_state` flag
Simplify the state machine by removing the `end_state` flag
> [StateMachine] replace end_state flag with Option

- tests/framework/scheduler.py
To build one generator to stop the iteration when the
matching batch in schedule found. And then yield the
batch item, to instead loop breaking statement.
This introduces a little more graceful mechanism to
set stopping condition for python generator.
Signed-off-by: keyangxie <keyang.xie@gmail.com>
To introduces a little more graceful mechanism for function `pytest_runtestloop`.
To build one generator to stop the iteration when the
matching batch in schedule found. And then yield the
batch item, to instead loop breaking statement.
`[Reviewer TODO: Verify that these criteria are met. Request changes …
> tests: refactor batch assignment mechanism

- src/devices/src/virtio/net/device.rs
- src/devices/src/virtio/queue.rs
- src/vmm/src/vmm_config/drive.rs
- src/vmm/src/vmm_config/net.rs
Having https://github.com/firecracker-microvm/firecracker/pull/1589 merged recently, we've introduced coverage which touched code paths uncovered through unit tests. This PR aims to resolve this situation. It comprises unit tests for few overlapping code paths, already covered by our current suite of unit tests.
Closes #1621.
Added remaining viritio device unit tests for `Net` device, unit tests for `NetworkInterfaceConfig` implementation and unit tests for `BlockDeviceConfig` implementation. 
> Unit tests in net and block configs

- CHANGELOG.md
- src/firecracker/src/main.rs
- src/jailer/src/main.rs
- src/utils/src/arg_parser.rs
#1632
Back-porting PR https://github.com/firecracker-microvm/firecracker/pull/1633 to `v0.21.1`
In new release Firecracker `v0.21.0`, the command line arg `--version` is missing.
```
$ ./firecracker-v0.21.0-x86_64 --version
2020-02-26T03:15:13.135125190 [anonymous-instance:ERROR:src/firecracker/src/main.rs:132] Arguments parsing error: Found argument 'version' which wasn't expected, or isn't valid in this context.
```
And the `--version` is quite an universal command line arg to print application version number.
clearly …
> Backport v0.21.1: Add flag `--version`

- CHANGELOG.md
- src/firecracker/src/main.rs
- src/jailer/src/main.rs
- src/utils/src/arg_parser.rs
#1632 
In new release Firecracker `v0.21.0`, the command line arg `--version` is missing.
```
$ ./firecracker-v0.21.0-x86_64 --version
2020-02-26T03:15:13.135125190 [anonymous-instance:ERROR:src/firecracker/src/main.rs:132] Arguments parsing error: Found argument 'version' which wasn't expected, or isn't valid in this context.
```
And the `--version` is quite an universal command line arg to print application version number.
located …
> Args: Add flag `--version`

- src/devices/src/virtio/block/device.rs
- src/devices/src/virtio/block/event_handler.rs
- src/devices/src/virtio/device.rs
- src/devices/src/virtio/mmio.rs
- src/devices/src/virtio/net/device.rs
- src/devices/src/virtio/vsock/device.rs
- src/vmm/src/device_manager/mmio.rs
- tests/integration_tests/build/test_coverage.py
Fixes #1620 
Some small changes to the VirtioDevice trait interface:
- The VirtioDevice trait can work with references instead of owned objects for Queues and QueueEvents so no cloning is necessary. Also use slice references instead of owned Vecs.
- For a short while we were also using `activate`/`reset` and `set_device_activated`. This moves all devices and tests to using `activate`/`reset` to activate, respectivelly reset a VirtioDevice.
> VirtioDevice trait cleanup

- src/devices/src/virtio/block/device.rs
- src/devices/src/virtio/mod.rs
- src/rate_limiter/src/lib.rs
- src/vmm/src/builder.rs
Signed-off-by: karthik nedunchezhiyan <karthik.n@zohocorp.com>
This PR has the following changes:
* block-device: replaced hardcoded value with `CONFIG_SPACE_SIZE`.
* virtio: removed redundant import statements.
* rate-limiter (nit): previously gcd took for `complete_refill_time_ms` and `NANOSEC_IN_ONE_MILLISEC` separately. current implementation provides the same result but this time with lesser code. I hope `complete_refill_time_ms * NANOSEC_IN_ONE_MILLISEC` should not cause overflow issue as it is `unsigned 64`. Overflow issues will happen if user provides a huge `complete_refill_time_ms` value for more than 580 years (I hope fc users will not have such use-case). 
* vmm-builder (nit): previously single logic is split into two parts (some outside the for loop and some inside the for …
> removed superfluous code

- src/kernel/src/cmdline/mod.rs
- src/vmm/src/resources.rs
- src/vmm/src/rpc_interface.rs
- src/vmm/src/vmm_config/boot_source.rs
- src/vmm/src/vmm_config/net.rs
- src/vmm/src/vstate.rs
- tests/integration_tests/build/test_coverage.py
Closes #1641 
Added unit tests for `VmResources` (vmm::resources.rs).
Note: `VmResources::from_json` is covered in [`Refactor logger`](https://github.com/firecracker-microvm/firecracker/pull/1614) PR.
> Added VmResources unit tests

- src/devices/src/legacy/i8042.rs
- src/vmm/src/lib.rs
- tests/host_tools/logging.py
- tests/integration_tests/functional/test_metrics.py
- tests/integration_tests/functional/test_shut_down.py
- tests/integration_tests/functional/test_signals.py
#1624
Updated `test_shut_down.py` to assert the flushing of metrics when a reboot is issued from within the booted microVM.
`mod tests` from vmm/lib.rs is not neccessary for this file, since the units testing fit better for integration tests, which are already covered by our current integration tests.
Modified the API for creation and flags manipulation of a `logging::Fifo`. These changes offer flexibility in choosing if the opened pipe is blocking or non blocking and support for changing file descriptor flags for the opened fifo.
`[Reviewer TODO: Verify that these criteria are met. Request changes …
> test_shut_down.py: assert reboot flushes metrics

- src/dumbo/src/pdu/arp.rs
- src/dumbo/src/tcp/endpoint.rs
- src/logger/src/lib.rs
- src/logger/src/logger.rs
- src/micro_http/src/common/headers.rs
- src/micro_http/src/request.rs
Some cfg(test) helper could very well been placed inside the `mod tests` section.
As per my investigation, there is no other helper that needs to be replaced. Fixes #605.
> clean-up: get rid of misplaced cfg(test)

- src/devices/src/virtio/block/device.rs
- src/jailer/src/cgroup.rs
- src/logger/src/metrics.rs
- src/vmm/src/builder.rs
- src/vmm/src/vmm_config/logger.rs
Previous version of tempfile from vmm_sys_util
did not offer the interface for owning the File inside
the TempFile. This limitation was solved by https://github.com/rust-vmm/vmm-sys-util/pull/70.
Adjusted all unit tests. Fixes #1466.
> tempfile: make use of into_file

- Cargo.lock
- src/micro_http/Cargo.toml
- src/micro_http/src/lib.rs
- src/micro_http/src/server.rs
- src/polly/src/event_manager.rs
- tests/integration_tests/functional/test_signals.py
Fixes #197 
Gracefully handle EINTR errors in our `EventManager` and `HttpServer` requests loops, they are internally consumed and treated as a `epoll` timeout with no events rather than io (fatal) errors.
The inner `vsock epoll` loop doesn't care about EINTR because it always runs non-blocking (with `timeout=0`) and also doesn't `break` on errors.
**Before**
```
kata@kata-devo:~/code/firecracker-demo$ sudo gdb -p `pidof firecracker`
Attaching to process 9345
[New LWP 9346]
[New LWP 9466]
0x000000000079a6a7 in epoll_pwait ()
warning: Missing auto-load script at offset 0 in section .debug_gdb_scripts
of file /home/kata/code/firecracker-demo/firecracker.
Use `info auto-load python-scripts [REGEXP]' to list them.
(gdb) c
Continuing.
Thread 1 "firecracker" received signal SIGSYS, Bad system …
```
> Gracefully handle EINTR events in our async loops

- docs/logger.md
- docs/metrics.md
Links in logger and metrics were broken.
Fix those links.
> Fix links in logger and metrics docs

- Cargo.lock
- src/arch/Cargo.toml
- src/devices/Cargo.toml
- src/devices/src/virtio/vsock/packet.rs
- src/kernel/Cargo.toml
- src/vmm/Cargo.toml
PArtially addresses #1683
- upgrade vm-memory dependency to 0.2.0
- simplify `get_host_address()`
> upgrade vm-memory dependency to 0.2.0

- src/seccomp/src/lib.rs
Since the enum SeccompLevel values are simple integers, it's safe and
convenient to be able to copy and clone its values. That's the reason
why this patch derives both Clone and Copy trait for the enum type
SeccompLevel.
Signed-off-by: Sebastien Boeuf <sebastien.boeuf@intel.com>
> seccomp: Allow to copy and clone SeccompLevel

- src/devices/src/virtio/block/device.rs
- src/devices/src/virtio/net/device.rs
- src/logger/src/metrics.rs
- tests/integration_tests/build/test_coverage.py
We've introduced an error log for the case when there is no available buffer for RX data. This can happen for heavy network traffic usage, and it is not an actual error, rather a limitation for which we must increment a metric.
Signed-off-by: iulianbarbu <iul@amazon.com>
Fixes #1677 
Removed an unnecessary error log.
> device.rs: increment metric instead of logging error

- src/devices/src/virtio/block/mod.rs
- src/vmm/src/builder.rs
- src/vmm/src/controller.rs
- src/vmm/src/device_manager/mmio.rs
- src/vmm/src/resources.rs
- src/vmm/src/vmm_config/drive.rs
- tests/integration_tests/build/test_coverage.py
Reduce code complexity.
Fixes #1711 
We were using two different functions each with its own way to get to the underlying block device and update its backing file, then update its virtio configuration space.
This commit drops the `rescan_block_device()` function and just updated the virtio configuration space in the `update_drive_disk_image()` function.
> vmm: simplify block device rescan

- src/snapshot/benches/basic.rs
- src/snapshot/src/lib.rs
- src/versionize/src/lib.rs
- src/versionize/src/primitives.rs
- src/versionize_derive/src/descriptors/struct_desc.rs
- src/versionize_derive/src/descriptors/union_desc.rs
- src/versionize_derive/src/fields/struct_field.rs
- src/versionize_derive/src/fields/union_field.rs
- src/versionize_derive/src/helpers.rs
- src/versionize_derive/src/lib.rs
Fixes #1718, #1707.
Described in commit message.
> Make Versionize and serde_bincode compatible and split Versionize/Snapshot errors.

- CHANGELOG.md
- src/api_server/swagger/firecracker.yaml
- src/vmm/src/resources.rs
- src/vmm/src/rpc_interface.rs
- tests/integration_tests/build/test_coverage.py
- tests/integration_tests/functional/test_api.py
Reduces code complexity.
Adds missing information to our API specification.
Fixes #1710 
The dedicated Block device PATCH/update that only updates the underlying backing file doesn't make sense pre-boot.
Before boot, users can simply PUT/create on `/drives/{id}` using an existing `id` to update any part of its configuration.
This PR removes pre-boot support for `UpdateBlockDevicePath` to reduce code complexity. It also removes `UpdateNetworkInterface` based on the same reasoning.
Since some API operations are only allowed pre-boot and some only post-boot, this PR adds description for API operations restrictions to our swagger API spec. …
> API/RPC: UpdateBlockDevicePath only allowed post-boot

- src/snapshot/src/lib.rs
- src/versionize_derive/src/descriptors/union_desc.rs
Fixes #1730
Replaced `std::mem::size_of::<#field_type>` with  `std::mem::size_of::<#field_type>()` in order to return the correct size of union fields.
> Fix field sizes vec for union (de)serialization

- src/devices/src/lib.rs
- src/devices/src/virtio/block/device.rs
- src/devices/src/virtio/block/event_handler.rs
- src/devices/src/virtio/device.rs
- src/devices/src/virtio/mmio.rs
- src/devices/src/virtio/net/device.rs
- src/devices/src/virtio/net/event_handler.rs
- src/devices/src/virtio/queue.rs
- src/devices/src/virtio/vsock/device.rs
- src/devices/src/virtio/vsock/event_handler.rs
- src/devices/src/virtio/vsock/mod.rs
- src/vmm/src/builder.rs
- src/vmm/src/device_manager/mmio.rs
- tests/integration_tests/build/test_coverage.py
Fixes #1639 
Passing memory during device activation instead of during construction enables the following story: #1702 #1708 #1709 and finally #1713
The changes in this PR are in line with the model currently defined in https://github.com/rust-vmm/vm-virtio.
They are also compatible with the https://github.com/rust-vmm/vm-virtio/pull/10 proposal where memory is also passed to the device during activation:
```rust
/// Associated guest memory
type M: GuestMemory;
...
/// Activates this device for real usage.
/// The ownership of the VirtioDeviceConfig object moves into the VirtioDevice object if
/// activate succeeds, otherwise it should return the ownership back.
fn activate(&mut self, config: VirtioDeviceConfig<M>) -> ActivateResult<VirtioDeviceConfig<M>>;
```
Postpone external events …
> Align device events registration after device activation

- CHANGELOG.md
- docs/devctr-image.md
This guide should simplify our lives when we need to update the development container with something, 
Documented the process of generating and pushing a new image for the development container.
Already there. https://github.com/rust-vmm/rust-vmm-container
> docs: guide for updating dev container image

- src/vmm/src/vstate.rs
- tests/integration_tests/build/test_coverage.py
Fixes #1625 
Vcpu threads started in tests stay around as zombies until the whole test process exits. This PR adds support to cleanly reap vcpu threads when tests finish.
In tests the main/vmm thread exits without `exit()`ing the whole process. All channels get closed on the other side while the Vcpu threads are still running.
Add a dedicated `cfg(test)` exit function that just does a clean finish without reporting back to the main/vmm thread.
> Clean up vcpu threads created by tests

- tests/integration_tests/functional/test_concurrency.py
- tests/integration_tests/performance/test_boottime.py
The integration tests exercising boot time when spawned
with multiple microVMs are irrelevant due to them happening
in an unoptimized environment and also due to spawning a
small number of microVMs. However, making sure that concurrent run of multiple
microVMs runs smoothly is still relevant. Added a separate integration test for that.
Removed test_multiple_microvm_boottime_no_network and test_multiple_microvm_boottime_with_network from test_boottime.
doc changes are included in this PR. Docs in scope are …
> CI: adjust test_multiple_microvm_boottime_* integration tests 

- src/devices/src/virtio/mmio.rs
- src/devices/src/virtio/net/device.rs
- src/utils/src/net/tap.rs
- src/vmm/src/builder.rs
- src/vmm/src/device_manager/mmio.rs
- src/vmm/src/resources.rs
- src/vmm/src/vmm_config/net.rs
- tests/integration_tests/functional/test_api.py
Fixes #1708 
Prerequisite for #1713 
Refactored the `insert()` function to remove duplicated code between the create and update cases. Also removed a couple of redundant getters.
Following the more decoupled design we can now create net devices on their configuration path, rather than saving a config and delaying creation to boot-time.
Such a model allows user-errors (like invalid resources or permissions) to be reported as part of the configuration step rather than later at attempted boot.
It would also remove the time window between configuration and boot where changes to the host system (creating Taps, changing permissions, etc) would cause microVM boot failures (race condition between validation and commitment of resources).
Such a model should also decrease code complexity and should …
> Create Net devices during configuration instead of boot-time

- src/devices/src/virtio/vsock/device.rs
- src/devices/src/virtio/vsock/mod.rs
- src/vmm/src/builder.rs
- src/vmm/src/resources.rs
- src/vmm/src/rpc_interface.rs
- src/vmm/src/vmm_config/boot_source.rs
- src/vmm/src/vmm_config/machine_config.rs
- src/vmm/src/vmm_config/metrics.rs
- src/vmm/src/vmm_config/vsock.rs
- tests/integration_tests/build/test_coverage.py
Fixes #1709 
Prerequisite for #1713 
Following the more decoupled design we can now create the `Vsock` device on its configuration path, rather than saving a config and delaying creation to boot-time.
Such a model allows user-errors (like invalid resources or permissions) to be reported as part of the configuration step rather than later at attempted boot.
It would also remove the time window between configuration and boot where changes to the host system (creating Sockets, changing permissions, etc) would cause microVM boot failures (race condition between validation and commitment of resources).
Such a model should also decrease code complexity and should provide better efficiency to the process of configuring and starting a microVM (no more moving configurations around in memory and …
> Create Vsock device during configuration instead of boot-time

- src/devices/src/virtio/block/device.rs
- src/vmm/src/builder.rs
- src/vmm/src/controller.rs
- src/vmm/src/device_manager/mmio.rs
- src/vmm/src/resources.rs
- src/vmm/src/vmm_config/drive.rs
- tests/integration_tests/build/test_coverage.py
Fixes #1702 
Prerequisite for #1713 
Following the more decoupled design we can now create `block` devices on their configuration path, rather than saving a config and delaying creation to boot-time.
Such a model allows user-errors (like invalid resources or permissions) to be reported as part of the configuration step rather than later at attempted boot.
It would also remove the time window between configuration and boot where changes to the host system (deleting backing files, changing permissions, etc) would cause microVM boot failures (race condition between validation and commitment of resources).
Such a model should also decrease code complexity and should provide better efficiency to the process of configuring and starting a microVM (no more moving configurations around in memory …
> Create Block devices during configuration instead of boot-time

- src/devices/src/virtio/vsock/unix/muxer.rs
Occasionally, the vsock tests fail because the created file descriptors already exist. This PR tries to avoid that situation by trying multiple file names.
This can also happen when concurrent firecracker test runs are executed from the same path.
When a file is created, first, check if it exists. If it does, try to append a number to the file name.
> vsock: Use TempFile when generating file names

- FAQ.md
- docs/rootfs-and-kernel-setup.md
Recommended kernel configuration links in the docs are pointing to an
incorrect location after recent file rename.
Signed-off-by: Fraser Pringle <fraser.pringle@gmail.com>
Fixes:  #1766   
Correct the documentation links to the recommended kernel configuration.
> docs: Fix link to kernel configuration.

- tests/conftest.py
- tests/framework/jailer.py
- tests/framework/microvm.py
- tests/framework/utils.py
- tests/host_tools/cargo_build.py
- tests/host_tools/drive.py
- tests/host_tools/memory.py
- tests/host_tools/network.py
- tests/integration_tests/build/test_coverage.py
- tests/integration_tests/build/test_style.py
- tests/integration_tests/functional/test_cpu_features.py
- tests/integration_tests/functional/test_drives.py
- tests/integration_tests/functional/test_max_vcpus.py
- tests/integration_tests/functional/test_mmds.py
- tests/integration_tests/functional/test_rate_limiter.py
- tests/integration_tests/functional/test_shut_down.py
- tests/integration_tests/functional/test_signals.py
- tests/integration_tests/security/test_sec_audit.py
- tests/integration_tests/security/test_seccomp.py
Since subprocess.run is widely used in the testing framework, we should route all calls through a custom function which logs all the commands.
This is useful for both developing tests and debugging failures.
Add a custom shell call endpoint that logs all commands.
> tests: Log all commands through custom endpoint

- Cargo.lock
- src/rate_limiter/Cargo.toml
- src/rate_limiter/src/lib.rs
- src/rate_limiter/src/persist.rs
Being able to serialize the RateLimiter is a requirement for serializing the Block (#1424) and Net (#1425) devices.
Implemented the Persist trait for the RateLimiter and the TokenBucket structs and derived the Versionize trait for them.
> Implement serialization for RateLimiter

- Cargo.lock
- src/devices/Cargo.toml
- src/devices/src/lib.rs
- src/devices/src/virtio/block/device.rs
- src/devices/src/virtio/block/mod.rs
- src/devices/src/virtio/block/persist.rs
- src/devices/src/virtio/device.rs
- src/devices/src/virtio/mmio.rs
- src/devices/src/virtio/mod.rs
- src/devices/src/virtio/net/device.rs
- src/devices/src/virtio/persist.rs
- src/devices/src/virtio/queue.rs
- src/devices/src/virtio/vsock/device.rs
- src/versionize/Cargo.toml
- src/versionize/src/lib.rs
- src/vmm/src/builder.rs
- src/vmm/src/device_manager/mmio.rs
- src/vmm/src/resources.rs
- src/vmm/src/vmm_config/drive.rs
- tests/integration_tests/build/test_coverage.py
Fixes #1424
- Introduce a VirtioDeviceState that captures the generic Virtio fields that all devices have
- Implement the Persist trait for the block device in order to be able to save/restore it
- Derive Versionize for the BlockState
> Implement (de)serialization for block devices

- src/snapshot/src/lib.rs
- src/snapshot/tests/test.rs
- src/versionize/src/primitives.rs
- src/versionize/tests/test.rs
Fixes #1699 
Added tests that check representation compatibility across versions. These tests are placed in `snapshot/tests/test.rs` and `versionize/tests/test.rs` and, to make the review easier, the preexisting tests from snapshot and versionize crates are still in the same place. Once the review is done, I will move all the tests in the corresponding `test.rs`s if it's okay for everyone.
> Add tests for hardcoded snapshot deserialization

- src/jailer/src/main.rs
#1804 
Change function used from `as_raw_fd` to `into_raw_fd` to ensure 100 fd's are created and held open for the sanitize_process function to close. 
> jailer: fix test for sanitize_process

- src/versionize/tests/test.rs
- src/versionize_derive/src/fields/struct_field.rs
- src/versionize_derive/src/fields/union_field.rs
Fixes #1810
Support constants as sizes for arrays when generating deserializers.
> Versionize arrays where the size is a constant

- CHANGELOG.md
- docs/mmds.md
- src/api_server/src/parsed_request.rs
- src/api_server/src/request/mmds.rs
- src/dumbo/src/ns.rs
- src/utils/src/net/ipv4addr.rs
- src/utils/src/net/mod.rs
- src/vmm/src/resources.rs
- src/vmm/src/rpc_interface.rs
- src/vmm/src/vmm_config/mmds.rs
- tests/integration_tests/build/test_coverage.py
- tests/integration_tests/functional/test_mmds.py
MMDS configuration `ipv4_address` field must be a valid link-local IPv4 address.
Added a link-local check for the IPv4 address which comes with MMDS configuration, returning an error if the provided IPv4 address is not link-local.
> mmds: IPv4 address link-local check at config time

- src/devices/src/virtio/block/device.rs
- src/devices/src/virtio/block/mod.rs
- src/devices/src/virtio/block/persist.rs
- src/devices/src/virtio/device.rs
- src/devices/src/virtio/mmio.rs
- src/devices/src/virtio/net/device.rs
- src/devices/src/virtio/persist.rs
- src/devices/src/virtio/vsock/mod.rs
- src/devices/src/virtio/vsock/persist.rs
Fixes #1714 
Defines `MmioTransportState` and implements (de)serialization for `MmioTransport` primitives.
Creates (de)serialization framework and and hooks in the `Block` and `Vsock` devices (de)serialization to the `MmioTransport` devices that hold block or vsock devices. This allows (de)serialization of the inner device state along with `MmioTransport` primitives.
> Support (de)ser for MmioTransport

- Cargo.lock
- src/devices/src/virtio/net/device.rs
- src/devices/src/virtio/net/mod.rs
- src/devices/src/virtio/net/persist.rs
- src/dumbo/Cargo.toml
- src/dumbo/src/lib.rs
- src/dumbo/src/ns.rs
- src/dumbo/src/persist.rs
- src/dumbo/src/tcp/handler.rs
- src/vmm/src/resources.rs
- src/vmm/src/vmm_config/net.rs
- tests/integration_tests/build/test_coverage.py
- tests/integration_tests/functional/test_api.py
Fixes #1425 
- The Net device constructor receives the Tap interface name and opens it. This is similar to how the Block device handles the disk file.
- Implement the Persist trait for the Net device in order to be able to save/restore it.
- Derive Versionize for the NetState.
> Implement (de)serialization for net devices

- CHANGELOG.md
- docs/mmds.md
- src/api_server/src/lib.rs
- src/micro_http/src/common/headers.rs
- src/mmds/src/data_store.rs
- src/mmds/src/lib.rs
- src/vmm/src/builder.rs
- src/vmm/src/resources.rs
- tests/integration_tests/functional/test_mmds.py
Closes #1775. 
This PR adds full JSON support for MMDS, on both storage and retrieving metadata.
JSON response format is activated if an `Accept: application/json` header is present
in the MMDS request. Added relevant documentation in `mmds.md`. Further detailed documentation
is provided in #1800.
IMDS format response is kept intact.
> MMDS JSON response support

- src/cpuid/src/transformer/amd.rs
- src/cpuid/src/transformer/common.rs
- src/cpuid/src/transformer/intel.rs
- src/cpuid/src/transformer/mod.rs
- tests/integration_tests/build/test_coverage.py
Solve issue #1705 
Set the mod block to `mod tests` instead of `mod test` in the `cpuid` crate. This will make the test code in `cpuid` crate get excluded by kcov. If it's not excluded kcov counts the test code as code and then the test coverage result gets messed up.
> Fix unit test coverage for the cpuid crate

- src/dumbo/src/pdu/tcp.rs
- src/dumbo/src/tcp/connection.rs
- src/dumbo/src/tcp/endpoint.rs
- tests/integration_tests/build/test_coverage.py
- tests/integration_tests/functional/test_mmds.py
#1836 
Using the Ethernet/IP/TCP stack for sending TCP payloads larger than MSS (Maximum Segment Size) established at connection handshake results in incorrect payload at the receiving endpoint.
This PR adds support for accounting of TCP payloads larger than MSS, sent with multiple segments.
Signed-off-by: Iulian Barbu <iul@amazon.com>
> dumbo: add support for TCP payloads larger than MSS

- CHANGELOG.md
- src/micro_http/src/common/mod.rs
- src/micro_http/src/response.rs
- src/mmds/src/lib.rs
- tests/integration_tests/build/test_coverage.py
#1819
Add a validation check to enforce MMDS HTTP requests to use only `GET`.
Documentation about MMDS guest requests failures can be found in #1800 .
> MMDS HTTP method check for guest requests

- src/devices/src/virtio/block/persist.rs
- src/devices/src/virtio/net/persist.rs
- src/devices/src/virtio/persist.rs
- src/devices/src/virtio/vsock/persist.rs
- src/vmm/src/builder.rs
- src/vmm/src/device_manager/mmio.rs
- src/vmm/src/lib.rs
- src/vmm/src/persist.rs
- src/vmm/src/vstate.rs
- tests/integration_tests/build/test_coverage.py
Part of #1779
This PR is the first step towards saving/restoring the full Firecracker microVM.
It defines the MicrovmState structure and introduces functionality for saving the mmio device states.
> Add MicroVMState structure

- src/vmm/src/builder.rs
- src/vmm/src/device_manager/mmio.rs
- src/vmm/src/lib.rs
- src/vmm/src/vstate.rs
- tests/host_tools/cargo_build.py
Treat build errors as warnings.
Changed cargo/config.
**Obs** Tests are expected to fail until #1693 gets merged.
> cargo/config: disallow build warnings

- src/devices/src/virtio/net/device.rs
- src/devices/src/virtio/net/persist.rs
Fixes #1856 
Update the Mac address whenever there is a write to the config space.
This way, we update the spoofing metric for both cases: guest MAC provided by the user or
by the guest driver.
> Fix MAC spoofing metric

- src/vmm/tests/integration_tests.rs
- src/vmm/tests/mock_resources/mod.rs
- src/vmm/tests/mock_seccomp/mod.rs
- src/vmm/tests/test_utils/mod.rs
- tests/integration_tests/build/test_coverage.py
#1834 
* the tests that run a vmm now `fork`. The vmm itself runs in the child process and terminates either with `vmm.stop()` (exit code 0) or `libc::exit(errcode)` in case of panic. The parent waits on the vmm process and asserts on its exit status.
* signal handling doesn't work under `kcov` => changed the default action in the test seccomp filter to `Kill` instead of `Trap`. `Trap`ping doesn't work either under `kcov` (!!) and, now that the vmm runs in a forked child, we can assert on its `SIGSYS`-marked exit code.
> vmm: fix rust integration tests

- docs/benchmarks/state-serialize.md
- src/snapshot/benches/basic.rs
This PR is publishing basic synthetic state serialization benchmarks. As snapshot functionality becomes available we will publish the a full breakdown of microvm save/restore for various configurations:
- state serialization/deserialization
- kvm state save/restore
- device save/restore
- overall save/restore latency.
In commit messages.
> Add micrvom state serialization benchmark report.

- src/api_server/swagger/firecracker.yaml
- src/vmm/src/lib.rs
- src/vmm/src/rpc_interface.rs
- src/vmm/src/vstate.rs
- src/vmm/tests/integration_tests.rs
- tests/framework/microvm.py
- tests/framework/resources.py
- tests/integration_tests/functional/test_pause_resume.py
Fixes #1845
Implement pause/resume for microvm.
> vmm: implement Pause and Resume

- src/vmm/src/builder.rs
- src/vmm/src/device_manager/legacy.rs
- src/vmm/src/device_manager/mmio.rs
- src/vmm/src/lib.rs
- src/vmm/src/persist.rs
- src/vmm/src/vstate.rs
- tests/integration_tests/build/test_coverage.py
Prerequisite for #1847 
Rearranges vmm creation code to differentiate between creating resources and configuring them for boot.
This is a prerequisite for building from snapshot in order to share logic between the two paths.
**Note**: should be much easier to review going one commit at a time.
> Prepare vmm/builder for building from snapshot

- src/devices/src/virtio/block/persist.rs
- src/devices/src/virtio/net/persist.rs
- src/devices/src/virtio/persist.rs
- src/devices/src/virtio/vsock/persist.rs
- src/dumbo/src/persist.rs
- src/rate_limiter/src/persist.rs
- src/snapshot/src/persist.rs
- src/vmm/src/builder.rs
- src/vmm/src/device_manager/mmio.rs
- src/vmm/src/device_manager/mod.rs
- src/vmm/src/device_manager/persist.rs
- src/vmm/src/lib.rs
- src/vmm/src/persist.rs
- src/vmm/src/vmm_config/vsock.rs
Part of #1847 
Move device map crawling and serialization from Vmm to the device manager.
The device manager implements 'save()' which creates the previously defined 'DeviceStates' containing the devices' states plus mmio bus and irq attributes.
The device manager implements 'restore()' which takes a 'DeviceStates' structure, restores the devices and registers them using the original mmio bus and irq settings.
Ideally the device-manager would be device implementation agnostic, but Persist and Versionize don't allow dynamic dispatch.
The current organization of serialized data does however allow such a design, so the present state is a two-way-door and if in the future we invest here, we might be able to get the implementation there with no disruption to the user.
By submitting this pull …
> (de)serialiaze devices through device manager

- CHANGELOG.md
- src/jailer/src/env.rs
- src/jailer/src/main.rs
- tests/integration_tests/build/test_coverage.py
- tests/integration_tests/security/test_jail.py
#1802  
The jailer enforces `0o755` (`rwx|r_x|r_x`)  permissions on the jail folder hierarchy, to make sure that the de-privileged firecracker can always access device nodes.
rust-vmm doesn't have a jailing crate yet.
> jailer: ensure correct permissions on folders inside jail

- tests/integration_tests/build/test_style.py
Fixes #1322 
Updated comment to match reason for which we are not running `rustfmt` on `aarch64`
> tests: enough to run rustfmt on single arch

- src/api_server/src/parsed_request.rs
- src/api_server/src/request/snapshot.rs
- src/api_server/swagger/firecracker.yaml
- src/vmm/src/persist.rs
- src/vmm/src/version_map.rs
- src/vmm/src/vmm_config/snapshot.rs
- src/vmm/tests/integration_tests.rs
Fixes #1893 
Parsing the target version from the PUT /snapshot/create API call
params as a string allows for 1:1 mapping with the Firecracker version
that can be seen with the `./firecracker --version` command.
- modify the type of the `version` field from `CreateSnapshotParams` from `Option<u16>` to `Option<String>`
>  Use string for target version in CreateSnapshot API call

- docs/mmds/mmds-design.md
#1336 investigation reached the conclusion that there is no limitation in terms of MMDS  request size.
Trying to store MMDS payloads larger than 256KiB is possible due to
whitelisting of `mremap` syscall. Updated the MMDS documentation
related to this limitation.
> docs: mmds: remove mmds payload limitation

- src/firecracker/src/main.rs
- src/utils/src/arg_parser.rs
- tests/integration_tests/build/test_coverage.py
Signed-off-by: Shion Yamashita <shioyama1118@gmail.com>
Fix: #1688
Improve the following in `--help` content
- Display default values along with the description
- Segregate required and optional arguments
- Sort and align arguments
```
Jailer v0.21.0
required arguments:
--exec-file <exec-file>   File path to exec into.
--gid <gid>               The group identifier the jailer switches to after exec.
--id <id>                 Jail ID.
--node <node>             NUMA node to assign this microVM to.
--uid <uid>               The user identifier the jailer switches to after exec.
optional arguments:
--chroot-base-dir <chroot-base-dir>   The base folder where chroot jails are located. [default: "/srv/jailer"]
--daemonize                           Daemonize the jailer before exec, by invoking …
```
> Improve `--help` content in both firecracker and jailer

- tests/conftest.py
- tests/framework/artifacts.py
- tests/framework/builder.py
- tests/framework/matrix.py
- tests/integration_tests/functional/test_pause_resume.py
Fixes #1849.
Adds the flexibility required to generate a test matrix for save/restore tests using multiple snapshot images and firecracker binaries.
This PR introduces a new way for spinning up microvms in integration tests. Firstly, it does not rely on the hidden logic of fixtures to create and configure the microvms. Secondly, it defines a decoupled view of test resources, machine configurations, microvm configuration and implements  simple APIs that manage these. And thirdly, it allows a single test function to be run multiple times in a different setup (machine, disks, kernels, snapshots).
Layers and components:
- Resources layer components: **ArtifactCollection**, **Artifact**, **ArtifactSet**, **MicrovmBuilder**
- Test layer components: **TestContext**, **TestMatrix**
The resources …
> Add some infrastructure for snapshot integration test.

- Cargo.lock
- src/utils/Cargo.toml
- src/utils/src/net/tap.rs
Fixes  #1769. 
Remove the dependency of crate `utils` on crate `dumbo`. Dubmo was used to test sending IPv4 packets on the Tap interface. This refactor is for better testing for `utils` crate. Since now if the tests fail they only refer to problems in `utils` crate and not in `dumbo`.
*  Change `test_write` to write raw IPV4 UDP packet with a constant payload and assert that the same payload was received on the other end.
* Change `test_write` to parse the ARP request and respond without needing `dumbo`. And validating the payload read from the TAP device.
> Remove dependency of `utils` crate on `dumbo` crate

- src/devices/src/legacy/serial.rs
- src/devices/src/virtio/block/event_handler.rs
- src/devices/src/virtio/net/device.rs
- src/devices/src/virtio/net/event_handler.rs
- src/devices/src/virtio/vsock/event_handler.rs
- src/vmm/src/device_manager/persist.rs
- tests/integration_tests/build/test_coverage.py
Part of #1847 
Small reworking of devices event registering logic. Devices now own reporting their `interest-list` depending on their `activate` state. The mechanism to register events now becomes context independent and can be used and is used when restoring devices from snapshot.
> Reregister devices with event-manager on restore

- tests/conftest.py
- tests/integration_tests/build/test_style.py
- tests/integration_tests/functional/test_initrd.py
- tests/integration_tests/functional/test_serial_io.py
The latest pylint version throws a few new styling errors as mentioned in #1913 
This PR fixes those errors.
Fix styling errors.
The `import-error` error was added to the ignore list, because the import paths are implicitly verified when the tests are executed.
> tests: Fix pylint 2.5.2 errors

- src/micro_http/src/server.rs
Signed-off-by: Shion Yamashita <shioyama1118@gmail.com>
Fix #1803
Updated the tests for `micro_http` to use `TempFile` from `vmm-sys-util` to cleanup sockets.
> Use TempFile when generating path to socket

- tests/integration_tests/build/test_coverage.py
The cpuid crate introduces a slight
difference in the coverage value.
> CI: adjust coverage on AMD

- tools/devtool
Add a new parameter to devtool that fixes
permissions for the build directory (the one that can
get modified by the container).
This way unprivileged users can regain rights
(i.e delete build session) when devtool dies in
the middle of a privileged session.
> devtool: support for new parameter

- src/devices/src/virtio/block/device.rs
- src/devices/src/virtio/net/device.rs
- tests/conftest.py
- tests/framework/microvm.py
- tests/host_tools/change_net_config_space.c
- tests/host_tools/network.py
- tests/integration_tests/functional/test_metrics.py
- tests/integration_tests/functional/test_net_config_space.py
Fixes: #1822.
Support partial writes to network & block devices config space.
- ~~[ ] Any newly added `unsafe` code is properly documented~~.
- ~~[ ] Any API changes are reflected in `firecracker/swagger.yaml`~~.
- ~~[ ] Any user-facing changes are mentioned in `CHANGELOG.md`~~.
> devices: support partial config space write

- src/api_server/src/lib.rs
- src/micro_http/src/server.rs
- src/vmm/src/builder.rs
- src/vmm/src/device_manager/persist.rs
- src/vmm/src/persist.rs
- src/vmm/src/resources.rs
- src/vmm/src/vmm_config/vsock.rs
Fix #1803
- Renamed helper function for tests as mentioned in #1922
- Use `TempFile` in `src/api_server/src/lib.rs::test_bind_and_run()`
- Remove `src/vmm/src/vmm_config/vsock.rs::TempSockFile`
> Use TempFile from vmm-sys-utils to cleanup test files

- src/api_server/src/lib.rs
- src/api_server/src/parsed_request.rs
- src/api_server/src/request/actions.rs
- src/api_server/src/request/boot_source.rs
- src/api_server/src/request/drive.rs
- src/api_server/src/request/instance_info.rs
- src/api_server/src/request/logger.rs
- src/api_server/src/request/machine_configuration.rs
- src/api_server/src/request/metrics.rs
- src/api_server/src/request/mmds.rs
- src/api_server/src/request/mod.rs
- src/api_server/src/request/net.rs
- src/api_server/src/request/snapshot.rs
- src/api_server/src/request/vsock.rs
Fixes #1142 
Box `VmmAction` in `ParsedRequest::Sync` to keep enum variants around the same size.
> api_server: normalize ParsedRequest enum size

- src/devices/src/virtio/block/device.rs
- src/devices/src/virtio/net/device.rs
- src/rate_limiter/src/lib.rs
- src/rate_limiter/src/persist.rs
- src/vmm/src/rpc_interface.rs
- src/vmm/src/vmm_config/mod.rs
- src/vmm/src/vmm_config/net.rs
- tests/integration_tests/build/test_coverage.py
- tests/integration_tests/functional/test_rate_limiter.py
Fixes #1918 
TokenBucket constructor now validates input and provides 'None' result meaning disabled when its 'size' or 'refill_time' are zero.
Simplify and slightly optimize code by changing 'one_time_burst' from 'Option<u64>' to simple 'u64'. Value of zero is equivalent to 'None'.
> rate-limiter: remove code-paths that divide by zero

- tests/host_tools/proc.py
- tests/integration_tests/build/test_coverage.py
AMD CI would intermittently fail while checking against expected coverage.
Read value of processor model from `/proc/cpuinfo` rather than relying on python's "platform.processor()" function.
> CI: fix bug in getting AMD's coverage

- Cargo.lock
- src/firecracker/Cargo.toml
- src/firecracker/src/main.rs
- tests/host_tools/cargo_build.py
- tests/integration_tests/build/test_binary_size.py
- tests/integration_tests/build/test_unittests.py
- tools/devctr/Dockerfile.aarch64
- tools/devctr/Dockerfile.x86_64
- tools/devtool
We've decided  to completely remove `backtrace` dependency because of the following reasons:
- the backtrace wasn't useful for us (Firecracker team) in the debugging process :(,
- requires `musl-gcc` to be installed (`musl-tools`),
- prints the stack only in `--release` mode,
- caused us some troubles; see: #1088 for details -> forces us to whitelist some syscalls, which we are trying to avoid as much as possible.
We are curious if someone from the community was actually helped by our backtrace or if someone has an idea of how can we improve the generated backtrace. Any feedback would be greatly appreciated :blush:.
As an example, for the following panic message:
```
2020-04-28T14:01:47.106739566 [anonymous-instance:ERROR:src/firecracker/src/main.rs:67] Firecracker panicked at 'Error …
```
> Remove backtrace dependency

- Cargo.lock
Related to: https://github.com/rust-vmm/vm-memory/issues/93
In rust-vmm/vm-memory 0.2.0, the functions read_obj and write_obj
are not doing atomic accesses for all combinations of platform and
libc implementations. This is caused by everything being written
at a one byte granularity. The reads and writes eventually translate
to memcpy, which in some cases are not optimized to write at a higher
granularity. Since accesses are not guaranteed to be atomic, using
vm-memory in the virtio implementation causes undefined behavior
because the requirement of 2-byte aligned accesses of descriptor
indexes cannot be fulfilled.
The patch that fixes this issue is included in the 0.2.1 vm-memory
update.
There were no Firecracker releases after 2020-03-03; all existing
releases, including those used by …
> update to vm-memory 0.2.1

- docs/getting-started.md
- tools/devtool
The script in the getting started guide supposed to let to know the user whether firecracker would run on their machine or not, is broken when checking the kernel version when using Zsh.
Fixed the arithmetic and evaluation expression.
> Fix script checking firecracker requirements

- src/jailer/src/env.rs
- tests/integration_tests/build/test_coverage.py
#1688
#1688, with the following additions:
* documented `--start-time-us` and `--start-time-cpu-us`, fixed `start-time-cpu-us` typo
* one unit test for jailed (#363) to counter imprecise kcov results preventing coverage test to pass
* the most relevant issue for this behavior I've found is https://github.com/rust-lang/rust/issues/55352
...and with the exception for:
>Segregate mandatory and optional arguments properly.
See https://github.com/firecracker-microvm/firecracker/issues/1688#issuecomment-623550854.
> Improve command-line arguments

- tests/framework/utils.py
Fix typo inside utils.py: ```stdin``` instead of ```stdout``` and ```stdout``` instead of ```stderr```
Fix small typo inside utils.py
> test: fix typo in utils.py

- src/jailer/src/env.rs
- src/jailer/src/main.rs
- tests/integration_tests/build/test_binary_size.py
- tests/integration_tests/build/test_coverage.py
A step forward for #363.
With the recently merged #1862, realized the coverage for jailer can be quite easily increased.
Split `run()` in two in order to be able to unit-test some part of it.
Added a few unit tests and made a small cleanup in jailer env tests.
> jailer: increase code coverage

- tests/integration_tests/functional/test_metrics.py
Improve metrics test case, to read metrics back and assert 2 items
values inside result.
Values in these 2 items should be always equal to expected under normal case.
~~- [ ] Any newly added `unsafe` code is properly documented.~~
~~- [ ] Any API changes are reflected in `firecracker/swagger.yaml`.~~
~~- [ ] Any user-facing changes are …
> tests: add some assertions to metrics case

- src/devices/src/legacy/serial.rs
- src/devices/tests/integration_tests.rs
- src/devices/tests/serial_utils/mod.rs
Firecracker serial device is emulated around the standard input of a Firecracker process. When the Firecracker standard input is set up as an end of a pipe and the other end of the pipe is closed, then this event will level-trigger an `EPOLLHUP` event on the Firecracker standard input, which is monitored for driving the serial device emulation.
`EPOLLHUP` is currently an unexpected event and when it arrives, it will issue a warning. This warning is logged continuously, raising the Firecracker emulation thread to 100% utilization, starving the emulation and the guest, if quotas are imposed on the Firecracker process as a whole.
Fixes: #1875 .
Added handling of `EPOLLHUP` event received on the serial device input. When it is received, consume any bytes which might be inflight, then …
> serial: handle HANG_UP

- src/vmm/src/persist.rs
Since we are mmaping the memory file with MAP_PRIVATE, we don't need to open the file with write permission.
> snapshot load: open memory file in O_RDONLY mode

- src/vmm/src/memory_snapshot.rs
Replace the call to the `write_to` method from `vm_memory` with `write_all_to`. This one will use the [`Write::write_all`](https://doc.rust-lang.org/std/io/trait.Write.html#method.write_all) method that makes sure to keep writing in a loop until done.
This fix ensures we are writing all the guest memory to file.
> snapshot memory dump: make sure to write all bytes

- src/devices/src/virtio/vsock/csm/connection.rs
- src/devices/src/virtio/vsock/csm/mod.rs
- src/devices/src/virtio/vsock/csm/txbuf.rs
- src/devices/src/virtio/vsock/unix/muxer.rs
- src/devices/src/virtio/vsock/unix/muxer_rxq.rs
Addresses #1751 
This PR changes some of the internal mechanisms in the vsock device, that were causing the problems described in #1751.
> Update vsock logic to address stalling problems

- src/vmm/src/builder.rs
- src/vmm/src/vstate.rs
Fixes #1942
Use KVM_GET_CPUID2 in Vcpu::save_state().
Currently the CPUID is cached only at microvm boot time. The restore path
fails to cache the CPUID from the snapshot and will save a bogus value when
a new snapshot is created from the current state. When such a snapshot is loaded
it will cause the in-kernel KVM LAPIC emulation to setup incorrectly and
other undefined behaviour.
This commit removes CPUID caching from Vcpu and calls KVM_GET_CPUID2 on
the Vcpu::save_state() path.
> Remove CPUID caching.

- CHANGELOG.md
- src/devices/src/virtio/vsock/csm/connection.rs
- src/devices/src/virtio/vsock/device.rs
- src/devices/src/virtio/vsock/event_handler.rs
- src/devices/src/virtio/vsock/unix/muxer.rs
- src/logger/src/metrics.rs
- tests/integration_tests/build/test_coverage.py
- tests/integration_tests/functional/test_metrics.py
Add metrics tracking for the vsock devive similar to the network virtio
device.
Signed-off-by: Joshua Abraham <sinisterpatrician@gmail.com>
I'm not sure if you have additional metrics you'd want to capture in the vsock module, or if the CHANGELOG needs to be updated :)
Closes #1210.
This patch adds metrics tracking for the vsock virtio device TX and RX code paths.
> Add metrics for vsock virtio device

- src/api_server/src/lib.rs
- src/api_server/src/parsed_request.rs
- tests/integration_tests/build/test_coverage.py
devices::virtio::net::Error::TapOpen contains '"' in the string representation, which results an invalid JSON like below.
```
{
"fault_message": "Could not create Network Device: TapOpen(CreateTap(Os { code
: 1, kind: PermissionDenied, message: "Operation not permitted" }))"
}
```
It is safer to use serde_json rather than format!().
- Use serde_json instead of using format!() to create a JSON object.
> api_server: escape JSON meta characters

- CHANGELOG.md
- src/cpuid/src/transformer/common.rs
- src/cpuid/src/transformer/intel.rs
Fixes #1017 
Newer processors (like the one we run the CI on, AMD EPYC)
have adopted the TSC_DEADLINE_TIMER cpu flag which used to be Intel
specific.
** Please review by commits. Thanks!
> Fix boot time for AMD guests

- src/arch/src/aarch64/layout.rs
According to the definition, DRAM_MEM_END should be 1024G.
Signed-off-by: Wei Yang <richard.weiyang@linux.alibaba.com>
Fixes #1949.
> aarch64: fix definition of DRAM_MEM_END in layout.rs

- SPECIFICATION.md
Minor spelling fix
The word `average` was misspelled in the specification document.
I changed the spelling of the word `averadge` to `average`.
> Fix spelling error in SPECIFICATION.md

- docs/getting-started.md
the leading whitespace in a few scripts made it a bit more laborious
than usual to copy them into files for execution, so I removed it. I
also took the liberty of cleaning up some inconsistent indentation
while I was in there.
> clean up whitespace in "getting started" scripts

- CHANGELOG.md
- src/micro_http/src/common/headers.rs
- tests/integration_tests/build/test_coverage.py
Partially addresses #1975 and #1976 
Any number of whitespace characters are accepted after ":" when parsing HTTP headers.
> micro-http: Add more flexibility when parsing the headers

- CHANGELOG.md
- src/devices/src/lib.rs
- src/devices/src/virtio/net/device.rs
- src/devices/src/virtio/net/mod.rs
- src/logger/src/metrics.rs
- tests/integration_tests/build/test_coverage.py
This PR removes a potential panic condition caused by the virtio net device expecting to find a vnet header in every frame. In case a malformed shorter frame shows up on the TX path (large enough buffers make sure that it can't happen on RX), error messages are now logged and a dedicated metric is emitted. With this occasion, several unused device error variants have been removed.
* When processing a TX frame, Firecracker no longer `panic`s if it's missing the vnet header. Instead, it propagates an error and increments a metric.
> virtio net: don't rely on vnet header always being present

- src/arch/src/aarch64/fdt.rs
- src/arch/src/aarch64/gic.rs
- src/arch/src/aarch64/gicv2.rs
- src/arch/src/aarch64/gicv3.rs
- src/arch/src/aarch64/mod.rs
- src/arch/src/aarch64/regs.rs
- src/devices/src/legacy/rtc_pl031.rs
- src/kernel/src/loader/mod.rs
- src/vmm/src/builder.rs
- src/vmm/src/vstate.rs
- tests/integration_tests/build/test_style.py
Fixes #1007.
Fixes clippy errors and enforce check in test_style.
> Enforce clippy integration test on aarch64

- src/vmm/src/default_syscalls/mod.rs
> seccomp: allow KVM_GET_DIRTY_LOG ioctl

- CHANGELOG.md
- src/devices/src/virtio/net/device.rs
- src/logger/src/metrics.rs
This PR aims to improve the virtio-net metrics by covering some missing cases:
- throttled events (fixes #1986)
- mac address updates (fixes #1867)
- 2 new cases are separated from **rx_fails**: tap_read_fails and rx_partial_write
- 2 new cases are separated from **tx_fails**: tap_write_fails and tx_partial_reads
See above.
> net: add metrics

- Cargo.lock
- src/devices/Cargo.toml
- src/devices/src/virtio/net/device.rs
- src/devices/src/virtio/net/persist.rs
- src/dumbo/Cargo.toml
- src/dumbo/src/lib.rs
- src/dumbo/src/pdu/udp.rs
- src/dumbo/src/tcp/endpoint.rs
- src/dumbo/src/tcp/handler.rs
- src/dumbo/src/tcp/mod.rs
- src/micro_http/src/response.rs
- src/mmds/Cargo.toml
- src/mmds/src/lib.rs
- src/mmds/src/ns.rs
- src/mmds/src/persist.rs
- src/vmm/src/lib.rs
- src/vmm/src/resources.rs
- tests/integration_tests/build/test_coverage.py
Signed-off-by: moricho <ikeda.morito@gmail.com>
Fix: https://github.com/firecracker-microvm/firecracker/issues/1770
This PR 
・moves `dumbo::ns` to `mmds` crate.
・implements response retrieval callback passed to dumbo's tcp::handler
to remove the dumbo's dependency on `mmds`.
> Remove dumbo's dependency on mmds

- tests/framework/utils.py
When executing a shell command from a thread, the event loop in the
thread may be missing, so we should create one when that happens.
When no event loop exists, we create one and set it.
> Create event loop when one does not exist

- src/firecracker/src/main.rs
If the logger initialization from command line
arguments failed, the process aborted with a coredump.
> Gracefully handle cmd line logger errors

- src/dumbo/src/tcp/endpoint.rs
- src/micro_http/src/common/mod.rs
- src/micro_http/src/request.rs
- src/micro_http/src/response.rs
- src/micro_http/src/server.rs
- tests/integration_tests/build/test_coverage.py
Part of #2003
This PR adds checks/comments for the micro_http operations that are not fixed in #1985
> micro_http: check arithmetic operations

- CHANGELOG.md
- src/api_server/src/lib.rs
- src/api_server/src/parsed_request.rs
- src/devices/src/legacy/rtc_pl031.rs
- src/dumbo/src/tcp/mod.rs
- src/jailer/src/main.rs
- src/logger/src/lib.rs
- src/logger/src/metrics.rs
- src/mmds/src/lib.rs
- src/utils/src/time.rs
- src/vmm/src/persist.rs
- src/vmm/src/rpc_interface.rs
- src/vmm/tests/integration_tests.rs
- tests/integration_tests/build/test_coverage.py
- tests/integration_tests/functional/test_metrics.py
#1848
Added metrics that measure the duration of creating a full or diff snapshot and of loading from a snapshot.
> snapshot: add metrics for load and create

- CHANGELOG.md
- src/api_server/src/request/logger.rs
- src/api_server/swagger/firecracker.yaml
- src/vmm/src/vmm_config/logger.rs
For more flexibility, logger level should be case-insensitive.
Added support for configuring the logger with a case-insensitive level.
> logger: add support for case-insensitive level

- src/arch/src/aarch64/gic.rs
- src/arch/src/aarch64/layout.rs
We previously stated that we have a total of
128 usable interrupts when in fact we have a total
of 96 (128-32) since KVM_DEV_ARM_VGIC_GRP_NR_IRQS will
set the highest SPI number not the number of
usable SPIs.
> aarch64: fix confusion in IRQ allocation

- CHANGELOG.md
- src/devices/src/virtio/block/device.rs
- src/logger/src/metrics.rs
There are now two new metrics for throttled events in the block
device: `ops_rate_limiter_throttled` and
`transfer_rate_limiter_throttled`.
#1987 
Added `ops_rate_limiter_throttled` and `transfer_rate_limiter_throttled` metrics for a block device.
> block: added metrics for throttled events

- src/vmm/src/persist.rs
Fixes #2027.
Currently we directly use a plain [Read](https://doc.rust-lang.org/std/io/trait.Read.html) object to read from the snapshot file which is not efficient. This PR switches to a [BufReader](https://doc.rust-lang.org/std/io/struct.BufReader.html) which fits perfectly with how deserialization works.
> Use BufReader to load snapshots.

- src/dumbo/src/tcp/endpoint.rs
- src/micro_http/src/common/headers.rs
- src/micro_http/src/common/mod.rs
- src/micro_http/src/connection.rs
- src/micro_http/src/request.rs
Fixes #1977
* Changed `Content-Length` from `i32` to `u32`.
* Added a bunch of fixes for unchecked unsigned arithmetic in `connection.rs`. 
* Added more unit tests too that exercise failure cases for over/underflows in math operations.
* Replaced some `unwrap`s with error propagation, introducing new error variants.
> micro-http: unsigned Content-Length + several checked arithmetic operations

- Cargo.lock
- src/cpuid/Cargo.toml
- src/cpuid/src/lib.rs
- src/cpuid/src/transformer/common.rs
- src/cpuid/src/transformer/mod.rs
- src/utils/src/lib.rs
- src/vmm/Cargo.toml
- src/vmm/tests/integration_tests.rs
make it easier to update vmm_sys_util version.
> Use vmm_sys_util from utils everywhere

- src/vmm/src/default_syscalls/filters.rs
Fix for issue [#1960](https://github.com/firecracker-microvm/firecracker/issues/1960)
Whitelisted getpid and tgkill syscalls in seccomp filter for GNU.
Glibc is using these syscalls in the `pthread_kill()` implementation
> whitelist getpid and tgkill syscalls for gnu libc

- resources/tests/init.c
- src/arch/src/aarch64/fdt.rs
- src/arch/src/lib.rs
- src/devices/src/lib.rs
- src/devices/src/pseudo/boot_timer.rs
- src/devices/src/pseudo/mod.rs
- src/vmm/src/builder.rs
- src/vmm/src/device_manager/mmio.rs
- src/vmm/src/device_manager/persist.rs
- src/vmm/src/lib.rs
- src/vmm/src/vmm_config/logger.rs
- src/vmm/src/vstate.rs
- tests/integration_tests/build/test_coverage.py
- tests/integration_tests/build/test_style.py
- tests/integration_tests/performance/test_boottime.py
Proposed solution to #1865 
Still work in progress and untested, but at a high-level is this going in the right direction?
Where I've: 
1. Added a new pseudo `BootTimer` device 
2. Added it to the first slot on the MMIO bus
3. Removed the boot signal handling and timestamping from Vcpu (AFAICT,  the timestamp was only used for the boot log time)
4. Removed the logging statement to the BootTimer device.  
Still got to: 
- Write an `/sbin/init` wrapper for x86_64 in order to generate the signal at the correct address.
- Complete the "logic" of the device.
- Test.
- Add missing tests. 
Hope that makes sense.
Add a device to improve kernel boot time logging. 
the …
> devices: btimer: Add boot timer device.

- src/api_server/src/lib.rs
Firecracker panics if socket address is already in use.
Caught the error that caused the panic and gracefully exited with the proper code and error message.
> Handled Firecracker panic when socket address is already in use

- src/logger/src/metrics.rs
Comments for RTC devices may be copied from i8042 device.
Signed-off-by: bin liu <bin@hyper.sh>
These comments are misleading.
Change them to correct comment.
> Fix comments of copy miss

- src/devices/src/virtio/net/device.rs
- src/rate_limiter/src/lib.rs
Handled the corner case where a request to the rate limiter wanted
to consume more tokens than the bucket size by emptying the bucket
and arming the timer with a custom duration such that the rate
limiting is consistent.
Fixes #259 
> rate_limiter: enforce limit for large requests

- src/rate_limiter/src/persist.rs
Invalid inputs for rate limiter might cause Firecracker to panic while loading a snapshot.
Propagated the error upwards.
> Improved error handling for rate limiter

- src/devices/src/virtio/block/device.rs
- src/devices/src/virtio/block/persist.rs
- src/devices/src/virtio/block/request.rs
- src/vmm/src/device_manager/mmio.rs
- src/vmm/src/rpc_interface.rs
- src/vmm/src/vmm_config/drive.rs
- tests/framework/builder.py
- tests/framework/microvm.py
- tests/integration_tests/build/test_coverage.py
- tests/integration_tests/functional/test_api.py
- tests/integration_tests/functional/test_snapshot_basic.py
- tests/integration_tests/performance/test_snapshot_perf.py
- tests/pytest.ini
Needs regression test before upgrading to mergeable PR.
Fixes #1974 
When doing a Block device backing file update we have to update multiple properties built from the backing file.
The actual backing file path was not being updated so snapshots would use the old path and snapshot restores would malfunction.
Created `DiskProperties` helper object for setting up all `Block` fields derived from the backing file. The object can be used in both construction and update paths for the `Block` device.
It provides functionality for setting up all backing file related fields so that all related logic is contained.
This commit fixes snapshots of uVMs with PATCHed block devices.
`[Author …
> Fix snapshots of uVMs with PATCHed block devices

- CHANGELOG.md
- Cargo.lock
- src/api_server/swagger/firecracker.yaml
- src/devices/src/virtio/net.rs
- src/firecracker/Cargo.toml
- src/jailer/Cargo.toml
- tests/framework/microvm.py
- tests/host_tools/cpu_load.py
- tests/host_tools/network.py
- tests/integration_tests/functional/test_net.py
- tests/integration_tests/functional/test_rate_limiter.py
- tools/devtool
> Patch release v0.21.2

- CHANGELOG.md
- Cargo.lock
- src/api_server/swagger/firecracker.yaml
- src/devices/src/virtio/net.rs
- src/firecracker/Cargo.toml
- src/jailer/Cargo.toml
- tests/framework/microvm.py
- tests/host_tools/cpu_load.py
- tests/host_tools/network.py
- tests/integration_tests/functional/test_net.py
- tests/integration_tests/functional/test_rate_limiter.py
- tools/devtool
> Patch release v0.20.1

- src/devices/src/virtio/net/device.rs
- tests/framework/microvm.py
- tests/host_tools/cpu_load.py
- tests/host_tools/network.py
- tests/integration_tests/functional/test_net.py
- tests/integration_tests/functional/test_rate_limiter.py
#2057
- Fix and regression test for #2057
- Regression test for #1444 
> Fix net RX freeze bug

- tests/framework/microvm.py
- tests/host_tools/memory.py
- tests/integration_tests/functional/test_initrd.py
- tests/integration_tests/functional/test_serial_io.py
- tests/integration_tests/functional/test_shut_down.py
- tests/integration_tests/functional/test_signals.py
This PR refactors the memory monitor from the testing framework into a class, similar to how the [cpu load monitor](https://github.com/firecracker-microvm/firecracker-embargo/commit/42c42172ef2290fb9143cb089d9201985f492a14) is structured. 
Currently, the memory monitor determines the usage by parsing the `pmap` output and always skipping the region that has the same size as the guest memory region (because we are interested only in the VMM overhead).
The assumption that the guest region has the expected size is broken by the [current balloon memory release logic](https://github.com/firecracker-microvm/firecracker/pull/2054/), which `mmaps` a new region before using `madvise` to release it.
In this PR, a slightly different way of determining the guest memory region is used: 
1. first time …
> tests: refactor memory monitor

- tests/framework/microvm.py
- tests/integration_tests/functional/test_drives.py
- tests/integration_tests/functional/test_snapshot_basic.py
Fixes #1750
Add integration test that verifies that the root device corresponds to /dev/vda and the other
devices start from /dev/vdb and match the configuration order.
> Test block device ordering

- src/vmm/src/builder.rs
- src/vmm/src/default_syscalls/filters.rs
- src/vmm/src/lib.rs
- src/vmm/src/persist.rs
- src/vmm/src/resources.rs
- src/vmm/src/vstate/mod.rs
- src/vmm/src/vstate/system.rs
- src/vmm/src/vstate/vcpu.rs
- src/vmm/src/vstate/vm.rs
Fixes #1605.
vstate.rs is now a module with 2 submodules: vm.rs and vcpu.rs.
> vmm: broke up vstate in 2 separate files

- Cargo.lock
- src/arch/Cargo.toml
- src/devices/Cargo.toml
- src/kernel/Cargo.toml
- src/vmm/Cargo.toml
upgrade vm-memory version to 0.2.2
upgrade vm-memory version to 0.2.2
> upgrade vm-memory version to 0.2.2

- src/vmm/src/lib.rs
- tests/integration_tests/build/test_coverage.py
Also, fixes #1353.
Details in commit message.
> vmm: use display trait in errors where possible

- docs/api_requests/patch-block.md
`Is is` -> `It is`. Also changed `else` to `otherwise` for sentence clarity
Fixing minor typo in docs
`Is is` -> `It is`. Also changed `else` to `otherwise` for sentence clarity
> Fix minor doc typo in patch-block.md

- CHANGELOG.md
- src/firecracker/src/api_server_adapter.rs
- src/firecracker/src/main.rs
- src/vmm/src/builder.rs
- src/vmm/src/device_manager/persist.rs
- src/vmm/src/resources.rs
- src/vmm/src/rpc_interface.rs
- tests/integration_tests/build/test_coverage.py
- tests/integration_tests/performance/test_boottime.py
[#2069](https://github.com/firecracker-microvm/firecracker/issues/2069)
- Disabled boot timer device when restoring a snapshot.
- Added a dedicated **--boot-timer** parameter in order to activate the boot timer feature.
> Boot timer prod removal

- Cargo.lock
- src/devices/src/virtio/net/device.rs
- src/devices/src/virtio/net/persist.rs
- src/dumbo/src/lib.rs
- src/dumbo/src/pdu/arp.rs
- src/mmds/src/ns.rs
- src/mmds/src/persist.rs
- src/utils/Cargo.toml
- src/utils/src/net/mac.rs
- src/utils/src/net/mod.rs
- src/vmm/Cargo.toml
- src/vmm/src/resources.rs
- src/vmm/src/vmm_config/net.rs
Move MacAddr from dumbo crate to net
Fixes #1765.
Move MacAddr from dumbo crate to net. Update references to reflect change. Remove now unneeded dependency on dumbo from devices.
> Move MacAddr to utils

- src/devices/src/lib.rs
- src/devices/src/virtio/block/device.rs
- src/devices/src/virtio/net/device.rs
- src/devices/src/virtio/queue.rs
- src/devices/src/virtio/vsock/device.rs
- tests/integration_tests/build/test_coverage.py
During snapshot load, attempting add available descriptor into the virtio used ring caused errors when the address was off.
Added error and exited gracefully to handle the case described above.
> Improved virtqueue error handling for used ring

- Cargo.lock
- src/devices/Cargo.toml
- src/devices/src/lib.rs
- src/devices/src/virtio/balloon/device.rs
- src/devices/src/virtio/balloon/event_handler.rs
- src/devices/src/virtio/balloon/mod.rs
- src/devices/src/virtio/balloon/persist.rs
- src/devices/src/virtio/balloon/utils.rs
- src/devices/src/virtio/mod.rs
- src/logger/src/metrics.rs
- tests/integration_tests/build/test_coverage.py
- tests/integration_tests/functional/test_metrics.py
#1571 
Added a virtio balloon device that supports statistics.
Note: Because Firecracker uses a private anonymous mapping for freshly booted microVMs and private file-backed mapping for snapshot resumed microVMs, a madvise call for releasing memory is not sufficient to work in both cases.
This PR currently uses a hacky approach: before madvise, mmap a fresh private anonymous region over the one that we want the kernel to release.
> Memory ballooning support

- src/dumbo/src/tcp/endpoint.rs
- src/micro_http/src/common/headers.rs
- src/micro_http/src/common/mod.rs
- src/micro_http/src/connection.rs
- src/micro_http/src/lib.rs
- src/micro_http/src/request.rs
- src/micro_http/src/server.rs
Signed-off-by: cihodar <cihodar@amazon.com>
Fixes #1976
Made the output of InvalidHeader more verbose.
Modified InvalidHeader error such that it will give more context.
> Made Invalid Header error more verbose

- README.md
- docs/getting-started.md
- docs/jailer.md
Update docs to reflect experimental status of gnu builds and glibc jailer support.
A couple of parts in the documentation need to be updated:
- Using the jailer with glibc linked binaries is not supported.
- glibc Firecracker builds are considered experimental and not recommended for production.
- The jailer no longer installs the seccomp filters, the Firecracker process does.
Updated relevant documentation files.
> Update docs to reflect experimental status of gnu builds and glibc jailer support

- src/devices/src/virtio/block/persist.rs
- src/devices/src/virtio/net/persist.rs
- src/devices/src/virtio/persist.rs
- src/devices/src/virtio/queue.rs
- src/devices/src/virtio/vsock/mod.rs
- src/devices/src/virtio/vsock/persist.rs
- src/vmm/src/device_manager/mmio.rs
- src/vmm/src/device_manager/persist.rs
- src/vmm/src/lib.rs
- src/vmm/src/persist.rs
- src/vmm/src/vstate/vcpu/mod.rs
- src/vmm/tests/integration_tests.rs
- tests/integration_tests/build/test_coverage.py
Added sanity checks along the restore from snapshot path for device manager and virtio devices.
Also provided support for explicit user-facing error when attempting snapshot-create without pausing.
Fixes #2099 
> Snapshot restore - devices sanity checks

- src/vmm/src/device_manager/persist.rs
- tests/framework/utils_vsock.py
- tests/integration_tests/functional/test_snapshot_basic.py
- tests/integration_tests/functional/test_vsock.py
Vsock device did not restore properly after loading a microvm from snapshot.
Fixed vsock restore and updated snapshot integration tests to use a vsock device.
> Snapshot vsock

- Cargo.lock
- src/arch/Cargo.toml
- src/cpuid/Cargo.toml
- src/devices/Cargo.toml
- src/dumbo/Cargo.toml
- src/kernel/Cargo.toml
- src/logger/Cargo.toml
- src/micro_http/Cargo.toml
- src/mmds/Cargo.toml
- src/polly/Cargo.toml
- src/rate_limiter/Cargo.toml
- src/snapshot/Cargo.toml
- src/snapshot/src/lib.rs
- src/utils/Cargo.toml
- src/vmm/Cargo.toml
#1991  Reason for This PR
Firecracker does not use versionize_derive from crates.io.
Firecracker does not use latest versionize version.
Found some unused dependencies.
Other style adjustments were applied.
Fixes #1924.
> use latest versionize/versionize_derive

- CHANGELOG.md
- docs/design.md
- docs/jailer.md
- src/jailer/src/cgroup.rs
- src/jailer/src/env.rs
- src/jailer/src/main.rs
- src/utils/src/arg_parser.rs
- tests/framework/jailer.py
- tests/integration_tests/build/test_coverage.py
- tests/integration_tests/security/test_jail.py
Increase cgroups integration flexibility for the Jailer. 
Fixes #1937
Fixes #1617
New `--cgroups` argument have been added to the Jailer. This argument takes care of setting the passed cgroups generically and check that the expected value is correctly written.
The `Cgroup` type have been modified in order to represent each of the cgroups passed by `--cgroups` command line argument.
> Add --cgroups parameter to jailer

- Cargo.lock
- docs/benchmarks/state-serialize.md
- src/snapshot/Cargo.toml
- src/snapshot/benches/main.rs
- src/snapshot/benches/version_map.rs
- src/snapshot/src/lib.rs
- src/snapshot/tests/test.rs
- src/vmm/src/persist.rs
- src/vmm/tests/integration_tests.rs
CRC checksum was computed after deserialization of the snapshot state file.
Changed API to compute and add CRC checksum during snapshot save/load and moved CRC check before snapshot deserialization.
> snapshot: compute crc check before deserization

- CHANGELOG.md
- Cargo.lock
- src/api_server/swagger/firecracker.yaml
- src/firecracker/Cargo.toml
- src/jailer/Cargo.toml
This PR separates the changes done for 0.22.0 from the unreleased changes.
This was done as a separate PR because merging from v0.22.0 branch seems to be broken.
> Update changelog to include the v0.22.0 release

- tests/conftest.py
- tests/framework/artifacts.py
- tests/framework/builder.py
- tests/framework/jailer.py
- tests/framework/matrix.py
- tests/framework/microvm.py
- tests/framework/microvms.py
- tests/framework/utils.py
- tests/integration_tests/functional/test_cpu_features.py
- tests/integration_tests/functional/test_pause_resume.py
- tests/integration_tests/functional/test_snapshot_basic.py
- tests/integration_tests/functional/test_snapshot_version.py
- tests/integration_tests/performance/test_snapshot_perf.py
This completes the test suite mentioned in issue #1850. 
Also fixes #2077 and #2075 - collateral from snapshot networking config changes.
Add two snapshot version integration tests:
- Use current version to load snapshots created with older versions.
- Create snapshots with current versions and load in older releases.
Framework changes:
- added binary path parameters in init_microvm()
- added FirecrackerArtifact class
- added SnapshotArtifact class
- added support to specify the fc version when creating a snapshot
- use static network configuration for snapshots
More details in commit messages.
`[Reviewer TODO: Verify that these criteria …
> Add cross-version save/load integration tests.

- src/vmm/src/default_syscalls/filters.rs
- src/vmm/src/default_syscalls/mod.rs
The seccomp filters needed some auditing to tighten security even further and improve maintainability.
Some syscalls or parameters are no longer needed and some are used only before installing the filters.
* Removed some allowed syscalls and seccomp conditions.
* Added some more architecture-specific rules.
* Restricted allowed parameters even more.
* Modified a `fcntl` parameter type to be `DWORD`
* Added descriptive comments where relevant.
> Audit seccomp allowlist

- CHANGELOG.md
- tests/framework/jailer.py
- tools/devtool
When running tests with devtool, one might want to explicitly restrict the cpus and mems to a specific NUMA node or cross NUMA nodes.
Added two devtool flags:
* -c|--cpuset-cpus _cpulist_
* -m|--cpuset-mems _memlist_
The _cpulist_ and _memlist_ are forwarded to docker `--cpuset-cpus` and `--cpuset-mems`.
~~- [ ] Any newly added `unsafe` code is properly documented.~~
~~- [ ] Any API changes are reflected in `firecracker/swagger.yaml`.~~
~~- [ ] All added/changed functionality …
> devtool: added support for cpus/mems confinement

- CHANGELOG.md
- Cargo.toml
- tests/host_tools/cargo_build.py
- tools/devtool
This fix is to make tools/devtool to build jailer binary
only for musl targets.
Currently, jailer binary gets built successfully for even
non-musl targets but doesn't work with corresponding
firecracker binary.
As mentioned in #2102 
Currently, jailer binary gets built successfully for even
non-musl targets but doesn't work with corresponding
firecracker binary. This commit ensures jailer is not built for non-musl
targets.
- Modifed Cargo.toml workspace to exclude jailer for default build
- Modified devtool script to build jailer binary only for musl targets
- Updated changelog with the fix information …
> Fixed jailer build process

- src/cpuid/src/common.rs
- src/cpuid/src/lib.rs
- src/cpuid/src/template/intel/c3.rs
- src/cpuid/src/template/intel/mod.rs
- src/cpuid/src/template/intel/t2.rs
- src/cpuid/src/template/mod.rs
- src/cpuid/src/transformer/mod.rs
- src/vmm/src/vstate/vcpu/x86_64.rs
- tests/framework/microvms.py
- tests/integration_tests/build/test_coverage.py
- tests/integration_tests/functional/test_cpu_features.py
- tests/integration_tests/functional/test_pause_resume.py
- tests/integration_tests/functional/test_snapshot_basic.py
- tests/integration_tests/functional/test_snapshot_version.py
- tests/integration_tests/performance/test_snapshot_perf.py
#2130 
For the moment we have 2 CPUID templates: T2 and C3. They are both Intel-specific.
We have to store this information and validate it when applying a template. We shouldn't be able to apply Intel templates on AMD or vice-versa.
> make CPU templates vendor specific

- tests/framework/decorators.py
- tests/framework/http.py
- tests/framework/utils.py
- tests/host_tools/cpu_load.py
- tests/host_tools/memory.py
- tests/host_tools/proc.py
- tools/devctr/Dockerfile.aarch64
- tools/devctr/Dockerfile.x86_64
- tools/devtool
Performance tests might need core pinning  for spawned processes.
Added `psutil` python3 package to a new version of dev container and used it to get/set cpu affinity for processes but retrieve a process threads as well. 
~~- [] Any required documentation changes (code and docs) are included in this PR.~~
~~- [] Any API changes are reflected in `firecracker/swagger.yaml`.~~
~~- [] Any user-facing changes are mentioned in `CHANGELOG.md`.~~
~~- [] All added/changed functionality is tested.~~
> tests: pin processes to cpu cores

- src/devices/src/virtio/net/device.rs
- src/snapshot/Cargo.toml
- tests/integration_tests/build/test_coverage.py
Net: retry frame tx/rx in case of queue error
Net: retry frame tx/rx in case of queue error
> Net: retry frame tx/rx in case of queue related error

- Cargo.lock
- src/arch/Cargo.toml
- src/devices/Cargo.toml
- src/kernel/Cargo.toml
- src/vm-memory/Cargo.toml
- src/vm-memory/src/bitmap.rs
- src/vm-memory/src/lib.rs
- src/vm-memory/src/mmap.rs
- src/vmm/Cargo.toml
- tests/integration_tests/build/test_coverage.py
Bootstrap implementation for dirty page tracking in vm-memory - #1997
Thanks @alexandruag for providing insight/PoC on the proxy crate approach.
Create a "proxy" crate that Firecracker will use as a dependency for all current vm-memory imports. This crate will export local GuestMemoryMmap and GuestRegionMap implementations that will contain dirty page tracking functionality. All other re-exports will be fetched from upstream vm-memory.
> Start dirty page tracking implementation in vm-memory.

- docs/dev-machine-setup.md
Outdated information in [Setting up a Development Environment for Firecracker](https://github.com/firecracker-microvm/firecracker/blob/22908c9fb0cd5fb20febc5d18ff1284caa5f3a53/docs/dev-machine-setup.md#readme)
Replace cautionary note that AWS only provide bare-metal instances in one region; these are now more widely available.
> Fix superseded advice about region choice for EC2 bare metal

- src/vmm/src/default_syscalls/filters.rs
- tests/framework/jailer.py
- tests/framework/microvm.py
- tools/devctr/Dockerfile.aarch64
- tools/devctr/Dockerfile.x86_64
- tools/devtool
The [previous similar PR](https://github.com/firecracker-microvm/firecracker/pull/2147) was closed because I needed to do a rebase from mainline first. 
With the previous allowlist, Firecracker raised a SIGSYS when running non-jailed.
This was because the `/etc/localtime` was getting memory mapped by the `localtime_r` musl implementation, used in the logger.
It was not caught by our CI because we don't mount the `/etc/localtime` in the jailer.
- Allowed the `mmap` syscall with the `MAP_SHARED` flag.
- Added a new docker container tag that installs the `tzdata` package - `fcuvm/dev:v20` - in order to have access to the `/etc/localtime` file in the container.
- Modified the test framework to mount `/etc/localtime` in the jailer root so that this error will not reappear in the future.
By …
> Add mmap with MAP_SHARED to allowlist.

- tests/integration_tests/performance/test_boottime.py
- tests/integration_tests/performance/test_process_startup_time.py
We recently switched our CI to run on m6g instances.
Adjusted boot time for initrd and process startup time.
> CI: adjust the boot time and process startup time to m6g's performances

- src/devices/src/virtio/queue.rs
Fixed a bug in the virtio mechansim which could lead to the virtqueue reading stale data. Specifically, the virtqueue pop() function reads the index of the available ring tail from the driver in order to check for new descriptors made available.
Based on that, it goes on to read the location of the available virtq descriptors. This introduces a load-load control dependency for which we need to protect against with a full memory barrier on weak memory models like arm.
The Firecracker virtqueue implementation does not take into account Arm's weak ordering, which requires barriers to ensure that data from the guest is not stale. The current implementation does not include this barrier so it is possible for an emulated device to lose customer data …
> arm: fix possible load-load data inconsistency

- src/devices/src/virtio/vsock/test_utils.rs
Signed-off-by: Cihodaru Alexandru <cihodar@amazon.com>
Queue size used in TestContext was different from the one used
in development.
Changed value of queue size in TestContext to be the same with the
value used in development(256).
> Modified queue size in TestContext.

- src/devices/src/legacy/serial.rs
- src/devices/tests/integration_tests.rs
- src/vmm/src/builder.rs
- tests/integration_tests/build/test_coverage.py
- tests/integration_tests/functional/test_serial_io.py
- tests/integration_tests/security/test_sec_audit.py
> [v0.22.1] Fix serial memory allocation issue.

- docs/snapshotting/snapshot-support.md
- src/devices/src/legacy/serial.rs
- src/devices/src/virtio/queue.rs
- src/devices/tests/integration_tests.rs
- src/vmm/src/builder.rs
- tests/integration_tests/build/test_coverage.py
- tests/integration_tests/functional/test_serial_io.py
Cherry pick relevant commits from master and v0.22.1 bug fix.
Fixes possible load-load data inconsistency on arm.
Documentation updates for snapshotting.
Fixes #2177 
> [v0.23.0] Cherry-pick commits

- Cargo.lock
- src/vm-memory/Cargo.toml
- src/vm-memory/src/mmap.rs
- tests/integration_tests/build/test_coverage.py
Bootstrap implementation for dirty page tracking in vm-memory - #1997
- Added a dedicated dirty page bitmap for GuestRegionMap.
- Updated local vm-memory's API with capabilities to enable dirty page tracking.
- Updated dirty page bitmap every time the memory is altered.
- Added unit tests for both GuestRegionMap and GuestMemoryMmap.
> Added dirty page tracking functionality to local vm-memory

- docs/design.md
- docs/prod-host-setup.md
Documentation was out of date. Seccomp filters are no longer installed by the Jailer,
they are a default of the Firecracker process.
Update statements in `prod-host-setup.md` and `design.md`
> docs update: seccomp is enabled by Firecracker

- src/vmm/src/default_syscalls/mod.rs
- tests/framework/microvm.py
- tests/integration_tests/functional/test_shut_down.py
The following `ioctl` parameters were removed from the allowlist after the audit: `TCSETS` and `TCGETS`.
These calls are triggered on microVM shutdown, if Firecracker was launched from a shell, in order to restore the calling terminal settings.
This was not triggered by our integration tests, because in `test_shut_down.py` we were using the jailer to `exec` into Firecracker.
- Add `ioctl` `TCGETS` & `TCSETS` to seccomp allowlist
- Add regression test, by launching Firecracker from a `screen` session in the shutdown test.
- Modified the `microvm.kill` method in the test framework to ignore errors from `screen kill`. Otherwise the command would return an error, since the process was already killed by the reboot. …
> seccomp_audit: allow ioctl TCGETS & TCSETS

- src/vmm/src/default_syscalls/filters.rs
- src/vmm/src/default_syscalls/mod.rs
- tests/framework/jailer.py
- tests/framework/microvm.py
- tests/integration_tests/functional/test_shut_down.py
- tools/devctr/Dockerfile.aarch64
- tools/devctr/Dockerfile.x86_64
- tools/devtool
Merge feature/seccomp_audit into master.
The seccomp allowlist audit is done and was properly tested.
Also fixes: #2128 
Note: These commits were already reviewed and approved on the feature branch
- Removed unnecessary allowed syscalls.
- Tighten allowed parameters.
- Add arch-specific `ioctl` conditions
- Add descriptive comments where relevant
- Add regression checks for some syscalls/arguments: `mmap(MAP_SHARED)`, `ioctl(TIOCGWINSZ)`, `ioctl(TCGETS)`, `ioctl(TCSETS)`
- Changes `FCNTL_FD_CLOEXEC` param type to be `DWORD`
> Merge feature/seccomp_audit into master

- docs/snapshotting/snapshot-support.md
When snapshots are used in a such a manner that a given guest's state is resumed from more than once, guest information assumed to be unique may in fact not be; this information can include identifiers, random numbers and random number seeds, as well as cryptographic tokens. Without a strong mechanism that enables users to guarantee that unique things stay
unique across snapshot restores, we consider resuming execution from the same state more than once insecure.
This PR adds documentation about this, including examples.
We also outline a possible path forward, [referencing](https://lkml.org/lkml/2020/10/16/629) the discussion about Linux guest operating system handling this situation on lkml.
- Add documentation about the effects of resuming execution multiple times from the same state, …
> docs: add documentation on snapshot uniqueness

- tests/conftest.py
- tests/framework/builder.py
- tests/framework/scheduler.py
- tests/framework/statistics/__init__.py
- tests/framework/statistics/consumer.py
- tests/framework/statistics/core.py
- tests/framework/statistics/criteria.py
- tests/framework/statistics/function.py
- tests/framework/statistics/producer.py
- tests/framework/statistics/types.py
- tests/framework/utils.py
- tests/integration_tests/performance/test_network_latency.py
This PR adds a generic statistical information gathering component. It can be used for performance testing, where statistical information can be inferred from multiple iterations.
An usage example of this component was added for `test_network_latency.py` performance test, provided in #1916 .
The component has three entities:
* Statistics core: base class which exposes the loop for managing multiple measurements.
* Statistics producer: base class which is used by the core to run measurements on host or guest and produce raw data output.
* Statistics consumer: base class which consumes multiple results, in multiple iterations, parses them and computes the statistics.
**Note**: This PR is focused only on the results computation of statistical tests. The statistics result is a JSON which will …
> tests: added statistics component

- tests/framework/statistics/function.py
* Stddev function has an implementation for `call` instead of `__call__`.
* Percentile `__call__` has a redundant extra argument.
* Renamed `call` to `__call__` for Stddev function.
* Removed the percentile `__call__` extra arg.
~~- [] Any required documentation changes (code and docs) are included in this PR.~~
~~- [] Any newly added `unsafe` code is properly documented.~~
~~- [] Any API changes are reflected in `firecracker/swagger.yaml`.~~
~~- [] Any user-facing changes are mentioned in `CHANGELOG.md`.~~
~~- [] All added/changed functionality is tested.~~
> Fixes around statistics functions

- src/vmm/src/signal_handler.rs
- tests/host_tools/proc.py
- tests/integration_tests/build/test_coverage.py
- tools/devctr/Dockerfile.aarch64
- tools/devtool
Fixes #1579.
Read commits one by one.
> aarch64: enable coverage integration test

- tools/devtool
Resolves #2225.
Replace `cargo update` with `cargo check` in `devtool prepare_release`.
The `cargo check` command updates in the lockfile the new firecracker and jailer versions, while also checking that all the code compiles.
> devtool: remove cargo update from prepare_release

- tests/integration_tests/build/test_coverage.py
Seems that on the CI machines, this is still
unstable.
> CI: disable kcov test on arm

- src/api_server/src/parsed_request.rs
- src/api_server/src/request/balloon.rs
- src/api_server/swagger/firecracker.yaml
- src/devices/src/virtio/balloon/device.rs
- src/devices/src/virtio/balloon/mod.rs
- src/vmm/src/lib.rs
- src/vmm/src/rpc_interface.rs
- src/vmm/src/vmm_config/balloon.rs
- tests/framework/resources.py
- tests/integration_tests/build/test_coverage.py
- tests/integration_tests/functional/test_api.py
- tests/integration_tests/functional/test_balloon.py
We need an API call to poll the state of the balloon device.
Added an API call to poll the state of the balloon device.
> [Balloon] Added GET call for balloon device state

- Cargo.lock
- src/vmm/tests/integration_tests.rs
- tests/integration_tests/build/test_coverage.py
As a post-release step, I ran `cargo update` in mainline, to update dependencies.
Updated all dependencies, apart from `versionize` and `versionize_derive`, since they require extra coding work for supporting union deserialization.
- ran `cargo update`
- manually edited `Cargo.lock` to rollback the versions of `versionize_derive` and `versionize`
- removed some `unsafe` uses, which were not needed after upgrading the `libc` crate
> Cargo: updated dependencies

- src/devices/src/virtio/block/device.rs
- src/devices/src/virtio/net/device.rs
- src/vmm/src/device_manager/mmio.rs
- src/vmm/src/lib.rs
- src/vmm/src/rpc_interface.rs
- src/vmm/src/vmm_config/drive.rs
- src/vmm/src/vmm_config/net.rs
- tests/integration_tests/functional/test_api.py
Cleans up some device-specific and vmm-internal logic from `RPC interface` and breaks that code into separate pieces, each working at the appropriate layer/component.
Also de-dups device downcasting code - currently only two operations:
1. update net rate limiters
2. update block device path
But going further we plan to add others such as:
- update block rate limiters
- get balloon config
- get balloon stats
This PR paves the way for them.
- Created helper `device_manager::on_virtio_device_with_id()` to de-duplicate code that needs to find a specific virtio device then downcast it to its concrete type to call one of its methods. The helper function can be given a closure that directly works with a `&mut T` where T is the concrete type.
- Vmm exposes programmatic interface to update net …
> Improve device update operations

- src/api_server/src/lib.rs
- src/vmm/src/builder.rs
- src/vmm/src/lib.rs
- src/vmm/src/rpc_interface.rs
- src/vmm/src/vmm_config/mmds.rs
- tests/integration_tests/build/test_coverage.py
RPC interface had no unit-test coverage.
Fixes #2060 - Loading snapshot is allowed after configuration of kernel and rootfs
The RPC interface code has the purpose of transforming locally defined RPC commands (VmmActions) to programmatic API calls to the underlying components.
In order to efficiently test the RPC interface code we could create mock objects for these underlying components and make use of these mock objects to control and validate expected RPC interface behavior.
Adds `struct MockVmRes` which, when under config(test), is exported as `VmResources`.
With a mock VmResources struct we can easily test most of the PrebootApiController.
Adds `struct MockVmm` which, when under config(test), is exported as `Vmm`.
With a mock Vmm struct we can easily test the RuntimeApiController, as …
> Add unittests to RPC interface

- src/devices/src/virtio/net/device.rs
The main reason is fixing the following: 
[Bug] Network device `rx_fails` metric is incremented on TX path #2175
The function where the change occurs is called **process_tx**.
The proper metric to be counted in the case of a failure on line 578 is **tx_fails**. 
Therefore, I have replaced **rx_fails** with **tx_fails**.
> [NET] Fix rx_fails mismatch

- docs/snapshotting/snapshot-support.md
This commit fixes a broken link pointing to RELEASE_POLICY.md, inside snapshot-support.md file.
Change the link pointing to RELEASE_POLICY.md to the correct one,
to guide the readers into the right location.
> Fix release_policy.md link

- CHANGELOG.md
- src/jailer/src/main.rs
Jailer's `--extra-args` parameter is basically a noop. It is not parsed and its value is not used by the jailer.
The supported mechanism for passing arguments to Firecracker, which is also documented in the jailer docs is using the `--` separator.
- Removed the `--extra-args` param from jailer.
- Updated the `--help` information of the jailer.
> jailer: remove useless --extra-args param

- src/devices/src/virtio/balloon/device.rs
- src/devices/src/virtio/balloon/mod.rs
- src/devices/src/virtio/balloon/persist.rs
We introduced sanity checks for virtqueues on snapshot restore, but they were not used in the balloon device.
Applied the sanity checks on the virtio queues in the balloon restore function.
> [Balloon] Fix snap load crashes with invalid input

- src/api_server/src/parsed_request.rs
- src/api_server/src/request/machine_configuration.rs
- tests/integration_tests/functional/test_api.py
Fixes #2165 
* Return an error when trying to set cpu_template on aarch64 since it is not supported.
* Add to unit tests of parsing PUT machine configuration to make sure the error is returned on aarch64.
* Modify unit tests that test setting machine config making them platform-specific.
Now trying to set the `cpu_template` on aarch64 by running:
```bash 
curl --unix-socket /tmp/firecracker.socket -i  -X PUT "http://localhost/machine-config"  -H "accept: application/json"  -H "Content-Type: application/json"  -d "{ \"vcpu_count\": 1, \"mem_size_mib\": 32, \"ht_enabled\": false, \"cpu_template\": \"T2\" }"
```
will return the following error:
```bash
{"fault_message":"cpu_template is not supported on aarch64"}
```
While running the same request on an x86 machine will work normally.
By …
> Return error when setting CPU template on aarch64

- src/firecracker/src/api_server_adapter.rs
- src/firecracker/src/metrics.rs
Signed-off-by: kumargu <kumargu@amazon.com>
#607
Changed visibility of pub fun in crate-firecracker. Public functions which are accessible only within crate are now changed to pub(crate).
This reduces the visibility of pub functions in the crate-firecracker.
> Changed visibility of pub functions in firecracker crate

- CHANGELOG.md
- src/firecracker/src/main.rs
- src/jailer/src/main.rs
- src/utils/src/arg_parser.rs
- tests/integration_tests/build/test_binary_size.py
- tests/integration_tests/build/test_coverage.py
This is a draft PR meant to solve [#2063](https://github.com/firecracker-microvm/firecracker/issues/2063).
An added functionality to display an ordered list of the current supported snapshot data format versions to the `--version` command line parameter. 
The updated `./firecracker --version` command will print the information in the format below:
> Firecracker v0.x.0
> 
> Supported snapshot data format versions: v0.y.0, v0.z.0
> Added command line parameter to retrieve supported snapshot versions

- src/vmm/src/lib.rs
- src/vmm/src/persist.rs
- src/vmm/src/resources.rs
- src/vmm/src/vmm_config/machine_config.rs
- tests/integration_tests/functional/test_api.py
Previously, when users set the target size of the balloon device, the request would succeed even if the target size was greater than the total amount of memory the VM had.
Added checks to ensure users cannot request more memory from the balloon than the total amount of VM memory.
> [Balloon] Added checks for invalid target sizes on balloon config updates

- tests/integration_tests/functional/test_balloon.py
Currently, tests in test_balloon.py use sleep() calls with hard coded values to
wait until the RSS of the microvm reaches a stable value for reading.
The behavior is changed and the test now waits until the percentage change in
RSS falls under a specified threshold. Right now 0.5% is used as the threshold.
Tests in test_balloon.py use hard-coded sleep() calls. Fixing that to make tests more robust.
The hard-coded sleep() calls results in failure of tests on aarch64.
The hard-coded sleep calls are removed and the test now waits until the percentage change in
RSS falls under a specified threshold. Right now 0.5% is used as the threshold. …
> Avoid hard-coded sleep() calls in balloon driver functional tests

- tests/integration_tests/functional/test_rtc.py
Check that the RTC device, which is only
present on aarch64 microVMs, functions properly.
Fixes https://github.com/firecracker-microvm/firecracker/issues/1117
> CI: add RTC test on aarch64

- src/firecracker/src/main.rs
- src/jailer/src/env.rs
- src/jailer/src/main.rs
- src/seccomp/src/lib.rs
- src/utils/src/arg_parser.rs
Simplify code.
Simplify for flag-type arguments: change `Value::Bool(bool)` to `Value::Flag` since the value only encodes whether an argument with no values (also referred to as a flag) is present or not. The inner bool is redundant (since it is always true) and confusing (because it suggests it could also be false).
Also do a quick rename of `Value::String` and `Value::Vector` to `Value::Single` and `Value::Multiple` to avoid confusion caused by the name collision with the standard types.
> Minor improvements to argument parsing code

- src/vmm/src/builder.rs
- src/vmm/src/device_manager/mmio.rs
- src/vmm/src/device_manager/persist.rs
- src/vmm/src/lib.rs
- src/vmm/src/rpc_interface.rs
- src/vmm/tests/integration_tests.rs
- tests/integration_tests/build/test_coverage.py
Fixes bug where, following a snapshot load, device emulation takes place while VM is _Paused_.
Kicking the devices after loading snapshot but _before_ resuming vm, breaks the assumption that vm state does not change while paused.
Fix this by moving device kicking from 'load snapshot' to 'vm resume'.
> vmm: kick devices on resume-vm instead of load-snaphot

- src/vm-memory/src/bitmap.rs
Optimized bitmap functions by changing atomic ordering types
and deleted attribute which allowed dead code.
Addressed extra comments here: https://github.com/firecracker-microvm/firecracker/pull/2259.
Relaxed atomic ordering types for the bitmap functions and forbade dead code for the bitmap file.
> snapshot: changed atomic ordering for bitmap functions

- tests/host_tools/readmem.c
- tests/integration_tests/functional/test_balloon.py
We needed an integration test to ensure memory allocated after an inflate/deflate cycle is indeed zeroed out.
Added a test for the ballon device that ensures the memory after a deflate is zeroed out.
> [Balloon] Add integration test for memory scrubbing

- docs/ballooning.md
- src/api_server/src/parsed_request.rs
- src/api_server/src/request/balloon.rs
- src/api_server/swagger/firecracker.yaml
- src/devices/src/virtio/balloon/device.rs
- src/devices/src/virtio/balloon/event_handler.rs
- src/devices/src/virtio/balloon/mod.rs
- src/devices/src/virtio/balloon/persist.rs
- src/vmm/src/builder.rs
- src/vmm/src/device_manager/persist.rs
- src/vmm/src/persist.rs
- src/vmm/src/resources.rs
- src/vmm/src/vmm_config/balloon.rs
- tests/framework/resources.py
- tests/integration_tests/functional/test_api.py
- tests/integration_tests/functional/test_balloon.py
The `must_tell_host` feature is not useful to any use case as of now because of the fact that the device does not offer page poisoning functionality. Therefore, since it is not useful, it should be removed.
Removed the `must_tell_host` feature of the balloon device.
- ~~[ ] Any newly added `unsafe` code is properly documented.~~
- ~~[ ] Any user-facing changes are mentioned in `CHANGELOG.md`.~~
> [Balloon] Remove `must_tell_host` device feature

- Cargo.lock
- src/arch/Cargo.toml
- src/cpuid/Cargo.toml
- src/devices/Cargo.toml
- src/mmds/Cargo.toml
- src/rate_limiter/Cargo.toml
- src/snapshot/Cargo.toml
- src/vmm/Cargo.toml
Update versionize, kvm-bindings and kvm-ioctls dependencies.
Update vm-memory from 0.3.0 to 0.4.0.
Update other dependencies.
> Upgrade versionize, kvm-bindings and kvm-ioctls dependencies.

- src/devices/src/virtio/balloon/persist.rs
- src/devices/src/virtio/block/persist.rs
- src/devices/src/virtio/net/persist.rs
- src/devices/src/virtio/persist.rs
- src/devices/src/virtio/vsock/persist.rs
- src/mmds/src/persist.rs
- src/rate_limiter/src/persist.rs
- src/vmm/src/device_manager/mmio.rs
- src/vmm/src/device_manager/persist.rs
- src/vmm/src/memory_snapshot.rs
- src/vmm/src/persist.rs
- src/vmm/src/vstate/vcpu/x86_64.rs
- src/vmm/src/vstate/vm.rs
Added warning comments to #[derive(Versionize)]
structures that require snapshot version bumps.
Fixes #2089
Added warning comments to remind developers to bump the snapshot version when changing structures with the versionize trait. 
> Added warning comments for version bumping

- tests/integration_tests/functional/test_drives.py
> CI: enable partuuid test on aarch64

- src/vmm/src/builder.rs
- src/vmm/src/device_manager/mmio.rs
- src/vmm/src/device_manager/persist.rs
Fixed unnatural naming of functions relating to mmio device
registration. 
Signed-off-by: HQ01 <qh384@nyu.edu>
Fixes #2015 
Renamed "register_new_virtio_mmio-device" to
"register_mmio_virtio_add_cmdline", "register_virtio_mmio_device" to
"register_mmio_virtio", and "register_new_mmio_boot_timer" to
"register_mmio_boot_timer". New function names are more consistent with
other mmio device registration functions. "New" is now only present in
names of functions that create the corresponding device. Functions that
register a new virtio device now have names better reflecting their
jobs.
`[Reviewer TODO: Verify that these criteria are met. …
> Fixed function naming in mmio device registration

- tests/framework/http.py
The micro-http server holds a HashMap of all opened connections and has a limit for the number of active connections at the same time. The `requests_unixsocket` python package, used by the testing framework for issuing API requests, opens a new connection for every API call and keeps it alive even after receiving the response from the server. These sockets are kept inside the connections HashMap and might very easily end up in exceeding the micro-http's limit, triggering a `503` response from the server. 
To prevent this from happening, the `pool_connections` argument was set to 10, consistent with the maximum number of open connections allowed: `MAX_CONNECTIONS`. Attempts to issue a new API request, after this limit has been reached, …
> tests: changed limit for reusable connections

- CHANGELOG.md
- Cargo.lock
- src/api_server/Cargo.toml
- src/api_server/src/lib.rs
- src/micro_http/Cargo.toml
- src/micro_http/src/server.rs
- src/vmm/src/lib.rs
- tests/README.md
- tests/framework/builder.py
- tests/integration_tests/build/test_coverage.py
- tests/integration_tests/functional/test_snapshot_basic.py
This PR addresses the following [bug](https://github.com/firecracker-microvm/firecracker/issues/2116). For now, the status is RFC since integration tests have to be added.
The important points of this change are the following:
- the VCPU errors that killed the process before, are now allowed to return to the API
thread.
- the API thread decides if an error is considered **fatal** or not. New errors can be added in the future which are deemed fatal
- in case of a **fatal** error, the Firecracker process is killed by the API thread,
since the VMM thread is already compromised
- this mechanism abides by the rules of the [Snapshotting specification](https://github.com/firecracker-microvm/firecracker/blob/master/docs/snapshotting/snapshot-support.md) which says that,
in the case of an error …
> Firecracker exits before returning API response FIX

- src/micro_http/src/connection.rs
- src/micro_http/src/server.rs
The server in `micro_http` was not explicitly handling the `EPOLLHUP`, `EPOLLRDHUP` and `EPOLLERR` epoll events.
Added new checks that close a connection that is signaled with these events.
- ~~[ ] Any newly added `unsafe` code is properly documented.~~
- ~~[ ] Any API changes are reflected in `firecracker/swagger.yaml`.~~
- ~~[ ] Any user-facing changes are mentioned in `CHANGELOG.md`.~~
> micro-http: explicit HUP/ERR handling in server

- src/cpuid/src/common.rs
- src/cpuid/src/template/intel/mod.rs
- src/cpuid/src/transformer/mod.rs
- src/vmm/src/persist.rs
- src/vmm/src/vstate/vcpu/x86_64.rs
- src/vmm/tests/integration_tests.rs
- tests/integration_tests/build/test_coverage.py
Partially implements #2023.
Validate cpu vendor id when loading a snapshot. More details in commit messages.
> Validate cpu vendor id on snapshot load.

- CHANGELOG.md
- src/arch/src/x86_64/layout.rs
- src/arch/src/x86_64/mptable.rs
- src/vmm/src/device_manager/mmio.rs
- src/vmm/src/persist.rs
- tests/framework/builder.py
- tests/integration_tests/functional/test_max_devices.py
- tests/integration_tests/functional/test_snapshot_version.py
increase the number of IRQs on x86_64
increase the number of IRQs on x86_64
> increase the number of IRQs on x86_64

- docs/initrd.md
I just tried using `initrd_path` and had to get more information in the firecracker Slack because some things were unclear due to the lack of documentation.
Added a very short guide to creating an initrd and using `initrd_path`.
> Add a short guide to using initrd_path

- tests/integration_tests/build/test_coverage.py
We tried replicating the variations seen in first phase by spawning multiple m6g and obtaining the coverage, however the value was always the same. We decided to enable the kcov test for the moment and solve the variations if/when the issue replicates again.
> CI: enable kcov on aarch64

- CHANGELOG.md
- docs/snapshotting/snapshot-support.md
- src/api_server/src/request/snapshot.rs
- src/api_server/swagger/firecracker.yaml
- src/vmm/src/persist.rs
- src/vmm/src/rpc_interface.rs
- src/vmm/src/vmm_config/snapshot.rs
- tests/framework/builder.py
- tests/framework/microvm.py
- tests/framework/resources.py
- tests/integration_tests/build/test_coverage.py
- tests/integration_tests/functional/test_balloon.py
- tests/integration_tests/functional/test_snapshot_basic.py
- tests/integration_tests/functional/test_snapshot_version.py
In order to minimize latency and overhead for starting a vm from snapshot, add option to both load the vm from snapshot and resume running it on the same API call.
Added optional `resume_vm` field to `SnapshotLoadParams` which, if `true` will lead to resuming the vm after a successful snapshot load.
The field is optional and takes a `false` default value, so this _API change is backward compatible_.
Added rpc-interface unit test to `LoadSnapshot` command.
Changed snapshot integration tests to use the new functionality to resume vm. The dedicated `resume` api call is still covered by `pause/resume` independent tests.
`[Reviewer TODO: …
> Add optional 'resume_vm' option to /snapshot/load API call

- src/api_server/src/lib.rs
- src/api_server/src/parsed_request.rs
- src/api_server/src/request/actions.rs
- src/api_server/src/request/balloon.rs
- src/api_server/src/request/boot_source.rs
- src/api_server/src/request/drive.rs
- src/api_server/src/request/instance_info.rs
- src/api_server/src/request/logger.rs
- src/api_server/src/request/machine_configuration.rs
- src/api_server/src/request/metrics.rs
- src/api_server/src/request/mmds.rs
- src/api_server/src/request/net.rs
- src/api_server/src/request/snapshot.rs
- src/api_server/src/request/vsock.rs
Reduce visibility of public functions. Functions which are visible only
with the crate are marked as pub(crate). Functions which are visible only
within the mod are marked as private.
Signed-off-by: kumargu <kumargu@amazon.com>
https://github.com/firecracker-microvm/firecracker/issues/607
Reduce visibility of public functions. Functions which are visible only with the crate are marked as pub(crate).
Functions which are visible only within the mod are marked as private.
> Change visibility of pub fun in api_server crate

- Cargo.lock
- Cargo.toml
- src/arch/Cargo.toml
- src/cpuid/Cargo.toml
- src/vmm/Cargo.toml
- src/vmm/src/vstate/vm.rs
- tests/integration_tests/build/test_coverage.py
This purpose of this PR is to reduce the overhead needed for maintaining, and releasing the firecracker-microvm/kvm-ioctls fork. The changes enable using the upstream kvm-ioctls, while still keeping the kvm-bindings + versionize support.
This should reduce the burden of maintaining forks of both kvm-ioctls
and kvm-bindings, and allows us to use the upsream kvm-ioctls while only
replacing the kvm-bindings dependency with one that supports versionize.
> use upstream kvm-ioctls

- tests/integration_tests/performance/test_snapshot_perf.py
Latency baseline for snapshot resume in v0.24.0 must be present in the baselines map of the CI.
- Add snapshot load latency baseline for v0.24.0.
- Removed redundant builder creation.
> Add snapshot load latency baseline for v0.24.0

- src/vmm/src/vstate/vcpu/mod.rs
- tests/integration_tests/build/test_coverage.py
- tests/integration_tests/functional/test_shut_down.py
Signed-off-by: Alexandru Cihodaru <cihodar@amazon.com>
Kvm system events were not handled and they caused `unexpected`
errors.
Added handler for KVM_SYSTEM_EVENT_SHUTDOWN
KVM_SYSTEM_EVENT_CRASH and KVM_SYSTEM_EVENT_RESET
on aarch64
> Handle kvm system events on aarch64

- src/arch/src/aarch64/fdt.rs
- src/arch/src/x86_64/msr.rs
- src/devices/src/virtio/balloon/utils.rs
- src/devices/src/virtio/block/request.rs
- src/devices/src/virtio/net/device.rs
- src/devices/src/virtio/vsock/unix/muxer.rs
- src/dumbo/src/tcp/connection.rs
- src/kernel/src/cmdline/mod.rs
- src/utils/src/arg_parser.rs
- src/vmm/src/default_syscalls/filters.rs
- tests/integration_tests/build/test_binary_size.py
- tests/integration_tests/build/test_coverage.py
- tests/integration_tests/security/demo_seccomp/src/bin/demo_malicious.rs
- tests/integration_tests/security/demo_seccomp/src/bin/seccomp_rules/mod.rs
- tools/devctr/Dockerfile.aarch64
- tools/devctr/Dockerfile.x86_64
- tools/devtool
Ideally we would update to the latest stable which is `1.48.0` - which has also promoted `aarch64-unknown-linux-musl` to _Tier 2_.
Unfortunately that's not possible because of compiler and linker issues https://github.com/rust-lang/rust/issues/79789 and https://github.com/rust-lang/rust/issues/79791.
Latest stable we can use now is `1.46.0` - the version targeted by this PR.
**Binary size** decreases along with covered lines because of aggressive LTO code deduplication.
> Update Rust toolchain to 1.46.0

- src/arch/src/aarch64/gic/dist_regs.rs
- src/arch/src/aarch64/gic/icc_regs.rs
- src/arch/src/aarch64/gic/redist_regs.rs
- src/vmm/src/vstate/vm.rs
The `KVM_DEV_ARM_VGIC_GRP_CPU_SYSREGS` group of GICv3 registers are serialized in 64bit chunks, instead of 32bit chunks.
Added a regression unit-test that fails without this fix and passes with it.
> Fix memory corruption during Aarch64 GICv3 serialization

- tests/framework/artifacts.py
- tests/integration_tests/performance/test_snapshot_perf.py
Ensure the latency for creating diff or full snapshots does not degrade over time.
Improved existing full snapshot creation test and added a new one for measuring latency for diff snapshots.
> Improved snapshot creation performance tests

- src/cpuid/src/cpu_leaf.rs
- src/cpuid/src/template/intel/c3.rs
- src/cpuid/src/template/intel/t2.rs
- tests/integration_tests/functional/test_cpu_features.py
Fixes an inconsistency in the templates - the OSPKE feature bit is masked, but the XSAVE PKRU bit is not. Snapshots created on a CPU with OSPKE from a T2/C3 uVM would fail to load on a CPU without OSPKE (Broadwell): https://elixir.bootlin.com/linux/latest/source/arch/x86/kvm/x86.c#L4299.
> Mask XSAVE PKRU bit in C2/T3 templates

- CHANGELOG.md
- src/api_server/src/lib.rs
- src/api_server/swagger/firecracker.yaml
- src/firecracker/src/api_server_adapter.rs
- src/firecracker/src/main.rs
- src/vmm/src/resources.rs
- src/vmm/src/rpc_interface.rs
- src/vmm/src/vmm_config/instance_info.rs
- src/vmm/src/vmm_config/logger.rs
- tests/framework/microvm.py
DescribeInstance command now provides information about microVM state
(Stopped, Running, Paused) instead of a boolean of whether it's started
or not.
Signed-off-by: HQ01 <qh384@nyu.edu>
#2285
DescribeInstance command now provides information about microVM state
(Stopped, Running, Paused) instead of a boolean of whether it's started
or not.
> Enabled describeInstance to show VM pause/resume

- src/devices/src/virtio/balloon/device.rs
- tests/integration_tests/build/test_coverage.py
Fix an infinite loop when guest virtio balloon driver provides invalid
descriptor chains to the balloon device.
Instead of looping while queue is not empty, only loop as long as there
are valid descriptor chains available.
> balloon: fix possible loop in inflation process

- Cargo.lock
Fix `Cargo.lock` after commit `9b95abacdd17b0e6c3132e202585e5281c9c495f` introduced `criterion` dependency.
> cargo.lock: add missing criterion dependency

- README.md
Fixes #2306 
Adds a clarification in the README that Firecracker only supports little-endian systems, naming some common examples.
> Clarify support for LE CPUs only in README

- src/vmm/src/device_manager/mmio.rs
- src/vmm/src/persist.rs
- tests/integration_tests/build/test_coverage.py
- tests/integration_tests/functional/test_balloon.py
ARM snapshot functionality does not support target version "0.23.0".
Also the version map needed updates for ARM.
- Moved snapshot version sanity checks and translation to a dedicated function.
- Added sanity check to prevent snapshot creation on ARM with "0.23.0" target version.
- Added the ARM specific VM/VCPU states to the specific root struct version.
> [ARM] Forbid snapshot creation for target version: 0.23.0

- src/devices/src/legacy/rtc_pl031.rs
The reset value for RTCPeriphID2 on aarch64 was incorrect.
According to https://developer.arm.com/documentation/ddi0224/c/Programmers-model/Summary-of-RTC-registers,
the reset value should be 0x04, not 0x14.
> aarch64/rtc: update reset value for RTCPeriphID2

- src/arch/src/aarch64/gic/mod.rs
- src/arch/src/aarch64/gic/regs/dist_regs.rs
- src/arch/src/aarch64/gic/regs/icc_regs.rs
- src/arch/src/aarch64/gic/regs/mod.rs
- src/arch/src/aarch64/gic/regs/redist_regs.rs
Improves on top of the fix for #2234
Split the GicState per vCPUs
> [aarch64][snap] Split the GicState per vCPUs

- src/logger/src/logger.rs
- tests/integration_tests/functional/test_logging.py
As per issue #2117, add capability to logger to log current
thread name in the prefix. Add unit test that spawns named
thread and checks the logged prefix for that name.
Signed-off-by: sundar.preston.789@gmail.com <sundar.preston.789@gmail.com>
Co-authored-by: Kevin Guo <kev.guo123@gmail.com>
Addresses issue #2117 
Submitted earlier PR #2314, but accidentally messed up git rebase. :cry:.
* Modified `src/logger/src/logger.rs` to always append the thread name to the log prefix. Also added unit test that creates a thread with custom name and checks the log's prefix for that name.
* Updated `tests/integration_tests/functional/test_logging.py` to reflect newly added thread names in log prefix.
By submitting this pull request, I confirm that my …
> Add thread name to logger prefix.

- docs/prod-host-setup.md
We need to provide recommendations on how to safely use the serial device.
Updated `prod_host_setup.md` with recommendations to control the output of serial device and log file such that users avoid unexpected disk or memory usage on the host when guests flood these with data.
> Updated prod-host-setup.md with serial device recommendations

- tests/integration_tests/performance/test_snapshot_perf.py
re-enable test_older_snapshot_resume_latency for aarch64
re-enable test_older_snapshot_resume_latency for aarch64
> re-enable test_older_snapshot_resume_latency for aarch64

- tests/integration_tests/performance/vsock_throughput_test_config.py
Some failures in Vsock throughput performance test for a CPU model of m5d.metal
Regathered baselines for an m5d.metal cpu model.
> Adjust m5d.metal VSOCK throughput baselines.

- docs/snapshotting/random-for-clones.md
- docs/snapshotting/snapshot-support.md
We need to document and provide examples to users on how to handle randomness when Firecracker snapshot/restore functionality is used. 
Add a high level overview on how randomness is handled in linux kernel;
Present the recommendations related to handling randomness when restoring
multiple microVM clones from a single snapshot.
> docs: randomness handling when restoring multiple VM clones from same snapshot

- src/devices/src/virtio/block/device.rs
- src/devices/src/virtio/block/event_handler.rs
- src/devices/src/virtio/block/request.rs
- src/jailer/src/main.rs
- tests/integration_tests/build/test_coverage.py
- tests/integration_tests/functional/test_drives.py
Fix the reported used bytes for any virtio block request.
Report the correct/actual bytes written/read from the virtio block buffers, which are accounted as used, and reported back to driver.
~~- [ ] This functionality can be added in [`rust-vmm`](https://github.com/rust-vmm).~~
~~- [] Any newly added `unsafe` code is properly documented.~~
~~- [ ] Any API changes are reflected in `firecracker/swagger.yaml`.~~
~~- [ ] Any user-facing changes are mentioned in `CHANGELOG.md`.~~
> Fix block used bytes reporting

- CHANGELOG.md
- docs/prod-host-setup.md
- src/devices/src/legacy/serial.rs
- tests/integration_tests/build/test_coverage.py
If the stdout buffer is full and non-blocking, the serial writes block.
If the stdout buffer is full and non-blocking, the serial writes no longer block.
Any new bytes will be lost, until the buffer is freed. The device also logs these
errors and increments the `uart.error_count` metric for each lost byte.
> Fix serial device bug for a full, non-blocking buffer.

- src/vmm/src/builder.rs
- src/vmm/src/lib.rs
- useful for #2236 
- code simplification
- possible bug fix: `construct_gicr_typer()` was touching bits below 32, possibly altering the offset or the instr encoded in the `attr` field 
We only use construct_gicr_typer() for calling:
- KVM_DEV_ARM_VGIC_GRP_REDIST_REGS
- KVM_DEV_ARM_VGIC_GRP_CPU_SYSREGS
But for this ioctls we don't need to construct the GICR_TYPER register.
We only need a squashed MPIDR, as specified in the linux kernel
documentation: https://github.com/torvalds/linux/blob/master/Documentation/virt/kvm/devices/arm-vgic-v3.rst
Quoting:
```
KVM_DEV_ARM_VGIC_GRP_CPU_SYSREGS
Attributes:
The attr field of kvm_device_attr encodes two values:
bits:     | 63      ....       32 | 31  ....  16 | 15  ....  0 |
values:   |         mpidr         |      RES     |    instr    |
The mpidr …
```
> [aarch64][snap] simplify construct_gicr_typer()

- src/devices/src/virtio/queue.rs
- tests/integration_tests/build/test_coverage.py
We have no check for an invalid number of descriptors in the available ring of the virito queues.
Added a check for an invalid number of descriptors in the available ring of the virito queues.
> Added number of virtq available descriptors check on snapshot restore

- src/jailer/src/env.rs
- src/jailer/src/main.rs
- src/utils/src/arg_parser.rs
- tests/integration_tests/build/test_coverage.py
- Alignment fixed in jailer's cgroup help text.
- In arg_parser replaced `clone` with `take`. Instead of cloning the user value each time, taking the value is a better alternative because clone overhead will be eliminated.
- In jailer commented for using `into_raw_fd` in netns. author written a TODO to check why EBADFD is faced while using`as_raw_fd` but not in `into_raw_fd`. added a comment to clarify that.
> jailer: some minor corrections

- FAQ.md
No mention of `SendCtrlAltDel` being unsupported on `aarch64` in FAQ.
Addition in FAQ.md to mention `SendCtrlAltDel` is not supported in the context of cleanly rebooting a VM on ARM.
> Updated FAQ.md

- CHANGELOG.md
- docs/devctr-image.md
- tools/devtool
This PR changes the repository from where docker images are pulled.
DockerHub is replaced by Amazon ECR.
> devtool: change docker repo to ecr

- FAQ.md
No mention of lack of cross-architecture emulation support in FAQ.
Mentioned lack of cross-architecture emulation support in FAQ.
> Mention lack of cross-architecture emulation support in FAQ

- src/vm-memory/src/mmap.rs
- src/vmm/src/builder.rs
- src/vmm/src/memory_snapshot.rs
- tests/integration_tests/build/test_coverage.py
This PR fixes the following [issue](https://github.com/firecracker-microvm/firecracker/issues/1533).
A guard page mechanism is implemented for guest memory creation and restore from Snapshot. Every memory region in the before mentioned cases will be surrounded by a left/right border, with the dimension of a system's PAGE_SIZE.
Rust unittests are also implemented.
> Guard Pages Mechanism

- src/vmm/src/default_syscalls/filters.rs
Fixes #2393. 
More details in this comment: https://github.com/firecracker-microvm/firecracker/issues/2393#issuecomment-757936727
Removed seccomp param checks for `clock_gettime`
Minor comment updates
Replace hardcoded `SYS_ftruncate` value with rust/libc constant
> Seccomp: allow clock_gettime with any parameters.

- CHANGELOG.md
- src/devices/src/virtio/block/device.rs
- src/devices/src/virtio/block/request.rs
- tests/integration_tests/build/test_coverage.py
The block device validated addresses from virtio descriptors before trying to execute requests. In this validation, the `checked_offset` function of guest memory was used to determine if the slice defined by the sum of the address and length of the virtio descriptor was within the guest memory bounds. However, this sum is greater than the last valid offset, `addr + len - 1`, by 1. This made the block device mark descriptors with slices at the very end of a region as invalid, making the last byte of a memory region unusable by the block device.
This check was performed as the previous guest memory model did not have it built in. This commit removes the checks as the current guest memory model validates the addresses before operations. Also added regression tests for this case.
By …
> block: fix off-by-one error in addr validation

- Cargo.lock
- src/vmm/Cargo.toml
- src/vmm/src/memory_snapshot.rs
- tests/integration_tests/build/test_coverage.py
In Firecracker the sysconf crate is only used for fetching the system's page size. In order to keep the dependencies list to a minimum, sysconf could be removed.
Fixes #2187 
Replaced sysconf's `pagesize()` with `libc::sysconf(libc::_SC_PAGESIZE)`.
> Removed sysconf dependency

- CHANGELOG.md
- Cargo.lock
- src/api_server/swagger/firecracker.yaml
- src/devices/src/virtio/block/device.rs
- src/devices/src/virtio/block/request.rs
- src/firecracker/Cargo.toml
- src/jailer/Cargo.toml
- tests/framework/utils.py
- tests/integration_tests/performance/test_boottime.py
Applying off-by-one block device patch to v0.22.
Adapt patch from upstream and release v0.22.3
> Apply block off-by-one patch and release v0.22.3

- .mailmap
- CHANGELOG.md
- Cargo.lock
- src/api_server/swagger/firecracker.yaml
- src/devices/src/virtio/block/device.rs
- src/devices/src/virtio/block/request.rs
- src/firecracker/Cargo.toml
- src/jailer/Cargo.toml
- src/vmm/src/default_syscalls/filters.rs
- tests/integration_tests/build/test_coverage.py
Releasing the v0.24.1 patch release.
Apply patch from upstream and release v0.24.1
Apply fix for `clock_gettime` on platforms without VDSO.
> Release v0.24.1

- tests/framework/artifacts.py
- tests/framework/utils.py
- tests/integration_tests/functional/test_snapshot_advanced.py
- tests/integration_tests/performance/test_snapshot_perf.py
Previously, the snapshot tests that were supposed to retrieve
the older Firecracker binaries from S3 were not filtering the artifacts
by version number.
This results in test failures for patch releases, where the test
will use both older and newer binaries.
Added support in the testing framework for this and fixed the
respective tests.
> tests: fix snapshot tests for older versions

- src/devices/src/virtio/vsock/device.rs
- src/devices/src/virtio/vsock/test_utils.rs
* be able to access vsock constructor from outside the `devices` crate
* expand auxiliary function to return the fd's for the complete interest list of the vsock device
* pub crate -> pub
* return all the 5 fd's in vsock's interest list
> vsock: little changes for accessibility purposes

- tests/conftest.py
- tests/framework/artifacts.py
- tests/framework/builder.py
- tests/framework/defs.py
- tests/framework/jailer.py
- tests/framework/statistics/__init__.py
- tests/framework/statistics/baselines_util.py
- tests/framework/statistics/consumer.py
- tests/framework/statistics/core.py
- tests/framework/statistics/function.py
- tests/framework/statistics/types.py
- tests/host_tools/network.py
- tests/integration_tests/build/test_coverage.py
- tests/integration_tests/build/test_unittests.py
- tests/integration_tests/functional/test_snapshot_basic.py
- tests/integration_tests/functional/test_vsock.py
- tests/integration_tests/performance/configs/block_performance_test_config_raw.json
- tests/integration_tests/performance/configs/network_tcp_throughput_test_config.py
- tests/integration_tests/performance/configs/vsock_throughput_test_config.py
- tests/integration_tests/performance/test_block_performance.py
- tests/integration_tests/performance/test_network_latency.py
- tests/integration_tests/performance/test_network_tcp_throughput.py
- tests/integration_tests/performance/test_snapshot_perf.py
- tests/integration_tests/performance/test_vsock_throughput.py
- tools/devtool
Lack of a block device performance test.
Added a test for Firecracker block device performance regression detection:
* Used `fio` to compute: iops, bandwidth, latency.
* Used `top` to compute cpu utilization host/guest.
* `fio` workloads cover the following modes: randread, randrw, read, readwrite.
* Block sizes for disk requests vary between: 512, 1024, 4096, 65536 bytes.
**NOTE**: I am still working through validating the computed baselines.
~~- [ ] This functionality can be added in [`rust-vmm`](https://github.com/rust-vmm).~~
~~- [ ] Any newly added `unsafe` …
> [performance] block device test

- tools/devtool
Added a mechanism of retrying commands and wrapped the "docker pull"
command in it.
The reason for doing this is that occasionally a docker pull command may
be rate limited by ECR.
docker pull occasionally throws errors
Added a mechanism of retrying a command. 
> devtool: add retry loop for docker pull

- tests/framework/builder.py
Signed-off-by: berciuliviu <lberciu@amazon.com>
The prefix wasn't added properly to the beginning of the folder name when creating MicrovmBuilder rootpath.
> Add prefix properly to MicrovmBuilder rootpath

- .cargo/config
- CHANGELOG.md
- docs/getting-started.md
- tools/devtool
Fixes https://github.com/firecracker-microvm/firecracker/issues/2104
TL;DR: `devtool` runs the `cargo build` command from inside the container. When working with dependencies on libraries which reside inside private git repositories, we need a way to perform git authentication for fetching those dependencies.
Added `devtool` build `--ssh-keys` flag to provide a way to specify the paths to the public and private SSH keys on the host. These will be mapped to the guest and used for authentication when fetching from private repositories.
This is how the added functionality was tested:
- Mirrored one of Firecracker's dependencies (say `dep-name`) into a private git repository on my account (with the title `new-dep-name`)
- Replaced `dep-name`'s …
> devtool: allow fetching private git repos

- .gitignore
- tests/conftest.py
- tests/framework/defs.py
- tests/framework/statistics/core.py
- tests/framework/utils.py
- tests/integration_tests/performance/configs/network_tcp_throughput_test_config.py
- tests/integration_tests/performance/configs/vsock_throughput_test_config.py
- tests/integration_tests/performance/test_network_tcp_throughput.py
- tests/integration_tests/performance/test_vsock_throughput.py
- tests/integration_tests/style/test_licenses.py
- tools/parse_baselines/main.py
- tools/parse_baselines/providers/iperf3.py
- tools/parse_baselines/providers/types.py
There is currently no standard way of gathering baselines when it comes to long-running performance tests.
In order to gather baselines:
- One has to modify the test code in order to output the raw results.
- After a number of test iterations are run, the resulting data has to be parsed with manual written scripts into the right baselines.
- Add support for pytest `--dump-results-to-file`, which will transform into a `results_file_dumper` fixture used for writing raw test data in the `test_results` folder
- Added a `parse_baselines` script that allows for custom logic for parsing the raw data into baselines.
- Added implementations for `parse_baselines` for vsock and network tcp tests.
- Refactored the `vsock_throughput` and `network_tcp_throughput` performance tests to use the …
> Support and tools for easier baseline gathering

- CHANGELOG.md
- Cargo.lock
- src/api_server/swagger/firecracker.yaml
- src/devices/src/virtio/block/device.rs
- src/devices/src/virtio/block/event_handler.rs
- src/devices/src/virtio/block/request.rs
- src/firecracker/Cargo.toml
- src/jailer/Cargo.toml
- tests/integration_tests/functional/test_drives.py
Improved the previous off-by-one error fix by making it more generic in order to preserve consistency across versions.
- Reverted the previous off-by-one error fix
- Added the used bytes reporting fix
- Added the off-by-one error fix which is consistent across all patches
> Made the previous off-by-one error fix more generic

- tests/framework/utils.py
- tests/integration_tests/performance/test_block_performance.py
- tools/parse_baselines/main.py
- tools/parse_baselines/providers/block.py
- tools/parse_baselines/providers/types.py
Add baseline parser for block performance test.
- Refactor `DataParser` interface.
- Add baseline parser for block performance test.
- Add flush on `ResultsFileDumper.writeln()`.
- Refactor block performance test to use the default VM temp folder instead of `src/tests/results`, for storing fio logs
> block perf test: parse_baselines script

- src/devices/src/virtio/balloon/utils.rs
- tests/integration_tests/build/test_coverage.py
The balloon device did not have any mechanism in place for dealing with duplicate page frame numbers coming from the guest driver. This is an edge case, as a normal driver would not be allowed to send duplicate pages to the balloon.
With this change, the balloon will log an error message and skip any duplicate page frame numbers sent by the guest driver.
> balloon: log error for duplicate pfns

- tools/devtool
The initial implementation for retry_cmd was returning the
first error code of the failed command. If that command later
succeeded, the first error code would still be returned.
> devtool: fix retry_cmd returning error code

- docs/snapshotting/snapshot-support.md
Path to README.md file in snapshot-support.md is broken and this fixes it to correctly point to the README at the root of the repo.
> Fix README path in snapshot-support.md

- resources/seccomp/aarch64-unknown-linux-musl.json
- resources/seccomp/x86_64-unknown-linux-musl.json
Given the fact that seccompiler and Firecracker now have support for different allowlists per thread category, we can now restrict the seccomp filters even further.
Before this PR, the same filter was used irrespective of the thread category
Split and audit the allowlist for each thread category for x86 and aarch64 musl targets.
> feature/file_based_seccomp: Triage allowlist for thread categories

- docs/devctr-image.md
- tools/devctr/Dockerfile.aarch64
- tools/devctr/poetry.lock
- tools/devtool
The `build_devctr` command was returning an error on aarch64, due to the lack of the `setuptools_rust` package.
The `build_devctr` command was also overriding the latest `v*` tag instead of creating a new one called `latest`
Update aarch64 Dockerfile.
Update python dependencies versions.
Switch devtool versions.
Modify `devtool build_devctr` command to create a new tag called `latest`.
> Update devctr image and small build_devctr fix

- src/api_server/src/lib.rs
- src/firecracker/src/api_server_adapter.rs
- src/seccomp/src/lib.rs
- src/seccomp/src/seccompiler.rs
- src/vmm/src/builder.rs
- src/vmm/src/lib.rs
- src/vmm/src/seccomp_filters/mod.rs
- src/vmm/src/signal_handler.rs
- src/vmm/src/vstate/vcpu/mod.rs
- tests/integration_tests/security/demo_seccomp/src/bin/demo_jailer.rs
1. The BPF deserialization helper was not passing any byte limit for allocation to `bincode`, the deserialization backend. This could potentially mean an uncontrolled amount of memory allocation for a filter deserialization. This can be constrained in Firecracker because we know the max filter length and the thread categories.
1. After some investigation, it turns out that the `prctl` syscall, that receives a the filter pointer, actually does a `copy_from_user` and leaves that memory region untouched. This is an opportunity to reuse the same filter reference for all VCPU threads, avoiding additional clones.
1. One other small fix that makes the `FilterTooLarge` error a little more understandable
View commit messages.
By submitting this pull request, I confirm that my contribution is made …
> feature/file_based_seccomp: add byte_limit to deserialization and other small improvements

- tests/conftest.py
- tests/framework/matrix.py
- tests/framework/microvm.py
- tests/framework/statistics/consumer.py
- tests/framework/statistics/core.py
- tests/framework/statistics/criteria.py
- tests/framework/statistics/function.py
- tests/framework/statistics/metadata.py
- tests/framework/utils.py
- tests/integration_tests/performance/configs/block_performance_test_config.json
- tests/integration_tests/performance/configs/network_tcp_throughput_test_config.json
- tests/integration_tests/performance/configs/vsock_throughput_test_config.json
- tests/integration_tests/performance/test_block_performance.py
- tests/integration_tests/performance/test_network_latency.py
- tests/integration_tests/performance/test_network_tcp_throughput.py
- tests/integration_tests/performance/test_vsock_throughput.py
- tests/integration_tests/performance/utils.py
- tools/parse_baselines/providers/block.py
- tools/parse_baselines/providers/iperf3.py
- tools/parse_baselines/providers/types.py
Performance tests fail fast. When the first case of misalignment between the baselines and the values gathered by the test cases is detected, the test stops.
* made the fail fast mechanism optional by default and introduced an exception aggregator abstraction. Exception message example:
```
E   Failed on 'vmlinux-4.14.bin/ubuntu-18.04.ext4/vsock-p1024K-1vcpu-g2h': 
E   'cpu_utilization_vmm/value': EqualWith failed. Target: '51 +- 4.59' vs Actual: '23.35'.
E   Failed on 'vmlinux-4.14.bin/ubuntu-18.04.ext4/vsock-pDEFAULT-1vcpu-g2h': 
E   'throughput/total': EqualWith failed. Target: '7036 +- 351.8' vs Actual: '8144.99'.
E   'cpu_utilization_vmm/value': EqualWith failed. Target: '51 +- 4.59' vs Actual: '26.65'.
E   'cpu_utilization_vcpus_total/value': EqualWith failed. Target: '99 +- 4.95' …
```
> Made performance tests fail fast mechanism optional by default

- CHANGELOG.md
- docs/api_requests/block-caching.md
- src/api_server/src/parsed_request.rs
- src/api_server/src/request/drive.rs
- src/api_server/swagger/firecracker.yaml
- src/devices/src/virtio/block/device.rs
- src/devices/src/virtio/block/mod.rs
- src/devices/src/virtio/block/persist.rs
- src/devices/src/virtio/block/request.rs
- src/devices/src/virtio/block/test_utils.rs
- src/vmm/src/builder.rs
- src/vmm/src/default_syscalls/filters.rs
- src/vmm/src/device_manager/persist.rs
- src/vmm/src/persist.rs
- src/vmm/src/resources.rs
- src/vmm/src/rpc_interface.rs
- src/vmm/src/version_map.rs
- src/vmm/src/vmm_config/drive.rs
- tests/framework/microvm.py
- tests/framework/resources.py
- tests/integration_tests/build/test_coverage.py
- tests/integration_tests/functional/test_drives.py
#2172 
This commit introduces the notion of cache type to the virtio block device implementation. This allows users to choose from two cache types:
- `unsafe`: this option will advertise the flush virtio capability to the guest block driver, but will acknowledge and ignore incoming flush requests;
- `writethrough`: this option will advertise the flush virtio capability to the guest block driver and will perform a `fsync` syscall on incoming flush requests;
This functionality is exposed to users through an optional `ignore_flush` field in the block configuration API request. When absent, this field defaults to `true`, ignoring incoming flush requests from the guest driver and keeping the behavior of the block device the same as before this change. Setting it to `false` will make the device …
> [Block] Add option to configure block device flush

- CHANGELOG.md
- src/devices/src/legacy/rtc_pl031.rs
- src/vmm/src/builder.rs
- src/vmm/src/device_manager/mmio.rs
- src/vmm/src/device_manager/persist.rs
- tests/integration_tests/build/test_coverage.py
This PR solves 2 problems:
* The RTC Pl031 implementation uses an u32 counter and our implementation would not check for a fixed 4-sized buffer.
* Removes unnecessary interrupt assertion
- unify appearance for read/write function
- cover corner cases in unit tests
- check for a fixed 4-sized buffer like the RTC PL031 specification asks for
> Fix non-compliant checks inside the RTC PL031 device

- src/arch/src/aarch64/regs.rs
- src/jailer/src/env.rs
- src/vmm/src/persist.rs
- src/vmm/tests/integration_tests.rs
- tests/integration_tests/build/test_coverage.py
- tests/integration_tests/performance/test_versioned_serialization_benchmark.py
Completes implementation for #2023.
On ARM, the Vendor ID is called Manufacturer ID and it is found inside the MIDR_EL1 system register [31:24].
For the Snapshot part, the MIDR_EL1  is located inside the **regs** field of each VCPUstate.
For the Host part, the MIDR_EL1 is located at the path _/sys/devices/system/cpu/cpu0/regs/identification/midr_el1_.
> ARM Snapshot Vendor Check

- src/devices/src/legacy/serial.rs
- src/vmm/src/builder.rs
- tests/framework/microvm.py
- tests/integration_tests/build/test_coverage.py
- tests/integration_tests/functional/test_serial_io.py
Firecracker stdout could block when trying to write from the serial if the buffer was full, blocking the vCPU trying to write to it.
Stdout is now non-blocking, also added an integration test for this behavior.
> Make stdout non-blocking

- CHANGELOG.md
- Cargo.lock
- src/api_server/swagger/firecracker.yaml
- src/firecracker/Cargo.toml
- src/jailer/Cargo.toml
- src/vmm/src/signal_handler.rs
- tests/framework/artifacts.py
- tests/framework/utils.py
- tests/framework/utils_vsock.py
- tests/integration_tests/functional/test_signals.py
- tests/integration_tests/functional/test_snapshot_advanced.py
- tests/integration_tests/functional/test_vsock.py
- tests/integration_tests/performance/test_snapshot_perf.py
- Fixes #2464
- Release v0.24.2
Don't exit VMM on SIGPIPE delivery. Recently we discovered that this can happen if the vsock emulation attempts to write() some guest app bytes to the UDS connection after it was closed by the host application. Metrics and errors are still being logged and the corresponding EPIPE error is handled at the vsock emulation layer.
Adds negative and regression test for vsock UDS connection close while there is inflight data from guest app to host app. 
> [v0.24.2] Gracefully handle SIGPIPE patch + release specific changes.

- CHANGELOG.md
- src/vmm/src/signal_handler.rs
- tests/framework/utils_vsock.py
- tests/integration_tests/functional/test_signals.py
- tests/integration_tests/functional/test_vsock.py
Fixes #2464.
Don't exit VMM on SIGPIPE delivery. Recently we discovered that this can happen if the vsock emulation attempts to write() some guest app bytes to the UDS connection after it was closed by the host application. Metrics and errors are still being logged and the corresponding EPIPE error is handled at the vsock emulation layer.
Adds negative and regression test for vsock UDS connection close while there is inflight data from guest app to host app. 
> Gracefully handle SIGPIPE.

- README.md
- docs/design.md
- docs/jailer.md
- docs/prod-host-setup.md
- docs/seccomp.md
- docs/seccompiler.md
- src/api_server/src/lib.rs
- src/seccomp/src/lib.rs
- src/vmm/src/builder.rs
- src/vmm/src/seccomp_filters/mod.rs
- src/vmm/src/vstate/vcpu/mod.rs
- tests/integration_tests/build/test_coverage.py
- tests/integration_tests/performance/test_process_startup_time.py
- tests/integration_tests/security/demo_seccomp/src/bin/demo_jailer.rs
- tests/integration_tests/security/test_custom_seccomp.py
- The documentation in regards to seccomp was outdated.
- There was also no documentation about seccompiler.
- There was no performance test measuring the impact of using a custom seccomp filter.
- Add & update documentation
- Add perf startup time test for custom filters
- Replace the regular file Reader with a BufReader for custom filter support. this speeds up the startup time considerably.
- Other small fixes
> [feature/file_based_seccomp] documentation, performance startup test and small fixes

- src/devices/src/virtio/net/tap.rs
- src/jailer/src/env.rs
- src/jailer/src/main.rs
- src/utils/src/net/macvtap.rs
- src/utils/src/net/mod.rs
- tests/framework/jailer.py
- tests/framework/microvm.py
- tests/host_tools/network.py
- tests/integration_tests/build/test_coverage.py
- tests/integration_tests/functional/test_net.py
- tests/integration_tests/performance/test_process_startup_time.py
- tests/integration_tests/style/test_licenses.py
Firecracker uses /dev/net/tun to open/create tap interfaces. On the host these are typically bridged, using the standard Linux bridge implementation.
Linux macvtap interfaces are similar to bridges but simpler: the kernel doesn't snoop frames to maintain a FIB to map MAC addresses to interfaces and doesn't need to use flooding, because the full topology is known to the kernel.
However, macvtap interfaces are exposed to userland as /dev/tap%d device nodes, which Firecracker doesn't support. This commit adds support by checking whether the `host_dev_name` in the network configuration looks like a path name, and opening the device node if it does.
Tested thus:
```bash
sudo ip link add dummy0 type dummy
sudo ip link add link dummy0 name vtap0 type macvtap mode bridge
sudo ip link add link …
```
> Add prototype support for macvtap interfaces

- tests/integration_tests/style/test_gitlint.py
The default location for the config file
is .gitlint, however when run from the tests
directory this needs to be adjusted.
> CI: fix bug in gitlint test

- tests/framework/utils.py
There is a bug in the [decision making logic for when to propagate an error](https://github.com/firecracker-microvm/firecracker/blob/master/tests/framework/utils.py#L283): when a new line was not added at the beginning of the ExceptionAggregator, but there is exactly one error in the list, the error would go unreported.
Checked for the case where the line was not added and there was exactly one error in the list.
> [Performance tests] Fixed bug in error propagation

- docs/getting-started.md
#2495 
Kernel image links in quickstart guide lacked the latest functionality, such as the balloon device driver. Updated the links in the guide to point to up-to-date kernel images.
> Updated kernel links in quickstart guide

- src/firecracker/src/main.rs
- src/seccompiler/src/seccompiler.rs
- src/vmm/src/seccomp_filters/mod.rs
- tests/integration_tests/build/test_coverage.py
- Errors in the seccompiler binary were bubbled up to the `main()` level and then unwrapped, causing ugly panics instead of gracefully exiting.
- Similar situation in Firecracker in regards to seccomp parameters.
Replaced the panic mechanism with logging + `exit(error_code)`
> [feature/file_based_seccomp] add graceful error handling

- src/vmm/src/vmm_config/balloon.rs
Issue #2490 has shown that there is confusion on user side when DeviceNotActive error is encountered.
Extended error message to make it more explicit leaving no room for confusion or doubt
> change wording of DeviceNotActive error message

- Cargo.lock
- Cargo.toml
- src/arch/Cargo.toml
- src/arch/src/aarch64/regs.rs
- src/arch/src/x86_64/msr.rs
- src/cpuid/Cargo.toml
- src/cpuid/src/transformer/amd.rs
- src/cpuid/src/transformer/common.rs
- src/cpuid/src/transformer/mod.rs
- src/devices/Cargo.toml
- src/devices/src/virtio/vsock/unix/muxer.rs
- src/micro_http/src/server.rs
- src/mmds/Cargo.toml
- src/polly/src/event_manager.rs
- src/rate_limiter/Cargo.toml
- src/snapshot/Cargo.toml
- src/utils/Cargo.toml
- src/vmm/Cargo.toml
- src/vmm/src/vstate/vcpu/aarch64.rs
- src/vmm/src/vstate/vcpu/x86_64.rs
New version of vmm-sys-util was available, with a couple of fixes.
- update vmm-sys-util dependency of `utils` crate and adapt code for slight modification in `epoll.wait` interface
- update dependencies that use vmm-sys-util with versions that depend on the same version as Firecracker (versionize, kvm-bindings, kvm-ioctls). Adapt code to account for upstream API changes.
> upgrade vmm-sys-util

- tests/integration_tests/performance/configs/block_performance_test_config.json
- tests/integration_tests/performance/configs/network_tcp_throughput_test_config.json
- tests/integration_tests/performance/configs/vsock_throughput_test_config.json
- tools/parse_baselines/providers/types.py
Due to a bug in the performance testing framework, some failures were not properly reported. This was fixed by this PR: https://github.com/firecracker-microvm/firecracker/pull/2498 
Now, this surfaced some typos/mistakes in the baselines for some performance tests.
- regather baselines for the statistics that were causing failures (fortunatelty, they were obviously off, due to human error from previous PRs)
- fixed a duplication in the block performance baseline that was also causing failures
- small adaptation of the baseline parser scripts to match the expected baseline format
`[Reviewer TODO: Verify that these criteria are met. Request …
> Adjust performance test baselines

- docs/rootfs-and-kernel-setup.md
I have added little detail about this command 'for d in bin etc lib root sbin usr; do tar c "/$d" | tar x -C /my-rootfs; done' .  Some of the people might be confused about it. For example me :) I was confused about that command result and I created this issue (https://github.com/firecracker-microvm/firecracker/issues/2473). Thank you so much @gc-plp @twitchyliquid64
1. An Added explanation and a warning message that is the result of 'for d in bin etc lib root sbin usr; do tar c "/$d" | tar x -C /my-rootfs; done' command.
> Docs: Suggestion against warning message

- docs/devctr-image.md
- tests/integration_tests/style/test_gitlint.py
Firecracker needs to use inclusive language. Documentation and code have been updated to use inclusive terms. The next step is to replace all occurrences of the *master* branch to *main*.
Renamed the *master* branch to *main*.
Fixes #2517 
> Changed master branch's name to *main*

- CHANGELOG.md
- docs/jailer.md
- src/api_server/src/lib.rs
- src/firecracker/src/api_server_adapter.rs
- src/firecracker/src/main.rs
- src/jailer/src/env.rs
- src/jailer/src/main.rs
- src/logger/src/lib.rs
- src/logger/src/metrics.rs
- tests/framework/jailer.py
- tests/integration_tests/build/test_coverage.py
- tests/integration_tests/performance/test_process_startup_time.py
- tests/integration_tests/security/test_jail.py
The [Jailer documentation](https://github.com/firecracker-microvm/firecracker/blob/master/docs/jailer.md) recommends that the user spawns the jailer process is into a new PID namespace, for extra resilience. This PR implements a mechanism which takes the burden off the users and allows the Jailer to spawn the Firecracker process into a new PID namespace.
Added a bool optional parameter to the Jailer: `--new-pid-ns`, which enables the jailer to exec into the provided binary in a new PID namespace.
> Add Jailer parameter to allow spawning the firecracker process into a new PID namespace

- README.md
renew slack invite link
renew slack invite link
> renew slack invite link

- CHANGELOG.md
- docs/ballooning.md
- src/api_server/src/parsed_request.rs
- src/api_server/src/request/balloon.rs
- src/api_server/swagger/firecracker.yaml
- src/devices/src/virtio/balloon/device.rs
- src/devices/src/virtio/balloon/mod.rs
- src/devices/src/virtio/balloon/persist.rs
- src/vmm/src/builder.rs
- src/vmm/src/device_manager/persist.rs
- src/vmm/src/lib.rs
- src/vmm/src/persist.rs
- src/vmm/src/resources.rs
- src/vmm/src/rpc_interface.rs
- src/vmm/src/vmm_config/balloon.rs
- tests/framework/resources.py
- tests/integration_tests/functional/test_api.py
- tests/integration_tests/functional/test_balloon.py
- tests/integration_tests/functional/test_snapshot_advanced.py
#2482 
Changed the API definition to reflect the correct units of memory (MiB).
> Balloon API correction

- CHANGELOG.md
- src/devices/src/virtio/block/device.rs
- src/devices/src/virtio/block/persist.rs
- src/vmm/src/persist.rs
- tests/framework/builder.py
- tests/framework/jailer.py
- tests/framework/microvm.py
- tests/framework/resources.py
- tests/integration_tests/functional/test_snapshot_version.py
- tests/integration_tests/performance/test_snapshot_perf.py
Depending on the host FS configuration, snapshot-related files (memory, vm-state, block devices backing files) could get corrupted if the backing mediums are moved while snapshot data is in-flight.
To provide a safe and consistent CreateSnapshot operation, Firecracker now flushes all snapshot related host-file as part of the create snapshot operation.
> snapshots: sync host resources as part of create-snapshot API call

- CHANGELOG.md
- docs/devctr-image.md
- tools/devtool
This PR backports the changes did on the main branch where we moved from using DockerHub to ECR.
- Change the origin of docker pull commands
- Add retry loop to handle ECR limits.
> Backport devtool using ECR to v0.24

- CHANGELOG.md
- Cargo.lock
- src/firecracker/Cargo.toml
- src/firecracker/src/main.rs
- src/snapshot/src/lib.rs
- src/utils/src/arg_parser.rs
- tests/integration_tests/build/test_coverage.py
- tests/integration_tests/functional/test_balloon.py
- tests/integration_tests/functional/test_cmd_line_parameters.py
- tests/integration_tests/functional/test_snapshot_advanced.py
- tests/integration_tests/functional/test_snapshot_basic.py
As snapshot format versions evolve, we need a mechanism to fetch the data version of a snapshot state file.
Added `describe-snapshot` parameter to fetch data version of the snapshot state file provided. Example:
```
$ ./firecracker --describe-snapshot full_snap.image
v0.23.0
```
> Add `describe-snapshot` parameter to fetch snapshot data version

- CHANGELOG.md
- src/devices/src/virtio/block/device.rs
- src/devices/src/virtio/block/persist.rs
- src/vmm/src/default_syscalls/filters.rs
- src/vmm/src/persist.rs
- tests/framework/builder.py
- tests/framework/jailer.py
- tests/framework/microvm.py
- tests/framework/resources.py
- tests/integration_tests/functional/test_snapshot_version.py
- tests/integration_tests/performance/test_snapshot_perf.py
Depending on the host FS configuration, snapshot-related files (memory, vm-state, block devices backing files) could get corrupted if the backing mediums are moved while snapshot data is in-flight.
To provide a safe and consistent CreateSnapshot operation, Firecracker now flushes all snapshot related host-file as part of the create snapshot operation.
> [v0.24 patch] snapshots: sync host resources as part of create-snapshot API call

- tests/framework/resources.py
- tests/integration_tests/functional/test_balloon.py
- tests/integration_tests/functional/test_snapshot_advanced.py
#2530 
The v0.24.3 ballooning API PR was merged and we updated the 0.24 binaries used in CI testing.
Changing the API in v0.24 broke the tests for the `main` branch, and this PR fixes this.
**This PR needs to be merged in order to unblock other PRs.**
> Remove extra logic from balloon API change

- docs/ballooning.md
The ballooning documentation was misleading with regards to the `deflate_on_oom` setting.
Clarified the behavior of `deflate_on_oom` in `ballooning.md`.
> [Balloon] Update `deflate_on_oom` documentation

- src/firecracker/src/api_server_adapter.rs
- src/firecracker/src/main.rs
- src/seccompiler/src/common.rs
- src/seccompiler/src/compiler.rs
- src/seccompiler/src/lib.rs
- src/seccompiler/src/seccompiler.rs
- src/vmm/src/builder.rs
- src/vmm/src/lib.rs
- src/vmm/src/persist.rs
- src/vmm/src/rpc_interface.rs
- src/vmm/src/seccomp_filters/mod.rs
- src/vmm/src/utilities/test_utils/mod.rs
- src/vmm/src/vstate/vcpu/mod.rs
- tests/integration_tests/build/test_coverage.py
See comment: https://github.com/firecracker-microvm/firecracker/pull/2557#discussion_r631847141
Previously, the InstanceStart request, was using a mutable
reference of the seccomp filter collection, removing the
entries for each thread category, after they were launched.
If a recoverable error occured, that did not bring down
the process, because the BPF map was mutated, a subsequent
InstanceStart would fail because the filters would have
already been freed.
This commit fixes this, by changing the mutable reference
on the PrebootAPIController to be a regular reference,
kept valid for the entire lifetime of the preboot controller
(until the instance is started).
The vmm and vcpu filters are no longer removed from the
filter map, until the entire map is freed.
This way, a subsequent call …
> make InstanceStart idempotent for seccomp filters

- tools/devtool
Add the 'distclean' command to clean up build files, test results and
the docker container.
The purpose of this command is to remove everything built or pulled
during the build process.
> devtool: add distclean command

- resources/seccomp/aarch64-unknown-linux-musl.json
- resources/seccomp/x86_64-unknown-linux-musl.json
With musl, `open`, `fstat` and `mmap` are used to read the
local timezone from `/etc/localtime`.
Depending on when the logger functions are first called,
they happen on different thread categories.
In the CI tests, they were always called on the API thread, but
when running with different configurations, this may not happen.
Added the above syscalls to the allowlist, for all thread
categories.
> seccomp: allow timezone-specific syscalls on all threads

- src/api_server/src/lib.rs
- src/api_server/src/parsed_request.rs
- src/api_server/src/request/instance_info.rs
- src/firecracker/src/api_server_adapter.rs
- src/firecracker/src/main.rs
- src/logger/src/metrics.rs
- src/vmm/src/builder.rs
- src/vmm/src/lib.rs
- src/vmm/src/persist.rs
- src/vmm/src/resources.rs
- src/vmm/src/rpc_interface.rs
- src/vmm/src/utilities/test_utils/mod.rs
- src/vmm/src/vmm_config/instance_info.rs
- src/vmm/src/vmm_config/logger.rs
- src/vmm/tests/integration_tests.rs
- tests/integration_tests/build/test_coverage.py
- tests/integration_tests/functional/test_cmd_line_start.py
- tests/integration_tests/functional/test_snapshot_basic.py
This PR is based on https://github.com/firecracker-microvm/firecracker/pull/2489 and some of the commits herein are co-authored by `Franck Séhédic <franck.sehedic@ledger.fr>`
When configured through `--config-file` the ApiServer improperly reports the VmState as "Not started" even when it actually is "Running".
(Note: This breaks integration with kata-runtime which does use `--config-file` and expects a "Running" VmState to be reported by the ApiServer).
`InstanceInfo` contains Vmm-instance-related information. As such, it makes more sense to be tied to a `Vmm` instance.
Embedded `InstanceInfo` in `struct Vmm` and exposed it through RPC all the way to HTTP API.
All Vmm state changes are naturally handled by Vmm internal logic.
API server no longer tracks Vmm state based on HTTP API calls …
> Fix GetInstanceInfo when config-file is used

- CHANGELOG.md
- src/vmm/src/lib.rs
- src/vmm/src/vstate/vcpu/mod.rs
- tests/integration_tests/build/test_coverage.py
- tests/integration_tests/performance/test_snapshot_perf.py
Currently the vcpus threads are started by the vmm which then moves forward and executes vcpu_resume which sends a signal to each vcpu thread.
The signal handler touches run_on_thread_local_vcpu in a way that is not thread and signal safe, so if there is a race between the main thread sending the signal and the vcpu threads initializing the local data in init_thread_local_data a SIGSEGV might happen because there is a risk for run_on_thread_local_vcpu to work with corrupted data.
The fix is for the Vmm thread to explicitly wait for vCPUs threads initialization after their creation, before moving forward. …
> [v0.24 backport] vmm: fix potential seg fault path on vcpu TLS

- Cargo.lock
- src/devices/Cargo.toml
- src/devices/src/virtio/balloon/utils.rs
- tests/integration_tests/build/test_coverage.py
#2480
Adds 2 new property based tests for compact_page_frame_numbers()
> Add balloon pfn compact property based tests

- src/firecracker/Cargo.toml
- src/jailer/Cargo.toml
- src/seccompiler/Cargo.toml
Adds support for [cargo-bitbake](https://github.com/meta-rust/cargo-bitbake), which enables easier maintenance for firecracker recipes going into [meta-aws](https://github.com/aws/meta-aws/pull/128).
Adds meta data needed by cargo-bitbake, so manual changes are not required prior to running cargo-bitbake.
> cargo-bitbake support

- CHANGELOG.md
- docs/prod-host-setup.md
- src/firecracker/src/main.rs
- tests/integration_tests/build/test_coverage.py
- tests/integration_tests/security/test_ssbd_mitigation.py
In our guide, we recommend enabling the SSBD mitiagtion through the kernel command line with `spec_store_bypass_disable=seccomp`. However, this only works for x86_64.
Added the fix in the jailer through the `prctl` interface. Updated the guide with the addition of the mitigation in the jailer through `prctl` and the alternative through the `ssbd=force-on` kernel command line parameter.
> Fix SSBD mitigation for aarch64

- tools/devctr/Dockerfile.aarch64
- tools/devctr/Dockerfile.x86_64
- tools/devtool
fixes `build_devctr --no-python-package-update`
Copy poetry.lock to the docker image when executing
tools/devtool build_devctr --no-python-package-update
in order to make sure that the python packages won't be updated.
> [devtool] fix build_devctr

- CHANGELOG.md
- Cargo.lock
- docs/devctr-image.md
- docs/prod-host-setup.md
- src/api_server/swagger/firecracker.yaml
- src/devices/src/virtio/block/device.rs
- src/devices/src/virtio/block/persist.rs
- src/firecracker/Cargo.toml
- src/firecracker/src/main.rs
- src/jailer/Cargo.toml
- src/vmm/src/default_syscalls/filters.rs
- src/vmm/src/lib.rs
- src/vmm/src/persist.rs
- src/vmm/src/vstate/vcpu/mod.rs
- tests/framework/builder.py
- tests/framework/jailer.py
- tests/framework/microvm.py
- tests/framework/resources.py
- tests/integration_tests/performance/test_snapshot_perf.py
- tests/integration_tests/security/test_ssbd_mitigation.py
- tests/integration_tests/style/test_rust.py
- tools/devtool
Backport fixes to v0.23 and release v0.23.4
- Changed Docker images repository from DockerHub to Amazon ECR.
- Snapshot related host files (vm-state, memory, block backing files) are now
flushed to their backing mediums as part of the CreateSnapshot operation.
- Fixed race between vcpu initialization and emulation thread which could
potentially lead to segmentation faults.
- Fixed the SSBD mitigation not being enabled on `aarch64` with the provided
`prod-host-setup.md`, by force-enabling it.
> Backport and Release Firecracker v0.23.4

- tools/devtool
Devtool checkenv() did not check/advise on SSBD mitigation options.
Add check_ssbd() in devtool checkenv()
> devtool: add check_ssbd() in checkenv()

- CHANGELOG.md
- src/devices/src/virtio/balloon/device.rs
- src/devices/src/virtio/balloon/persist.rs
- tests/integration_tests/functional/test_balloon.py
When testing for another issue, I resumed a snapshot with a balloon device in Firecracker v0.25. After resuming, the following log message is printed every `stats_polling_interval_s` seconds:
```
2021-05-26T16:04:35.049659990 [anonymous-instance:main:ERROR:src/devices/src/virtio/balloon/device.rs:426] Failed to update balloon stats, missing descriptor.
```
After digging into this some more, I found the root cause.
For context, the way balloon statistics work is the following:
- The guest driver is always putting a descriptor with the latest stats on the stats queue, in the available ring.
- The host sees the statistics and, when it wants new ones, it places the descriptor in the used ring.
- The guest driver immediately sends a new descriptor in the available ring.
We save the descriptor …
> Fix balloon statistics being broken after a snapshot restore event

- tests/framework/builder.py
- tests/integration_tests/performance/test_snapshot_perf.py
This aims to further stabilize the LoadSnapshot time
in the performance tests, by loading the snapshot from
a ramdisk.
> add ramdisk to test_snapshot_resume_latency

- CHANGELOG.md
- docs/seccompiler.md
- src/seccompiler/src/backend.rs
- src/seccompiler/src/compiler.rs
- src/seccompiler/src/seccompiler.rs
- tests/integration_tests/security/test_custom_seccomp.py
- tests/integration_tests/security/test_seccomp.py
This commit fixes https://github.com/firecracker-microvm/firecracker/issues/2585, adds a check to deny filters that have the same on-match and default actions and removes support for rule-level actions.
See details on why we are removing rule-level actions below:
Until now, a filter consisted of a default action, a filter action and an array of rules.
Each of these rules can have an optional rule-level action, that, when it matches, overrides the filter-level action.
This can be useful sometimes, when debugging or for some advanced filters. For example, you could specifically kill the process when you get an exec() call, instead of trapping, which would be the filter-level action.
Firecracker does not use this option, and there are no real use cases I can think of, where this is …
> seccompiler: remove rule-level actions and other fixes

- src/rate_limiter/src/lib.rs
- src/rate_limiter/src/persist.rs
- tests/integration_tests/functional/test_drives.py
Fixes https://github.com/firecracker-microvm/firecracker/issues/2176
The firecracker rate-limiter implementation leans more on efficiency at the expense of accuracy. Even so, the accuracy can be improved without performance penalties.
Firecracker rate-limiter is a passive implementation driven by the consumer. Each time `X` tokens go through it, the rate-limiter:
1. calculates how much time has passed since last operation
2. replenishes its budget based on elapsed time above
3. attempts to allow `X` if it fits the budget
Because we don't want to incur the cost of floating point operations the operation in `step 2` is a non-floating point division which loses precision:
```rust
// At each 'time_delta' nanoseconds the bucket should refill with:
refill_amount = (time_delta * size) / …
```
> rate-limiter: increase limiter precision

- resources/seccomp/aarch64-unknown-linux-musl.json
- resources/seccomp/x86_64-unknown-linux-musl.json
Fixes #962 
`TimerFd`s are used by rate-limiters, metrics, and balloon device.
Since #1494, #1735 and #1736, all of them are created before boot, thus before seccomp filters are applied.
This means we don't need `timerfd_create` syscall on our allow-list, and can be removed to tighten it.
> seccomp: remove timerfd_create from allow-list

- .cargo/config
- Cargo.lock
- src/arch/Cargo.toml
- src/arch/src/aarch64/fdt.rs
- src/libfdt-bindings/Cargo.toml
- src/libfdt-bindings/build.rs
- src/libfdt-bindings/src/lib.rs
- tests/integration_tests/build/test_coverage.py
- tests/integration_tests/performance/test_process_startup_time.py
- tools/devctr/Dockerfile.aarch64
- tools/devtool
fix libfdt linking when compiled using `-fstack-protector`
As part of #2579 we pushed a commit that involved compiling libfdt using `-fno-stack-protector` in order to workaround https://github.com/rust-lang/rust/issues/79791 .
This is a cleaner fix that enables us to compile firecracker using rust toolchain 1.52.1 even when libfdt is compiled using `-fstack-protector`
> fix libfdt linking when compiled using -fstack-protector

- docs/prod-host-setup.md
Running with the host kernel command line parameter `console=AMA0` on `aarch64` was degrading the snapshot restore latency from 3ms to 8.5ms.
Added an entry in the snapshot performance known issues to highlight this behavior.
> Updated snapshot docs with ARM kernel parameter induced latency

- src/firecracker/src/main.rs
- tests/framework/microvm.py
- tests/integration_tests/security/test_seccomp.py
We didn't have a test that checked the runtime warning logged for using `--seccomp-level`.
Add a check that verifies the existence of the warning
> test seccomp-level deprecation warning

- src/vmm/src/rpc_interface.rs
- tests/integration_tests/functional/test_api.py
- tests/integration_tests/functional/test_snapshot_basic.py
allow diff snapshots on on uVMs with vsock devices
After implementing #2574 we track the dirty memory used by the vsock device so we should allow diff snapshots on on uVMs with vsock devices
> allow diff snapshots on on uVMs with vsock devices
